### ISSUE TITLE
Superclass calls fail when combined with conditional class compilation

### ISSUE THREAD

**Issue by haael** [brython-dev/brython#100]
Python has a super() call. It works in Brython.

Python allows to compile classes conditionally. You can put an if statement on class level and put a method definition inside. It also works in Brython.

However, those two features don't work in Brython when combined. This code fails in Brython while working in Python3:

    class A:
        if True:
            def aaa(self, x):
                pass
    
    class B(A):
        if True:
            def aaa(self, x):
                super().aaa(x)
    
    b = B()
    b.aaa(0)

The error message will say: "RuntimeError: TypeError: self._ _thisclass__ is undefined".

**Comment by olemis** [comment]
At least for me there's something weird with your sample code . What happens if you use `class A` and `class B(A)` instead of `def` statements ? Does this code really work in Python 3 ? This is what I get

```python
>>> def A:
  File "<stdin>", line 1
    def A:
         ^
SyntaxError: invalid syntax
>>>     if True:
  File "<stdin>", line 1
    if True:
    ^
IndentationError: unexpected indent
>>>         def aaa(self, x):
  File "<stdin>", line 1
    def aaa(self, x):
    ^
IndentationError: unexpected indent
>>>             pass
  File "<stdin>", line 1
    pass
    ^
IndentationError: unexpected indent
```

**Comment by haael** [comment]
Sorry. There should be 'class' instead of 'def' of course. Edit made.

**Comment by PierreQuentel** [comment]
Thanks for the report !
