### ISSUE TITLE
Web component ???

### ISSUE THREAD

**Issue by Mohamed-Kaizen** [brython-dev/brython#1002]
Can brython do something  like this:
Class My comp extends HTMLElement{
Constructor (){...}
ConnectedCallback (){...}
disconnectedCallback (){...}
}

basically making Web components  with brython

**Comment by Ordiel** [comment]
https://github.com/brython-dev/brython/issues/27

**Comment by PierreQuentel** [comment]
Sorry for the very late reaction to this issue, I was not familiar with the Web Component technology.

I have taken a little time to teach myself the basics, and in the commit referenced above I have implemented it through a new module, __`browser.webcomponent`__, which exposes a class `WebComponent` used as a metaclass to define custom HTML tags and their behaviour. I have written a short [documentation page](https://github.com/brython-dev/brython/blob/master/www/doc/en/webcomponent.md) and added an example in the gallery (__`webcomponent.html`__).

Can you take a look and tell me what you think ?

**Comment by Ordiel** [comment]
Good documentation; its good to mention that I am not precisely that well versed on the web technologies world, but for the little I know I really like what I am seeing 

I am anxious to give it a try, is it in a build I can pull, or better folder to download?

**Comment by PierreQuentel** [comment]
The standard way of getting the current development version is first to do `git clone` to get a local copy of the repository, and `git pull` to update to the latest commit.

If you are not familiar with git, you can also download a zip file with the links "Clone or download / Download ZIP" from the Brython Github home page.

**Comment by Ordiel** [comment]
what would I need to do if I wanted to create a package for local testing (as the ones in the download page)?

I tried by going into the `npm` dir and running `npm link` but the package it created was empty (I went through both the readme and contributing documents but there is no mention on how to achieve this.

Thanks in advance Pierre

**Comment by Mohamed-Kaizen** [comment]
> Sorry for the very late reaction to this issue, I was not familiar with the Web Component technology.
> 
> I have taken a little time to teach myself the basics, and in the commit referenced above I have implemented it through a new module, **`browser.webcomponent`**, which exposes a class `WebComponent` used as a metaclass to define custom HTML tags and their behaviour. I have written a short [documentation page](https://github.com/brython-dev/brython/blob/master/www/doc/en/webcomponent.md) and added an example in the gallery (**`webcomponent.html`**).
> 
> Can you take a look and tell me what you think ?

thanks it work, sorry for the very late replay

**Comment by Ordiel** [comment]
When will this be officially released? (latest version is still 3.7.3)
