### ISSUE TITLE
__name__ should not be an attribute of bool values, int names

### ISSUE THREAD

**Issue by tjnaughton** [brython-dev/brython#1007]
Salut,

For compatibility with Python 3.7, the code:

```
print(True.__name__)
```

should raise "AttributeError: 'bool' object has no attribute '__name__'", but it does not with Brython 3.7.0.

It is a similar case with names with int/bool values (each line below should raise an AttributeError):

```
a = 7; print(a.__name__)
a = True; print(a.__name__)
```

Merci!

**Comment by PierreQuentel** [comment]
Many thanks, this one was not so easy to fix !

There was a bug in the implementation of special attributes of classes. It also applied to user-defined classes:
```python
class A:
    pass

A().__name__ # would return "A" instead of raising AttributeError
```
I found this example on stackoverflow:
```python
class A:
    __name__ = "foo"

A.__name__ # should be "A", ok for Brython
A().__name__ # should be "foo", Brython gave "A"
```
The implementation change needed to make Brython return the correct values have consequences on many scripts; `__name__` was an attribute of the Javascript object representing a Python class, I have introduced another attribute `$infos` (as for functions) and the class name is now `A.$infos.__name__`
