### ISSUE TITLE
Use https instead of http for external media includes in the gallery

### ISSUE THREAD

**Issue by niekas** [brython-dev/brython#1014]
When I open https://brython.info/gallery/three.html page using Firefox I get this error in console:

```
Blocked loading mixed active content “http://cdnjs.cloudflare.com/ajax/libs/three.js/r79/three.min.js”[Learn More]
three.html
Loading failed for the <script> with source “http://cdnjs.cloudflare.com/ajax/libs/three.js/r79/three.min.js”. three.html:5:1
start ...
brython.js:5614:49
Error: brython.js line 7073 > eval:31:340
Traceback (most recent call last):
  module __main__ line 5
    THREE = window.THREE
AttributeError: no attribute THREE for [object Window]
```
This error would be gone if the Javascript import source `http://cdnjs.cloudflare.com/ajax/libs/three.js/r79/three.min.js` would be changed to `https://cdnjs.cloudflare.com/ajax/libs/three.js/r79/three.min.js` as suggested in https://stackoverflow.com/a/18320348.

In addition, when I open `http://cdnjs.cloudflare.com/ajax/libs/three.js/r79/three.min.js` in the browser it automatically redirects to `https://cdnjs.cloudflare.com/ajax/libs/three.js/r79/three.min.js`.

**Comment by PierreQuentel** [comment]
Thanks for the report !
