### ISSUE TITLE
shlex is missing

### ISSUE THREAD

**Issue by jstafford** [brython-dev/brython#1022]
Went to http://raspberry-python.blogspot.com/2013/08/a-python-interactive-console-in-my-blog.html to read a little about Brython, tried to follow the little tutorial on that page. When I typed 
`import webbrowser` into the console, I got the following error:
```Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 6, in <module>
 ImportError: No module named shlex
```
Reproduced the same behavior at https://brython.info/tests/console.html?lang=en 
So either shlex needs to be added, or webbrowser should be removed.

**Comment by PierreQuentel** [comment]
@jstafford 
Thanks for the report. I added module __`shlex`__ in commit afcbcfe02a613a04660ad35214263130641061d9 and rewrote __`webbrowser`__ in commit a21df34953f4f2b01a8310defdf6ed2f13b39353 to adapt it to the context of a browser, where registering another browser is meaningless.
