### ISSUE TITLE
Vue demo is not that "pythonish"

### ISSUE THREAD

**Issue by chiboreache** [brython-dev/brython#1031]
Hi!

I just want to make some calculations with input data, and output it through Vue(Nuxt to be precise) how can I do that? Simple return doesn't work

Btw with external js file it would be really handy ;)

Since in vue-demo we can only see something like that 
```python
def reverse_message(ev):
    this().message = ''.join(reversed(this().message))
```
which is not that helpful `~_~`

**Comment by PierreQuentel** [comment]
@chiboreache I'm sorry but I don't understand which improvement you propose to which feature in Brython, nor how they are related to the issue title. Can you give more information ?

**Comment by chiboreache** [comment]
I mean:

> vue.js (framework for user interfaces)
```
...
})

def reverse_message(ev):
    this().message = ''.join(reversed(this().message))

app5 = Vue({
....
```

it doesn't look like a valid python code
so it doesn't compile in Vue(Nuxt) template file either

**Comment by PierreQuentel** [comment]
What makes you say it is not valid Python ? CPython 3.7 doesn't complain: 

```
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> def reverse_message(ev):
...     this().message = ''.join(reversed(this().message))
...
>>>
```

**Comment by chiboreache** [comment]
Hmm..

`from javascript import this`

I'm ok now ;)
*Sorry for my inattention*
