### ISSUE TITLE
import requests available?

### ISSUE THREAD

**Issue by rashearth** [brython-dev/brython#1032]
Hi, first of all, thank you so much for the wonderful application.
I have one question using it.
I cannot use the "import requests" for the brython.
it just gives error.

could you kindly tell me if Brython could also use "import requests"?

Thank you

**Comment by PierreQuentel** [comment]
Hi,

Short answer : no :-(

The CPython package __`requests`__ is used to interact (send requests, get responses) from servers on Internet. In a browser, for security reasons, you can only send / get Ajax requests to urls in the same domain, or to servers that accept cross-domain requests.

Besides this, __`requests`__ uses the low-level OS stacks for communication on Internet (sockets), which are not available in a browser.
