### ISSUE TITLE
SyntaxError has no __name__

### ISSUE THREAD

**Issue by schmave** [brython-dev/brython#1039]
This test fails:

```python
try:
    eval('"asdf')
except Exception as e:
    assert getattr(e, '__name__', None) == 'SyntaxError'
```

It seem that it was broken by commit f9a038bfb252d6b42ca8b634b5d5b3c9e5bb2d6a

**Comment by PierreQuentel** [comment]
If the test passed before commit f9a038b it was a bug : it doesn't pass with CPython. `e` is a `SyntaxError` _instance_, which doesn't have an attribute `__name__`. This test works both for CPython and Brython: 

```python
try:
    eval('"asdf')
except Exception as e:
    assert getattr(type(e), '__name__', None) == 'SyntaxError'
```

**Comment by schmave** [comment]
Ah, my mistake! Thanks for looking into it, @PierreQuentel.
