### ISSUE TITLE
list sort returns the list instead of None under certain circumstances

### ISSUE THREAD

**Issue by tiggerntatie** [brython-dev/brython#1045]
Under 3.7.1:

In general, when calling the sort method of a list, None is returned, as it should be (see brython-dev/brython#307 from almost four years ago!). However, when calling the sort method of a list that is the result of adding two lists together, a sorted list is still returned.

```
a = ["a"]
b = ["b"]
print(a.sort())
print((a+b).sort())
print(type(a))
print(type(a+b))
```
Produces the following output:

```
None
['a', 'b']
<class 'list'>
<class 'list'>
```

**Comment by PierreQuentel** [comment]
Merci Eric !
