### ISSUE TITLE
chr(8364) returns Ⴌ instead of €

### ISSUE THREAD

**Issue by mcorne** [brython-dev/brython#1047]
chr(8364) returns Ⴌ instead of €

**Comment by PierreQuentel** [comment]
Sorry, I can't reproduce this bug, for me `print(chr(8364))` prints € on Firefox, Edge and Chrome (on Windows 10) and on my Android smartphone. In which configuration do you get Ⴌ ?

**Comment by mcorne** [comment]
I guess that's what I'm doing that's causing the issue. Unfortunately, I'm both a Python and Brython newbie so I don't know why. Please, check out the piece of code below just in case you could spot anything and feel free to close the case if that really bugs you.

Basically, I get a piece of Python code, ex print(char(8364)), from a web page textarea with the ID "code", then I run exec(document["code"].value), then I capture the result from the stdout which I put in document["result"].innerHTML.
You can try it out live at https://micmap.org/python-by-example/ and select the chr function when everything is loaded. The code excerpt below comes from the execute_python.py file in https://github.com/mcorne/python-by-example. (This is simple project that I'm doing to learn Python functions which I'll share with others at some point.)

```python
from browser import document
import sys
from io import StringIO
import contextlib

@contextlib.contextmanager
def stdoutIO(stdout=None):
    old = sys.stdout

    if stdout is None:
        stdout = StringIO()

    sys.stdout = stdout
    yield stdout
    sys.stdout = old

def eval_code(event):
    with stdoutIO() as s:
        try:
            exec(document["code"].value)
        except BaseException as e:
            print(e)

    document["result"].innerHTML = s.getvalue().replace('&','&amp;').replace('<','&lt;').replace('>','&gt;').replace('"','&quot;')

document["execute"].bind("click", eval_code)
```

**Comment by schmave** [comment]
Perhaps the bug is in StringIO. This snippet prints "Ⴌ" for me in the Brython console:

```python
from io import StringIO
s = StringIO()
s.write(chr(8364))
print(s.getvalue())
```

**Comment by PierreQuentel** [comment]
@mcorne The commit referenced above fixes the issue mentioned by @schmave, so it should fix the issue ; can you confirm ?

**Comment by mcorne** [comment]
Forgive me for asking but how do I check that?

**Comment by PierreQuentel** [comment]
You can test by temporarily replacing __brython.js__ and __brython_stdlib.js__ in your Brython-3.7.1 directory by the latest version in this development repository : [brython.js](https://raw.githubusercontent.com/brython-dev/brython/master/www/src/brython.js), [brython_stdlib.js](https://raw.githubusercontent.com/brython-dev/brython/master/www/src/brython_stdlib.js) (right-click on the links and select "Save link target as...")

**Comment by mcorne** [comment]
That works fine with the latest dev version.

**Comment by ch-yx** [comment]
I tried this:
`chr(128512)==chr(62976)`
and it was true.🤔

**Comment by PierreQuentel** [comment]
@ch-yx Thanks for reporting, the commit referenced above should fix this bug.

**Comment by ch-yx** [comment]
> 
> 
> @ch-yx Thanks for reporting, the commit referenced above should fix this bug.

thank you.
and I fuond that `"😀"=="\ud83d\ude00"`.


and please know that your site (brython.info) have been banned in China mainland.
please connect OVH SAS or consider setting up a mirrorsite.

and i need your help in #1176 .I'm not sure if I did everything correctly.
