### ISSUE TITLE
delattr does not remove attribute

### ISSUE THREAD

**Issue by mcorne** [brython-dev/brython#1048]
class Foo:
    bar = 1
foo = Foo()
delattr(foo, 'bar')
print(foo.bar)

returns 1 instead of exception AttributeError: bar

**Comment by mcorne** [comment]
Please reopen this issue as it is not fixed, thx.

**Comment by PierreQuentel** [comment]
I can't reproduce the bug. With the latest development version: 
```python
class Foo:
    bar = 1
foo = Foo()
delattr(foo, 'bar')
print(foo.bar)
```
gives the same error message as CPython:
```
Traceback (most recent call last):
  module __main__ line 4
    delattr(foo, 'bar')
AttributeError: bar
```

and so does this code (deleting the attribute of class `Foo`, not of the instance)
```python
class Foo:
    bar = 1
foo = Foo()
delattr(Foo, 'bar')
print(foo.bar)
```
which raises
```
Traceback (most recent call last):
  module __main__ line 5
    print(foo.bar)
AttributeError: 'Foo' object has no attribute 'bar'
```
