### ISSUE TITLE
brython({debug:10}) not recognized

### ISSUE THREAD

**Issue by cforger** [brython-dev/brython#105]
Hello,

Setting debug:10 doesn't dump the JS code as stated in the docs

 Line 7620 of Brython.js states:

if($B.$options.debug==10 && module.name=='_thread'){console.log('code for module '+module.name)

This seems to me why setting debug doesn't work. I set it to this:

if($B.$options.debug==10){console.log('code for module '+module.name)

and it works. Perhaps that is all that is needed?

**Comment by PierreQuentel** [comment]
Thanks for the report and for finding where the bug was
