### ISSUE TITLE
Equivalent sets not recognised as equivalent

### ISSUE THREAD

**Issue by tjnaughton** [brython-dev/brython#1052]
Hi,

In the Brython 3.7.1 console
````
>>{2, 1}
{2, 1}
````
but with Python 3.7
````
>>{2, 1}
{1, 2}
````
This subtle difference has a concrete effect in expressions such as
````
>>{tuple({1, 2}), tuple({2, 1})}
````
where Brython returns {(1, 2), (2, 1)} and Python returns {(1, 2)}. Thanks for your amazing project!

**Comment by PierreQuentel** [comment]
Thanks for the report, I misinterpreted the "non-ordered" character of sets. 

The fix introduces another slight difference with Python : the iteration order of a set with strings will always be the same, while in Python the hash value of strings may change at each run, making the iteration order unpredictable.

**Comment by tjnaughton** [comment]
Wow, great. I think we can all live with this new slight difference for the moment; it will only become a problem if/when Brython becomes a more popular target for Python programmers than cpython and people begin to rely on that predictable behaviour. :-)
