### ISSUE TITLE
How do I run the generated Javascript?

### ISSUE THREAD

**Issue by gilch** [brython-dev/brython#1055]
I tried out the editor page: http://brython.info/tests/editor.html?lang=en

If I click the `Javascript` button, it compiles the default program from the left pane and shows output that begins with
```
var $B = __BRYTHON__;
var $bltns = __BRYTHON__.InjectBuiltins();eval($bltns);

var $locals = $locals___main__;
```
If I paste that line-by-line into the browser js console, it crashes on that last line with the error
```
ReferenceError: $locals___main__ is not defined
```
The generated Javascript code is not sufficient to actually run the program, even with `__BRYTHON__` present.

Brython's public interface `brython()` seems only to be for the `<script>` tags, useful, but not enough to replace all uses of Javascript in the browser. I would like to be able to use the compiled Javascript in a bookmarklet or in the web console, or be able to evaluate Python strings from a Javascript function that I can use in a bookmarklet and in the console.

I've been experimenting with injecting developer tools into the page using a bookmarklet to make the Brython development experience more interactive like normal Python is. I'd like to be able to run new Python code without re-running all the `text/python3` tags in the page, so `brython()` is out. (Javascript can do this.) I knew there must be a way to compile to Javascript, since the editor does it. Using the `py2js` internal function does it (and it's harder than a good public interface would be, but at least I could implement one myself) but I can't actually eval the resulting Javascript because it crashes with that reference error.

**Comment by gilch** [comment]
After reading the documentation more carefully, I found the `ipy_id` argument for `brython()`, which should at least allow me to execute one script tag in particular instead of re-running all of them.

However, if I try the following in the browser Javascript console, on a test page that loads Brython from cdn (per "zero-install option" in the readme)
```
e = document.createElement("script")
e.type = "text/python3"
e.id = "spameggs"
e.innerHTML = "print('Hello, World!')"
document.documentElement.appendChild(e)
brython({debug:1,ipy_id:['spameggs']})
```
Then I still get the same error.
```
ReferenceError: "$locals___main__ is not defined"

    <anonymous> https://cdnjs.cloudflare.com/ajax/libs/brython/3.7.1/brython.min.js line 1 > eval:4 _run_scripts https://cdnjs.cloudflare.com/ajax/libs/brython/3.7.1/brython.min.js:1 brython https://cdnjs.cloudflare.com/ajax/libs/brython/3.7.1/brython.min.js:1 <anonymous> debugger eval code:1 

brython.min.js:1:218962
Javascript error ReferenceError: "$locals___main__ is not defined"

    <anonymous> https://cdnjs.cloudflare.com/ajax/libs/brython/3.7.1/brython.min.js line 1 > eval:4 _run_scripts https://cdnjs.cloudflare.com/ajax/libs/brython/3.7.1/brython.min.js:1 brython https://cdnjs.cloudflare.com/ajax/libs/brython/3.7.1/brython.min.js:1 <anonymous> debugger eval code:1 

brython.min.js:1:219076
Traceback (most recent call last):
undefined: ReferenceError: $locals___main__ is not defined brython.min.js:1:254237
Error
```

**Comment by schmave** [comment]
I think you should call the JS function `python_to_js` instead of `py2js`. This works for me:

```html
<script type="text/javascript" src="path/to/brython.js"></script>
<script type="text/javascript">
eval(__BRYTHON__.python_to_js('x = 5; print(x);'));
</script>
```

**Comment by gilch** [comment]
Thanks, that works for me too. The missing element that `python_to_js()` adds to the JS translation seems to be the
```
$locals___main__ = {}
```
Just an empty object. (I thought I had tried that already, and got some "t equals null" error, but I can't seem to reproduce it.) Now creating that as a global seems to enable the `ipy_id` approach as well.

I feel like this could be documented better.

But it's enough to get Brython bookmarklets running on pages that have `__BRYTHON__`. For example, this very minimal Brython console
```
javascript:eval(__BRYTHON__.python_to_js("\
from browser import document as d\n\
b=d.createElement('textarea')\n\
b.style={'position':'fixed','bottom':'0px'}\n\
def k(e,n={},r=None):\n\
 if e.keyCode==13and e.shiftKey:\n\
  e.preventDefault()\n\
  print('>>>',b.value)\n\
  try:r=eval(b.value,n)\n\
  except SyntaxError:exec(b.value,n)\n\
  print(repr(r))\n\
  b.value=''\n\
b.bind('keypress',k)\n\
d.documentElement.appendChild(b)\n\
"))
```
This lets me mess around with the DOM using Brython instead of JS, without adding an extra script tag to every page. That's getting close to the interact() functionality I wanted in #853. It would be nice to get `pdb` working too. That console has its own namespace.

**Comment by desean1625** [comment]
@gilch if you don't need access to the DOM here is an example that I have transferring inputs and outputs to and from brython running in a webworker. But since you are creating elements it's probably not what you need, but the code in the executor will run outside of a webworker

https://codesandbox.io/s/brython-in-webworker-ss03z
