### ISSUE TITLE
Performance in Firefox much slower than in Chromium

### ISSUE THREAD

**Issue by andresmrm** [brython-dev/brython#106]
Hello, you all! And thanks for this AMAZING project! =D

I'm doing a little multiplayer real-time game with Brython (maybe the worst use case for now =P ), but I noticed that the FPS in Chromium hardly goes below 59, while in Firefox it easly falls to 10. That saddens me a little for I prefer FF to Chromium... Any idea if it's FF "fault", or something related to Brython? And, does Brython translates the code before the execution, like CoffeScript? (I guess not, but didn't find anything about)

You can "play" the game here:
http://amoamo-bosque.rhcloud.com:8000
You can connect with more than one browser and see the little bunnies running around, if you have luck. Arrows to move, "c" to plant a tree. It's still in pre-pre-pre-alfa... and probably will never get much farther than that. =P
Code here:
https://github.com/andresmrm/brython-experiment
It uses  Flask + Websockets + Phaser (image&phys) + Howler (sound).
It was really painfull to interface Brython with Phaser, but at least not impossible. =)

**Comment by Ernest0x** [comment]
Hello,

Perhaps it would be useful to use the developer tools that are built in firefox to record javascript calls and see where most time is spent and whether the measured times are reasonable for each function call.

**Comment by JamesHutchison** [comment]
Brython code is compiled to javascript, which is why it has that long delay on load.

If you can reduce it down to a simple test case that highlights the speed difference, that would be helpful. One idea might be to remove all of the Brython logic except the bare minimum needed to get the FPS and see if there is still a large discrepancy, then go from there.

**Comment by juancarlospaco** [comment]
This is case-specific, and not general to the code of Brython itself, can it be Closed :grey_question:

**Comment by andresmrm** [comment]
Sorry for not answering before. Yes, I think you are right. I'm using other libs, so maybe it's a problem with them.

**Comment by kikocorreoso** [comment]
@andresmrm I tested that today on Chromium (Version 40.0.2214.93) and FF (35.0.1). On Chromium I get a stable 60fps rate. In FF I get around 30-40 irregular fps rate.

Sadly, some stuff will be faster or slower depending the browser. For instance, `for` loops are really fast on FF (even Brython `for` loops are faster on FF than on CPython),...
