### ISSUE TITLE
str(bytes('abc', encoding='ascii'), encoding='ascii') returns [object Object]

### ISSUE THREAD

**Issue by mcorne** [brython-dev/brython#1060]
print(str(bytes('abc', encoding='ascii'), encoding='ascii'))
returns [object Object] instead of 'abc'

**Comment by mcorne** [comment]
Please reopen this issue as it is not fixed, thx.
I changed 'abc' with 'pythôn'.
It returns [object Object] instead of 'pythn'.
The accent seems to be causing an issue.
I just tried with 3.7.2-dev.

**Comment by PierreQuentel** [comment]
Maybe there is a problem with the version you are using ? In the current development version, the result of the first example is the expected string `'abc'`, and the second raises the same exception as CPython: 

```
Traceback (most recent call last):
  module __main__ line 1
    print(str(bytes('pythôn', encoding='ascii'), encoding='ascii'))
UnicodeEncodeError: 'ascii' codec can't encode character 0x4 in position undefined
```

**Comment by mcorne** [comment]
Oops, I forgot the "ignore" param. Sorry about that. Here is what I meant:
print(str(bytes('pythôn', encoding='utf-8'), encoding='ascii', errors='ignore'))
returns [object Object] instead of 'pythn'.

**Comment by PierreQuentel** [comment]
Ok, I have fixed this issue. Thanks again !
