### ISSUE TITLE
import unicodedata

### ISSUE THREAD

**Issue by mvallet91** [brython-dev/brython#1061]
I'm using Brython for a project and I need to use the *unicodedata* module, however, _import unicodedata_ throws an error on my console. 

It's also not available in the test console (http://brython.info/tests/console.html), but I see it is mentioned in *brython_stdlib.js* and there are unit tests for it. Is there a different way to use it?

**Comment by PierreQuentel** [comment]
@mvallet91  Thanks for reporting this. 

__unicodedata__ has never been included in Brython ; the CPython module is not written in Python so it can't be included "as is". In the commit referenced above, I have added a Javascript module that implements a good part of the CPython module.

**Comment by mvallet91** [comment]
Awesome! thanks for the commit and Brython in general
