### ISSUE TITLE
`browser.ajax.post()` does not work

### ISSUE THREAD

**Issue by niekas** [brython-dev/brython#1066]
`browser.ajax.get(url)` - this API call reaches its destination. However`browser.ajax.post(url)` silently does nothing. I have tried calling `browser.ajax.post` with various parameter values (e.g. `headers={}`, `data={'1': '2'}`) but without any success.

**Comment by PierreQuentel** [comment]
Can you give an example that doesn't work ? The one in the gallery works for me.

**Comment by niekas** [comment]
Sorry, I forgot to post CSRF_TOKEN. Everything works as expected. Sorry for my mistake.

**Comment by vivekest** [comment]
Hi Niekas, how did you fix this, how did you find and mention the CSRF_TOKEN in Ajax in Brython? Would you mind sharing relevant piece of code? Thanks :)

**Comment by vivekest** [comment]
> Sorry, I forgot to post CSRF_TOKEN. Everything works as expected. Sorry for my mistake.

Hi Niekas, how did you fix this, how did you find and mention the CSRF_TOKEN in Ajax in Brython? Would you mind sharing relevant piece of code? Thanks :)
