### ISSUE TITLE
Speed of partial imports

### ISSUE THREAD

**Issue by andy31lewis** [brython-dev/brython#1067]
Hi again

As I add more code to my module, so it becomes slower to import, until it now takes from 1 to 3 seconds depending on the speed of the processor in the device.  I assume this is the time taken to compile it from Python into Javascript.

However, if I use `from module import class` to import a single class which is just 6 lines long and has no dependencies, the time remains unchanged - ie it seems the whole module still gets compiled.

Is this something which it is possible to improve? If it is an inevitable feature of the way Brython works, I will look at ways to split the module into smaller chunks which can be imported separately depending on what functionality is needed.

Thanks in advance.

**Comment by gilch** [comment]
In CPython it's the same. The whole module must be executed before you can read objects from its __dict__. Changing this behavior would reduce compatibility with existing Python libraries.

I do think splitting the module is the best approach.

**Comment by PierreQuentel** [comment]
I'm sorry to ask, but did you try to build a __brython_modules.js__ using the CPython brython package, as explained in [this page](http://www.brython.info/static_doc/en/import.html) ?

**Comment by andy31lewis** [comment]
Hi, @PierreQuentel ,

I thought building brython_modules.js only built a smaller file for imports from the Python standard library. I am asking about partial imports from my own module (brySVG) - ie rather than `import brySVG`, using `from brySVG import BezierObject` (for example). It seems there is no speed advantage in the second case because the whole module gets compiled even if it is not needed.  But don't worry - at  the moment I am working on splitting the module into smaller chunks which can be imported separately.

**Comment by PierreQuentel** [comment]
The other advantage with __brython_modules.js__ is that the translation from Python to JS is stored in an indexedDB database, making imports much faster.

**Comment by andy31lewis** [comment]
I am closing this as I have now worked out how to split my module into smaller files, so that the end-user can just import the functionality they need rather than having to import the whole module. Your fix of #1083 was the final piece of the jigsaw needed to make this work - thank you!
(With regard to your point above, the creation of brython_modules.js is something that would have to be done by the end-user, as I don't know ahead of time what functionality they need.)
