### ISSUE TITLE
'__class__' is not defined

### ISSUE THREAD

**Issue by mcorne** [brython-dev/brython#1068]
class Class():
    def method(self):
      return __class__.__name__
print(Class().method())
return '__class__' is not defined
instead of Class

**Comment by PierreQuentel** [comment]
@mcorne 

It's hard to know exactly where the bug is because of formatting issues in your example, but this code works: 

```python
class Class:
    def method(self):
        return Class.__name__

assert Class().method() == "Class"
```

**Comment by mcorne** [comment]
Sorry about that, here it is again
`class Class():
    def method(self):
      return __class__.__name__

print(Class().method())`
