### ISSUE TITLE
b'\xff'.decode('utf-8') doesn't raise UnicodeDecodeError

### ISSUE THREAD

**Issue by schmave** [brython-dev/brython#1070]
```python
b'\xff'.decode('utf-8')
```

In CPython, this raises UnicodeDecodeError, but in Brython, it returns the string `'ÿ'`. I think this error was introduced in commit 94a065745b895734f39239bca0876b3e2ec8e2b6

**Comment by PierreQuentel** [comment]
It's strange, I think I could reproduce the bug yesterday, but after making a minor change referenced above which doesn't change the algorithm, the code you mention actually raises an exception. Can you check again ?

**Comment by schmave** [comment]
Yes, I think that fixes it. What I saw was that the JS exception raised by `decodeURIComponent` wasn't being handled. I guess there's something else that is still causing the PR build to fail, though.
