### ISSUE TITLE
updating __dict__ of object does not work.

### ISSUE THREAD

**Issue by earney** [brython-dev/brython#108]
The following code does not work in brython (but does work in python 3.x).  Most objects in python have a \__dict\__ variable that can be updated to add/update variables.     Should we think about creating a \__dict\__ variable for each new class/function or should we use some other approach to emulate this?
```
def funcattrs(**kwds):
    def decorate(func):
        func.\__dict\__.update(kwds)
        return func
    return decorate

class C(object):
       @funcattrs(abc=1, xyz="haha")
       @funcattrs(booh=42)
       def foo(self): return 42

print(C().foo(), 42)
print(C.foo.abc, 1)
print(C.foo.xyz, "haha")
print(C.foo.booh, 42)
```

**Comment by cforger** [comment]
Without much thought on it, I'd suggest following the Python method, and if that means creation of __dict__ then it should happen - I really like that Brython is trying to follow CPython as closely as possible. I'll trade a bit a performance for a proper reference implementation any day. 

However, I see most Brython objects already have __dict__ - When I create a class, it has __dict__ and adding to the class adds that to the __dict__

(from the brython.info console)
>>> class Panel():
...   pass
... 
>>> panel = Panel()
>>> panel.__dict__
{'__class__': <class 'Panel'>}
>>> panel.test_int =1
>>> panel.__dict__
{'__class__': <class 'Panel'>, 'test_int': 1}
>>> panel.__dict__['test_str']="string"
>>> panel.__dict__
{'__class__': <class 'Panel'>, 'test_int': 1, 'test_str': 'string'}
>>> panel.test_str
'string'
>>>

**Comment by cforger** [comment]
(oops.. I didn't escape _ _ d i c t _ _ - all tose references above are with the double-underscore

**Comment by earney** [comment]
Well maybe there is a problem somewhere else because the following does work:

```
class Panel:
    pass

panel=Panel()
panel.__dict__.update(a=1, b=2, c=3)
print(panel.__dict__)

outputs: {'__class__': <class 'Panel'>, 'name': 'a', 'value': 1}

```

But note that b and c are not added.  This is probably a bug.

Let me investigate this further, and I'll report my findings..

**Comment by earney** [comment]
I just noticed that the output should be:

{'\__class\__': <class 'Panel'>, 'a': 1, 'b':2, 'c':3}

so there are some serious issues here..   I'll investigate further.

**Comment by cforger** [comment]
Two things:

One:

 When I run your code under Python 3.3.4, / 3.4.1 I get:
{'a': 1, 'c': 3, 'b': 2}

as an answer, not what you have.

Two: 
 I just opened a dict issue - It's to do with a dict in a dict, but perhaps the lack of recursion in the py_dict creation routine is also causing some issues for you here.

**Comment by earney** [comment]
Thanks cforger..  I'll look into your issue.  Maybe if your issue is solved, that will help this issue.

**Comment by cforger** [comment]
Yeah, do that.. fix my problem first, and see if it fixed yours. :-)

**Comment by JamesHutchison** [comment]
Coincidentally I was working on refactoring `$MakeArgs` and I immediately recognize the name/value pairs as the artifact of a keyword object getting created.

Another dict bug I discovered last night is that this is possible:

```
dict(a=5, **{'a':7})
```

`$MakeArgs` also for some reason has the argument `$after_star`, but you are not allowed to provide positional arguments after a `*` value (syntax error) so it's not even used.

Really, the whole means of argument passing needs refactoring. It would probably eliminate bugs like this as well.

**Comment by cforger** [comment]
Hmm, I am currently also running into some weirdness with **kwargs type passing in classes and methods, but I haven't dug into it much - Perhaps what John is noticing is at the root of that as well.

**Comment by JamesHutchison** [comment]
To circle back on this, I think this is related to issue #90. By refactoring how objects are structured this wouldn't be an issue.

**Comment by PierreQuentel** [comment]
James,

You can't provide positional arguments after a `*` value, but you can pass a keyword argument : 

```python
def f(*a, b):
    print(b)

f(1,2,b=3)
```

If yu run this code in the editor and click on "show javascript" you will see that `MakeArgs1` is called with the last argument `$after_star` set

**Comment by JamesHutchison** [comment]
Hah, I never knew Python had key-word only args because I never use them.

**Comment by earney** [comment]
Same here..  There is a lot to be learned about python.  I've learned quite
a bit by looking at the unittests.  Many times, I've ran them because I
don't believe what I'm seeing (ie, there is no way that works, but it does).

For many cases, we'll have to make a call if we should support the
additional functionality or not.  I feel, if it does not compromise
performance, it should be fine.  If it does compromise performance,
hopefully it will occur only in the worst case scenario, and not the best
or average case.

Billy

**Comment by JamesHutchison** [comment]
Well, it's funny for me because I'm a professional python developer. In a decade of use, I've never come across it nor needed it.

I think for a lot of this it comes down to differences in implementation and javascript optimizations. A lot of this should just fit into place (and be fast) if we implement it the same way that CPython does. We shouldn't be fudging things to get the desired results, it should be a natural by-product of the implementation.
