### ISSUE TITLE
Exceptions when calling 0-argument methods in a chained subclass of built-in classes

### ISSUE THREAD

**Issue by YukkuriC** [brython-dev/brython#1081]
```python
class a(list):
    pass

class b(a):
    pass

test1=a([1,2,3])
test1.append(4)
print(test1)
test1.pop()
print(test1)
test2=b([1,2,3])
test2.append(4)
print(test2)
test2.pop()
print(test2)
```

and here's the output:
> [1, 2, 3, 4]
[1, 2, 3]
[1, 2, 3, 4]
Traceback (most recent call last):
RuntimeError: TypeError: Cannot convert undefined or null to object

The exception happens when b.pop is called, no idea what's going on

**Comment by PierreQuentel** [comment]
Thanks @YukkuriC for reporting this issue. AFAICT it only happens for subclasses of list subclasses, and for attributes that have the same name as Javascript Array objects, such as "pop".
