### ISSUE TITLE
Modifying a class's __bases__ doesn't work as in CPython

### ISSUE THREAD

**Issue by andy31lewis** [brython-dev/brython#1083]
This example (taken from [this StackOverflow page](https://stackoverflow.com/questions/8544983/dynamically-mixin-a-base-class-to-an-instance-in-python)) works as described in CPython, but in Brython it throws an exception `AttributeError: 'Person' object has no attribute 'introduce_self'`:
```python
class Gentleman(object):
  def introduce_self(self):
    return "Hello, my name is %s" % self.name

class Base(object):pass
class Person(Base):
  def __init__(self, name):
    self.name = name

p = Person("John")
Person.__bases__=(Gentleman,object,)
print(p.introduce_self())
# "Hello, my name is John"

q = Person("Pete")
print(q.introduce_self())
# Hello, my name is Pete
```
Thanks,
Andy

**Comment by PierreQuentel** [comment]
Merci @andy31lewis !
