### ISSUE TITLE
zlib compression/decompression doesn't do anything

### ISSUE THREAD

**Issue by numbermaniac** [brython-dev/brython#1099]
Using Python 3.7.3 installed on a computer:

```py
>>> import zlib
>>> zlib.compress(b'test')
b'x\x9c+I-.\x01\x00\x04]\x01\xc1'
>>> zlib.decompress(b'x\x9c+I-.\x01\x00\x04]\x01\xc1')
b'test'
```
Using the [Brython online console](http://brython.info/tests/console.html):
```py
>>> import zlib
>>> zlib.compress(b"test")
b'test'
>>> zlib.decompress(b'x\x9c+I-.\x01\x00\x04]\x01\xc1')
b'x\x9c+I-.\x01\x00\x04]\x01\xc1'
```

Brython's zlib just returns the input without compressing or decompressing it.

**Comment by PierreQuentel** [comment]
@numbermaniac Thanks for reporting this. The module was in Brython stdlib to avoid breaking other modules, but actually didn't do anything.
The pure-Python __Lib/zlib.py__ module now replaces the previous version in __libs/zlib.js__. It was great fun to write - working on Huffman coding brought me 40 years back in time :-) - and the deflate algorithmn is a masterpiece.
The module is limited in scope - for instance the input is not split in blocks - but it supports fixed and dynamic Huffman trees.
The big problem is performance, it can't be used in real world examples for the moment. I will try to improve the Python version, but my intention is to rewrite it in Javascript.

**Comment by PierreQuentel** [comment]
I have put one of the slowest functions (LZ items generation) to a Javascript module. The performance is still terrible, but a little less...
