### ISSUE TITLE
Chained additions generate large amount of JS code

### ISSUE THREAD

**Issue by schmave** [brython-dev/brython#1101]
The following code evaluates correctly, but gets compiled to 125KB of Javascript code. It seems that each subsequent addition operator doubles (or more?) the amount of code generated.

```python
x = 100
print(5 + x + x + x + x + x + x)
```

**Comment by PierreQuentel** [comment]
A long time ago I wrote a blog post called [Translating a + b](https://brythonista.wordpress.com/2015/03/01/translating-ab/). The generated code has changed a little since then but it explains the reason behind this very long Javascript code.

In other words, it's not possible (or at least I haven't found a way) to have at the same time a full compliance with Python, a decent speed and short code...

**Comment by schmave** [comment]
Thanks for that clear article, Pierre. 

`a + b` seems to be fine to me, but `x + y + z` starts to get out of hand. If `x`, `y`, and `z` are local variables, then `x + y + z` gets compiled to this:

(typeof $locals___main__["x"].valueOf() == "number" && typeof $locals___main__["y"].valueOf() == "number" && typeof $locals___main__["z"].valueOf() == "number" ? (typeof $locals___main__["x"] == "number" && typeof $locals___main__["y"] == "number" && typeof $locals___main__["z"] == "number" ? $B.add($B.add($locals___main__["x"],$locals___main__["y"]),$locals___main__["z"]) : new Number($B.add($B.add($locals___main__["x"],$locals___main__["y"]),$locals___main__["z"]))) : (typeof (typeof $locals___main__["x"].valueOf() == "number" && typeof $locals___main__["y"].valueOf() == "number" ? (typeof $locals___main__["x"] == "number" && typeof $locals___main__["y"] == "number" ? $B.add($locals___main__["x"],$locals___main__["y"]) : new Number($B.add($locals___main__["x"],$locals___main__["y"]))) : (typeof $locals___main__["x"] == "string" && typeof $locals___main__["y"] == "string") ? $locals___main__["x"]+$locals___main__["y"]: $B.$getattr($locals___main__["x"],"__add__")($locals___main__["y"])) == "string" && typeof $locals___main__["z"] == "string") ? (typeof $locals___main__["x"].valueOf() == "number" && typeof $locals___main__["y"].valueOf() == "number" ? (typeof $locals___main__["x"] == "number" && typeof $locals___main__["y"] == "number" ? $B.add($locals___main__["x"],$locals___main__["y"]) : new Number($B.add($locals___main__["x"],$locals___main__["y"]))) : (typeof $locals___main__["x"] == "string" && typeof $locals___main__["y"] == "string") ? $locals___main__["x"]+$locals___main__["y"]: $B.$getattr($locals___main__["x"],"__add__")($locals___main__["y"]))+$locals___main__["z"]: $B.$getattr((typeof $locals___main__["x"].valueOf() == "number" && typeof $locals___main__["y"].valueOf() == "number" ? (typeof $locals___main__["x"] == "number" && typeof $locals___main__["y"] == "number" ? $B.add($locals___main__["x"],$locals___main__["y"]) : new Number($B.add($locals___main__["x"],$locals___main__["y"]))) : (typeof $locals___main__["x"] == "string" && typeof $locals___main__["y"] == "string") ? $locals___main__["x"]+$locals___main__["y"]: $B.$getattr($locals___main__["x"],"__add__")($locals___main__["y"])),"__add__")($locals___main__["z"]));


What if instead you declared a helper function for adding two values:
```javascript
$B.add_two = function(a, b) {
	if (typeof a.valueOf() == “number” && typeof b.valueOf() == “number”) {
		if (typeof a == “number” && typeof b == “number”) {
			// ints
			return a + b
		} else {
			// floats
			return new $B.$FloatClass(a+b)
		}
	} else if (typeof a==”string” && typeof b==”string”) {
		// strings
		return a + b
	}
	return getattr(a,”__add__”)(b);
}
```

and then compiled `x + y + z` to this:

```javascript
$B.add_two($B.add_two($locals___main__["x"], $locals___main__["y"]), $locals___main__["z"])
```

You could also try compiling `x + y` to `$B.add_two($locals___main__["x"], $locals___main__["y"])` instead of inlining the logic. Not sure which would have better performance.

What do you think?

**Comment by PierreQuentel** [comment]
When I wrote the code for addition, I remember having tested a function call instead of inline code and found that there was a big difference in speed. I have tested it again and this time, the function code is even faster, so I have implemented your suggestion (with a minor change for long integers).

Many thanks !

**Comment by schmave** [comment]
Wonderful. Thanks for investigating and fixing this!
