### ISSUE TITLE
Question about PyGame Zero...

### ISSUE THREAD

**Issue by abixadamj** [brython-dev/brython#1105]
I am wondering if there is possibility to import pgzero module inside brython.If anyone can point me to some good direction, I would thank.

Adam

**Comment by kikocorreoso** [comment]
PyGame Zero depends on PyGame and Numpy. The dependencies have compiled extensions so you are not lucky.

You could try to use a JS game engine (https://github.com/collections/javascript-game-engines) and manage the game engine using Python via Brython. There are some examples of pixiJS on the mail list (https://groups.google.com/forum/?fromgroups=#!searchin/brython/pixi%7Csort:date).

Also, The [mail list](https://groups.google.com/forum/?fromgroups=#!forum/brython) is a better place for these kind of questions that are not brython issues 😃
