### ISSUE TITLE
math.log1p(x) same as math.log(1 + x)

### ISSUE THREAD

**Issue by mcorne** [brython-dev/brython#1111]
math.log1p(1e-5) should return 0.00000999995000033333 instead of 0.000009999950000398841
it looks like it's been implemented as math.log(1 + 1e-5) which returns 0.000009999950000398841 as well

**Comment by PierreQuentel** [comment]
Merci pour tous ces signalements !

Strangely, the result of the Javascript function `Math.log1p(1e-5)` is not exactly the same with Edge (0.00000999995000033333, like CPython) and with Firefox and Chrome (0.000009999950000333332)
