### ISSUE TITLE
math.gamma(2) should return 1

### ISSUE THREAD

**Issue by mcorne** [brython-dev/brython#1112]
it returns 1.999999999999998 instead

**Comment by PierreQuentel** [comment]
I rewrote the implementation of `math.gamma()`, the previous one gave wrong results. I have adapted the code found here : [https://en.wikipedia.org/wiki/Lanczos_approximation](https://en.wikipedia.org/wiki/Lanczos_approximation). It only works for real numbers (not complex) so far.

Thanks again !
