### ISSUE TITLE
dict_items and dict_keys are not set-like (regression)

### ISSUE THREAD

**Issue by schmave** [brython-dev/brython#1114]
The following tests in www/src/Lib/test/test_dict.py are failing because dict_items and dict_keys values do not support some set operations:

test_dictview_mixed_set_operations 
test_dictview_set_operations_on_items
test_dictview_set_operations_on_keys
test_errors_in_view_containment_check
test_itemiterator_pickling
test_items
test_iterator_pickling
test_keys
test_keys_contained
test_values
test_valuesiterator_pickling

I think that this bug was introduced in 42e7c95079dffbe7471cf59d76ac4823fcc11e4b.

The test "test_dictitems_contains_use_after_free" is failing because it is raising a "RuntimeError: dictionary changed size during iteration" exception. It didn't used to, and doesn't in CPython. I think that this new behavior may be consistent with [the documentation](https://docs.python.org/3.7/library/stdtypes.html?highlight=dict%20items#dictionary-view-objects) even though it is not consistent with CPython's implementation. If you agree, we could mark this test as skipped to get the build to pass.

**Comment by schmave** [comment]
Wonderful, thank you!

**Comment by PierreQuentel** [comment]
Thanks for the report and sorry for the regression :-(

The last test you mention failed because of a bug in membership testing : for "`x in e`", if there is an exception when calling `next(e)`, the exception should be ignored and the test returns `False`; in Brython the exception was raised.
