### ISSUE TITLE
json.dumps() got an unexpected keyword argument 'sort_keys'

### ISSUE THREAD

**Issue by mcorne** [brython-dev/brython#1117]
The following code sample should return formatted JSON instead of an error.
Note that it does not support the "separators" keyword argument either.
``` python
import json
print(json.dumps({'4': 5, '6': 7}, sort_keys=True, indent=4))

**Comment by PierreQuentel** [comment]
Merci Michel ! I replaced the very basic implementation based on the Javascript JSON object by the package in CPython standard library. The commit referenced above fixes this bug.
