### ISSUE TITLE
Creating a set does not remove duplicate values if they are floats (regression)

### ISSUE THREAD

**Issue by andy31lewis** [brython-dev/brython#1119]
Sorry, Pierre, here is another one:

The following snippet:
```python
L1 = [0, 10, 10, 20.0, 20.0, 40, 40.0, 60.0, 60, 80]
S = set(L1)
L2 = sorted(S)
print(L2)
```
gives `[0, 10, 20.0, 40, 60.0, 80]` in CPython, but `[0, 10, 20.0, 20.0, 40, 40.0, 60.0, 60, 80]` in Brython. (Note that one of the 10s has been removed, but if one or both of the duplicated pair are floats, neither is removed.)

This works correctly before commit aee1ce on Dec 1st last year.

**Comment by davidkwast** [comment]
```
david@david:~$ ipython
Python 3.7.3 (default, Apr  2 2019, 17:47:15) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.4.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: set([1.0,1.0,1.0])                                                      
Out[1]: {1.0}
```

```
Brython 3.7.2 on Netscape 5.0 (X11)
>>> set([1.0,1.0,1.0])
{1.0, 1.0, 1.0}
```

**Comment by PierreQuentel** [comment]
Thanks for the report - fortunately it's not as critical as the previous bug !
