### ISSUE TITLE
CPython tests take a very long time when they fail

### ISSUE THREAD

**Issue by mircea3** [brython-dev/brython#1132]
CPython tests finish very quickly when they pass, but can take a *very* long time when there is a failure, making it necessary to kill the browser process.

In Brython 3.7.0 the problem seems to be less pronounced; for example, a typical single test pass/fail takes 10/4200 ms.

In Brython 3.7.3 the failed test takes much longer; for example, two consecutive tests in `test_set`.

```
TestBasicOpsBytes  test_isdisjoint_empty  861  4      ok
TestBasicOpsBytes  test_iteration         885  54358  fail  line 889 - AttributeError: 'set iterator' object has no attribute '__length_hint__'
```
Therefore, in this particular case, it takes 4ms for the passed test, versus 54 seconds for the failed test. This long duration seems to happen with most, if not all, failed tests.

Browser: Palemoon v28.2.2 (2018-12-06) (Mozilla-based)

**Comment by PierreQuentel** [comment]
I noticed that, but I thought I was the only one to use these tests, so I postponed working on this issue ;-)

**Comment by mircea3** [comment]
Thank you, this last commit has lowered the execution time back to levels similar to those seen in v3.7.0 (slightly higher).
