### ISSUE TITLE
NameError is raised when providing default value to builtins

### ISSUE THREAD

**Issue by aure-olli** [brython-dev/brython#1133]
I have a problem with a module starting with
```python
try:
    set
except NameError:
    from sets import Set as set
```
Because of that, any further call to `set` will fail. Here is a minimal script reproducing the problem:
```python
if False:
	set = list
set()
```
Importing this script will result in `NameError: name 'set' is not defined`. This behavior is consistent in a function body, but not at the module level. This seems to be a consequence to solving the issue https://github.com/brython-dev/brython/issues/362

From my shallow understanding of Brython, the solution implemented here https://github.com/brython-dev/brython/blob/master/www/src/py2js.js#L4346 seems problematic.
```javascript
if($test){console.log("use check def")}
val = '$B.$check_def("' + val + '",' +
    scope_ns + '["' + val + '"])'
```
A call to `$search` instead seems to do the trick:
```javascript
if($test){console.log("use check def")}
val = '$B.$search("' + val + '")'
```
It has a consistent behavior for all the cases I can think about:
```python
if False:
	set = list
	var = True

def test1():
	return set()

def test2():
	if False: set = list
	return set()

def test3():
	return var
```
```
>>> test.test1()
set()
>>> test.test2()
UnboundLocalError: local variable 'set' referenced before assignment
>>> test.test3()
UnboundLocalError: local variable '$$var' referenced before assignmen
```

**Comment by PierreQuentel** [comment]
Thanks for the report and for taking the time to dig into the code :-)

Using `$search()` instead of `$check_def()` would work, but it's a more complex function so I think it would slightly reduce performance.

**Comment by aure-olli** [comment]
Oh I see that you've fixed the `$check_def` function. Thank you :)
