### ISSUE TITLE
struct format does not support spaces

### ISSUE THREAD

**Issue by aure-olli** [brython-dev/brython#1134]
The `struct` format does not allow spaces, whereas the documentation and CPython does:
```python
from struct import calcsize
calcsize('>4s c 15x 6l') # format from pytz
>>> StructError:   is not a valid format
```
This is due to the functions `getmode` and `getNum` not checking for whitespaces (https://github.com/brython-dev/brython/blob/master/www/src/Lib/_struct.py#L280). This implementation of `getNum` gets rid of middle spaces.
```python
def getNum(fmt,i):
    num=None
    cur = fmt[i]
    while cur == ' ':
        i += 1
        cur = fmt[i]
    while ('0'<= cur ) and ( cur <= '9'):
        if num == None:
            num = int(cur)
        else:
            num = 10*num + int(cur)
        i += 1
        cur = fmt[i]
    return num,i
```
Getting rid of end spaces will be little trickier because all the function use `getNum` like this:
```python
    while i<len(fmt):
        num,i = getNum(fmt,i)
        cur = fmt[i]
        [...]
        i += 1
```
I suggest either to systematically use `fmt = fmt.rstrip()`, either to change the behavior of `getNum`
```python
def getNum(fmt,i):
    num=None
    cur = fmt[i]
    while cur == ' ':
        i += 1
        cur = fmt[i]
    while ('0'<= cur ) and ( cur <= '9'):
        if num == None:
            num = int(cur)
        else:
            num = 10*num + int(cur)
        i += 1
        cur = fmt[i]
    i += 1
    while i < len(fmt) and fmt[i] == ' ':
        i += 1
    return num,i,cur
```
And use it like this
```python
    while i<len(fmt):
        num,i,cur = getNum(fmt,i)
        [...]
```

**Comment by PierreQuentel** [comment]
Thanks for reporting the issue. I took a more radical approach : in all the functions exposed by the module (`calcsize, pack, pack_into, unpack, unpack_from`) a function `_normalize()` is called on the format ; this function checks that there is no "illegal" whitespace (between a count and a format character) and removes all the other whitespaces.

I don't often use __`struct`__ so I may be missing side effects, if so please re-open the issue.

**Comment by aure-olli** [comment]
It works for me, thanks :)
