### ISSUE TITLE
Commit abf98cdf6 broke imports

### ISSUE THREAD

**Issue by aure-olli** [brython-dev/brython#1135]
While trying to test the latest version of `brython.js` (c22c74ca6), I realized that import where broken.
This is apparently due to commit abf98cdf6 checking for stdlib modules in the function `import_hooks`. It wrongly relies on the argument `from_stdlib`: https://github.com/brython-dev/brython/blob/c22c74ca64ea8a87e8453b782dbc3f2046326df4/www/src/py_import_hooks.js#L23-L31
Whereas `from_stdlib` is computed by: https://github.com/brython-dev/brython/blob/c22c74ca64ea8a87e8453b782dbc3f2046326df4/www/src/py_import.js#L892-L905
Because of that, any import in `Lib/` or `libs/` files are assumed to be stdlib imports, and thus won't be fetched, breaking any dependencies between `Lib/site-packages` modules. Removing the condition solves the problem. Changing the way `from_stdlib` is computed would be a better solution.

For instance:
`Lib/site-packages/test1.py`
```python
from test2 import test2
test1 = True
```
`Lib/site-packages/test2.py`
```python
test2 = True
```
`test.html`
```html
<script type="text/python3">
  from test1 import test1, test2
</script>
```
console
```
test2
    at Object._b_.ImportError.$factory (eval at $make_exc (http://localhost/brython/brython.js:7443:5), <anonymous>:71:321)
    at Object.import_hooks (http://localhost/brython/brython.js:13144:25)
    at $B.$__import__ (http://localhost/brython/brython.js:8964:60)
    at Object.$B.$import (http://localhost/brython/brython.js:8997:43)
    at eval (eval at run_py (http://localhost/brython/brython.js:8744:14), <anonymous>:14:12)
    at eval (eval at run_py (http://localhost/brython/brython.js:8744:14), <anonymous>:26:2)
    at run_py (http://localhost/brython/brython.js:8744:41)
    at exec_module (http://localhost/brython/brython.js:8856:41)
    at f (http://localhost/brython/brython.js:6217:30)
    at method (http://localhost/brython/brython.js:6221:58)
brython.js:8749 args ["No module named test2", __brython__: true, __class__: {…}]
brython.js:8749 __class__ {__class__: {…}, __mro__: Array(3), $is_class: true, $infos: {…}, $factory: ƒ, …}
brython.js:8749 $py_error true
brython.js:8749 $stack (2) [Array(4), Array(4)]
brython.js:8749 $line_info undefined
brython.js:8749 __cause__ {__class__: {…}}
brython.js:8749 __context__ {__class__: {…}}
brython.js:8749 __suppress_context__ false
brython.js:8749 name test2
brython.js:8750 Traceback (most recent call last):
brython.js:8751 message: undefined
brython.js:8752 filename: undefined
brython.js:8753 linenum: undefined
brython.js:5935 Traceback (most recent call last):
ImportError: No module named test2
```

**Comment by PierreQuentel** [comment]
Thanks, I forgot the case of imports from **Lib/site-packages**. It should be fixed now.

I keep the test to avoid useless imports from modules in the "real" stdlib. As much as possible I copy the modules from the CPython distribution, and some of them try to import modules written in C (for instance **`json.py`** tries "`import _json`" and defaults to the pure-Python version if not found). In Brython, imports are expensive because Ajax calls are made to all the possible locations ; since a module from the stdlib can only import from the stdlib itself, it's a performance issue to try locations that we know will fail.

**Comment by aure-olli** [comment]
I totally agree with you.
