### ISSUE TITLE
`python -m brython --modules` does not read `<script type="text/python3">`

### ISSUE THREAD

**Issue by aure-olli** [brython-dev/brython#1136]
When calling `python -m brython --modules`, `<script type="text/python3">` tags are not read.
Cause:
https://github.com/brython-dev/brython/blob/f9362a23808dd820bce2ed077a0cbb6358fe3041/setup/list_modules.py#L456
Solution:
```python
if key == 'type' and value in ("text/python", "text/python3"):
```

**Comment by PierreQuentel** [comment]
Good catch, thanks !

(this has to be the fastest fix in all Brython history :-)
