### ISSUE TITLE
`python -m brython --modules` does not recognize Lib/site-pacakges as packages

### ISSUE THREAD

**Issue by aure-olli** [brython-dev/brython#1137]
https://github.com/brython-dev/brython/blob/f9362a23808dd820bce2ed077a0cbb6358fe3041/setup/list_modules.py#L364-L380
Because `Lib/site-pacakges` does not have a `__init__.py` file (and should not), its subfolders are not recognized as packages by `python -m brython --modules`.
Solution:
```python
packages = {os.getcwd(), os.getcwd() + '/Lib/site-packages'}

def is_package(folder):
    """Test if folder is a package, ie has __init__.py and all the folders
    above until os.getcwd() also have __init__.py.
    Use set "packages" to cache results.
    """
    if folder in packages:
        return True
    current = folder
    while True:
        if not os.path.exists(os.path.join(current, "__init__.py")):
            return False
        current = os.path.dirname(current)
        if current in packages:
            packages.add(folder)
            return True
```
Everything else seems to work fine, that should be the last time I annoy you ^^ Thanks for the great work, this is an awesome tool.

**Comment by aure-olli** [comment]
Was little trickier than I thought, made a merge request.

**Comment by PierreQuentel** [comment]
Merci beaucoup !
