### ISSUE TITLE
CDATA in multiple script elements gives syntax error

### ISSUE THREAD

**Issue by darthglowball** [brython-dev/brython#1140]
Hi,

I have an html file with svg content in it. The svg content mixes html elements in some places which is inside of foreignObject elements. There are multiple scripts in the file, either in svg or in html elements. I reduce the problem to 2 scripts. Cases:

First script has CDATA and second has not: no error, runs fine.
Second script has CDATA and first has not: syntax error.
Both scripts have CDATA: syntax error.

Try a test like
`<script type="text/python"><![CDATA[`
`from browser import document, alert`
`alert("hello")`
`]]></script>`

Or anything, and you will get the syntax error with something about CDATA in the message. Adding the CDATA and first python command in a script on the same line has no influence on the error.

Chrome error:
`syntax error token op after $B.parser.$NodeCtx {node: $B.p…r.$Node, tree: Array(0), type: "node", toString: ƒ, to_js: ƒ}
brython.js:5887 Traceback (most recent call last):
  File __main__, line 1
    <![CDATA[
    ^
SyntaxError: invalid syntax
brython.js:5028 Uncaught Error
    at Object._b_.SyntaxError.$factory (eval at $make_exc (brython.js:7382), <anonymous>:141:337)
    at Object.$B.$SyntaxError (brython.js:7195)
    at $B.parser.$_SyntaxError (brython.js:223)
    at $B.parser.$transition (brython.js:4143)
    at $B.parser.$tokenize (brython.js:4696)
    at Object.$B.py2js (brython.js:4748)
    at Object.$B.run_script (brython.js:4842)
    at $B.parser._run_scripts (brython.js:4912)
    at $B.parser.brython (brython.js:4838)
    at onload (GUI_with_brython.html:1)`

Firefox error:
`syntax error token op after 
Object { node: {…}, tree: [], type: "node", toString: toString(), to_js: to_js()
 }
brython.js:4142:9
Traceback (most recent call last):
  File __main__, line 1
    <![CDATA[
    ^
SyntaxError: invalid syntax brython.js:5887:9`

**Comment by PierreQuentel** [comment]
Brython expects the textContent of `<script type="text/python">` tags to be valid Python code. In your example, it is obviously not the case.

I don't know if this would solve the issue, but maybe:
```xml
<script type="text/python">
#<![CDATA[
from browser import document, alert
alert("hello")
#]]>
</script>
```

**Comment by darthglowball** [comment]
@PierreQuentel it seems that it can solve the syntax error, but I think it ignores the issue that it's not how Javascript in SVG and HTML Script tags parse CDATA. While `<!` looks like a Javascript comment, Javascript comment syntax is `<!--`. So your analog in Python to use # for a comment to create the same meaning for CDATA as in Javascript doesn't seem right to me. CDATA isn't supposed to be a special comment. I think Brython needs to be able to understand `<![CDATA[]]>` as is. Other software will get upset if you change this token.

**Comment by PierreQuentel** [comment]
@darthglowball 
Javascript doesn't interpret `<!` as a comment either: if you write this
```xml
<script>
<![[CDATA
var x = 0
]]>
</script>
```
you will get a syntax error. The correct syntax is Javascript is with the comment delimiter `//` before the CDATA delimiters (see [this post](https://stackoverflow.com/questions/66837) on stackoverflow)
```xml
<script>
// <![[CDATA
var x = 0
// ]]>
</script>
```
This is why I suggested to try the equivalent with Brython.

**Comment by darthglowball** [comment]
@PierreQuentel your examples are wrong: with or without comments you should write `<![CDATA[`. But you're right if you're saying that comments + CDATA is correct in some file structures. That would explain my issue: I had script 1 in a <g> (SVG) and script 2 in a <div> (HTML) in the same html document. SVG scripts accept CDATA without comment in Firefox, Chrome, Opera, Internet Explorer; while HTML scripts give a syntax error in those browsers, according to my tests.

Your `#<![CDATA[` does fix the syntax error with an SVG Brython <script>, but the issue I see is that in an HTML Brython <script> that would be redundant (with or without it the script stays unmodified), and when you do need CDATA for an SVG Brython <script>, using `#<![CDATA[` converts the script's strings to character entities (try an alert of a string), which is not desirable nor what a SVG Javascript <script> does with or without a comment next to its CDATA.

**Comment by PierreQuentel** [comment]
@darthglowball 
I would really like to help, but I don't understand all that you write. Could you provide a minimal example of something that works as you expect with Javascript and not with Brython ?

**Comment by darthglowball** [comment]
@PierreQuentel there's two type of script tags that could run Javascript and Brython (maybe there's more in the web standards, I don't know): HTML and SVG. SVG is a dialect of XML, so the rules for CDATA in an SVG script are different than in an HTML script. Have a file with .html extension and add an SVG document fragment inside (an < svg > tag with stuff inside of it). Add a script tag in your file, either in the HTML namespace, or in the SVG namespace, to see the difference. For instance, a script inside of a < g > is in the SVG namespace because < g > is an SVG element.

Put in the SVG namespace a Javascript script with some XML-ish tag strings:
`<script type="text/javascript"><![CDATA[
  alert('<html><html x="ew" y="qw">')
  ]]></script>`

Works fine, no weird output in the alert, right?

Now put in the SVG namespace an equivalent Brython script with:
`<script type="text/python">#<![CDATA[
  from browser import alert
  alert('<html><html x="ew" y="qw">')
  #]]></script>`

And you'll see weird output, different from your stored literal, right? These are XML character entities, assuming that an XML parser is used for that SVG part. This is I think undesirable. I remove the comment next to the CDATA and I get the same result. No syntax error though, either with or without the comment next to the CDATA.

**Comment by darthglowball** [comment]
To clarify my OP: it is solved. I had CDATA in an HTML script, which is not allowed. It is allowed in an SVG script. So yeah thanks for that. I found this new issue when printing/alerting strings in Brython, as explained above, which may be related to this CDATA buisiness.

**Comment by PierreQuentel** [comment]
Can we close the issue ?

**Comment by darthglowball** [comment]
Yes. I'll continue the new issue in another thread when I have time.
