### ISSUE TITLE
yield assignment unpacking

### ISSUE THREAD

**Issue by mircea3** [brython-dev/brython#1141]
The following works:

```
def no_unpack():
    xy = yield
    print(xy[0] + xy[1])
    yield None
gen = no_unpack()
next(gen)
gen.send((5, 4))
```

But the following gives an exception: 
`NameError: <Javascript ReferenceError>: invalid assignment left-hand side`

```
def unpack():
    x, y = yield
    print(x + y)
    yield None
gen = unpack()
next(gen)
gen.send((5, 4))
```

Should this be working?

**Comment by PierreQuentel** [comment]
If it works in CPython, it shoud work in Brython ;-)
