### ISSUE TITLE
Builtin function exec sometimes does not work

### ISSUE THREAD

**Issue by jasonyu1996** [brython-dev/brython#1142]
Version: 3.7.3
Browser: Firefox 67.0.2, Chromium 75.0.3770.90

Example:
```
def A():
    exec("print('haha')", {'print': print}, {})
```

This same function above will run or fail with
```
Exception: <Javascript SyntaxError>: missing ) after formal parameters
```
 depending on its location. 

Now it seems that it is probably relevant to its depth in the module hierarchy. Would do more experiments on this.

**Comment by PierreQuentel** [comment]
Sorry for the late answer. I tried the code above, the call to `A()` gives the correct result, without raising an exception.
Do you have a use case when the code fails ?

**Comment by PierreQuentel** [comment]
Without more information, I prefer to close the issue. Don't hesitate to reopen it if you can provide an example where it can be reproduced.
