### ISSUE TITLE
website issue - ajax demo has an error

### ISSUE THREAD

**Issue by gibberishbc** [brython-dev/brython#1145]
Just so you know, on the brython.info website (Demo page) there is an error returned by the AJAX demo (it sits on the "waiting . . ." message forever). Error returned in console is:

Mixed Content: The page at 'https://brython.info/demo.html?lang=en#' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://api.open-notify.org/iss-now.json'. This request has been blocked; the content must be served over HTTPS.

**Comment by PierreQuentel** [comment]
Thanks for reporting this !

The demo works if the page at brython.info is served in http, not https.

If https is used, the Ajax request using http is considered "Mixed Content" and raises the error message you mention. And unfortunately, api.open-notify.org doesn't seem to support https. So I think the best would be to add a comment on the demo page, saying that it will only work in http.

**Comment by gibberishbc** [comment]
I arrived at the website following a google search, so was receiving page in however-it-is-usually-served. Can you perhaps use an .htacess file to force serving page in https? Just a thot.

**Comment by PierreQuentel** [comment]
Adding an .htaccess file is something the owner of api.open-notify.org would have to do, not on the brython.info side.

**Comment by PierreQuentel** [comment]
The [request for https support](https://github.com/open-notify/Open-Notify-API/issues/19) was made to the Open-Notify-API project long ago, but without any result apparently.
