### ISSUE TITLE
Generator doesn't recover after generator.throw: exception keeps repeating

### ISSUE THREAD

**Issue by mircea3** [brython-dev/brython#1146]
Given the following test case:

```
def fgen():
    while 1:
        try:
            print('trying...')
            yield
        except GeneratorExit:   # exit nicely
            break
        except:
            print('ERROR')
        else:
            print('OK')

gen = fgen()
for i in range(5):
    if i == 2:
        print('THROW')
        gen.throw(Exception())
    else:
        next(gen)
```

The CPython output shows how the generator can handle the exception, then keeps going:

```
trying...
OK
trying...
THROW
ERROR
trying...
OK
trying...
OK
trying...
```

But in brython, currently, the exception keeps repeating:

```
trying...
OK
trying...
THROW
ERROR
trying...
ERROR
trying...
ERROR
trying...
```

(Sorry for all the edits. I tried to simplify and clarify the example, removing unnecessary details.)

**Comment by mircea3** [comment]
The following change seems to fix it.:

```
py_generator.js: generator.$$throw:

-    return generator.__next__(self)
+    var res = generator.__next__(self)
+    self.sent_value = _b_.None
+    return res
```

**Comment by mircea3** [comment]
*After* getting past this problem, another exception-related problem appears, when there is a `yield` statement inside the `except` block. It appears *both* the `except` and the `else` blocks execute. This can be seen in the following example, by setting `SHOW_ERROR = True`:

```
SHOW_ERROR = False

def fgen():
    while 1:
        try:
            print('trying...')
            yield
        except GeneratorExit:   # exit nicely
            break
        except:
            print('ERROR handler start')
            if SHOW_ERROR:
                yield
            print('ERROR handler end')
        else:
            print('OK')

gen = fgen()
for i in range(5):
    if i == 2:
        print('THROW')
        gen.throw(Exception())
        if SHOW_ERROR:
            next(gen)
    else:
        next(gen)
```

**Comment by mircea3** [comment]
It seems that after the `yield` the "failed variable" is no longer defined.  The following (hack?) seems to fix the last problem:

```
py2js.js $TryCtx:
- new $NodeJSCtx(else_node, 'if(!'+failed_name+ ')')
+ new $NodeJSCtx(else_node, 'if(typeof('+failed_name+')!="undefined"&&!'+failed_name+')')
```

**Comment by PierreQuentel** [comment]
@mircea3 
Once again many thanks for the precise report !
I fixed the bug in a different way than what you suggested: 

- the attribute `sent_value` is reset to None in the generated code _before_ throwing the exception instead of _after_ (which, of course, never happens...), not in method `generator.$$throw()`. Your fix would probably have given the same result.
- the internal value `$failedX` is set as an attribute of `$locals` instead of a local variable. This way, its value is preserved when the generator is resumed.
