### ISSUE TITLE
Configurable import path?

### ISSUE THREAD

**Issue by jasonyu1996** [brython-dev/brython#1147]
Hi! Is it possible to configure the paths where Brython attempts to find the imported modules? I want it to avoid some which are intended for other purposes.

**Comment by eruvanos** [comment]
Hi, 
you can manipulate the `pythonpath` with options of the brython function 
http://brython.info/static_doc/en/options.html

Example:
```
<body onload="brython({debug:1, pythonpath:['/static/py/']})">
```

**Comment by eruvanos** [comment]
@jasonyu1996, does it work for you? Should we close this issue?

**Comment by PierreQuentel** [comment]
I close the issue, if @jasonyu1996 disagrees, please reopen it.
