### ISSUE TITLE
marshal.loads raises exception

### ISSUE THREAD

**Issue by eruvanos** [brython-dev/brython#1148]
Using the python json modules seems to be really slow, so I tried using the JS version, which is wrapped in the module `marshal`. Using this throws an error:

Example code:
```python
import marshal
print(marshal.loads('{"hello":"world"}'))
```

Error:
```
Traceback (most recent call last):
  File https://brython.info/tests/editor.py, line 112, in run
    exec(src, ns)
  File <string>, line 2, in <module>
Exception: <Javascript TypeError>: $B.jsobject2pyobject is not a function
```

Expected:
Python dict

**Comment by PierreQuentel** [comment]
I fixed the bug, but using the __`marshal`__ module to access Javascript's JSON object is not the most obvious...

In the second commit above I added and documented an attribute `JSON` in the __`javascript`__ module so that your code would become: 
```python
import javascript

print(javascript.JSON.parse('{"hello":"world"}'))
```

**Comment by eruvanos** [comment]
Just tested it, it is amazingly fast!

Tried it with:
```
raw = '{"state": {"players": [{"username": "maic", "coins": 11, "cards": [], "score": 11}], "cur_player": null, "order": [], "status": "waiting for players", "open_card": null, "coins": 0, "cards_left": 0}, "type": "STATE"}'
```

json.parse: 1.6-1.9 sec
javaspript.JSON.parse: 0.002 sec

Found a small bug, the null object is not parsed right, will try to write my first PR to fix it.

Thank you!
