### ISSUE TITLE
instanceof returns True for str and JSObject

### ISSUE THREAD

**Issue by eruvanos** [brython-dev/brython#1149]
Using `instanceof` resoluts in unexpected behavior. Strings seems to be instance of JSObject.

Example code:
```
from javascript import JSObject
print('Should be false:', isinstance('', JSObject))
```

Result:
```
Should be false:  True
```

Expected:
```
Should be false:  False
```

**Comment by PierreQuentel** [comment]
Thanks for the report.

`JSObject` has been deprecated for a while, but the deprecation warning only showed when creating an instance of the class, not in this case. 

The fix shows the warning and `isinstance('', JSObject)` returns `False`.
