### ISSUE TITLE
importing json triggers ajax imports

### ISSUE THREAD

**Issue by eruvanos** [brython-dev/brython#1153]
Regarding the documentation:

> To import modules or packages, Brython uses the same mechanism as CPython : to resolve 
    "import X", the program looks for a file in several places :
    * a module X in the standard distribution
    * a file X.py in the root directory
    * a file __init__.py in directory X

importing a module from std_lib should not trigger AJAX imports. But this is the case, tested with following code:

```
<html>
<head>
    <meta charset="utf-8">
    <title>Brython demo</title>
    <script src="brython.js"></script>
<script src="brython_stdlib.js"></script>
</head>
<body onload="brython(1)">

<script type="text/python">

import json

</script>
</body>
</html>
```

**Comment by PierreQuentel** [comment]
Can you give more context for this issue ? Without knowing what is inside __`brython_modules.js`__ I won't be able to reproduce it.

**Comment by eruvanos** [comment]
@PierreQuentel Sorry, 
I did the same with the std_lib, forgot to turn back my changes.

Using the brython_stdlib, there should be no AJAX call to import json, right?

**Comment by PierreQuentel** [comment]
That's annoying... I am trying with __`brython_stdlib.js`__ and seeing no Ajax call in my browser console.

I tried with the latest development version and with release 3.7.3.

**Comment by eruvanos** [comment]
I checked it with the last development version. Here it works like expected.

Using the brython.js from the installed site-packages folder brings back the old behavior.

I checked the header of that file.

```
// brython.js brython.info
// version [3, 7, 0, 'final', 0]
// implementation [3, 7, 3, 'final', 0]
// version compiled from commented, indented source files at
// github.com/brython-dev/brython
```

I tried a reinstallation, now it looks like it is working like expected, but is not able to completely load the json module. 

```
using indexedDB for stdlib modules cache
brython.js:5887 Traceback (most recent call last):
  module __main__ line 2
    import json
  module json line 106
    from .decoder import JSONDecoder,JSONDecodeError
  module json.decoder line 3
    import re
  module re line 122
    import enum
  module enum line 1
    import sys
  module sys line 46
    
  module sys line 48
    mant_dig=53
AttributeError: 'module' object has no attribute 'Number'
brython.js:5028 Uncaught Error
    at Object._b_.AttributeError.$factory (eval at $make_exc (brython.js:7382), <anonymous>:41:354)
    at attr_error (brython.js:6365)
    at Object.$B.$getattr (brython.js:6478)
    at eval (eval at exec_module (brython.js:8719), <anonymous>:203:60)
    at eval (eval at exec_module (brython.js:8719), <anonymous>:211:6)
    at exec_module (brython.js:8719)
    at f (brython.js:6154)
    at method (brython.js:6158)
    at Object.import_hooks (brython.js:13081)
    at $B.$__import__ (brython.js:8882)
```

System: MacOS 10.14
Python: Pipenv virtual environment Python 3.7.3 (installed via pyenv)

**Comment by eruvanos** [comment]
Thank you very much for the investigation, I guess because the dev version already fixed the issue, this issue can be closed.
