### ISSUE TITLE
Setting Javascript JSON parse()'s result to a Python class attribute, and using that class attribute in stringify() causes "converting circular structure to JSON" error

### ISSUE THREAD

**Issue by darthglowball** [brython-dev/brython#1168]
Hi,

Setting Javascript JSON parse()'s result to a Python class attribute, and using that class attribute in stringify() causes "converting circular structure to JSON" error in Chrome and CEF.

Python:

       from browser import window
       
       json_to_load = '{"tab" : {"def" : ["yeah"]}}'
       
       class myclass():
           tab = {}
           def __init__(self, content):
               json_object = window.JSON.parse(content)
               self.tab = json_object["tab"]
               print(window.JSON.stringify(self.tab["def"]))
              
       myclass(json_to_load)

**Comment by darthglowball** [comment]
The problem can be simplified some more, so it may not actually be related to classes:

       from browser import window
       
       json_to_load = '{"tab" : {"def" : ["yeah"]}}'
       
       json_object = window.JSON.parse(json_to_load)
       print(window.JSON.stringify(json_object["tab"]["def"]))

**Comment by PierreQuentel** [comment]
I get the same result.

One of the confusing things with the browser engines is that the global namespace (available in Brython with the object `browser.window`) mixes two kind of objects : 
- the names defined by the Javascript language (eg `Array, Map, Math, JSON...`) : complete list available [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects)
- the names defined by the Document Object Model (eg `document, indexedDB, localStorage...`)

I have started splitting these names : the first ones in the __`javascript`__ module, the other ones available as attributes of `browser.window`.

In this specific case, replacing `window.JSON` by `javascript.JSON` fixes the issue.

**Comment by darthglowball** [comment]
@PierreQuentel thank you, it works! It may be useful to put a notice on the Brython site that `window.JSON` shouldn't be used, as well as `import json`, which creates an endless loop for me.
