### ISSUE TITLE
difflib.HtmlDiff is not working?

### ISSUE THREAD

**Issue by ch-yx** [brython-dev/brython#1176]
import difflib
d=difflib.HtmlDiff()
document["out"].innerHTML=d.make_table(s1.splitlines(),s2.splitlines())

```
Traceback (most recent call last):
  module __main__ line 10, in change
    	document["out"].innerHTML=d.make_table(s1.splitlines(),s2.splitlines())
  module difflib line 2020, in make_table
    fromlist,tolist,flaglist=self._collect_lines(diffs)
  module difflib line 1888, in _collect_lines
    for fromdata,todata,flag in diffs:
  module difflib line 1604
    
  module difflib line 1586
    from_line,to_line,found_diff=next(line_iterator)
  module difflib line 1500
    lines.append(next(diff_lines_iterator,'X'))
TypeError: next() takes exactly 1 argument (2 given)
```

**Comment by PierreQuentel** [comment]
Thanks for the bug report. The cause was that a `continue` inside a loop in a generator was not handled properly. For instance, this code
```python
def f():
    while True:
        if t:
            yield t.pop()
            continue
        print(t)
        return

t = ["a", "b", "c"]
list(f())
```
which should print the empty list actually printed `["a", "b"]`.

**Comment by ch-yx** [comment]
thanks a lot for your work!
(Could you tell me where could I get the fixed version?)

**Comment by PierreQuentel** [comment]
Bug fixes are applied to the current development version, that you can get by cloning the Github repository. 

I release new versions regularly (see the page [Releases](https://github.com/brython-dev/brython/releases)), the next one should be published before the end of this month.
