### ISSUE TITLE
latin_1.py not found

### ISSUE THREAD

**Issue by aliasal** [brython-dev/brython#1177]
As I couldn't get SymPy to work I am using Algebrite together with brython which works quite fine.

It seems Algebrite uses Latin-1 encoding on its strings, so when I tried to use float() on such a string I got the error message that latin_1.py was not found in Lib/encodings.
Which is true, as there is no such file.
I copied it from some other python repository and now everything is working.
Maybe you missed it accidentally?

EDIT: Obviously you were aware of latin1, which I found out after looking into aliases.py 
But the error came up again, this time with latin-1 not found or latin-1 unable to decode character..
I added the alias latin-1 but still no luck.
Finally I gave up converting the string to a float and made the comparisons on string level, which is good enough for my purposes.

**Comment by PierreQuentel** [comment]
For common encodings, the `encode` / `decode` functions in __`py_bytes.js`__ don't use the modules in package __`encodings`__ but are written in Javascript, this improves performance. "latin1" was supported, but not "latin-1"...

**Comment by PierreQuentel** [comment]
Fixed by commit ace1272b64da513c19a97ba6f14af192af75fb23
