### ISSUE TITLE
Import can't find Regex module

### ISSUE THREAD

**Issue by darthglowball** [brython-dev/brython#1179]
I try to import regex module from a Brython script in my Client folder. regex is located at `...\Client\resources\backend\javascript_packages\Brython\Lib\site-packages\regex`. Regex is found [here](https://bitbucket.org/mrabarnett/mrab-regex/src/default/). I do:

`import regex` and I get this error:

```
Error 0 means that Python module regex was not found at url file:///C:/Users/hp/Documents/Programming/Web%20development/File%20content%20searcher%20and%20categorizer/Client/regex.py
brython.js:8724 Failed to load resource: net::ERR_FILE_NOT_FOUND
brython.js:8729 Error 0 means that Python module regex was not found at url file:///C:/Users/hp/Documents/Programming/Web%20development/File%20content%20searcher%20and%20categorizer/Client/regex/__init__.py
brython.js:8724 Failed to load resource: net::ERR_FILE_NOT_FOUND
brython.js:8729 Error 0 means that Python module regex was not found at url file:///C:/Users/hp/Documents/Programming/Web%20development/File%20content%…t/resources/backend/javascript_packages/Brython/Lib/site-packages/regex.py
brython.js:8724 Failed to load resource: net::ERR_FILE_NOT_FOUND
brython.js:8729 Error 0 means that Python module regex was not found at url file:///C:/Users/hp/Documents/Programming/Web%20development/File%20content%…es/backend/javascript_packages/Brython/Lib/site-packages/regex/__init__.py
brython.js:5979 Traceback (most recent call last):
ImportError: No module named regex
brython.js:5124 Uncaught Error
    at Object._b_.ImportError.$factory (eval at $make_exc (brython.js:7501), <anonymous>:71:321)
    at Object.import_hooks (brython.js:13227)
    at $B.$__import__ (brython.js:9028)
    at Object.$B.$import (brython.js:9061)
    at eval (eval at $B.loop (brython.js:5108), <anonymous>:20:8)
    at $B.loop (brython.js:5108)
    at $B.inImported (brython.js:5098)
    at $B.loop (brython.js:5114)
    at IDBOpenDBRequest.idb_cx.onsuccess (brython.js:5078)
```

I'm using CEF. 
the init.py contains `from .regex import *`. In the regex folder there is is a regex.py script.
The __init__.py is present in the regex folder. If you look at the part `regex was not found at url file:///C:/Users/hp/Documents/Programming/Web%20development/File%20content%…es/backend/javascript_packages/Brython/Lib/site-packages/regex/__init__.py` it looks like resources folder isn't present, but there's `...es` which I think is an abbreviation for that folder. So the error shows the right paths to check, but the module isn't found. I'm 100% sure that the scripts are in the correct folders with the correct names.

**Comment by PierreQuentel** [comment]
The `file://` at the beginning of the paths shows that you are opening the page in the browser ; in this case, Ajax calls fail. You had better load the page through a web server.

**Comment by darthglowball** [comment]
(side issue: importing Brython's Ajax module gives CPU load of 100% continuously in CEF (are you having that issue?))

My application runs on pywebview with CEF enabled. It is a local browser-based app so all resources, including Python scripts, are on the user's pc. Is there a way I can avoid using a server? Do you know of a security feature in CEF that enables unlimited acces to the user's file system, making the Brython "file not found" error go away?

Another idea for importing in Brython is this: pywebview has js_api which allows for communication between a Python interpreter and the browser, so if I can use Python's import statement to load the module I want, and use a module (I tried Python's `inspect` module's `getsource()`, but it doesn't give me source code of module objects that were stitched together from other scripts) to get the source code of that module that was stitched together from several scripts, and then use exec() to run the code in Brython. This would be really annoying to do with each added module, so I'd rather not.

**Comment by darthglowball** [comment]
I figured out how to start an HTTP server in pywebview. Now regex loads partially, but there are many errors. I omitted all except the last. The last error is ImportError. Maybe Brython is unable to read .pyd files? And what's up with these underscores that are added before folder names (which can be seen in the errors)? Could someone please try importing [regex](https://bitbucket.org/mrabarnett/mrab-regex/src/default/)?
﻿
```
Traceback (most recent call last):
ImportError: No module named regex._regex
brython.js:5124 Uncaught Error
    at Object._b_.ImportError.$factory (eval at $make_exc (brython.js:7501), <anonymous>:71:321)
    at Object.import_hooks (brython.js:13227)
    at $B.$__import__ (brython.js:9028)
    at Object.$B.$import (brython.js:9061)
    at eval (eval at run_py (brython.js:8807), <anonymous>:20:12)
    at eval (eval at run_py (brython.js:8807), <anonymous>:31398:2)
    at run_py (brython.js:8807)
    at exec_module (brython.js:8919)
    at f (brython.js:6267)
    at method (brython.js:6271)
```

**Comment by PierreQuentel** [comment]
In the regex package, module _regex is written in C, this is why Brython can't import it ; it can only handle scripts written in Python or Javascript.

**Comment by darthglowball** [comment]
@PierreQuentel Alright, thank you!
