### ISSUE TITLE
Expose __BRYTHON__ in globals()

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [brython-dev/brython#1181]
1. currently `__BRYTHON__` is implicitly available in browser mode in global scope,
but is missing from `globals()`

2. it would help to expose `__BRYTHON__` in `globals()` to avoid import errors in editor mode:
```
BRYTHON = globals()['__BRYTHON__']
BRYTHON.path = [  'http://user-test/path'  ]
```
3. perhaps `__BRYTHON__` should not be automatically/implicitly 
made available in browser mode in global scope at all

**Comment by PierreQuentel** [comment]
I have added `__BRYTHON__` to `globals()` as you suggested, but you are right, it would be better to access the values stored in `__BRYTHON__` with modules such as `os` or `sys`. This means rewriting a few scripts, I will do it shortly. Thanks !

**Comment by Andrei-Pozolotin** [comment]
great, thank you
