### ISSUE TITLE
__traceback__ missing from exceptions

### ISSUE THREAD

**Issue by solsword** [brython-dev/brython#1184]
I'm writing some code for Python learners in their very first coding class and want to be able to format exceptions and attach them to the line of code where they occurred, which means I need to be able to get line numbers from exceptions. In Python 3, exceptions should have __traceback__ attributes that contain their traceback (or None if they were created manually) and the line number info I need is in there. However, in Brython 3.7.4, the following code does not work:

```python
try:
  int('abc') # raises an error
except Exception as e:
  print(dir(e)) # works, but "__traceback__" isn't on the list
  print(e.__traceback__) # fails with an AttributeError
```

I couldn't find anything in the docs specifying this divergence from standard Python 3, so I thought I'd put it here. Because of this bug, the following code also fails (an attempt to construct a TracebackException object from the caught exception):

```python
import traceback
try:
  int('abc')
except Exception as e:
  tbe = traceback.TracebackException.from_exception(e)
```

I can access the stack from within an except clause like this as a workaround:

```python
import sys, traceback
try:
  int('abc')
except Exception as e:
  tbe = traceback.TracebackException.from_exception(*sys.exc_info())
```

However, for reasons I don't understand this method takes *several seconds* to execute whereas when I don't invoke sys.exc_info things are quite fast. It may be the case that simply constructing the traceback is going to take that time in any case, because of all the work it has to do to get line numbers and connect to stack frames, which I can imagine is horribly complicated in Brython :P. But I can't be sure as things stand.

**Comment by solsword** [comment]
Quick update for those looking into workarounds:

My initial workaround that was not being as performant as I'd have liked (and of course, very possibly due to other things going on with my code) uses traceback.TracebackException, because I had read that it was created for the purpose I'm interested in: holding pseudo-traceback objects without leaving them entangled with the stack frames that tracebacks came from.

If I change the code to just call sys.exc_info but don't build a TracebackException (which is enough to grab the line numbers I need) things work much faster. So if you're having speed issues with TracebackExceptions, try using raw tracebacks instead (though I haven't thoroughly tested this yet and it might have long-term unwanted consequences).

**Comment by PierreQuentel** [comment]
Thanks for reporting this; exception objects had an attribute with the traceback object but it was `traceback` instead of `__traceback__`...

I can't be sure, but the reason why the second example takes a long time might be because you don't load __`brython_stdlib.js`__ in the page - in this case, `import traceback` takes a few seconds because this module imports many, many other modules (maybe 40 !), and without the packed stdlib each imported module must be loaded by an Ajax call and translated from Python to Javascript on the fly.

If it is the case, when you use __`brython_stdlib.js`__, the first run is long but the other ones are much faster.

**Comment by solsword** [comment]
Thanks for the quick reply! I can't believe I failed to find the .traceback property ^.^;

I can confirm that `traceback.TracebackException.from_exception(e)` works on current Brython if you first say `e.__traceback__ = e.traceback`. The script I was originally having issues with was using brython_stdlib.js, so I'm not sure that's the problem, but given the various workarounds even if there is a performance issue there in some cases, it's not a priority.

Thanks again for resolving this issue so quickly :)
