### ISSUE TITLE
NameError not generated when variable is defined later

### ISSUE THREAD

**Issue by solsword** [brython-dev/brython#1188]
I'm writing code for Python learners, so I can count on a lot of bad code being run through my system. So far things are working well and I'm able to catch errors and attach them to the line of code that generated them, which is great for students. However, I noticed the following strange behavior. This code:

```py
x.foo()
```

generates a NameError because `x` is not defined, as it should. However, this code:

```py
x.foo()
x = 5
```

generates a debugging message, but no NameError, and it ultimately results in this JavaScript Exception:

```js
Javascript exception: TypeError: Cannot read property '$is_class' of undefined
    at Object.$B.$getattr (brython.js:6494)
    at eval (eval at $$eval (brython.js:6422), <anonymous>:14:17)
    at $$eval (brython.js:6422)
    at exec (brython.js:6448)
    at exec_code48 (eval at $B.loop (brython.js:5108), <anonymous>:3052:39)
    at eval_button_handler51 (eval at $B.loop (brython.js:5108), <anonymous>:3291:127)
    at HTMLButtonElement.<anonymous> (brython.js:12385)
```

The aforementioned debugging message is:

```js
get attr setBorderWidth of undefined
```

That comes from line 6493 of the minified brython, which is:

if(obj===undefined){console.log("get attr",attr,"of undefined")}

and that's in the `$B.$getattr` function. It seems like the solution would be to generate a NameError at that point instead of a debugging message, but maybe things aren't that simple if you're using undefined as None? I'm guessing the fact that adding the later code line to the mix changes things is because you have to pre-create variables somehow, so I understand that this might be messy and not at all easy to fix.

**Comment by PierreQuentel** [comment]
I tried to reproduce this bug, but these examples
```python
x.foo()
x = 5
```
and
```python
def f():
    x.foo()
    x = 5

f()
```
both raise the expected exception.

From the traceback I guess that the bug happens in a callback function when the user clicks on a button. Could you send a more complete example ?

**Comment by solsword** [comment]
Sorry about that! I should be more diligent about isolating MWEs. Here's one that works for the web console. The extra variable in the situation seems to be the use of explicit globals/locals in the call to exec:

```py
>>> exec("x.foo()", globals={}, locals={})
Traceback (most recent call last):
  File <string>, line 1, in <module>
  File <string>, line 1, in <string>
NameError: name 'x' is not defined
>>> exec("x.foo()\nx=3", globals={}, locals={})
Traceback (most recent call last):
  File <string>, line 1, in <module>
Exception: <Javascript TypeError>: Cannot read property '$is_class' of undefined
>>> 
```

Running the same code without `locals={}` (setting globals is fine) produces the correct NameError. In my case I'm passing around explicit environments between different chunks of code on the page as I evaluate/execute them. Running the code with `locals=locals()` has the same problem. Interestingly, there are some operations that won't even raise an error when locals is set in exec, like:

```py
exec("print(x)\nx = 3", locals={})
```

or

```py
exec("print(x is None)\nx = 3", locals={})
```

although the following does raise a JavaScript error at least:

```py
exec("print(x == None)\nx = 3", locals={})
```

**Comment by solsword** [comment]
Quick update for those looking for workarounds:

Wrapping the code in a function seems to correctly generate an UnboundLocalError, presumably because when executing the code, the function context gets a "real" locals object. So I can do this:

```py
exec("def f():\n . print(x)\n . x = 3\nf()", {}, {})
```

and I'll get an UnboundLocalError about x being referenced before assignment.

**Comment by PierreQuentel** [comment]
Thanks for the explanation. It's a nightmare to get locals and globals to work correctly inside an `exec()` ;-)

**Comment by solsword** [comment]
Thanks for the quick fix! I'm setting up a git clone now so that I can see it in action :)
