### ISSUE TITLE
brython.py executed on import

### ISSUE THREAD

**Issue by stefanhoelzl** [brython-dev/brython#1189]
After I installed brython (`pip install brython`) I wanted to access `brython.js`
```python
import pkg_resources
pkg_resources.resource_string("brython", "data/brython.js")
```
but this results in executing `brython.py` and the call fails.

please put the [main logic of `brython.py`](https://github.com/brython-dev/brython/blob/3757228ccf421c6da62f93c52b5cb99f79f41091/setup/brython.py#L11) inside `if __name__ == "__main__":` to avoid this.

**Comment by PierreQuentel** [comment]
I tried this code in Python REPL and got the content of __`brython.js`__, without __`brython.py`__ being executed. I'm on Windows 10 with CPython 3.7.0 and Brython-3.7.4. What is your config ? Do other users have the same problem ?

**Comment by stefanhoelzl** [comment]
you are right in the Python REPL it works, I tried it from the PyCharm Console and there it failed.
I think thats because PyCharm sets some values in `sys.argv` and then [this line](https://github.com/brython-dev/brython/blob/master/setup/brython.py#L36) fails

you can put the code in a file `test.py` and calling it without argument works:
```bash
$ python test.py
```
But calling it with an argument fails:
```bash
$ python test.py 1
usage: test.py [-h] [--add_package ADD_PACKAGE] [--install] [--make_dist]
              [--modules] [--port PORT] [--reset] [--server] [--update]
test.py: error: unrecognized arguments: 
``

**Comment by PierreQuentel** [comment]
Ok, got it, thanks !
