### ISSUE TITLE
Importing re or copy modules give 100% CPU indefinitely

### ISSUE THREAD

**Issue by darthglowball** [brython-dev/brython#1191]
Hi,

This happens on Chrome and some older version of CEF (3.3359.1774.gd49d25f), Chromium Version: 66.0.3359.181.

Code:

```
<html>
<head>
  <script type="text/javascript" src="resources/backend/javascript_packages/Brython/brython.js"></script>
  <script type="text/javascript" src="resources/backend/javascript_packages/Brython/brython_stdlib.js"></script>
</head>
  <body onload="brython()" overflow="scroll">
    <script id = "script1" type="text/python">
        import re
        print(re)
        print("hi")
    </script>
  </body>
</html>
```

**Comment by PierreQuentel** [comment]
@darthglowball 
If this bug only happens in CEF (I had to use a search engine to know what this means...) I really can't take the time to investigate and fix it, sorry.

**Comment by darthglowball** [comment]
In Chrome it immidiately finishes without max CPU usage for more than a second when starting up for the first time, but with page refreshes afterward the bug occurs. In Chrome I have to wait 30 sec to 1 minute after page refresh for the script to finish. In Opera the I have to wait 10 seconds for it to finish at startup and with page refreshes afterwards. In CEFPython the CPU is indefinitely at 100% and the script never finishes. OS used: windows 7, 32-bit.

**Comment by PierreQuentel** [comment]
I don't have the same behaviour on my PC (Windows 10, Chrome 76.0.3809.100 64 bits).

Can you try with the indexedDB cache disabled:
```
<body onLoad="brython({indexedDB: false})">
```

**Comment by darthglowball** [comment]
@PierreQuentel that didn't do anything for the load times in Chrome and Opera, but in cefpython it did fix the infinite waiting to 15 seconds.

**Comment by PierreQuentel** [comment]
I am closing this old issue, even though I am not sure whether the problem is solved...
