### ISSUE TITLE
KeyboardEvent.repeat is always false in CEF

### ISSUE THREAD

**Issue by darthglowball** [brython-dev/brython#1192]
This happens in CEF (3.3359.1774.gd49d25f), which uses Chromium Version: 66.0.3359.181. It is an older version because I use CEFPython. The KeyboardEvent.repeat works fine in Chrome.

Code:
```
        from browser import document
        
        mydiv = document.getElementById("mydiv")
        
        def key_down(event):
            print(event.repeat)
            
        mydiv.addEventListener("keydown", key_down)
```

**Comment by darthglowball** [comment]
It seems to be a bug in either pywebview which uses CEFPython, or CEFPython or CEF when using javascript. Will anyone do a workaround in Brython regardless?

**Comment by PierreQuentel** [comment]
I have the same comment as for issue #1191 : if this bug is specific to CEF, it is beyond the scope of Brython.

**Comment by darthglowball** [comment]
Yes I'm only getting this bug in CEFPython.
