### ISSUE TITLE
How to use input() function inside a brython worker thread

### ISSUE THREAD

**Issue by benomase** [brython-dev/brython#1198]
Hello,

I have a worker thread that does the execution of a python script in which there will be input() python functions.

On brython, Input() is translated to javascript prompt() but as i'm using a worker thread, it doesn't work as the worker can't access the DOM.

Do you have an idea on how to achieve this ?

Thanks.

**Comment by PierreQuentel** [comment]
I'm afraid there is no solution for that; by design, `prompt()` and `confirm()` are not available in web workers.
