### ISSUE TITLE
Performance issues when upgrading from 3.7.1 to 3.7.4

### ISSUE THREAD

**Issue by desean1625** [brython-dev/brython#1199]
https://codesandbox.io/s/brython-in-webworker-ss03z

#### Set in javascript
```js
inputs['test'] = ["1"]
```

#### Processed in Brython webworker
```py
l = inputs['test']
for i,v in enumerate(l):
  l[i] = v + " TEST"
outputs.list = l
```

v3.7.0
Brython Complete 181.6349999862723 <--- Time to just execute brython script
TOTAL TIME: 587.0599999907427 <--- Time to transfer data via post message execute brython script and transfer back

v3.7.4
Brython Complete 4222.049999982119 <--- Time to just execute brython script
TOTAL TIME: 4548.055000021122 <--- Time to transfer data via post message execute brython script and transfer back

**Comment by PierreQuentel** [comment]
Could you try with the latest release 3.7.5 ?

**Comment by desean1625** [comment]
3.7.1
Brython Complete 114.51499990653247
index.js:27 TOTAL TIME: 383.0800000578165

3.7.4
Brython Complete 3877.3400000063702
index.js:27 TOTAL TIME: 4336.434999946505

3.7.5
Brython Complete 3957.46499998495
index.js:27 TOTAL TIME: 4397.5749999517575

**Comment by PierreQuentel** [comment]
No progress with this version then...

When I run the code with version 3.7.1 I see what seems to be an error message in the browser console:
```
Array [ "TypeError: $B.path_hooks is undefined" ]
```
and I don't have this message in versions 3.7.4 and 3.7.5. Maybe there is a link between this error and the difference of performance, but I couldn't find where this error came from in version 3.7.1. Do you have an idea ?

**Comment by desean1625** [comment]
https://github.com/brython-dev/brython/blob/b957bcad8b2f3ea5e37478978ef2a5422c380e12/www/src/py_import.js#L644

**Comment by desean1625** [comment]
![image](https://user-images.githubusercontent.com/11495566/64886560-7e78cc00-d634-11e9-89b3-06268e04aa4f.png)

![image](https://user-images.githubusercontent.com/11495566/64886595-951f2300-d634-11e9-9fd7-571ec7b3cde5.png)

**Comment by desean1625** [comment]
Looks like it is recursively calling run_py and doing the imports over and over

**Comment by desean1625** [comment]
Hope that helps

**Comment by PierreQuentel** [comment]
I have found the reason : the culprit is the __`json`__ module which is imported in the script.

Until version 3.7.1 it was a Brython-specific version of the stdlib module, built on top of Javascripts's JSON object. Because of issues reported in #1116 and #1117, I had to replace it with the CPython stdlib package. Unfortunately it is much longer to import and this explains what you observe.

Instead of this package, you can still use the Javascript JSON object, which is available as the attribute `JSON` of `browser.window`. Instead of
```python
import json
json.dumps(value)
```
you can use the much faster
```python
from browser import window
window.JSON.stringify(value)
```

From 3.7.4 onwards, `JSON` is also an attribute of the `javascript` module.

**Comment by desean1625** [comment]
Ok I see those changes, and what if we just expand the old implementation to include the indent and sorting keys?

Here is that implementation below
```js
var $module = (function($B){

  var _b_ = $B.builtins
  function js2py(js){
      switch(typeof js){
          case "object":
              if(js === null){
                  return _b_.None
              }else if(Array.isArray(js)){
                  var res = _b_.list.$factory()
                  js.forEach(function(item){
                      res.push(js2py(item))
                  })
              }else{
                  var res = _b_.dict.$factory()
                  Object.keys(js).forEach(function(key){
                      res.$string_dict[key] = js2py(js[key])
                  })
              }
              return res
          default:
              return js
      }
  }
  //$fname,argcount,slots,var_names,args,$dobj,extra_pos_args,extra_kw_args
  return  {
      loads : function(){
          var $ = $B.args('loads', 1, {obj:null}, ['obj'], arguments, {},
              null, null)
          return js2py(JSON.parse($.obj))
      },
      load : function(){
          var $ = $B.args('load', 1, {obj:null}, ['obj'], arguments, {},
              null, null)
          return $module.loads(obj.$content);
      },
      dumps : function(){
          var $ = $B.args('dumps', 1, {obj:null,sort_keys:null,indent:null}, ['obj'], arguments, {sort_keys:false,indent:0},
              null, "kw")
          var obj = $B.pyobj2jsobj($.obj);
          if($.sort_keys){
            var keys = Object.keys(obj).sort();
            var oldObj = obj;
            obj = {};
           keys.forEach(key=>{
             obj[key] = oldObj[key]
           })
          }
          return JSON.stringify($B.pyobj2jsobj($.obj),null,$.indent)
      }
  }
  
  })(__BRYTHON__)

```

**Comment by desean1625** [comment]
I tested version 3.7.5 overloading the the json module 

```js
__BRYTHON__.VFS.json[0] = ".js";
__BRYTHON__.VFS.json[1] = \`var $module = (function($B){
...truncated
```
And these are the numbers I got
Brython Complete 145.34000000276137
TOTAL TIME: 695.9600000118371

**Comment by PierreQuentel** [comment]
It would be a good solution if we could implement the complete interface of the [Python module](https://docs.python.org/3/library/json.html), but I'm not sure it is possible for options of `json.dump()` such as `ensure_ascii, allow_nan, separators`, etc.

By the way, the time taken to import `json` is always relatively long in your application because it has to translate the Python source to Javascript every time, without taking advantage of the indexedDB cache. If you could find a way to use it, the performance would still be poor the first time, but much better for the next runs.

**Comment by desean1625** [comment]
Would it make sense in the build process to run the compile to javascript distribute the precompiled modules? I have been experimenting with this, but it doesn't seem to be as simple as setting 
```js
__BRYTHON__.precompiled = {json:"....","json.decoder":"....",'json.encoder':"....",'json.scanner':"...",re:"..."}
```

**Comment by desean1625** [comment]
Here is a more complete interface.
```js
var $module = (function($B){

  var _b_ = $B.builtins
  function js2py(js){
      switch(typeof js){
          case "object":
              if(js === null){
                  return _b_.None
              }else if(Array.isArray(js)){
                  var res = _b_.list.$factory()
                  js.forEach(function(item){
                      res.push(js2py(item))
                  })
              }else{
                  var res = _b_.dict.$factory()
                  Object.keys(js).forEach(function(key){
                      res.$string_dict[key] = js2py(js[key])
                  })
              }
              return res
          default:
              return js
      }
  }
  var allow_nan_replacer = function(k,v){
    if(v === Number.NEGATIVE_INFINITY){
    return "~~~-Infinity~~~"
    }else if(v === Number.POSITIVE_INFINITY){
    return "~~~Infinity~~~"
    }else if(v !==v){
    return "~~~NaN~~~"
    }
    return v;
    }
  return  {
      loads : function(){
          var $ = $B.args('loads', 1, {obj:null}, ['obj'], arguments, {},
              null, null)
          return js2py(JSON.parse($.obj))
      },
      load : function(){
          var $ = $B.args('load', 1, {obj:null}, ['obj'], arguments, {},
              null, null)
          return $module.loads(obj.$content);
      },
      dumps : function(){
          var $ = $B.args('dumps', 1, {obj:null,sort_keys:null,indent:null,ensure_ascii:null,allow_nan:null}, ['obj'], arguments, {sort_keys:false,indent:0,ensure_ascii:true,allow_nan:true},
              null, "kw")
          var obj = $B.pyobj2jsobj($.obj);
          if($.sort_keys){
            var keys = Object.keys(obj).sort();
            var oldObj = obj;
            obj = {};
           keys.forEach(key=>{
             obj[key] = oldObj[key]
           })
          }
          var replacer = $.allow_nan? allow_nan_replacer:null
          var str = JSON.stringify(obj,replacer,$.indent);
          if($.allow_nan){
            str = str.replace(/\"~~~(.+?)~~~\"/g,function(v,m){return m})
          }
          if($.ensure_ascii){
            return str.replace(/[\u007F-\uFFFF]/g, function(chr) {
              return "\\\\u" + ("0000" + chr.charCodeAt(0).toString(16)).substr(-4);
          });
          }else{
            return str;
          }
      }
  }
  
  })(__BRYTHON__)
```

**Comment by PierreQuentel** [comment]
@desean1625 
I really appreciate the effort, but I don't want to change the CPython implementation for a JS version that would not implement exactly the same features.

Regarding the precompilation, this is actually done in the indexedDB cache. It could be done with precompiled files, but it's not how Brython is designed : no explicit precompilation should be required to run a script. Another problem is that the generated Javascript is typically 10 times bigger than the Python source, so the precompiled file would take some time to load, reducing its interest as far as performance is concerned.

**Comment by PierreQuentel** [comment]
I am closing this issue, once again many thanks for the report and the proposals. If you can develop a Javascript equivalent of the module, please submit a PR.
