### ISSUE TITLE
frame objects don't have any attributes

### ISSUE THREAD

**Issue by glyph** [brython-dev/brython#120]
Trying to port some custom traceback-formatting code to brython, I discovered that the `frame` object doesn't have any attributes.

**Comment by kikocorreoso** [comment]
Could you provide more context, please?

**Comment by glyph** [comment]
I am referring to the frame objects associated with tracebacks.  To be compatible with Python, they must have `f_back`, `f_builtins`, `f_code`, `f_globals`, `f_lasti`, `f_lineno`, `f_locals`, `f_trace` attributes.  Instead, they have no attributes.

**Comment by PierreQuentel** [comment]
Thanks for the report, it's one of the difficult tasks I had postponed until someone noticed it was missing ;-)

I have added an object `__BRYTHON__.frames_stack` which is populated when the program enters a module or a function, and popped from when the function or module exits. The object pushed on the stack is a 2-element list `[locals_id, globals_id]`

When an exception is raised, the attribute `tb_frame` of the traceback object is the value returned by the function `frame()` in py_builtin_functions.js, an object with most of the required arguments of frame objects set.

At the moment some of these arguments are not correctly set, so I don't close the issue, but at least they avoid raising name errors in the module `deferred`

**Comment by PierreQuentel** [comment]
Glyph,

I fixed a bug I introduced when adding some of these attributes. I installed your packages "brytly" and "deferred" ; the test gives the weird results you mention in issue #121, but frame objects seem to have the minimal attributes now

**Comment by glyph** [comment]
@PierreQuentel Cool!  As soon as I have tracked down that weird behavior a bit more and figured out how to work around it, I will start trying to uncomment bits of `deferred.Failure`'s formatting logic and making it more like the upstream `Deferred`.
