### ISSUE TITLE
A Brython keyboard event handler function is 73x slower in Chrome and 143x slower in CEF than its Javascript equivalent

### ISSUE THREAD

**Issue by darthglowball** [brython-dev/brython#1200]
10 trials were performed for Brython and 10 trials for Javascript with a loop in a keyboard event handler function as the load, per browser (Chrome and CEF). See the attachment for the benchmark test. In it you can derive the 73x/143x slowdown factors, you can find the versions of the browsers, my pc specs and the run time per trial.

The code load used with the benchmark test:
```
<html>
<head>
  <script type="text/javascript" src="resources/backend/javascript_packages/Brython/brython.js"></script>
  <script type="text/javascript" src="resources/backend/javascript_packages/Brython/brython_stdlib.js"></script>
</head>
  <body onload="brython()" overflow="scroll">
    <div tabindex="0" id="mydiv" style="background:blue;width:100px;height:10000px">
      <div id="mydiv2" style="position:absolute;background:red;width:10px;height:10px"></div>
    </div>
    <script id = "script1" type="text/python">
        from browser import document
        
        mydiv = document.getElementById("mydiv")
        
        def key_down(event):
            for i in range(10000000):
               pass

        def key_up(event):
            for i in range(10000000):
               pass
            
        mydiv.addEventListener("keydown", key_down)
        mydiv.addEventListener("keyup", key_up)
    </script>
    <!--<script id = "script2" type="text/javascript">
        
        mydiv = document.getElementById("mydiv")
        
        function key_down(event){
            for (i = 0;i<10000000;i++){
            }
        }

        function key_up(event){
            for (i = 0;i<10000000;i++){
            }
        }
            
        mydiv.addEventListener("keydown", key_down)
        mydiv.addEventListener("keyup", key_up)
    </script>-->
  </body>
</html>
```
[performance of keyboard.pdf](https://github.com/brython-dev/brython/files/3546870/performance.of.keyboard.pdf)

**Comment by PierreQuentel** [comment]
I tried these scripts to compare the speeds:
```
<script id = "script1" type="text/python">
import time
from browser import bind

@bind("#mydiv", "mousedown")
def mousedown(event):
    print("mousedown")
    t0 = time.time()
    for i in range(10000000):
       pass
    print(1000 * (time.time() - t0))

</script>
<script id = "script2" type="text/javascript">

var mydiv = document.getElementById("mydiv")

function mouseup(event){
    console.log("mouseup")
    var t0 = new Date()
    for (i = 0;i<10000000;i++){
    }
    console.log((new Date()) - t0)
}

mydiv.addEventListener("mouseup", mouseup)
</script>
```

With Chrome 76.0.3809.132 on Windows 10, the ratio is more around 30-40 than 73. But on Firefox it's only between 4 and 6 : once again it shows that Brython performs much better on Firefox. I'm afraid there is not much to be done from the Brython side to improve performance on Chrome.

**Comment by darthglowball** [comment]
I wanted to benchmark the generated Brython code by accesing `javascript.py2js`, but that generated code errors (`Uncaught ReferenceError: __BRYTHON__ is not defined`) so I wasn't able to. If that method could be fixed, I may try some benchmarking tests to see where the difference in Chrome and Firefox lay. Otherwise I think I'll use some other transpiler instead of Brython because in my case with CEF the 143x slowdown compared to Javascript is detrimental to my app.

**Comment by PierreQuentel** [comment]
The error message suggests that bython.js is not loaded in the page.
