### ISSUE TITLE
www.brython.info  is broken（ERR_CONNECTION_TIMED_OUT）

### ISSUE THREAD

**Issue by Alix00544** [brython-dev/brython#1201]
The website seems to have some problems. 
I am sure that it is not my network problem. Although I am restricted in the Chinese network, I linked to the VPN when I visited the website, which made it easy for me to access google.
Because I can't access the website, I can't watch the Console and Editor examples mentioned in the readme, which has caused me a lot of trouble.

**Comment by PierreQuentel** [comment]
Maybe it was just temporary, I have no problem reaching brython.info.
