### ISSUE TITLE
Inconsistent types, type-hierarchy for WebComponents, html tags and browser.document?

### ISSUE THREAD

**Issue by AgarwalPragy** [brython-dev/brython#1203]
1. The [documentation](https://brython.info/static_doc/en/browser.html) says that `browser.DOMNode` is a class. However, it is actually a function.
2. `browser.document` is an instance of `<dom>.DOMNode`, and not `browser.DOMNode`
3. When a WebComponent object is created, `self` is an instance of `JSObject` but not of the WebComponent class that handles its functionality.
4. `<dom>.DOMNode` and `browser.DOMNode` are not subclasses of `JSObject`
5. WebComponent instances cannot be created by calling the class, i.e. `browser.document <= MyComponent()` doesn't work. Instead, they have to be created by using the component tag in the HTML as `<my-component></my-component>`. This is bad because it makes the usage of web components different from the rest of the HTML tags available in `browser.html`.

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My App</title>
    <script type="text/javascript" src="/brython/brython.js"></script>
    <script type="text/javascript" src="/brython/brython_stdlib.js"></script>
</head>
<body onload="brython()">
    <my-component></my-component>
    <script type="text/python" src="/index.py"></script>
</body>
</html>
```

```python
import browser

class MyComponent:
    tag_name = 'my-component'

    def __init__(self):
        print('self', self)
        print('type(self)', type(self))
        print('self.__class__', self.__class__)
        print('isinstance(self, MyComponent)', isinstance(self, MyComponent))
        JSObject = type(self)
        print(isinstance(browser.document, JSObject))

__BRYTHON__.createWebComponent(MyComponent)

domnode_class_1 = browser.DOMNode
domnode_class_2 = type(browser.document)
print(domnode_class_1, domnode_class_2, domnode_class_1 == domnode_class_2)
```

```python
OUTPUT

brython.js:5979 self <WebComp object>
brython.js:5979 type(self) <class 'JSObject'>
brython.js:5979 self.__class__ <class 'JSObject'>
brython.js:5979 isinstance(self, MyComponent) False
brython.js:5979 False
brython.js:5979 <function browser.DOMNode> <class '<dom>.DOMNode'> False
```

**Comment by AgarwalPragy** [comment]
@PierreQuentel 
Hey, thanks for the fix :D 

How can I use these changes in my project? Is there a way I can create a Brython release from the latest code?

**Comment by PierreQuentel** [comment]
You can always clone the repository and use the version of __`brython.js`__ and __`brython_stdlib.js`__ there.

By the way, the commit above is applied to the new interface for web components, explained in issue #1163. With this new API, the code should be
```python
import browser
import browser.webcomponent

class MyComponent:

    def __init__(self):
        print('self', self)
        print('type(self)', type(self))
        print('self.__class__', self.__class__)
        print('isinstance(self, MyComponent)', isinstance(self, MyComponent))
        JSObject = type(self)
        print(isinstance(browser.document, JSObject))

browser.webcomponent.define("my-component", MyComponent)

domnode_class_1 = browser.DOMNode
domnode_class_2 = type(browser.document)
print(domnode_class_1, domnode_class_2, domnode_class_1 == domnode_class_2)
```
