### ISSUE TITLE
Descriptor protocol is broken unless class using it subclasses `object` explicitly

### ISSUE THREAD

**Issue by jafd** [brython-dev/brython#1204]
Consider the following code:
```
class Knob:
    def __init__(self, left=-1000, right=1000, init=0):
        self.val = init
        self.left = left
        self.right = right

    def __set__(self, obj, val):
        direction, howmuch = val.split(' ')
        if direction == 'L':
            print(f"Turning the knob left by {howmuch}")
            v = self.val - int(howmuch)
        elif direction == 'R':
            print(f"Turning the knob right by {howmuch}")
            v = self.val - int(howmuch)
        if v > self.right:
             v = self.right
        if v < self.left:
             v = self.left
        self.val = v
        print(f"New knob value: {self.val}")

    def __get__(self, obj, objtype):
        return self.val


class Dummy:
    knob = Knob()

    def turn(self):
        self.knob = "L 1"


x = Dummy()
print(f"x.knob = {x.knob}")
x.knob = "L 123"
print(f"x.knob = {x.knob}")
x.knob = "L 1"
print(f"x.knob = {x.knob}")
x.turn()
print(f"x.knob = {x.knob}")
```
Under CPython, it gives:
```
x.knob = 0
Turning the knob left by 123
New knob value: -123
x.knob = -123
Turning the knob left by 1
New knob value: -124
x.knob = -124
Turning the knob left by 1
New knob value: -125
x.knob = -125
```
Under Brython 3.7.4:
```
x.knob = 0
Turning the knob left by 123
New knob value: -123
x.knob = -123
Turning the knob left by 1
New knob value: -124
x.knob = -124
x.knob = L 1
```

`x.__dict__` at the end in CPython: `{}`
`x.__dict__` at the end in Brython 3.7.4: `{'knob': 'L 1'}`

Welp :(

**Comment by jafd** [comment]
Having to write in the example above
```
self.__class__.knob.__set__(self, 'L 1')
```
will sure make it work as intended, but is too tiresome and not readable enough for my liking.

**Comment by jafd** [comment]
This breakage only exists if you access `self`.
For example, if I rewrite the `turn()` method in the example above to:

```
def turn(this):
    self = this
    this.knob = 'L 1'
``` 

it will work.

Still a bug.

**Comment by jafd** [comment]
Okay, seems like I've found what the _real_ bug is:

Brython, despite being Python 3, differentiates between old-style and new-style classes. `class Dummy(object):` will work properly, `class Dummy:` won't.

Wonder why, since Python 3 doesn't distinguish those anymore.

**Comment by PierreQuentel** [comment]
@jafd Many thanks for the report !

In methods, there is an optimisation when setting an attribute to `self`, based on a set of criteria. The bug was in the evaluation of one of these criteria, but it was masked by another test, the presence of an explicit parent in the class definition.
