### ISSUE TITLE
[Feature Request] stdlib xml support

### ISSUE THREAD

**Issue by Ordiel** [brython-dev/brython#1206]
Please add/implement/support (get working) xml standard libraries:

* Lib\xml
* Lib\xmlrpc

I think being the type of project it is having those libraries working would be of amazing help.

[This page](https://brython.info/static_doc/en/stdlib.html) clearly states they are not supported; could we get an ETA? or where to see whats its order in priority (if any)?

**Comment by PierreQuentel** [comment]
I agree that it would be nice to have these packages in the stdlib, but they rely on a library, __`pyexpat`__, which is not written in Python and for which I couldn't find a pure-Python version. I'm afraid you will have to use the technique explained in the [demo page](http://www.brython.info/demo.html?lang=fr#), section "Parse an XML document".

**Comment by Ordiel** [comment]
It does help. Thanks!

Yet it would still be nice to have them since it would facilitate moving logic already defined from the backend (flask/django) to the frontend (brython) of an application or even share it ensuring there is no code duplication lets say on your validations (this way the same validation on the back can be used on the front)

**Comment by PierreQuentel** [comment]
I have to close the issue since I don't think it's currently possible to add these libraries.

**Comment by Ordiel** [comment]
Agree. Thanks Pierre!
