### ISSUE TITLE
Pip and NPM wrong version

### ISSUE THREAD

**Issue by Ordiel** [brython-dev/brython#1208]
Hi, the [pip distribution](https://pypi.org/project/brython/)  and the [npm one](https://www.npmjs.com/package/brython) both say 3.7.5, yet when using them to install/update Brython I am always getting 3.7.4 (this from checking on the console with `__BRYTHON__.version_info`) 

Thanks in advance

**Comment by PierreQuentel** [comment]
The Brython version number is given by [sys.implementation](https://docs.python.org/3/library/sys.html#sys.implementation). `version_info` should be 3.7.0.

**Comment by Ordiel** [comment]
My bad, it is giving 3.7.0 (c&p error) and thanks, that clarification solves this
