### ISSUE TITLE
Unable to reload page having Brython WebComponents

### ISSUE THREAD

**Issue by Ordiel** [brython-dev/brython#1213]
## Issue/Question
When trying to reload the python scripts of a page having Brython WebComponents in it, I am getting the following error, apparently caused by trying to define twice the same web component to the CustomElementRegistry:

`Traceback (most recent call last):
RuntimeError: NotSupportedError: Failed to execute 'define' on 'CustomElementRegistry': the name "fancy-element" has already been used with this registry`

This might be a question rather than an issue, but if not this way, how can I reload the scripts of a page that uses WebComponents?

**Workaround:**

I tried various methods to avoid redefining the element without much luck, at the end what worked was to remove all the script tags already loaded from the document, then execute `window.brython(0)` then add them back to the page (for correctness of the record of whats loaded)

## Steps to Replicate

1. Add the following files to a folder
2. On the root of that folder `python3 -m http.server`
3. Go to localhost:8000
4. Click the button 
5. See the error on console output

**index.html**

```
<!DOCTYPE html>
<html>
<head>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/brython/3.7.5/brython.js"></script>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/brython/3.7.5/brython_stdlib.js"></script>
	<script type="text/python" src="/fancy-element.py"></script>
	<script type="text/python" src="/ctrlr.py"></script>
</head>
<body onload="brython(0)">
	<fancy-element></fancy-element>
	<button id="btn">click me</button>
</body>
</html>
```

**fancy-element.py**

```
#!/usr/bin/env python3

from browser import webcomponent

from browser.html import B, BR

class FancyElement():

	def __init__(self):
		self.shadow = self.attachShadow({'mode': 'open'})
		self.shadow <= B("I'm fancy") + BR()

webcomponent.define("fancy-element", FancyElement)
```

**ctrlr.py**

```
#!/usr/bin/env python3

from browser import document, window

def reloadStuff(ev=None):
	# imagine I reload some of my page content that requires other script to work, lets say:
	#
	# <script type="text/python" src="/abc.py"></script>
	#
	# add it to the page:
	#
	# document.head <= myScriptElement
	#
	# reload:
	window.brython(1)

document['btn'].addEventListener("click", reloadStuff)
```

**Comment by PierreQuentel** [comment]
This is because of
```python
window.brython(1)
```
When you load the HTML page, the function `brython()` is called a first time. It runs alls the scripts in the page that have the attribute `type="text/python"`. __`fancy-element.py`__ is one of these scripts, so the line
```python
webcomponent.define("fancy-element", FancyElement)
```
is executed.

If you hit the button and run `reloadStuff()`, you run the same function a second time _without reloading the page_, and the browser complains that you define a web component a second time.

If you want to run another script, you can load it by `open()` or `ajax.get()` and `exec()` its content.

**Comment by Ordiel** [comment]
Nice! thanks for your quick response, will give it a try to fetch the script using ajax the document and `exec` it. Will let you know the outcome.

**Comment by Ordiel** [comment]
It end up being easier within the source file of the web container to add a flag to the window object to preserve a reference of already loaded WebComponents on which I check before performing a call to the `define` method.

Would it be possible to delegate this to the library, more specifically the `webcomponent.define` method? Maybe storing it withing the `__BRYTHON__` object or globaly (`window`). This so that it is not necessary to add extra logic to the web component files just to handle this scenario

I am not sure if that would break any specification of WebComponents

**Comment by PierreQuentel** [comment]
I think that this would be too much magic for a relatively minor use case, and it would actually break the specification.

Another option (better IMO) would be to add a function in __`browser.webcomponent`__ to test if a name is already set to a component, using [customElement.get()](https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/get). The code in __`fancy-element.py`__ could end with:

```python
if not webcomponent.get("fancy-element"):
    webcomponent.define("fancy-element", FancyElement)
```

Would that be ok ?

**Comment by Ordiel** [comment]
That would be fantastic, that way devs are not in charge of adding stuff to the window object or somewhere else, and its ovious where to check for previously loaded components. Two lines addition to each WebComponent (with this particular use case) is not bad at all

**Comment by PierreQuentel** [comment]
Can we close the issue ?

**Comment by Ordiel** [comment]
Sorry for the late reply, sure. Thanks Pierre!
