### ISSUE TITLE
script with src and type doesn't validate

### ISSUE THREAD

**Issue by thorstenkampe** [brython-dev/brython#1214]
According to the documentation
> If the Python program is large, another option is to write it in a separate file, and to load it using the src attribute of the script tag 

Unfortunately, this will result in the following validation error by the W3C checker:
> A script element with a src attribute must not have a type attribute whose value is anything other than the empty string, a JavaScript MIME type, or module.

Is there a solution for this?

**Comment by PierreQuentel** [comment]
Do you mean the validator at [https://validator.w3.org/](https://validator.w3.org/) ?
It shows all sorts of warnings and errors, including the one you mention. I don't think there is any solution for this one : the "text/python" type is required by the Brython engine to identify the Python scripts and get them with an Ajax call.

**Comment by PierreQuentel** [comment]
BTW, this validator finds no less than 79 errors or warnings on www.python.org ;-)

**Comment by thorstenkampe** [comment]
The [HTML documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script) says about the type attribute for the script tag:
> Any other value: The embedded content is treated as a data block which won't be processed by the browser. Developers must use a valid MIME type that is not a JavaScript MIME type to denote data blocks. The src attribute will be ignored.

According to this `src` plus `type="text/python"` would be valid. I'm going to close this ticket.
