### ISSUE TITLE
documentation for cache option browser and none

### ISSUE THREAD

**Issue by thorstenkampe** [brython-dev/brython#1215]
I forgot where I found the cache option for loading brython (like in `brython({cache: 'browser'})`). Is there some documentation about this option?

**Comment by PierreQuentel** [comment]
@thorstenkampe 
I have searched even in very old versions of Brython and couldn't find any documentation...
The original idea was to specify if, when importing a file, the Ajax request to get the file content should use the browser cache or not. I don't think it's relevant, if the source file has changed, when reloading the page the new version should be changed in any case. Unless you disagree, the option should be removed.

**Comment by thorstenkampe** [comment]
Sure, go ahead.
