### ISSUE TITLE
pygame package has copies of the same files with different case

### ISSUE THREAD

**Issue by glyph** [brython-dev/brython#122]
This means that when you clone the repo on a Mac (or Windows), you get this:

```console
$ git clone https://github.com/brython-dev/brython
Cloning into 'brython'...
remote: Counting objects: 5643, done.
remote: Compressing objects: 100% (2319/2319), done.
remote: Total 5643 (delta 3287), reused 5577 (delta 3244)
Receiving objects: 100% (5643/5643), 10.58 MiB | 379.00 KiB/s, done.
Resolving deltas: 100% (3287/3287), done.
Checking connectivity... done.
$ cd brython/
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   src/Lib/site-packages/pygame/Rect.py
	modified:   src/Lib/site-packages/pygame/Surface.py

no changes added to commit (use "git add" and/or "git commit -a")
$ 
```

**Comment by JamesHutchison** [comment]
module names shouldn't have an uppercase letter.

What's the point of including pygame anyways?

**Comment by glyph** [comment]
@JamesHutchison - Presumably it is a *heavily* modified subset of PyGame which talks to browser APIs.

**Comment by glyph** [comment]
I'm not proposing that PyGame be removed; until #119 is resolved it's not really clear how people would get a 3rd-party module and install it into their brython environment.

**Comment by earney** [comment]
glyph,

The uppercase module names are my doing.  I'll look into modifying these so they are all lower case.

**Comment by glyph** [comment]
@earney thanks!

**Comment by earney** [comment]
@glyph, I have removed Rect.py and Surface.py, which I believe are the only uppercase filenames.    I hope to get back to developing pygame for brython soon.

**Comment by glyph** [comment]
Thanks!
