### ISSUE TITLE
Convert JS String to a Python string

### ISSUE THREAD

**Issue by VoxelPrismatic** [brython-dev/brython#1221]
Please add a function to convert a JS string to a Python string. I already did some work and figured this out:
```python
def pyStr(js_string):
    return "".join(js_string[int(index)] for index in dir(js_string))
```

**Comment by PierreQuentel** [comment]
The standard way of using JS objects in Brython is through `browser.window`:
```xml
<script>
var js_string = "Pleurez, doux alcyons, ô vous, oiseaux sacrés"
</script>

<script type="text/python">
from browser import window

assert window.js_string == "Pleurez, doux alcyons, ô vous, oiseaux sacrés"
assert isinstance(window.js_string, str)
</script>
```
Can you give an example where this doesn't work as you expect ?

**Comment by VoxelPrismatic** [comment]
Actually I thought it would be easier to understand when you are working in python only
```python
import javascript as js
from browser import window
# 'from re import sub' is a bit slow, so I made my own equivalent function
def sub(regex_str, format_str, input_str):
    jsInputStr = js.String.new(input_str)
    jsRegExp = js.RegExp.new(regex_str)
    while jsInputStr.search(jsRegExp) != -1:
        jsInputStr = js.String.new(jsInputStr.replace(jsRegExp, format_str))
    return jsInputStr

def pyStr(jsStringObject):
    return ''.join(jsStringObject[int(index)] for index in dir(jsStringObject))
    # jsStringObject is not an iterable, but dir(jsStringObject) returns the indecies of the string 
    # jsStringObject[:] returns slice(None, None, None) rather than the string
js_str = sub(r"(\d)", "$1$1", "4545") # Returns '44554455' as a JSObject
print(js_str) # Should print '<String object>' without the quotes
py_str = pyStr(js_str) # window.js_str doesn't make much sense here, although it does work
print(py_str) # Should print '44554455' without the quotes
```
There are certainly better examples, but this is just one that I actually use

**Comment by PierreQuentel** [comment]
As you know, Javascript has 2 types of strings : the "native" strings created by `var x = "abc"` , and the instances of the `String` class, created by `var y = new String("abc")`.

In Brython, `window.x` is an instance of `str` and `window.y` is an instance of `JSObject` wrapping the Javascript object.

Such instances of `JSObject`, like the one you create in function `sub()` with `window.String.new()`, can be converted to a Python str simply by calling their `toString()` method
```
py_str = js_str.toString()
```

BTW, I couldn't run the example, the loop inside the `sub()` function is infinite.

**Comment by VoxelPrismatic** [comment]
Oh, I don't actually use JavaScript and didn't realize the `toString()` function was a thing. Thanks!
Also the loop in the `sub()` function is necessary to catch all instances of the RegEx, otherwise it would stop after the first one.
