### ISSUE TITLE
"ReferenceError: Can't find variable: brython"

### ISSUE THREAD

**Issue by VoxelPrismatic** [brython-dev/brython#1222]
Brython 3.8.0 does not have the Brython function for some strange reason.
I am using cdnjs: 
```html
<script type="text/javascript" 
    src="https://cdnjs.cloudflare.com/ajax/libs/brython/3.8.0/brython.min.js">
</script>
```

**Comment by PierreQuentel** [comment]
Thanks for reporting this. cdnjs is not yet updated to version 3.8.0, so trying to load _brython/3.8.0/brython.min.js_ results in a 404 error... Hopefully it will be online soon.

**Comment by PierreQuentel** [comment]
It looks like cdnjs has not been updated for a few days now. I have changed the CDN to jsDeliv on the home page.
