### ISSUE TITLE
eval("[x for x in range(3)]") causes <Javascript TypeError>: $B.frames_stack.length is not a function [v3.8.0]

### ISSUE THREAD

**Issue by dbader** [brython-dev/brython#1223]
Thanks for the lovely project. I'm using Brython to power the code runner questions at https://realpython.com/quizzes/ and it's been a very successful & fun project so far. 

I'm running into an issue when `eval()`-ing list comprehensions. Here's a minimal example that causes the error inside http://brython.info/tests/editor.html:

Code to reproduce:
```python
eval("[x for x in range(3)]")
```

Brython console output:
```
Traceback (most recent call last):
  File http://brython.info/tests/editor.py, line 115, in run
    exec(src, ns)
  File <string>, line -1, in <module>
  File <string>, line -1, in <module>
Exception: <Javascript TypeError>: $B.frames_stack.length is not a function
<completed in  10.00 ms>
```

Browser JS console output:
```
Javascript exception: TypeError: $B.frames_stack.length is not a function
    at eval (eval at $$eval (py_builtin_functions.js:688), <anonymous>:9:37)
    at $$eval (py_builtin_functions.js:688)
    at eval (eval at $$eval (py_builtin_functions.js:680), <anonymous>:12:29)
    at $$eval (py_builtin_functions.js:684)
    at exec (py_builtin_functions.js:771)
    at run35 (eval at run_py (py_import.js:252), <anonymous>:926:43)
    at lambda_lc1grh7c_514 (eval at $B.loop (loaders.js:332), <anonymous>:168:107)
    at HTMLButtonElement.<anonymous> (py_dom.js:1068)
py_exceptions.js:461 (4) ["$exec_52", {…}, "$exec_52", {…}]0: "$exec_52"1: {__name__: "__main__", __package__: "", __annotations__: {…}}2: "$exec_52"3: {__name__: "__main__", __package__: "", __annotations__: {…}}length: 4__proto__: Array(0)
py_exceptions.js:462 recursion error ? false
```

* Brython version: 3.8.0 (but also happens on 3.7.5)
* Browser version: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"

**Interestingly this only happens when "Debug" is unchecked**. It seems to work fine with "Debug" enabled.

<img width="1334" alt="Screenshot 2019-10-17 11 42 25" src="https://user-images.githubusercontent.com/306708/67037877-3e918280-f0d3-11e9-9847-d7f22c0a9b1c.png">

**Comment by PierreQuentel** [comment]
Thanks for the report, there was a ";" missing somewhere...
