### ISSUE TITLE
Python's repr and str function should ignore any instance attributes for __repr__ and __str__.

### ISSUE THREAD

**Issue by ikhaliq15** [brython-dev/brython#1229]
Calling repr or str on an instance of an object should directly call the class attribute repr and ignore any instance attributes named __repr__ or __str__. Below is a documented difference between CPython and Brython interpreter. 

Here is what the CPython interpreter shows when the instance has its own __repr__ and __str__ attributes. 
![Screen Shot 2019-10-26 at 2 19 05 PM](https://user-images.githubusercontent.com/6558567/67626161-50260900-f7fc-11e9-8825-70c7ed902adf.png)

Here is what the output is from the Brython interpreter running on [https://brython.info/console.html](https://brython.info/console.html). 
![Screen Shot 2019-10-26 at 2 20 41 PM](https://user-images.githubusercontent.com/6558567/67626179-9d09df80-f7fc-11e9-89d0-d14e666e6a77.png)

This is defined in the python docs under special method lookup.
[https://docs.python.org/3/reference/datamodel.html#special-method-lookup](https://docs.python.org/3/reference/datamodel.html#special-method-lookup)

**Comment by PierreQuentel** [comment]
@ikhaliq15 
Many thanks for reporting the bug and pointing to the documentation, I was not aware of this lookup rule for "implicit invocations". I have changed the behaviour of many built-in functions, but maybe forgot a few of them.

**Comment by ikhaliq15** [comment]
Not sure if this should be reported as a new issue, but I saw that the code relies on the use of an instance's repr for the builtin quit/exit functions. The quit and exit objects appear to be instances of the Quitter class in _sitebuiltins. The implementation of Quitter class in cpython can be found here. https://github.com/python/cpython/blob/master/Lib/_sitebuiltins.py

Quitter Implementation:
![Screen Shot 2019-10-27 at 2 29 08 PM](https://user-images.githubusercontent.com/6558567/67642165-3b15ac80-f8c6-11e9-959d-234ce15038cc.png)

And then in the site.py module, the setquit() function creates two objects in the builtin for exit and quit which are instances of that Quitter class. And when the site package is loaded, setquit() is called. https://github.com/python/cpython/blob/master/Lib/site.py

![Screen Shot 2019-10-27 at 2 34 35 PM](https://user-images.githubusercontent.com/6558567/67642250-06562500-f8c7-11e9-9170-e946d29ac41e.png)


CPython.
![Screen Shot 2019-10-27 at 2 10 14 PM](https://user-images.githubusercontent.com/6558567/67641920-b0cc4900-f8c3-11e9-8078-f0556a8633ca.png)
![Screen Shot 2019-10-27 at 2 15 22 PM](https://user-images.githubusercontent.com/6558567/67641977-4e277d00-f8c4-11e9-9db7-05094208f1d9.png)


Brython after the changes to special method lookup.
![Screen Shot 2019-10-27 at 2 10 43 PM](https://user-images.githubusercontent.com/6558567/67641923-b4f86680-f8c3-11e9-9beb-cb37c8910577.png)
![Screen Shot 2019-10-27 at 2 15 42 PM](https://user-images.githubusercontent.com/6558567/67641976-4962c900-f8c4-11e9-9d79-2cb787395e70.png)

**Comment by ikhaliq15** [comment]
@PierreQuentel not sure if notifications are on for closed issues. should i open a new issue for this one?

**Comment by PierreQuentel** [comment]
@ikhaliq15 
Yes, I got the notifications. You are right that Brython doesn't work like CPython in this case, but `quit()` and `exit()` are not really relevant in the browser context, because there is no concept of exiting from a program to accept new commands on the command line; the equivalent would be to close the tab or load another page into it.
