### ISSUE TITLE
The type error for the absolute value function shows the javascript object type, not the python one.

### ISSUE THREAD

**Issue by ikhaliq15** [brython-dev/brython#1232]
When I put pass in an incorrect object type to the absolute value function, the type error that is returned shows the javascript type of the object such as 'string!' or '[object Object]' instead of 'str' and 'function'.

CPython:
![Screen Shot 2019-10-28 at 4 05 04 PM](https://user-images.githubusercontent.com/6558567/67724739-366ff780-f99d-11e9-981b-b5a407b64a97.png)

Brython:
![Screen Shot 2019-10-28 at 4 05 10 PM](https://user-images.githubusercontent.com/6558567/67724746-3ec83280-f99d-11e9-83e7-5d5b054c97f0.png)

**Comment by PierreQuentel** [comment]
Thanks for this report and the previous one :-)
