### ISSUE TITLE
Brython raises ImportError instead of ModuleNotFoundError

### ISSUE THREAD

**Issue by schmave** [brython-dev/brython#1237]
This code:

```python
import foo
```

raises an ImportError in Brython, but as of CPython 3.6, it raises a ModuleNotFoundError. Here it is in the docs:

https://docs.python.org/3/library/exceptions.html#ModuleNotFoundError

Lib/subprocess.py relies on this behavior.

**Comment by PierreQuentel** [comment]
Thanks for mentioning this, I had missed this change in Python 3.6.

It is not very well documented, if I understand correctly, `ModuleNotFoundError` is raised in two cases:
- `import foo` and module __`foo.py`__ doesn't exist
- `import a.b` and module a exists but is not a package; in this case, `from a import b` still raises `ImportError`
