### ISSUE TITLE
test_repr in Lib/test/test_dict fails

### ISSUE THREAD

**Issue by schmave** [brython-dev/brython#1238]
Here's a simplified version of the test:

```python
class Exc(Exception): pass

class BadRepr(object):
    def __repr__(self):
        raise Exc()

d = {1: BadRepr()}
repr(d)
```

Calling `repr(d)` is supposed to raise `Exc`, but instead Brython raises `AttributeError`.

**Comment by PierreQuentel** [comment]
This was fixed a few days ago in commit 3b6777c823c16c746703593515586dd6bb2e1404.
Thank you !
