### ISSUE TITLE
In Brython 3.0.2, loading a Python script with multiline string causes syntax error

### ISSUE THREAD

**Issue by pixellator** [brython-dev/brython#124]
I don't have the following problem with Brython 2.2.1, but do in the 3.x.y versions.

In my HTML file, after loading and starting Brython, I have this line: <script type="text/python" src="Mondrian.py"></script>

And at the beginning of that file is a multiline string. The first two lines of the file are these:

"""Mondrian.py
A SOLUZION problem formulation.

(the multiline string goes on for a few more lines, etc.) Here is the error message I am getting in the Chrome (Windows 7) browser's JavaScript console:

SyntaxError: invalid syntax Traceback (most recent call last): module main line 164 subdivision_operators =\ module main line 2 A SOLUZION problem formulation. ^ brython.js:4329 Uncaught Error: invalid syntax

Thanks for your attention -- Steve Tanimoto

**Comment by PierreQuentel** [comment]
Could you provide an example of a HTML file that causes the problem ? You explanation is not clear enough for us to help

**Comment by pixellator** [comment]
I see that it might not be the multi-line string causing the problem, but
something else.  I don't know. The error message mentions line 2 which is
in the multiline string.  Here is the .html file and the .py file.   To try
it, just edit the src=brython.js part to match your path to Brython.
  Thanks very much for considering this.


On Mon, Feb 2, 2015 at 1:01 PM, Pierre Quentel <notifications@github.com>
wrote:

> Could you provide an example of a HTML file that causes the problem ? You
> explanation is not clear enough for us to help
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brython-dev/brython/issues/124#issuecomment-72536868>.
>
"""Mondrian.py
A SOLUZION problem formulation.
The XML-like tags used here may not be necessary, in the end.
But for now, they serve to identify key sections of this 
problem formulation.  It is important that COMMON_CODE come
before all the other sections (except METADATA), including COMMON_DATA.
"""
#<METADATA>
SOLUZION_VERSION = "0.1"
PROBLEM_NAME = "The Mondrian Design Problem"
PROBLEM_VERSION = "0.1"
PROBLEM_AUTHORS = ["S. Tanimoto"]
PROBLEM_CREATION_DATE = "08-JUN-2014"
PROBLEM_DESC=\
"""This version is mainly for the Brython version of the solving client
and the Brython version of Python.
However, it should all be generic Python 3, and this file is intended
to work a future Python+Tkinter client that runs on the desktop.
Anything specific to the Brython context should be in the separate 
file MondrianVisForBRYTHON.py, which is imported by this file when
being used in the Brython SOLUZION client."""
#</METADATA>


print("Hello from Mondrian.py")

#<COMMON_DATA>
#</COMMON_DATA>

#<COMMON_CODE>
def copy_state(s):
  # Performs an appropriately deep copy of a state,
  # for use by operators in creating new states.
  news = {}
  boxlist = []
  for box in s["boxes"]:
    boxlist.append(box.copy())
  news["boxes"]=boxlist
  news["selected"]=s["selected"]
  return news

def describe_state(state):
  """ Produces a textual description of a state.
      Might not be needed in normal operation with GUIs."""
  txt = "\n"
  for box in state["boxes"]:
      txt += str(box) + "\n"
  txt += "selected: "+state["selected"]
  return txt

class MondRect:
  """A box that represents a basic structural element in this
     particular form of graphic art."""
  def __init__(self, x1, y1, x2, y2, parentRect):
    self.x1 = x1
    self.y1 = y1
    self.x2 = x2
    self.y2 = y2
    self.parentRect = parentRect # Not actually used in this version,
     # but which could be useful if a richer set of navigation operators
     # were to be added.
    self.color = "white" # Default color is white.

  def setColor(self, color):
    self.color = color

  def subdivide(self, use_horizontal_divider, fraction):
    """This method returns a list of
     two new rectangles, obtained by subdividing, either
     horizontally or vertically, where the subdivision
     occurs so as to make the first rectangle have an
     area that is the given fraction of the original."""
    if use_horizontal_divider:
      ymid = self.y1 + fraction*(self.y2 - self.y1)
      R1 = MondRect(self.x1, self.y1, self.x2, ymid, self)
      R2 = MondRect(self.x1, ymid, self.x2, self.y2, self)
    else:
      xmid = self.x1 + fraction*(self.x2 - self.x1)
      R1 = MondRect(self.x1, self.y1, xmid, self.y2, self)
      R2 = MondRect(xmid, self.y1, self.x2, self.y2, self)
    return [R1, R2]
     
  def copy(self):
    newb = MondRect(self.x1, self.y1, self.x2, self.y2, self.parentRect)
    newb.color = self.color
    return newb

def goal_test(s):
  """Somewhat arbirarily, we'll say a goal has been reached
     when the number of rectangles is at least 6."""
  nrect = len(s["boxes"])
  return nrect > 5

def goal_message(s):
  return "A masterpiece!"

class Operator:
  def __init__(self, name, precond, state_transf):
    self.name = name
    self.precond = precond
    self.state_transf = state_transf

  def is_applicable(self, s):
    return self.precond(s)

  def apply(self, s):
    return self.state_transf(s)

def selected_box_is_large_enough(s):
  sb = s["boxes"][s["selected"]]
  dx = sb.x2-sb.x1
  dy = sb.y2-sb.y1
  THRESHOLD = 0.04
  if dx < THRESHOLD: return False
  if dy < THRESHOLD: return False
  return True

def subdivide(state, hv, fraction):
  boxlist = state["boxes"]
  sel = state["selected"]
  selectedBox = boxlist[sel]
  horiz = True
  if hv=="vertical": horiz=False
  newBoxes = selectedBox.subdivide(horiz, fraction)
  newBoxList = boxlist[:sel]+newBoxes+boxlist[sel+1:]
  newState = copy_state(state)
  newState["boxes"]=newBoxList
  return newState

def change_selection(state, incr):
  newState = copy_state(state)
  newState["selected"]+=incr
  return newState

def recolor(state, color):
  newState = copy_state(state)
  box = newState["boxes"][newState["selected"]]
  box.setColor(color)
  return newState
#</COMMON_CODE>

#<INITIAL_STATE>
INITIAL_STATE =\
  {"boxes":[MondRect(0.0, 0.0, 1.0, 1.0, None)],
   # The list of boxes give a structural representation of the painting
   # The initial state has one large box, ready to be subdivided.
   "selected": 0}

# The following is some extra stuff for trying to make the template
# work with Javascript.
"""
try:
  from browser import window
  window.SOLUZION_INITIAL_STATE = INITIAL_STATE
  print("Inside of the template Mondrian.py, the INITIAL_STATE is ")
  print(INITIAL_STATE)
except e:
  print("There was an exception when trying to communicate back from Python to Javascript.")
  print(e)
"""
#</INITIAL_STATE>

#<OPERATORS>
available_fractions = [0.25, 0.3333, 0.5, 0.6667, 0.75]
subdivision_operators =\
  [Operator("Divide with "+hv+" line at fraction "+str(f),
            lambda s: selected_box_is_large_enough(s),
            lambda s: subdivide(s, hv, f))
   for hv in ["horizontal", "vertical"]
   for f in available_fractions]
selection_operators =\
  [Operator("Select next box for alteration",
            lambda s: s["selected"] < len(s["boxes"])-1,
            lambda s: change_selection(s, 1)),
   Operator("Select previous box for alteration",
            lambda s: s["selected"] > 0,
            lambda s: change_selection(s, -1))]
color_operators =\
  [Operator("Recolor the selected box to "+color,
            lambda s: not color==s["boxes"][s["selected"]].color,
            lambda s: recolor(s, color))
  for color in ["white", "red", "blue", "yellow"]]
OPERATORS = subdivision_operators + selection_operators + color_operators
#</OPERATORS>

#<GOAL_TEST> (optional)
GOAL_TEST = lambda s: goal_test(s)
#</GOAL_TEST>

#<GOAL_MESSAGE_FUNCTION> (optional)
GOAL_MESSAGE_FUNCTION = lambda s: goal_message(s)
#</GOAL_MESSAGE_FUNCTION>

#<STATE_VIS>
#if "BRYTHON" in globals():
# from MondrianVisForBrython import set_up_gui as set_up_user_interface
# from MondrianVisForBrython import render_state_svg_graphics as render_state

# if 'TKINTER' in globals(): from MondrianVisForTKINTER import set_up_gui
#</STATE_VIS>

**Comment by pixellator** [comment]
Here is the html file that was supposed to go with the above post.  

<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

<title>Multiline Strings in Brython Code</title>


<script type="text/javascript" src="../libs/Brython302/brython.js"></script>

<script type="text/javascript">brython()</script>

<script type="text/python">
"""First multiline string
is here."""

print("Hello from Brython")
from browser import alert

alert("Here we are starting to process a Python script in Brython.")

"""This is a multiline string in Python, and it should not
cause any problem in Brython."""

alert(" and the multiline strings within an embedded Python script must be OK if we get this far.")
</script>


<script type="text/python" src="test.py"></script>

</head>

<body onload="brython(1)">
<h1>Multiline Strings in Brython Code</h1>
The purpose of this page is to find out whether the latest versions of
 Brython object to multiline strings or any others normal Python syntax.

</body>
</html>

**Comment by pixellator** [comment]
Let me try to get it "unformatted"
<pre>
File Edit Options Buffers Tools HTML SGML Help
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

<title>Multiline Strings in Brython Code</title>


<script type="text/javascript" src="../libs/Brython302/brython.js"></script>

<script type="text/javascript">brython()</script>

<script type="text/python">
"""First multiline string
is here."""

print("Hello from Brython")
from browser import alert

alert("Here we are starting to process a Python script in Brython.")

"""This is a multiline string in Python, and it should not
cause any problem in Brython."""

alert(" and the multiline strings within an embedded Python script must be OK if we get this far.")
</script>


<script type="text/python" src="test.py"></script>

</head>

<body onload="brython(1)">
<h1>Multiline Strings in Brython Code</h1>
The purpose of this page is to find out whether the latest versions of
 Brython object to multiline strings or any others normal Python syntax.

</body>
</html>



<\pre>

**Comment by pixellator** [comment]
Here is a URL to the html.  I also have the python file and Brython there, so you can see the issue in the JavaScript console.
http://socrates.cs.washington.edu/tanimoto/brython-testing/test.html

**Comment by PierreQuentel** [comment]
Steve,

Thanks for the report. The problem was not in the multiline string, it was related to the lambdas inside  list comprehensions, like in

```python
subdivision_operators =\
  [Operator("Divide with "+hv+" line at fraction "+str(f),
            lambda s: selected_box_is_large_enough(s),
            lambda s: subdivide(s, hv, f))
   for hv in ["horizontal", "vertical"]
   for f in available_fractions]
```

The bug was raised with a confusing error message

**Comment by pixellator** [comment]
Thanks very much.  If you have any suggestions for how best to resolve the
lambda issue, please let me know.
