### ISSUE TITLE
[Web Components] observedAttributes

### ISSUE THREAD

**Issue by kkinder** [brython-dev/brython#1242]
WebComponents' `observedAttributes` static method does not work in a Python-based web component:

```
<script type="text/python">
from browser import html, webcomponent

class TestingStuff:
    def __init__(self):
        shadow = self.attachShadow({'mode': 'open'})

        shadow <= html.B('data-something is ' + self.attrs.get('data-something', '(Nothing)'))

    def attributeChangedCallback(self, name, oldValue, newValue):
        print('Attribute Changed', name, oldValue, newValue)

    @classmethod
    def observedAttributes(cls):
        print('observedAttributes called')
        return ['data-something']


webcomponent.define("testing-stuff", TestingStuff)

</script>

<testing-stuff id="my-foobar" data-something="spam"></testing-stuff>

<script type="text/python">
from browser import document


document['my-foobar'].setAttribute('something', 'eggs')
</script>
```

What should happen here is that `observedAttributes` should be called, which tells the browser which attribute changes to alert the component for via `attributeChangedCallback`.

My suspicion is that the _static get_ of the JavaScript definition isn't being translated into the classmethod for the Python class.

**Comment by PierreQuentel** [comment]
Thanks for the report @kkinder. I have modified the example in the gallery to include your example.

BTW, besides the standard DOM `element.setAttribute(name, value)` you can also write
```python
element.attrs["name"] = value
```
