### ISSUE TITLE
Test GrammarTests.test_former_statements_refer_to_builtins fails

### ISSUE THREAD

**Issue by schmave** [brython-dev/brython#1249]
A test in Lib/test/test_grammar.py is failing. Last time I ran the tests it was passing, but I think now that maybe it was passing because of some other bug that hid the failure. Not sure.

Here's a version of the test that can be run directly in the Brython editor:

```python
import unittest

class GrammarTests(unittest.TestCase):
    # Check the heuristic for print & exec covers significant cases
    # As well as placing some limits on false positives
    def test_former_statements_refer_to_builtins(self):
        keywords = "print", "exec"
        # Cases where we want the custom error
        cases = [
            "{} foo",
            "{} {{1:foo}}",
            "if 1: {} foo",
            "if 1: {} {{1:foo}}",
            "if 1:\n    {} foo",
            "if 1:\n    {} {{1:foo}}",
        ]
        for keyword in keywords:
            custom_msg = "call to '{}'".format(keyword)
            for case in cases:
                source = case.format(keyword)
                with self.subTest(source=source):
                    with self.assertRaisesRegex(SyntaxError, custom_msg):
                        exec(source)
                source = source.replace("foo", "(foo.)")
                with self.subTest(source=source):
                    with self.assertRaisesRegex(SyntaxError, "invalid syntax"):
                        exec(source)

runner = unittest.TextTestRunner()
runner.run(GrammarTests('test_former_statements_refer_to_builtins'))
```

It's testing to see that `print foo` and `exec foo` (and a bunch of other variations) raise a special message something like this:

```
>>> exec 123
  File "<stdin>", line 1
    exec 123
           ^
SyntaxError: Missing parentheses in call to 'exec'
>>> print {123}
  File "<stdin>", line 1
    print {123}
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print({123})?
```

This doesn't seem hugely important to me, but since it used to pass and there is a test for it, I thought I'd report it.

**Comment by schmave** [comment]
Ah, I see now that the @unittest.skip statement was recently removed from this test, so you're probably already working on it!

**Comment by PierreQuentel** [comment]
@schmave 
The test should pass now, as well as a few others in __`test_grammar.py`__. For this test, I admit that I don't really understand why `print {1:(foo.)}` raises a `SyntaxError` with just "invalid syntax" and `print {1: foo}` also raises a `SyntaxError` but with a different message... This should probably be implementation-specific.
