### ISSUE TITLE
Brython & Angular

### ISSUE THREAD

**Issue by piedacoulisse** [brython-dev/brython#1252]
Hello,

Brython seams to be a great tool but I have some problems to include it in an Angular project.

I import in angular.json :
- brython.js
- brython_stdlib.js

When i want to create a new component the <script type="text/python"> doesn't work in the HTML file.

Do you have any solution ?

Thanks,

Florent

**Comment by PierreQuentel** [comment]
Sorry, I don't know Angular at all, so I can't help for this specific issue.

**Comment by frederickavita** [comment]
une question pierre tu pense pas qu'il faudrait retravaille le module template de brython pour l'optimisé au niveau d'un vue.js ou encore angular.js? Moi je l'utilise mais il est parfois très lent j'aimerais le réécrire avec javascript pour l'optimisé
