### ISSUE TITLE
Incorrect behavior when using an asterisk as a variable name

### ISSUE THREAD

**Issue by schmave** [brython-dev/brython#1254]
This should raise a SyntaxError, but instead it calls the function `f` and prints "hi":

```python
def f():
    print('hi')
f(*)
```

This raises a JS exception instead of a SyntaxError:
```python
f(*, 1)
```

**Comment by PierreQuentel** [comment]
Thanks Evan !

The commit also fixes a similar issue with
```python
def f(x, *):
    print('hi')
f(7)

def f(x, **):
    print('hi')
f(7)
```
