### ISSUE TITLE
Regex named groups `(?P<name>...)` not supported

### ISSUE THREAD

**Issue by jghaines** [brython-dev/brython#1258]
**Brython version**: 3.8.0

As per title - Brython lacks  [named group](https://docs.python.org/3/library/re.html#index-17) support.

test code:
```
import _jsre as re

regex = re.compile('(?P<groupname>a|b)')
print(regex.match("a").group(0)) # Expected: "a" Actual: Exception: <Javascript SyntaxError>: Invalid regular expression: /^(?P<groupname>a|b)/: Invalid group
```

**Comment by jghaines** [comment]
This version works though. I'm not sure what the expected behaviour of `_jsre` is.
This issue can perhaps be closed

```
import re

regex = re.compile('(?P<groupname>a|b)')
print(regex.match("a").group(0)) # "a"
```

**Comment by PierreQuentel** [comment]
@jghaines Thanks for reporting this issue

The `_jsre` module is a wrapper around the Javascript regular expression engine. It supports Javascript's re syntax, which is not exactly the same as Python's ; one of the differences is the absence of named groups. They should be introduced in future versions of Javascript, but unfortunately not with the same syntax:

- Python : `(?P<groupname>...)`
- Javascript : `(?<groupname>...)`

Implementing named groups in the `_jsre` module would probably be difficult (it would also require to implement the back references to a named group), so I am closing this issue as "won't fix".

More generally, I introduced this module in the early days of Brython; I would not do the same now. The Javascript engine can be used as explained in the [demo page](https://brython.info/demo.html) ; the pure-Python implementation is also provided, so it's more confusing than useful IMO to have a module "in between" that uses the Javascript engine with a syntax close to that of the Python module.
