### ISSUE TITLE
json data loading is very slow on larger objects

### ISSUE THREAD

**Issue by ondrejj** [brython-dev/brython#1259]
Using json.loads() on larger objects (not very large, it's enough to be aprox. 1 kB) is very slow.
Looks like json module is using re, which causes this problem.

Trying to switch json to use _jsre, but this implementation is not working. json library is using match().end(), which returns different results for re and _jsre. Example:

```
>>> import re
>>> re.compile(" *").match("   test").end()
3
>>> import _jsre
>>> _jsre.compile(" *").match("   test").end()
1
```

Is it possible to fix this? Is _jsre still supported?
Or is it possible to use process json differently? Also have no luck to use window.JSON.parse(), whcih returns hard to use JS objects.

**Comment by PierreQuentel** [comment]
@ondrejj 
Could you give an example of objects that take a long time to process ? I know that the pure-Python json module is not fast, but it shouldn't be blocked with just 1kB of data.

Using `window.JSON` should be much faster, but there again I would like to know with an example what you mean with "hard to use JS objects".

**Comment by ondrejj** [comment]
OK, sorry, it's a bit larger tha 1 kB, exactly 38 kB. But still just a few kB. Can't send them now, possibly contains sensitive data, but I can prepare something if you need them. Real python can process them in a second. Brython raises slowness warning in Firefox, processes in aprox. minute.
Sometimes I need to process much larger objects. Brython docs says, that it's speed is comparable with a real python. I agree, but re/json processing is multiple times slower. :-(
I removed "re" usage from my apps, so they are running well now, except for large json objects.

And window.JSON example:
```
>>> window.JSON.parse('{"data": [{"grp": 2}]}').to_dict()
Traceback (most recent call last):
AttributeError: object has no attribute __repr__
```

Not sure, how to convert this window.JSON reply to an python object.

**Comment by PierreQuentel** [comment]
Javascripts objects such as JSON are intended to be used through the `javascript` module, which adds a layer to make them usable with Brython :

```python
from javascript import JSON

t = JSON.parse('{"data": [{"grp": 2}]}')
print(t) # prints "{'data': [{'grp': 2}]}"
```

They are also available as attributes of `window` (because the `window` object in Javascript mixes everything from the Web API to language-specific names), but I will add a deprecation message suggesting to use the `javascript` module instead.

**Comment by ondrejj** [comment]
Thanks, javascript.JSON.parse() works perfectly. Fast as python version.
Is there any chance to replace python's json.loads with javascript.JSON.parse() to make this behaviour available for libraries using json.loads()? I don't use them, but may be others do it.

**Comment by PierreQuentel** [comment]
There was a discussion on this topic for issue #1199 : if someone can implement a Javascript version that behaves exactly like the CPython module it's perfect, but having a module that misses some of the features will raise issues complaining that it's not compliant with CPython.

**Comment by ondrejj** [comment]
May be an switch will be useful. Something like from __future__ import ..., just different names. Something what switches json.parse and other function to not fully compatible, but very fast mode.
from __brython__ import browser_json  ?
