### ISSUE TITLE
__getattr__ does not work from metaclasses

### ISSUE THREAD

**Issue by ShaneFarrell** [brython-dev/brython#126]
Ok. This time I'm pretty sure this should work:

    class MyType(type):
    	def __getattr__(cls, attr):
    		return 5
    
    class MyParent(metaclass=MyType):
        pass
    
    class MyClass(MyParent):
        pass
    
    print(MyClass.spam)

This should be printing 5 (and it does in cPython 3) but instead it just raises an attribute error.

**Comment by PierreQuentel** [comment]
Shane,

Kiko Correoso reported that the bug was not fixed. The commit referenced above should make your code work now
