### ISSUE TITLE
Brython build error

### ISSUE THREAD

**Issue by bobkars** [brython-dev/brython#1260]
I had created a dockerfile for testing brython.  Several months ago the same dockerfile worked fine but now it fails.  Ideas?

Note I recently added steps 5 & 6 based on input from others with similar issues but to no avail. 

PS C:\brython> docker build -t test .
Sending build context to Docker daemon  66.05kB
Step 1/11 : FROM node:alpine
 ---> d4edda39fb81
Step 2/11 : RUN apk add python3
 ---> Using cache
 ---> 110ab918f98b
Step 3/11 : WORKDIR /usr/src/app
 ---> Using cache
 ---> 8e94dc052a36
Step 4/11 : RUN npm install express
 ---> Using cache
 ---> 84f7e5b62428
Step 5/11 : RUN pip3 install --upgrade pip
 ---> Using cache
 ---> d42a56b262aa
Step 6/11 : RUN pip3 install --upgrade setuptools
 ---> Using cache
 ---> dd985443845e
Step 7/11 : RUN pip3 install brython
 ---> Running in b3b23891a3d4
Collecting brython
  Downloading https://files.pythonhosted.org/packages/ae/d5/2573a2b19b14394997cfecd0ea92c937d205bbdcb096fb3ddbf0750e89cb/brython-3.8.1.tar.gz (1.1MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-l9nu83hs/brython/setup.py'"'"'; __file__='"'"'/tmp/pip-install-l9nu83hs/brython/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-l9nu83hs/brython/pip-egg-info
         cwd: /tmp/pip-install-l9nu83hs/brython/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-l9nu83hs/brython/setup.py", line 12, in <module>
        with open(os.path.join(release_dir, 'README.rst'), encoding='utf-8') as fobj:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-l9nu83hs/releases/README.rst'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
The command '/bin/sh -c pip3 install brython' returned a non-zero code: 1

**Comment by PierreQuentel** [comment]
@bobkars 
Thanks for reporting this, `pip install brython` was broken... I have released a new version, hopefully fixing the issue.
