### ISSUE TITLE
Incompatibilities with python 3.7 and earlier

### ISSUE THREAD

**Issue by aure-olli** [brython-dev/brython#1262]
I cannot use `brython --modules` with python 3.6 or 3.7 for 2 reason:
- the usage of the `"extend"` action of argparse: https://github.com/brython-dev/brython/blob/master/setup/brython/__main__.py#L28
- the usage of the new `/` argument in many places in `brython_stdlib.js`
Those 2 features were introduced by python 3.8, which is not the default python3 on most distributions.

Currently I have to do this to use it
```bash
venv/bin/pip install brython
sed -i 's|,/\([,)]\)|\1|g' venv/lib/*/site-packages/brython/data/brython_stdlib.js
sed -i 's|"extend"|"append"|g' venv/lib/*/site-packages/brython/__main__.py
rm -rf venv/lib/*/site-packages/brython/__pycache__
```

**Comment by PierreQuentel** [comment]
Good point. I have modified the part of the script that parses Python source code. Hopefully you should be able to run it with CPython versions below 3.8 (probably all 3.x versions, I only tested with 3.7). Can you try ? 

You have to uninstall brython (`pip uninstall brython`), then run the usual `python setup.py sdist / python setup.py install` with your CPython version to update the CPython brython package, finally try again `brython --modules`.

If it's ok I will release a new version soon.

**Comment by aure-olli** [comment]
Thanks, that works fine to me :)
