### ISSUE TITLE
import browser in electron

### ISSUE THREAD

**Issue by arthuro555** [brython-dev/brython#1263]
Hello! I noticed that loading python code containing an import of `browser.document` or `browser.window` makes an unknown exception while loading the code through` new Function(__BRYTHON__.python_to_js(src,"__main__"))()` on electron. I cannot use the brython() method and only need to eval some python code (no worries bout security), that is why I use that. Is that the cause of the problem or is it electron? importing browser alone works just fine (crash when accessing it's properties tho)

Complete error: https://pastebin.com/fc2T1A68

**Comment by PierreQuentel** [comment]
I don't know electron, but I ran the example (electron-quick-start) and tried to add brython.js to the index.html page, I got this message in the console:
```
Uncaught EvalError: Refused to evaluate a string as JavaScript 
because 'unsafe-eval' is not an allowed source of script in the 
following Content Security Policy directive: "script-src 'self'".

    at brython.js:6063
    at brython.js:6311
```

So I'm afraid there is not a big chance that you can use Brython in electron...
