### ISSUE TITLE
__set_name__ does not get called

### ISSUE THREAD

**Issue by Docopoper** [brython-dev/brython#1264]
Having this method would be handy for a project I'm working on.

**Comment by PierreQuentel** [comment]
@Docopoper 
Are you using the latest Brython version (3.8.6) ? It fixes a bug related to `__set_name__`.

If you use it, can you give a short example where it is not called as expected ?

**Comment by Docopoper** [comment]
Python 3.7.3 IDLE
```
>>> class TestDescriptor:
	def __set_name__(self, owner, name):
		print(owner, name)

		
>>> class TestObject:
	my_descriptor = TestDescriptor()

	
<class '__main__.TestObject'> my_descriptor
```

Brython      3.8.4
```
<!doctype html>
<html>

    <head>
        <meta charset="utf-8">
        <script type="text/javascript" src="brython.js"></script>
        <script type="text/javascript" src="brython_stdlib.js"></script>
    </head>

    <body onload="brython(1)">
        <script type="text/python">
            class TestDescriptor:
                def __set_name__(self, owner, name):
                    print(owner, name)

            class TestObject:
                my_descriptor = TestDescriptor()

        </script>
    </body>

</html>
```
Nothing is printed to the console when run in Brython.

**Comment by Docopoper** [comment]
Oh, right, wow. Yeah, I guess I'm a very small amount behind haha. I'll update and see if the problem persists.

**Comment by Docopoper** [comment]
Ok, I tested it on 3.8.6 and get the same issue.

After it failed to work I updated the code to include a print("test") statement to show that printing is working at the time of the __set_name__ call. The code below prints test to the console but does not print the text being printed in __set_name__.
```
<!doctype html>
<html>

    <head>
        <meta charset="utf-8">
        <script type="text/javascript" src="brython.js"></script>
        <script type="text/javascript" src="brython_stdlib.js"></script>
    </head>

    <body onload="brython(1)">
        <script type="text/python">
            class TestDescriptor:
                def __set_name__(self, owner, name):
                    print(owner, name)

            class TestObject:
                my_descriptor = TestDescriptor()
                print("test")

        </script>
    </body>

</html>
```

**Comment by Docopoper** [comment]
I ran that code directly from a python -m brython --install in an empty folder by the way and just modified index.html.

**Comment by PierreQuentel** [comment]
Thanks, I didn't quite get PEP 487. When it says that "_upon class creation, a `__set_name__` hook is called on all the attribute (descriptors) defined in the class_", I thought, only the attributes that have a `__get__` attribute...

**Comment by Docopoper** [comment]
After adding __get__ it does indeed work, however I have noticed another bug:
the owner argument should be the class the attribute was defined in, not the class of the descriptor itself. In the example above owner should be TestObject, not TestDescriptor.
