### ISSUE TITLE
Allow loading without timestamps

### ISSUE THREAD

**Issue by ondrejj** [brython-dev/brython#1266]
Currently every <script src...> or import ... is loaded with an timestamp. I am trying to write an offline application, which should run in mobile, but this "feature" block to load my app from cache. Is it possible to disable adding timestamp for loaded .py files?
Loaded file urls:
```
https://hostname/main.py?1576766629012
https://hostname/module.py?v=1576766629155
```
It it possible to disable this behaviour or do we need another option for brython() function?

**Comment by PierreQuentel** [comment]
@ondrejj 
If you run the application locally on a mobile, you will not be able to load scripts or files with Ajax calls, with or without a timestamp.

**Comment by ondrejj** [comment]
@PierreQuentel, thanks, but it's not very nice. I use mobile web app. This way app can have it's own icon and it's easy to start. Everything works well, if I embed my code into HTML page. Just this timestamping block to distribute my app as is.

**Comment by PierreQuentel** [comment]
What do you mean with a "mobile web app", is it an Android application made as explained [in the wiki](https://github.com/brython-dev/brython/wiki/Writing-an-Android-application) ?

**Comment by ondrejj** [comment]
Mobile web app is described here:
  https://developers.google.com/web/fundamentals/web-app-manifest
It's an universal web application, which can run offline, if it's pinned to desktop. Easy to develop, build, install. No need to have android account to publish.

**Comment by PierreQuentel** [comment]
In the commit referenced above I have added an option "cache" to the `brython()` function, eg :

```xml
<body onload="brython({debug: 1, cache: true})`
```
 This removes the query string in the Ajax calls that load external scripts (`<script type="text/python" src="script.py">`) and those that import modules.

Does it solve the issue ?

**Comment by ondrejj** [comment]
Yes, looks good. But why "cache: true" disabled caching? Why not false?

Btw, I found, that it's possible to avoid caching by using "python -m brython --modules", which compiles all my scripts to javascript. But then it's not possible to change my code.
Is it possible to define, which files should be searched and compiled?

**Comment by PierreQuentel** [comment]
With "cache: true", no query string is attached, so the url stays the same for each request, which allows caching.

**Comment by PierreQuentel** [comment]
`python -m brython --modules` does _not_ precompile Python to Javascript, it just bundles all the Python scripts (their source code) used by the application in a single Javascript program. The only precompilation feature in Brython is the indexedDB cache.

**Comment by ondrejj** [comment]
May be an option nocache: true with default to nocache: false will be better. But you current solution is good too.

Agree with precompile. It's in javascript but caching is enabled after bundling. Still missing --exclude/--include for --modules parameter.

**Comment by PierreQuentel** [comment]
What would be the use of these options for `--modules` ? 

The program scans all the Python scripts in a Brython repository (inside HTML pages or standalone) and bundles all the standalone scripts + the modules in the standard library used by these embedded and standalone scripts, and puts everything in __`brython_modules.js`__. 

I don't see the need to exclude some of these scripts (imports would fail) or to include other ones (they would never be used).

**Comment by ondrejj** [comment]
In my directory there are examples, which are scanned long time.
Also brython.timer is not a part of brython base, so I need to add it to brython_modules.js.
When I run --modules script, then all my sources are converted to brython_modules.js and I am unable to develop my application. Changed in future reloads will be ignored and loaded from brython_modules.js.
My idea is to only add one module or some modules, which I really want to add. For example only browser.timer.
Currently all modules (including my own ones and main program from index.html) are added to brython_modules.js.

**Comment by PierreQuentel** [comment]
Sorry, I don't understand everything you wrote : what does "which are scanned long time" mean ? and what do you mean by "browser.timer is not a part of brython base" ? (it is in brython_stdlib.js, the Brython version of Python standard library, and --modules will indude it in __`brython_modules`__ if it is used in the application).

It's true that using __`brython_modules`__ is not as flexible as loading the scripts with Ajax calls (at least with the cache disabled...), but another advantage is that it can use the indexedDB cache, making the application loading time faster.

**Comment by ondrejj** [comment]
brython --modules runs on my source directory 20-30 seconds due to files, which are not needed in my game, but present in this directory. Currently I need these files here, but don't want to be scanned using brython --modules.

I need to run brython --modules to create brython_modules.js only with browser.timer, nothing else. For this currently I have this content in my "js" directory:
`from browser import timer`
Runnning brython --modules in this directory creates brython_modules.js as I need them.
