### ISSUE TITLE
Getting ModuleNotFoundError for any pip import

### ISSUE THREAD

**Issue by kalmengr** [brython-dev/brython#1271]
So I'm not sure I got right but I've tried installing several pip packages, a few of which i know don't use any external libraries. 

I've also ran `python -m brython --add_pacckage name` and it was added to my Lib folder in my project root under site-packages folder. i also put the package folder in my project root

expected behavior: the modules load in and I'm able to use them

what actually happens: I'm getting the following in the console
`Traceback (most recent call last):
ModuleNotFoundError: trashguy
brython.js:5255 Uncaught trashguy
    at Object._b_.ModuleNotFoundError.$factory (eval at $make_exc (file:///C:/Users/kal/tguy/brython.js:7655:5), <anonymous>:1:211)
    at Object.import_hooks (file:///C:/Users/kal/tguy/brython.js:13526:33)
    at $B.$__import__ (file:///C:/Users/kal/tguy/brython.js:9146:60)
    at Object.$B.$import (file:///C:/Users/kal/tguy/brython.js:9187:43)
    at eval (eval at $B.loop (file:///C:/Users/kal/tguy/brython.js:5236:1), <anonymous>:17:21)
    at $B.loop (file:///C:/Users/kal/tguy/brython.js:5236:45)
    at idb_load (file:///C:/Users/kal/tguy/brython.js:5168:1)
    at IDBRequest.req.onsuccess (file:///C:/Users/kal/tguy/brython.js:5179:29)
_b_.ModuleNotFoundError.$factory @ VM857:1
import_hooks @ brython.js:13526
$B.$__import__ @ brython.js:9146
$B.$import @ brython.js:9187
eval @ VM917:17
$B.loop @ brython.js:5236
idb_load @ brython.js:5168
req.onsuccess @ brython.js:5179
IndexedDB (async)
idb_get @ brython.js:5178
$B.loop @ brython.js:5244
idb_load @ brython.js:5168
req.onsuccess @ brython.js:5179
IndexedDB (async)
idb_get @ brython.js:5178
$B.loop @ brython.js:5244
$B.inImported @ brython.js:5226
$B.loop @ brython.js:5244
$B.inImported @ brython.js:5226
$B.loop @ brython.js:5244
store.openCursor.onsuccess @ brython.js:5205
IndexedDB (async)
store.openCursor.onsuccess @ brython.js:5204
IndexedDB (async)
idb_cx.onsuccess @ brython.js:5197
IndexedDB (async)
$B.idb_open @ brython.js:5183
$B.loop @ brython.js:5244
$B.parser._run_scripts @ brython.js:5119
$B.parser.brython @ brython.js:5045
onload @ app.html:6`

and I'm getting pretty much the same behavior with the emoji module (pip install emoji) 

os: win10 x64
python version: 3.7.4

**Comment by kalmengr** [comment]
I forgot to mention, Yes I did include brython_stdlib.js in my html head

**Comment by kalmengr** [comment]
Another thing worth mentioning is that `python -m brython --modules` does list these packages in the modules {}

**Comment by PierreQuentel** [comment]
@kalmengr 
Thanks for the report, and sorry for the late answer. I could not reproduce the bug, unfortunately.

I tried to install the emoji package. Here are the steps I followed:

```
C:\Users\PC>pip install emoji
Collecting emoji
  Downloading https://files.pythonhosted.org/packages/40/8d/521be7f0091fe0f2ae690cc044faf43e3445e0ff33c574eae752dd7e39fa/emoji-0.5.4.tar.gz (43kB)
     |████████████████████████████████| 51kB 469kB/s
Installing collected packages: emoji
  Running setup.py install for emoji ... done
Successfully installed emoji-0.5.4
WARNING: You are using pip version 19.2.3, however version 20.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

C:\Users\PC>e:

E:\>cd temp/brython

E:\temp\brython>mkdir 20200121

E:\temp\brython>cd 20200121

E:\temp\brython\20200121>python -m brython --install
None
Installing Brython 3.8.6 in an empty directory

E:\temp\brython\20200121>python -m brython --add_package emoji
None
add package emoji...
copy folder E:\Python38\lib\site-packages\emoji

E:\temp\brython\20200121>python -m http.server 8001
```

I edited the __`index.html`__ page:

```xml
<!doctype html>
<html>

<head>
<meta charset="utf-8">
<script type="text/javascript" src="brython.js"></script>
<script type="text/javascript" src="brython_stdlib.js"></script>
</head>

<body onload="brython(1)">
<script type="text/python">
import emoji
print(emoji)
</script>
</body>

</html>
```

Here is what I see in the browser console when loading the page:
```
XHR GET http://localhost:8001/emoji.py?v=1579639212646
[HTTP/1.0 404 File not found 0ms]

Error 404 means that Python module emoji was not found at url http://localhost:8001/emoji.py brython.js:8884:9
XHR GET http://localhost:8001/emoji/__init__.py?v=1579639212654
[HTTP/1.0 404 File not found 0ms]

Error 404 means that Python module emoji was not found at url http://localhost:8001/emoji/__init__.py brython.js:8884:9
XHR GET http://localhost:8001/Lib/site-packages/emoji.py?v=1579639212661
[HTTP/1.0 404 File not found 0ms]

Error 404 means that Python module emoji was not found at url http://localhost:8001/Lib/site-packages/emoji.py brython.js:8884:9
XHR GET http://localhost:8001/Lib/site-packages/emoji/__init__.py?v=1579639212668
[HTTP/1.0 200 OK 0ms]

XHR GET http://localhost:8001/Lib/site-packages/emoji/core.py?v=1579639212689
[HTTP/1.0 200 OK 0ms]

XHR GET http://localhost:8001/Lib/site-packages/emoji/unicode_codes.py?v=1579639217306
[HTTP/1.0 200 OK 16ms]

<module emoji>
```
So it seems that the package was correctly loaded and the expected message, `<module emoji>`, was printed in the browser console.

The directory structure is:
```
brython.js
brython_stdlib.js
demo.html
index.html
README.txt
unicode.txt
Lib
|--- site-packages
     |--- emoji
          |--- __init__.py
               emoji.py
               unicode_codes.py
```

I also tried the `python -m brython --modules` feature ; I first removed __`demo.html`__ to avoid putting in __`brython_modules.js`__ files that are not used by the script in __`index.html`__

```
E:\temp\brython\20200121>del demo.html

E:\temp\brython\20200121>python -m brython --modules
None
Create brython_modules.js with all the modules used by the application
searching brython_stdlib.js...
search in site-packages...
skip non-Python module core.cpython-38.pyc
skip non-Python module unicode_codes.cpython-38.pyc
skip non-Python module __init__.cpython-38.pyc
finding packages...
script in html index.html
python core.py
python unicode_codes.py
python __init__.py
modules {'abc', 'email.encoders', '_dummy_thread', 'importlib._bootstrap', 'inspect', 'token', 'importlib', 'importlib.machinery', 'fnmatch', 'copyreg', 'unittest.signals', 'urllib', 'os', 'linecache', 'email.generator', 'unittest.result', '_operator', 'quopri', 'struct', '_codecs', '_base64', 'urllib.parse', 'email', '_zlib_utils', 'base64', 'email.message', 'shlex', '_threading_local', 'tokenize', 'pydoc_data.topics', 'math', 'warnings', 'unittest.runner', 'email._encoded_words', 'emoji.unicode_codes', '_socket', 'unittest.main', 'copy', 'logging', 'emoji.core', 'zipfile', 'dis', 'code', '_posixsubprocess', 'email.policy', 'posixpath', '_imp', 'time', 'email.parser', 'optparse', 'unittest.loader', 'marshal', 'importlib.util', '_binascii', 'py_compile', 'traceback', 'browser.aio', 'pydoc_data', '_thread', 'emoji', 'unittest.suite', 'select', 'argparse', 'locale', 'datetime', 'encodings.utf_8', 'operator', 'itertools', '_string', 'random', '_warnings', 'browser', 'keyword', 'selectors', 'functools', 'builtins', 'textwrap', 'email.feedparser', 'bdb', 'signal', 'reprlib', 'stat', 'webbrowser', 'heapq', 'typing', 'getopt', 'collections', '_struct', 'unittest.util', '_sre_utils', 'binascii', 'platform', '_strptime', 'pprint', 'email.base64mime', 'unittest.case', 'sre_constants', 'unittest.async_case', 'codeop', 'doctest', 'gettext', 'pkgutil', 'errno', 'email._parseaddr', 'weakref', 'sys', '_functools', 'contextlib', 'difflib', 'uu', 'enum', 'string', '_collections_abc', 'email.header', 'http', 'cmd', 'shutil', 'encodings', 'calendar', 'email.utils', '__future__', 'gc', 'email.errors', '_io', '_locale', 'unittest', 'threading', 'tarfile', '_weakref', 'array', 'email.iterators', 'subprocess', 'pydoc', '_collections', 'codecs', 'pdb', 'zlib', 'pwd', 'glob', 'email._policybase', 'email.quoprimime', 'types', 'posix', '_weakrefset', 'atexit', 'importlib.abc', 'sre_compile', 'email.contentmanager', 'genericpath', 'sre_parse', 'email.headerregistry', '_py_abc', 're', 'email._header_value_parser', 'importlib._bootstrap_external', 'collections.abc', 'socket', '_sre', 'io', 'email.charset', 'unicodedata', 'encodings.aliases', 'tempfile', '_aio'} True
```

After replacing __`brython_stdlib.js`__ by __`brython_modules.js`__ in __`index.html`__, the script also ran as expected.

**Comment by kalmengr** [comment]
Thanks for your response. I've tried following your exact procces. I've tried with `emoji` as well as some random packages including `twilio`. They're all giving me the same error. I'm not running in any environments and I use the standard python installation so I can't see why this happens. Thanks for your work and I really hope we can figure it out

**Comment by PierreQuentel** [comment]
Can you post the complete log that you see in the browser console (before the error message) when you only use __`brython_stdlib.js`__ ? It should show a few XHR calls.

**Comment by kalmengr** [comment]
Interestingly enough there are no XHR calls. or at least the console doesn't say so. 

```Traceback (most recent call last):
  module main line 2
    import twilio
ModuleNotFoundError: twilio
brython.js:5255 Uncaught twilio
    at Object._b_.ModuleNotFoundError.$factory (eval at $make_exc (file:///C:/Users/three/OneDrive/Pictures/Kalmen/trashguyani/brython.js:7655:5), <anonymous>:1:211) 
    at Object.import_hooks (file:///C:/Users/three/OneDrive/Pictures/Kalmen/trashguyani/brython.js:13526:33)
    at $B.$__import__ (file:///C:/Users/three/OneDrive/Pictures/Kalmen/trashguyani/brython.js:9146:60)
    at Object.$B.$import (file:///C:/Users/three/OneDrive/Pictures/Kalmen/trashguyani/brython.js:9187:43)
    at eval (eval at $B.loop (file:///C:/Users/three/OneDrive/Pictures/Kalmen/trashguyani/brython.js:5236:1), <anonymous>:18:8)
    at $B.loop (file:///C:/Users/three/OneDrive/Pictures/Kalmen/trashguyani/brython.js:5236:45)
    at $B.inImported (file:///C:/Users/three/OneDrive/Pictures/Kalmen/trashguyani/brython.js:5226:1)
    at $B.loop (file:///C:/Users/three/OneDrive/Pictures/Kalmen/trashguyani/brython.js:5244:6)
    at IDBRequest.store.openCursor.onsuccess (file:///C:/Users/three/OneDrive/Pictures/Kalmen/trashguyani/brython.js:5205:1)```

**Comment by kalmengr** [comment]
I also see no network calls for the module in the network tab.

**Comment by PierreQuentel** [comment]
I think I know what is wrong : you are loading the file with the browser File/Open menu (or by double-click in the file explorer). In this case, the protocol is `file`, not `http`, and the Ajax calls that load the modules in __`site-packages`__ are not supported.

If you start a web browser by running this command in the application directory
```
python -m http.server 8001
```
then enter _localhost:8001/index.html_ in the browser address bar, it might work better.

**Comment by PierreQuentel** [comment]
I think I know what is wrong : you are loading the file with the browser File/Open menu (or by double-click in the file explorer). In this case, the protocol is `file`, not `http`, and the Ajax calls that load the modules in __`site-packages`__ are not supported.

If you start a web browser by running this command in the application directory
```
python -m http.server 8001
```
then enter _localhost:8001/index.html_ in the browser address bar, it might work better.

**Comment by kalmengr** [comment]
Thank you! That did it!

**Comment by PierreQuentel** [comment]
Good news ! 
I should document this more explicitely
