### ISSUE TITLE
lambda statement without arguments causes wrong error

### ISSUE THREAD

**Issue by niansa** [brython-dev/brython#1281]
Hi

I just found out that a line just containing the word "lambda" would cause a recursion error. ;-)

**Comment by PierreQuentel** [comment]
Hi @niansa 

Thanks for reporting this. It is the case in version 3.8.6, but not in the current development version, where it raises the expected `SyntaxError`. Can you try ?

**Comment by PierreQuentel** [comment]
I am closing this issue, with the latest version (3.8.7) I think that the issue is solved. If not, don't hesitate to reopen it.

**Comment by niansa** [comment]
Yep, that fixed it
