### ISSUE TITLE
Run Python script from a string

### ISSUE THREAD

**Issue by martinRenou** [brython-dev/brython#1283]
Let me first say that this package looks amazing! 

I would like to run a small snippet of Python code (provided by my users) without the need of creating a new `<script>` tag in the page for each snippet of code I receive. Is it currently possible to use the `Brython` main function on a string of Python code?

**Comment by niansa** [comment]
The trick is https://docs.python.org/3/library/functions.html#exec ;-)

**Comment by martinRenou** [comment]
Mmmmh I am a bit confused here.

I want to be able to do this in JavaScript, not Python. Something like:

```javascript
var brython = require('brython');

var code = `
  import sys

  print(sys.version)
`;

brython(code);
```

**Comment by martinRenou** [comment]
Note that the `require` does not even work, see #1284

**Comment by PierreQuentel** [comment]
I'm afraid you are confusing Javascript and Node.js. `require` doesn't work in Javascript, it throws this exception:
```
ReferenceError: require is not defined
```
I don't know anything about Node.js, and I confess I don't even know why I publish releases on npm (the developer who first published a version must have left the project long ago). If you can help fixing it, you are welcome !

**Comment by martinRenou** [comment]
> require doesn't work in Javascript

It does if you use Webpack or https://requirejs.org, I would say using Webpack is a good practice for JavaScript packages like this one.

If you start using Webpack, you will be able to get rid of your custom `javascript_minifier.py` processor and maybe other scripts. You are kind-of reinventing the wheel because Webpack does all this kind of thing already and is widely used.

I am not sure I understand the structure of the project, so I don't really know if it's easy to port it to using Webpack.

Anyway, fixing the other issue might not be too difficult for now, should I change this file: https://github.com/brython-dev/brython/blob/master/www/src/brython.js#L11 ? I feel like it is somewhat generated (from Python?).

Just to give some more context, I would be very interested in using something like brython in order to implement fast animations (written in Python and executed on the web-page in JavaScript) in my ipycanvas package: https://github.com/martinRenou/ipycanvas.

**Comment by martinRenou** [comment]
I forgot to mention, I am really not using Node.js, I am trying to use brython in a web-page.

**Comment by schmave** [comment]
If you want to run Python code without making an script tag for each bit of Python, you can use Brython's python_to_js function like this:

```
<script type="text/javascript" src="path/to/brython.js"></script>
<script type="text/javascript">
window.eval(__BRYTHON__.python_to_js('x = 5; print(x);'));
</script>
```

**Comment by martinRenou** [comment]
Thanks a lot. That is exactly what I am looking for.

**Comment by martinRenou** [comment]
I guess we can close this issue then, and continue this webpack discussion in the relevant issue. Thanks again

**Comment by radiantone** [comment]
Hi. If I give the string "5 * 3" to the above window.eval I need to get back the result of the expression, but currently it does not.

**Comment by radiantone** [comment]
All you need to do is add this
```
try{
    ;$locals.$line_info = "1,__main__";if($locals.$f_trace !== _b_.None){$B.trace_line()};_b_.None;
    **var result =** $B.mul(5,3);
    $B.leave_frame({$locals, value: _b_.None})
    **return result;**
}
```
