### ISSUE TITLE
Brython does not play well with Webpack

### ISSUE THREAD

**Issue by martinRenou** [brython-dev/brython#1284]
Once installed with `npm`, doing:
```javascript
require('brython');
```

in a JavaScript project fails with `TypeError: Cannot read property 'name' of undefined`. The line of code responsible for this error is:
```javascript
$B.isNode=(typeof process !=='undefined')&&(process.release.name==='node')
```

A (outrageously ugly) workaround for that is to do the following before requiring brython:
```javascript
process.release = { name: 'This is not Node' };
```

I feel like this project would benefit from working with Webpack, in order to be included in bigger projects.

Also, I understand `brython` sets a global variable instead of exporting the main function from the JS package.

**Comment by PierreQuentel** [comment]
Salut Martin ;-)
Same answer as for issue #1283. Help on fixing Node.js issues would be very much appreciated !

**Comment by martinRenou** [comment]
> require doesn't work in Javascript

It does if you use Webpack or https://requirejs.org, I would say using Webpack is a good practice for JavaScript packages like this one.

If you start using Webpack, you will be able to get rid of your custom javascript_minifier.py processor and maybe other scripts. You are kind-of reinventing the wheel because Webpack does all this kind of thing already and is widely used.

I am not sure I understand the structure of the project, so I don't really know if it's easy to port it to using Webpack.

Anyway, fixing this issue might not be too difficult for now without going through this Webpack refactor, should I change this file: https://github.com/brython-dev/brython/blob/master/www/src/brython.js#L11 ? I feel like it is somewhat generated (from Python?).

Just to give some more context, I would be very interested in using something like brython in order to implement fast animations (written in Python and executed on the web-page in JavaScript) in my ipycanvas package: https://github.com/martinRenou/ipycanvas.

**Comment by PierreQuentel** [comment]
> Anyway, fixing this issue might not be too difficult for now without going through this Webpack refactor, should I change this file: https://github.com/brython-dev/brython/blob/master/www/src/brython.js#L11 ? I feel like it is somewhat generated (from Python?).

If you haven't yet, you can take a look at the page about [how Brython works](https://github.com/brython-dev/brython/wiki/How-Brython-works); it gives an idea of the project structure. Development is made on "individual" scripts in directory __`www/src`__; __`brython.js`__ is generated from these scripts by the Python program __`scripts/make_dist.py`__.

For testing, I usually replace __`brython.js`__ in the test page by all the individual scripts; you can copy and paste the list from a page such as [sort_table.html](https://github.com/brython-dev/brython/blob/master/www/gallery/sort_table.html).

Tell me if I can help in any way, but to be honest I don't want to learn yet another tool in the Javascript ecosystem. It's already a lot of work to maintain Brython...

**Comment by redradist** [comment]
I agree ...

It would be nice to use and split py2js in few file to be able to read it ...

During working on issue https://github.com/brython-dev/brython/issues/1419 for me was hard to read *.js files that has 6000 lines !!

Using `webpack` is pretty easy ;)

Here answer that shows how to work with `webpack`:
https://stackoverflow.com/questions/45097737/webpack-how-do-i-bundle-multiple-javascript-files-into-a-single-output-file

**Comment by redradist** [comment]
> 
> 
> > Anyway, fixing this issue might not be too difficult for now without going through this Webpack refactor, should I change this file: https://github.com/brython-dev/brython/blob/master/www/src/brython.js#L11 ? I feel like it is somewhat generated (from Python?).
> 
> If you haven't yet, you can take a look at the page about [how Brython works](https://github.com/brython-dev/brython/wiki/How-Brython-works); it gives an idea of the project structure. Development is made on "individual" scripts in directory **`www/src`**; **`brython.js`** is generated from these scripts by the Python program **`scripts/make_dist.py`**.
> 
> For testing, I usually replace **`brython.js`** in the test page by all the individual scripts; you can copy and paste the list from a page such as [sort_table.html](https://github.com/brython-dev/brython/blob/master/www/gallery/sort_table.html).
> 
> Tell me if I can help in any way, but to be honest I don't want to learn yet another tool in the Javascript ecosystem. It's already a lot of work to maintain Brython...

@PierreQuentel It will allow not only debug, but also split nicely big *.js file into smaller one ... ;)

**Comment by vrescobar** [comment]
is there any progress in this front? nowadays it is necessary to actually be webpack compatible, it helps to split, pack, minimize and load on demand parts of the stdlib on demand and to play well with the rest of the JS ecosystem.

**Comment by schmave** [comment]
I'd be happy to review a PR if anyone wants to get started on this. I agree that it would be a nice improvement, though it would take some work.

**Comment by PierreQuentel** [comment]
I am closing this old issue. If someone is interested, please reopen it.
