### ISSUE TITLE
Exception in comprehension generators not always raised

### ISSUE THREAD

**Issue by casatir** [brython-dev/brython#1286]
Tested in iteractive mode only with console.html. If a division by zero is thrown inside a generator given by comprehension, like in `tuple(1 / 0 for n in range(10))`, then no error is raised and the console log contains :

> `no __str__ for TypeError: "_frame[4].$infos is undefined"`

This is the same with `sum(1 / 0 for n in range(10))` and `a = (1 / 0 for n in range(10)) ; a.next()`.

If the generator is defined as a function using the yield statement, like in `def generator(): yield 1 / 0 ; a = generator() ; a.next()` the error is raised. This is working for all exceptions that I have tested.

Please note that this append with other errors : `tuple(d['missing key'] for n in range(10))` does not raise `NameError: name 'd' is not defined` and if you define an empty dict d, a `KeyError`is not raised either.

**Comment by PierreQuentel** [comment]
Thanks for the very clear report. I also fixed similar bugs for list / dict / set comprehensions.
