### ISSUE TITLE
The problem of increased page display time.

### ISSUE THREAD

**Issue by freak-js** [brython-dev/brython#1291]
Hello!
I really like Brython, but I noticed that the pages on which "onload(brython)" load much longer.
Is there a method to eliminate this unpleasant feature?

On the production server:
    (vanilla js code) load: 200-220 ms
    (brython code)   load: 600-650 ms

Thank you in advance for your response!

**Comment by PierreQuentel** [comment]
здравствуй, и спасибо за вопрос !

The increased loading time cannot be totally eliminated : the browser has to load and parse the script __`brython.js`__, inspect the Python scripts in the page and translate them to Javascript. From the user point of view, I don't think that a difference of 0.4 s is such a big problem.

**Comment by freak-js** [comment]
Thank you for the answer and the work you have done!
