### ISSUE TITLE
Implement filesystem api seamlessly

### ISSUE THREAD

**Issue by niansa** [brython-dev/brython#1296]
An option to use the filesystem API (https://developer.mozilla.org/en-US/docs/Web/API/FileSystem) would be great!
It should work directly from the posix module.

**Comment by PierreQuentel** [comment]
The page your link points to explicitely states that this is an experimental technology, not supported by all browsers, so I don't think it's relevant to have a Brython-specific implementation.

That being said, you can probably use the API in browsers that support it. I tried with the few example I found, but bad luck, `requestFileSystem()` doesn't seem to be implemented in Chrome or Firefox.

**Comment by bit-garden** [comment]
Pierre is correct in this decision. Unofficial api shouldn't be used by third party libs like this. 

That being said, it is possible to implement this to a degree. I had trouble getting a folder list(due to js/brython interop issues) but basic open/create/write of single files is already possible. 

My implementation here might get you started if you want to handle this. 
```
class fopen():
  def __init__(self, new_file=False):
    if new_file:
      self.opts = {
        'type': 'saveFile',
        'accepts': [{
          'description': 'Text file',
          'extensions': ['txt'],
          'mimeTypes': ['text/plain'],
        }],
      }
    else:
      self.opts = {}

  async def __aenter__(self):
    if self.opts:
      self.fileHandle = await window.chooseFileSystemEntries(self.opts)
    else:
      self.fileHandle = await window.chooseFileSystemEntries()
    self.file = await self.fileHandle.getFile()
    self.text = await self.file.text()

    return self

  async def write(self, content):
    writer = await self.fileHandle.createWriter()
    await writer.truncate(0)
    await writer.write(0, content)

    await writer.close()

  async def __aexit__(self, *l):
    pass
```

Use like `open` but async
```
async with fopen() as f:  # browser ui prompts for file
  # do stuff
  f.write('file contents')
```

**Comment by niansa** [comment]
This is how I implemented it:
https://pythonlabs.ga/ide/virtualfs.py
