### ISSUE TITLE
FileNotFoundError with open()

### ISSUE THREAD

**Issue by redstoneleo** [brython-dev/brython#1301]
My brython code in `index.html` as the following :
```
from browser import document
document <= "Hello !"
import json,os
print(os.getcwd())
d = open("collins.json", encoding='utf-8')
print(d)

```
The `collins.json` is in the same directory as `index.html` , but I got
```
Traceback (most recent call last):
  module __main__ line 8
    d = open("collins.json", encoding='utf-8')
FileNotFoundError: collins.json
```
so what's wrong with my [testCode.zip](https://github.com/brython-dev/brython/files/4219333/testfile.zip) ?

**Comment by PierreQuentel** [comment]
There is nothing wrong with the code, but you are probably loading the HTML page with the File/Open... menu or with a double-click in the file explorer ; in this case the protocol is "file", not "http", and the function `open()` can't send an Ajax call to read a file in this protocol. You should start a web server in the page directory and load the page with its url in the address bar.

This is explained in a [new section](http://www.brython.info/static_doc/en/file_or_http.html) of the documentation. I have also added a warning in the commit referenced above.

Anyway, the file you are trying to open is very big, loading and processing it is going to take some time.
