### ISSUE TITLE
brython.info - could not open indexedDB database 

### ISSUE THREAD

**Issue by dubiouscript** [brython-dev/brython#1307]
browser : fox 61.0.1 (64-bit)

url : https://brython.info/

console : "could not open indexedDB database"

---

perhaps you could should include a link to github 
on your main page
because in my case nothing loads other than a logo 
=s

**Comment by PierreQuentel** [comment]
This is typically the kind of bug difficult to reproduce... I could not find much documentation on what can cause `indexedDB.open()` to throw an error.

I have modified the code executed in this case, to disable the use of indexedDB and proceed with script execution. Can you test the home page with this modification at [https://brython.info/index_issue_1307.html](https://brython.info/index_issue_1307.html) ?

**Comment by dubiouscript** [comment]
this test link works 

however i still see 'could not open indexedDB database'

**Comment by jmgurney** [comment]
Right now, brython.info is really slow for me.  Takes a really long time to establish a connection.

**Comment by PierreQuentel** [comment]
@jmgurney Is it the same issue (ie with the message "could not open indexedDB database") ?
