### ISSUE TITLE
time and datetime always return current time ?

### ISSUE THREAD

**Issue by samgratte** [brython-dev/brython#131]
Hello,

I tried to use the *time* and *datetime* modules but all the functions i tried, but *ctime*, behaved like the *time tuple* or *timestamp* I passed were the current time :

```Python
Brython 3.0.2 on Netscape 5.0 (X11)
>>> import time
>>> time.gmtime(0.0)
[2015, 2, 10, 11, 13, 23, 2, 0, 0]
>>> time.gmtime(0)
[2015, 2, 10, 11, 13, 31, 2, 0, 0]
>>> time.gmtime(1000000.0)
[2015, 2, 10, 11, 13, 38, 2, 0, 0]
>>> import datetime
>>> datetime.datetime.utcfromtimestamp(0.0)
datetime.datetime(2015, 2, 10, 11, 15, 51)
>>> time.ctime()
'Tue, 10 Feb 2015 12:21:42 GMT'
>>> time.ctime(0.0)
'Thu, 01 Jan 1970 00:00:00 GMT'
>>> time.asctime()
Traceback (most recent call last):
  module exec-132 line 1
    time.asctime()
AttributeError: 'module' object has no attribute 'asctime'
```
 Is there something special to do or are those modules not ready yet ?

the function 'asctime' lacks too ... (not very important)
thanks

**Comment by kikocorreoso** [comment]
@samgratte Please, have a look if the patch #135 solve your issues.

Though there are more issues related with `time.py` and `datetime.py`. I will work on them during the next days to try to fix most of them.

**Comment by kikocorreoso** [comment]
PR #143 fixes this issue.

**Comment by samgratte** [comment]
I'll look into it as soon as I can, thanks!
