### ISSUE TITLE
create TCP sockets

### ISSUE THREAD

**Issue by ch-yx** [brython-dev/brython#1310]
I want to create a TCP socket by brython.

import socket
socket.socket().connect

'socket' object has no attribute 'connect'

Is it impossible to do that in brython/browser?

**Comment by PierreQuentel** [comment]
@ch-yx 
No, it's not possible to create a socket in the browser. Take a look at this [stackoverflow question](https://stackoverflow.com/questions/12407778/connecting-to-tcp-socket-from-browser-using-javascript) for more information.

**Comment by ch-yx** [comment]
> 
> 
> @ch-yx
> No, it's not possible to create a socket in the browser. Take a look at this [stackoverflow question](https://stackoverflow.com/questions/12407778/connecting-to-tcp-socket-from-browser-using-javascript) for more information.

Thanks for your reply !    
But... May I know why you keep this module in brython?

**Comment by PierreQuentel** [comment]
Good question ! It is because some modules in the standard distribution - among them __`Lib/test/support/__init__.py`__, which is used in some internal Brython tests - require that this module can be imported, even though it is not actually used in these tests.

**Comment by ch-yx** [comment]
> Good question ! It is because some modules in the standard distribution - among them **`Lib/test/support/__init__.py`**, which is used in some internal Brython tests - require that this module can be imported, even though it is not actually used in these tests.

May I have another question?

In Javascript, there is no difference between "😀"  and  "\ud83d\ude00".
But in python, they are different. len("😀")==1  and  len("\ud83d\ude00")==2

how did you /will you solve this problem?

**Comment by ch-yx** [comment]
![image_53](https://user-images.githubusercontent.com/45825511/75448711-ae2f4c80-59a6-11ea-94d3-4539e9334c5d.png)
