### ISSUE TITLE
Regression: `while` inside `for` loop inside generator

### ISSUE THREAD

**Issue by mircea3** [brython-dev/brython#1317]
The following example stopped working on 2020-02-09 commit (c18522c63a33c580e7eec428f8eb2ad530c8a702):

```
def gg():
    for jj in range(2):
        ii = 0
        done = False
        while not done:
            ii += 1
            done = ii == 3
            yield ii
print(list(gg()))
```

Expected: `[1, 2, 3, 1, 2, 3]`
Currently: `[1, 1]`

**Comment by mircea3** [comment]
Just a quick clarification. I used the term 'regression' because this problem existed, then it was fixed (a long time ago), then it came back again. But if this functionality was neither specifically targeted nor tested and it was just a coincidence, it was probably the wrong term to use. In that case, my apologies for that.

**Comment by PierreQuentel** [comment]
@mircea3 
Once again many thanks for this bug report. It was helpful that you mentioned this commit because the bug was actually related to this feature.
