### ISSUE TITLE
Input function overwrite

### ISSUE THREAD

**Issue by jcubic** [brython-dev/brython#1318]
I want to change input function to be more like in terminal.

I have experience that in Python you can do lot of tricks to execute same code (there is one right way but lot of different ways as well). In my terminal library that use at https://trypython.jcubic.pl/ I have read function that ask for user input and return a promise is there a way to add some kind of hook that will replace prompt in whole Python? It will be different because it will not stop the evaluation but return a JS Promise.

**Comment by jcubic** [comment]
By looking at the code I've found that I can use corutines

```javascript
var read = (function($B) {
  function read(str) {
    function func() {
      return new Promise(function(resolve) {
        // read is same API as Promise but not same object
        $.terminal.active().read(str).then(resolve);
      });
    }
    func.$infos = {
        __name__: "read"
    };
    return {
        __class__: $B.coroutine,
        $args: [str],
        $func: func
    };
  }

  return read;
})(__BRYTHON__);
```

is it possible to hook this into `sys.stdin.read`? and make function async and return string? I have print() working with terminal but input is still using prompt.

I have something like this in my [LISP interpreter in JavaScript](https://jcubic.github.io/lips/), every promise is auto resolved while evaluating expressions:

```
(--> (fetch "http://example.com/file.txt") (text))
```
fetch is standard browser function not a wrapper.

**Comment by PierreQuentel** [comment]
@jcubic 
Not sure if this is exactly what you want, but the first example in the [documentation of the browser.aio module](http://www.brython.info/static_doc/en/aio.html) shows how to simulate (asynchronous) `input()`.

**Comment by jcubic** [comment]
I know that I can use:
```python
async def foo():
  print(await read("what? "))
aio.run(foo())
```

but is possible to hook into internals if Brython to have just `print(input())` without async stuff? Or just input need to be using prompt to pause the execution, I had same issue with EMscripten where async code was not possible out of the box, you need to use hacks in C.

**Comment by PierreQuentel** [comment]
Unfortunately, it's not possible because Javascript doesn't support blocking functions other than the built-in `alert(), confirm()` and `prompt()`. It's frustrating, it would be much nicer to be able to customize input dialogs...

**Comment by jcubic** [comment]
I understand that it's hard, but I don't understand why it's not possible. Brython is written in JavaScript but it control how it evaluate Python code. You're not forced to stop the evaluation of hosting langauge only evaluation of Python code. But I'm not familar with Brython code and how it's implemented. Adding auto resolving promises to my lisp was not that hard. The only side effect is that my exec function needed to always return a promise, so it's easier to use and you don't need to check if you have promise or not.

**Comment by jcubic** [comment]
I've just read in docs [How-Brython-works](https://github.com/brython-dev/brython/wiki/How-Brython-works) that brython is python to JavaScript compiler, now i understand that it may be imposible.

**Comment by PierreQuentel** [comment]
Yes, it's because Brython translates Python to Javascript that Python's `input()` cannot be implemented other than with JS `prompt()`.
