### ISSUE TITLE
websocket demo broken out of the box

### ISSUE THREAD

**Issue by glyph** [brython-dev/brython#132]
1. start server.py
2. click "websocket" in the docs
3. click "open connection" in the example

Expected: a websocket connection

Observed: no connection, console log messages:

```
[Log] undefined: undefined is not an object (evaluating 'self.func.bind') (brython.js, line 5186, x6)
undefined
```

**Comment by glyph** [comment]
This does seem to work on http://brython.info/, but I'm not sure if that's because it's a different version of the code, or because there's a back-end not packaged with server.py?

**Comment by PierreQuentel** [comment]
Glyph,

I can't reproduce the bug, the demo works for me with the local server. If you can embed the code in the documentation inside an HTML page and set debug mode to 1 or more, you might get more explicit error messages

**Comment by kikocorreoso** [comment]
It also works for me with the actual repo.

Maybe you have something cached?
