### ISSUE TITLE
 when importing    "/Lib" is  prefixed, but "$B.brython_path" has no effect !?

### ISSUE THREAD

**Issue by dubiouscript** [brython-dev/brython#1321]
i have a script to collect the console.html dependency's 

```
url_lst='

http://brython.info/console.html

http://brython.info/brython.css

http://brython.info/fonts/libra_bt.ttf
http://brython.info/fonts/Montserrat-Light.otf


http://brython.info/src/brython.js

http://brython.info/tests/console.py?1583263242950

http://brython.info/src/Lib/sys.py?v=1583263243699
http://brython.info/src/Lib/tb.py?v=1583263244006

';



for i in $url_lst  ; do  fname=$( basename "$i" ); [ -f "$i" ] ||  wget -nc  "$i" ; done

```

after copying ./console.html to index.html

and correcting the paths to scripts and fonts 

i have encountered this problem 

eg 
>import sys

try's to fetch the path 

> foobar.gitlab.oi/Lib/sys.py

i found `grep -en 'Lib' -r ./*` the section 

> ./brython.js:9131:var path=$B.brython_path+"Lib/"+modobj.__name__

which appears to be adding this prefix 
..however
in console 

>$B.brython_path

returns

> "foobar.gitlab.oi/brython-test/Lib/sys.py" 

so im not shore why this is appears to be having no effect 

as it appears to me that the result should be 

> "foobar.gitlab.oi/brython-test/" 

ideally for my case the path should be 

> "foobar.gitlab.oi/brython-test/sys.py

any simple way to achieve this?
am i missing something obvious??

i did look around abit https://github.com/brython-dev/brython/issues/491
but did not find anything that appeared relevant

**Comment by dubiouscript** [comment]
:grimacing: 
>https://brython.info/static_doc/en/options.html
> pythonpath : a list of paths where imported modules should be searched

**Comment by PierreQuentel** [comment]
_Il n'est pas de problème dont une absence de solution ne finisse par venir à bout._
