### ISSUE TITLE
Problem with window.js_obj

### ISSUE THREAD

**Issue by Animenosekai** [brython-dev/brython#1322]
I'm currently facing a problem with **window.js_obj**
I have a JSObject obtain through an API and jQuery but when I try to convert the gotten JSObject into a proper Python Dict, it seems like there is no module called js_obj into window.
Here is what I wrote to convert the thing:
```
userInfo_request = window.js_obj.to_dict(userInfo_request)
```
(userInfo_request is my variable containing the JSObject as stated when I input 
```
print(type(userInfo_request))
```
```
<class 'JSObject'>
```
The error that I get in my browser's console is:
```
Traceback (most recent call last):
  module __main__ line 31
    userInfo_request = window.js_obj.to_dict(userInfo_request)
AttributeError: no attribute js_obj for [object Window]
```

If someone could help me it would be super cool
Thanks in advance

**Comment by PierreQuentel** [comment]
@Animenosekai 
Can you provide a code sample to reproduce the issue ?
Normally, if `userInfo_request` is a Javascript object, you can reference it in Brython by `window.userInfo_request`, for instance:
```xml
<script type="text/javascript">
userInfo_request = "hello"
</script>

<script type="text/python">
from browser import window

print(window.userInfo_request)
</script>
```

**Comment by Animenosekai** [comment]
>@Animenosekai  ...

@PierreQuentel I understood the problem.
In fact, I think it was changed in an update (but we should change the documentations) and the js_obj.to_dict got changed into JSObject.to_dict in the module “javascript” instead of “window”

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Animenosekai** [comment]
>@Animenosekai  ...

@PierreQuentel thank you for your reply tho!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
