### ISSUE TITLE
While loops make the browser freeze

### ISSUE THREAD

**Issue by Animenosekai** [brython-dev/brython#1326]
I’m trying to get the response of an api request made with ajax.ajax() and the response is stored into ['apiResponse'] in the HTML5 Local Storage (but the rest of the python function processes without waiting for it be put into localStorage).

Because of this I need to wait for it before getting the response and I thought I could do what I did below for the program to wait before it proceed.

Unfortunately the browser seems to freeze every time I put a while loop...

If someone know how to make Brython and the browser to stop freezing or another method to do what I wanna do...

(It would really help me as it’s the only step before succeeding getting Spotify api requests response)

```

from browser import ajax #to make requests
from browser.local_storage import storage as localStorage #to access HTML5 Local Storage

import json #to convert a json-like string into a Python Dict

#Request to the API
def on_complete(req):
    if req.status==200 or req.status==0:
        localStorage['apiResponse'] = req.text
    else:
        print("An error occured while asking Spotify for data")

def apiRequest(requestUrl, requestMethod):
    req = ajax.ajax()
    req.bind('complete', on_complete)
    req.open(requestMethod, requestUrl, True)
    req.set_header('Authorization', localStorage['header'])
    req.send()

def response():
    while localStorage['apiResponse'] == '':
        continue
    print('done')
    return json.loads(localStorage['apiResponse'])

```

Thanks in advance!

**Comment by PierreQuentel** [comment]
@Animenosekai 

Could you give a complete example, with the url, header, calls to the functions `apiRequest()` and `response()` ? With the code you have provided it's hard to detect what it going wrong.

In any case, the loop
```
    while localStorage['apiResponse'] == '':
        continue
```
is going to be infinite if the initial value of `localStorage['apiResponse']` is the empty string, simply because this value is not modified inside the loop.

**Comment by Animenosekai** [comment]
>@Animenosekai  ...

@PierreQuentel Yes sorry
Here is the code calling the function (which is in another file):
```
import spotifyRequest

spotifyRequest.apiRequest("https://api.spotify.com/v1/me","GET")
userInfo_request = spotifyRequest.response()

print('')
print('')

print(userInfo_request)
print(type(userInfo_request))

```

The header is a normal “Authorization” header needed by Spotify which is something like this:
`'Authorization': 'Bearer ' + token`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by PierreQuentel** [comment]
Thanks. The problem is that you send the request, and want to read the result in the same code block:

```python
# send request
spotifyRequest.apiRequest("https://api.spotify.com/v1/me","GET")
# read response
userInfo_request = spotifyRequest.response()
```

This is not how asynchronous programming works : you have to put the code that reads the result in a "callback" function that you pass as an argument in the request; this function will be called when the request is completed. Something like (untested, I don't have Spotify):

```python
import json

def callback(req):
    if req.status == 200 or req.status == 0:
        # read response
        print(json.loads(req.text))
    else:
        print("An error occured while asking Spotify for data")

def apiRequest(requestUrl, requestMethod, callback):
    req = ajax.ajax()
    req.bind('complete', callback)
    req.open(requestMethod, requestUrl, True)
    req.set_header('Authorization', localStorage['header'])
    req.send()

# send request
spotifyRequest.apiRequest("https://api.spotify.com/v1/me", "GET", callback)
```

**Comment by Animenosekai** [comment]
>Thanks. The problem is that you send the request, and want to read the result in the same code block: ...

@PierreQuentel Yes but that’s the main problem because I want the python program to wait before I get the response (because if I don’t wait and try to read the request response right after I send the request I get an empty string (because it proceed with the program without waiting to get the response))

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by PierreQuentel** [comment]
I understand that it's how you would like the program to run, but I'm afraid it's not possible. Sending an Ajax request doesn't block the program until the request completes and then executes the next instruction - unless the API supports blocking Ajax calls, ie with the third parameter of `req.open()` set to `False`, but I would be surprised if it works.

**Comment by Animenosekai** [comment]
> I understand that it's how you would like the program to run, but I'm afraid it's not possible. Sending an Ajax request doesn't block the program until the request completes and then executes the next instruction - unless the API supports blocking Ajax calls, ie with the third parameter of `req.open()` set to `False`, but I would be surprised if it works.

So there is no way of using APIs with Brython? (because the only way would be to use while loops and it seems to freeze every time we are using it)

**Comment by Animenosekai** [comment]
Oh wait, putting the third parmeter of ```req.open()``` seems to work!!!

**Comment by PierreQuentel** [comment]
Great ! can we close the  issue then ?

**Comment by Animenosekai** [comment]
>Great ! can we close the  issue then ?

@PierreQuentel Yes!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
