### ISSUE TITLE
bug report:  sets are hashable / can add sets to sets

### ISSUE THREAD

**Issue by dkosbie** [brython-dev/brython#1329]
Hi all.   I hope you are all doing ok....

And here's a bug report.  Here's the code:

```
print(hash({1,2,3}))
```

Expected output: TypeError: unhashable type: 'set'
Observed output: 9007199254740990

Similarly:

```
s = set()
s.add({1,2,3})
print(s)
```

Expected output:  TypeError: unhashable type: 'set'
Observed (erroneous) output: {{1, 2, 3}}

Thanks, and thanks for all your amazing work.

David

**Comment by PierreQuentel** [comment]
Thanks David !
