### ISSUE TITLE
Brython not playing well with Opal.

### ISSUE THREAD

**Issue by dkgof** [brython-dev/brython#1336]
I am trying to get Opal (Ruby for JS) to play well with Brython.

But for some reason if Opal is loaded before Brython, and i then try to import datetime, i get an error.

If i remove the script that loads Opal, the error goes away again.

Minimal example that has the error:
```
<!doctype html>
<html>
  <head>
    <script src="https://cdn.opalrb.com/opal/1.0.0/opal.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/brython@3.8.8/brython.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/brython@3.8.8/brython_stdlib.js"></script>
  </head>
  <body onload="brython(1)">
    <script type="text/python">
    import datetime
    </script>
  </body>
</html>
```

The error is:

```
Javascript exception: TypeError: Cannot read property 'length' of undefined
    at Object.$B.$getattr (brython.js:6908)
    at _is_dst3982 (eval at exec_module (brython.js:9272), <anonymous>:428:91)
    at eval (eval at exec_module (brython.js:9272), <anonymous>:733:65)
    at exec_module (brython.js:9272)
    at t (brython.js:6570)
    at s (brython.js:6574)
    at Object.e.import_hooks (brython.js:13989)
    at $B.$__import__ (brython.js:9428)
    at Object.$B.$import (brython.js:9472)
    at eval (eval at exec_module (brython.js:9272), <anonymous>:16:8)
```

**Comment by PierreQuentel** [comment]
@dkgof 
Interesting ! 

In Brython, the class of an object is usually determined by its attribute `__class__` but, for a reason that I don't remember, the attribute `$class` was used instead for a particular class (module), so this attribute `$class` was tested in the function that gets an object's class.

Unfortunately, it seems that Opal sets an attribute `$class` to Javascript's `Date` objects...

In the commit referenced above I have removed the use of `$class` in Brython, and your code now works. I leave the issue open for the moment, in case you find other incompatibilities.

**Comment by dkgof** [comment]
Thanks alot for the quick fix!

I will be sure to come back with any other incompatibilities i find :)

**Comment by dkgof** [comment]
Found another one, if i add the Opal-Parser module, it again gives me an error:

```
<!doctype html>
<html>
<head>
<script src="https://cdn.opalrb.com/opal/1.0.0/opal.min.js"></script>
<script src="https://cdn.opalrb.com/opal/1.0.0/opal-parser.min.js" onload="Opal.load('opal-parser')"></script>

<script src="brython.js"></script>
<script src="brython_stdlib.js"></script>
</head>
<body onload="brython(1)">
<script type="text/python">
import datetime
</script>
</body>
</html>
```

The error is:

```
ValueError: argument of long_int must be a string, not function
```

**Comment by PierreQuentel** [comment]
The latest commit changes an internal attribute `$value` used by Brython for instances of subclasses of `int` or `float` to a more specific `$brython_value`. Opal apparently sets the attribute `$value` for numbers, which caused the incompatibility.

**Comment by dkgof** [comment]
Cool, works great now!
