### ISSUE TITLE
Brython str() and repr() don't detect reference loops

### ISSUE THREAD

**Issue by solsword** [brython-dev/brython#1337]
Whereas Python 3.7 (and I presume 3.8) str() and repr() detect looping object references and insert '...' when they encounter them, Brython does not currently do this, and instead you get a RecursionError, which isn't an unreasonable result, but differs from standard Python. Here's a minimal example that triggers this behavior:

```
L = [[0], [1]]
L[0].append(L[1])
L[1].append(L[0])
repr(L) # or str(L)
```

I'd simply patch this up in my own code by defining a myrepr function like this:

```
def myrepr(obj, memo=None):
    if memo == None:
        memo = {}
    if id(obj) in memo:
        return '...'
    <repr code here that saves result in memo before returning>
```

But the problem is that although myrepr could conceivable recurse on lists, tuples, and dictionaries, custom objects with their own __repr__ (which likely call normal repr() internally) would break out of the myrepr chan, which is why i'm requesting this improvement.

The use case for this for me: I'm writing a web app where students are solving code challenges, and students started to complain that the app crashes when they submit a solution. Of course, the correct solution does not have an infinite reference loop, but students' incorrect solutions did, and my code wasn't using try/except when it attempted to print the result of the students' code to show them it was different from the expected result.

**Comment by PierreQuentel** [comment]
Thanks for the bug report :-)
