### ISSUE TITLE
Resetting the state of Brython

### ISSUE THREAD

**Issue by mrwwalmsley** [brython-dev/brython#134]
I am using Brython with an online Python course at http://codeavengers.com/python/1

In this course the learners are given coding tasks they must complete. There is a run button to run their code and a check button to check if their code is correct.

Each time the learner clicks the check or run button, the state of all brython variables, functions etc. must be reset before the learner's code is re-run.

For our level 1 courses, it seems to be sufficient to delete all the user's variables (those not beginning and ending with `__`) that are contained in `__BRYTHON__.vars.__main__` and `__BRYTHON__.bound.__main__`

Are there other things I should be clearing to restore the state of `__BRYTHON__` to what it was before the user's code was run the first time?

Should there be a reset function to reset the state of `__BRYTHON__` properties that change when code is run.

**Comment by PierreQuentel** [comment]
First let me say that I am impressed by the quality of the course. It's going to be one of the most serious references of Brython usage for real life applications.

Regarding your question, I don't understand exactly what you mean by "resetting the state" of variables and functions, and why you would want to do so. Could you give an example ?

**Comment by PierreQuentel** [comment]
Sorry, I just saw what you wrote in the comments of issue #88

I don't know if it would solve the issue, but did you try to run the code in a specific namespace using `exec(some_code, namespace)`, and reset the namespace to an empty dict afterwards ?

**Comment by mrwwalmsley** [comment]
Thanks! We included some turtle graphics lessons in there as well. We
really wanted Python 3 and Brython seemed the best option for that.

Regarding resetting the state...

If you run the following code it will print out the message "Hello"

message = "Hello"
print(message)

If you then run the following code:
#message = "Hello"
print(message)

It should reset the state of the variables and throw an error since the
message variable does not exist.
Instead, it will print "Hello" since the message variable still exists from
the first time the program ran.

On 11 February 2015 at 23:42, Pierre Quentel <notifications@github.com>
wrote:

> First let me say that I am impressed by the quality of the course. It's
> going to be one of the most serious references of Brython usage for real
> life applications.
>
> Regarding your question, I don't understand exactly what you mean by
> "resetting the state" of variables and functions, and why you would want to
> do so. Could you give an example ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brython-dev/brython/issues/134#issuecomment-73862114>.
>



-- 
Mike Walmsley
Creator of...

Learn to code, change the world!
Fun effective learning @ *codeavengers.com* <http://codeavengers.com/>

*twitter* <https://twitter.com/CodeAvengers>* | **facebook
<http://facebook.com/CodeAvengers>** | google +
<https://plus.google.com/105827980034533177298>*

**Comment by mrwwalmsley** [comment]
I currently do

__BRYTHON__.builtins.exec(code);

How do I execute in some namespace then reset the namespace dict afterward?

On 12 February 2015 at 00:12, Michael Walmsley <mike@codeavengers.com>
wrote:

> Thanks! We included some turtle graphics lessons in there as well. We
> really wanted Python 3 and Brython seemed the best option for that.
>
> Regarding resetting the state...
>
> If you run the following code it will print out the message "Hello"
>
> message = "Hello"
> print(message)
>
> If you then run the following code:
> #message = "Hello"
> print(message)
>
> It should reset the state of the variables and throw an error since the
> message variable does not exist.
> Instead, it will print "Hello" since the message variable still exists
> from the first time the program ran.
>
> On 11 February 2015 at 23:42, Pierre Quentel <notifications@github.com>
> wrote:
>
>> First let me say that I am impressed by the quality of the course. It's
>> going to be one of the most serious references of Brython usage for real
>> life applications.
>>
>> Regarding your question, I don't understand exactly what you mean by
>> "resetting the state" of variables and functions, and why you would want to
>> do so. Could you give an example ?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/brython-dev/brython/issues/134#issuecomment-73862114>
>> .
>>
>
>
>
> --
> Mike Walmsley
> Creator of...
>
> Learn to code, change the world!
> Fun effective learning @ *codeavengers.com* <http://codeavengers.com/>
>
> *twitter* <https://twitter.com/CodeAvengers>* | **facebook
> <http://facebook.com/CodeAvengers>** | google +
> <https://plus.google.com/105827980034533177298>*
>



-- 
Mike Walmsley
Creator of...

Learn to code, change the world!
Fun effective learning @ *codeavengers.com* <http://codeavengers.com/>

*twitter* <https://twitter.com/CodeAvengers>* | **facebook
<http://facebook.com/CodeAvengers>** | google +
<https://plus.google.com/105827980034533177298>*

**Comment by PierreQuentel** [comment]
From the code you post, it seems that it is run inside a Javascript program, is that true ?

If it was inside a Python program (which is a better option, see the code of the Brython console or editor)  you would do something like

```python
ns = {}
exec(code, ns)
ns = {}
```

**Comment by mrwwalmsley** [comment]
Right. I tried

__BRYTHON__.builtins.exec(code, {});

And it didn't seem to work.

Yes, it is running from a JavaScript program.

On 12 February 2015 at 01:54, Pierre Quentel <notifications@github.com>
wrote:

> From the code you post, it seems that it is run inside a Javascript
> program, is that true ?
>
> If it was inside a Python program (which is a better option, see the code
> of the Brython console or editor) you would do something like
>
> ns = {}exec(code, ns)
> ns = {}
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brython-dev/brython/issues/134#issuecomment-73876344>.
>



-- 
Mike Walmsley
Creator of...

Learn to code, change the world!
Fun effective learning @ *codeavengers.com* <http://codeavengers.com/>

*twitter* <https://twitter.com/CodeAvengers>* | **facebook
<http://facebook.com/CodeAvengers>** | google +
<https://plus.google.com/105827980034533177298>*

**Comment by mrwwalmsley** [comment]
I will try again.

On 12 February 2015 at 07:36, Michael Walmsley <mike@codeavengers.com>
wrote:

> Right. I tried
>
> __BRYTHON__.builtins.exec(code, {});
>
> And it didn't seem to work.
>
> Yes, it is running from a JavaScript program.
>
> On 12 February 2015 at 01:54, Pierre Quentel <notifications@github.com>
> wrote:
>
>> From the code you post, it seems that it is run inside a Javascript
>> program, is that true ?
>>
>> If it was inside a Python program (which is a better option, see the code
>> of the Brython console or editor) you would do something like
>>
>> ns = {}exec(code, ns)
>> ns = {}
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/brython-dev/brython/issues/134#issuecomment-73876344>
>> .
>>
>
>
>
> --
> Mike Walmsley
> Creator of...
>
> Learn to code, change the world!
> Fun effective learning @ *codeavengers.com* <http://codeavengers.com/>
>
> *twitter* <https://twitter.com/CodeAvengers>* | **facebook
> <http://facebook.com/CodeAvengers>** | google +
> <https://plus.google.com/105827980034533177298>*
>



-- 
Mike Walmsley
Creator of...

Learn to code, change the world!
Fun effective learning @ *codeavengers.com* <http://codeavengers.com/>

*twitter* <https://twitter.com/CodeAvengers>* | **facebook
<http://facebook.com/CodeAvengers>** | google +
<https://plus.google.com/105827980034533177298>*

**Comment by PierreQuentel** [comment]
Mike,

If you run

```javascript
__BRYTHON__.builtins.exec(code, {});
```
inside a Javascript program, you won't get any useful result. For instance, the object you pass as the second argument is an empty Javascript object, but Python expects a dictionary.

Generally speaking, you can use Javascript programs and libraries from Brython, but the reverse is false : Brython objects can't be easily used from a Javascript program.

If you want to run the Python source with a Brython program, take a look at the function `run` in the [editor](https://github.com/brython-dev/brython/blob/master/site/tests/editor.py)

**Comment by mrwwalmsley** [comment]
Ahh, OK, that makes sense. I may have to give that a go. I had looked at
the run function in the editor to work out which builtin function to run.

I guess things are working OK for now, but will try that other approach a
little later.

Thanks again for your help.

Mike

On 12 February 2015 at 23:08, Pierre Quentel <notifications@github.com>
wrote:

> Mike,
>
> If you run
>
> __BRYTHON__.builtins.exec(code, {});
>
> inside a Javascript program, you won't get any useful result. For
> instance, the object you pass as the second argument is an empty Javascript
> object, but Python expects a dictionary.
>
> Generally speaking, you can use Javascript programs and libraries from
> Brython, but the reverse is false : Brython objects can't be easily used
> from a Javascript program.
>
> If you want to run the Python source with a Brython program, take a look
> at the function run in the editor
> <https://github.com/brython-dev/brython/blob/master/site/tests/editor.py>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brython-dev/brython/issues/134#issuecomment-74046386>.
>



-- 
Mike Walmsley
Creator of...

Learn to code, change the world!
Fun effective learning @ *codeavengers.com* <http://codeavengers.com/>

*twitter* <https://twitter.com/CodeAvengers>* | **facebook
<http://facebook.com/CodeAvengers>** | google +
<https://plus.google.com/105827980034533177298>*

**Comment by earney** [comment]
so in short, we would do the following python:

```
ns = {}
exec(code, ns)
ns = {}
```

we would do the following in javascript:

```
__BRYTHON__.builtins.exec(code, __BRYTHON__.builtins.dict());
```

Is this correct, Pierre?

**Comment by mrwwalmsley** [comment]
Ahh... that sounds like what I am looking for.

On 17 February 2015 at 13:32, Billy Earney <notifications@github.com> wrote:

> so in short, we would do the following python:
>
> ns = {}
> exec(code, ns)
> ns = {}
>
> we would do the following in javascript:
>
> __BRYTHON__.builtins.exec(code, __BRYTHON__.builtins.dict());
>
> Is this correct, Pierre?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brython-dev/brython/issues/134#issuecomment-74596478>.
>



-- 
Mike Walmsley
Creator of...

Learn to code, change the world!
Fun effective learning @ *codeavengers.com* <http://codeavengers.com/>

*twitter* <https://twitter.com/CodeAvengers>* | **facebook
<http://facebook.com/CodeAvengers>** | google +
<https://plus.google.com/105827980034533177298>*

**Comment by niallb** [comment]
What worked for me is:

__BRYTHON__.builtins.exec(source, __BRYTHON__.builtins.dict.$factory([]));

**Comment by niallb** [comment]
What worked for me is 
```
  __BRYTHON__.builtins.exec(source, __BRYTHON__.builtins.dict.$factory([]));
```
