### ISSUE TITLE
Using .py extension for external scripts causes problems on some webhosts

### ISSUE THREAD

**Issue by andy31lewis** [brython-dev/brython#1340]
Hello again
I have been testing Brython on various webhosts, both paid and free. On most, the suggested way of loading external scripts `<script type="text/python" src="test.py"></script>` works fine.

But on some (both paid and free) webhosts, this does not work because the server treats the Ajax call to `test.py` as a request to *execute* `test.py` rather than return it as plain text. This normally fails with a HTTP 500 error as soon as a Brython-specific line of code such as `from browser import document` is encountered.

The way round this is to change the file extension to something which the server does not automatically try to execute - for example `test.bry`.

Since this works on all platforms that I have tested, I am wondering whether it would be better to change the documentation to suggest using `.bry` (or something similar) as the extension for external Brython scripts.

Andy

**Comment by PierreQuentel** [comment]
Thanks for the report Andy !

I have updated the documentation to suggest using the extension __`.bry`__ in this case. If you think this is not enough to consider the issue solved, don't hesitate to reopen it.

**Comment by andy31lewis** [comment]
Thank you, Pierre, that looks perfect to me. In my case, I think I will start using `.bry` for brython scripts in all cases, because it will help me remember which of my files are client-side brython scripts, and which are server-side python scripts.
