### ISSUE TITLE
While warlus yield, infinite loop

### ISSUE THREAD

**Issue by bit-garden** [brython-dev/brython#1341]
It seems an infinite loop is generated from trying to loop with a yield and warlus statement. The same code acts as expected and simply prints all truthy values that are sent in Cpython.

Brython:
```
def main():
  while (a:=(yield)): # something funny happens here and freezes the page.
    print(a)
next(test:=main())
test.send('magic')
```
The equivalent doesn't freeze
```
def main():
  while True:
    a = yield
    if a:
      print(a)
    else:
      break
next(test:=main())
test.send('magic')
```

**Comment by PierreQuentel** [comment]
Thank you Danny. As usual with generators, the fix was not obvious ;-)
