### ISSUE TITLE
Can't import external file

### ISSUE THREAD

**Issue by leo-smi** [brython-dev/brython#1347]
This works fine:
`
from browser import document
from browser.html import FORM, INPUT, LABEL, BR

def LoginForm():

	form = FORM(id="meu-forme", action="#", method="get", target="_blank")
	form <= LABEL('seu nome ', For='nome', name="nome")
	form <= INPUT(id='nome')
	form <= BR()
	form <= LABEL('sua senha', For='senha')
	form <= INPUT(id='senha', type='password', name="senha")
	form <= BR()
	form <= INPUT(id='submit', type='submit')
	
	return form

document <= LoginForm()
`
But this doesn't:

`
from browser import document
from login_form import LoginForm

document <= LoginForm
`

**Comment by PierreQuentel** [comment]
Could it be because in the first example the function `LoginForm` is called, and not in the second example ?

**Comment by leo-smi** [comment]
Did not work btw...But [here](https://mega.nz/folder/iTgS1Y4J#o3RZeOVsiwzVS8PiezSudg) is he files

**Comment by PierreQuentel** [comment]
It works better when you uncomment the first line of __`login_form.py`__
The error messages are like CPython, in the browser console.

**Comment by leo-smi** [comment]
Unfortunately didn't work but my question is the same as issue #565 Thank you for the support

**Comment by PierreQuentel** [comment]
Are you running a web server in the directory, or just loading __`index.html`__ by the File / Open menu ? There are [limitations](http://www.brython.info/static_doc/en/file_or_http.html) in the second case, including the impossibility to load modules.

Generally speaking, it always helps to copy / paste the error message besides just reporting that a program "doesn't work".

**Comment by leo-smi** [comment]
It worked, I have tried to create a server but now I can. Sorry for the issue title!

1. I opened cmd in the project folder and ran `python -m http.server`
2. I opened http://localhost:8000/index.html where index.html is the html page project (it can be changed )

**Comment by PierreQuentel** [comment]
Can we close the issue then ?

**Comment by leo-smi** [comment]
Yes, thank you for the support!
