### ISSUE TITLE
How can I route print() to a DIV box?

### ISSUE THREAD

**Issue by danijar** [brython-dev/brython#1348]
I'm working on a web editor, where the user can inert Python code. So far, I'm simply passing the content of the text box to `eval()` to execute it. I'm printing errors to a DIV box using `traceback.format_exc()`. However, `print()` statements in the user code still show up only in the Browser's developer console. Is there a way to temporarily route stdout into a variable?

**Comment by PierreQuentel** [comment]
Sure, as in standard Python you can assign `sys.stdout` and `sys.stderr` to an object with a `write()` method, for instance if a TEXTAREA element has the id "console":

```python
from browser import document
import sys

console = document["console"]

class Output:

    def write(self, arg):
        console.value += str(arg) + "\n"

output = Output()

sys.stdout = sys.stderr = output

print("test") # "test" is printed in the TEXTAREA element
1 / 0         # same for the ZeroDivisionError error message
```

**Comment by danijar** [comment]
Awesome, thanks!
