### ISSUE TITLE
Is it possible to console.log() the JS objects underlying Python objects?

### ISSUE THREAD

**Issue by danijar** [brython-dev/brython#1349]
When logging Python variables via `print()`, they often show up as `<Object object>` or similar in the browser's developer console. However, this doesn't provide much information that could be useful for debugging, and is often followed by `print(dir(...))` to get at least a bit more information. In contrast, logging JS objects natively using `console.log()` gives an interactive output where one can expand nested values etc. Would it be possible to leverage this feature for Python objects?

**Comment by PierreQuentel** [comment]
You can use Javascript `console.log()` this way:
```python
from browser import console
console.log(object)
```
You can test this for instance on a DOM element (referenced by `document[elt_id]`) to see the difference with `print()`.

Does this help ?

**Comment by danijar** [comment]
Great, that makes sense. This works well, not just for DOM elements but also to inspect properties of other objects. Thanks again.
