### ISSUE TITLE
How can I execute Brython when including it through Browserify?

### ISSUE THREAD

**Issue by danijar** [brython-dev/brython#1351]
I'm hoping to load Brython into the client side code through Browserify, so that it can be bundled together with all other dependencies into one file. This seems to work well with all other NPM packages I've tried, so it's surprising that it doesn't work with Brython.

deps.js

```javascript
// This file and all its required dependencies will be bundled by Browserify
// to make them available to scripts in index.html. This lets us use NPM
// packages for client side scripts.

// Make _require() available to the front end to load the modules listed
// in the present file. Note: We would usually assign to `window.require`,
// however, this seems to cause an infinite recursion for Brython.
window._require = require

// Require NPM packages to be used by the front end, so that they will
// be included in the bundle.
require('brython')
require('tone')
```

index.html

```html
<html>
<body>
</body>

<!-- Load our dependencies. -->
<script type="text/javascript" src="bundle.js">

<!-- Activate Brython for the script below. -->
<script type="text/javascript">
Tone = _require('tone')  // This works.
brython = _require('brython')
brython({debug: 1})  // This doesn't work.
</script>

<!-- Use the dependencies. -->
<script type="text/python">
print('Hello world!')
from browser import window
path = 'https://cdn.jsdelivr.net/gh/Tonejs/Tone.js/examples/audio/505/snare.ogg'
Tone = window._require('tone')
Tone.Player.new(path).connect(Tone.Volume.new(-12).toDestination()).start()
</script>

</body>
</html>
```

Comands

```sh
mkdir example && example
npm init
npm install brython
npm install browserify
npm install tone
npx browserify deps.js -o bundle.js
google-chrome index.html
```

Developer console output

```
Uncaught TypeError: Cannot read property 'name' of undefined
```

**Comment by PierreQuentel** [comment]
@danijar 
I am really sorry but I can't answer this question. I don't know anything about browserify and I don't want to learn every environment to check if it is compliant with Brython. Hopefully people who know better than me can help, but I am closing this issue with the "wontfix" label.

**Comment by danijar** [comment]
Okay, I see. That's a bit unfortunate because I think compatibility with Browserify and Webpack could help increase adoption of Brython.

The error above seems to be the same that occurs with Webpack (https://github.com/brython-dev/brython/issues/1284), suggestion that it may be about using Brython as a JS module in general rather than about a specific packaging tools.

I've opened https://github.com/browserify/browserify/issues/1960 to see if Browserify developers have an idea what is causing this.

**Comment by PierreQuentel** [comment]
@danijar 
Just an idea reading your code again : the function `brython()` is executed in a Javascript script at a moment when the HTML page has not finished loading : at that time, the Python script is not yet available, so `brython()` will not be able to find it.

Could you replace this call by
```javascript
window.addEventListener("load", function(){
  brython({debug: 1})
})
```
and tell me if it fixes the issue ?

**Comment by danijar** [comment]
One step further! Importing does not raise an error anymore but it seems to import an empty object, likely because Brython does not export anything in a way module loaders expect:

```html
<html>
<body>
<body>
<script type="text/javascript" src="bundle.js"></script>
<script type="text/python">print('Hello world!')</script>
<script type="text/javascript">
brython = _require('brython')
console.log(brython)  // {}
window.addEventListener('load', () => {
  brython({debug: 1})  // Uncaught TypeError: brython is not a function
})
</script>
</body>
</html>
```

I think the solution for this would be to turn Brython into an UMD module. This way, it will work both with JavaScript module loaders and when included as a `<script>` tag:

```js
(function (root, factory) {
if (typeof define === 'function' && define.amd) { define([], factory); }  // AMD
else if (typeof module === 'object' && module.exports) { module.exports = factory(); }  // CommonJS
else { root.brython = factory(); }  // Script tag
}(typeof self !== 'undefined' ? self : this, function () {
// ...
return brython;
}));

**Comment by danijar** [comment]
@PierreQuentel What are your thoughts on supporting something along the lines or my previous comment?

**Comment by PierreQuentel** [comment]
As I said, I am not in favour of including this in Brython. If you want to add support for Browserify, you can fork the project and add what is required in this environment.
