### ISSUE TITLE
webcomponent weird __init__ behavior.

### ISSUE THREAD

**Issue by perkinslr** [brython-dev/brython#1354]
Apologies for the uninformative title, I'm not sure how to describe this...  So I have a somewhat complicated `webcomponent`, using shadow root (`self.shadow = self.attachShadow(a)`), similar to the example.  But I want to save the shadow root in order to edit its internalHTML later, (essentially reset the GUI component in-place).  Trying to access `self.shadow` later (from another function) fails, with an attribute error.  So I added a bunch of print statements.

    class Map:
        def __init__(self):
          self.shadow = self.attachShadow({'mode':'open'})
          print(self)
          Map._s = self
          self.addHeader()
        def addHeader(self):
    #      self.shadow <= "hello"  # fails
            print(self)
            print(Map._s)
    #      print(self.shadow) # fails
            print(Map._s is self)
            print(Map._s == self)
            print(Map._s.shadow)
            Map._s.shadow <= "world"

Pasting that in the console, you get the following

    >>> a = document.createElement('test-map')
    <__main__.Map object>
    <Map object>
    <__main__.Map object>
    False
    True
    <ShadowRoot object>

It seems that the object passed from `__new__` to `__init__` is not the object which gets bound to the function returned by `getattr(self, 'addHeader')`, or... something.  

It's not a show stopper, but it is incredibly surprising behavior, and doesn't seem to be documented anywhere.  If the object passed in to `__init__` isn't the actual object that's going to get bound to data descriptors (and returned by `__new__`, or created by the machinery when adding the dom element), maybe it would be better to have a class or static method instead of `__init__` for custom components.

**Comment by perkinslr** [comment]
Please note that I have figured out that the shadow root is accessible elsewhere via `self.shadowRoot`, but *any* value set as `self.var = val` in `__init__` gets lost.

**Comment by PierreQuentel** [comment]
@perkinslr 
I tested your script with Brython 3.8.8 and it actually fails, but not with the current development version. I have no idea why ;-)

Here is the complete HTML page:
```xml
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<script type="text/javascript" src="/src/brython.js"></script>
<script type="text/javascript" src="/src/brython_stdlib.js"></script>
</head>

<body onload="brython()">

<map-tag>map tag</map-tag>
<script type="text/python">
from browser import webcomponent

class Map:

    def __init__(self):
      self.shadow = self.attachShadow({'mode':'open'})
      print(self)
      Map._s = self
      self.addHeader()

    def addHeader(self):
        self.shadow <= "hello"
        print(self)
        print(Map._s)
        print(self.shadow)
        print(Map._s is self)
        print(Map._s == self)
        print(Map._s.shadow)
        Map._s.shadow <= " world"

webcomponent.define("map-tag", Map)
</script>

</body>
</html>
```

**Comment by PierreQuentel** [comment]
I am closing the issue since I think it is fixed, if it is not the case you can of course reopen it. Thanks !

**Comment by perkinslr** [comment]
Alright, that's mostly fixed.  It's still odd that `self is Map._s` is False, but it appears that attributes set on one correctly get mapped to the other, so it should function.  

It might be better to use `__new__(cls)` instead of `__init__(self)`, since `__init__` is *supposed* to be called on the final object, so that identity check *should* be True, whereas `__new__` is a classmethod and expected to return a new object, which is *not* the value of `cls` (but should be related to it, usually an instance).
