### ISSUE TITLE
parsing multi-line generator expressions with comments may fail

### ISSUE THREAD

**Issue by coproc** [brython-dev/brython#1355]
When commenting a multi-line generator expression I ran into an unexpected syntax error. A minimal example showing the parsing problem is this:

    def f():
      [{ # comment
        0: 0} # comment
        for _ in []]

Outside a function definition the above expression can be parsed. Also removing one of the comments makes the expression parsable.

**Comment by PierreQuentel** [comment]
Thanks for the report :-)

**Comment by coproc** [comment]
And many thanks to you for your continued support
