### ISSUE TITLE
"Improving" communication

### ISSUE THREAD

**Issue by GiovanniSM20** [brython-dev/brython#1356]
hi there, have you thought about implementing a communication channel like [Gitter](https://gitter.im/) ?

this could be used to answer questions and suggestions for the project...

**Comment by PierreQuentel** [comment]
@GiovanniSM20 
It's a good idea, and if someone creates such a channel I will join it. Thanks !

**Comment by GiovanniSM20** [comment]
@PierreQuentel I'll try to wait for more people from the community to speak up and also suggest other channels to see what's best for everyone, okay ? wait a little while and no one demonstrating I create there to communicate. We have Slack, Discord and others also.

**Comment by PierreQuentel** [comment]
May I suggest that you post a message on the Google group to get more feedback ?
