### ISSUE TITLE
Brython and electron desktop

### ISSUE THREAD

**Issue by yescine** [brython-dev/brython#1357]
I tried to combine Brython with electon.js to make a desktop application but nothing worked, no error, no warning!

here the link for the template I created https://github.com/yescine/Brython-electron

**Comment by PierreQuentel** [comment]
@yescine 
Sorry, I have no idea what electron.js is, and I can't learn all the various frameworks in the Javascript ecosystem - I have had similar reports for Webpack and browserify these last days and made the same answer. If someone can fix this issue it's fine, but I am closing it with the "wontfix" tag. Désolé :-(
