### ISSUE TITLE
implement pathlib

### ISSUE THREAD

**Issue by goffi-contrib** [brython-dev/brython#1359]
Hello,

while testing Brython I've seen that `pathlib` from stdlib is not implemented. I understand that many methods from it are tricky or impossible in the context of Brython (like `Path.stat` or `Path.open` even if we could probably adapt them like it was done for the builtin `open` method), but the filename manipulation methods of `pathlib` are really handy and very useful even in the web context.

Would it be possible to implement this lib, and if no what is preventing implementation?

Thank you, and thank you very much for this great project.

**Comment by PierreQuentel** [comment]
Thanks for the report. It's likely that only a small part of __`pathlib`__ is usable, but the basics seem to work:

```
>>> import pathlib
>>> p = pathlib.Path('/etc')
>>> q = p / 'init.d' / 'reboot'
>>> q
PosixPath('/etc/init.d/reboot')
```

**Comment by goffi-contrib** [comment]
great, it was really quick! Thank you very much :)
