### ISSUE TITLE
integrate console in brython lib (or optional module)

### ISSUE THREAD

**Issue by goffi-contrib** [brython-dev/brython#1362]
Hello,

The console available at http://www.brython.info/tests/console.html is really handy, and could be particularly valuable during development phase (a REPL shell is really useful to check values or test methods).

For the moment, the code is available only in `www` dir of Brython source (and notably in) `www/tests/console.py`, which make it cumbersome to install for testing purpose.

Would it be possible to move the code in Brython stdlib in a way that would it make it trivial to create a console in a `<div>`? That would be of great help!

Thanks

**Comment by PierreQuentel** [comment]
Many thanks, this has to be one of the most interesting suggestions ever !

In commits 16581f70bbf1da9358a54fa6dab8ba429b89327a and aafda32ab9cac968e8bbf14ba1d5121f969ea9c3 I have added a module __`browser.repl`__ which exposes a single class, `Repl`. It is called with
```python
Repl(elt_id=None, globals=None, locals=None)
```
where

- _elt_id_ is the id of a textarea in the page. If set to `None`, opens a popup window with a textarea
- _globals_ and _locals_ are the environment where REPL commands will be executed. By default they are empty dictionaries, but they can be passed to debug a script with code like

```python
from browser import repl

x = 8

repl.Repl(globals=globals())
```
where the REPL runs in a namespace with the names `x` and `repl` set.

I have adapted the console pages (__`www/console.html`__ and __`www/tests/console.html`__) to use this module.

Please let me know what you think and report issues if you find any.

**Comment by goffi-contrib** [comment]
I've just tried, it's working great, it's a good idea to create a popup by default.
As a future improvement could it be possible to get file descriptor for it, e.g. to redirect `stdin` and `stdout` there? Could be used for `pdb` too :)

**Comment by PierreQuentel** [comment]
`stdin` and `stdout` are actually redirected to the textarea when an instance of `Repl` is created.

Not sure about __`pdb`__ because a popup window is not blocking, and you need to block program execution at breakpoints.

**Comment by goffi-contrib** [comment]
I see, for pdb it's not a big deal to use the JS console. Thanks a lot, this `repl` module will be super useful!

**Comment by goffi-contrib** [comment]
@PierreQuentel after testing again, I have an issue: if I launch `repl.Repl()`, nothing is stored, I can import or assign anything.
Here is the Python code:
```python
from browser import repl

repl.Repl()
```
And then in the console:
```
Brython 3.8.9 on Netscape 5.0 (X11)
>>> import os
>>> os
Traceback (most recent call last):
  File <string>, line 1, in <string>
NameError: name 'os' is not defined
>>> y=3
>>> y
Traceback (most recent call last):
  File <string>, line 1, in <string>
NameError: name 'y' is not defined
```

**Comment by PierreQuentel** [comment]
In the previous commit I have fixed this bug and added another class to __`browser.repl`__. I have called it `Debugger` although I am not too sure if this is a correct name. It is meant to be used in code like:

```python
from browser import repl

def f(x):
    x += 3
    if x > 5:
        repl.Debugger()
    x += 1
    return x

f(4)
```

This opens a popup window with an interpreter open in the execution frame where `Debugger()` is called. With the dropdown menu you can select the execution frame where you want to execute code.

Opening the interpreter doesn't freeze code execution, but the namespace where it runs is a copy of `globals()` and `locals()` at breakpoint, so that if you enter

```
>>> x
```

in the example above, the value will be 7 (value when `Debugger()` was called) and not 8 (value when code execution ends).

Any feedback / bug report / feature request is welcome !

**Comment by goffi-contrib** [comment]
It's a good idea

> I have called it Debugger although I am not too sure if this is a correct name.

I would expect from something called `Debugger` to have commands similar to pdb (`continue`, `next`, etc). Maybe something like `Inspect` would fit better?

I've tested it it works, but the value of `x` is `8` and not `7`. Also the background of the dialog transparent on my site (console background is dark, but dialog is transparent), making it hard to see the dropdown.

**Comment by goffi-contrib** [comment]
OK I get it: `x` is `7` when checking it just when the popup is opened, but if I use the dropdown to change the frame and go back to the one of `f`, then `x` is `8`

**Comment by PierreQuentel** [comment]
Bien vu !
I have renamed to `Inspector` which is indeed more adapted, and "frozen" the execution frames namespace to avoid the problem you mention.

**Comment by PierreQuentel** [comment]
I have changed the implementation once again : instead of __`browser.repl`__ it is now in __`interpreter`__, at the top level of the stdlib. There was no compelling reason to put it in the __`browser`__ package, which is mostly related to the interface with the DOM, and "interpreter" is more explicit than "repl".

I have also written the documentation pages in French and English for this module (to see them in folder _/static_doc_, run __`scripts/make_doc.py`__). Any feedback is appreciated :-)

**Comment by goffi-contrib** [comment]
Hello @PierreQuentel , I've tried to test it, but I have 

```python
Traceback (most recent call last):
  module __main__ line 1
    from interpreter import Inspector
ModuleNotFoundError: interpreter
```

I've installed from `master` `HEAD` in a virtual env using `python setup build && python setup install` then `python -m brython --install` in a test directory. Is there something I'm missing?

**Comment by PierreQuentel** [comment]
Isn't it rather `python setup.py sdist` instead of `build` ? I just tried it and the interpreter was found.

**Comment by goffi-contrib** [comment]
ah indeed, the `setup.py` script checks for `sdist` command. That would be nice to have it work with `build` too, otherwise we have to look for the dist archive, uncompress it, then install brython from there, it's a bit cumbersome when we want to try quickly last developments.

Also I was using the wrong installation of brython, that's why the module was not found.

Anyway I've just test it, it looks like it's working fine, it's really handy, thanks a lot. Should I close this issue?

**Comment by PierreQuentel** [comment]
You just have to do `python setup.py sdist` then `python setup.py install`, no need to look for an archive and uncompress it.

If you are ok with the module, yes, you can close the issue.

Encore un grand merci pour l'idée et les retours !
Pierre

**Comment by goffi-contrib** [comment]
@PierreQuentel oh right I've read again the script, it's copying `data`, so indeed the `python setup.py sdist && python setup.py install` is working. Is this explained somewhere. I don't see this in the documentation. Anyway this is out of topic for this issue.

Yeah I'm fine with the module, thank you for the positive feedback, I'm closing this ticket.
