### ISSUE TITLE
Python Packages

### ISSUE THREAD

**Issue by Sachin5411** [brython-dev/brython#1367]
Hi , 
I have been enjoying brython very much 
Can I add packages like Numpy , Pandas etc... to brython?

**Comment by PierreQuentel** [comment]
Unfortunately not, these packages use code written in C and Brython only supports pure Python code.

Anyway, Brython's goal is to develop front-end applications for the browser. I doubt that the browser is a relevant platform for heavy calculation.

**Comment by perkinslr** [comment]
If you need numpy to work not for heavy computation, but for easy matrix operations, check out https://github.com/wadetb/tinynumpy
It's mostly API compatible with numpy, but is going to be *much* slower.  A more ambitious project would be to compile numpy via emscripten, which could then be used from brython.
