### ISSUE TITLE
Unpack with self reference in class doesn't unpack

### ISSUE THREAD

**Issue by bit-garden** [brython-dev/brython#1368]
I'm not sure which update caused this one. It can be remedied by wrapping the self.* in parenthesis, but it is likely to be causing issues in pure python packages somewhere. 

Brython:
```
Brython 3.8.8 on Netscape 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/78.0.3904.108 Chrome/78.0.3904.108 Safari/537.36
>>> class Test:
...   def __init__(self):
...     self.count = [1, 2, 3]
...   def test_unpack(self):
...     print([*self.count])
... 
>>> t = Test()
>>> t.test_unpack()
[[1, 2, 3]]
```

CPython:
```
Python 3.8.2 (default, Feb 26 2020, 02:56:10) 
[GCC 7.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> class Test:
...   def __init__(self):
...     self.count = [1, 2, 3]
...   def test_unpack(self):
...     print([*self.count])
... 
>>> t = Test()
>>> t.test_unpack()
[1, 2, 3]
```

**Comment by PierreQuentel** [comment]
Thanks Danny. To be honest, I don't think this has ever worked, or has it ?

**Comment by bit-garden** [comment]
I was wondering that myself. I thought it may have been a side effect of one of the other unpacking buts I reported, but I can't find a spot it was working. 

I love this project and the attention you give it. This makes it a bit harder to say that b2f9ee6 doesn't fix the issue. 

The asserts added to the test fail still.

**Comment by PierreQuentel** [comment]
Are you testing on brython.info or with the latest development version ?

**Comment by bit-garden** [comment]
I did latest development version (at the time was https://github.com/brython-dev/brython/blob/b2f9ee6594e826bf7951254a8363e5a44ca1cd81/www/src/brython.js)

**Comment by bit-garden** [comment]
At the time I pulled from the lastest. I just did it again this morning and it is working fine. My browser probably cached it. Sorry. Thanks!

**Comment by PierreQuentel** [comment]
No worries, thank you !
