### ISSUE TITLE
add a __version__ attribute

### ISSUE THREAD

**Issue by goffi-contrib** [brython-dev/brython#1369]
Brython version is set in `implementation` attribute, but it is common practice to put it in `__version__`, and the way recommended by https://www.python.org/dev/peps/pep-0396/, it should be put there too.

**Comment by goffi-contrib** [comment]
note: I've made a PR with the attribute at https://github.com/brython-dev/brython/pull/1370

**Comment by PierreQuentel** [comment]
Good catch !
I have fixed the bug, but not as you suggested in the PR : __`setup/brython/__init__.py`__ is generated by __`make_dist.py`__, so it is this script that had to be modified.

**Comment by goffi-contrib** [comment]
> setup/brython/__init__.py is generated by make_dist.py, so it is this script that had to be modified.

Oh alright! I'm not yet used to Brython architecture :)
Again thanks for your quick feedback.
