### ISSUE TITLE
code objects compiled with "compile" can't be evaluated with "eval"

### ISSUE THREAD

**Issue by glyph** [brython-dev/brython#137]
On http://brython.info/tests/console.html just now:

```
>>> codeobj = compile("3 + 4", "<example>", "eval")
>>> eval(codeobj)

TypeError: undefined is not a function (evaluating 'src.replace(/\r\n/gm,'\n')')
  module 'exec-131' line 1
eval(codeobj)
  module 'exec-131' line 1
eval(codeobj)
```

compare CPython 3.4:

```
>>> codeobj = compile("3 + 4", "<example>", "eval")
>>> eval(codeobj)
7
```

**Comment by glyph** [comment]
Thanks a ton!

**Comment by rbarve** [comment]
I find an inconsistency between a compiled code object being exec'd and an unpreprocessed code statement being exec'd in regards to the update of accompanying context dictionary:

Brython 3.1.1 on Netscape 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.39 Safari/537.36
>>> x=4
>>> cd=dict(globals())
>>> cd.update(locals())
>>> exec("x=x+4",cd)
>>> x
4
>>> cd['x']
8
>>> y=5
>>> yd=dict(globals())
>>> yd.update(locals())
>>> co=compile("y=y+4","","exec")
>>> exec(co,yd)
9
>>> yd['y']
5
>>>
