### ISSUE TITLE
JS to_dict conversion bug

### ISSUE THREAD

**Issue by ese942** [brython-dev/brython#1375]
There's seems to be a bug with handling data returned by the[ chrome.storage.local API](https://developer.chrome.com/extensions/storage).  This API is used inside chrome extensions.
Docs for the [API call get ()](https://developer.chrome.com/extensions/storage#method-StorageArea-get).

# Example code
```
data = {}
data ['key1'] = {'foo' : 'bar'}
data ['key2'] = {'rab' : 'oof'}
...
chrome.storage.local.set (data, callback)

# later on...
chrome.storage.local.get (none, other_callback)

def other_callback (obj):
    console.log (obj)
    # prints: {key_1: {foo: 'bar'}, key_2: {rab: 'oof'}}
    data = obj.to_dict ()
    console.log ('data = %s' % data)
    # raises exception: Javascript exception: TypeError: Cannot read property '$is_class' of undefined
```

obj is a regular javascript data object.  The issue seems to be that obj gets properly wrapped as a javascript object, but the dicts stored as values inside obj do not.  

```
data ['key1'] ['foo']  # throws error
data ['key1'].foo  # returns 'bar'
data ['key1'].to_dict () # throws error
```

# Steps to reproduce the bug

1. Download and unzip attached file below.  This contains a skeleton chrome extension with brython.
2. Go to Chrome Extensions page in your browser (at chrome://extensions/), enable Developer Mode switch at top right, then Load Unpacked button at top left
3. In the dialog, choose the directory 'min-ext' where you unzipped the file.
4. Now open the test page in the extension to run the brython script:
- Method 1: click the white arrow on blue circle in your browser extension icons to the right of the address bar (icon installed by extension).  This will open a new tab with the test page.
- Method 2:  get the extension ID from your extensions page, a string of 30+ random chars.  Enter the test page url in your address bar: chrome-extension://<id_string>/test.html

That's it.  Open the console and examine the output.  
You can make changes to test.py in the min-ext directory, refresh the test page, and see the results.  
The brython 3.8.8. lib is also loaded from the min-ext directory.

[brython-ext.zip](https://github.com/brython-dev/brython/files/4548582/brython-ext.zip)

**Comment by PierreQuentel** [comment]
@ese942 
Many thanks for the precise report, I could reproduce the bug and propose a fix. Does it work for you ?

**Comment by ese942** [comment]
Thanks Pierre.  Yes it seems to work now.  Thanks for your help.

For others' benefit here's how I tested the fix:
Downloaded the file brython.js from your change above.  Put it in my min-ext dir, updated test.html to point to it, and reloaded the extension.

It got past the first hurdle - the log statement on line 45 of test.py now succeeds.  It prints this:
`brython.min.3.8.9.js: items = {'key1': {'foo': 'bar', 'mod': True, 'seen': 1588189145790}, 'key2': {'mod': False, 'rab': 'oof', 'seen': 1588189145790}}`

Looks like the embedded objects were also converted to dicts.  Super.

After the fix, it now raises an error on line 55 of test.py.  But that's expected because your patch already converted the value to a dict.  Line 55 is obsolete and can be removed.   So everything looks good.  Thanks so much.

You even fixed the warning that JSObject.to_dict is deprecated and going away. :)

**Comment by PierreQuentel** [comment]
Can we close the issue ?
Thanks again, I am ashamed to confess that I didn't even know what a Chrome Extension was before :-(
