### ISSUE TITLE
`browser.load` is not respecting `cache: true` argument

### ISSUE THREAD

**Issue by goffi-contrib** [brython-dev/brython#1378]
Hello,

I'm using `browser.load` to dynamically load javascript libraries in my website (I'm then wrapping in Python module, like in the documentation example at http://www.brython.info/static_doc/fr/jsobjects.html). It's working, but I see that the javascript module is loaded each time I hit the webpage, even if it didn't change on the HTTP server. I've set the `cache: true` option while calling brython (it's launched with `<body onload='brython({"debug": 1, "cache": true})'>`) and I would expect the `browser.load` method to then use cache (a dummy `?foo=xxx` suffix is added after library name despite the `cache: true`).

steps to reproduce
------------------------
- start brython with `"cache": true` option
- load any javascript module with `browser.load`
- open the page, check that javascript module is loaded with a `200` HTTP code
- reload the page

**expected result**: the cache is hit, and javascript module is loaded with a `304` (Not Modified) code
**actual result**: the JS library is downloaded again, with a `200` code.

**Comment by PierreQuentel** [comment]
I think that the commit above fixes the bug. The browser prints a status 200 but it seems that browser cache is used.
