### ISSUE TITLE
Indentation error when typing doctest example in console

### ISSUE THREAD

**Issue by natec425** [brython-dev/brython#1379]
I may be doing something wrong, but I don't seem to be able to write a doctest example in the brython console without getting an IndentationError. I've attached a screenshot below to demonstrate. The definition is fine when I don't use all 3 `>`s. However, once I try to write a docstring with a complete `>>>` it errors.

Please let me know if I'm missing something obvious or if there is some way I can help. Thanks!

![image](https://user-images.githubusercontent.com/1424988/80833146-9bf2aa00-8bb3-11ea-945b-3d318b2e12d3.png)

**Comment by PierreQuentel** [comment]
@natec425 
Thanks for the report, the bug was that for multiline statements, the program executed the code starting at the latest string ">>>" before the current caret position... It's the kind of bug that makes me laugh :-)
