### ISSUE TITLE
How to compile Brython package by Brython under development?

### ISSUE THREAD

**Issue by ShenTengTu** [brython-dev/brython#1382]
As PR #1380 , I plan to do the translation.

I need to compile the updated `www/assets/header.py` into `header.brython.js`,  in order to preview the language options and the translated menu.

I use `pip install -e` in the virtual environment to install the module, but this method can't make Brython execute normally.

**Comment by PierreQuentel** [comment]
You should install the CPython package brython with `pip install brython`, then run this command in the directory __`www/assets`__:
```
python -m brython --make_package headers
```

**Comment by ShenTengTu** [comment]
OK, I got it.
