### ISSUE TITLE
Problem with functools.partial

### ISSUE THREAD

**Issue by ese942** [brython-dev/brython#1383]
Found what appears to be an error with functools.partial in Brython.  This code works fine in python but brython console throws an error:

```
Brython 3.8.8 on Chrome/81.0.4044.129
>>> import functools
>>> import random
>>> random.randrange (100)
60
>>> func = functools.partial (random.randrange, 100)
>>> func () 
Traceback (most recent call last):
  File <string>, line 1, in <module>
  File VFS._functools.py, line 41, in __call__
    return self.func(*self.args,*args,**newkeywords)
ValueError: non-integer arg 2 for randrange()
```

Brython scripts throw the same error.  Easier to demonstrate with console.

It seems the type of the argument is lost between the call to partial and the call to func.  If I had to take a wild guess, perhaps it has something to do with javascript automatic type coercion?  Could the 100 be saved as a string or other non-int type somewhere in the javascript plumbing?

Another possibility is that the functools.partial is invoking the saved random.randrange function incorrectly.  randrange accepts up to 3 arguments.  No matter how many args you supply, the error always complains about argument n+1.  For example:

```
>>> func = functools.partial (random.randrange, 0, 100, 1);  func ()
Traceback (most recent call last):
  File <string>, line 1, in <module>
  File VFS._functools.py, line 41, in __call__
    return self.func(*self.args,*args,**newkeywords)
ValueError: non-integer arg 4 for randrange()
```

# Steps to reproduce

1. Open a [brython console](https://brython.info/tests/console.html?lang=en) 
2. Enter statements above

**Comment by PierreQuentel** [comment]
Thanks @ese942 !
The problem was that `random.randrange()` did not accept keyword arguments.
