### ISSUE TITLE
Cannot delete attribute of subclasses of HTML or SVG elements

### ISSUE THREAD

**Issue by andy31lewis** [brython-dev/brython#1384]
Hello again
This code works as expected:
```python
class A():
    def __init__(self, s):
        self.myattr = s

x = A("Andy")
print(hasattr(x, "myattr"), x.myattr)
del x.myattr
print(hasattr(x, "myattr"))
```
Output:
```
True Andy
False
```
But if A is subclassed from any HTML or SVG object, then deleting `myattr` fails:
```python
import browser.html as html

class A(html.DIV):
    '(the rest as above)'
```
Output:
```
True Andy
Traceback (most recent call last):
  File <string>, line 10, in <module>
AttributeError: 'A' object has no attribute 'myattr'
```
(This may be related to #829. But I hope not, because that one caused a lot of trouble!)

Many thanks in advance,

Andy

**Comment by perkinslr** [comment]
Looks similar to issue #1354 

My workaround is to use

import browser.html as html

    class A(html.DIV):
        def __init__(self, s):
            super().__init__()
            self.postInit(s)
        def postInit(self, s):
            self.myattr = s

Note that this is supposed to be fixed (by accident) in the latest dev build.

**Comment by PierreQuentel** [comment]
Thanks Andy, this one was super-easy :-)
