### ISSUE TITLE
Bug in string conversion

### ISSUE THREAD

**Issue by ese942** [brython-dev/brython#1388]
# Issue
Converting certain objects to string results in a javascript TypeError: Cannot read property '$is_class' of undefined.  The object is otherwise valid and can be serialized and unserialized to JSON with no problems.  The problem only occurs with the latest 3.8.9.dev version of Brython.  The code runs fine in Brython v3.8.0.

# Explanation

The object that triggers the bug is a list of [BookmarkTreeNodes](https://developer.chrome.com/extensions/bookmarks#type-BookmarkTreeNode).  The nodes are returned by the chrome extension bookmarks API.  It returns a tree structure containing nodes and children, which is an array of nodes.  My code sorts these nodes into folders and bookmarks.

The problem happens with folders.  I make a python list called `recent` containing folder objects returned by the API.  The `recent` list can be displayed in console.log, but conversion to string (%s) fails for no obvious reason.

I tried to serialize the `recent` list with JSON, hoping a brython script could simply unserialize and reproduce the error.  However it doesn't work.  The unserialized object works fine with %s.

I found one difference between the raw and unserialized objects.  Each folder in `recent` has a children array.  In my code, the children object has a property `__class__`.  I assume this came from the chrome API call as the tree structure was created by the API.  I never converted any part of the bookmark tree to a Brython object.  Serialized copies of `recent` do not have a __class__ property.  I'd guess it's the source of the problem.  See sample output from javascript console (line starting with __class__ under element 22:):

```
>>> console.log (recent)
Array(2)
0: children: Array(23)
0: {dateAdded: 1589362422455, id: "59353", index: 0, parentId: "59352", title: "foo 1", …}
1: {dateAdded: 1589362422465, id: "59354", index: 1, parentId: "59352", title: "foo2", …}
2: {dateAdded: 1589362422470, id: "59355", index: 2, parentId: "59352", title: "foo3", …}
...
22: {dateAdded: 1589362422624, id: "59376", index: 22, parentId: "59352", title: "foo 23", …}
__class__: {__class__: {…}, __mro__: Array(1), $infos: {…}, $is_class: true, $native: true, …}
length: 23
__proto__: Array(0)
dateAdded: 1589362422430
dateGroupModified: 1589362422624
id: "59352"
index: 188
parentId: "18939"
title: "john carter"
__proto__: Object
```

# Steps to reproduce

1. Download and unzip attached file below.  This contains a skeleton chrome extension with brython.
2. Go to Chrome Extensions page in your browser (at chrome://extensions/), enable Developer Mode switch at top right, then Load Unpacked button at top left
3. In the dialog, choose the directory 'min-ext-bk' where you unzipped the file.
4. Now open the test page in the extension to run the brython script:
- Method 1: click the white arrow on blue circle in your browser extension icons to the right of the address bar (icon installed by extension).  This will open a new tab with the test page.
- Method 2:  get the extension ID from your extensions page, a string of 30+ random chars.  Enter the test page url in your address bar: chrome-extension://<id_string>/test.html

That's it.  Open the console and examine the output.
You can wait until the script writes "finished" to the html page.  With large bookmark collections, it can take several seconds to process (runs slower if console is open).

You can make changes to test.py in the min-ext directory, refresh the test page, and see the results.  

The latest brython lib 3.8.9-dev-0 is loaded from the min-ext-bk directory.  Brython 3.8.0 is also included - no errors if you switch to that version in test.html.

[min-ext-bk.zip](https://github.com/brython-dev/brython/files/4622152/min-ext-bk.zip)

**Comment by PierreQuentel** [comment]
Thanks Edward ! The commit referenced above should fix this bug, but it's hard to imagine all the possible interactions between Javascript and Brython objects, I wouldn't be surprised if you submit other issues shortly ;-)
