### ISSUE TITLE
Class variables handled incorrect in __dict__

### ISSUE THREAD

**Issue by jorants** [brython-dev/brython#1392]
Consider the class:
```
class A():
    b = "This is b"
    message = "This is a"
    def __init__(self):
        self.x = 5
```
Then
```
for k in A.__dict__:
    print(k)
```
Shows "b" but not "message", it seems something is special about this variable name.

Also `A.__dict__["__dict__"]` is not the same dictonary, it contains very different values (including `$$message`).

If we instantiate A then the instance variables will show up but the class ones do not:

```
a = A()
print(a.b) # works, so b is present
print(a.__dict__) # {'x':5}
```

In all cases `dir` seems to give the right key back, so
```
A__dict__ = {k: getattr(A,k) for k in dir(A)}
```
works as a sort of replacment, altough it contains to many values compared to cpython.

**Comment by PierreQuentel** [comment]
@jorants 
Thanks for the bug report. `message` is part of a list of "aliased" names to avoid confusion with Javascript reserved names : they are translated internally with leading `$$`, and sometimes Brython doesn't correctly "un-alias" them.

I have not found a list of the keys that should be included in a class `__dict__`, so I leave it as it is now, hoping that this falls into the "implementation-specific" category ;)
