### ISSUE TITLE
Setting a DOMNode JSObject attribute does not convert the value to JS

### ISSUE THREAD

**Issue by mircea3** [brython-dev/brython#1393]
Consider the following example (Chromium supported, but I'm not sure about other browsers):
```
from browser import window, html
video = html.VIDEO()
video.srcObject = window.MediaStream.new()
```

Currently, this results in a JS exception: `Failed to set the 'srcObject' property on 'HTMLMediaElement': The provided value is not of type 'MediaStream'.`

The following modification demonstrates the problem and a quick fix, in this particular case, but probably a nicer solution exists (py_dom.js, around line 1056, in `__setattr__`):
```
// Set the property
self.elt[attr] = value.js || value
```

**Comment by PierreQuentel** [comment]
Thanks @mircea3 
I adapted your proposal, first testing if `value.js` is an instance of the Javascript class `TargetEvent`, which should cover most of the elements that are liable to be set as attribute values.
