### ISSUE TITLE
String formatting - precision truncation not up to spec

### ISSUE THREAD

**Issue by whoisteri** [brython-dev/brython#1396]
When using a formatting string that includes a precision specification, the results are not the same as CPython's 

**Example:**
```
print("|{0:.4}|".format("Hello"))
# Expected output: |Hell|
```
Top - output from [brython console](https://brython.info/console.html)
Bottom - output from CPython 3.6.9 on my machine
![image](https://user-images.githubusercontent.com/3697116/82297437-f3b25300-99b2-11ea-9c49-dd8c4b41c52d.png)

**Example 2**
```
print("|{0:.4}|".format(1.2345678))
# CPython output: |1.235|
# Brython output: |1.2346|
```

**For floating point numbers:** In Brython, the precision argument is taken to mean how many decimal places the result should have. Instead, `precision` expresses how many significant digits should be displayed. E.g. `"{0:.3}".format(12345.0)` should output `1.23e+04` (which is 12300.0 exactly)
**For strings:** In Brython, the result is always the entire string instead of just first `n` letters.

**Comment by PierreQuentel** [comment]
Thanks @whoisteri !
