### ISSUE TITLE
Generator loop `continue` inside `except` block not working

### ISSUE THREAD

**Issue by mircea3** [brython-dev/brython#1398]
The failing example is shown below:

```
out = []
prn = out.append
def g():
    while 1:
        prn('start')
        err = 0
        try:
            yield
        except Exception as ee:
            prn(str(ee))
            err = 1
            # work-around: shift left (out of `except`):
            if err:
                continue
        prn('end')
    prn("shouldn't be here")

g = g()
prn('1:'); next(g)
prn('2:'); next(g)
prn('3:'); g.throw(Exception('ERROR'))
prn('4:'); next(g)
prn('5:'); next(g)
assert out == [
    '1:', 'start',
    '2:', 'end', 'start',
    '3:', 'ERROR', 'start',
    '4:', 'end', 'start',
    '5:', 'end', 'start']
print('\n'.join(out))
```

As a work-around, one may use a variable (`err` in the example) and place the `continue` statement outside of the `except` block. However, this work-around **does not** work if the `while` loop is replaced with a `for` loop. In that case, there is no crash, but the output is incorrect. In other words, `while` and `for` loops behave differently with respect to this issue.

**Comment by PierreQuentel** [comment]
@mircea3 

Thanks for this bug report. 

After years of maintaining an implementation of Python generators written initially at a time when there was no generators in Javascript - it was by far the most difficult thing I ever had to code for Brython, with the most bugged result -, I have spent the last weeks rewriting this implementation with JS generators. 

I have committed the result a few minutes ago. As I expected, this issue is fixed ; hopefully, you should find it more difficult to find new bugs now ;-)

Many thanks again for all these reports, without them I would probably have postponed this work to an undetermined future...

**Comment by mircea3** [comment]
Thank you, Pierre! I would personally classify this changeset as another landmark improvement to Brython (although, after all the fixes, the previous version seemed pretty close.)

I spent some time backporting this to an older version of Brython to test with an older browser. It works well, at least back to Pale Moon 27.5.1 (2017-10-10). Below are a few notes resulting from the testing.

The following tiny change fixes a problem:

```
py_generator.js, around line 85:

- throw _b_.StopIteration.$factory(value)
+ throw _b_.StopIteration.$factory(res.value)
```

A currently failing example to demonstrate this:

```
def gg():
    yield
    yield

gg = gg()
next(gg)
assert gg.send(100) == None
```

If I'm not mistaken, the following bits of code are no longer needed:

1) `py2js.js`: all references to `.is_try` and `.is_catch`

2) `py2js.js`, around line 9047: `func_scope.ntype = 'generator'`

3) `py_builtin_functions.js`, around line 362:

```
// If obj is a generator object with a context manager whose method
// __exit__ has not yet been called, call it
if(obj.$is_generator_obj && obj.env){
    for(var attr in obj.env){
        if(attr.search(/^\$ctx_manager_exit\d+$/) > -1){
            $B.$call(obj.env[attr])()
            delete obj.env[attr]
        }
    }
}
```

4) `py_utils.js`, around line 1170:

```
if(frame[1][key] && frame[1][key].$is_generator_obj){
    var gen_obj = frame[1][key]
    // If the generator object's attribute env has an attribute
    // $ctx_manager_exit, it means that a context manager has not yet
    // called the method __exit__ (issue #1143)
    if(gen_obj.env !== undefined){
        for(var attr in gen_obj.env){
            if(attr.search(/^\$ctx_manager_exit\d+$/) > -1){
                // Call __exit__
                $B.$call(gen_obj.env[attr])()
                return true
            }
        }
    }
}
```

The following bit of code seems to make no difference for tests, but I do not understand all the implications (`py2js.js`, around line 9065):

```
$get_node(this).context.tree[0].transform = function(){
    return context.transform.apply(context, arguments)
}
```

**Comment by PierreQuentel** [comment]
Thanks @mircea3 , I am impressed by how you know Brython code !
I included these changes and a few other cosmetic ones in the commit referenced above.
