### ISSUE TITLE
Brython website broken

### ISSUE THREAD

**Issue by ese942** [brython-dev/brython#1399]
The Brython website has broken with a change in the last few days.

The navigation bar across the top (Tutorial, Demo, Documentation, etc) no longer works.  The items are no longer links, but `<span>` classes inside a `div.banner_row`.

Since they are not real links with <a> tags:
1. Middle click / ctrl-click to open in a new tab fails
2. Open in new window fails
3. They can not be copied and pasted, without loading the page first
4. They can not be sent to others, without loading the page first
5. Link:visited styling no longer works to show visited links and history

among other issues.  These fake links cause terrible usability problems.  See e.g. 
https://www.accessibilityoz.com/2014/02/links-and-accessibility/
https://formidable.com/blog/2014/05/08/anchors-buttons-and-accessibility/
https://www.sitepoint.com/15-rules-making-accessible-links/
https://usability.yale.edu/web-accessibility/articles/links
https://usabilitygeek.com/15-usability-guidelines-for-designing-web-site-links/

Many screen readers and browsers for the visually impaired won't even recognize the top row as links.  In the US this would violate laws on accessibility for disabled people.

The W3 HTML validator can't even validate the page.  I've seen many badly formed web pages over the years but never one the validator choked on before.
https://validator.w3.org/nu/?doc=https%3A%2F%2Fbrython.info%2Fstatic_doc%2Fen%2Fjsobjects.html

Please change it back to the old version.

**Comment by PierreQuentel** [comment]
Good point Edward, thanks for reporting this. I will update the site this weekend.

**Comment by ese942** [comment]
Merci beaucoup.  Following web standards is a worthwhile effort.

If you describe what you were trying to accomplish with the change, perhaps
I can suggest a way to do the same thing with regular anchor tags <a>.
They can be tricky to work with at times.

**Comment by PierreQuentel** [comment]
The original idea was to reduce the number of items in the main navigation bar, because it doesn't render correctly on small devices. I also wanted to use the menu widgets that I developed for version 3.8.9.

Before the commit above, menu items were not implemented as anchor tags with an associated "href" attribute, but as <span> elements with a callback function, which caused the issues you reported. The fix consists in adding another method to menu items, that insert anchor tags instead of <span> elements.

**Comment by ese942** [comment]
Ok, so everything works as you want it now?  Mobile websites are tricky,
but in general there are ways to hide or change how elements  appear on
mobile with css.  Some examples:

https://www.w3schools.com/howto/howto_js_mobile_navbar.asp
https://www.thesitewizard.com/css/hide-images-on-mobile-website.shtml

I saw the new menu widgets in the release notes.  Sounds interesting.  I'll
check out the new documentation pages when I have time.

Thanks Pierre.
Edward
