### ISSUE TITLE
optimization - line_info

### ISSUE THREAD

**Issue by JamesHutchison** [brython-dev/brython#140]
When code is transpiled to javascript, it appears that the line_info code is inefficient

```
$B.line_info=[187,"sre_compile"];None;
```

I'm not sure why there's a trailing `None` but I would imagine there is a small overhead cost to its inclusion. Also, I would think this would execute faster if the line number was kept as a separate value and was simply updated rather than creating a new list structure every single line (which also adds to the garbage collection overhead)

**Comment by earney** [comment]
James,
Are you proposing something what is below instead?
```
$B.line_pos=187;
$B.line_module="sre_compile";
```

**Comment by JamesHutchison** [comment]
probably without the redundant line_module unless its needed. Otherwise the array might be cheaper. For example when you switch to a new module, the module changes. Otherwise only the line number is updated.

**Comment by earney** [comment]
of course.. that makes sense.

**Comment by earney** [comment]
It looks like Pierre ( or maybe someone else) has implemented a solution, by creating a variable called line_info, which is a string, and contains the line number, a comma, and then the module name.  This should be much more efficient.
I'm going to close this, but feel free to open if more discussion is needed.
