### ISSUE TITLE
Question: Does this allow easier passing of variables from thepython backend to the frontend?

### ISSUE THREAD

**Issue by Frick-David** [brython-dev/brython#1400]
I am hoping to be able to pass a pandas Dataframe easily to the front-end without having to make it into json. Is this possible with Brython?

**Comment by PierreQuentel** [comment]
I am sorry, I don't know what a "pandas Dataframe" is.

**Comment by Frick-David** [comment]
Yeah, so python has a very popular library named pandas for data science that has an object named Dataframe (much like an Excel spreadsheet). I use it quite a bit in  my work but unfortunately it does not like to play nice with javascript. Passing variables from the Python backend to the javascript front-end ends up being quite a chore that I am looking for ways to simiply.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by PierreQuentel** [comment]
I'm afraid I can't help much for this issue. Just for the record, since this has been discussed by people who know this library, pandas is not supported by Brython because it uses modules written in C.

**Comment by Frick-David** [comment]
Okay thanks for the info.
