### ISSUE TITLE
Some numerical functions can't handle subclass of float

### ISSUE THREAD

**Issue by andy31lewis** [brython-dev/brython#1401]
Hi again
I created a subclass of `float` (yes I know it may be an odd thing to do, but it should work).  Instances of that class behave like floats in most respects, but break some functions (either built-in, or imported from `math` module).

```python
from math import sin, log

class Angle(float):
    def __new__(cls, angle, point):
        return super().__new__(cls, angle)
    def __init__(self, angle, point):
        self.points = point

x = Angle(36.9, (1,2))
y = Angle(53.1, (3,4))

print(x, x+y, x<y, x**0.5)
print(abs(x), int(x), sin(x), log(x))
```
CPython output (as for normal floats):
```
36.9 90.0 True 6.074537019394976
36.9 36 -0.7167370231606575 3.6082115510464816
```
Brython 3.8.9 output:
```
36.9 90.0 True 6.074537019394976
nan nan nan nan
```
A rather obscure use case, but I thought it was worth reporting as the same bug may occur in other situations.
Thanks!
Andy

**Comment by bit-garden** [comment]
Can you test with a version made after commit 8ea4765. There was a change in how the numbers were being handled.

**Comment by andy31lewis** [comment]
Good idea. However I have just tried with the latest from master branch, and it made no difference - the output was still as above.
