### ISSUE TITLE
python -m brython --add_package math broken?

### ISSUE THREAD

**Issue by ceprio** [brython-dev/brython#1403]
I'm using brython version 3.8.9 over Python 3.6.8 and when I issue this command in the same folder where I did a `python -m brython --install`:
```
python -m brython --add_package math
```
I get this error:
```
add package math...
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python36\lib\site-packages\brython\__main__.py", line 142, in <module>
    main()
  File "C:\Program Files\Python36\lib\site-packages\brython\__main__.py", line 48, in main
    package_file = package.__file__
AttributeError: module 'math' has no attribute '__file__'
```
Documentation is lacking as I did not found any expaination to this or step by step examples as to how to add the math or time or other packages to a distribution.

I also have this same issue open on Stackoverflow for a few days now and would love for some answers:

[Brython: how do I get packages (math, time, etc.)](https://stackoverflow.com/questions/62057267/brython-how-do-i-get-packages-math-time-etc)

Brython seem very promissing, I just can't wait to get started.

Thank you,

**Comment by PierreQuentel** [comment]
You don't have to install anything to use the module __`math`__, it is already in Brython standard distribution.
```
Brython 3.8.9 on Netscape 5.0 (Windows)
>>> import math
>>> math.sqrt(2)
1.4142135623730951
>>> 
```

**Comment by ceprio** [comment]
That unlocked my issue: math is part of the brython_stdlib.js file that must be loaded as a script in the html file along with brython.js. So something like this:
```
    <script type="text/javascript" src="/brython.js"></script>
    <script type="text/javascript" src="/brython_stdlib.js"></script>
```

My problem was that my second script command had a typo and it was not loaded. This gave out console output that thew me off to thinking that math file was missing:
```
brython.js:9188 GET http://127.0.0.1:5000/time.py?v=1591284638836 404 (NOT FOUND)
brython.js:9188 GET http://127.0.0.1:5000/time/__init__.py?v=1591284638855 404 (NOT FOUND)
brython.js:9188 GET http://127.0.0.1:5000/Lib/site-packages/time.py?v=1591284638881 404 (NOT FOUND)
brython.js:9188 GET http://127.0.0.1:5000/Lib/site-packages/time/__init__.py?v=1591284638909 404 (NOT FOUND)
```
So thank you, and I hope that anyone that makes the same mistake will stumble upon this post.

Now the fun begins :)
