### ISSUE TITLE
A way to run inline javascript

### ISSUE THREAD

**Issue by goffi-contrib** [brython-dev/brython#1408]
Hello,

this is just a suggestion open for discussion. I've been using `pyjamas` (a Python 2 => JS transpiler) which was allowing to run native javascript using something like
```python
import JS

JS(""""
some_javascript_here();
""")
```

In the same spirit as integrating inline assembly in C/C++.

I wonder if this would make sense to do the same in Brython. This would allow to access all features of JS without overhead when necessary (for performance reason or because something is not accessible to Brython).

What do you thing about it?

Thanks!

**Comment by PierreQuentel** [comment]
The global Javascript namespace is available in Brython through the `window` object, and it includes Javascript `eval()`:
```python
from browser import window

js = """var t = {a: 1, b: 2}
document.write(Object.keys(t))"""

window.eval(js)
```

**Comment by goffi-contrib** [comment]
Oh right! Thanks, I've missed it. Nothing to add then, sorry for the noise :)

I'm closing this ticket

**Comment by PierreQuentel** [comment]
Pas de problème !

Another way to use Javascript code inside Brython is to define names in a Javascript program, and to reference them in Brython through this `window` object, as explained in the [documentation](https://www.brython.info/static_doc/en/jsobjects.html), section "Objects in Javascript programs".
