### ISSUE TITLE
[Sugestion] instalation path using CLI

### ISSUE THREAD

**Issue by dunossauro** [brython-dev/brython#1409]
When we install Brython using pip. We are presented with a beautiful way to place the javascript files in our project.

However, if we had more files in that directory we have to create a new folder for that and then move to our old assets folder.

Is it really necessary to use an empty path?

What do you think of a parameter for the command and installation where we pass the path?

https://github.com/brython-dev/brython/blob/47b76c35f5725f8b6adbf2db1b9d2c5c3fe4baec/setup/brython/__main__.py#L78-L90

**Comment by PierreQuentel** [comment]
Hi Eduardo, _obrigado_ for your promotion of Brython on Twitter :-)

The idea was to avoid to erase __`brython.js`__ and __`brython_dist.js`__ in case they are already present in the directory. Maybe another option would be to test if these scripts exist and if so, ask the user if he wants to update them ?

**Comment by dunossauro** [comment]
Don't thank me. Your work is incredible, it has to be shown to as many people as possible.

_Je suis celui qui doit remercier_ :heart: 

I would like to contribute to this implementation. Could you explain to me how you would like this to be done?

**Comment by PierreQuentel** [comment]
In the section for the option "--install", the program could test if there is a script __`brython.js`__, and if so, use `input()` to ask the user if it should be overridden ("The script brython.js is already present in this directory. Override ? (Y/N)"); abort if N and proceed if Y.

I don't think it's useful to test the other files in the distribution (__`brython_stdlib.js, demo.html`__ etc.)

If this makes sense I will be glad to merge your first Pull Request !

**Comment by PierreQuentel** [comment]
@dunossauro The changes in your fork look good to me, but I don't see a Pull Request, can you create it ?
