### ISSUE TITLE
[Suggestion] Seemplify useability of `brython`

### ISSUE THREAD

**Issue by redradist** [brython-dev/brython#1413]
Currently Brython installation is require to install brython compiler in project folder and than load it like this:
```html
<script src="brython.js"></script>
<script src="brython_stdlib.js"></script>
```

But what if you will add to release file also raw *.js files then loading brython would be much easier as for me :)
```html
<script src="https://github.com/brython-dev/brython/releases/download/3.8.9/brython.js"></script>
<script src="https://github.com/brython-dev/brython/releases/download/3.8.9/brython_stdlib.js"></script>
```

**Comment by PierreQuentel** [comment]
@redradist 
Thanks for the suggestion. In fact this is already possible, Brython is available on CDNs, but your report made me realize that this was documented in the Github home page but not in the documentation...
The fix updates the ["Install" documentation page](https://www.brython.info/static_doc/en/install.html).

**Comment by redradist** [comment]
> 
> 
> @redradist
> Thanks for the suggestion. In fact this is already possible, Brython is available on CDNs, but your report made me realize that this was documented in the Github home page but not in the documentation...
> The fix updates the ["Install" documentation page](https://www.brython.info/static_doc/en/install.html).

It is very cool, thanks for link !!

I think you need to add button for donate in such way community will help you with your work ;)

**Comment by PierreQuentel** [comment]
>  I think you need to add button for donate in such way community will help you with your work ;)

I appreciate the intention, but I prefer that people who appreciate Brython donate to the Python Software Foundation, for reasons explained in the [Contributing guide](https://github.com/brython-dev/brython/blob/master/CONTRIBUTING.md)
