### ISSUE TITLE
[Idea] Precompiled Python code

### ISSUE THREAD

**Issue by redradist** [brython-dev/brython#1414]
Consider the following improvement:
```html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/brython/3.8.9/brython.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/brython/3.8.9/brython_stdlib.min.js"></script>
    </head>

    <body onload="brython(1)">
        <script type="text/python" src="lib.py" precompiled></script>
    </body>
</html>
```

If `script` tag marked with custom attribute `precompiled` then `Brython` first will try to download `lib.py.js` and if there are no precompiled `lib.py.js` fallback to downloading `lib.py` and only if there is no `lib.py` produce an error

In such way `Brython` could improve performance if there are a lot of `Python` code should be compiled ... but anyway it should be tested if there is significant performance improvement

**Comment by PierreQuentel** [comment]
I am not in favour of this feature. It would require that every time the Python source code is modified, it must be translated to Javascript and saved to a .js file, this is not how Brython is designed : web client development should remain as straightforward as possible, edit the Python file and reload the page without a precompilation step.

In case there are many files to translate, the solution used in Brython is to generate __`brython_modules.js`__ which takes advantage of the indexedDB cache, where the translation to Javascript is handled without any explicit action of the developer.

**Comment by SamBugler** [comment]
Would there not be performance improvements with this feature? Another advantage of having this feature available would be that it would have some parallels with ReactJS which is compiled to JS. So, in theory you could create complex Brython client side apps that could compete with ReactJS client side apps for example.

You could code your client side app in python, compile it to JS and upload it to the server, just as a ReactJS developer would do.

**Comment by jsbueno** [comment]
One can do everything you are saying without any pre-compiling already.

Brython is a well conformand Python implementation and allows one to write
arbitrarily large and complex applications as it is - without the
minimizing + obfuscation steps using React in Javascript require.

**Comment by SamBugler** [comment]
Are there any tests to illustrate performance comparisons? Is it currently feasible to pre-compile it if someone wanted to make such tests?
