### ISSUE TITLE
[Idea] Compile Python code with Brython statically

### ISSUE THREAD

**Issue by redradist** [brython-dev/brython#1416]
It would be nice to compile `Python` code with `Brython` statically as `TypeScript` did

By doing so it expand `Brython` also to `Node.js` and `Deno` run-times as platform for writing application instead of `JavaScript`

It is also cool because `Node.js` and `Deno` have `JIT` execution mechanism that is much faster then original `Python` implementation and also those run-times have `Worker`-s (Active Object Pattern) that allow to have real `Multi-Threading` execution

**Comment by redradist** [comment]
Also I would suggest to concentrate on `Deno` run-time, because it supports from the box almost all browser elements like `window`, `console`, and etc.

Also it would be nice to run `Brython` application with `Deno` like this:

```console
deno main.py
```

Of course it would be possible it `Deno` team dissed that `Brython` is deserve to be on of the languages to be able run as one of the supported languages

Underhood it could do the following things:

```console
python -m mypy main.py # If Python and mypy is installed run the following type checking
deno brython.js main.py # If Compile main.py to main.js that contains run-time, standard library and main logic
deno main.js
```

**Comment by schmave** [comment]
This file https://github.com/brython-dev/brython/blob/master/scripts/node_bridge.js can be run using node like this:

`node scripts/node_bridge.js test.py` 

and it will compile and execute the code in `test.py` using Node. Imports don't work right now, but this is the basic idea. You could use this as a starting place. I've never used deno, but I imagine that something like node_bridge.js would work with it as well.

**Comment by redradist** [comment]
> 
> 
> This file https://github.com/brython-dev/brython/blob/master/scripts/node_bridge.js can be run using node like this:
> 
> `node scripts/node_bridge.js test.py`
> 
> and it will compile and execute the code in `test.py` using Node. Imports don't work right now, but this is the basic idea. You could use this as a starting place. I've never used deno, but I imagine that something like node_bridge.js would work with it as well.

Okay, thanks !!

I have looked at code and even run it with debugger, but I did not get how to hook importing module with `Brython` ?

**Comment by redradist** [comment]
I have found that it should be provided hook like this:
```javascript
__BRYTHON__.import_hooks = function import_hooks(type, style, customSelectorText) {
    var result = __BRYTHON__.meta_path.slice();
    var builtins = __BRYTHON__.builtins;
    var data = __BRYTHON__.imported;
    
    var el;
    var value;
    if (customSelectorText) {
        var lastOpenParenLoc = result.indexOf(__BRYTHON__.finders["path"]);
        if (lastOpenParenLoc > -1) {
            result.splice(lastOpenParenLoc, 1);
        }
    }
    /** @type {number} */
    var len = result.length;
    for (var i = 0; i < len; i++) {
        var el = result[i];
        var callback = __BRYTHON__.$getattr(el, "find_spec", builtins.None);
        if (callback == builtins.None) {
            var callback = __BRYTHON__.$getattr(el, "find_module", builtins.None);
            if (callback !== builtins.None) {
                el = callback(type, style);
                if (el !== builtins.None) {
                    var result = __BRYTHON__.$getattr(el, "load_module");
                    var item = __BRYTHON__.$call(result)(type);
                    data[type] = item;
                    return item;
                }
            }
        } else {
            value = callback(type, style);
            if (!__BRYTHON__.is_none(value)) {
                item = __BRYTHON__.imported[value.name];
                if (item !== undefined) {
                    return data[value.name] = item;
                }
                el = builtins.getattr(value, "loader", builtins.None);
                break;
            }
        }
    }
    if (el === undefined) {
        var exc = builtins.ModuleNotFoundError.$factory(type);
        /** @type {string} */
        exc.name = type;
        throw exc;
    }
    if (__BRYTHON__.is_none(item)) {
        if (value === builtins.None) {
            throw builtins.ModuleNotFoundError.$factory(type);
        }
        var itemName = builtins.getattr(value, "name");
        if (!__BRYTHON__.is_none(el)) {
            var result = builtins.getattr(el, "create_module", builtins.None);
            if (!__BRYTHON__.is_none(result)) {
                item = __BRYTHON__.$call(result)(value);
            }
        }
        if (item === undefined) {
            throw builtins.ImportError.$factory(type);
        }
        if (__BRYTHON__.is_none(item)) {
            item = __BRYTHON__.module.$factory(type);
            var key = builtins.getattr(value, "origin");
            if (builtins.getattr(value, "has_location")) {
                /** @type {string} */
                key = "from '" + key + "'";
            } else {
                /** @type {string} */
                key = "(" + key + ")";
            }
        }
    }
    item.__name__ = itemName;
    item.__loader__ = el;
    item.__package__ = builtins.getattr(value, "parent", "");
    item.__spec__ = value;
    var key = builtins.getattr(value, "submodule_search_locations");
    if (item.$is_package = !__BRYTHON__.is_none(key)) {
        item.__path__ = key;
    }
    if (builtins.getattr(value, "has_location")) {
        item.__file__ = builtins.getattr(value, "origin");
        __BRYTHON__.$py_module_path[item.__name__] = item.__file__;
    }
    var e = builtins.getattr(value, "cached");
    if (!__BRYTHON__.is_none(e)) {
        item.__cached__ = e;
    }
    if (__BRYTHON__.is_none(el)) {
        if (!__BRYTHON__.is_none(key)) {
            data[itemName] = item;
        } else {
            throw builtins.ImportError.$factory(type);
        }
    } else {
        var key = builtins.getattr(el, "exec_module", builtins.None);
        if (__BRYTHON__.is_none(key)) {
            item = builtins.getattr(el, "load_module")(itemName);
        } else {
            data[itemName] = item;
            try {
                key(item);
            } catch (e) {
                delete data[itemName];
                throw e;
            }
        }
    }
    return data[itemName];
}
```

But from my point of view it is too complicated ...
I thought smaller hook like get module with name and all other things will be done by `Brython` ...

Anyway ... I cannot understand ...

@schmave 
I have modified little bit your import hook function, but it still does not work:
```javascript
function $import_single(module) {
  var search_path=['./www/src/libs', './www/src/Lib'];
  var ext=['.js', '.py'];
  var mods=[module, module+'/__init__'];

  for(var i=0, _len_i = search_path.length; i < _len_i; i++) {
     for (var j=0, _len_j = ext.length; j < _len_j; j++) {
         for (var k=0, _len_k = mods.length; k < _len_k; k++) {
             var path=search_path[i]+'/'+mods[k]+ext[j]

             //console.log("searching for " + path);
             var module_contents;
             try {
               module_contents=fs.readFileSync(path, 'utf8')
             } catch(err) {}
             if (module_contents !== undefined) {
                console.log("imported " + module)
                //console.log(module_contents);
                if (ext[j] == '.js') {
                   return $import_js_module(module,alias,names,path,module_contents)
                }
                 __BRYTHON__.$py_module_path['__main2__']=path
                 var js = __BRYTHON__.python_to_js(module_contents, '__main_soln__')
                return module_contents
             }
         }
     }
  }
  console.log("error time!");
  res = Error()
  res.name = 'NotFoundError'
  res.message = "No module named '"+module+"'"
  throw res
}
```

Actually I do not know what should I return `python` code or `javascript` code ?

**Comment by redradist** [comment]
> 
> 
> This file https://github.com/brython-dev/brython/blob/master/scripts/node_bridge.js can be run using node like this:
> 
> `node scripts/node_bridge.js test.py`
> 
> and it will compile and execute the code in `test.py` using Node. Imports don't work right now, but this is the basic idea. You could use this as a starting place. I've never used deno, but I imagine that something like node_bridge.js would work with it as well.

I have fixed issue with importing single module ;)

**Comment by PierreQuentel** [comment]
I have merged the PR, thanks @redradist 

But I am getting dizzy with all these frameworks : only in the last 2 months there have been requests for Brython to be adapted to work with Webpack, Opal, jinja2, node.js, Deno, Travis, BeautifulSoup, Electron and Browserify...

I have nothing against these requests, but if they are included in the project, Brython users will expect that it works for months or years, support new versions of these programs, and if the author of the initial Pull Request loses interest in the mean time, I don't want to have to maintain it myself, or explain to users that I remove the feature.

An option would be to open a Wiki page pointing to forks of Brython that work with these frameworks. Would that be ok ?

**Comment by redradist** [comment]
@PierreQuentel 
> 
> I have merged the PR, thanks @redradist
> 
> But I am getting dizzy with all these frameworks : only in the last 2 months there have been requests for Brython to be adapted to work with Webpack, Opal, jinja2, node.js, Deno, Travis, BeautifulSoup, Electron and Browserify...

It is the price to pay for getting popular ;)

> I have nothing against these requests, but if they are included in the project, Brython users will expect that it works for months or years, support new versions of these programs, and if the author of the initial Pull Request loses interest in the mean time, I don't want to have to maintain it myself, or explain to users that I remove the feature.

This mean you need to expand support team for example organize small organization
Nowadays organizations are payless to open on GitHub

> An option would be to open a Wiki page pointing to forks of Brython that work with these frameworks. Would that be ok ?

I do not think it is a good idea ... all this requests are strictly related to `JavaScript` ecosystem and supporting them you are achieveing your goal:
```
...
Brython is designed to replace Javascript as the scripting  language for the Web. 
...
```

**Comment by PierreQuentel** [comment]
> This mean you need to expand support team

"Of things, some depend upon ourselves, others do not depend upon ourselves." (Epictetus)

**Comment by lborgman** [comment]
I would suggest being able to compile Python to JavaScript with Node.js would be very nice. The translated code code should (at least in my case) be used in the web browser. (I do not know Python, but I need the functionality in some code written by others. And the code I am interested in will change quite often so I need to auto-generate the JavaScript files.)

Using Brython in the web browser will not work in my case since the number of imports is huge.

**Comment by PierreQuentel** [comment]
No, Brython is designed to run without precompiling. If the number of imports is important, you can create a file with all the scripts used by your program and the Javascript translation will be done only once and stored in an indexedDB cache (cf. [implementation of import](https://www.brython.info/static_doc/en/import.html))

**Comment by redradist** [comment]
@lborgman 
> 
> 
> I would suggest being able to compile Python to JavaScript with Node.js would be very nice. The translated code code should (at least in my case) be used in the web browser. (I do not know Python, but I need the functionality in some code written by others. And the code I am interested in will change quite often so I need to auto-generate the JavaScript files.)
> 
> Using Brython in the web browser will not work in my case since the number of imports is huge.

Agree with you, brython potentially could be very useful in separate run-time like NodeJs due perfomance of NodeJs that has JIT inside

... but @PierreQuentel not really like this idea ...

**Comment by redradist** [comment]
@lborgman @PierreQuentel Also this feature could help choose Python instead of JavaScript for people that like Python, but want speed of NodeJs runtime
