### ISSUE TITLE
Multiple import optimisation

### ISSUE THREAD

**Issue by ShaneFarrell** [brython-dev/brython#142]
I'm not sure if you already do this or not, but sinse having multiple import statements in a block is such a common idiom; you could probably make the compiler recognise import blocks and have it request the source code for all of them asynchronously at the same time. You could still run them in order, it's just that there's no point in waiting on requesting the files.

... Actually now that I think of it; you could probably do that for all top level static imports in the file. There might be some problem with that I'm not thinking of. But it sounds fine to me right now.

**Comment by ShaneFarrell** [comment]
Actually you could probably do it for all imports using the import statement. And if it's not prohibitively difficult to do with the way you've implemented it; you could probably asynchronously compile them too. You could just wait until they were actually supposed to have been compiled to throw any syntax errors you get.

**Comment by olemis** [comment]
Hi Shane !
:)

What you say is consistent with the third approach I mentioned in a
previous thread [1]_ about asynchronous module imports by integrating
them with (existing?) AMD/UMD loaders . I'd like to have the time to
work on that feature , hopefully any time soon .


.. [1] https://groups.google.com/d/topic/brython/EwP9PIsXN8M

--
Regards

Olemis


On 2/22/15, ShaneFarrell <notifications@github.com> wrote:
> Actually you could probably do it for all imports using the import
> statement. And if it's not prohibitively difficult to do with the way you've
> implemented it; you could probably asynchronously compile them too. You
> could just wait until they were actually supposed to have been compiled to
> throw any syntax errors you get.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/brython-dev/brython/issues/142#issuecomment-75425527


-- 
Regards,

Olemis - @olemislc

Apache(tm) Bloodhound contributor
http://issues.apache.org/bloodhound
http://blood-hound.net

Blog ES: http://simelo-es.blogspot.com/
Blog EN: http://simelo-en.blogspot.com/

Featured article:

**Comment by JamesHutchison** [comment]
I'd also like to point out that Mozilla is contemplating removing the ability to block on AJAX calls.

Either way, we need a solution that allows you to load all your code in about the time it takes to make 2 or 3 sequential requests.

I like the idea of using sys.path to tell Brython what to pre-fetch, and using JSON objects to store common sets of code and transpiled javascript.

having imports all fetched at once would help as well, but I would typically think an individual would package an entire project into a single json file that contains the transpiled code for maximum efficiency.
