### ISSUE TITLE
Input event handling

### ISSUE THREAD

**Issue by qualblue** [brython-dev/brython#1423]
I had problems to correctly work with input events. I only wanted to get informed about changed characters within contenteditable divs. Therefore I had to use the data attribute. But I always got <<dom>.xxxx> types from this function.
I finally changed the "data" section of the DOMEvent.__getattribute__ function in 
 py_dom.js(~line 325):
if(self.dataTransfer !== undefined){
should be replaced with
if(self.dataTransfer != undefined){
Afterwards normal input and pasted input was correctly shown with ev.data/ev.data.data.getData(...)
on firefox.

This change was inspired from the 
https://rawgit.com/w3c/input-events/v1/index.html#interface-InputEvent-Attributes
document (Editing host | inputType | data | dataTransfer)

**Comment by PierreQuentel** [comment]
Thanks for the report and the suggestion. I fixed the bug slightly diffently:
```javascript
if(dataTransfer !== null){
    ...
}
```
