### ISSUE TITLE
urllib.parse.urlencode fails for multi line strings

### ISSUE THREAD

**Issue by andy-5** [brython-dev/brython#1424]
With Brython 3.8.8 and 3.8.9, the following code throws an exception:

```python
import urllib.parse

text = """Hello
World"""

print(urllib.parse.urlencode({"text": text}))
```

The exception is:

```
Exception: <Javascript TypeError>: self.$hashes is undefined
```

This code works fine with Brython 3.8.0. Also, changing `text` to e.g. `text = "Hello World"` works as expected for all Brython versions.

**Comment by PierreQuentel** [comment]
Thanks for the report !
