### ISSUE TITLE
Issue with print's f-string handling of new = option when printing function call

### ISSUE THREAD

**Issue by Ulugbeg** [brython-dev/brython#1427]
Newly introduced in 3.8 (https://docs.python.org/3/whatsnew/3.8.html#f-strings-support-for-self-documenting-expressions-and-debugging), this fails when trying to print a function call; it works fine for variables & expressions as far as I can tell.

To use the example from the what's new:
Python:
```python
Python 3.8.3 (default, May 17 2020, 18:15:42) 
[GCC 10.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from math import cos,radians
>>> theta = 30
>>> print(f'{theta=}  {cos(radians(theta))=:.3f}')
theta=30  cos(radians(theta))=0.866
>>> 
```

Brython:
```python
Brython 3.8.9 on Netscape 5.0 (X11)
>>> from math import cos,radians
>>> theta = 30
>>> print(f'{theta=}  {cos(radians(theta))=:.3f}')
  File <string>, line 1
    print(f'{theta=}  {cos(radians(theta))=:.3f}')
           ^
SyntaxError: SyntaxError: unmatched ) in regular expression
>>>
```

Love the project! I'm awful at regular expressions, so I can't help myself other than reporting the problem, in this case.

**Comment by PierreQuentel** [comment]
Thanks @Ulugbeg !
