### ISSUE TITLE
importlib not working under Brython 3.8.9

### ISSUE THREAD

**Issue by moepnse** [brython-dev/brython#1428]
### Plugin-System

With the help of `importlib` I try to implement a plugin system.
It works under Python 3.8, but not under Brython 3.8.9. 

### Sample Code for Python 3 and Brython

[brython_importlib_demo.zip](https://github.com/brython-dev/brython/files/4804668/brython_importlib_demo.zip)

### Python3 - works
```
$ python3 importlib_demo.py 
plugin_plugin1 loaded
```

### Brython 3.8.9

Steps to reproduce:

1. Start Webserver

```
$ python3 ws.py
======== Running on http://127.0.0.1:8085 ========
(Press CTRL+C to quit)
```

2. Goto http://localhost:8085/plugin_demo.html

3. Open Developer-Console

```
using indexedDB for stdlib modules cache brython.js:5316:36
handle error 
Object { __class__: {…}, __mro__: (3) […], "$is_class": true, "$infos": {…}, "$factory": $factory()
, __module__: "builtins" }
 
Array [ "'NoneType' object has no attribute 'loader'" ]
brython.js:5380:9
Traceback (most recent call last):
  File http://localhost:8085/plugin_demo.html/__main__ line 20, in <module>
    load_plugin("plugins/plugin1.py")
  File http://localhost:8085/plugin_demo.html/__main__ line 16, in load_plugin
    spec.loader.exec_module(module)
AttributeError: 'NoneType' object has no attribute 'loader' brython.js:6254:9
Error: brython.js line 7929 > eval:41:354
```

**Comment by moepnse** [comment]
>>> type(importlib.util.spec_from_file_location("io", 'https://brython.info/src/Lib/io.py'))
<class 'NoneType'>
>>> type(sys.meta_path[1].find_spec("io", 'https://brython.info/src/Lib/io.py'))
<class 'module'>

https://github.com/brython-dev/brython/blob/master/www/src/Lib/importlib/_bootstrap_external.py#L669

>>> type(importlib._bootstrap_external._get_supported_file_loaders())
<class 'NoneType'>

https://github.com/brython-dev/brython/blob/master/www/src/Lib/importlib/_bootstrap_external.py#L1560

**Comment by PierreQuentel** [comment]
Thanks for the report :-)
