### ISSUE TITLE
Performance for list slice

### ISSUE THREAD

**Issue by s-cork** [brython-dev/brython#1429]
I've been in awe of some of the speed benchmarks tests from brython

here's one that's not so hot and would be worth improving

```python
a = [1,2,3]
for i in range(100000):
    a[:]
```

on the brython console runs at a full 10 seconds. 
compared to Cpythons 0.03 seconds

**Comment by redradist** [comment]
Take a look at this pull-request https://github.com/brython-dev/brython/pull/1430

Also read discussions https://github.com/brython-dev/brython/issues/1419

**Comment by s-cork** [comment]
When I profiled the code the log jam is not on list.__getitem__ but in $B.$getItem which does a check for $getInt which is slow as it walks up the MRO to check if there’s an __int__ or an __index__ method before then reaching out to list.__getitem__

**Comment by redradist** [comment]
@s-cork 
> 
> When I profiled the code the log jam is not on `list.__getitem__` but in `$B.$getItem` which does a check for `$getInt` Inside a try catch which is slow as it walks up the MRO to check if there’s an `__int__` or an `__index__` method before then reaching out to `list.__getitem__`

There are another pull-request that improve performance of `$B.$getattr` that could improve performance for you case

**Comment by PierreQuentel** [comment]
I have marked the issue as fixed because the time to run this code is divided by more than 100, but speed improvement is a neverending task...
