### ISSUE TITLE
Ideas for improving performance of function calls

### ISSUE THREAD

**Issue by schmave** [brython-dev/brython#1431]
I saw that simple function calls in Brython take around 5x the time of CPython, so I looked into it a bit to see if there were some quick ways to speed it up. I found a few things that together led to a 10x speedup. I'm not sure if two of them are safe, so I'm just listing them here instead of making a PR.

1) Add `if(frame[1].$has_yield_in_cm){` test around the call to `exit_ctx_managers_in_generators` in `$B.leave_frame_exec`. This saves a ton of time (when you are running inside of an `exec`), and is analogous to the code in `$B.leave_frame`. Hopefully it is possible to do this, but I don't know for sure.

2) Every function body contains this line `$locals.__annotations__ = _b_.dict.$factory()`, but I don't think it is possible to annotate local variables inside the function, so it is never used. Can it be removed?

3) In `$B.leave_frame`, remove the call to `$B.del_exc` and add `frame[1].$current_exception = undefined` after `var frame = $B.frames_stack.pop()`. 

4) In `$B.enter_frame`, return `null` everywhere you currently use `_b_.None`, and change the autogenerated trace code from `if($locals.$f_trace !== _b_.None){$B.trace_line()}` to `if($locals.$f_trace){$B.trace_line()}`. This didn't make nearly as large a difference as the first three, but it's a simple change that also reduces the size of the generated code, so it still seems worth doing. 

Thanks for taking a look at these!

**Comment by redradist** [comment]
>     4. In `$B.enter_frame`, return `null` everywhere you currently use `_b_.None`, and change the autogenerated trace code from `if($locals.$f_trace !== _b_.None){$B.trace_line()}` to `if($locals.$f_trace){$B.trace_line()}`. This didn't make nearly as large a difference as the first three, but it's a simple change that also reduces the size of the generated code, so it still seems worth doing.
> 
> 
> Thanks for taking a look at these!

As I also mentioned in https://github.com/brython-dev/brython/issues/1419 I would be better to completely remove `if($locals.$f_trace !== _b_.None){$B.trace_line()}` in release `brython(0)` and also `$locals.$line_info`, after I have hardcodely  removed this line in compiler my `list` example starts worikng 2x faster !!

**Comment by schmave** [comment]
`$locals.$line_info` is needed to generate proper exception messages, and `$B.trace_line()` is needed to support `sys.settrace`. Since both of those are available in CPython, I think it makes sense to have them always available in Brython too, not just when debugging mode is enabled.

**Comment by PierreQuentel** [comment]
I just pushed a commit with a branch "function_call_speed" that implements all these suggestions (there are probably a few minor regressions, for instance removing `$locals.__annotations__` makes the name `__annotation__` unavailable inside functions, though it is present in CPython functions). 

Unfortunately I don't see such improvement in function call speed. Can you test ?

**Comment by schmave** [comment]
Looks good to me! When I run the benchmark named "function call" using http://localhost:8000/speed on the master branch, it takes 1900-2000ms for 1,000,000 calls to f(). When I run it on the function_call_speed branch, it takes 150ms. I disabled caching in my browser and cleared local storage and indexed DB between runs. 

In CPython, I see that `__annotations__` inside a function seems to refer to the module level `__annotations__`, and I think this will continue to work in Brython:

```python
x: int = 5
print(__annotations__)
def f():
  print('in f', __annotations__)

f()

def g():
   y: int = 7
   print('in g', __annotations__)
 
g()
```

CPython 3.8.0 output:
```
{'x': <class 'int'>}
in f {'x': <class 'int'>}
in g {'x': <class 'int'>}
```

**Comment by redradist** [comment]
> 
> 
>     2. Every function body contains this line `$locals.__annotations__ = _b_.dict.$factory()`, but I don't think it is possible to annotate local variables inside the function, so it is never used. Can it be removed?

What do you mean here ?

I can easily write code like this:
```python
def some_function():
    k: int
```

And it useful with `mypy`

**Comment by schmave** [comment]
You can specify annotations on local variables, but I believe that they are not available at runtime (from [PEP 526](https://www.python.org/dev/peps/pep-0526/#runtime-effects-of-type-annotations)):

> Store variable annotations also in function scope: The value of having the annotations available locally is just not enough to significantly offset the cost of creating and populating the dictionary on each function call.

**Comment by PierreQuentel** [comment]
I ran the tests with the new branch compared to the current implementation on Firefox 77.0.1, Windows 10. I ran the test twice for each version and report the mean time for each test.

```
                                              func   current
------------------------------------------------------------
simple assignment                            |  16.0|  12.0
augmented assignment                         |  11.0|  21.0
augmented assignment and list append         | 340.0| 391.0
simple assignment to float                   | 113.0| 106.5
big integers                                 |6234.5|3372.0
build dictionary                             | 332.5| 492.0
build dictionary 2                           | 118.0|  95.5
set dictionary item                          |  83.0|  85.0
build set                                    | 693.5| 608.0
build list                                   |  59.5|  50.0
set list item                                |  51.5|  56.0
list slice                                   | 568.0| 552.5
integer addition                             | 127.0| 128.5
string addition                              | 126.5| 114.0
cast int to string                           | 109.5| 102.5
create function without arguments            | 431.0| 432.0
create function, single positional argument  | 419.0| 447.0
create function, complex arguments           | 606.5| 625.5
function call                                | 271.5| 635.0
function call, complex arguments             | 564.5|1113.0
create simple class                          | 588.5| 523.0
create class with init                       | 627.0| 557.0
create instance of simple class              | 255.5| 218.0
create instance of class with init           | 708.5| 941.5
call instance method                         | 574.0|1324.5
-----------------------------------------------------------
mean                                         |561.18|520.12

without big integers

mean                                         |324.79|401.29
```

Function call is actually faster, but not as much as in your tests ; which browser / OS do you use ?

Other tests are slower with the changed version (no idea why at this stage), but without the "big integers" test which is not such a big deal, the improvement is around 20%.

I would be interested if you could run the same tests on your machine. I have often observed that speed results are not always stable between runs.

**Comment by schmave** [comment]
Interesting! I'm running Chrome 83 on Mac OS 10.15. Looks like there's quite a big difference between Firefox and Chrome on my machine, too. I also found that the time it takes to run the CPython example differs quite a lot between runs, and is faster when I run the timing harness in Firefox instead of Chrome, so I modified speed.py so that it reports the CPython and Brython results independently (instead of only reporting the ratio). 

Here are my timings on the master branch and function_call_speed branch:

https://docs.google.com/spreadsheets/d/1erdFGccunHFzPpnmJZjwu1GzIIpLrP7h6Zz1whTKcFQ/edit?usp=sharing

**Comment by PierreQuentel** [comment]
The commits referenced above implement all the proposed changes but the last, in a slightly different way for 2 of them:

- the code in `leave_frame()` simulates what happens when a generator with `yield` statements inside context managers is garbage collected in CPython : the context manager must be closed, which, in Brython's implementation, requires to apply method `return()` of the matching Javascript generator. The first commit sets an attribute `$close_generators` to the current `$locals`, a list of the generators running in the current frame that have these yields inside context managers; this is done in function `$B.$call()` in __`py_utils.js`__, when such generators are initialized by calling the generator function. In `leave_frame()`, if this attribute is set, method `return()` is applied to all the generators in the list

- instead of removing `$locals.__annotations__`, all the calls `_b_.dict.$factory()` are replaced by `$B.empty_dict()` which avoids the overhead of parsing arguments in `dict.__init__`

In my tests, this greatly improves the speed of function calls. Is is also the case in your environment ?

**Comment by PierreQuentel** [comment]
With the latest changes, here are the current speed test results compared to version 3.8.9

```
                                            current  3.8.9

simple assignment                               22     77
augmented assignment                            44     79
augmented assignment and list append           381
simple assignment to float                     113    182
big integers                                   769   6829
build dictionary                               340    359
build dictionary 2                             185    232
set dictionary item                            115    153
build set                                      600    643
build list                                      62    101
set list item                                   64    124
list slice                                     709
integer addition                                99    164
string addition                                126    141
cast int to string                             169    164
create function without arguments              297    524
create function, single positional argument    304    498
create function, complex arguments             405    701
function call                                  292    770
function call, complex arguments               820   1264
create simple class                            447    516
create class with init                         534    605
create instance of simple class                 86    262
create instance of class with init             612   1257
call instance method                           642   2475
---------------------------------------------------------
mean                                           329    788
```

Results are still very unstable between runs, but it seems that there is a significant improvement.

Can we close the issue ?

**Comment by schmave** [comment]
Thanks, Pierre! Sorry, I haven't had a chance to review this this week but I agree the issue is resolved. It's good to know about empty_dict(), though it looks like you ended up agreeing that $locals.__annotations__ was unnecessary. Thanks for your work on this. I'm excited to merge it into my application and see what the speedup is.
