### ISSUE TITLE
imports do not work in script inside html and from browser does not work in external files

### ISSUE THREAD

**Issue by DimaBryuhanov** [brython-dev/brython#1432]
I was trying to move your example calculator code to an external .py file, but 'from browser' did not work, since there's no such library. I installed 'pip install brython', which did not help.

Then I tried importing a different python class inside the html python script, however, it did not work either. The other file lies in the same root directory where the requesting code is. What can be wrong?

`
<body onload="brython()">
    <script type="text/python">
from calculator import * # this causes a ModuleNotFoundError: calculator
from browser import document, html
    </script>
</body>
`

**Comment by PierreQuentel** [comment]
It's hard to tell without the complete HTML page, but here is a working example, assuming that __`calculator.py`__ is in the same directory as the page (if necessary, change the path to __`brython.js`__):

```xml
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<script type="text/javascript" src="/src/brython.js"></script>

<style>
*{
    font-family: sans-serif;
    font-weight: normal;
    font-size: 1.1em;
}
td{
    background-color: #ccc;
    padding: 10px 30px 10px 30px;
    border-radius: 0.2em;
    text-align: center;
    cursor: default;
}
#result{
    border-color: #000;
    border-width: 1px;
    border-style: solid;
    padding: 10px 30px 10px 30px;
    text-align: right;
}
</style>
</head>

<body onload="brython()">

<script type="text/python">
from calculator import *
</script>

</body>
</html>
```

**Comment by DimaBryuhanov** [comment]
In my case it looks somewhat like this:
`<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <script type="text/javascript" src="Brython-3.8.9/brython.js"></script>
    <script type="text/javascript" src="Brython-3.8.9/brython_stdlib.js"></script>
    <style>
        *{
            font-family: sans-serif;
            font-weight: normal;
            font-size: 1.1em;
        }
        td{
            background-color: #000;
            color: blanchedalmond;
            padding: 10px 30px 10px 30px;
            border-radius: 0.2em;
            text-align: center;
            cursor: default;
        }
        #result{
            border-color: #000;
            border-width: 1px;
            border-style: solid;
            padding: 10px 30px 10px 30px;
            text-align: right;
            font-family: digital-7;
            color: chartreuse;
            background-color: black;
            font-size: 2em;
        }
        </style>
</head>

<body onload="brython()">
    <script type="text/python">
from browser import document, html

calc = html.TABLE()
calc <= html.TR(html.TH(html.DIV("0", id="result"), colspan=4))
lines = ["789+", "456-", "123*", "C0=/"]
calc <= (html.TR(html.TD(x) for x in line) for line in lines)
document <= calc

result = document["result"] # direct acces to an element by its id

def action(event):

    element = event.target
    value = element.text
    if value not in "=C":
        if result.text in ["0", "error"]:
            result.text = value
        else:
            result.text = result.text + value
    elif value == "C":
        result.text = "0"
    elif value == "=":
        try:
            result.text = eval(result.text)
        except:
            result.text = "ERROR"

for button in document.select("td"):
    button.bind("click", action)
    </script>
</body>
</html>`

The calculator file is located in the same root folder, where this .html file sits. However, the file is invisible to the brython code. What could be the reason and what could be done?

**Comment by PierreQuentel** [comment]
The reason is that you don't have the basic markup of an HTML page, with the tags `<html>`, `<head>`, and the specific version of the `<body>` tag for Brython. 

Here is a corrected and working version:
```xml
<!doctype html>

<html>

<head>
<script type="text/javascript" src="/src/brython.js"></script>
<script type="text/javascript" src="/src/brython_stdlib.js"></script>
<style>
* {
  font-family: sans-serif; font-weight: normal; font-size: 1.1em;
}
td{
  background-color: #000;
  color: blanchedalmond;
  padding: 10px 30px 10px 30px;
  border-radius: 0.2em;
  text-align: center;
  cursor: default;
}
#result{
  border-color: #000;
  border-width: 1px;
  border-style: solid;
  padding: 10px 30px 10px 30px;
  text-align: right;
  font-family: digital-7;
  color: chartreuse;
  background-color: black;
  font-size: 2em;
}
</style>
</head>

<body onload="brython()">

<script type="text/python">
from browser import document, html

calc = html.TABLE()
calc <= html.TR(html.TH(html.DIV("0", id="result"), colspan=4))
lines = ["789+", "456-", "123*", "C0=/"]
calc <= (html.TR(html.TD(x) for x in line) for line in lines)
document <= calc

result = document["result"] # direct acces to an element by its id

def action(event):
  element = event.target
  value = element.text
  if value not in "=C":
      if result.text in ["0", "error"]:
          result.text = value
      else:
          result.text = result.text + value
  elif value == "C":
      result.text = "0"
  elif value == "=":
      try:
          result.text = eval(result.text)
      except:
          result.text = "ERROR"

for button in document.select("td"):
  button.bind("click", action)
</script>

</body>
</html>
```

**Comment by DimaBryuhanov** [comment]
Dear Pierre, I had exactly the same HTML code like you showed above, except GitHub removed all the HTML tags from my question, probably for security reasons. Thus, the problem was not in the HTML layout, since the web page works fine up to the moment, when I add the line where I'm trying to import a class form a file located in the same root directory with the HTML file.

`from browser import document, html

from calculator import calculator # this line causes the errors below:`

Error: brython.js line 7929 > eval:1:211
    $factory file:///media/root/Seagate Backup Plus Drive/Documents/Python/t-kinter/Brython-3.8.9/brython.js line 7929 > eval:1
    import_hooks file:///media/root/Seagate Backup Plus Drive/Documents/Python/t-kinter/Brython-3.8.9/brython.js:14176
    $__import__ file:///media/root/Seagate Backup Plus Drive/Documents/Python/t-kinter/Brython-3.8.9/brython.js:9475
    $import file:///media/root/Seagate Backup Plus Drive/Documents/Python/t-kinter/Brython-3.8.9/brython.js:9519
    anonymous file:///media/root/Seagate Backup Plus Drive/Documents/Python/t-kinter/Brython-3.8.9/brython.js line 5368 > Function:19
    loop file:///media/root/Seagate Backup Plus Drive/Documents/Python/t-kinter/Brython-3.8.9/brython.js:5368
    inImported file:///media/root/Seagate Backup Plus Drive/Documents/Python/t-kinter/Brython-3.8.9/brython.js:5352
    loop file:///media/root/Seagate Backup Plus Drive/Documents/Python/t-kinter/Brython-3.8.9/brython.js:5376
    inImported file:///media/root/Seagate Backup Plus Drive/Documents/Python/t-kinter/Brython-3.8.9/brython.js:5352
    loop file:///media/root/Seagate Backup Plus Drive/Documents/Python/t-kinter/Brython-3.8.9/brython.js:5376
    <anonymous> file:///media/root/Seagate Backup Plus Drive/Documents/Python/t-kinter/Brython-3.8.9/brython.js:5327

**Comment by PierreQuentel** [comment]
It seems that you are loading the page with the File/Open menu, not by running a local web server. Please read [this documentation page](https://www.brython.info/static_doc/en/file_or_http.html).

**Comment by PierreQuentel** [comment]
To avoid the formatting problem in this issue tracker, you should use the [markdown syntax](https://guides.github.com/features/mastering-markdown/) for code, here put the code between lines starting with ```

**Comment by DimaBryuhanov** [comment]
> It seems that you are loading the page with the File/Open menu, not by running a local web server. Please read [this documentation page](https://www.brython.info/static_doc/en/file_or_http.html).

You are right. I was openning my html file directly in the browser. I'll try with an http server. Hope, it helps! Thanks for your time and patience!

**Comment by PierreQuentel** [comment]
I close the issue, assuming that the script runs when loaded from a web server. If it's not the case don't hesitate to reopen it.
