### ISSUE TITLE
[Issue] Inheritance from JavaScript object disabled adding new methods to class

### ISSUE THREAD

**Issue by redradist** [brython-dev/brython#1439]
Hi, I try to make adaptation for `React` for `Brython` (second attempt)

Test html:
```html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <script src="brython.js"></script>
        <script src="brython_modules.js"></script>
        <script src="https://unpkg.com/react@16/umd/react.development.js" crossorigin></script>
        <script src="https://unpkg.com/react-dom@16/umd/react-dom.development.js" crossorigin></script>
    </head>

    <body onload="brython(1)">
        <script type="text/python" src="lib.py" precompiled></script>
        <div id="root"></div>
    </body>
</html>
```

I try to inherit from JS object something like thi
```python
class Hello(window.React.Component):
    def __init__(self):
        super().__init__(self)

    def render(self):
        return window.React.createElement('div', None, f"Hello {self.props.toWhat}")


react_obj = Hello()
print(f'react_obj is {dir(react_obj)}')
react_obj.render()
```

But got the error that there is no such method like `render` ... but inherited properties are available

When I remove inheritance from `JavaScript` object method `render` appears on instance of class

**Comment by redradist** [comment]
@PierreQuentel This issue relates to https://github.com/brython-dev/brython/issues/1418 ... seems like it was not fully fixed

**Comment by redradist** [comment]
@PierreQuentel Have you seen the issue ?
I can help with it, but actually for me it if harder to find the part of code where I should start ...

Seems like `py_type.js` `type.__getattribute__` is appropriate place ?

**Comment by PierreQuentel** [comment]
@redradist 
Yes, I have seen the issue; in fact the big change in the interface with Javascript objects a few days ago was directly related to it. But despite a number of attempts, I still haven't found a way to implement the Python equivalent of the `class A extends B` statement in Javascript.

I have been busy on other issues lately but I don't forget this one :-)

**Comment by PierreQuentel** [comment]
@redradist 
The series of commits above introduce 2 new functions in the __`javascript`__ module : 
- `javascript.extends(js_class)` : a decorator meant to be decorate a Python class to transform it into a Javascript class that extends the one passed as `js_class`
- `javascript.super()` : meant to be used in the `__init__` method of the subclass. The return value has a single attribute, `__init__`, that initialized the parent class

Your example works when written with these functions: 
```python
from browser import window, console, document
import javascript

React = window.React

@javascript.extends(React.Component)
class Hello:

    def __init__(self, props, children):
        javascript.super().__init__(props, children)
        self.state = {"liked": False}

    def render(self):
        if self.state["liked"]:
            return 'You liked this.'
        return React.createElement("button",
            { "onClick": lambda ev: self.setState({ "liked": True }) },
            'Like'
        )

domContainer = document['like_button_container']
window.ReactDOM.render(React.createElement(Hello), domContainer)
```

For the moment, I prefer to define a specific syntax for this case, instead of using standard Python inheritance (`class Hello(React.Component)`) and the standard built-in `super()`. I'm not sure of all the implications of using the standard Python mechanism for this situation.

**Comment by PierreQuentel** [comment]
I am closing the issue, hoping that the result is ok. If not, feel free to reopen it.
Thanks @redradist !

**Comment by redradist** [comment]
> 
> 
> @redradist
> The series of commits above introduce 2 new functions in the **`javascript`** module :
> 
>     * `javascript.extends(js_class)` : a decorator meant to be decorate a Python class to transform it into a Javascript class that extends the one passed as `js_class`
> 
>     * `javascript.super()` : meant to be used in the `__init__` method of the subclass. The return value has a single attribute, `__init__`, that initializes the parent class
> 
> 
> Your example works when written with these functions:
> 
> ```python
> from browser import window, console, document
> import javascript
> 
> React = window.React
> 
> @javascript.extends(React.Component)
> class Hello:
> 
>     def __init__(self, props, children):
>         javascript.super().__init__(props, children)
>         self.state = {"liked": False}
> 
>     def render(self):
>         if self.state["liked"]:
>             return 'You liked this.'
>         return React.createElement("button",
>             { "onClick": lambda ev: self.setState({ "liked": True }) },
>             'Like'
>         )
> 
> domContainer = document['like_button_container']
> window.ReactDOM.render(React.createElement(Hello), domContainer)
> ```
> 
> For the moment, I prefer to define a specific syntax for this case, instead of using standard Python inheritance (`class Hello(React.Component)`) and the standard built-in `super()`. I'm not sure of all the implications of using the standard Python mechanism for this situation.

@PierreQuentel Hi Pierre, as for me the best way to help new users to use this feature is to make this inheritance as in standard Python, because user can import JavaScript object from another Python file and try to inherit from it and will get still an error ... also it is not obvious that BRython is not support standard python inheritance (even from JavaScript object) and I expect that user will create an issue here and only then will find this decorator and super method in documentation ...

Do you consider to switch this mehanism to standard Python inheritance ?

**Comment by PierreQuentel** [comment]
In Python, a class inherits a Python class, either built-in such as `dict` or user-defined.

Adding the possibility to inherit from something else (here, an object that wraps a Javascript "class") would _not_ be standard Python, so no, Brython is not going to support this feature; using a decorator makes it explicit that something else than standard class inheritance happens.

**Comment by redradist** [comment]
> 
> 
> In Python, a class inherits a Python class, either built-in such as `dict` or user-defined.
> 
> Adding the possibility to inherit from something else (here, an object that wraps a Javascript "class") would _not_ be standard Python, so no, Brython is not going to support this feature; using a decorator makes it explicit that something else than standard class inheritance happens.

@PierreQuentel I cannot agree with this, because when you extend some runtime (Kotlin for Java, TypeScript for JavaScript, BRython base on JavaScript) one of the fundamental parts of success is compatability with predecessor

... otherwise you should not even allow developer to import window properties because it is JavaScript object and variable do not contain truly Python object

**Comment by PierreQuentel** [comment]
If `x` is a Javascript object, the object referenced by `window.x` in Brython code is a Python object, with a class, attribute resolution etc. 

But if `x` is a Javascript class (built with the JS keyword `class`), it is *not* a Python class, ie an object whose class is a Python metaclass. I tried hard to make it this kind of object, but finally gave up, for reasons that I don't remember now, but believe me I spent hours on this issue. Please don't insist on this point.

**Comment by redradist** [comment]
@PierreQuentel  What I am thinking now it that what is MRO in the following case:
```python
from browser import window, console, document
import javascript

React = window.React

class Base:
    def render(self):
        pass

@javascript.extends(React.Component)
class Hello(Base):

    def __init__(self, props, children):
        javascript.super().__init__(props, children)
        self.state = {"liked": False}

    def render(self):
        if self.state["liked"]:
            return 'You liked this.'
        return React.createElement("button",
            { "onClick": lambda ev: self.setState({ "liked": True }) },
            'Like'
        )

domContainer = document['like_button_container']
window.ReactDOM.render(React.createElement(Hello), domContainer)
```
Maybe the better approach would be the following:
```python
from browser import window, console, document
import javascript

React = window.React

class Base:
    def render(self):
        pass

class Hello(Base, javascript.base(React.Component)):

    def __init__(self, props, children):
        javascript.super().__init__(props, children)
        self.state = {"liked": False}

    def render(self):
        if self.state["liked"]:
            return 'You liked this.'
        return React.createElement("button",
            { "onClick": lambda ev: self.setState({ "liked": True }) },
            'Like'
        )

domContainer = document['like_button_container']
window.ReactDOM.render(React.createElement(Hello), domContainer)
```
