### ISSUE TITLE
A simple comprehension fails to evaluate

### ISSUE THREAD

**Issue by sgala** [brython-dev/brython#1440]
>>> len(list(chr(i) for i in range(sys.maxunicode) if 'L' in unicodedata.category(chr(i)) ))
Traceback (most recent call last):
  File <string>, line 1, in <module>
NameError: <Javascript ReferenceError>: cps is not defined

in python produces:

>>> len(list(chr(i) for i in range(sys.maxunicode) if 'L' in unicodedata.category(chr(i)) ))
116766

**Comment by sgala** [comment]
To simplify more:

```
import unicodedata
>>> ''.join('' for i in range(888) if 'N' in unicodedata.category(chr(i)))
''
>>> ''.join('' for i in range(889) if 'N' in unicodedata.category(chr(i)))
Traceback (most recent call last):
  File <string>, line 1, in <module>
NameError: <Javascript ReferenceError>: cps is not defined
```

**Comment by PierreQuentel** [comment]
Thanks for reporting this bug. The category of unassigned Unicode code points was not correctly set to "Cn".
