### ISSUE TITLE
Execution vs eval

### ISSUE THREAD

**Issue by JamesHutchison** [brython-dev/brython#145]
Currently Brython builds a javascript string from imports and then evals it. It could potentially speed up execution time significantly if javascript was executed directly from python code without having to eval a string. I'm wondering if this approach has been considered before and if there are any issues that would prevent this?

**Comment by glyph** [comment]
Is this more or less the same thing I'm asking for on #123 ?

**Comment by JamesHutchison** [comment]
Not quite, it would be like that except instead of creating javascript then executing it, you just execute directly. This would only applicable to python files instead of pre-compiled javascript.

**Comment by glyph** [comment]
OK, in that case I don't follow :).  How do you have any JavaScript to execute if you didn't create it somehow?

**Comment by PierreQuentel** [comment]
I don't understand either. Can you explain more ?
