### ISSUE TITLE
Some Lib/test/test_dict tests are failing

### ISSUE THREAD

**Issue by schmave** [brython-dev/brython#1450]
On the latest master, the following tests are failing: 

* DictTest.test_copy_fuzz
* DictTest.test_dictview_set_operations_on_items
* DictTest.test_errors_in_view_containment_check
* DictTest.test_getitem
* DictTest.test_pop
* DictTest.test_setdefault

Looks like many of the failures probably have the same root cause.

**Comment by schmave** [comment]
Here's a link to a Travis build that shows the failures: 

https://travis-ci.org/github/brython-dev/brython/jobs/708699929

**Comment by PierreQuentel** [comment]
Thanks Evan !
Most of the bugs were related to the implementation of dict, except the last one which happened in all the tests where method `subTest()` of `unittest.TestCase` is called. There was a regression due to the change in the implementation of generators.
