### ISSUE TITLE
unable to move html element with the mouse

### ISSUE THREAD

**Issue by laurentHYZ** [brython-dev/brython#1451]
Hello!
I am trying out  Brython and right now I am **facing a problem when trying to move an html element with the mouse.**
`
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script type="text/javascript"
    src="https://cdn.jsdelivr.net/npm/brython@3.8.9/brython.min.js">
</script>
<script type="text/javascript"
src="https://cdn.jsdelivr.net/npm/brython@3.8.9/brython_stdlib.js">
</script>
  
   
    <title>Brython Demo</title>
</head>
<body onload="brython()">

    <button id="joke-btn">Get Joke</button>
    <div id="joke" class="card">Click the "get joke" button</div>

    
    <script type="text/python" id="script3">
        from browser import document, ajax

        url = 'https://api.chucknorris.io/jokes/random'

        def on_complete(req):
            import json
            data = json.loads(req.responseText)
            joke = data['value']
            document['joke'].text = joke

        def get_joke(e):
            req = ajax.ajax()
            req.open('GET', url, True)
            req.bind('complete', on_complete)
            document['joke'].text = 'Loading...'
            req.send()

        document['joke-btn'].bind('click', get_joke)
    </script>

    <div class="example" id="ex_mousemove" style="display: block;">

        <b id="moving" style="top: 10px; left: 140px; cursor: move;">drag me
        </b>
    
        <script type="text/python" id="script_mousemove">
        from browser import document
    
        class ElementMove:
    
            def __init__(self, moving):
                """Make "moving" element movable with the mouse"""
                self.moving = moving
                self.is_moving = False
                self.moving.bind("mousedown", self.start)
                self.moving.bind("mouseup", self.stop)
                moving.style.cursor = "move"
    
            def start(self, event):
                """When user clicks on the moving element, set boolean is_moving
                to True and store mouse and moving element positions"""
                self.is_moving = True
                self.mouse_pos = [event.x, event.y]
                self.elt_pos = [self.moving.left, self.moving.top]
                document.bind("mousemove", self.move)
                # prevent default behaviour to avoid selecting the moving element
                event.preventDefault()
    
            def move(self, event):
                """User moves the mouse"""
                if not self.is_moving:
                    return
    
                # set new moving element coordinates
                self.moving.left = self.elt_pos[0] + event.x - self.mouse_pos[0]
                self.moving.top = self.elt_pos[1] + event.y - self.mouse_pos[1]
    
            def stop(self, event):
                """When user releases the mouse button, stop moving the element"""
                self.is_moving = False
                document.unbind("mousemove")
    
        ElementMove(document["moving"])
        </script>
    </p></div>
</body>
</html>
`

**Comment by PierreQuentel** [comment]
This is because the style attribute `position` of the dragged element must be set to "absolute". You can either add "position: absolute" in the `<b>` tag, or add this line at the end of  `__init__()`:

```python
        moving.style.position = "absolute"
```

**Comment by laurentHYZ** [comment]
Thank you very much, it is working now!  :pray:
