### ISSUE TITLE
JavaScript error when using exec in code in a package

### ISSUE THREAD

**Issue by BrenBarn** [brython-dev/brython#1454]
I encountered a strange bug where I had a package containing some Brython code that uses `exec`.  I would get the JavaScript error "Arg string terminates parameters early".

I believe I have tracked down the source of the error.  In [py_builtin_function.js](https://github.com/brython-dev/brython/blob/2c35ec5fb2d8cd6bcde025955ec02d5ec611297d/www/src/py_builtin_functions.js#L508) there is some code that maps Python-style module names to JS identifers to store information about the local and global namespaces.  It does this by replacing periods with underscores:

        var current_locals_id = current_frame[0].replace(/\./, '_'),
            current_globals_id = current_frame[2].replace(/\./, '_')

I believe it needs to be changed to this:

        var current_locals_id = current_frame[0].replace(/\./g, '_'),
            current_globals_id = current_frame[2].replace(/\./g, '_')

Note the `g` RegExp flag.  The current implementation does not correctly replace all periods in nested module names (e.g., `package.subpackage.module`), but only the first one.  This leads to errors when using `exec` because the relevant code winds up trying to create a JavaScript function with an argument called something like `$locals_package_subpackage.module`, which is not a valid JS identifier.

Probably this bug was not noticed before because both nested packages and use of exec are relatively rare in Brython code, and it looks like this bug will only surface when `exec` (or maybe `eval` too) is used from within a module in a subpackage of an outer package.

**Comment by PierreQuentel** [comment]
Many thanks @BrenBarn !
