### ISSUE TITLE
how to import python spacy library in brython ? 

### ISSUE THREAD

**Issue by akshayrajeev1503** [brython-dev/brython#1455]
I want to import spacy library into brython. So that while loading the page spacy is loaded and does not make anymore http requests. Should i use a webserver and try accessing a spacy folder or is there any other method ?
Please do help !!!!

**Comment by PierreQuentel** [comment]
Generally speaking, to [install a CPython module](https://brython.info/static_doc/en/install.html) you can use the command `brython-cli --add_package <package_name>`.

Keep in mind that Brython can only handle programs written in Python, not those in C. The __`spacy`__ package requires __`numpy`__, which itself uses modules written in C, so unfortunately you can't import this library in Brython.
