### ISSUE TITLE
Code highlight inconsistent

### ISSUE THREAD

**Issue by gellnerm** [brython-dev/brython#1459]
The highlighting in the example https://brython.info/gallery/barcode.html gets inconsistent at the bottom.

**Comment by ShubhamKJha** [comment]
It is happening because the [hightlight.py](https://github.com/brython-dev/brython/blob/b97ec7ec112f36da17f5936ad012f261de17daec/www/src/Lib/browser/highlight.py#L76-L98) file doesn't account for multi-line strings. I would be quickly sending a fix (my first to this project).

**Comment by ShubhamKJha** [comment]
@PierreQuentel how to install brython from sources?

**Comment by PierreQuentel** [comment]
You just have to clone the repository and start the built-in server (__`server.py`__), then load pages from _localhost:8000_, like _http://localhost:8000/gallery/barcode.html_

**Comment by PierreQuentel** [comment]
Thanks for @gellnerm for the report and to @ShubhamKJha for the fix :-)
