### ISSUE TITLE
time.strptime is slow

### ISSUE THREAD

**Issue by kikocorreoso** [brython-dev/brython#146]
The following simple code:

``` python
import time

print(time.strptime("2010 11 12", "%Y %m %d"))
```

Takes more than 2.5 s (FF) or almost 2s (Chromium) on an intel i7 CPU. Most of the overhead is due to the `re` module import. Once imported the module, the previous code takes more than 0.1s.

I think the functionality of `strptime` could be accelerated avoiding the use of the `re` module.

Someone has any consideration/recommendation/advise/problem/whatever if `strptime` is coded this way?

**Comment by earney** [comment]
It looks like most of the re stuff is in the class TimeRE.   We could investigate trying to use _jsre and see if this works correctly.
