### ISSUE TITLE
uuid4 does not produce terribly random UUIDs

### ISSUE THREAD

**Issue by glyph** [brython-dev/brython#1462]
on https://brython.info/tests/console.html?lang=en :

```
Brython 3.8.9 on Netscape 5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Safari/605.1.15
>>> import uuid
>>> uuid.uuid4()
UUID('00000000-0000-4000-0000-000000000000')
>>> uuid.uuid4()
UUID('00000000-0000-4000-0000-000000000000')
>>> uuid.uuid4()
UUID('00000000-0000-4000-0000-000000000000')
>>> uuid.uuid4()
UUID('00000000-0000-4000-0000-000000000001')
>>> uuid.uuid4()
UUID('00000000-0000-4000-0000-000000000000')
>>> 
```

`os.urandom` seems to work properly (at least, it *looks* random) so the issue seems to be with the `version=` argument?

**Comment by PierreQuentel** [comment]
Thanks @glyph , the results should be slightly more random now ;-)

**Comment by glyph** [comment]
(They're still not random on brython.info, if that was expected to be updated by this commit, but I assume there's a deploy process that hasn't run yet?)

**Comment by PierreQuentel** [comment]
brython.info is only updated at every new release, the development version is not tested as completely as releases.
