### ISSUE TITLE
[Suggestion] Imporve JavaScript code for better maintanance

### ISSUE THREAD

**Issue by redradist** [brython-dev/brython#1463]
Hi @PierreQuentel 

I want to discuss improving old JavaScript code with the following steps:

1. Applying JavaScript code style. Lots of tools could do this automatically, for example WebStorm (I've tested with it on your JavaScript code base)
It will help easily to add some new stuff of to fix old one
2. Convert old style JavaScript to new style JavaScript for example with tool https://github.com/lebab/lebab
You can convert old style var to new style let if it is possible and so on
Also in future it could be possible to convert whole old style JavaScript with prototypes to new one with classes and ES modules that will improve maintains
Also I have tested it on py_utils.js and it works pretty nice ...

All this steps will help you as my opinion and also encourage new developers from both worlds Python and JavaScript (npm guys) help maintain and evolve this nice Python implementation ;)

**Comment by PierreQuentel** [comment]
@redradist 
1. there is already a [Javascript coding style](https://github.com/brython-dev/brython/wiki/Javascript-coding-style-for-Brython-scripts) for Brython, and I'm afraid external tools will report warnings that I don't agree with (eg the obligation to end each line with a semicolon).

2. I am very cautious when including features from the latest versions of Javascript, to make sure that most browsers will support Brython. For instance it's only with the current development version that I introduced the Javascript "yield" keyword for Python generators. 
Another issue with new Javascript constructs is that they sometimes decrease performance : in all the tests I made
. "new style" `f(x, ...args)` is much slower than building a list `allargs` made of `x` and the items in `args` and calling `f.apply(null, allargs)`
. "new style" `for(item of list){...}` is much slower than "old style" `for(var i = 0, len = list.length; i < len; i++){var item = list[i]; ...}`.

**Comment by redradist** [comment]
> 
> 
> @redradist
> 
>     1. there is already a [Javascript coding style](https://github.com/brython-dev/brython/wiki/Javascript-coding-style-for-Brython-scripts) for Brython, and I'm afraid external tools will report warnings that I don't agree with (eg the obligation to end each line with a semicolon).
> 
>     2. I am very cautious when including features from the latest versions of Javascript, to make sure that most browsers will support Brython. For instance it's only with the current development version that I introduced the Javascript "yield" keyword for Python generators.
>        Another issue with new Javascript constructs is that they sometimes decrease performance : in all the tests I made
>        . "new style" `f(x, ...args)` is much slower than building a list `allargs` made of `x` and the items in `args` and calling `f.apply(null, allargs)`
>        . "new style" `for(item of list){...}` is much slower than "old style" `for(var i = 0, len = list.length; i < len; i++){var item = list[i]; ...}`.

@PierreQuentel 1 point is very contraceptive as for me ...
Most of JavaScript code styles recommend using at the end semicolon and so on ... I understand that as for Python developer it is not easy to get used to semicolon at the end, but JavaScript is there different language (not the beautiful one) ... but it will allow developers that used to JavaScript code style to contribute to your code

Also what about JavaScript modules ? It will make more clear to understand what happens in py_utils.js and other modules due to that you should not create custom short-hands like _b_, $B ... It will be easier to read code ...
What do you think about modules ?

**Comment by PierreQuentel** [comment]
I'm not too sure what you mean with "contraceptive" ;-)

In my opinion you give too much importance to things that are only minor details; if developers refuse to contribute to a project for such things, I'd rather they don't.

My personal opinion is that adding a symbol that is useless in 99% of cases only adds visual pollution; the 1% when they are needed only show an inconsistency in the Javascript syntax. And even in this case, you can put the semicolon at the beginning of the next line (every time this line begins with the "(" bracket) instead of a the end of the current line.

I am closing the issue, being sure that we won't convince each other.
