### ISSUE TITLE
repl on the commandline (not in a browser) ?

### ISSUE THREAD

**Issue by stuaxo** [brython-dev/brython#1465]
Is there a way I can use brython as a repl, like I can with python ?

This would  be handy for all the usual stuff you do in a repl, but also it would be very quick to check how `brython` behaves vs the `cpython`.

**Comment by schmave** [comment]
There is a script that lets you use Brython with Node, which might meet some of your needs. 

https://github.com/brython-dev/brython/blob/master/scripts/node_bridge.js

You can run `node node_bridge.js path/to/python.py` and it will evaluate your script. I think that imports from the standard library work, but more complicated imports may not. And it's certainly not a REPL -- but it's a start.

**Comment by stuaxo** [comment]
Thanks, I had a vague memory that *something* existed.

Does brython implement exec, I guess this the main thing needed for a repl (apart from readline)?

**Comment by schmave** [comment]
Yeah, Brython implements exec very well, so you could write the REPL in Python.

**Comment by PierreQuentel** [comment]
I am reviewing old issues, I think that we can close this one. @stuaxo, if you disagree, feel free to reopen it.
