### ISSUE TITLE
javascript.JSON.stringify crashes when None is used as a dict value

### ISSUE THREAD

**Issue by goffi-contrib** [brython-dev/brython#1467]
Hello, the following script is crashing with `Exception: <Javascript TypeError>: cyclic object value` (tested in https://www.brython.info/tests/console.html with Brython `3.8.9`):

```python
from javascript import JSON

JSON.stringify({'test': None})
```

As a workaround, using `window.JSON.stringify` works.

**Comment by PierreQuentel** [comment]
This bug with `javascript.JSON` was fixed in a commit a few days ago.

Using it was an alternative to the pure-Python __`json`__ module, which was very slow for "big" JSON data, but I replaced it recently by a Javascript version which is much faster.

```python
import json

json.dumps({"test": None})
```
gives the expected result : `{"test": null}`
