### ISSUE TITLE
sleep function on time module as a source of problems

### ISSUE THREAD

**Issue by kikocorreoso** [brython-dev/brython#147]
I've implemented `sleep` functionality on the `time` module.

https://github.com/brython-dev/brython/blob/master/src/Lib/time.py#L229

It is coded in a very rude way :smiling_imp: and it blocks the browser.

It could be a source of problems and it should be used only for testing purposes.

I think it should be documented and/or highlighted somewhere. So I have some questions about it:

* Should be removed?
* Should show a warning?
* Should be documented somewhere?
* Other options...

**Comment by PierreQuentel** [comment]
Kiko,

This is a very old issue, but a project I'm working on at the moment made me realize that it's better to raise an exception for this function. Your implementation works for a single call to `time.sleep()` but for code like :
```python
time.sleep(1)
print('one')
time.sleep(2)
print('two')
```

the program hangs for 3 seconds, then prints 'one' and 'two' at the same time. Building an animation with this kind of code is therefore impossible in Brython, and probably in any browser-based implementation. I think it's more useful to raise a `NotImplementedError` and to advice to use functions in module __browser.timer__ instead.
