### ISSUE TITLE
Consistent Module Build

### ISSUE THREAD

**Issue by AstraLuma** [brython-dev/brython#1471]
Currently every time you run `brython-cli --modules` the contents of `brython_modules.js` file is updated (even if there were no actual changes).

This has ripple effects in other tooling: git, rsync, cache-busting post-processing, e-tag generation, and probably others.

Can there be a build mode where the file isn't updated if there's no changes?

**Comment by PierreQuentel** [comment]
@AstraLuma 
Thanks for the suggestion. The commit referenced above doesn't update __`brython_modules.js`__ if no change has been detected in the modules required by the application.

To test this change, you have to uninstall the current CPython brython package, then in directory `setup`, run

```
python setup.py sdist
python setup.py install
```

**Comment by AstraLuma** [comment]
Yup, I can confirm this works. Thank you!
