### ISSUE TITLE
Problems with timing

### ISSUE THREAD

**Issue by kmindspark** [brython-dev/brython#1474]
I needed to use delays in my functions for an app I'm building so I am doing them as such.
I tried this out on the brython website (https://brython.info/tests/editor.html?lang=en) and in my own app. Same issue in either case - in the output, you can see that the third call to my_proceed has an extra 17 ms (this exact number varies run-to-run) added to it. Further investigation reveals that this delay is probably occurring during function invocation. This is bizarre in my opinion. This deviation happens consistently. Any thoughts on why this might be? It seems to be that function invocation is taking time.

```
import time

def my_proceed(duration):
    start = time.time()
    counter = 0
    while time.time() - start < duration:
        counter += 1
        pass
    print("internal time: " + str(time.time() - start))

def main():
    start = time.time()
    my_proceed(4)
    print("actual time: " + str(time.time() - start))
    
    start = time.time()
    my_proceed(2)
    print("actual time: " + str(time.time() - start))
    
    start = time.time()
    my_proceed(4)
    print("actual time: " + str(time.time() - start))
    
    start = time.time()
    my_proceed(2)
    print("actual time: " + str(time.time() - start))
    
main()
```

![image](https://user-images.githubusercontent.com/7551261/91117025-86adf980-e642-11ea-96c9-b0633ad1766e.png)

**Comment by PierreQuentel** [comment]
Brython might add some overhead, but the translation of the script to Javascript
```javascript
function my_proceed(duration){
    var start = Date.now()/1000,
        counter = 0
    while((Date.now()/1000 - start) < duration){
        counter += 1
    }
    console.log("internal time:", Date.now()/1000 - start)
}

function main(){
    var start

    start = Date.now()/1000
    my_proceed(4)
    console.log("actual time:", Date.now()/1000 - start)

    start = Date.now()/1000
    my_proceed(2)
    console.log("actual time:", Date.now()/1000 - start)

    start = Date.now()/1000
    my_proceed(4)
    console.log("actual time:", Date.now()/1000 - start)

    start = Date.now()/1000
    my_proceed(2)
    console.log("actual time:", Date.now()/1000 - start)
}

main()
```

gives results that are not always correct : see the example below (the results may slightly vary between runs)
![issue_1474](https://user-images.githubusercontent.com/3447215/91284817-b406be80-e78c-11ea-9bbd-1c4e5fe73323.png)

**Comment by kmindspark** [comment]
Interesting. Thank you so much.

**Comment by PierreQuentel** [comment]
I am closing this issue, since it is similar to #1476.
Thanks again !
