### ISSUE TITLE
Undocumented attribute ".query"

### ISSUE THREAD

**Issue by andy31lewis** [brython-dev/brython#1477]
Hello again

This isn't a bug, more an undocumented fact (at least I couldn't find it in the documentation).  All objects in the browser.html and browser.svg modules seem to have a read-only attribute `query` which gives the query string part of the url of the current page.  For example, in the editor on the Brython website,
```python
from browser import html
d = html.P()
d.query = 99
print(d.query)
```
gives me the output `?lang=en`. (I only discovered this by accident after creating an attribute `obj.query` and spending some time working out why I kept getting errors when using it in other expressions.)

Maybe it is worth mentioning this in the documentation, perhaps in the list of special attributes on the "Attributes, properties and methods" page?

Thanks as ever, Brython just keeps getting better.

Andy

**Comment by PierreQuentel** [comment]
Thanks Andy. It was much more a bug than a feature - there is no reason to set an attribute `query` on all DOM nodes, it only makes sense for `document` (this is documented in the [Query string](https://www.brython.info/static_doc/en/query.html) section).

**Comment by andy31lewis** [comment]
Wow, another fast fix - thank you Pierre.

I had totally missed that part of the documentation - in fact a short while ago I wrote a function to get `window.location.search` and convert it into a dictionary.  I won't need that function any more! :-)

By the way, I don't understand what the phrase in brackets, "(which might be the case for SELECT tags with the attribute MULTIPLE set, or for <INPUT type="checkbox"> tags)" has to do with the query string - it looks like it belongs somewhere else?

Thanks again
Andy

**Comment by PierreQuentel** [comment]
If you have an HTML page with a form such as
```xml
<form action="test1.html">
<select name="numbers" multiple>
<option value="1">one
<option value="2">two
<option value="3">three
</select>
<input type="submit" value="ok">
</form>
```
and the user checks the values "two" and "three", then the page _test1.html_ receives the query string `numbers=2&numbers=3`, `document.query["numbers"]` is the list of selected values.

It is the same if the form includes `<input type="checkbox">` tags with the same name.

**Comment by andy31lewis** [comment]
Thank you - that makes sense to me now. I have always used POST rather than GET for HTTP requests so I haven't needed to think about this before.
Andy
