### ISSUE TITLE
ajax.get(and some other methods) do not respect headers argument

### ISSUE THREAD

**Issue by qualblue** [brython-dev/brython#1480]
I think every method which is using _request_without_body does not respect the headers argument.
Here is a patch against commit 90ef490  (of _www/src/_ajax.js)

diff --git a/www/src/libs/_ajax.js b/www/src/libs/_ajax.js
index 04c844f9..df3002fc 100644
--- a/www/src/libs/_ajax.js
+++ b/www/src/libs/_ajax.js
@@ -53,6 +53,7 @@ function handle_kwargs(self, kw, method){
     var data,
         encoding,
         headers,
+       returnHeaders= {},
         cache,
         mode = "text",
         timeout = {}
@@ -77,9 +78,9 @@ function handle_kwargs(self, kw, method){
             encoding = kw.$string_dict[key][0]
             self.js.encoding = encoding
         }else if(key == "headers"){
-            headers = kw.$string_dict[key].$string_dict
+            headers = kw.$string_dict[key][0].$string_dict
             for(var key in headers){
-                self.js.setRequestHeader(key, headers[key][0])
+               returnHeaders[key]=headers[key][0]
             }
         }else if(key.startsWith("on")){
             var event = key.substr(2)
@@ -120,7 +121,8 @@ function handle_kwargs(self, kw, method){
         data:data,
         encoding: encoding,
         mode: mode,
-        timeout: timeout
+        timeout: timeout,
+       returnHeaders:returnHeaders
     }
 }
 
@@ -299,6 +301,10 @@ function _request_without_body(method){
         return _read(self)
     }
     self.js.open(method.toUpperCase(), url, async)
+    //headers con only be set after calling open !!
+    for (var key in items.returnHeaders) {
+       self.js.setRequestHeader(key,items.returnHeaders[key])
+    }
     self.js.send()
 }

**Comment by qualblue** [comment]
`diff --git a/www/src/libs/_ajax.js b/www/src/libs/_ajax.js
index 04c844f9..df3002fc 100644
--- a/www/src/libs/_ajax.js
+++ b/www/src/libs/_ajax.js
@@ -53,6 +53,7 @@ function handle_kwargs(self, kw, method){
     var data,
         encoding,
         headers,
+       returnHeaders= {},
         cache,
         mode = "text",
         timeout = {}
@@ -77,9 +78,9 @@ function handle_kwargs(self, kw, method){
             encoding = kw.$string_dict[key][0]
             self.js.encoding = encoding
         }else if(key == "headers"){
-            headers = kw.$string_dict[key].$string_dict
+            headers = kw.$string_dict[key][0].$string_dict
             for(var key in headers){
-                self.js.setRequestHeader(key, headers[key][0])
+               returnHeaders[key]=headers[key][0]
             }
         }else if(key.startsWith("on")){
             var event = key.substr(2)
@@ -120,7 +121,8 @@ function handle_kwargs(self, kw, method){
         data:data,
         encoding: encoding,
         mode: mode,
-        timeout: timeout
+        timeout: timeout,
+       returnHeaders:returnHeaders
     }
 }
 
@@ -299,6 +301,10 @@ function _request_without_body(method){
         return _read(self)
     }
     self.js.open(method.toUpperCase(), url, async)
+    //headers con only be set after calling open !!
+    for (var key in items.returnHeaders) {
+       self.js.setRequestHeader(key,items.returnHeaders[key])
+    }
     self.js.send()
 }
`

**Comment by qualblue** [comment]
corrected diff

    diff --git a/www/src/libs/_ajax.js b/www/src/libs/_ajax.js
    index 04c844f9..4191f7d0 100644
    --- a/www/src/libs/_ajax.js
    +++ b/www/src/libs/_ajax.js
    @@ -53,6 +53,7 @@ function handle_kwargs(self, kw, method){
	 var data,
	     encoding,
	     headers,
    +	returnHeaders= {},
	     cache,
	     mode = "text",
	     timeout = {}
    @@ -77,9 +78,9 @@ function handle_kwargs(self, kw, method){
		 encoding = kw.$string_dict[key][0]
		 self.js.encoding = encoding
	     }else if(key == "headers"){
    -            headers = kw.$string_dict[key].$string_dict
    +            headers = kw.$string_dict[key][0].$string_dict
		 for(var key in headers){
    -                self.js.setRequestHeader(key, headers[key][0])
    +		returnHeaders[key]=headers[key][0]
		 }
	     }else if(key.startsWith("on")){
		 var event = key.substr(2)
    @@ -112,15 +113,15 @@ function handle_kwargs(self, kw, method){
	 }
	 if((method == "post" || method == "put") && ! headers){
	     // For POST requests, set default header
    -        self.js.setRequestHeader("Content-type",
    -                                 "application/x-www-form-urlencoded")
    +	returnHeaders["Content-type"]="application/x-www-form-urlencoded"
	 }
	 return {
	     cache: cache,
	     data:data,
	     encoding: encoding,
	     mode: mode,
    -        timeout: timeout
    +        timeout: timeout,
    +	returnHeaders:returnHeaders
	 }
     }

    @@ -299,6 +300,10 @@ function _request_without_body(method){
	     return _read(self)
	 }
	 self.js.open(method.toUpperCase(), url, async)
    +    //headers con only be set after calling open !!
    +    for (var key in items.returnHeaders) {
    +	self.js.setRequestHeader(key,items.returnHeaders[key])
    +    }
	 self.js.send()
     }

    @@ -316,6 +321,9 @@ function _request_with_body(method){
	 var items = handle_kwargs(self, kw, method),
	     data = items.data,
	     timeout = items.timeout
    +    for (var key in items.returnHeaders) {
    +	self.js.setRequestHeader(key,items.returnHeaders[key])
    +    }
	 set_timeout(self, timeout)
	 // Add function read() to return str or bytes according to mode
	 self.js.read = function(){

**Comment by PierreQuentel** [comment]
> I think every method which is using _request_without_body does not respect the headers argument

Can you provide an example of what doesn't work as expected ?

**Comment by qualblue** [comment]
without the patch a button click in the following web page does not create the header "some-header" within the request

    <html>
      <head> 
        <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
        <script src="brython.js" type="text/javascript"></script>
        <script src="brython_stdlib.js" type="text/javascript">
        </script>
      </head>
      <body onLoad="brython(1)">
            some button
            <button id="submit">Send header</button>

        <script type="text/python3"">
          from browser import document
          from browser import ajax

          def MakeRequest(evt):
              ajax.get("HeaderCheck",
                       headers={'some-header':"true",},
                       mode="text",
              )

          document["submit"].bind("click",MakeRequest)

        </script>

      </body>
    </html>
 

The header will be inserted after applying the patch.

**Comment by PierreQuentel** [comment]
Thanks @qualblue !
The commit referenced above should fix the issue, in a slightly different way from your suggestion. Can you confirm ?

**Comment by qualblue** [comment]
Yes, I can confirm

**Comment by PierreQuentel** [comment]
Thanks, I close the issue then.
