### ISSUE TITLE
Iterative page load

### ISSUE THREAD

**Issue by xanthics** [brython-dev/brython#1481]
I am attempting to write Brython code to iteratively create a webpage.  I've created 2 versions that seem to work, but each come with their own issues.  The root of what I am trying to do is generate a webpage from [this list of lists](https://github.com/xanthics/poe_craftingrecipes/blob/master/table_data.py) which has about 1,000 items in it in a correct and fast manner.  One thing to note is both of these solutions **take significantly longer on latest firefox** vs chrome.

# AIO Hack
[Hosted](https://xanthics.github.io/poe_craftingrecipes/index_aio_hack.html) _Takes about 4.5 seconds to finish on Chrome_
[Github file](https://github.com/xanthics/poe_craftingrecipes/blob/master/index_aio_hack.html)

This was my first attempt which just dropped in aio sleep and run.  I know that this generates the page in order, so I can depend on the output.  But it's absolutely a hack since it slows down the total page load by each call to sleep.  I'm not trying to develop/fix this version further, it only exists as a reference.

# Webworker
[Hosted](https://xanthics.github.io/poe_craftingrecipes/index_webworker.html) _Takes about 2 seconds to finish on Chrome_
[Github - index.html](https://github.com/xanthics/poe_craftingrecipes/blob/master/index_webworker.html)
[Github - main.py - line 40](https://github.com/xanthics/poe_craftingrecipes/blob/master/main.py)
[Github - web_worker.py](https://github.com/xanthics/poe_craftingrecipes/blob/master/web_worker.py)

So with this implementation, I've offloaded the generate of all the tables to a web worker.  However in doing so I lose the ability to leverage Brython's tools, such as TABLE and TR, and instead have to work with f-strings and return them.  From the [description](https://brython.info/static_doc/en/worker.html) of worker, in order execution can be assumed, but is not explicit.

An important question, does `from table_data import mods` in web_worker.py get called each time the worker is given a message or does it stay loaded until the worker is "done"?  (_Note that I don't know if/when a worker would consider itself done._)

# Question
Is what I am trying to do supported by Brython?  If so is there a better way to organize the logic so that I have constant access to Brython browser.html functions? Or is the only choice(s) here to leave it as is or have the worker return each sub-list and generate the table sections in main?  

With this specific project, I can also just c+p the output html since the underlying data only changes about once every 3 months, but I'm hoping to expand this to other projects.  I'm currently defining the scope of a project that would have a dictionary with about 20k items in it that can be reorganized based on 3 different values and filtered subsets of those items.

## Question 2
I found that `@bind` on a function for the check boxes and buttons being created needs to be called after all the elements exist.  Is that intended or is there a way to refresh what those functions are bound to?  Currently I have to delay the `@bind` functions from being created until after the tables are created.

**Comment by PierreQuentel** [comment]
Sorry for the very late answer :-(

As far as speed is concerned, nothing beats pure HTML: instead of generating __`table_data.py`__ and using it inside a Brython script (or the equivalent in Javascript), it would be much faster to generate the HTML page, including a Brython script that adds the client-side program: the part of __`main.py`__ that handles events. In the test I made, this static page would have a little less than 300 kB, twice as much as __`table_data.py`__, but the page loads almost immediately (browsers are ultra-optimized to load pure HTML).

If you want progressive loading, then your approach with Web Workers is perfect. My only comment is that in this case, you could remove all the HTML code from __`table_data.py`__, for instance instead of
```xml
'<span class="am"></span><span class="be"></span><span class="bd"></span><span class="bo"></span><span class="gl"></span><span class="he"></span><span class="qu"></span><span class="ri"></span><span class="sh"></span>'
```
the value could simply be
```
'am be bd bo gl he qu ri sh'
```
and the Brython program would generate the SPAN tags on the fly.

Answering your questions:
- the webworker imports `table_data` only once, not at each message
- for bindings:
    - since there is a reference to the buttons, you can add the binding on the fly with the line `b_generate.bind("click", togglemod)`
    - for the `<input>` tags, with the code in __`main.py`__ you have no other choice than what you wrote: add the bindings on the items selected by `@bind('input[type=checkbox]', 'click')`

**Comment by PierreQuentel** [comment]
I am closing the issue, hoping that the answer was relevant. If not, don't hesitate to reopen it.
