### ISSUE TITLE
Floor division + assignment operator fails when variable is a positive integer and operand is a constant positive integer.

### ISSUE THREAD

**Issue by bradley-z** [brython-dev/brython#1482]
The following example fails:
```python
x = 350
x //= 10
print(x) # outputs 350
```
![image](https://user-images.githubusercontent.com/38670656/92009555-b205a800-ed16-11ea-82bc-f5506761e0be.png)
The following examples work as expected:
```python
x = 350
x //= (10)
print(x) # outputs 35
```
```python
x = 350
y = 10
x //= y
print(x) # outputs 35
```
```python
x = -350
x //= 10
print(x) # outputs -35
```
```python
x = 350
x //= -10
print(x) # outputs -35
```

Interestingly, if x is redefined further in the code, the floor division operator works correctly.
![image](https://user-images.githubusercontent.com/38670656/92009036-e88ef300-ed15-11ea-88f1-027eb2596d2f.png)
![image](https://user-images.githubusercontent.com/38670656/92009139-0fe5c000-ed16-11ea-8304-b5452330b7a1.png)
![image](https://user-images.githubusercontent.com/38670656/92009254-3d326e00-ed16-11ea-9797-5afec33c2248.png)

float operands work as expected.

**Comment by PierreQuentel** [comment]
Thanks for the report !
