### ISSUE TITLE
IE9 error because of WebSocket

### ISSUE THREAD

**Issue by youri-ds** [brython-dev/brython#149]
Hello,

jQuery demos don't work with Internet Explorer 9 (supported by [Brython](http://brython.info/static_doc/en/faq.html)):
http://brython.info/gallery/jqui/menu.html
http://brython.info/gallery/jqui/button.html

**Console:**
LOG: Error: no attribute WebSocket for [object Window] for module browser 
LOG: message: no attribute WebSocket for [object Window] 
LOG: filename: undefined 
LOG: linenum: undefined 
LOG: line info 9,browser 
LOG: AttributeError: no attribute WebSocket for [object Window]
Traceback (most recent call last):
  module browser line 9
    WebSocket = javascript.JSConstructor(window.WebSocket) 
SCRIPT16389: Unspecified error. 
js_objects.js, line 230 character 9

**Tested configuration:**
Windows 7 SP1 32 bits
IE9
Brython 3.1

WebSocket is initialized at the loading of the browser module but IE9 doesn't support web sockets.
I found this bug while testing IE9 with my website.

Thank you.

**Comment by PierreQuentel** [comment]
I can't test on IE9 but there are many things that won't work with this browser, it's too hard to adapt Brython to IE-specific (lack of) features
