### ISSUE TITLE
Webcomponents and inheritance

### ISSUE THREAD

**Issue by lovasb** [brython-dev/brython#1497]
Hello,

I try to integrate Brython to my project, and work with webcomponents.

I created some base class from custom elements, like this:

```
    class Element:
    _component_config: Component

    def connectedCallback(self):
        print("connected callback")
        # ... some common logic ...
```
        
        
I try to define a custom webcomponent, like this:

```
    from browser import webcomponent
    
    class Panel(Element):
        def connectedCallback(self):
            super().connectedCallback()

    webcomponent.define('dl-panel', Panel)
```
    
When the super().connectedCallback() is called, I got the folliwing error:

>     Javascript exception: TypeError: Cannot read property '__mro__' of undefined
>         at $$super.__getattribute__ (brython.js:7452)
>         at Object.$B.$getattr (brython.js:6999)
>         at connectedCallback1 (eval at $B.loop (brython.js:5368), <anonymous>:61:29)
>         at brython.js:9109
>         at HTMLElement.eval [as connectedCallback] (eval at run_js (brython.js:9375), <anonymous>:60:54)
>         at define (eval at run_js (brython.js:9375), <anonymous>:83:20)
>         at __call__3 (eval at run_py (brython.js:9428), <anonymous>:130:102)
>         at method (brython.js:5492)
>         at eval (eval at $B.loop (brython.js:5368), <anonymous>:108:38)
>         at $B.loop (brython.js:5368)

Can you help me please, why can't call super on webcomponent like Panel? As I see it the self (on the Panel instance) point's to <Panel object> not HTMLElement.

**Comment by lovasb** [comment]
Example HTML:

```
<html>
    <head>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/brython/3.8.10/brython.min.js" integrity="sha512-vaUMOYK2BF2hTTOXyvh7IoMaY6dDi7WkcywhsyX7XmASXxyZITWmsNK08VVQQwLrcsyGVXsypUNL/rbCeCpyLw==" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/brython/3.8.10/brython_stdlib.min.js" integrity="sha512-CRKDjWdmHDkAJF/3fn4TFNRQkMybzRW41h92BUXM/n4bRMkOpfoO9t7saEw7BN/JstEu9LmYn0tTku+wY6jixw==" crossorigin="anonymous"></script>
        
        <script type="text/python">
            from browser import webcomponent
            
            class Element:
                def connectedCallback(self):
                    print("connected callback")
                    
            class Panel:
                def connectedCallback(self):
                    super().connectedCallback()
                    
            webcomponent.define('dl-panel', Panel)
        </script>
    </head>

    <body onload="brython(1)">
        <dl-panel>Example panel</dl-panel>
    </body>
</html>
```

**Comment by PierreQuentel** [comment]
Thanks for the report @lovasb !

**Comment by lovasb** [comment]
Dear Pierre,

It's working, thank you for your help!
