### ISSUE TITLE
Add more helpful information in `__repr__` methods

### ISSUE THREAD

**Issue by cool-RR** [brython-dev/brython#1498]
I'm debugging my Brython app by using print ([obligatory link](https://github.com/cool-RR/PySnooper/)) and one of the frustrating things I have to deal with is `<HTMLDivElement object>`. Would be cool if these kind of objects had `__repr__` methods that showed some helpful info about them.

By the way, do you know of a way to use something like an interactive debugger on Brython code?

**Comment by PierreQuentel** [comment]
HTML elements have literally hundreds of attributes, so it's difficult to determine what is the "helpful" information that should be shown. But you can customize methods of the `DOMNode` class:

```python
from browser import DOMNode

def show(elt):
  return f"element {elt.tagName}: {elt.html}"

DOMNode.__repr__ = show
```

For interactive debugging, the standard library module __`pbd`__ is supported.

**Comment by cool-RR** [comment]
That could be a useful hack, thank you. I do think that showing some combination of id / name / truncated content would be a good compromise between "no information" and "information overload."

Regarding debuggers, I hate pdb with a passion. Is there anything fancier than pdb that works on Brython?

**Comment by PierreQuentel** [comment]
In the commit referenced above I have modified the defaults methods `__repr__` and `__str__` of `DOMNode`: they now do the same as the browser's inspector, ie show all the attributes of the element. Many thanks for the suggestion !

I'm sorry to disappoint you but no, there is no alternative debugger... I recently added the class `Inspector` in module [__`interpreter`__](https://www.brython.info/static_doc/en/interpreter.html), but all it does is show the value of the variables in the execution stack.

**Comment by cool-RR** [comment]
Thank you, that's helpful!
