### ISSUE TITLE
Implement `sys.gettrace` to allow easier debugging 

### ISSUE THREAD

**Issue by cool-RR** [brython-dev/brython#1499]
I tried to use PySnooper to debug my Brython program, but it failed because it required [`sys.gettrace`](https://docs.python.org/3/library/sys.html#sys.gettrace), which Brython does not implement.

Looking at the documentation, it says it's a CPython implementation detail and might not be available in other Python implementations. That's fair, but it would be helpful if Brython implemented it. What do you think?

**Comment by PierreQuentel** [comment]
Done - this was easier than implementing `settrace()`;-)

**Comment by cool-RR** [comment]
Talk about fast service!

I did try to use PySnooper earlier, with a hacky version of `gettrace`, and it failed on something else without a clear Python traceback. (I know nothing about JavaScript, which is why I'm using Brython in the first place.) If you'd be interested in trying to get PySnooper working on Brython, that'd be cool.
