### ISSUE TITLE
Bug in int handling 

### ISSUE THREAD

**Issue by cool-RR** [brython-dev/brython#1504]
Brython:

```
>>> int('db1e8800bc27a3', base=16)
Traceback (most recent call last):
  File <string>, line 1, in <module>
Exception: <Javascript Error>: wrong exp 8800bc27a3
```

CPython:

```
>>> int('db1e8800bc27a3', base=16)
61676589376350115
```

**Comment by cool-RR** [comment]
I tried different strings, some work and some don't. I couldn't find the pattern. I initially thought it's determined by length but it's not, or at least not just by length.

**Comment by andy31lewis** [comment]
From trying a few strings, I think it only fails if it is at least 14 characters long, AND contains a lower case e. If you change the e to upper case E, it works.
What is causing this I can't imagine...

**Comment by PierreQuentel** [comment]
Thanks for the report. A lowercase 'e' was mistaken with the exponential notation...
