### ISSUE TITLE
Multi-processing

### ISSUE THREAD

**Issue by maxkeller321** [brython-dev/brython#1508]
Hello Brython-Contributors, 

First: Thanks for this awesome software.

 I'm using Brython as an interpreter for scripts, which users code on my website (As a first validation stage, before I run them on the server-side).  

Is there a way to use multiprocessing in Brython ? I would like to kill processes after max. 10 seconds (to stop endless loops, ...).

Thanks for the help in advance. 

Max

**Comment by moepnse** [comment]
You could achieve that with `RestrictedPython` and a customized `NodeTransformer`.

Brython is based on JavaScript. Concurrency can be achieved in Javascript using `Web Workers`.

See: [Web Workers](https://brython.info/static_doc/en/worker.html)

Maybe someone else has a better idea.

**Comment by moepnse** [comment]
I took a closer look at the Brython source code.

A multiprocessing module like the one from CPython also exists in Brython.

The multiprocessing module from Brython is based on `WebWorkers` and also implements a function to end a running "process".

See:
https://docs.python.org/3/library/multiprocessing.html#multiprocessing.Process.terminate

And:
https://github.com/brython-dev/brython/blob/13ad2cb11827935bdd4e0cee3a8444bb0fa78735/www/src/libs/_multiprocessing.js#L58

I have written a small example, which unfortunately breaks with an exception.

```python
Brython 3.9.0 on Netscape 5.0 (X11)
>>> from browser import timer, console
from multiprocessing import Process


def f():
    while True:
        console.log("running!")


p = Process(target=f)
p.start()

timer.set_timeout(p.terminate, 3000)
Traceback (most recent call last):
  File <string>, line 2, in <module>
  File https://www.brython.info/src/Lib/multiprocessing/__init__.py, line 40, in <module>
    from multiprocessing.util import SUBDEBUG, SUBWARNING
  File https://www.brython.info/src/Lib/multiprocessing/util.py, line 18, in <module>
    from subprocess import _args_from_interpreter_flags
  File https://www.brython.info/src/Lib/subprocess.py, line 80, in <module>
    import selectors
  File https://www.brython.info/src/Lib/selectors.py, line 616, in <module>
    elif _can_use('poll'):
  File https://www.brython.info/src/Lib/selectors.py, line 595, in _can_use
    selector_obj = selector()
  File https://www.brython.info/src/Lib/select.py, line 65, in __init__
    self.selector = java.nio.channels.Selector.open()
NameError: name 'java' is not defined
>>> 
```

Seems to be an unfinished port from a Jython module.

https://github.com/brython-dev/brython/blob/13ad2cb11827935bdd4e0cee3a8444bb0fa78735/www/src/Lib/select.py#L46

**Comment by moepnse** [comment]
This sample does what you want.

```python
<!DOCTYPE html>
<html>
    <head>
        <!-- Required meta tags-->
        <meta charset="utf-8">
        <title>WebWorker</title>
        <!-- Brython -->
        <script src="/static/brython/brython.js"></script>
        <script src="/static/brython/brython_stdlib.js"></script>
        <script type="text/python" id="test_worker" class="webworker">
# In web workers, "window" is replaced by "self".
# Standard library imports.
from browser import bind, self, console

# Related third party imports.

# Local application/library specific imports.


@bind(self, "message")
def message(evt):
    """Handle a message sent by the main script.
    evt.data is the message body.
    """
    while True:
        console.log("running!")

        </script>
        <script type="text/python">
# Standard library imports.
from browser import console, window, worker, bind, timer

test_worker = worker.Worker("test_worker")


@bind(test_worker, "message")
def onmessage(e):
    pass


def kill():
    console.log("kill!")
    test_worker.terminate()


test_worker.send("test")

# does not work
#timer.set_timeout(test_worker.terminate, 500)
timer.set_timeout(kill, 500)
        </script>
    </head>
    <body onload="brython({debug: 1});">
    </body>
</html>
```

Be careful. In combination with the development-console it crashed my machine, if the timeout is set too high.

If you want to find infinite loops in advance, then a customized `NodeTransformer` is what you want.
