### ISSUE TITLE
None as an object attribute is not null

### ISSUE THREAD

**Issue by cool-RR** [brython-dev/brython#1514]
When you use `__BRYTHON__.$getattr` to get an attribute on an object, and that attribute's value is None, then it doesn't get translated to JavaScript's null. This tripped me up. I'm now using False as a workaround, let me know if there's a better one.

**Comment by PierreQuentel** [comment]
_If you really want to use Brython objects in a Javascript program_ (which once again I don't recommend), yes, you can use a boolean value.

**Comment by cool-RR** [comment]
But when I asked you how to construct JavaScript objects in Brython so they could be read easily on the JavaScript side, you said you didn't recommend that either. If both ways are not recommended, what is the recommended way to move information between Brython and JavaScript?
