### ISSUE TITLE
Optimize regular expressions performance

### ISSUE THREAD

**Issue by cool-RR** [brython-dev/brython#1519]
I just ran into the problem [that Edward Elliott raised here](https://groups.google.com/g/brython/c/F5u-IsOSDho/m/-iRULPVmCAAJ). I had lots of slowness in my program, and after a binary search I found it was because I was using the `re` module, which is very slow under Brython.

**Comment by cool-RR** [comment]
Also, a recipe for using JavaScript regexes from Brython would be helpful.

**Comment by PierreQuentel** [comment]
There is a recipe in the last example of the [demo page](https://www.brython.info/demo.html?lang=en#).

**Comment by cool-RR** [comment]
Right, thank you.

**Comment by PierreQuentel** [comment]
This issue was fixed with the introduction of a Javascript version of the Python regular expression engine in Brython 3.9.2.

**Comment by cool-RR** [comment]
Awesome! Thank you.
