### ISSUE TITLE
How to open local file?

### ISSUE THREAD

**Issue by pckhoi** [brython-dev/brython#1525]
Hello, I'm trying to read local file with `open`. I feel like it should work but it doesn't.

```Python
from browser import document

input = document.getElementById("file")

def change(event):
    global input
    document <= "loading..."
    f = open(input.files[0])
    document <= f.read()

input.addEventListener('change', change)
```

There seems to be some support for this in the past with `asyncio.fs` module? What replace it now?

**Comment by PierreQuentel** [comment]
@pckhoi 
I would suggest that you take a look at the section "select, read and save a local file" of the Demo page.

**Comment by pckhoi** [comment]
Thanks for pointer!
