### ISSUE TITLE
CustomEvent parameters

### ISSUE THREAD

**Issue by iansparks** [brython-dev/brython#1526]
Hi, I was trying to create a custom event to allow an element to communicate up the DOM heirarchy to a parent element.

I tried to use CreateEvent

https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events

in brython like:

```
event = window.CustomEvent.new("counter_change", {detail: 1, bubbles: True})
el.dispatchEvent(event)   # el is a html.BUTTON element here but it doesn't matter
```

I get the error from the console:

```
event = window.CustomEvent.new("counter_change", {
NameError: name 'detail' is not defined
```

Note that I was able to do what I wanted with the old-style approach using document.createEvent :

```
event = document.createEvent("CustomEvent")
event.initCustomEvent("counter_change", True, True, 1)
el.dispatchEvent(event)   # el is a html.BUTTON element here but it doesn't matter
```

Which I'm including here in case anyone else has this issue. I am not 100% sure this is a bug since many versions of IE don't support window.CustomEvent and instead use only document.createEvent. If someone can comment on what the intention is, I would be happy to attempt a PR to update the docs to mention custom events.

**Comment by PierreQuentel** [comment]
This is because in Python, if you define a dictionary with
```python
{detail: 1}
```
it will try to map _an object named_ `detail` (there is none in your code, hence the error message), whereas in Javascript the same code maps the _string_ "detail".

Here is a working example:
```python
from browser import bind, document, window

el = document["el"]
@bind(el, "counter_change")
def counter_change(ev):
  print("event triggered")

event = window.CustomEvent.new("counter_change", 
    {"detail": 1, "bubbles": True}) # note the quotes around the keys
el.dispatchEvent(event)
```

**Comment by iansparks** [comment]
Thanks @PierreQuentel. Sorry it was something so simple.
