### ISSUE TITLE
ImportError: Import ipaddress fails

### ISSUE THREAD

**Issue by SamiLehtinen** [brython-dev/brython#1534]
In brython.info console:
Brython 3.9.0 on Netscape 5.0 (Windows)
>>> import ipaddress
Traceback (most recent call last):
  File <string>, line 1, in <module>
  File https://brython.info/src/Lib/ipaddress.py, line 1529, in <module>
    class _IPv4Constants:
  File https://brython.info/src/Lib/ipaddress.py, line 1538, in _IPv4Constants
    _private_networks = [
  File https://brython.info/src/Lib/ipaddress.py, line 1504, in __init__
    raise ValueError('%s has host bits set' % self)
ValueError: 255.255.255.255/32 has host bits set
>>>

**Comment by PierreQuentel** [comment]
@SamiLehtinen Thanks for the report :-)
