### ISSUE TITLE
html.DIV subclass loses methods on mouseover?

### ISSUE THREAD

**Issue by iansparks** [brython-dev/brython#1536]
This may be another rookie mistake. Here I am making a html.DIV subclass and adding a button as a child to it. I also add mouseover to "self" (the DIV) which sets the border of the DIV to red. Clicking the button should say "HELLO" to the console.

Scenario 1: Click the button without hovering over the div. As expected get a message on the console.
Scenario 2: Hover over  the div (it gets red border) then click the button. Boom! The div apparently does not have the subclass methods and in fact is no longer a subclass instance but (I think) reverted to just the base type (DIV).

Tested in Firefox and Chrome but could be a misunderstanding about how events are bound. Code to reproduce:

```
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <script type="text/javascript"
        src="https://cdn.jsdelivr.net/npm/brython@3.9.0/brython.min.js">
    </script>
</head>


<body onload="brython(1)">

<script type="text/python">
from browser import document, window, html, console, bind

class Greeting(html.DIV):

  def __init__(self, *args, **kwargs):

    html.DIV.__init__(self, *args, **kwargs)

    self.up_button = html.BUTTON("SAY HI")
    self <= self.up_button
    self.up_button.bind("click", self.greet)
    self.bind('mouseover', self.mouse_over)

  # Methods
  def say_hello(self):
    console.log("HELLO!")

  # Events
  def greet(self, evt):
    # Once mouse-over has occurred, the "self" that gets passed here does not have say_hello method any more...
    # assert isinstance(self, Greeting)  <-- put this back in if you want to assure yourself that its no longer a Greeting
    self.say_hello()

  def mouse_over(self, event):
    event.target.style.border = "1px solid red"
    event.target.style.cursor = "pointer"
#    event.stopPropagation()   <- makes no difference


c = Greeting()
document.body <= c

</script>

</body>

</html>
```

**Comment by PierreQuentel** [comment]
Thanks @iansparks. The bug happened when getting a reference to an element created from a subclass of an HTML class : the object had its `__class__` set to the base class... Here, this happened when getting a reference to the `Greeting` instance by `event.target`.

**Comment by iansparks** [comment]
Thanks @PierreQuentel. I am not sure if there is any documentation on how html.XXX elements (and subclasses) interact with the DOM. 

With your latest this now works (thank you!)

```
c = Greeting()
document.body <= c
x = document.select_one("div")
x.say_hello()
```

But how does `x` know it is a python object and not just a Plain Old DOM object? 

I am sorry to add this question to a closed issue!
