### ISSUE TITLE
Need a way for binding an element with delegate "mechanism" (like with .on() on jquery)

### ISSUE THREAD

**Issue by kegilko** [brython-dev/brython#1540]
Hi, thank you for this incredible library :) I'm making a website for my students (learning python)

Long post here : [https://stackoverflow.com/questions/64935302/brython-python-through-javascript-generate-dynamically-multiple-python-front](https://stackoverflow.com/questions/64935302/brython-python-through-javascript-generate-dynamically-multiple-python-front)

And in short, I want create dynamically instances of python code on a web page. And each instance must be bound with a custom event managed in a main "text/python" script tag. 
But I don't find how can I do it with Brython (maybe its impossible ?)

Is there a way for binding an non-existant dom element with Brython api ? 

Thank you for any help :)

**Comment by iansparks** [comment]
I don't know if this helps at all but any event that is fired on an element in the DOM tree will "bubble" up. This is all that .on() in jquery is doing - it's attaching the listener for the event on the document or on the body element so that it will receive the event if nothing else does.

When you recieve the event you can find out what element dispatched it and then do another bind to THAT (or to something inside it) if you need to.

```
from browser import console
from browser import html, document

# Define capturing event handler
def capture_event(event):
    console.log("Received your event!")
    console.log(event)
    console.log(event.target.my_prop)
    console.log(event.detail)

# Bind document to capture the event
document.bind("MyCustomEvent", capture_event)

# Create a new DIV
new_div = html.DIV("Hello World!")

# Set a custom property on the div
new_div.my_prop = "Yes, it's me"

# Add the new div to the document
document <= new_div

# Trigger event on div
event = document.createEvent("CustomEvent")
event.initCustomEvent("MyCustomEvent", True, True, {'a' : 1, 'b' : 2})
new_div.dispatchEvent(event)

```

does it help?

**Comment by iansparks** [comment]
If you want to detect that the script with python is added, maybe Pierre's example using MutationObserver can also be helpful? It allows you to detect that a new element is being added to the DOM (or modified...) and act accordingly. Works in most modern browsers.

https://github.com/brython-dev/brython/issues/1533#issuecomment-723441261

**Comment by kegilko** [comment]
Thanks for your help :) 

I generate html blocs with javascript. And for each bloc dynamically generated (with a simple button "generate another editor" by example), I need to bind an element (the button "exec your code") of the bloc to a function 'run' defined from a main "text/python" tag : 

```python
def run(e): # execute the python code 
    id = e.target.getAttribute("data-pythonshell-id")
    sys.stdout = consoleToDOMElement(id) # for show the output result in the webpage instead console.log pannel
    try:
        exec(document.select('.pythonshell-codeBloc[data-pythonshell-id="' + id + '"]')[0].textContent)
    except Exception:
        # ... show error
```

In your first answer, the "generated element" is managed from python code. For various reasons, I want to keep the dynamic generation in the javascript side (that includes the bind of the generated button "exec your code"), and my problem is I don't succeed in calling a defined python function from javascript. 

Your second answer seems about a pure python way, I'm not sure if that help me...(maybe I'm wrong ?)

The "selector" python with a delegate mechanism does not seems exist, now I'm looking for access to a defined python function from a javascript script tag : (if I can execute a python command in the fly from javascript code, I think my problem will be solved)

My last minimalist code try : 

```html
<div id="exec-result" style="height: 150px;background-color: #66aa66"></div>
<script type="text/python">
from browser import document, window
import traceback
import sys

class consoleToDOMElement:
    def __init__(self, id):
        self.console = document.select('#exec-result')[0]
        self.buf = ''

    def write(self, data):
        self.buf += str(data)

    def flush(self):
        self.console.value += self.buf
        self.buf = ''

    def __len__(self):
        return len(self.buf)

def execfoo(code):
    sys.stdout = consoleToDOMElement(id)
    try:
        exec(code)
    except Exception:
        document.select('#exec-result')[0].value=traceback.format_exc()

window.execfoo = execfoo
</script>
<script type="text/javascript">
    console.log(window);
    window['execfoo']('print(123)');
</script>
```

In the console.log, the object window has the "fooo" entry : 

![window](https://i.ibb.co/gP7znVV/Screenshot-from-2020-11-21-11-08-16.png)

but the `window['execfoo']('print(123)');` does not show the execution of the python command "print(123)" in the "#exec-result" div, instead I get this dumb error `Uncaught TypeError: window.execfoo is not a function`...

**Comment by iansparks** [comment]
I am not sure, maybe you are making this harder than it needs to be? Here I use javascript to add new "code blocks" (a textarea and a button to run it). 

```
<!doctype html>
<html>

    <head>
        <meta charset="utf-8">
        <script src="https://raw.githack.com/brython-dev/brython/master/www/src/brython.js"></script>

    </head>

    <div id="editor_container">

    </div>
    <button id="add_another">Add Another</button>


<body onload="brython()">

<script type="text/python">
from browser import console

# Define capturing event handler
def capture_event(event):
    console.log("Received your event!")
    console.log(event)
    console.log(event.target)
    exec(event.target.value)


</script>

<script type="text/javascript">

    var button = document.getElementById("add_another");
    var container = document.getElementById("editor_container");

    // We'll add a unique value to each "Hello from python" message
    var i = 1;

    // Inject Each time we click the button, add another code block and button.
    button.addEventListener("click", function(){
        var new_area = document.createElement('div');

        var text = document.createElement("textarea");
        text.innerText = 'print("Hello from python! #' + i + '")';
        new_area.appendChild(text);

        var run_btn = document.createElement("button");
        run_btn.innerText = "Run!";
        new_area.appendChild(run_btn);

        // When we click the added run button we dispatch our custom event on the text area
        // out python handler can receive the event
        run_btn.addEventListener("click", function(){
            var event = new CustomEvent('MyCustomEvent', {bubbles: true, cancelable: true});
            text.dispatchEvent(event);
        });

        container.appendChild(new_area);

        i += 1;

    })


     </script>
  </body>
</html>
```

**Comment by kegilko** [comment]
> maybe you are making this harder than it needs to be?

Its possible ;) 

I tested your code, I generated some "editor_container" with your button "add_another". But when I clic on a button "Run !", nothing happen..no error, no message in console.log panel and nothing on the webpage 

Is that normal ?

**Comment by iansparks** [comment]
Ouch! Sorry! I missed the binding line. Make the python script section this:

```
<script type="text/python">
from browser import console

# Define capturing event handler
def capture_event(event):
    console.log("Received your event!")
    console.log(event)
    console.log(event.target)
    exec(event.target.value)


# Bind document to capture the event
document.bind("MyCustomEvent", capture_event)    # <---- Missing line!
</script>

```

**Comment by iansparks** [comment]
Grr.. I also missed import of document on the python side. Rushing!

```
<script type="text/python">
from browser import console, document # <-- also need document for the bind
# Define capturing event handler
def capture_event(event):
    console.log("Received your event!")
    console.log(event)
    console.log(event.target)
    exec(event.target.value)


# Bind document to capture the event
document.bind("MyCustomEvent", capture_event)    # <---- Missing line!
```

**Comment by kegilko** [comment]
Its work :D its alliiveeee 

Indeed, Im making this harder than it needs to be
Your great example code help me to gain a better understanding about binding element and, as you show in your first answer, there is just need to bind the document element. 

Thank you again for your help and your time :)
