### ISSUE TITLE
Cannot override appendChild in subclasses of html.* elements 

### ISSUE THREAD

**Issue by iansparks** [brython-dev/brython#1543]
For [nef|v]arious reasons I want to subclass html.* elements and capture attempts to add child elements to them.

No matter how a child is added ( <=, attach(), via constructor) I want to know so I'm looking for the universal "addAChild"  function. In the code that looks like` appendChild`

What I found is that overriding appendChild on a html.DIV is ignored. Demonstrated below:

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <script src="https://raw.githack.com/brython-dev/brython/master/www/src/brython.js"></script>
  </head>
<body onload="brython(1)">
</body>
</html>

<script type="text/python">
from browser import document, html

class MyDIV(html.DIV):

    def appendChild(self, other):
        print(f"Appending Child {other}")
        super().appendChild(other)

# Most surprising our appendChild is never called but child span ends up in the document.
d = MyDIV()
d.appendChild(html.SPAN("Test!"))
document <= d


</script>
</body>
</html>

```

**Comment by PierreQuentel** [comment]
`appendChild` is a property of DOMNode _instances_. `element.appendChild` is resolved as this instance property, regardless of a method of the same name defined in the instance's class.

If you want to override methods, you can use those defined in Brython `DOMNode` class such as `attach`, or even `__le__` if you use the operator <= to append a child

```python
from browser import document, html

class MyDIV(html.DIV):

    def attach(self, other):
        print(f"Appending Child {other} with 'attach'")
        super().attach(other)

    def __le__(self, other):
        print(f"Appending Child {other} with <=")
        super().__le__(other)


d = MyDIV()
d.attach(html.SPAN("Test attach"))
document <= d

d = MyDIV()
d <= html.SPAN("Test <=")
document <= d
```

**Comment by iansparks** [comment]
Thanks @PierreQuentel - that behaviour is surprising to the uninitiated but you put me on the course to being able to intercept attach and __le__ calls. However, the constructor method calls appendChild directly I think.

Is there a way to intercept appends that happen via the constructor - example below (OK overriding __init__ but another way?) - it just feels like there should be a single place that could be instrumented?



```
from browser import document, html

class MyDIV(html.DIV):

    def attach(self, other):
        print(f"Appending Child {other} with 'attach'")
        super().attach(other)

    def __le__(self, other):
        print(f"Appending Child {other} with <=")
        super().__le__(other)


d = MyDIV()
d.attach(html.SPAN("Test attach"))
document <= d

d = MyDIV()
d <= html.SPAN("Test <=")
document <= d

d = MyDIV([html.SPAN("Test Constructor")])    # <--- how to capture this? If answer is only __init__ OK. 
document <= d
```

**Comment by PierreQuentel** [comment]
I understand that this is not obvious at first, because DOM elements come with a number of instance attributes that are not explicitely set in the constructor; in the commit above I have added a warning for such cases. Does it make sense ? should we limit it for when debug mode is > 1 ?

In your first example, resolution of the attribute `appendChild` would require to bypass the usual rule and give priority to the class attribute over the instance attribute. But if we redefine the attribute by

```python
d.appendChild = 9
```

then we would expect that the next resolution of name `appendChild` uses the instance attribute.

For your other question (capturing appends made in the constructor), I can't think of a better solution than using `__init__`.

**Comment by iansparks** [comment]
Thanks for the explanation. I think the added warning is useful. I don't have an opinion on whether it should only appear for debug > 1 but for the message itself. An current example:

> Warning:line 36,DIVelement has instance attribute 'appendChild' set,attribute of class MyDIVis ignored

I suggest some small changes to spacing and punctuation for clarity:

> Warning:line 36,DIV element has instance attribute 'appendChild' set. Attribute of class MyDIV is ignored

changes are:

> Warning:line 36,DIV| |element has instance attribute 'appendChild' set|. A|ttribute of class MyDIV| |is ignored

Thanks!

**Comment by PierreQuentel** [comment]
I have slightly changed the message, but the whitespaces were there on the 3 browsers I tried (Firefox, Chrome and Edge).

**Comment by iansparks** [comment]
![Screenshot from 2020-12-01 10-58-47](https://user-images.githubusercontent.com/16936481/100732172-4a6a0200-33c4-11eb-99a2-7c32dcfb5cca.png)

The above is from firefox but chrome is the same for me. It is different from when I first viewed but the last "is" is still missing space.

Also, I think there is some slight delay or caching from https://raw.githack.com/brython-dev/brython/master/www/src/brython.js which meant I had to hard refresh a few times before I saw the change.

**Comment by PierreQuentel** [comment]
Very strange... I have modified the way the message is produced, does this solve the whitespace issue ?

**Comment by iansparks** [comment]
Yes:

```Warning: line 10, DIV element has instance attribute 'appendChild' set. Attribute of class MyDIV is ignored.```

I think some kind of caching issue. Thanks!

**Comment by iansparks** [comment]
I am sorry to re-open this issue. In this test I am receiving the warnings (regardless of brython(1) or brython() used) for elements that I am not (deliberately) overriding.

In this test when I hover over the greeting I expect the border to change to a red line. It does, but I also get the warning about Greeting.style being ignored which is confusing because here I did not override 'style'.

Is it possible to show the warning only if there is an overridden method/attribute? I recognize this might make brython slower. Maybe you think it best to remove the warning totally? 

```
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <script type="text/javascript"
        src="https://raw.githack.com/brython-dev/brython/master/www/src/brython.js">
    </script>
    <script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/brython/3.8.10/brython_stdlib.min.js">
    </script>

</head>


<body onload="brython()">

<script type="text/python">
from browser import document, window, html, console, bind

class Greeting(html.DIV):

    def mouse_over(self, event):
      self.style.border = "1px solid red" <-- warning that attribute of Greeting is being ignored
      #event.target.style.border = "1px solid red"   <-- same

c = Greeting("Hello World!")
c.bind("mouseover", c.mouse_over)
document.body <= c


</script>

</body>

</html>
```

**Comment by PierreQuentel** [comment]
Don't be sorry, it was my mistake ! Hopefully the message is now printed only in the cases when it is supposed to be.

**Comment by iansparks** [comment]
Sadly I still have the issue. I have tried downloading the brython.js from github and using githack url. Here's my most minimal test:

```
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <script type="text/javascript"
        src="https://raw.githack.com/brython-dev/brython/master/www/src/brython.js">
    </script>
</head>


<body onload="brython(1)">

<script type="text/python">
from browser import document, html

class Greeting(html.DIV):
  pass

c = Greeting("Hello  World!")
c.style.border = "1px solid red"
document.body <= c

</script>

</body>

</html>
```

Warning appears on the console when run.

**Comment by iansparks** [comment]
Confirm that fixes it. Thanks @PierreQuentel
