### ISSUE TITLE
`import importlib.resources` raises Javascript SyntaxError

### ISSUE THREAD

**Issue by mwchase** [brython-dev/brython#1546]
Encountered in the console on brython.info, which I believe is the latest release.

Steps to reproduce:

1. Navigate to https://brython.info/tests/console.html?lang=en
1. Type `import importlib.resources`

Expected behavior: import completes successfully, module is bound to `importlib.resources`

Encountered behavior: The following traceback is produced, and the module is not accessible:
```
Traceback (most recent call last):
Exception: <Javascript SyntaxError>: missing catch or finally after try
```
I reproduced this on both Firefox and Chromium, but either I'm misinterpreting the console tracebacks, or they're having trouble localizing the error, because it looked to me like they were pointing at totally different lines of Javascript.

**Comment by PierreQuentel** [comment]
@mwchase Thanks for the report !

I could reproduce the bug in the console at brython.info, but in the current development version I had another exception reporting that module __`importlib._common`__ was missing. I have added it in the commit referenced above and with this change, `import importlib.resources` now works.

The site at brython.info will be updated at next release, due in a few days.

**Comment by PierreQuentel** [comment]
I close the issue, the import works in the console with the new version 3.9.1.
