### ISSUE TITLE
Classes which inherit object and getattribute magic method?

### ISSUE THREAD

**Issue by iansparks** [brython-dev/brython#1551]
In CPython3.8 classes which descend from `object` have `__getattribute__` magic attribute. Brython seems to treat classes which extend from object as no-object classes.

cpython 3.8
```
class MyClass(object):   # <-- extends object

    def __init__(self):
       self.x = 1

    def __getattribute__(self, name):
        raise Exception("This will never happen")


m = MyClass()
print(m.x)
```

and I will get this exception:

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "<input>", line 8, in __getattribute__
Exception: This will never happen
```

Equivalent test code in brython:

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <script src="https://raw.githack.com/brython-dev/brython/master/www/src/brython.js"></script>
  </head>
<body onload="brython(1)">
</body>
</html>


<script type="text/python">

class MyClass(object):   

    def __init__(self):
       self.x = 1

    def __getattribute__(self, name):
        raise Exception("This will never happen")


m = MyClass()
print(m.x)

</script>


</body>

</html>

```

prints '1' to the console. Suggests that `__getattribute__` does not get called at all which is the same behaviour as a class in CPython that does not inherit from object:

**cpython 3.8:**
```
class MyClass:   # does not inherit from object

    def __init__(self):
       self.x = 1

    def __getattribute__(self, name):
        raise Exception("This will never happen")


m = MyClass()
print(m.x)
> 1 appears on console
```

Is it a known limitation?

**Comment by PierreQuentel** [comment]
No it was not known ;-)

There is a shortcut for name resolution in classes that have no other parent than `object` and in this shortcut, testing the presence of the special method `__getattribute__` was missing.

Thanks !
