### ISSUE TITLE
A print statement that blocks the browser?

### ISSUE THREAD

**Issue by iansparks** [brython-dev/brython#1554]
This is an odd one. When I load this program in a browser, it blocks the browser tab until (Firefox at least) asks me if I want to wait or kill the request.

I don't get errors on the console, the code simply doesn't load (FF and Chrome). The same 3 lines of code returns a SyntaxError in Python3.

```
  File "<input>", line 2
    print(f"Bad format {}")  # Hey, that's not nice..
                         ^
SyntaxError: invalid syntax
```

The Brython code:

```
<!doctype html>
<html lang="en">
<head>
    <script src="https://raw.githack.com/brython-dev/brython/master/www/src/brython.js"></script>
</head>

<body onload=brython(1) >

<script type="text/python">
print("Before bad format")
print(f"Bad format {}")  # Hey, that's not nice.. an f-string with no content..
print("After bad format")

</script>

</body>

</html>
```

**Comment by PierreQuentel** [comment]
Thanks Ian. Brython now raises the expected `SyntaxError: f-string: empty expression not allowed`
