### ISSUE TITLE
augmented assignment on tuple does not throw SyntaxError

### ISSUE THREAD

**Issue by austin-schick** [brython-dev/brython#1557]
These lines

```
a,b = 0,0
a,b += 1
```

run in the Brython console produce the one-element tuple `(0,)`. However, in the Python console they raise

```
SyntaxError: illegal expression for augmented assignment
```

The same holds for `-=` and `*=`

**Comment by PierreQuentel** [comment]
@austin-schick Thanks for the report. The commit above fixes other similar syntax errors:
```python
(a, b) += 1
[a, b] += 1
{a, b} += 1
{a: 0, b: 1} += 1
{} += 1
```

**Comment by austin-schick** [comment]
Thanks as always for the quick turnaround @PierreQuentel!
