### ISSUE TITLE
isinstance returns false when testing builtin types against abstract base classes

### ISSUE THREAD

**Issue by kyouko-taiga** [brython-dev/brython#156]
Hello guys,
It seems like the instance check and subclass check doesn't work for builtin types agains ABCs. Here's an example:
```python
from collections import abc
isinstance(dict(one=1), abc.Mapping)
>>> False
issubclass(dict, abc.Mapping)
>>> False
```

Obviously, both these expressions should return True.

**Comment by PierreQuentel** [comment]
Hi,

This is one of the shortests issue ever reported, but also one of the most difficult ever to solve ! I had to rewrite the implementation of generators to fix it...

Many thanks
- Pierre

**Comment by kyouko-taiga** [comment]
Many thanks on you, and good job!
