### ISSUE TITLE
Unpacking into tuple not working.

### ISSUE THREAD

**Issue by gilch** [brython-dev/brython#1562]
I tried this in both the online editor and the console at https://brython.info:

```
Brython 3.9.0 on Netscape 5.0 (Windows)
>>> foobar = *'foobar',
  File <string>, line 1
    foobar = *'foobar',
              ^
SyntaxError: invalid syntax
```
CPython can do it.
```
Python 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> foobar = *'foobar',
>>> foobar
('f', 'o', 'o', 'b', 'a', 'r')
```
If Brython doesn't use the same grammar as CPython, then some Python modules won't load in Brython.

**Comment by gilch** [comment]
CPython does have a test suite that should catch this kind of thing. Has anyone tried running that in Brython?

**Comment by PierreQuentel** [comment]
> CPython does have a test suite that should catch this kind of thing. Has anyone tried running that in Brython?

Yes, there is an online version of the CPython test suite. If you clone the repository it is at _tests/unittests_. I use it from time to time when there are no bug report to work on ;-)

**Comment by gilch** [comment]
I found another case that looks related. This works in CPython:
```
Python 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> spam = ['spam']
>>> *spam[0],
('s', 'p', 'a', 'm')
```
But not in Brython:
```
Brython 3.9.0 on Netscape 5.0 (Windows)
>>> spam = ['spam']
>>> *spam[0],
  File <string>, line 1
    *spam[0],
             ^
SyntaxError: invalid syntax
```

**Comment by gilch** [comment]
Found another one:

CPython:
```
>>> class Spam:
...   def __neg__(self):
...     return 'spam'
...
>>> *-Spam(),
('s', 'p', 'a', 'm')
```
Brython:
```
>>> class Spam:
...   def __neg__(self):
...     return 'spam'
... 
>>> *-Spam(),
Traceback (most recent call last):
Exception: <Javascript TypeError>: C.op.substr is not a function
```

**Comment by PierreQuentel** [comment]
Thanks for this report and the others !

I must confess that I would have said that `x = *'abcd'` is valid Python syntax, and that I don't know why the trailing comma is necessary for unpacking.

**Comment by gilch** [comment]
Iterable unpacking is only allowed inside certain contexts: call, tuple, list, and set. The trailing comma puts it inside a tuple.

Only singles require the trailing comma. For longer tuples, it's optional:

Does this case work in Brython now? There's no trailing comma this time (not required for a pair).
```
>>> 1, *'two'
(1, 't', 'w', 'o')
```

And, does it work for bytes now? It wasn't clear from the diff.
```
>>> *b'ABC',
(65, 66, 67)
```

And does it work in a list now? It doesn't in the web console yet. This doesn't have a comma either.
```
>>> [*'spam']
['s', 'p', 'a', 'm']
```
Sets work though.
