### ISSUE TITLE
Small problem with JS minifier

### ISSUE THREAD

**Issue by mircea3** [brython-dev/brython#1565]
Given the following short JS file:

```
var ss = '\''
```

Minifying it using `scripts/javascript_minifier.py` gives the following exception:

```
SyntaxError: string not closed in line 0 : '\''
```

Modifying line 27 solves the problem, but I cannot confirm it doesn't break something else:

```
- start = end+1
+ start = end
```

**Comment by PierreQuentel** [comment]
Thanks @mircea3 !
