### ISSUE TITLE
Reload python module without page reload

### ISSUE THREAD

**Issue by lovasb** [brython-dev/brython#1567]
My question is: Is there any API to programmatically reload a Python / Brython module without full page reload? I think it can dramatically speed up the development process.

I'm searching for functionality like:
```
<script type="text/python">
    from module_example import Klass
    k = Klass()

     VFS_invalidate('module_example')
     VFS_reload('module_example')

     k = Klass()
</script>
```

Thanks forwards.

**Comment by lovasb** [comment]
I tried reload the module in Javascript, but it doesn't seem to be working:

The Python/Brython module:

```
# frontend/a.py

example = 7
```

Script in HTML:

```
<html>
    <head>
        ...
        
        <script type="text/brython">
            from frontend import a
            print('example value:', a.example)
        </script>
    </head>
    ...
</html>
```

When I run this, I see in the console:

```
example: value: 7
```

After I try to reload the "a.py", run this Javascript in browser:

```
scripts = {"frontend.a": [".py", "example = 8", []]}
window.__BRYTHON__.update_VFS(scripts)
brython({debug:1})
```

I get a warning (Virtual File System: duplicate entry frontend.a), but the example value isn't incremented.

**Comment by PierreQuentel** [comment]
You can use the standard Python mechanism, ie function `reload()` of module __`importlib`__

```xml
<script type="text/python">
from browser import bind, document

from importlib import reload

import module_example
k = module_example.Klass()

@bind('#reload', 'click')
def _reload(ev):
  reload(module_example)
  k = module_example.Klass()
</script>

<button id="reload">reload</button>
```

I tried it with a first version of __`module_example.py`__

```python
class Klass:

    def __init__(self):
        print('v0')
````

Before hitting the "reload" button I changed the value inside `__init__`, the new value was printed in the console.

**Comment by lovasb** [comment]
Dear @PierreQuentel ,

Thanks for the answer. This solution is what I already tried, without any result. When I do the same way, I get module spec error:

```
brython.min.js:1 Traceback (most recent call last):
  File http://localhost:8000/__main__ line 11, in _reload
    reload(module_example)
  File VFS.importlib/__init__.py line 174, in reload
    del _RELOADING[name]
ModuleNotFoundError: spec not found for the module 'module_example'
```

I created a small PET project, which shows the error.
[reload_example.zip](https://github.com/brython-dev/brython/files/5761680/reload_example.zip)

When I run this script in CPython, it works:

```
from brython import module_example

k = module_example.Klass()
print(k.value)

from importlib import reload
reload(module_example)
```

Can you help me pleas, what I'm doing wrong?

**Comment by iansparks** [comment]
Hi @lovasb you are using the latest release and I think @PierreQuentel must be using the latest from master. He fixed a problem with importlib I reported a few weeks ago but maybe it is not in the latest release. If you use these script imports is it fixed for you?

```
        <script src="https://raw.githack.com/brython-dev/brython/master/www/src/brython.js"></script>
        <script src="https://raw.githack.com/brython-dev/brython/master/www/src/brython_stdlib.js"></script>
```
?

**Comment by lovasb** [comment]
Thank you @iansparks ! Now it's working! :+1:
