### ISSUE TITLE
Is this a closure bug?

### ISSUE THREAD

**Issue by ed2050** [brython-dev/brython#1570]
I'm honestly not sure.  Take the following code:

```
for x in [1,2] : 
    window.setTimeout (lambda : console.log ('got %s' % x), x * 100)
```

I expect that to print "got 1  got2".  Instead it prints "got 2  got 2".  It seems the value of x isn't saved in the lambda closure.  The callback somehow uses the same value of x twice.

Tried it on current live console, running 3.9.0.  Is this a bug?

**Comment by ed2050** [comment]
Update: Apparently it's not a bug.  Closures save a reference not a value, even for primitive types like int.  So when the reference `x` gets updated in parent scope, the later-running lambda picks up the changes.

The following code prints "got 1 got 2" as expected.  An extra level of indirection "fixes" the issue, if you don't want the behavior above.

```
    for x in [1, 2] :
        def wrapper (y) :
            return lambda : log ('got %s' % y)
        func = wrapper (x)
        window.setTimeout (func, x * 100)
```

**Comment by PierreQuentel** [comment]
I am closing the issue then. Thanks for the report anyway !
