### ISSUE TITLE
async f-string doesn't see the correct value of a global variable

### ISSUE THREAD

**Issue by Kodiologist** [brython-dev/brython#1571]
```
Brython 3.9.0 on Netscape 5.0 (X11)
>>> from browser import aio

n = 0
l = []

async def f():
    global n
    n = 0
    async def g():
        global n
        n += 1
        l.append(f'{n}')
    for p in range(3):
        await g()

aio.run(f())

>>> l
['1', '0', '0']
```

By contrast, if you replace `f'{n}'` with `str(n)`, the result is `['1', '2', '3']`, as expected. And the version with `f'{n}'` works with `asyncio` on CPython.

**Comment by PierreQuentel** [comment]
@Kodiologist Thanks for the report, and sorry for the very late fix :-(

**Comment by Kodiologist** [comment]
No problem. I've reported bugs to projects that have gone unfixed for over a decade, so if the bug gets fixed at all, that's a success in my book.
