### ISSUE TITLE
importlib.import_module breaks on already loaded modules

### ISSUE THREAD

**Issue by ShaneFarrell** [brython-dev/brython#158]
The first time importlib.import_module is called, it correctly returns the module. However it is called on a module that's already loaded it returns a "ref" object, which does not play nicely with brython.

Calling the built in __import__ on an already loaded module works fine.

Calling importlib's __import__ seems to have the same problem as import_module. So I'm guessing it's really a problem with that implementation.

I also just noticed that the built in __import__ actually functions like import_module and not as it's supposed to. In the case of __import__("os.path") it should be returning os, not path. This may be what is breaking importlib.

**Comment by ShaneFarrell** [comment]
Actually I noticed that importlib also seems to be missing things like importlib.machinery.all_suffixes()
This function was added in Python 3.3, so maybe the module is out of date.

**Comment by olemis** [comment]
@ShaneFarrell I'll appreciate if you could review [pull request 221](https://github.com/brython-dev/brython/pull/221) . In there `__import__()` has been implemented according to specs . Maybe this makes the original issue go away . The upgrade of importlib source code is something I leave to the consideration of @PierreQuentel and @earney . Exposure in importlib of built-in machinery objects will be implemented in #192 .
