### ISSUE TITLE
Creating a package via brython-cli fails

### ISSUE THREAD

**Issue by petko10** [brython-dev/brython#1580]
I just tried creating a brython package for a module I intend to use, but even with a minimal module (empty `test/__init__.py`) I get:
```
Traceback (most recent call last):
  File "/home/p10/.local/bin/brython-cli", line 33, in <module>
    sys.exit(load_entry_point('brython==3.9.1', 'console_scripts', 'brython-cli')())
  File "/home/p10/.local/lib/python3.9/site-packages/brython/__main__.py", line 162, in main
    make_package.make(package_name, os.getcwd())
  File "/home/p10/.local/lib/python3.9/site-packages/brython/make_package.py", line 92, in make
    tree = ast.parse(f.read())
  File "/usr/lib/python3.9/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 86
    except ParseError, e:
                     ^
SyntaxError: invalid syntax
```
That's with brython 3.9.1 and calling `brython-cli --make_package test`
Am I doing something wrong or is that a bug?

**Comment by PierreQuentel** [comment]
@petko10 
I could not reproduce the bug with a minimal package (empty file in `test/__init__.py`).

It seems that in the folder where you execute `brython-cli` there is a Python script written in Python 2.x. Can you check ?

If it it the case, I should probably add a more explicit error message when this happens.

**Comment by petko10** [comment]
@PierreQuentel 
It's probably something in my environment, sorry for the false alarm. I ran it in pycharm and it works without issue.

I deleted my `$HOME/.local/lib/python3.8` and a virtualenv `.local/share/virtualenvs/brython-vctiegzg` (I don't know by what process it was created) and now brython-cli works ok via the terminal too. I'm not sure what the problem was, exactly.
