### ISSUE TITLE
Cannot read property '$nat' of undefined

### ISSUE THREAD

**Issue by danijar** [brython-dev/brython#1581]
I'm getting this error message with Brython 3.9.0. The web application uses ShareDB with ReconnectingWebSocket. Unfortunately, the code base has become too large for me to create a minimal reproducing example. Do you have any idea how this error can come about and how to get a more informative error message from it? Thanks!

```
bundle.js:23273 Uncaught TypeError: Cannot read property '$nat' of undefined
    at _error14 (eval at run_py (brython.js:9481), <anonymous>:1483:48)
    at method (brython.js:5584)
    at bundle.js:28880
    at Array.forEach (<anonymous>)
    at Object.exports.callEach (bundle.js:28878)
    at Doc._clearInflightOp (bundle.js:27529)
    at Doc._opAcknowledged (bundle.js:27454)
    at Doc._handleOp (bundle.js:26851)
    at Connection.handleMessage (bundle.js:25968)
    at ReconnectingWebSocket.socket.onmessage (bundle.js:25865)
```

The corresponding code in the ReconnectingWebSocket package is this:

```js
  socket.onmessage = function(event) {
    try {
      var data = (typeof event.data === 'string') ?
        JSON.parse(event.data) : event.data;
    } catch (err) {
      logger.warn('Failed to parse message', event);
      return;
    }

    if (connection.debug) logger.info('RECV', JSON.stringify(data));

    var request = {data: data};
    connection.emit('receive', request);
    if (!request.data) return;

    try {
      connection.handleMessage(request.data);  // Error on this line
    } catch (err) {
      process.nextTick(function() {
        connection.emit('error', err);
      });
    }
  };
```

**Comment by danijar** [comment]
After further investigation, we found that brython@3.9.0 works fine but brython@3.9.1 gives the error above.

**Comment by PierreQuentel** [comment]
This error message happens when the Javascript `undefined` is passed as argument to a Python function. I would suggest that you check where this is the case.

**Comment by danijar** [comment]
Thanks, that's good to know. Why does Brython not convert the argument to `None` in that case?

**Comment by PierreQuentel** [comment]
In Javascript, if an argument is missing, it is converted to undefined.

```javascript
function f(x){
  return x
}
f() // undefined
f(undefined) // unedefined
```

In Python, it raises an exception.

```python
def f(x):
    return x

f(None) # None
f() # exception
```

Specifically, to explain the exception you get, Python code like

```python
f(x, y=2, z=3)
```

is converted to Javascript by

```javascript
f(x, {$nat: 'kw', kw: {y: 2, z: 3}})
```

The Javascript function that translates the Python function `f()` tests if there are keyword arguments with code like

```javascript
if(arguments.length > 0 && arguments[arguments.length - 1].$nat == 'kw')
```

This is ok when the function is called by a Python program, because we are sure that the last argument can't be Javascript `undefined`. 

When it is called by a Javascript function that doesn't pass any argument, you don't get the exception. But if it is called by a Javascript function that sends `undefined` as its last argument, it fails.

**Comment by danijar** [comment]
Okay so this error can only occur if a Python function is called by a JavaScript function? For example an event handler that's passed to a JavaScript objective like a DOM node or websocket.

From your explanation, it seems like the bug would be in this line. I understand it's just example code. But shouldn't this check whether `arguments[arguments.length - 1]` is undefined and in that case send `None` as the last positional argument to the Python function?

```js
if(arguments.length > 0 && arguments[arguments.length - 1].$nat == 'kw')
```

**Comment by PierreQuentel** [comment]
The best option would be to modify the Javascript code to test that it doesn't send `undefined` to a Python function.

In the commit referenced above, however, I have modified the handling of function arguments to convert `undefined` to the attribute `UNDEFINED` of the builtin module __`javascript`__ (this is more explicit that silently converting to `None`). 

It doesn't seem to break anything nor slow down execution, but for the moment I won't document this feature and I don't promise it will remain in future versions if I realize that it causes problems.

**Comment by danijar** [comment]
Thanks! Just to be clear, when you say the best solution would be to modify the JavaScript, do you mean the JavaScript generated for our Python callback or the third-party JavaScript that receives our callback? Because the later is often out of our control.

**Comment by PierreQuentel** [comment]
I meant the Javascript code that calls a Python function.

**Comment by danijar** [comment]
The problem with that is that as a programmer I can't patch all the JavaScript dependencies I'm using in a project. My understanding is that passing undefined is valid JavaScript code, right? In that case, wouldn't it make sense that Brython knows how to deal with it rather than throwing an internal error message?

**Comment by PierreQuentel** [comment]
> wouldn't it make sense that Brython knows how to deal with it rather than throwing an internal error message?

Isn't it what the commit above does ?

**Comment by danijar** [comment]
Cool, got it!
