### ISSUE TITLE
Can IndexedDB be used by Brython code?

### ISSUE THREAD

**Issue by kmindspark** [brython-dev/brython#1583]
I need to read IndexedDB data from inside a brython webworker which will have data written to it by javascript. Would this be possible in brython? I noticed there is an indexed_db.py module but haven't found any documentation for it.

**Comment by PierreQuentel** [comment]
There is an [example in the gallery](https://www.brython.info/gallery/library.html), did you see it ?

**Comment by kmindspark** [comment]
Oh, I did not see it. Thank you for pointing me there. A follow-up, is it possible to fetch objects in webworkers? I notice that to get the IndexedDB object you do window.indexedDB, but that wouldn't be possible with webworkers right? The JS version of IndexedDB is able to be used by webworkers.

**Comment by PierreQuentel** [comment]
Yes, you can use indexedDB in a webworker; you just have to replace `window` by `self`.

I have added a [gist](https://gist.github.com/PierreQuentel/f4212409b2aa4826409dc07bc179f2b3) with an example that combines webworkers and indexedDB. Hope this helps :-)

**Comment by kmindspark** [comment]
Thanks, very kind of you!
