### ISSUE TITLE
Question: Using custom modules from JS code via Brython

### ISSUE THREAD

**Issue by v-ko** [brython-dev/brython#1584]
Hello (again :), I hope I'm not becoming a nuisance in the Issues section),  I don't have posting access in the Google Group, so I'll ask here. Feel free to remove the issue if that's inappropriate.

Context:
I'm making an application for note organization, that I really want to be python based. The desktop frontend is written with PySide2 and I've taken inspiration from the Clear Architecture book, so entities, usecases, storage and GUI framework code/classes are mostly decoupled. Since I wan't to have web app, server, mobile apps, etc at some point, but still have as little duplication of the "business logic" - the idea is to have entities (notes, pages), the interface for their modification (e.g. CRUD) and the usecases (i.e. actions - translating user input to visual component property/state changes) written only in python. And to have the ability to implement GUI components in PySide2, JS/HTML (e.g. React) and any other platform that can use a python interface, without rewriting the rest of the code. I firstly looked at Transcrypt but it was lacking some stdlib modules and couldn't handle some python syntax, that I did not want to part with. So finding Brython was great.

The problem is, that now that I've started trying the setup out - I can't find documentation (or online info) about some of the questions I've ran into:
- How to access methods of Brython objects? I've found a solution on StackOverflow that says the model is as follows: `result = brython_obj.__class__.method_name(brython_obj, arg1, arg2)` , but that seems to not be very elegant. Is that the way by design? And if so - why not to map brython object method calls to the JS object?
- How to call functions with **kwargs? Trying this out:
```
from browser import window

def test_func(**kwargs):
	for a, v in kwargs.items():
		print(v)

window.test_func = test_func
```
I get a cryptic error in the JS console both when calling either `test_func(1, 'foo')` or `test_func({arg1: 1})`:
```
Uncaught Error
    at Object._b_.TypeError.$factory (eval at $make_exc (brython.js:8129), <anonymous>:145:327)
    at Object.$B.args (brython.js:6074)
    at test_func4 (eval at $B.loop (brython.js:5457), <anonymous>:242:53)
    at <anonymous>:1:1
```

- Is using a python module from JS an overall priority for the project? I get that the idea is to replace JS, but before a stable ecosystem forms two way interoperability seems vital.

**Comment by moepnse** [comment]
Hello :relaxed:

You should reconsider your approach. I guess you can solve this in pure Brython as well.

Nevertheless... I'll try to answer your question. Perhaps @PierreQuentel will answer you too. He can give you a more qualitative answer.

### Approach
I used the `py2src` function from the `javascript` modul to understand how `Brython` works. See: https://brython.info/static_doc/en/javascript.html
```python
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>py2src</title>

        <script src="https://raw.githack.com/brython-dev/brython/master/www/src/brython.js"></script>
        <script src="https://raw.githack.com/brython-dev/brython/master/www/src/brython_stdlib.js"></script>

        <script type="text/python">
from browser import console
import javascript

py_src = """def test(**kwargs):
    pass

test(a="1")
"""
console.debug(javascript.py2js(py_src))

        </script>
    </head>
    <body onload="brython({debug: 1});">
    </body>
</html>
```
Leads to:
```javascript
var $B = __BRYTHON__;
var _b_ = __BRYTHON__.builtins;
var $locals = $locals___main__2
$locals___main__2.__package__ = ""
$locals.__annotations__ = $B.empty_dict()
var $top_frame = ["__main__2", $locals___main__2, "__main__2", $locals___main__2]
$locals.$f_trace = $B.enter_frame($top_frame)
var $stack_length = $B.frames_stack.length;
try{
    ;$locals.$line_info = "1,__main__2";if($locals.$f_trace !== _b_.None){$B.trace_line()};_b_.None;
    var test$0 = function($defaults){function test0(){
        var $locals___main__2_test_3 = {},
            $locals = $locals___main__2_test_3;
        $locals___main__2_test_3 = $locals = $B.args("test", 0, {}, [], arguments, $defaults, null, "kwargs");
        $locals.$line_info = "1,__main__2"
        var $top_frame=["__main__2_test_3",$locals,"__main__2", $locals___main__2, test0]
        $locals.$f_trace = $B.enter_frame($top_frame)
        var $stack_length = $B.frames_stack.length;
        try{
            $B.js_this = this;
            ;$locals.$line_info = "2,__main__2";if($locals.$f_trace !== _b_.None){$B.trace_line()};_b_.None;
            void(0);
            if($locals.$f_trace !== _b_.None){
                $B.trace_return(_b_.None)
                }
                $B.leave_frame({$locals});return _b_.None
        }
        catch(err){
            $B.set_exc(err)
            if($locals.$f_trace !== _b_.None){$locals.$f_trace = $B.trace_exception()}
            $B.leave_frame({$locals});throw err
        }
    }
    test0.$is_func = true
    test0.$infos = {
        __name__:"test",
        __qualname__:"test",
        __defaults__ : _b_.None,
        __kwdefaults__ : _b_.None,
        __annotations__: {},
        __dict__: $B.empty_dict(),
        __doc__: _b_.None,
        __module__ : "__main__2",
        __code__:{
            co_argcount:0,
            co_filename:$locals___main__2["__file__"] || "<string>",
            co_firstlineno:1,
            co_flags:75,
            co_freevars: [],
            co_kwonlyargcount:0,
            co_name: "test",
            co_nlocals: 1,
            co_posonlyargcount: 0,
            co_varnames: $B.fast_tuple(["kwargs"])
        }
    };_b_.None;
    return test0}
    $locals___main__2["test"] = test$0({})
    $locals___main__2["test"].$set_defaults = function(value){return $locals___main__2["test"] = test$0(value)}
    ;$locals.$line_info = "4,__main__2";if($locals.$f_trace !== _b_.None){$B.trace_line()};_b_.None;
    $B.$call($locals___main__2["test"])({$nat:"kw",kw:{a:"1"}});
    $B.leave_frame({$locals, value: _b_.None})
}
catch(err){
    $B.leave_frame({$locals, value: _b_.None})
    throw err
}
```

### Solution & Demo

`__BRYTHON__.$call`

#### Demo

```python
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Demo</title>

        <script src="https://raw.githack.com/brython-dev/brython/master/www/src/brython.js"></script>
        <script src="https://raw.githack.com/brython-dev/brython/master/www/src/brython_stdlib.js"></script>
        
        <script>
function clicked() {
    __BRYTHON__.$call(test)({$nat:"kw",kw:{a:"1"}});
}
        </script>

        <script type="text/python">
from browser import window, console

def test(**kwargs):
    console.debug("kwargs:", kwargs)

window.test = test

        </script>
    </head>
    <body onload="brython({debug: 1});">
        <button onclick="clicked()">Click Me!</button>
    </body>
</html>
```

### Related Question
Some time ago I've asked a similar question: https://github.com/brython-dev/brython/issues/1489

**Comment by petko10** [comment]
Thank you for the explanation! I've, too, come to the conclusion that using only python/brython scripts will be the way to go, but I'm also curious whether implementing a Brython object wrapper class and a factory for those is feasable. E.g. in script:python: `brython.javascript.expose_object_with_wrapper(py_object[, scope/js_obj_parent?])`. And for that wrapper to have a stable interface for calling and getting args/return values. As I'm writing that I realize there's a lot of corner cases to be covered, so such an interface would require quite some work. 

Anyway, it would be nice to have a section in the documentation regarding that topic with a pointer that using brython only is the right approach and maybe some explanation/examples.

**Comment by PierreQuentel** [comment]
Hello,

I guess you didn't expect an answer after such a long time, but in commit 8e8d0a59edd925acabda4a09fccda6deff2334fb I have added a function in module `javascript` that makes it possible to import a module written in Javascript. It is described in the [documentation](https://github.com/brython-dev/brython/blob/master/www/doc/en/javascript.md).

I am closing the issue, but you can still comment if you have feedback on this new feature.

**Comment by v-ko** [comment]
Hi, thanks for the pointer. But the question was about using brython objects/functions (defined in python) in the js code, not the other way around. I didn't word the title very well.
 As far as I understood though (from a discussion in the group, if I remember correctly) - the intended use of brython is with python scripting only and no js calls (to e.g. a python library). I still think it would be nice to have that option (mainly for easing the transition into using brython). But I don't know if it would be feasible or worthwhile to implement.

**Comment by v-ko** [comment]
@PierreQuentel I just saw that pyodide has a `create_proxy` function, that allows using a python function in JS. Would it be feasible to implement something like that for Brython?

**Comment by PierreQuentel** [comment]
This is not necessary in Brython, where callbacks use a different (and hopefully more pythonic) syntax from standard DOM API. 

The [pyscript example](https://www.jhanley.com/pyscript-javascript-callbacks/) with `create_proxy` 

```python
from js import document
from pyodide import create_proxy
 
count = 0
 
def button_click(event):
	global count
 
	count += 1
 
	document.getElementById("msg").innerHTML = 'Button Clicked ' + str(count)
 
def setup():
	# The page is ready, clear the "page loading"
	document.getElementById("msg").innerHTML = ''
 
	# Create a JsProxy for the callback function
	click_proxy = create_proxy(button_click)
 
	# Set the listener to the callback
	e = document.getElementById("button")
	e.addEventListener("click", click_proxy)
 
setup()
```

 is written this way in Brython:

```python
from browser import document

count = 0

def button_click(event):
    global count
    count += 1
    document["msg"].innerHTML = f'Button Clicked {count}'

def setup():
    # The page is ready, clear the "page loading"
    document["msg"].clear()
    document["button"].bind("click", button_click)

setup()
```
The event callback is defined with method `bind()` of DOM nodes, which takes a Python function as argument: there is no need to define a Python function, then transform it into a function that probably transforms the `event` argument into an object that can be used by the Python function `button_click()` : all this is completely transparent for the developer in Brython.

By the way, I don't understand why in pyodide / pyscript the name `document` is imported from a module called `js` : `document` is a part of the DOM API, which is language-independant.

**Comment by v-ko** [comment]
I agree that the pythonic syntax is more elegant, but as far as I understood it - the create_proxy function enables the use of a python function from JS code. I get that brython intends to replace JS, not inter-operate with it. But As I mentioned earlier - I believe two-way interaction (JS<>Python) is going to be an important feature for devs/teams that want to transition to using brython.
