### ISSUE TITLE
Documentation of set_timeout needs updating

### ISSUE THREAD

**Issue by andy31lewis** [brython-dev/brython#1586]
Hello again

Not a software bug - just a little documentation problem.

The browser.timer documentation says:
"`set_timeout(function,ms)`
runs the `function` after `ms` milliseconds. `function` takes no argument. "

But `function` can take arguments, for example:
```python
from browser.timer import set_timeout

def f(x,y):
    print(x*y)
    
print("Starting")
set_timeout(f, 5000, 100, 2)
```
Here the extra arguments `100` and `2` to `set_timeout` are passed to `f` as `x` and `y`, so that after a 5 second delay the output is `200`.

Thanks as ever,

Andy

**Comment by andy31lewis** [comment]
However, what I have also just discovered is that these arguments are converted to Javascript objects and back again during the process of calling the timeout, so they have to be suitable for undergoing this treatment, as described on the "Using Javascript objects" page in the documentation.

So numbers, strings, booleans, DOMNodes, DOMEvents and lists of these objects arrive at the function unchanged but dictionaries need a line like `d = d.to_dict()` at the start of the function to restore them to their original form.

Other types of object (including instances of user-defined classes) arrive as JSObjects which can't be easily reconstituted into the form in which they were originally sent.

I hope this information is useful to somebody - it has been to me.

Andy

**Comment by PierreQuentel** [comment]
Thanks Andy for the report, and sorry for the late answer, I am almost 100% on the Javascript version of the Python regular expression engine - great fun, but not the easiest piece of code I have ever written...
