### ISSUE TITLE
SharedArrayBuffer implementation?

### ISSUE THREAD

**Issue by kmindspark** [brython-dev/brython#1588]
I was wondering if there is a way to achieve what is possible with SharedArrayBuffer in Brython? I need a Brython webworker to be able to access the same memory as the main thread. Thank you.

**Comment by PierreQuentel** [comment]
@kmindspark 
I didn't test, but I suppose that, as for all Javascript objects, you can access it through `window.SharedArrayBuffer` in the main script and `self.SharedArrayBuffer` in workers.

**Comment by kmindspark** [comment]
Yeah, it ended up working, I had a conversation with someone in the Google Group. The ability to access any Javascript object is a lifesaver. Thanks!
