### ISSUE TITLE
Add typescript types .d.ts for js API ?

### ISSUE THREAD

**Issue by Lyoko-Jeremie** [brython-dev/brython#1589]
can we add the `.d.ts` for typescript users ?

seems like It won't be too complicated .

**Comment by PierreQuentel** [comment]
What do you mean by "add the .d.ts" ?

**Comment by Lyoko-Jeremie** [comment]
it's a API describ file for typescript user/compiler .
user can add it to project to let VSCode or IDEA have type-check or intellience hint when they use the JS API .

in normal, it will named like `brython.d.ts` or similar in a project .

**Comment by Lyoko-Jeremie** [comment]
the detail you can see from here :

https://stackoverflow.com/questions/21247278/about-d-ts-in-typescript

https://stackoverflow.com/questions/50463990/what-are-d-ts-files-for

https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html

https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-d-ts.html

**Comment by PierreQuentel** [comment]
Can you make a Pull Request to generate what is required ?

**Comment by Lyoko-Jeremie** [comment]
i will do it later ~

**Comment by PierreQuentel** [comment]
I am closing the issue. When the PR is ready I will look into it.
Thanks !
