### ISSUE TITLE
Differences in eval behavior between CPython and Brython

### ISSUE THREAD

**Issue by mwchase** [brython-dev/brython#1597]
First off, sorry if these behaviors are intended, but I couldn't find any documentation on these differences.

The namespace arguments to `eval(code, globals, locals)` are treated differently in CPython and Brython.
I've included several snippets that show this off; they assume that the collections module is imported.

In CPython, the `globals` argument must be an instance of a dict subclass (usually dict). If the subclass defines the `__missing__` or overrides `__getitem__`, those changes are respected.
In Brython, the `globals` argument must be exactly of type `dict`.
Try for example `eval("a", collections.defaultdict(list))`
In CPython, this produces an empty list, and in Brython, it raises an exception.

In CPython, the `local` argument can be any mutable mapping. (I assume it has to be mutable, maybe it doesn't, it's not important.) Its implementation of the mapping methods is respected.
In Brython, the `locals`argument can be any mutable mapping. (Same caveat applies.) I *think* its values are ignored unless it's a `dict` subclass, and it appears to ignore at least the `__missing__` method. Practically speaking, there is little point in passing an argument that is not of type `dict`.
Try for example `eval("a", {}, collections.defaultdict(list))`, `eval("a", {}, collections.defaultdict(list, a=1))`, and `eval("a", {}, collections.UserDict(a=1))`.
In CPython, the first expression produces an empty list, and the third expression the number 1.
In Brython, the first and third expressions raise an exception.

**Comment by PierreQuentel** [comment]
Thanks for the report @mwchase !

I did not change the current behaviour for `globals` : the documentation explicitely says that it must be a dictionary, not a subclass. I saw that this constraint has been removed in Python3.3, but this is not documented and I prefer to stick to the official language specification.
