### ISSUE TITLE
defaultdict's type detection in Brython seems static

### ISSUE THREAD

**Issue by rayluo** [brython-dev/brython#1598]
Hi Pierre, I found another subtle difference between Brython and Cython. :-)

The following snippet is valid in Cython:

```python
from collections import defaultdict
d = defaultdict(int)  # Its default value type would be int
d.setdefault("bar", []).extend([123])  # However, it can still be explicitly assign a different default type at run-time
print(d["bar"])  # Cython would output [123]
```

In Brython, the interpretor would report error on line 3:

    AttributeError: 'int' object has no attribute 'extend'

But there is a workaround. Replacing the `setdefault(...)` by an old-school `if` would work:

```python
d = defaultdict(int)

#d.setdefault("bar", []).extend([123])

if "bar" not in d:
    d["bar"] = []
d["bar"].extend([123])  # Brython would not complain
```

So, this is not an urgent bug. I'll leave it to you to decide when to fix it. :-)

Thanks again for this project!

**Comment by rayluo** [comment]
Thanks for the quick work! Does that commit fix BOTH this `defaultdict` AND the `configparser` issue?

**Comment by PierreQuentel** [comment]
Only this issue, sorry...

**Comment by rayluo** [comment]
Only fixing this issue is perfectly fine. I was just confused because the commit also modified some files on `configparser` and `re`. :-)

And, I also tested it with the latest master branch. This fix works! Thanks again.
