### ISSUE TITLE
Document that using a string as an HTML element parses HTML instead of creating a text node

### ISSUE THREAD

**Issue by Kodiologist** [brython-dev/brython#1600]
I expected `html.P("not really <b>bold</b>")` to render as "not really \<b\>bold\</b\>", without parsing the HTML, as JavaScript's `document.createTextNode` does. It doesn't. If you don't want to change this behavior, which I think is dangerous, it should be documented prominently. I hope it's not already in the documentation somwhere and I missed it. The documentation just says "*content* is the child node of the the object ; it can be a Python object such as a string, a number, etc., or an instance of another class in the `html` module".

**Comment by PierreQuentel** [comment]
I'm afraid I disagree with your expectation. Passing a string with HTML markup suggests that it should be rendered as HTML, not as text.

If you want to set the text content:
```
p = html.P()
p.text = "not really <b>bold</b>"
```

For clarity, I have updated the document of module __`browser.html`__ in commit 9bc1dfcce023dfb60994c340c5d11137280baed9

**Comment by Kodiologist** [comment]
Thanks for the docs change. My strategy is to set `T = document.createTextNode` so I can say stuff like`html.P(T(user_input))`.
