### ISSUE TITLE
little error in code on homepage

### ISSUE THREAD

**Issue by aliasal** [brython-dev/brython#1604]
On the page 
https://brython.info/static_doc/en/intro.html
there is the simple example:

```
<html>
<head>
<script src="/brython.js"></script>
</head>
<body onload="brython()">
<script type="text/python">

from browser import document
from browser.widgets.dialog import InfoDialog

def click(ev):
    InfoDialog("Hello", f"Hello, {document['zone'].value} !")

# bind event 'click' on button to function echo
document["echo"].bind("click", click)

</script>
<input id="zone">
<button id="mybutton">click !</button>
</body>
</html>
```

This code gives an KeyError because the button-id is "mybutton" not "echo".

The embedded code on the page works because the button is named correctly.

**Comment by PierreQuentel** [comment]
Many thanks @aliasal ! This must have been present for ages and nobody ever reported it...
