### ISSUE TITLE
In Brython editor: Exception: <Javascript TypeError>: mode.search is not a function

### ISSUE THREAD

**Issue by lborgman** [brython-dev/brython#1606]
When trying to run some Python code in the editor I got the error in the subject line. 

The Python code and more details are available here: 

Brython and stickytape https://groups.google.com/g/brython/c/Kr0KfiiXGuo/m/F1GisJvKAAAJ

**Comment by lborgman** [comment]
Looking in Chrome Dev Tools I see that `mode` has the value 34050.

**Comment by lborgman** [comment]
I took a closer look at what happens. The problem is that StickyTape's way of creating a single Python file can not be directly used in Brython. 

StickyTape works by saving the import information and then mirror this in a temporary directory when the single Python file is run.

This is conceptually a simple and reasonable implementation AFAICS and it seems to work very well in the Python context But this can of course not work directly in the web browser context.

However it looks to me that this mirroring should not be to difficult to implement in Brython (since the import function structure is already available in Brython - if I understand it correctly). And I guess this would be very useful for speeding up Brython.

The crucial lines in the StickyTape single Python file output are these:

```python
import contextlib as __stickytape_contextlib

@__stickytape_contextlib.contextmanager
def __stickytape_temporary_dir():
    import tempfile
    import shutil
    dir_path = tempfile.mkdtemp()
    try:
        yield dir_path
    finally:
        shutil.rmtree(dir_path)

with __stickytape_temporary_dir() as __stickytape_working_dir:
    def __stickytape_write_module(path, contents):
        import os, os.path

        def make_package(path):
            parts = path.split("/")
            partial_path = __stickytape_working_dir
            for part in parts:
                partial_path = os.path.join(partial_path, part)
                if not os.path.exists(partial_path):
                    os.mkdir(partial_path)
                    with open(os.path.join(partial_path, "__init__.py"), "wb") as f:
                        f.write(b"\n")

        make_package(os.path.dirname(path))

        full_path = os.path.join(__stickytape_working_dir, path)
        with open(full_path, "wb") as module_file:
            module_file.write(contents)

    import sys as __stickytape_sys
    __stickytape_sys.path.insert(0, __stickytape_working_dir)
```

The imported modules are represented in the single Python file by lines that writes to the temporary directory tree:

```python
__stickytape_write_module(module_temp_path, module_code)
```

And the temporary files are then used by a Python import statement in the single Python file.

**Comment by PierreQuentel** [comment]
Looking at what stickytape does, I wonder if [Brython packages](https://www.brython.info/static_doc/en/brython-packages.html) could not be the solution.
