### ISSUE TITLE
Custom import in brython console

### ISSUE THREAD

**Issue by jha929** [brython-dev/brython#1613]
Hi, I'm trying to add a custom module so that I can import the module in the console (as below).
<img width="1131" alt="Screen Shot 2021-02-17 at 10 06 04 PM" src="https://user-images.githubusercontent.com/10961008/108208807-dd693b80-716c-11eb-8014-d15561d5ebcb.png">

[The link](https://brython.info/static_doc/en/import.html) describes how to perform such task on an HTML file but on a console.

Has anyone faced the same issue? Thanks in advance.

**Comment by PierreQuentel** [comment]
By default, the module must be in the same directory as the console HTML page.
You can customize the modules:
1. the usual Python way, by adding paths to `sys.path`
2. by setting the option `pythonpath` of function `brython()` to the list of paths where modules should be searched, eg

```xml
<body onload="brython({pythonpath: ['/custom_path']})">
```

**Comment by PierreQuentel** [comment]
I am closing the issue, hoping that the answer above is enough. If not, don't hesitate to reopen it.

**Comment by jha929** [comment]
Thanks for your help, I simply wrote my custom module as `.py` in the same directory with `index.html`
