### ISSUE TITLE
There is no Brython way to convert method using callback to async

### ISSUE THREAD

**Issue by goffi-contrib** [brython-dev/brython#1614]
Hello,

there is no way in Brython (beside using javascript) to convert a callback method based to an async one. In asyncio we have `Future` for that, `Deferred` with Twisted and `Promise` in javascript, we would need something something equivalent in Brython (re-using `Future` with a similar semantic would help in porting asyncio based code).

The idea is to be able to convert something like the following method to an async one:
```python
def some_function_with_callbacks(some_parameter, callback, errback):
    try:
        result = do_something_useful(some_parameter)
    except Exception as e:
        errback(e)
    else:
        callback(result)
```

Thanks!

**Comment by PierreQuentel** [comment]
Sorry, I don't understand what "convert a callback method based to an async one" means. Can you give more information and examples ? Have you tried using `aio.event` ?

**Comment by goffi-contrib** [comment]
Hello Pierre,

the goal is to convert something similar to above function to an async one, in asyncio you would use Future: https://docs.python.org/3/library/asyncio-future.html (`set_result` is called when the result is available, `set_exception` if something goes wrong, and you can await on the method).
It's doable in Brython by using Javascript `Promise`, I'm currently doing it with something like that:
```python
import window, timer
    def some_callbacks_method(self, ok_cb, error_cb):
        def got_result():
            ok_cb("this is the result")
        try:
            timer.set_timeout(got_result, 2000)
        except Exception as e:
            error_cb(e)

    async def async_method(self):
        # this method can be used with await
        return window.Promise.new(
            lambda resolve_cb, reject_cb: self.some_callbacks_method(resolve_cb, reject_cb)
        )
```
We can now use `await` with `async_method`.

This is working, but it would be better to have a Pythonic way to do that, ideally with the same API as Future so we can easily port asyncio code.

Is it more clear?
Thanks!

**Comment by PierreQuentel** [comment]
I see, but what is the advantage compared to somehing like this, adapted from the __`asyncio.Future`__ example:
```python
from browser import aio

class Future:

    def set_value(self, value):
        self.value = value

    async def set_after(self, secs, value):
        try:
            await aio.sleep(secs)
            self.set_value(value)
        except:
            print("error")

    def __str__(self):
        return self.value

async def f():
    print("Hello...")
    fut = Future()
    await(fut.set_after(2, '...world'))
    print(fut)

aio.run(f())
```

**Comment by goffi-contrib** [comment]
I think there is a misunderstanding. I'm not trying to do a sleep, but to convert an existing API which is callback based to one which is async and so usable with `await`, `Future` is just glue to do that (same thing as Javascript `Promise` or Twisted `Deferred`).

In my example above, `some_callbacks_method` is callback based API that I already have and can't modify, `async_method` is a way to convert this method to an async one, so I can use it with `await`.

To give a more precise idea, in Brython an implementation could be like this:

```python
from browser import window, timer, aio

class Future:
    def __new__(cls, *args, **kwargs):
        methods = {}
        def executor(resolve_cb, reject_cb):
            methods["resolve"] = resolve_cb
            methods["reject"] = reject_cb
        promise = window.Promise.new(executor)
        promise._methods = methods
        promise.set_result = cls.set_result.__get__(promise)
        promise.set_exception = cls.set_exception.__get__(promise)
        return promise


    def set_result(self, value):
        self._methods["resolve"](value)

    def set_exception(self, exc):
        self._methods["reject"](exc)
        
async def async_test(fut):
    print("awaiting...")
    result = await fut
    print(f"future awaited, result: {result}")    
        
        
fut = Future()
timer.set_timeout(lambda: fut.set_result("timeout!"), 2000)
aio.run(async_test(fut))
```

I've tested in Brython console, it's working as expected

**Comment by goffi-contrib** [comment]
**note:** I can actually put this code in a pull request for `aio` module if you want.

**Comment by PierreQuentel** [comment]
> note: I can actually put this code in a pull request for aio module if you want.

Yes, that would be great ! Could you also write some documentation in the __`browser.aio`__ page ? (en français si tu préfères ;-)

**Comment by goffi-contrib** [comment]
@PierreQuentel sure I will, a bit later today cause I'm busy right now. Also I'm not sure if my implementation is well optimized (I'm don't know Brython internals enough to know if it would be better to replace the `method` dict by an other data structure for instance), but I guess that can be discussed on the PR directly.

Pas de problème, merci pour les réponses, je fais ça dès que possible, et je laisse le ticket ouvert jusqu'à ce que la PR soit mergée.

**Comment by PierreQuentel** [comment]
Ca marche, merci !

**Comment by goffi-contrib** [comment]
code has been merged, closing this ticket, thanks!
