### ISSUE TITLE
Namespace packages do not work

### ISSUE THREAD

**Issue by ShaneFarrell** [brython-dev/brython#162]
As per this PEP: https://www.python.org/dev/peps/pep-0420/

There is now the option not to include an __init__.py in a package in order to make it a namespace package. The nuances of this are explained in the PEP. Namespace packages are only looked for if a normal package can't be found, so it's not a performance hit for current code flows.

**Comment by olemis** [comment]
Brython is designed to work in the browser . Therefore the main blocker for me to move forward with this is to figure out (efficiently) whether a given URL path is actually an existing "folder" or not . The nuances mentioned in the PEP work fine for a file system (local or not) . Nonetheless this is not trivial in an HTTP client/server architecture .

Any hints ?

**Comment by githob605608886** [comment]
https://github.com/brython-dev/brython/issues/374

**Comment by PierreQuentel** [comment]
I am closing this old issue. If it's still valid please reopen it.
