### ISSUE TITLE
zip() doesn't implement the iterator interface

### ISSUE THREAD

**Issue by pamelafox** [brython-dev/brython#1621]
It appears that zip() doesn't implement the full iterator interface- 

```
english = ["one", "two", "three"]
español = ["uno", "dos", "tres"]
zip_iter = zip(english, español)
eng, esp = next(zip_iter)
print(eng, esp)
```

In https://brython.info/tests/editor.html, that results in:

Traceback (most recent call last):
  File https://brython.info/tests/editor.py, line 119, in run
    exec(src, ns)
  File <string>, line 4, in <module>
AttributeError: 'zip' object has no attribute '__next__'

It's fine if you wrap zip in iter(), but that should not be necessary since zip should return an iterator, and does so in standard Python.
<completed in  19.00 ms>

**Comment by PierreQuentel** [comment]
Thanks @pamelafox !
