### ISSUE TITLE
Globals seem to be broken on top of tree

### ISSUE THREAD

**Issue by JimmyWu2** [brython-dev/brython#1629]
I switched over to using the top of tree Brython and now I get errors when trying to access my global variables, where Javascript says they're undefined (and it's clearly trying to access them as locals instead of globals, despite being declared global.)

Cut down reproducing test case:

```
<html>

<head>
    <meta charset="utf-8">
    <script type="text/javascript"
        src="https://raw.githack.com/brython-dev/brython/master/www/src/brython.js">
    </script>
    <script type="text/javascript"
        src="https://raw.githack.com/brython-dev/brython/master/www/src/brython_stdlib.js">
    </script>
</head>

<body onload="brython()">

<style>
*{
    font-family: sans-serif;
    font-family: Monaco, monospace;
    font-weight: normal;
    font-size: 1.1em;
}
td{
    background-color: #ccc;
    padding: 10px 30px 10px 30px;
    border-radius: 0.2em;
    text-align: center;
    cursor: default;
    font-family: sans-serif;
}
}
</style>
<p id='topzone'> </p>
<script type="text/python">

from browser import document, html, alert
import random, time, itertools

myGlob = 0

def randomString():
    global myGlob
    
    htmlString = "myGlob = " + "{}".format(myGlob)

    return htmlString

def drawMain():
    stack = html.TABLE()
    stack <= (html.TR(html.TH(html.DIV(html.B(randomString()), id="rand"))))
    document["topzone"].clear()
    document["topzone"] <= stack

def drawStatus():
    calc = html.TABLE()
    calc <= html.TR(html.TH(html.DIV("myGlob = 0", id="theGlob"), colspan=3))
    document <= calc

def reaction(event):
    # Only continue if they pressed enter
    if(event.type == "keyup" and event.keyCode != 13):
        return
    global myGlob
    theGlob = document["theGlob"]

    input = document["input16"].value
    if(input == "1"):
        document["input16"].value = ""
        myGlob += 1
        theGlob.text = "myGlob = " + str(myGlob)
        drawMain()
    else:
        document["input16"].value = ""
        myGlob -= 2
        theGlob.text = "myGlob = " + str(myGlob)
        drawMain()

document["button16"].bind("click", reaction)
document["input16"].bind("keyup", reaction)

drawMain()
drawStatus()

</script>
<p id='bottomzone'> </p>
<div class="example" id="ex16">
    <p><input id="input16" autocomplete="off" value="">
    <button id="button16">Submit answer</button>
    <p><div id="zone16" class="zone"></div>
</div>

</body>

</html>
```

Error is:

> Javascript exception: TypeError: $locals.myGlob is undefined
>     reaction3 https://raw.githack.com/brython-dev/brython/master/www/src/brython.js line 5452 > Function:258
>     callback https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:13822
>     bind https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:13828
>     method https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5577
>     anonymous https://raw.githack.com/brython-dev/brython/master/www/src/brython.js line 5452 > Function:333
>     loop https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5452
>     inImported https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5435
>     loop https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5460
>     inImported https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5435
>     loop https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5460
>     inImported https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5435
>     loop https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5460
>     inImported https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5435
>     loop https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5460
>     inImported https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5435
>     loop https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5460
>     run_script https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5257
>     loop https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5460
>     onerror https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5416
>     idb_open https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5412
>     loop https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5460
>     _run_scripts https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5318
>     brython https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5241
>     onload file:///home/user/bla.html:1
> brython.js:8082:32
> Array(5) [ "_reaction_5", {…}, "", {…}, reaction3(event)
>  ]
> brython.js:8083:9
> test is js exc is recursion error TypeError: $locals.myGlob is undefined
>     reaction3 https://raw.githack.com/brython-dev/brython/master/www/src/brython.js line 5452 > Function:258
>     callback https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:13822
>     bind https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:13828
>     method https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5577
>     anonymous https://raw.githack.com/brython-dev/brython/master/www/src/brython.js line 5452 > Function:333
>     loop https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5452
>     inImported https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5435
>     loop https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5460
>     inImported https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5435
>     loop https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5460
>     inImported https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5435
>     loop https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5460
>     inImported https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5435
>     loop https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5460
>     inImported https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5435
>     loop https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5460
>     run_script https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5257
>     loop https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5460
>     onerror https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5416
>     idb_open https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5412
>     loop https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5460
>     _run_scripts https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5318
>     brython https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5241
>     onload file:///home/user/bla.html:1
>  TypeError: $locals.myGlob is undefined brython.js:8117:9
> recursion error ? false brython.js:8084:9
> test is js exc is recursion error TypeError: $locals.myGlob is undefined
>     reaction3 https://raw.githack.com/brython-dev/brython/master/www/src/brython.js line 5452 > Function:258
>     callback https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:13822
>     bind https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:13828
>     method https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5577
>     anonymous https://raw.githack.com/brython-dev/brython/master/www/src/brython.js line 5452 > Function:333
>     loop https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5452
>     inImported https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5435
>     loop https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5460
>     inImported https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5435
>     loop https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5460
>     inImported https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5435
>     loop https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5460
>     inImported https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5435
>     loop https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5460
>     inImported https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5435
>     loop https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5460
>     run_script https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5257
>     loop https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5460
>     onerror https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5416
>     idb_open https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5412
>     loop https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5460
>     _run_scripts https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5318
>     brython https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5241
>     onload file:///home/user/bla.html:1
>  TypeError: $locals.myGlob is undefined

**Comment by PierreQuentel** [comment]
Many thanks @JimmyWu2 ! It's a side effect of a change made a few weeks ago that nobody had noticed yet.
