### ISSUE TITLE
An app would hang if attempting "import nonexistent_module" from CDN

### ISSUE THREAD

**Issue by rayluo** [brython-dev/brython#1631]
An app would hang if attempting "import nonexistent_module" from CDN, due to uncaught error in `brython.js`. Is it possible to have brython raise an `ImportError` instead?

Repro:

* Content in `index.html`

  ```html
  ...
  <script src="https://cdnjs.cloudflare.com/ajax/libs/brython/3.9.1/brython.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/brython/3.9.1/brython_stdlib.min.js"></script>
  <script type="text/python" src="main.py"></script>
  ...
  ```

* Content in `main.py`

  ```python
  try:
      import optional_module
  except ImportError:
      print("That is fine")
  ```

Expects to see "That is fine" in the console.

What actually happened is that the app hangs, with the following output on the browser console. The first 2 or 3 lines are expected, but can Brython or javascript recover from a "Cross-Origin Request Blocked" request?

```
Error 404 means that Python module cowsay was not found at url http://localhost:8000/optional_module.py
Error 404 means that Python module cowsay was not found at url http://localhost:8000/__init__/optional_module.py
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://cdnjs.cloudflare.com/ajax/libs/brython/3.9.1/Lib/site-packages/optional_module.py?v=1615571704659. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
Javascript exception: DOMException: A network error occurred.
...
test is js exc is recursion error DOMException: A network error occurred. NetworkError: A network error occurred.
...
Uncaught Error: 
    $factory https://cdnjs.cloudflare.com/ajax/libs/brython/3.9.1/brython.min.js line 1 > eval:1
    loop https://cdnjs.cloudflare.com/ajax/libs/brython/3.9.1/brython.min.js:1
    onsuccess https://cdnjs.cloudflare.com/ajax/libs/brython/3.9.1/brython.min.js:1
    onsuccess https://cdnjs.cloudflare.com/ajax/libs/brython/3.9.1/brython.min.js:1
brython.min.js line 1 > eval:1:7500
    $factory https://cdnjs.cloudflare.com/ajax/libs/brython/3.9.1/brython.min.js line 1 > eval:1
    loop https://cdnjs.cloudflare.com/ajax/libs/brython/3.9.1/brython.min.js:1
    onsuccess https://cdnjs.cloudflare.com/ajax/libs/brython/3.9.1/brython.min.js:1
    onsuccess https://cdnjs.cloudflare.com/ajax/libs/brython/3.9.1/brython.min.js:1
```

**Comment by PierreQuentel** [comment]
Ray,

I understand the concern, but I don't think there is a solution. As explained in [this page](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors), CORS errors cannot be handled by Javascript in a try / except block.

**Comment by rayluo** [comment]
[That page](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors) only says that the error detail would not be available to javascript.

> Note: For security reasons, specifics about what went wrong with a CORS request are not available to JavaScript code. All the code knows is that an error occurred. The only way to determine what specifically went wrong is to look at the browser's console for details.

It does not mention whether the error can be handled by try/except block. That being said, if you actually tried (pun not intended) but couldn't not catch the error, then, C'est la vie. :-)  Feel free to close this issue in that case.

**Comment by PierreQuentel** [comment]
I did try this Javascript program:
```javascript
var url = "https://cdnjs.cloudflare.com/ajax/libs/brython/3.9.1/Lib/site-packages/optional_module.py?v=1615916897909"
var xhr = new XMLHttpRequest()
xhr.open('GET', url)
console.log("try")
try{
  xhr.send()
  console.log("no JS exception")
}catch(err){
  console.log("error", err)
}
```
The console prints this:
```
try
no JS exception
XHRGEThttps://cdnjs.cloudflare.com/ajax/libs/brython/3.9.1/Lib/site-packages/optional_module.py?v=1615916897909
CORS Missing Allow Origin

Blocage d’une requête multiorigines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://cdnjs.cloudflare.com/ajax/libs/brython/3.9.1/Lib/site-packages/optional_module.py?v=1615916897909. Raison : l’en-tête CORS « Access-Control-Allow-Origin » est manquant.
```

**Comment by rayluo** [comment]
Thanks for investigating. So we have to live with this known issue. C'est la vie.

**Comment by rayluo** [comment]
Interestingly, I notice that the `ImportError` can be caught now, and the `except` clause can be run. Last time @PierreQuentel and I both tested this issue 3 months ago, it did not work at that time. The only difference today is I run it with a newer version of browser. Just a FYI.
