### ISSUE TITLE
Reassigning built-in types fails silently

### ISSUE THREAD

**Issue by itsvs** [brython-dev/brython#1634]
In the Python 3 console, the following behavior can be produced:

```
>>> dict = {'a': 'A', 'b': 'B'}
>>> dict.get('a')
'A'
```

However, in Brython, the following behavior occurs instead:

```
>>> dict = {'a': 'A', 'b': 'B'}
>>> dict.get('a')
Traceback (most recent call last):
  File <string>, line 1, in <module>
TypeError: get missing 1 positional argument: 'key'
```

I'm not sure if this has been documented already, but I assume it is not intended for the assignment to execute but the subsequent lookup to fail.

**Comment by PierreQuentel** [comment]
Thanks for the report @itsvs !
The bug only occured in the interactive interpreter, not in scripts embedded in an HTML page.

**Comment by itsvs** [comment]
Interesting, thanks for the quick resolution!
