### ISSUE TITLE
How to Import Another Library like ArcPy into Document

### ISSUE THREAD

**Issue by Behseini** [brython-dev/brython#1635]
ArcPy is a Python module for interacting with ArcGIS tools. The module was developed by Esri, the company that makes ArcGIS. can you please let me know if it is possible to import the module  into script like 

    <script type="text/python">
        from browser import document
        import sys
        import arcpy
         
        sys.stdout = document
        print("Testing ArcPy")
    </script>
I already tried this but it is not working and looks like it is killing the application as even the print not working when importing ArcPy.

Thanks

**Comment by PierreQuentel** [comment]
Generally speaking, the way to use a third-party package is to install it with `pip`, then run `brython-cli add_package arcpy` and see if the import works - which should be the case if the package only includes pure Python modules (not modules written in C).
