### ISSUE TITLE
A typo in docs

### ISSUE THREAD

**Issue by Darcy-C** [brython-dev/brython#1639]
URL [webcomponent](https://brython.info/static_doc/en/webcomponent.html)
Line `<bold-italic data-val="hello"></bold_italic>`
should be `</bold-italic>` instead of `</bold_italic>`

**Comment by rayluo** [comment]
Nice catch, @Darcy-C . IMHO, you can come up with a PR for this, so that the maintainer of this project can address it with fewer effort from their side.

**Comment by PierreQuentel** [comment]
Thanks @Darcy-C !
