### ISSUE TITLE
Research, Integrate and Implement HTML-GL

### ISSUE THREAD

**Issue by juancarlospaco** [brython-dev/brython#164]
# Research, Integrate and Implement HTML-GL
- Create or integrate a new module on Brython to use WebGL with this Lib.
- Check that the JQuery Plugin that Brython has and HTML-GL has play nice with each other.
- New Functional Tests, Demo Examples and Documentation covering this Feature are welcome.
- Enjoy WebGL :beers: 

**Links and Info:**
- http://htmlgl.com
- https://github.com/PixelsCommander/HTML-GL/#60-fps-and-amazing-effects-by-rendering-htmlcss-in-webgl-framework-agnostic

**Usage and Quick Start:**
- Get this file: https://raw.githubusercontent.com/PixelsCommander/HTML-GL/master/dist/htmlgl.min.js
- Save it, and create an empty file `test.html` on the same folder, fill it with the following markup:

Minimal bare bones example:

``` html
<script src=htmlgl.min.js></script><html-gl>This element is rendered in <h1>WebGL</h1>
```

**Developer notes:**
- Open to Discussion and more Info on this ticket.

:octocat:

**Comment by ShaneFarrell** [comment]
I would like this a lot, I'm trying to write a game engine that will run on both cPython and Brython. So after supporting dynamic imports and metaclasses correctly (I need them) I'd be very happy to see this. xP

**Comment by nicholascarroll** [comment]
Maybe a port of PyOpenGL to WebGL?
