### ISSUE TITLE
Difference in errors/error messages

### ISSUE THREAD

**Issue by pamelafox** [brython-dev/brython#1641]
I'm not sure if this is something you're interested in making consistent, but we're seeing differences in both error messages and error types:

```
mytup = (1, 2, 3)
mytup[0] = 0
```

results in "AttributeError: 'tuple' object has no attribute '__setitem__'" for Brython
versus "TypeError: 'tuple' object does not support item assignment" for CPython

Also:

```
mytup.__class__.__setitem__ = 0 
tuple.__setitem__ = 0
```

results in no error for Brython versus "TypeError: can't set attributes of built-in/extension type 'tuple'" for CPython

**Comment by PierreQuentel** [comment]
Thanks Pamela ! There was the same kind of errors for item deletion and various other operations on tuples.
