### ISSUE TITLE
Packaging brython for Guix/Guix System

### ISSUE THREAD

**Issue by jgarte** [brython-dev/brython#1643]
We're in the process of packaging brython for guix.

We want to create the minimal package for brython and it seems like it builds fine without plumbum.

Is there any risk in packaging brython without plumbum? We couldn't figure out how it was being used in the codebase.

http://guix.gnu.org/

**Comment by PierreQuentel** [comment]
Yes, you can safely package brython without plumbum. It was included at the time when a contributor started the development of a client script that required it, but the project came to a halt. I have removed requirements.txt.

**Comment by jgarte** [comment]
@PierreQuentel Thank you for the information and for clarifying that. I'll close this issue now.
