### ISSUE TITLE
Regression in iteration through element.attrs

### ISSUE THREAD

**Issue by andy31lewis** [brython-dev/brython#1647]
Hello again

This tiny example used to work in the editor on the website:
```python
from browser import document
import browser.html as html
d = html.DIV("Hello world", style={"background-color":"yellow"}, id="mydiv")
document["main_container"] <= d
for key, value in d.attrs.items():
    print(key, value)
```
But now it gives an error `attrs is undefined`. Similar errors are generated by `d.attrs.keys()` and `d.attrs.values()`.

(However, using this alternative still works:
```python
for key in d.attrs:
    print(key, d.attrs[key])
```
~Sorry, I'm not sure when this stopped working.~ This works up to Brython 3.8.9, but stops working in 3.9.0.)

Thanks as ever,

Andy

**Comment by PierreQuentel** [comment]
Merci Andy !
