### ISSUE TITLE
websocket API have an error on chrome

### ISSUE THREAD

**Issue by yuqaf1989** [brython-dev/brython#165]
Sorry for my pool english first :)
I use the websocket api to create a websocket to communicate with the server,the  code is like this

``` python
ws = websocket.WebSocket("ws://127.0.0.1:8888/ws")
```

It works well on firefox,but when I change my browser to chrome ,an error occured.

```
undefined: Failed to construct 'WebSocket'; Please use the 'new' operator,this DOM object constructor
cannot called as a function
```

Then I googled ,I found an answer on stackoverflow `http://stackoverflow.com/questions/15574274/dom-object-constructor-cannot-be-called-as-a-function` It says I should use the **new** operator,BUT
python doesn't have this .
The only method I know to fix it  is use the js code then implement it,It is a bad method.
Thanks!!

Sorry for my post, I found it only happen on my **linux**(mint 17.1), when I change my platform to `windows 7 SP1`, everything is OK, It is so wired.

**Comment by perkinslr** [comment]
`new` is available for all javascript stuff via a little bit weird of syntax.  

    import browser
    ws = browser.window.WebSocket.new('ws://127.0.0.1:8888/ws')


This is the equivalent of the javascript `new WebSocket(...)`.  So I think this issue can be closed.

**Comment by yuqaf1989** [comment]
2 years past,thx.
