### ISSUE TITLE
cleared set can not receive add

### ISSUE THREAD

**Issue by Felecarpp** [brython-dev/brython#1656]
Hey, I have a problem with the Brython set object. 
I have simplified it using the [web test console](https://brython.info/tests/console.html):
``` python
Brython 3.9.1 on Netscape 5.0 (X11)
>>> a = set()
>>> a.add(1)
>>> a.clear()
>>> a.add(1)
>>> a
set()
```
That is not the expected result. I will be use `list` awaiting this issue is fixed.

**Comment by PierreQuentel** [comment]
Thanks for the report @Felecarpp !
