### ISSUE TITLE
"InternalError: too much recursion" when using "document.select" with no match then accessing array

### ISSUE THREAD

**Issue by cedricvanrompay** [brython-dev/brython#1659]
Can be reproduced on https://brython.info/tests/editor.html (tested on Firefox 87.0):

```
from browser import document

document.select('#nonexistent')[0]
```

Click “run” and check the JS console of your browser to see the `InternalError: too much recursion` error.

You can put whatever you want in `select()` as long as it matches no elements in the page.

**Comment by PierreQuentel** [comment]
This is true with the current release on brython.info, but not with the current development version, which gives the correct error message: 
```
Traceback (most recent call last):
  File http://localhost:8000/tests/editor.py, line 119, in run
    exec(src, ns)
  File <string>, line 3, in <module>
IndexError: list index out of range
```

**Comment by cedricvanrompay** [comment]
OK, all good then! Sorry for not having tested on the latest version.
