### ISSUE TITLE
Fail to import tkinter?

### ISSUE THREAD

**Issue by johncwok** [brython-dev/brython#1660]
tkinter is part of the standard library, yet I can't import it by doing what I normally do.
in the head:
```	<script type="text/javascript" src="./brython.js"></script>
	<script type="text/javascript" src="./brython_stdlib.js"></script>
```
in the body:
```
	<script type="text/python">
		from browser import document, html
		import tkinter
	</script>
```
I would get the following errors:
```
ModuleNotFoundError: tkinter (warning: cannot import local files with protocol 'file')
```
Is tkinter somehow not usable in brython?

**Comment by jsbueno** [comment]
tkinter relies on interactions with the windowing system of the OS which
simply are not available,
nor can't be, from within a browser's content.

It is nonsense to want it to work "as is" from Brython - not pejoractivelly,
it literally does not make sense.

That is beside the point it is real functionality is all implemented in
native code (the compiled TCL).

Maybe, one day, one could tr to write an all-new Brython replacement for
tkinter wich
would open a pop-out window, and use that as the app window, but it would
really ned ot be rewritten from scratch  - and possibly, making it 1:1
compatible with
tkinter does not make sense either.

**Comment by kikocorreoso** [comment]
As @jsbueno said it is not available and it does not make sense to use a desktop GUI library from within a browser (again, not in a pejorative sense). 

If you want to build a desktop GUI it is better to stick with CPython.

I close the issue. Please, @johncwok if you fill it is not solved feel free to re-open it.
