### ISSUE TITLE
About new version release, document and CDN

### ISSUE THREAD

**Issue by rayluo** [brython-dev/brython#1662]
Thanks for the good news of 3.9.2 has been released 2 days ago! It is not currently available from CDNs, but you made a new relevant commit 6 hours ago. I assume that would make CDNs to pick up the new 3.9.2 soon.

Strangely, I notice that your new commit also include [a change on the install.md to change its content from 3.9.1 to 3.9.2](https://github.com/brython-dev/brython/commit/656d771f2a5cf3b10b51453e27f482879e8184c7#diff-15b5d4ba01d962e2ed711545801b43cd92d1af9f99855268abe683795a6f8805), which is the right move, but, did such a change not make it to the Brython.info since 3.9.1? Somehow [the current official doc remains "3.9.0"](https://brython.info/static_doc/en/install.html). Should be a quick fix. :-)

A relevant follow-up topic is, I happen to notice that, cdn.jsdelivr.com supports a Version Aliasing feature. For example, these 2 urls would automatically pick up future latest 3.x releases of Brython:

* https://cdn.jsdelivr.net/npm/brython@3/brython.min.js
* https://cdn.jsdelivr.net/npm/brython@3/brython_stdlib.min.js

I think that is a neat convenience, and I'm going to use that in my [brython project template](https://github.com/rayluo/brython-project-template). You can probably also use that in the install.md (and perhaps everywhere else) so that you would never need to worry about the website update issue.

**Comment by PierreQuentel** [comment]
Thanks for the suggestion Ray ! I wasn't aware of this feature of jsDelivr. I have adapted README.md and the [installation](https://brython.info/static_doc/es/install.html) documentation page to mention this, and changed the scripts that generate a new release to update these files.
