### ISSUE TITLE
brython.info instantly crashes safari on iOS 14.5

### ISSUE THREAD

**Issue by glyph** [brython-dev/brython#1663]
Happened to visit the site today and got a browser-level crash instantly. This is *probably* apple's bug, but it would be worth figuring out what's going on and reporting it to them. (Or maybe it's a fast memory leak, which I think can validly cause a renderer "crash", in which case it's a Brython issue)

**Comment by PierreQuentel** [comment]
Thanks for reporting this issue @glyph !

At some point in the development of the Python regexp engine in Javascript I thought I needed to compute the maximum string length supported by Javascript, which is browser-dependent. The issue was that the algorithm probably went into an infinite loop on Safari.

Fortunately I finally didn't use this value in the regexp engine, but forgot to remove this piece of code. It is done in the commit above. I have updated brython.info, it should be ok now.

**Comment by glyph** [comment]
Thanks @PierreQuentel !  Brython continues to be an absolute inspiration in your responsiveness to bug reports 😄 .

**Comment by glyph** [comment]
(I tested on my iPhone again, and it's working fine now. Unrelatedly the buttons on the calculator seem a bit unresponsive though, I wonder what that's about?)

**Comment by nandoflorestan** [comment]
Please make a service release!  Brython 3.9.2 crashes both Safari and Chrome on iOS 14.4.2.

I tried downgrading Brython to 3.9.1 and that seemed to recover Safari, but not Chrome iOS!  I don't know why, but Chrome only worked in Incognito mode.

Finally, I am trying to get into the google group but it seems nobody will approve a new member!?

**Comment by PierreQuentel** [comment]
@glyph confirmed that the version at brython.info now works, and I just tested with an iPhone without the error message. But it's true that a server with the current release 3.9.2 would crash with this OS, so I will have to publish a new release soon.

Sorry for the delay on the Google group, I used to receive a notification when a new user wanted to get access but this has stopped months ago, I have to take a look at the group and check if there are pending approvals and I confess I don't do it every day.

**Comment by glyph** [comment]
Thanks @PierreQuentel ! Sadly I don't get to do much with Brython right now but definitely looking forward to having a working release again so that I can play with it if I do have some time :).

**Comment by nandoflorestan** [comment]
Thank you, @PierreQuentel ! By the way, I think Brython is awesome!

**Comment by PierreQuentel** [comment]
Version 3.9.3 was published today. Thanks @nandoflorestan and @glyph !
