### ISSUE TITLE
Strange behaviour of abs(x**n)

### ISSUE THREAD

**Issue by andy31lewis** [brython-dev/brython#1666]
Hello again

Two in one day, sorry!  

In this code:
```python
a = 0.1
print(a, abs(a))

a = 10**(-1)
print(a, abs(a))
```
The first part gives `0.1 0.1` which is what you would expect.  But the second part, which should be the same, gives `0.1 0`.

In fact, abs(x**n),  where x > 1 and n is a negative integer, always seems to give zero. It works correctly if n is negative but not an integer, though.

Thanks

Andy

**Comment by PierreQuentel** [comment]
Thanks Andy !

**Comment by andy31lewis** [comment]
Thank you Pierre for two more very fast fixes!
