### ISSUE TITLE
document.on() doesn't work

### ISSUE THREAD

**Issue by amab8901** [brython-dev/brython#1667]
When I write document.bind(), it works perfectly fine. But when I replace "bind" with "on" to make it document.on(), the script stops working. How do I implement document.on(), instead of document.bind() ? 

Also, if there is no way to implement document.on(), then I think that this feature should be introduced to make it match the standards used in Python 3.0 (source: https://www.w3schools.com/jquery/event_bind.asp)

Here's my script:

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <script src="brython.js"></script>

    <script src="brython_stdlib.js"></script>

    <style>
        * {
        box-sizing: border-box;
        margin: 0;
        padding: 0;
      }

      body {
          font-family: Arial, Helvetica, sans-serif;
          font-size: 25px;
          padding: 30px;
          line-height: 1.6;
      }

      h1 {
        text-align: center;
        margin-bottom: 30px;
        border-bottom: 1px #ccc solid;
      }

      h2 {
        margin-top: 20px;
      }

      button {
        cursor: pointer;
        display: block;
        background: #333;
        color: #fff;
        border: 0;
        border-radius: 5px;
        padding: 10px 20px;
        margin: 20px 0;
      }

      input[type="text"] {
        border: 1px #ccc solid;
        width: 300px;
        padding: 4px;
        height: 35px;
        margin-top: 20px;
      }

      .card {
        border: #ccc 10px solid;
        height: 400px;
        width: 100%;
        align-content: center;
      }

      .box {
          background: steelblue;
          width: 1.6em;
          height: 1.6em;
          align-content: center;
      }

    </style>
    <title>Brython Demo</title>
</head>
<body onload="brython()">

    <div class="card">
        <button id="Left-btn">Left</button>
        <button id="Right-btn">Right</button>
        <div id="Boxx" class="box"></div>
    </div>

    
    <script type="text/python" id="script5">
        from browser import document, html

        box = document['Boxx']

        Hdist = 0
        Vdist = 0

        def Rchange(a):
            global Hdist
            global Vdist
            box.style.transform = f"translate({Hdist}px, {Vdist}px)"
            Hdist += 10

        def Lchange(a):
            global Hdist
            global Vdist
            Hdist -= 10
            box.style.transform = f"translate({Hdist}px, {Vdist}px)"

        document['Right-btn'].bind('click', Rchange)
        document['Left-btn'].bind('click', Lchange)
    </script>

</body>
</html>

**Comment by PierreQuentel** [comment]
I think the commit referenced above fixes the issue. If not, feel free to reopen it. Thanks !
