### ISSUE TITLE
Return a value from evaluating python_to_js

### ISSUE THREAD

**Issue by radiantone** [brython-dev/brython#1668]
Currently, calling
`window.eval(__BRYTHON__.python_to_js('5*3'));`
does not return a result.

Modifying brython so it produces code like below will allow values to be returned

```
try{
    ;$locals.$line_info = "1,__main__";if($locals.$f_trace !== _b_.None){$B.trace_line()};_b_.None;
 *  var result = $B.mul(5,3);
    $B.leave_frame({$locals, value: _b_.None})
 *  return result;
}
```
with that we can now do
`var result = window.eval(__BRYTHON__.python_to_js('5*3'));`

**Comment by PierreQuentel** [comment]
@radiantone 
Sorry for the very late reply :-(

It could be possible for simple code as in your example, but adding a `return` before each expression that can be the last evaluated one would be much more challenging for slightly more complex code like
```python
if a:
    b
elif c:
    try:
        e
    except:
        f
```
