### ISSUE TITLE
Raw formatted strings aren't treated the same as formatted raw strings.

### ISSUE THREAD

**Issue by alexkassil** [brython-dev/brython#1669]
Ran into this cool little bug!

minimal example below

Here is python3.8
![im1](https://user-images.githubusercontent.com/15950413/117100150-de4f4980-ad27-11eb-947f-ce8e58ab7dd5.png)

Here is brython

![im2](https://user-images.githubusercontent.com/15950413/117100158-e1e2d080-ad27-11eb-9de0-d330763c418b.png)

I have also typed out the code for your convenience:
```
s = "."
fr"\n{s}"
rf"\n
{s}"
```

**Comment by PierreQuentel** [comment]
Thanks for the report, but I can't reproduce the bug. With version 3.9.2 on brython.info I get the correct result:
```
Brython 3.9.2 on Netscape 5.0 (Windows)
>>> s = '.'
>>> fr'\n{s}'
'\\n.'
>>> rf'\n{s}'
'\\n.'
>>> 
```
The bug was fixed a few weeks ago with commit 418c028ff0ca40d03650783202e21c50f45c7767

**Comment by alexkassil** [comment]
Ah so sorry about that. I'll make sure to update to most recent in the future before checking. Thanks!

**Comment by PierreQuentel** [comment]
No worries Alex ! I try to fix bugs as fast as possible, but it's even better when they are fixed _before_ they are reported ;-)
