### ISSUE TITLE
`yield from` in a recursive generator produces incorrect results

### ISSUE THREAD

**Issue by rahularya50** [brython-dev/brython#1672]
The below code prints `[0, 1, 4, 3, 4]`, but should print `[0, 1, 2, 3, 4]`:
```python
def test(lst):
    if lst:
        yield lst[0]
        yield from [item for item in test(lst[1:])]

print(list(test([0, 1, 2, 3, 4])))
```

Replacing the `yield from [...]` with `yield from test(lst[1:])` stops the incorrect behavior from occurring.

**Comment by PierreQuentel** [comment]
Thanks for the bug report Rahul !
