### ISSUE TITLE
On iOS 14.5.1, double-quote and quote characters (at least) not recognized in Console REPL

### ISSUE THREAD

**Issue by AllegroGavin** [brython-dev/brython#1674]
I happened to come to brython.info today from an iPad and iPhone both running 14.5.1, and discovered that the single and double quote characters are not currently recognized by the Brython 3.9.2 Console demo. The behavior exists in Safari, Chrome, Edge, and Firefox (all the browsers I tested). Typing 'cat' (with quotes) or "cat" into the Console REPL gives: 

SyntaxError: invalid syntax (unknown token ['])

Works fine on Windows using the Edge browser.

Other things like parenthesis work correctly.

![screenshot](https://user-images.githubusercontent.com/1420200/117745641-7b9af980-b1d0-11eb-974d-b577f63f82e6.PNG)

**Comment by schmave** [comment]
Looks like this is due to iOS using curly quotes (U+2018 & U-2019) instead of straight quotes. There is probably a way to disable this in your keyboard settings. I guess the Brython REPL could also make some automatic substitution potentially.
