### ISSUE TITLE
On document ready/load event

### ISSUE THREAD

**Issue by oddmario** [brython-dev/brython#1677]
Hello,

I was wondering if it's possible to bind to the "ready" and/or "load" events of an element/DOM

Something like:
```py
<script type="text/python">
from browser import document, alert
def onready(ev):
    alert("Welcome!")
document.bind("load", onready)
</script>
```
or:
```py
<script type="text/python">
from browser import document, alert
def onready(ev):
    alert("Welcome!")
document.bind("ready", onready)
</script>
```

**Comment by oddmario** [comment]
Okay I think we can't use `load` on `document` because we use `<body onload="brython()"></body>` to initialize Brython.
**I came up with a workaround:**

So basically we'll just create an element and bind a `load` event there. I found a good solution here https://stackoverflow.com/a/41685045

So I just converted this to Brython to be:
```py
<script type="text/python">
from browser import document, alert
from browser.html import IMG
document <= IMG("", src="", id="onload")

def onready(ev):
    alert("Welcome!")

document['onload'].bind("error", onready)
</script>
```

**Comment by PierreQuentel** [comment]
I don't understand for which use case you would need to bind the event "load" on document. To get the same result as with your example, you can just write
```
<script type="text/python">
from browser import document, alert
alert("Welcome!")
</script>
```

AFAIK "ready" is jQuery-specific, Brython only supports the events defined in the DOM specification.

**Comment by PierreQuentel** [comment]
I am closing the issue. If you have comments on my reply feel free to reopen it.
