### ISSUE TITLE
Request: Official Visual Studio Code Extension

### ISSUE THREAD

**Issue by timkofu** [brython-dev/brython#1679]
Hi,

Thanks for this work.

Are there plans for an Official VSCode extension? One that would activate if it detects a 
```javascript
<script type="text/python">

</script>
```

inside a `.html` page?

**Comment by charoduke** [comment]
+ for pycharm

**Comment by PierreQuentel** [comment]
I'm afraid this is not an issue for Brython, more something that developers using VSCode or PyCharm should ask them.

**Comment by timkofu** [comment]
Integrating it into the developer workflow would greatly help with adoption. A plug-in developed by the authors of a language/library works best (as they best understand the tech) and is more trustworthy, like in the case of vscode and Go.

**Comment by PierreQuentel** [comment]
I did not know that someone had to write a plug-in. If someone can provide one, that's fine, but I am not able to write it myself.

Maybe you could post a message on the Google group to see if someone can do it ?
