### ISSUE TITLE
TypeError: 'int' object is not callable

### ISSUE THREAD

**Issue by sjlukacs** [brython-dev/brython#1680]
I don't think this could be more basic.  I just downlowded Brython and reference it in the <script src ...> in the header.

here is my code:
```
<script type="text/python">
from browser import document
from browser.html import TABLE, TR, TH, TD
from datetime import datetime
from random import randint

def show_result(event):
    btn = event.target
    #document['body'].text = f"{btn['name']}: {btn['value']}"
    itime = datetime.now()
    order, base, range, operation, lines = randint(0, 2), int(document['base'].value), int(document['range'].value), document['type'].value, int(document['lines'].value)
    #print(f"order: {order}, base: {base}, range: {range}, operation: {operation}, lines: {lines}")
    #print(str(type(lines)))
    t = TABLE()
    t <= TR((TD(base), TD(range), TD(lines), TD(f"{type(lines)}"),))
    for row in range(23):
        t <= TR((TD('x'),))
    document['body'].clear()
    document['body'] <= t
    ftime = datetime.now()
    document['time_span'].text = f"{(ftime - itime).total_seconds()}s"
    return

now = datetime.now()
document['time'].text = now.strftime("%A %B %d, %Y @ %H:%M:%S")
print(now.strftime("%Y-%m-%d %H:%M:%S"))
document['return'].bind('click', show_result)
</script>
```

where the first loop I've tried "for row in range(23):" using Brython is blowing big time with the following error, TypeError: 'int' object is not callable.  everything else was working until I tried the simple for loop.  indicating the code is working and the standard libraries also.

thank you in advance, Lucas

**Comment by ed2050** [comment]
Not an issue with brython.  You redefined range as an int on line 11, hence why call to range(23) fails.

This issue can be closed.

**Comment by sjlukacs** [comment]
oh, damn, i'm embarrassed and i apologize.  you're correct and after 15 years of python coding and converting javascript into brython, i forgot to get into python mode.  sorry.

**Comment by PierreQuentel** [comment]
No worries @sjlukacs !
I remember a few years ago naming a directory `dir = ...`, then spending hours wondering why the hell a call to the built-in `dir()` a few lines further raised an exception...
