### ISSUE TITLE
Stateful bug in html tag constructor?

### ISSUE THREAD

**Issue by ed2050** [brython-dev/brython#1681]
TD () constructor seems to have some weird stateful behavior.  Passing an int to constructor is normally fine.  However, after a failed TD () call, the next constructor call with int fails.  But subsequent calls with int work fine.

Very strange.  Presumably the same happens with other tag constructors in browser.html.  Haven't tested.

### Steps to Reproduce
The statements below demonstrate the problem in brython console.  I ran only these statements in a fresh console tab at https://brython.info/tests/console.html?lang=en:

```
Brython 3.9.3 on Netscape 5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
>>> from browser.html import TD

# normal behavior
>>> TD (5)
<HTMLTableCellElement>

# normal
>>> TD ('3454')
<HTMLTableCellElement>

# intentionally trigger an error by passing a function
>>> TD (range)
Traceback (most recent call last):
  File <string>, line 1, in <module>
TypeError: 'type' object is not iterable

# now passing int 5 doesn't work?
>>> TD (5)
Traceback (most recent call last):
  File VFS.interpreter.py line 223, in keypress
    _=self.globals['_']=eval(currentLine,
  File <string> line 1, in <module>
TypeError: 'type' object is not iterable<HTMLTableCellElement>

# aaaannndd... now it works again? what? 🥴
>>> TD(5)
<HTMLTableCellElement>
```

**Comment by PierreQuentel** [comment]
Thanks for reporting this Edward.
The issue was not with the constructor (the same code in a script, not in the console, worked as expected) but with the way errors were managed when the constructor raises an exception.
