### ISSUE TITLE
NameError when making Ajax request

### ISSUE THREAD

**Issue by cool-RR** [brython-dev/brython#1684]
```
Brython 3.9.3 on Netscape 5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
>>> from browser import ajax
>>> x = ajax.get('https://brython.info/', blocking=True)
>>> x
Traceback (most recent call last):
  File <string>, line 1, in <module>
NameError: name 'x' is not defined
```

**Comment by fbpyr** [comment]
@cool-RR  : I usually use ajax requests in Brython with a callback as shown below, which is a little different, than the usual requests syntax used in Python: 

```python
from browser import ajax, console
from javascript import JSON


def get_info():
    ajax.get(f"https://some_srv_some_url/api_v1/info/", oncomplete=parse_json, blocking=True)


def parse_json(args=None):
    console.log("parsing json after ajax request")
    if args:
        response = args.read()
        data = JSON.parse(response)
        console.log(data)
```

Hope this helps. 🙂

**Comment by cool-RR** [comment]
Sure, I use `ajax` and I've read the documentation. Thanks anyway.

**Comment by cool-RR** [comment]
Thanks Pierre. A few notes:

1. Would be nice if fixed bugs included tests that the bugs don't happen anymore.
2. Your fix is to the ajax module, but the error suggests that something on the Python level is bad. (You couldn't create a bug like that in CPython.) I don't know anything about how Brython is implemented, but maybe it should have different handling for a JavaScript function that doesn't return anything? Either translate it automatically to `None`, or raise an exception. What do you think?

**Comment by PierreQuentel** [comment]
Many thanks for the suggestions Ram !

**Comment by cool-RR** [comment]
Thank you for agreeing 😂
