### ISSUE TITLE
Incorrect behavior of int.__str__

### ISSUE THREAD

**Issue by schmave** [brython-dev/brython#1685]
`str(int)` works fine in Brython, but calling `int.__str__` does not work the same way it does in CPython. I'm not sure if this is just an implementation detail or not. (The same thing happens for other types too, like `float`)

```python
int.__str__()
```

CPython raises `TypeError: descriptor '__str__' of 'object' object needs an argument`
Brython raises `<Javascript TypeError>: Cannot read property '$brython_value' of undefined`

```python
print(int.__str__(int))
```

CPython prints `<class 'int'>`
Brython prints `[object Object]`

Thanks for considering these strange edge cases.

**Comment by PierreQuentel** [comment]
Thanks Evan. I did not realize before this report that `int.__str__` is `object.__str__`, and the same for most of the built-in classes except `bytes, bytearray` abd `str`.

CPython also has strange error messages at times
```
Python 3.10.0a7 (tags/v3.10.0a7:53e5529, Apr  6 2021, 10:20:47) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> int.__str__(1, 2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: expected 0 arguments, got 1
>>> int.__str__(self=8)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: descriptor '__str__' of 'object' object needs an argument
>>>
```

With this commit, Brython gives more logical error messages:
```
Brython 3.9.3 on Netscape 5.0 (Windows)
>>> int.__str__(1, 2)
Traceback (most recent call last):
  File <string>, line 1, in <module>
TypeError: descriptor '__str__' of 'object' expects 1 argument, got 2
>>> int.__str__(self=8)
Traceback (most recent call last):
  File <string>, line 1, in <module>
TypeError: descriptor '__str__' of 'object' doesn't accept keyword arguments
>>> 
```

**Comment by schmave** [comment]
Oh wow, I like your error messages better for sure. Thanks!
