### ISSUE TITLE
JS TypeError when NameError should be thrown

### ISSUE THREAD

**Issue by btwj** [brython-dev/brython#1688]
In certain instances, Brython raises a JS Exception `<Javascript TypeError>: obj is undefined` when a `NameError` should be raised instead:

```
def f(a):
    pass

for a in a.b:
    pass
```

In CPython, `NameError: name 'a' is not defined` is raised.
In Brython, `<Javascript TypeError>: obj is undefined` is raised instead.

Thank you for looking into this!

**Comment by PierreQuentel** [comment]
Thanks for the report @btwj !
