### ISSUE TITLE
memoryview doesn't implement __setitem__

### ISSUE THREAD

**Issue by ikelos** [brython-dev/brython#1691]
In the standard library `memoryview` supports item assignment but in brython-3.9.3 (also tested with 3.9.0), it throws the following:

Traceback (most recent call last):
  File http://127.0.0.1:8000/test.html#__main__ line 1, in <module>
    import test
  File http://127.0.0.1:8000/test.py line 3, in <module>
    x[2] = b'\x10'
TypeError: 'memoryview' object does not support item assignment

Where test.py is:

```
x = memoryview(b'\x00\x01\x02\x03')
print(x)
x[2] = b'\x10'
print(x)
```

I saw that memoryview is only listed as having a partial implementation in commit `80c4cb82`.  I was wondering if there was an intention to get a complete implementation at all?  It would be nice for compatibility between existing python code to be able to arbitrarily assign into these types of buffers, but I realize they may not get used often enough to make it worthwhile...

**Comment by PierreQuentel** [comment]
The error message in Brython is not exactly the same as in CPython, but item assignment to a memoryview also fails in Cpython:

```
Python 3.10.0a7 (tags/v3.10.0a7:53e5529, Apr  6 2021, 10:20:47) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> x = memoryview(b'\x00\x01\x02\x03')
>>> x[2] = b'\x10'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: cannot modify read-only memory
>>>
```

**Comment by ikelos** [comment]
That's only true if the underlying object doesn't allow assignment, which `bytearray` does:
```
Python 3.9.5 (default, Jun  2 2021, 20:01:29) 
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> x = memoryview(bytearray(b'\x00\x01\x02\x03'))
>>> x[2] = 255
>>> 
```

Which is thoroughly confusing/inconsistent, and I fully understand if it's not worth implementing.  I've got an embedded micropython project that I use `memoryview` for because of the limited resources, and I was hoping to use the source files unmodified as much as possible.  I could see whether just use bytearray will work, but since you were trying for compatibility I figured it would be worth recording somewhere...

**Comment by ikelos** [comment]
Awesome, thank you!  5:)
