### ISSUE TITLE
"SyntaxError: invalid syntax (else after...)" for minified Python code

### ISSUE THREAD

**Issue by lajtop** [brython-dev/brython#1693]
I've run into this issue when trying to run Python code that was minified with `python-minifier`. Minimal reproducible example:

```python
if 1:print("a");print("b")
else:print("x");print("y")
```

This code snippet works with stable version of Brython and in CPython 3.9 (and prints both `a` and `b` as expected). However, with **master** version of `brython.js` I get this error message:

```
Traceback (most recent call last):
  File __main__, line 2
    else:print("x");print("y")
     ^
SyntaxError: invalid syntax (else after expr)
```

Similar errors do occur when I replace `else` with `elif`, or when there are multiple assignments instead of multiple function calls. Single statements seem to be handled correctly:

```python
if 1:print("a");
else:print("x");
```

I am not sure, but this might be related to another strange behavior I have encountered in **stable** version where some lambdas are not parsed correctly if there is more code at this same line: 

```python
lambda:{};print("a");  # SyntaxError: invalid syntax (Unbalanced bracket)
```

Thank you in advance

**Comment by PierreQuentel** [comment]
Thanks for the report @lajtop !
