### ISSUE TITLE
Brython >3.9.1 fails to load on iPad

### ISSUE THREAD

**Issue by andy31lewis** [brython-dev/brython#1695]
Hello again

On an iPad (using Safari)  the following web page displays `Hello world` as expected.
```html
<html>
    <head>
        <script src="https://cdn.jsdelivr.net/npm/brython@3.9.1/brython.min.js"></script>
    </head>
    <body>
        <p>Hello world</p>
    </body>
</html>
```
However, if the Brython version is changed to 3.9.2 or 3.9.3, the page fails to load with the message:
"A problem repeatedly occurred."

Note that Brython is not being run using `<body onload>`; simply including the script in the page is enough to cause the error.

I can't provide any more details about the iPad.  However, I have a browser called "Epiphany" on my laptop which uses the same engine as Safari on the iPad.  Using that, the page loads correctly for Brython 3.9.1, but for 3.9.2 and 3.9.3 I can watch the amount of available memory (and swap) steadily diminishing to zero as the page tries to load, until eventually the system crashes (or I kill the browser before that happens!).  I assume something similar starts to happen on the iPad, but the system causes the page loading to fail, in order to protect itself from a crash.

Thanks as always,

Andy

**Comment by andy31lewis** [comment]
I meant to say that maybe this is related to #1663, but I'm not sure because that was fixed with the release of 3.9.3, whereas this problem still exists in 3.9.3.

Andy

**Comment by PierreQuentel** [comment]
It's my lucky day : I have visitors who happen to have Apple computers !

I tested brython.info with the latest version (3.9.3), I don't have any error message.

![20210614_141428](https://user-images.githubusercontent.com/3447215/121896093-3616a280-cd21-11eb-837e-8bfbdbd9a59e.jpg)
![20210614_145540](https://user-images.githubusercontent.com/3447215/121896096-3747cf80-cd21-11eb-8667-d663eaa66d36.jpg)

**Comment by andy31lewis** [comment]
I can also confirm that [brython.info](https://brython.info/tests/console.html?lang=en) works correctly on Epiphany (the browser I mentioned in the first post), but [http://mathsanswers.org.uk/oddments/brycharts/helloworld3.html](http://mathsanswers.org.uk/oddments/brycharts/helloworld3.html) causes an out of memory failure as described above.

Andy

**Comment by PierreQuentel** [comment]
Unfortunately, I could reproduce the bug... I will try to see what goes wrong.

**Comment by PierreQuentel** [comment]
Found !

The explanation is very simple : for a reason that I can't explain, the version loaded on npm for version 3.9.3 is in fact brython.js version 3.9.2... The CDN uses this version (which explains the bug, the same as in 3.9.2) whereas brython.info uses the correct version of brython.js (3.9.3).

I will have to release a new version...

**Comment by andy31lewis** [comment]
Thank you for the release of version 3.9.4.  I can confirm that my "iPad testers" report everything working correctly, so I think this issue could be closed now?

**Comment by PierreQuentel** [comment]
Yes, I am closing the issue. Thank you and thank your daughter-in-law :-)
