### ISSUE TITLE
JS TypeError (cannot read property '$factory' of undefined) when NameError expected

### ISSUE THREAD

**Issue by btwj** [brython-dev/brython#1697]
The latest development version of Brython that fixes a similar issue #1688 still throws a TypeError for the code below (albeit with a slightly different message):
```
for x.y in [0]:
    pass
```
Brython (Chrome): `<Javascript TypeError>: Cannot read property '$factory' of undefined`
Python: `NameError: name 'x' is not defined`

Thanks for checking this out!

**Comment by PierreQuentel** [comment]
Thanks for the report !
