### ISSUE TITLE
console can't understand starting a function any more

### ISSUE THREAD

**Issue by glyph** [brython-dev/brython#1699]
I navigate to https://brython.info/console.html in Safari

type `def foo():` and hit enter, and I get a traceback

<img width="341" alt="image" src="https://user-images.githubusercontent.com/716529/122499513-eac0f600-cfa5-11eb-98d3-1e86864bd1f0.png">

**Comment by PierreQuentel** [comment]
This is dreadful... I will yell at the release manager ;-)

I have fixed the bug and uploaded the corrected version to brython.info to hide the problem, and I will publish an emergency release shortly.

Many thanks for reporting this !
