### ISSUE TITLE
can't import module from pypi

### ISSUE THREAD

**Issue by Dagimal** [brython-dev/brython#1704]
hello, I'm very interested in this project, but I have a little problem related to import module (tqdm), I've downloaded the pypi package and as local, and I put it in the same directory.

![errortqdm2](https://user-images.githubusercontent.com/25417316/123267297-0c325c80-d527-11eb-877b-7eac29a64aee.png)

and I've also converted the package into js, like the guide on this page: [guide](https://brython.info/static_doc/en/brython-packages.html)

![errortqdm1](https://user-images.githubusercontent.com/25417316/123267831-a1355580-d527-11eb-83c3-cbc5641df464.png)

but when i do import module **"from tqdm import tqdm"**, I have a problem, there is an error in chrome 
**"RuntimeError: SyntaxError: Unexpected identifier"**

![errortqdm](https://user-images.githubusercontent.com/25417316/123268017-d6da3e80-d527-11eb-9223-bf301ceaa839.png)

what's wrong with my code? Please help me, i really like this project :)
sorry if my english is bad, i'm still learning, thanks :)

**Comment by PierreQuentel** [comment]
Thanks for the report !

There was nothing wrong with your code, if was a bug in Brython.

You won't be able to use this package though : it uses the __`ast`__ module, which is not implemented (yet) in Brython because it is written in C in CPython; and it also uses the __`pandas`__ library, which also doesn't work in Brython because it uses C modules.

**Comment by Dagimal** [comment]
ok sorry, is there any solution for this?

**Comment by PierreQuentel** [comment]
For the __`ast`__ module there is hope that it will be available some day.

For modules written in C it is theoretically possible to convert them to Web Assembly, but so far I haven't met anyone who could do it :-(
