### ISSUE TITLE
Unreachable code after return statement

### ISSUE THREAD

**Issue by andy31lewis** [brython-dev/brython#1706]
Hello again

I wasn't sure whether to report this, as it doesn't stop anything working, but I thought it might be worth looking into.

I keep getting the above warning in the browser console.  The line number reference in brython.js is 1545:16, which is `return $BodyCtx(C)}`.

It doesn't happen with every file I've written.  I've been trying to work out which line in my own code causes this section of brython.js to be run, and therefore triggers the warning.  But I haven't had any success with that.

Thanks as always,

Andy

**Comment by PierreQuentel** [comment]
Hello Andy,

I also have this message from time to time. In the test suite it happens in two tests, one for which this is expected because the Python code tested is
```python
def f():
    return
    yield 1
```

The other one happened in a script with a function that ends with `return await X`; I changed the translation in the commit referenced above.

If you can isolate other cases I will investigate.

Thanks,
Pierre

**Comment by andy31lewis** [comment]
Hello Pierre

I can report that your latest commit fixes the problem for me.  Which I thought was strange, because I do not use the aio module at all, and have nothing like `return await X` in my code.

However, by a rather long process of elimination, I found that one example of a line in my code which caused the problem was  `from functools import total_ordering`.  It turns out that `functools` imports `collections`, which in turn imports `_collections_abc`. In that module we find, in `class AsyncGenerator`, the line `return await self.asend(None)`. So the mystery is explained - any file of mine which imported anything from `functools` or `collections` would trigger the error. ;-)

Thanks for taking the time to solve this!

Andy
