### ISSUE TITLE
SVG

### ISSUE THREAD

**Issue by charoduke** [brython-dev/brython#1708]
Hello!

`SVG('', Class="bla")`
give me
`<svg Class="bla"></svg>`

some hack
```
s = SVG()
s.class_name = "bla"
```
work as need:
`<svg class="bla"> </svg>`

and I can't find tag `<use></use>` for svg sprites

**Comment by PierreQuentel** [comment]
As explained in the [documentation](http://localhost:8000/static_doc/en/svg.html), it is available in module __`browser.svg`__

```python
from browser import document, html, svg

s = html.SVG(Class="bla")
s <= svg.use(href="#")
document <= s
```

**Comment by charoduke** [comment]
Thanks, for response. I try and this get render:
`<svg Class="bla"><use xlink:href="#"></use></svg>`
But I think `Class=` must be `class=`.

**Comment by PierreQuentel** [comment]
Attribute names are case-insensitive, it doesn't matter if it is `class` or `Class`.

The attribute cannot be passed as `SVG('', class="bla")` because `class` is a Python keyword, it would raise a `SyntaxError`.

**Comment by charoduke** [comment]
Yes, thanks, you are right. It case-insensitive.
