### ISSUE TITLE
builtins.min not working for float values? (3.9.4 via cdnjs)

### ISSUE THREAD

**Issue by jjfiv** [brython-dev/brython#1717]
Hi all!

Apologies if this is a known issue, I don't know how to debug any deeper than I have, but I've attempted to minimize the example here. 

```html
<!DOCTYPE html>
<html>

<head>
    <title>Brython Experiment</title>
    <meta charset="utf-8">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/brython/3.9.4/brython.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/brython/3.9.4/brython_stdlib.min.js"></script>
</head>

<body onload="brython(2)">
    <div class="container">
    </div>
</body>
<script type="text/python">
    print(min(3, 4))
    assert abs(min(3, 4) - 3) < 0.1 # works OK!
    print(min(3.3, 4.3))
    assert abs(min(3.3, 4.3) - 3.3) < 0.1 # fails
</script>

</html>
```

I've been able to workaround with an if statement, but this second assertion is failing for me. Tested with Firefox 89 and Chrome 90.

Thanks!
John

EDIT: These statements appear to work fine in [the Console](https://brython.info/tests/console.html?lang=en), so that leaves me more confused.

**Comment by andy31lewis** [comment]
Hmm, this seems to work fine using
```
    <script src="https://cdn.jsdelivr.net/npm/brython@3.9.4/brython.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/brython@3.9.4/brython_stdlib.js"></script>
```
But I can confirm that it doesn't work for me using `cdnjs.cloudflare.com` as above.

Very strange!

Andy

**Comment by PierreQuentel** [comment]
Even stranger : if you replace the minified version at cdnjs by the original file

```xml
<script src="https://cdnjs.cloudflare.com/ajax/libs/brython/3.9.4/brython.js"></script>
```
the result is correct.

I doubt that the problem comes from minification, but I have no other explanation.

**Comment by jjfiv** [comment]
On the other hand, there seems to be at least superficial differences in minification between the two sites. The working jsdelivr min version has this header:

```javascript
/**
 * Minified by jsDelivr using Terser v5.3.5.
 * Original file: /npm/brython@3.9.4/brython.js
 *
 * Do NOT use SRI with dynamically generated files! More information: https://www.jsdelivr.com/using-sri-with-dynamic-files
 */
```

The cloudflare version has that chopped off, at least.
