### ISSUE TITLE
3.9.4 breaks multiline python variable

### ISSUE THREAD

**Issue by xanthics** [brython-dev/brython#1718]
While trying to automate some of my workflow (with selenium, grabbing the output of a dynamic page) I've encountered a project breaking change with 3.9.4.  I've been using 3.9.0 (project [here](https://github.com/xanthics/genshin_grind_planner)) and it's the token change between x.3 and x.4 that breaks my existing code.

Code like these two now generate `SyntaxError: invalid syntax (invalid token 	)`

```python
	t <= COLGROUP(
		COL() +
		COL() +
		COL(Class='left_border') +
		COL(Class='left_dotted') +
		COL(Class='left_border') +
		COL(Class='left_dotted') +
		COL(Class='left_border') +
		COL(Class='left_dotted') +
		COL(Class='left_border') +
		COL(Class='left_dotted') +
		COL(Class='left_border') +
		COL(Class='left_dotted') +
		COL(Class='left_dotted') +
		COL(Class='left_border') +
		COL(Class='left_dotted') +
		COL(Class='left_dotted')
	)

characters = {
	"amber": {
		'ascension': {
			'element_1': 'agnidus_agate',
			'element_2': 'everflame_seed',
			'local': 'small_lamp_grass',
			'common': 'arrowhead'
		},
		'talent': {
			'talent': 'freedom',
			'common': 'arrowhead',
			'boss': 'dvalins_sigh'
		},
		'weapon': 'bow',
		'element': 'pyro'
	}
}
```

The only fix seems to be to make sure that each python variable is declared on a single line, however files like [this one](https://github.com/xanthics/genshin_grind_planner/blob/master/characters.py) are 590 lines and would be too burdensome to work with as a single line

Is it intended that all python files be essentially minified going forward or was this an inadvertent change?  This can be recreated by changing brython to 3.9.4 in either of my html files and loading them in chrome or firefox (I am doing this via Pycharm preview to start the local browser)

---------------

Ran in to this while trying to fix a `JavaScript error: https://cdn.jsdelivr.net/npm/brython@3.9.3/brython.min.js line 7 > eval, line 1: Error: ` issue with Selenium, but I'm still troubleshooting that.

**Comment by PierreQuentel** [comment]
Sorry about that, it's a side effect of the rewriting of the Python tokenizer : the tabulation character was not supported...
