### ISSUE TITLE
Is TypedDict supported?

### ISSUE THREAD

**Issue by rayluo** [brython-dev/brython#1726]
Hi Pierre, when I'm trying to port a 3rd-party package into my project, I happen to notice such a usage would generate an error in Brython 3.9. The sample below is derived from [this section of the `TypedDict` PEP](https://www.python.org/dev/peps/pep-0589/#totality):

```python
from typing import TypedDict  # The TypedDict from CPython 3.9 is supposed to work

class Movie(TypedDict, total=False):  # But Brython 3.9 seems to generate an error from this line
    name: str
    year: int
```

The error I got is: `TypeError: __init_subclass__() got an unexpected keyword argument 'total'`.

Would you mind double check it and see if you can reproduce it. And if so, would that be an easy or difficult bug to fix?

**Comment by PierreQuentel** [comment]
Thanks Ray ! `TypedDict` was supported, it's just that `__init_subclass__()` was not called at the right place in __`py_types.js`__.
