### ISSUE TITLE
input() and print() for tutors and online courses

### ISSUE THREAD

**Issue by Inspired1601** [brython-dev/brython#1727]
Hello. Thanks for Brython, it's **very** useful for online education.
But there's a problem which has been raised several times already (https://groups.google.com/g/brython/c/ISIgpLQBURg), but no solution has yet been found.

As you know, Brython, Skulpt and other look-a-like solutions are widely used by online courses, tutors etc. And `input()` / `print()` functions are the main way to create basic interactive programs, which are usually created at the first steps while learning programming.

By default Brython uses JS `prompt()` function for `input()`, and there's a way to override `stdout` for `print()`, which allows to redirect output into some DOM element. That's fine, in general.

But there's an issue. Due to JS single-threaded nature, page content wouldn't be refreshed until the whole script finishes. For example, let's look at the common code snippet from basic Python course: 
```
true_password = 'python_is_cool'

while input('Password: ') != true_password:
  print('Incorrect password, try again')
```

What will happen when you launch this via Brython? User won't see any messages about incorrect password till he provide correct password, because DOM won't be updated until the whole script finishes.

Quasi-solution is `eval`'ing or `exec`'ing code line-by-line via `setTimeout(..., 0)` events to make browser "breathe". But this doesn't solve issues with loops, like in previous example. Because `exec()` will handle the whole loop, user will still be acting blind until the loop finishes.

Skulpt solved this issue with "suspensions": http://skulpt.org/docs/misceval.js.html
This allows you to suspend script execution until user finishes his input or DOM updates or something else.

For example, the code above (`while`, `input` etc) will execute perfectly with Trinket: https://trinket.io/python
It has Skulpt under the hood.

Is there any way to do the same thing with Brython? There's multiple requests for such a feature at https://groups.google.com/g/brython, therefore many tutors could use this feature.

**Comment by PierreQuentel** [comment]
I have read the Google group thread you mention and still don't understand what you mean with _" User won't see any messages about incorrect password till he provide correct password, because DOM won't be updated until the whole script finishes."_.

With the code below, the error message shows on the page at each incorrect entry:

```xml
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<script type="text/javascript"
    src="https://cdn.jsdelivr.net/npm/brython@3/brython.min.js">
</script>
<script type="text/javascript"
    src="https://cdn.jsdelivr.net/npm/brython@3/brython_stdlib.js">
</script>
</head>

<body onload="brython({debug:2})">

<script type="text/python">
import sys

from browser import document

sys.stdout = document # redirect print() to document.write()

true_password = 'python_is_cool'

while input('Password: ') != true_password:
  print('Incorrect password, try again<br>') # document.write expects HTML

print('cool !')
</script>

</body>
</html>
```

The result is obviously less elegant than Skulpt's, but although I read the page on suspensions many times, I still don't have a clue on how this could be converted to Brython.

**Comment by Inspired1601** [comment]
Maybe the video will explain the situation better than words. https://vimeo.com/574162247

As you can see, the page content is updated only after the script has completely finished its work. Therefore, the user does not see the intermediate messages "Incorrect password, try again" after entering an incorrect password.

Try to run the same code on Trinket.io - due to "suspensions" the user sees messages exactly when he should see them, and not after the whole script has finished its work.

That is, because the Brython script is executed in a JS environment, the resulting behavior is very different from what a user would get in a "natural" Python environment.

**Comment by PierreQuentel** [comment]
Very strange, this is not the result I get (sorry for the poor quality of the video...)
[https://drive.google.com/file/d/1bvkDISsJP1wgeFDD-PTycM02vkSrlhvu/view?usp=sharing](https://drive.google.com/file/d/1bvkDISsJP1wgeFDD-PTycM02vkSrlhvu/view?usp=sharing)
Recorded with Firefox 89 on Windows 10.

**Comment by Inspired1601** [comment]
Wow. Firefox's behavior is completely different than Chrome's. I've tested it, and with `document.write` it works exactly as you described. But with this code it works the same way as in Chrome:
```
class ConsoleOutput:
    encoding = 'utf-8'

    def __init__(self, doc, console_id):
        self.cons = doc[console_id]
        self.buf = ''

    def write(self, data):
        self.buf += str(data)

    def flush(self):
        self.cons.value += self.buf
        self.buf = ''
        return self.cons.value

    def __len__(self):
        return len(self.buf)

```

Script finishes, then DOM updates. Looks like Firefox processes `document.write` in different way, but in real project `document.write` is useless.

**Comment by PierreQuentel** [comment]
No, it's the same behaviour on Firefox with a textarea instead of `document.write()` : [https://drive.google.com/file/d/1c0KQSfxwR75iDuihL_D5Aqjq_Elu_A-6/view?usp=sharing](https://drive.google.com/file/d/1c0KQSfxwR75iDuihL_D5Aqjq_Elu_A-6/view?usp=sharing).

**Comment by Inspired1601** [comment]
Hmm. I could not reproduce this behavior with a textbox.
Anyway, Chrome currently uses ~ 65% of all users and Firefox ~ 4% of all users (https://gs.statcounter.com/browser-market-share). Accordingly, most users will encounter exactly the behavior that was originally described, namely, updating the DOM after the complete script execution.

**Comment by PierreQuentel** [comment]
Strange that you don't get the same behaviour, but you are right that Firefox is not much used anymore.

I can't think of a solution to run the original code in Brython. A workaround for this specific use case (input in a while loop) would be to replace `print()` by `browser.alert()` (alias for the Javascript blocking function `alert()`).

```python
from browser import alert

while input('Password: ') != "cool":
    alert('wrong password, try again')
```

**Comment by Inspired1601** [comment]
`alert ()` is not suitable for general use. This particular case is just a one case in hundreds. 

It turns out that we cannot find a solution to the problem in Brython? :(

**Comment by PierreQuentel** [comment]
There are workarounds, but the same behaviour as the Python interactive interpreter is not currently possible in Brython, and I doubt it will ever be because of the lack of user-defined blocking functions in Javascript.

Here is another version that doesn't use `alert()`:

```python
from browser import document

message = "Password ?"

while input(message) != 'cool':
    message = "Wrong password, try again"

document <= "Cool !"
```
