### ISSUE TITLE
Articles for Brython

### ISSUE THREAD

**Issue by kaustubhgupta** [brython-dev/brython#1728]
Hello,

I like this project very much and I love the idea of using Python as a front-end alternative. I have written two articles, one for explaining the basics and another one to bring out one of the use cases, creating a web interface for ML models. I would be grateful if these could be added to any relevant wiki pages of Brython or in the resources section of the documentation, whichever suits the project. 

[Run Python Code on Websites: Exploring Brython](https://towardsdatascience.com/run-python-code-on-websites-exploring-brython-83c43fb7ac5f) - Published on Medium, Nov 15, 2020

[Python on Frontend: ML Models Web Interface With Brython](https://www.analyticsvidhya.com/blog/2021/07/python-on-frontend-ml-models-web-interface-with-brython/) - Published on Analytics Vidhya, July 14, 2021

**Comment by kikocorreoso** [comment]
Hi @kaustubhgupta 

You can create a new wiki page here: https://github.com/brython-dev/brython/wiki (titled ("brython articles" or something like that). And after the page has been created you can add the page link as a new section here: https://github.com/brython-dev/brython/wiki 

I hope it helps.

Once done you can close this issue.

**Comment by kaustubhgupta** [comment]
Done with the page creation and linked it in the featured links section. Thanks for allowing me to do so!

Here is the page for ref:
https://github.com/brython-dev/brython/wiki/Brython-Articles
