### ISSUE TITLE
TypeError: module is undefined during conversion to JS

### ISSUE THREAD

**Issue by btwj** [brython-dev/brython#1729]
Came across this strange bug where trying to compile this piece of code:
```
for i in range(0):
    if True:
        f() += 1
```
causes `TypeError: module is undefined`.

Ideally, it should throw something like `SyntaxError: cannot assign to function call` when it's run, which correctly happens if either the for loop or if statement is removed above.

Thanks for checking this out!

**Comment by PierreQuentel** [comment]
Sorry for the late fix, I am almost full time on Pattern Matching these days...
