### ISSUE TITLE
Impossible to import xml.etree.ElementTree

### ISSUE THREAD

**Issue by MaximeCheramy** [brython-dev/brython#173]
The following code:

    from xml.etree import ElementTree

generates this error:

    SyntaxError: invalid syntax,xml.etree.ElementTree,1806,5,pass

Version: Brython3.1.1-20150328-091302

**Comment by MaximeCheramy** [comment]
```
Brython 3.1.1 on Netscape 5.0 (X11)
>>> from xml.etree import ElementTree
Traceback (most recent call last):
  module __main__18 line 116
    _ = editor_ns['_'] = eval(currentLine, editor_ns)
  module __main__18 line 131
    exec(currentLine, editor_ns)
  module xml.etree.ElementTree line 1806
    pass
       ^
SyntaxError: invalid syntax
```

**Comment by MaximeCheramy** [comment]
Funny thing, this seems to work:

    try:
        from xml.etree import ElementTree
    except SyntaxError:
         from xml.etree import ElementTree

**Comment by toyg** [comment]
Is there any way to parse xml in brython? I'm getting a different error in the live Editor on the website:

    Traceback (most recent call last):
     module __main__ line 70
    doc["add_main"].bind('click', add_main)
     module editor line 102
    undefined
     module editor line 5
    from xml.etree import ElementTree
     module xml.etree.ElementTree line 872
    try :
     ImportError: cannot import name 'ElementTree'

**Comment by PierreQuentel** [comment]
Sorry for the very late fix. Importing `ElementTree` should work with commit 050bf84
