### ISSUE TITLE
Type Checking

### ISSUE THREAD

**Issue by tomitrescak** [brython-dev/brython#1732]
Hello and thanks for the amazing package! I was wondering whether there is some kind of type checking available. For example I would like this to report a missing function error:

```
a = foo()
```

currently, it transpiles without warning. I checked the root level object `$B` and it should containe all the info needed to perform type checking, such as available packages, function names ...

**Comment by PierreQuentel** [comment]
Hello !

I'm not sure to understand what you mean by "it transpiles without warning". When I run this code I get this message in the browser console:

```
Traceback (most recent call last):
  File http://localhost:8000/tests/test.html#__main__ line 1, in <module>
    a = foo()
NameError: name 'foo' is not defined
```
which is the same as CPython.

**Comment by tomitrescak** [comment]
That’s correct and thank you for your reply. But this happens when you run the code. Yet, It is possible to catch these errors with type checking with static analysis before running the code, such as IDEs do. Would this be somehow possible? Thanks !

**Comment by PierreQuentel** [comment]
Detecting such errors before running the code is not in the Python language specification, and Brython follows them as much as possible; it is a feature for IDEs. The typing features added to the language in the past years allow IDEs to do such checks and warnings before executing the code.

Brython supports the syntax for typing, but IDEs presently don't support Python code inside HTML. What you can do is put the Brython code in a separate .py file, edit this file with an IDE, and include it in the HTML page with

```xml
<script type="text/python" src="myscript.py"></script>
```

**Comment by tomitrescak** [comment]
That makes sense! We’ll just implement static analysis over the JavaScript AST that to generate in py2js function. Should be pretty straightforward. Thank you!
