### ISSUE TITLE
Does async use 100% CPU when waiting?

### ISSUE THREAD

**Issue by kmindspark** [brython-dev/brython#1733]
Based on the nature of Javascript, I was wondering whether the asyncio module internally handles waits as active computation which eats up CPU or whether it is more energy/CPU-efficient?

**Comment by PierreQuentel** [comment]
I'm not sure whether this is a question for Brython, which doesn't support the __`asyncio`__ module.

**Comment by kmindspark** [comment]
I think I meant aio.sleep(), my bad.

**Comment by PierreQuentel** [comment]
By definition, asynchronous functions eat a minimal amount of CPU resources. `await aio.sleep(5)`  in an async function gives control back to the main application, and the function is resumed after 5 seconds.

Here is an example:

```xml
<script type="text/python">
from browser import aio, document

ta = document["zone"]
ta.focus()

async def main():
    ta.value += 'start\n'
    await aio.sleep(7)
    ta.value += '\nstop'

aio.run(main())
</script>

<textarea rows="40" cols="40" id="zone"></textarea>
```
The program prints "start" in the textarea, then you can enter text, and after 7 seconds "stop" is printed.
