### ISSUE TITLE
How can I easily tell a JavaScript attribute from an item from an index?

### ISSUE THREAD

**Issue by roger-** [brython-dev/brython#174]
In JavaScript you can access both attributes and items using dot notation, whereas in Python you need to use square braces for the latter. It's even worse in nested JavaScript objects because if your Brython code doesn't access something in a specific way then it seems to  do weird things.

It took me a long time to figure out that this JavaScript code:

```javascript
myChart.datasets[0].points[2].value
```

had to be written like this in Brython:

```python
myChart['datasets'][0].points[2].value
```

otherwise things would break.  

Is this normal?

**EDIT**:

Weird, because 
```python
console.log(myChart['datasets'][0])
``` 
gives an exception while 
```python
console.log(myChart.datasets[0])
``` 
works, though it seems to clobber something?

**Comment by PierreQuentel** [comment]
Hi,

It's hard to tell without more context

This code : 

```
<script>
myChart = {datasets:[{points:[0,1,{value:'a'}]}]}
</script>

<script type="text/python">
from browser import window

x1 = window.myChart.datasets[0].points[2].value
x2 = window.myChart['datasets'][0].points[2].value
assert x1==x2
</script>
```

doesn't raise any exception

**Comment by roger-** [comment]
Try this (uses Chart.js): https://gist.github.com/roger-/3735ae315229999446a5

As-is it doesn't plot, but if you comment line 35 (which just prints) it works. For some reason uncommenting line 38 makes it crash.

**Comment by roger-** [comment]
I'm also having problems with [this](https://gist.github.com/roger-/ee3ce00f4cac350743b5) Highcharts code, which works fine in JavaScript [here](http://jsfiddle.net/g3urtb00/) (reported as another issue).

**Comment by kikocorreoso** [comment]
@roger- This ([fiddle](http://jsfiddle.net/c86h8otg/)) seems to work now.

Is this the expected behavior? Could this issue be closed?
