### ISSUE TITLE
Wrong behaviour with default arguments

### ISSUE THREAD

**Issue by Inspired1601** [brython-dev/brython#1745]
Try this:
```python
def test_func_incorrect(a=1, b, c):
    print(a, b, c)


test_func_incorrect(2, 3)
```

## Actual behaviour:
2 3 <Javascript undefined>

## Expected behaviour:
SyntaxError: non-default argument follows default argument

**Comment by PierreQuentel** [comment]
Thanks for reporting this. It happens that this bug was fixed a few days ago in a series of commit to improve detection of syntax errors, the latest development version should raise the appropriate exception.
