### ISSUE TITLE
Width et Height of the sgv generated when I use turtle lib

### ISSUE THREAD

**Issue by kegilko** [brython-dev/brython#1746]
Hello :) thanks for this amazing lib who allow to create a educational website for my students !

I have a question about the lib turtle, when I execute a code using this lib, a svg tag is dynamically generated in my DOM and the width is set to 500 (same for height)
How can I config the width and the height before the generation ? (ideally I want to set a value like unset, or auto)

Thanks for any help :)

**Comment by dragazo** [comment]
Width and height can be set with keyword args through `turtle.set_defaults()`. These are the settings I used for the site I just made, which uses the current size of the `turtle-div` element (do this before running the user script):

```py
turtle_div = document['turtle-div']
width = turtle_div.clientWidth
height = turtle_div.clientHeight
turtle.set_defaults(turtle_canvas_wrapper = turtle_div, canvwidth = width, canvheight = height)
```

If you look in the source, all of [these](https://github.com/brython-dev/brython/blob/8d5f3a914af59f23dfdd31610419e915614d90af/www/src/Lib/turtle.py#L36-L62) options are available through other keyword args.

**Comment by kegilko** [comment]
THank you for your helpfull help ! and sorry for the the late reply :)
