### ISSUE TITLE
ModuleNotFoundError: asyncio

### ISSUE THREAD

**Issue by mkondratyev85** [brython-dev/brython#1749]
I'm trying to reproduce following example from the [documentation](https://www.brython.info/static_doc/en/asyncio.html):

```python
import asyncio

@asyncio.coroutine
def test_wget(urls):
    results = []
    for u in urls:
        req = yield asyncio.HTTPRequest(u)
        results.append(req.response)
    return results

t = asyncio.ensure_future(test_wget(['http://google.com','http://wikipedia.org']))
```

But I get the `ModuleNotFoundError: asyncio`.

The way I reference brython is this:
```html
	<script src="https://cdn.jsdelivr.net/npm/brython@3.9/brython.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/brython@3.9/brython_stdlib.js"></script>
```

other modules from standard libraries (at least, `typing` and `zipfile`) imported without a problem.

**Comment by PierreQuentel** [comment]
The module __`asyncio`__ was removed in version 3.7.1, over 2 years ago, and replaced by __`browser.aio`__; the CPython module relies on blocking functions, which are not supported by the browsers execution model.

I forgot to remove the documentation page, it is done now.

Thanks for the report !
