### ISSUE TITLE
TypeError: Cannot read property 'stacking' of undefined

### ISSUE THREAD

**Issue by roger-** [brython-dev/brython#175]
I'm having trouble with the following Highcharts code :

```python
data = { 'chart': {
            'renderTo': 'container'
        },
        'series': [{
            'data': [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]
        }]
    }

chart = JSConstructor(window.Highcharts.Chart)(data)

p = [129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4, 29.9, 71.5, 106.4]
chart.series[0].setData(p)
```

which gives this error message:

```
brython.js:5212 RuntimeError: TypeError: Cannot read property 'stacking' of undefined
Traceback (most recent call last):
  module __main__0 line 27
    chart.series[0].setData(p)
```

Not sure if this is a Brython or JavaScript issue?

**Comment by baccrog** [comment]
@PierreQuentel

This appears to be related to my other issue. I played with the code and it seems that when I call `chart.series[0].setData(p)`, all the properties `chart.series[0].xxx` move to `chart.series[0].js.xxx` which breaks Highcharts. I'm assuming the namespace `.js` means something special to Brython?

So it seems that sharing a dictionary between Brython and JavaScript is not allowed? How can I work around this?

**Comment by roger-** [comment]
@PierreQuentel

This appears to be related to my other issue. I played with the code and it seems that when I call `chart.series[0].setData(p)`, all the properties `chart.series[0].xxx` move to `chart.series[0].js.xxx` which breaks Highcharts. I'm assuming the namespace `.js` means something special to Brython?

So it seems that sharing a dictionary between Brython and JavaScript is not allowed? How can I work around this?
