### ISSUE TITLE
`input()` calls blocking `prompt` before previous `prints` were processed

### ISSUE THREAD

**Issue by lebalz** [brython-dev/brython#1753]
Take the following example:

```py
from random import randint
a = randint(1, 20)
b = randint(1, 20)
print(f'{a} + {b} = ?')
answer = int(input('Result?'))
if answer == (a + b):
    print('Congrats,', answer, 'is correct')
else:
    print('Nooope')
```

## Expected Behavior

1. the question is printed
2. the input dialog (a js prompt...) is shown to the user
3. the answer is evaluated and feedback is printed...

## Current Behavior (Chrome, Edge, Safari)

1. the input dialog (a js prompt...) is shown to the user
2. the question is printed
3. the answer is evaluated and feedback is printed...

Only Firefox seems to handle it correctly (tested it on macOS Big Sur 11.2.3)

- Chrome ❌
- Microsoft Edge ❌
- Safari ❌
- Firefox ✅

**Comment by PierreQuentel** [comment]
I tried your example on Firefox, Chrome and Edge on Windows 10, it works as expected. It must be a bug in the iOS versions, since I suppose that the equivalent Javascript program also works unexpectedly:
```javascript
var a = parseInt(20 * Math.random()),
    b = parseInt(20 * Math.random())
console.log(a + '+' + b + '?')
var answer = prompt('Result ?')
if(answer == a + b){
  console.log('congrats')
}else{
  console.log('error')
}
```

**Comment by lebalz** [comment]
Hmm, weird.

I checked it on a win 10 Surface Book with Edge, Chrome and Firefox - only Firefox worked as expected in brython. Contrary, the proposed JS Code worked in each browser 🧐.

The following screen record was done with Chrome Version 92.0.4515.159 (Official Build, 64-Bit).

![Brython - Google Chrome 2021-08-25 08-52-16](https://user-images.githubusercontent.com/22354689/130741669-02048a98-1aef-492a-aa85-4f7994678d93.gif)

hmmm...

**Comment by PierreQuentel** [comment]
I didn't understand that you ran the code in the editor, where "print" is implemented by updating a DOM element. When there is a prompt in the code, some browsers refuse to update the DOM until the box is closed - I have no idea why, it is obviously wrong.

It is the same with this page:
```xml
<!doctype html>
<html>
<head>
<meta charset="utf-8">
</head>

<body>
<div id="zone"></div>
<script>
function write(msg){
    document.getElementById("zone").innerText += msg + '\n'
}

var a = parseInt(20 * Math.random()),
    b = parseInt(20 * Math.random())

write(a + '+' + b + '?')

var answer = prompt('Result ?')
if(answer == a + b){
    write('congrats')
}else{
    write('error')
}
</script>
</body>
</html>
```

In Chrome and Edge on Windows, the question is printed after prompt; only Firefox runs the code as expected. I'm afraid there is not much to do, other than slightly changing the logic:

```python
from random import randint
a = randint(1, 20)
b = randint(1, 20)
answer = int(input(f'{a} + {b} = ?'))
if answer == (a + b):
    print('Congrats,', answer, 'is correct')
else:
    print('Nooope')
```

**Comment by lebalz** [comment]
I see, thanks for the clarification.
I know that the logic-change solves the problem... i'm working with students, and when they are coming up with solutions like the above, which works in theory/cpython, i always try to not confuse them by correcting a "working solution"...  so thats why i was wondering if there is a solution.

Thanks, and thanks for the great library :)
