### ISSUE TITLE
datetime doesn't parse cartain time format

### ISSUE THREAD

**Issue by kacerjak** [brython-dev/brython#1755]
Hello Pierre,

I am trying to convert the following sting to a datetime object:
date = "Thu, 26 Aug 2021 00:00:00 GMT"
date = datetime.strptime(date, "%a, %d %b %Y %H:%M:%S GMT")

Getting the following error:
Error: no match 0 T 0 %

Is it a bug or am I doing something wrong?

Jakub

**Comment by PierreQuentel** [comment]
Thanks for the report @kacerjak !
