### ISSUE TITLE
`1 - None` raises AttributeError

### ISSUE THREAD

**Issue by austin-schick** [brython-dev/brython#1757]
Running

```python
1 - None
```

on Brython.info fails with 

```
AttributeError: __rsub__
```

While in CPython, the error is

```
TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'
```

Thanks for looking into this!

**Comment by PierreQuentel** [comment]
@austin-schick 
You are right, it fails on brython.info, but not in the development version, the big was fixed a few weeks ago (I am too lazy to search the commit...). Can you check ?
Thanks !

**Comment by austin-schick** [comment]
Yes, this seems to be fixed now on the development version :)
