### ISSUE TITLE
Unexpected errors with `$B.forbidden` keywords

### ISSUE THREAD

**Issue by austin-schick** [brython-dev/brython#1760]
I've been experiencing an unusual error when running code after calling `sys.settrace`.

If the code I run contains a parameter like "message" or "length" which is in `$B.forbidden`, it raises `Exception: <Javascript TypeError>: trace_func is not a function`. 

I haven't been able to simplify this to an easily reproducible example which runs on brython.info. However, I'm hoping this separate error shines a light on a place where some bugs might be lurking:

Running 

```pyhon
def f(message):
    pass

f()
```

on brython.info raises 

```
TypeError: f() missing 1 positional argument: $$message
```

with the `$$` still prepended to `message`.

Thanks for taking the time to check this out :)

**Comment by PierreQuentel** [comment]
It happens that the issue with `$$` prepended to the argument name was fixed a few days ago (commit 291b3c99bc8d0c8242081a396a04751874aa6942).

If you run the code with the latest development version, do you still have the unexpected behaviour after calling `sys.settrace` ?

**Comment by austin-schick** [comment]
Huh, I'm actually still seeing `$$` prepended to the variable name on the development version.

I pulled master, ran `server.py` from the root directory of the repository, and ran this in the editor from the local site:

```python
def f(message):
    pass

f()
```

I'm still seeing 

`TypeError: f() missing 1 positional argument: $$message` as the error output

**Comment by PierreQuentel** [comment]
My mistake. There is a shorcut for functions that only take positional arguments and I forgot to fix the issue in this case.

**Comment by austin-schick** [comment]
Thanks! I'm now seeing the correct error for

```python
def f(message):
    pass

f()
```

However, I'm still seeing the `trace_func is not a function` error. I did find a way to reliably reproduce the error though! Running the following code prints out `a`, then throws an error in the dev console, and never prints `b`. 

```python
import sys

def f(message):
    pass

def traceFn(frame, event, arg):
    if (event != 'call'): return
    
    for i in range(frame.f_code.co_argcount):
        varName = frame.f_code.co_varnames[i]
        frame.f_locals[varName]
    
    return traceFn

sys.settrace(traceFn)

print('a')
f('')
print('b')
```

**Comment by austin-schick** [comment]
List comprehensions seem to cause a similar error. This function

```python
def f(x):
    a = [i for i in range(10)]
```

can be swapped in for 

```python
def f(message):
    pass
```

and fails in the same way.

**Comment by austin-schick** [comment]
@PierreQuentel any progress tracking down the source of this bug? Let me know if there's any information I can provide, or if I can help in any way :)

**Comment by PierreQuentel** [comment]
Sorry Austin, I have been working on a different topic lately (implementing Python Abstract Syntax Tree to support module __`ast`__) and completely forgot this issue.

The issue with the missing parameter in a function is related to "forbidden" names - I will try to remove them, it is the cause of bugs difficult to find and fix.

The one with the list comprehension has a different cause, it's somewhere in the management of trace functions.

Both issues might take a few days to fix.

**Comment by PierreQuentel** [comment]
Austin,

With the 3 commits referenced above, the issues you reported are fixed, but I prefer to let you close the issue if you think it can be closed.

They represent important changes:
- to avoid conflicts with Javascript keywords or reserved names / attributes ("forbidden" names), the previous versions used aliased names (starting with "$$"); this new version uses other techniques
- many Brython scripts started with code that injected builtin names (eg `eval, super`, etc.) in the Javascript namespace, they are now all referenced as attributes of `__BRYTHON__.builtins`)

The issue with the list comprehension had 2 unrelated causes:
- the frame of comprehensions had an attribute `f_code` that missed many attributes, such as `co_argcount` and `co_varnames` that are used in the function `traceFn()`
- exceptions in the execution of trace functions (such as `AttributeError: f_code has no attribute 'co_argcount'`) were not reported

**Comment by austin-schick** [comment]
These fixes look good to me. I merged the latest master into my application and things seem to be running smoothly now.

Thank you @PierreQuentel!
