### ISSUE TITLE
Markdown doesn't support images

### ISSUE THREAD

**Issue by adamlwgriffiths** [brython-dev/brython#1761]
Images are links prefixed with !.
Ie: `![Alt Text](https://example.com/image.png)`

When passing this to Brython's markdown.mark, the result is an anchor with ! infront of it.
Ie: `<p>!<a href="https://example.com/image.png">Alt Text</a><p></p></p>`

But it _should_ generate `<p><img src="https://example.com/image.png></p>`

**Comment by PierreQuentel** [comment]
Thanks @adamlwgriffiths, I had missed this feature.

The commit also handles nested `[]` as in `[subscriptions (x[y]) in Python](http://subscriptions.python.org)`

**Comment by adamlwgriffiths** [comment]
Thanks for that, I was intending to do it myself but haven't had any time.
Much appreciated!
