### ISSUE TITLE
readlines() fail on linux line endings for files opened in text mode

### ISSUE THREAD

**Issue by alekibango** [brython-dev/brython#1763]
I have seen some failing  tests in 'file open/read'.
Later i was able to narrow the problem into method readlines.

```py 
import io
print(len(io.StringIO("foo\n\n\n").readlines()))
```
This gives wrongly 1 instead of 3.

This problem only occurs on linux files opened in text mode (line endings '\n'). Binary mode works fine. Also windows format is working right (having lines ending by '\r\n').

**readline()** works as expected.
Its **readlines()** which is somehow having broken implementation in javascript.

**Comment by alekibango** [comment]
This issue is behind already closed issue #1719 (which is still not fixed).

**Comment by PierreQuentel** [comment]
@alekibango 
Thanks for the report and the PR. The issue should be fixed with the commit above. I just moved the tests from issues.py to test_io.py and test_file.py.
