### ISSUE TITLE
ReferenceError: brython is not defined at onload

### ISSUE THREAD

**Issue by Whirlpool-Programmer** [brython-dev/brython#1765]
the full `index.html`:
```html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<script type="text/javascript" src="brython.js"></script>
<script type="text/javascript" src="brython_stdlib.js"></script>
</head>
<body onload="brython(1)">
<script type="text/python">
from browser import document
from browser.widgets.dialog import InfoDialog

def click(ev):
    InfoDialog("Hello", f"Hello, {document['zone'].value} !")

# bind event 'click' on button to function echo
document["echo"].bind("click", click)
</script>
<input id="zone">
<button id="echo">click !</button>
</body></html>
```

I have brython installed in the same directory..

```
directory
 |- index.html
 |- brython_stdlib.js
 |- brython.js
 |- demo.html
 |- README.txt
 |- unicode.txt
```

**Comment by Whirlpool-Programmer** [comment]
I figured out how to fix it..
I had to do `bython-cli --update`
but, in the docs it is written to run this command only when the folder has old brython versions "already" installed..

and I have installed it just today..

**Comment by 0xD3ADC0W** [comment]
Reopening this issue to clarify for anyone who finds this. I made a very similar mistake as I didn't pay enough attention reading the manual.

Your body tag should look like this

```<body onload="brython();">```

Not this:

```<body>```

Otherwise Bryhon will never load and "compile" your Python to JS on the fly.
