### ISSUE TITLE
IOError: Browsers cannot write on disk

### ISSUE THREAD

**Issue by Whirlpool-Programmer** [brython-dev/brython#1766]
Is there any way to create a file and write something to it?
i am trying to use `open(file, 'w+')` in a `https://` url

**Comment by PierreQuentel** [comment]
No, browsers execute programs in a "sandbox" which forbids writing on disk. This is for safety reasons : imagine anyone being able to write malicious code or huge amounts of data on your machine !

But you can edit a file and save it on disk with an explicit user action : see the example "select, read and save a local file" in the [demo page](https://www.brython.info/demo.html).

**Comment by Whirlpool-Programmer** [comment]
But the file i want to edit is not local..
It is actually in the server (the index.html too is there)

**Comment by PierreQuentel** [comment]
If the file is in the server, then only a script running in the server can write on the server's disk, not a program running in the browser.

**Comment by snazzy92** [comment]
Create a Rest API and send an Ajax call to it from Brython, have that API modify your file based on the details sent from Brython.

**Comment by Whirlpool-Programmer** [comment]
> Create a Rest API and send an Ajax call to it from Brython, have that API modify your file based on the details sent from Brython.

How may i do that?

**Comment by PierreQuentel** [comment]
For the Brython part, use the module [browser.ajax](https://www.brython.info/static_doc/en/ajax.html). It will send a POST request to the server, with information on the content to save on disk on the server side.
