### ISSUE TITLE
AttributeError: 'str' object has no attribute '__dict__' 

### ISSUE THREAD

**Issue by 0xD3ADC0W** [brython-dev/brython#1769]
Hi, my code does successfully execute in FireFox 91 64bit on Windows 10, however it prints this error to console every time it executes:

`AttributeError: 'str' object has no attribute '__dict__'`

This is my simple function that triggers this error:

```py
<script type="text/python3">
  from browser import *

  def sayHi(event):
    alert("Hello World")

  document["submit_button"].bind("click", sayHi)
</script>
```

Full message in my developer console:

```py
Uncaught Error: 
    $factory brython.min.js line 7 > eval:1
    obj_dict brython.js:14052
    loop brython.js:6011
    loop brython.js:6025
    run_script brython.js:5822
    loop brython.js:6026
    _run_scripts brython.js:5885
    brython brython.js:5806
    onclick index.html:1
brython.min.js line 7 > eval:1:2566
```

Any suggestions would be appreciated. Please ignore GitHub screwing up the formatting.

**Comment by PierreQuentel** [comment]
Sorry, I can't reproduce the issue. Can you provide the whole HTML page ?

**Comment by 0xD3ADC0W** [comment]
> Sorry, I can't reproduce the issue. Can you provide the whole HTML page ?

Hey, sorry for the slow reply. Today's been a blah day. Here's the full HTML. I feel like I'm possibly doing something wrong? I just followed the tutorial from the Brython website + a few other things I read online. HTML is not my forte.

```<!doctype html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/brython@3.9.5/brython.min.js"></script>

<title>
</title>
</head>
<body onload="brython()">
  <script type="text/python3">
  from browser import *

  def sayHi(event):
    alert("Hello World")

  document["submit_button"].bind("click", sayHi)
</script>

  <form class="shorten-url">
    <div class="text-center mb-4">
      <div class="jumbotron text-center">
        <h1>Test URL Shortner</h1>
    </div>

      <div class="col-sm-4 offset-md-4">
          <input type="text" id="url_input" class="form-control" placeholder="https://www.example.com" required autofocus>
          <br/>
          <button class="btn btn-lg btn-primary btn-block" id="submit_button" onclick="brython('sayHi()');">Shorten!</button>
        </div>
    </div>
  </form>
</body>
</html>```

I'm just learning to work with Brython and I'm really appreciating all the work all you contributors put into making it happen. Thanks again!

**Comment by PierreQuentel** [comment]
Thanks; the origin is the attribute `onclick="brython('sayHi()');"` in the `<button>` tag. You call function `brython()` with a string argument, when it expects either nothing, or a number (the debug level) or an object with the options.

If you remove this attribute, the code works without error; the "click" event is defined by the line `document["submit_button"].bind("click", sayHi)`.

In the commit referenced above I have added a warning if the argument of `brython() is invalid.

**Comment by 0xD3ADC0W** [comment]
> Thanks; the origin is the attribute `onclick="brython('sayHi()');"` in the `<button>` tag. You call function `brython()` with a string argument, when it expects either nothing, or a number (the debug level) or an object with the options.
> 
> If you remove this attribute, the code works without error; the "click" event is defined by the line `document["submit_button"].bind("click", sayHi)`.
> 
> In the commit referenced above I have added a warning if the argument of `brython() is invalid.

Thank you so much. This was a very early copy of the page before I realized my mistakes and fixed them on the dev branch. I do feel like a bit of an idiot now. I have been reading more of the Brython documents and I'll take more care and make sure to separate my Python and HTML in the future!
