### ISSUE TITLE
Error when trying to use emojis in a string in console

### ISSUE THREAD

**Issue by pamelafox** [brython-dev/brython#1772]
To replicate, go to:
https://brython.info/tests/console.html?lang=en

Type:
test = '🤔'

See:
File <string>, line 1
    test = "🤔"undefined
           ^
SyntaxError: invalid syntax

**Comment by PierreQuentel** [comment]
Thanks for the report @pamelafox !
The commit also fixes a bug with `ord()` for such strings.

**Comment by pamelafox** [comment]
Thanks for the quick fix! I can go back to demos full of emojis!

**Comment by pamelafox** [comment]
Actually, do you know when you plan to make the next release? I realize we bring in Python via package.json and a version number. (No worries if you're waiting for something bigger than a bug fix)

**Comment by PierreQuentel** [comment]
Hopefully in a few days, I would like to fix other bugs before.
