### ISSUE TITLE
[Question] How import external package form url

### ISSUE THREAD

**Issue by JoseitoOliveira** [brython-dev/brython#1773]
Hi, I'm trying import a external package from cdn URL and faileding.

I'm following this steps:
1 - Create a empyt enviroment;
2 - Install brython-cli and bs4 packages;
3 - Create brython package: "brython-cli --make_package bs4";
4 - Upload the bs4.brython.js file to a repo (https://github.com/JoseitoOliveira/brython-packages);
5 -  Use jsdelivr cdn: https://cdn.jsdelivr.net/gh/JoseitoOliveira/brython-packages@main/packages/bs4.brython.js;
6 - Use following html code: 
```
<html>
<head>
    <meta charset="utf-8">
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/brython@3.9.5/brython.min.js"></script>
    <script src="https://cdn.jsdelivr.net/gh/JoseitoOliveira/brython-packages@main/packages/bs4.brython.js"></script>
</head>
<body onload="brython()">
<script type="text/python">
    from browser import document
    from bs4 import BeautifulSoup
    
    document <= "Hello !"
</script>
</body>
</html>
```
when open this file, I received error:
![image](https://user-images.githubusercontent.com/45806413/134101067-60935d61-3a51-422a-933c-ee777b9e1f90.png)

How is the correct way to do this? Thanks.

**Comment by PierreQuentel** [comment]
I think you have confused `--add_package` (add a CPython package in the Brython folder) with `--make_package` (create a Brython package with the Python scripts in the folder).

**Comment by JoseitoOliveira** [comment]
Thank you for clarifying, @PierreQuentel .
