### ISSUE TITLE
dispatch an "change" event  ?

### ISSUE THREAD

**Issue by manatlan** [brython-dev/brython#1774]
Hi ...

when I 'm doing : 
```
        evt = window.HTMLElement("change")
        self.dispatchEvent(evt)
```
It tells me to use the "new" constructor 
so i try:
```
        evt = window.HTMLElement.new("change")
        self.dispatchEvent(evt)
```
And it tells me, that the constructor is illegal

What I'm doing wrong ?

**Comment by PierreQuentel** [comment]
`HTMLElement` can not be created with `new`, see [this post on stackoverflox](https://stackoverflow.com/questions/26220243/instantiating-new-htmlelement-in-typescript) for an explanation.

Here is a working example of simulating a click event on a button: 

```xml
<button id="btn">click !</button>

<script type="text/python3">
from browser import bind, document, window

@bind(document['btn'], 'click')
def click(ev):
    print('clicked')

evt = window.MouseEvent.new("click")
document['btn'].dispatchEvent(evt)
</script>
```

Yopu see "clicked" in the browser console when the script is run, and each time you click on the button afterwards.

**Comment by manatlan** [comment]
Ok ... Thanks a lot

Can you post an example to dispatch a "change" event, in place of "click" event ?

**Comment by PierreQuentel** [comment]
```xml
<input id="zone">

<script type="text/python3">
from browser import bind, document, window

@bind(document['zone'], 'change')
def change(evt):
  print('change !')

evt = window.Event.new('change')
document['zone'].dispatchEvent(evt)
</script>
```

**Comment by manatlan** [comment]
Perfect !
Thanks for taking time ...

brython is marvelous ! you made a great work !

**Comment by PierreQuentel** [comment]
Thanks for the kind words :-)
