### ISSUE TITLE
"$$" shows in AttributeError

### ISSUE THREAD

**Issue by cool-RR** [brython-dev/brython#1777]
I tried to find where I can find the JavaScript `history.pushState` function in Brython so I could use it from there. While searching, I got this: 

```
>>> browser.history
Traceback (most recent call last):
  File <string>, line 1, in <module>
AttributeError: $$history
```

Note the "$$". I'm not sure whether this bug is interesting, if not feel free to ignore.

But do please tell me how to use `history.pushState` in Brython :)

**Comment by PierreQuentel** [comment]
Hello Ram,

Following a huge set of changes recently, the `$$` no longer appears in the development version - the new release should be published tomorrow.

`history` is an attribute of `window`, so you can access it with `browser.wiondow.history`.

**Comment by cool-RR** [comment]
Thank you!
