### ISSUE TITLE
Subclassing an HTML tag is not possible

### ISSUE THREAD

**Issue by anpylar** [brython-dev/brython#1778]
`DOMNode.$factory` ends up invoking `klass.$factory`

https://github.com/brython-dev/brython/blob/c1584fb5334cbc1af784bcfe7ab5588d4753145d/www/src/py_dom.js#L608-L611

This works for the tags automatically generated when generating `browser.html` because a `$factory` function is attached to them. But a subclass of a tag won't have a `$factory` as a direct attribute, which means that the code in `py_dom.js` will fail.

https://github.com/brython-dev/brython/blob/c1584fb5334cbc1af784bcfe7ab5588d4753145d/www/src/builtin_modules.js#L324-L326

The code in the `$factory` attached to the tag class is also present in the tag `__new__` classmethod.

https://github.com/brython-dev/brython/blob/c1584fb5334cbc1af784bcfe7ab5588d4753145d/www/src/builtin_modules.js#L242-L258

Ideally, instead of returning a class with a `$factory` a real class should be returned (which is a `function` in the Javascript code) and this what should be invoked by `DOMNode.$factory` using `return klass()` instead of `return klass.$factory()`

**Comment by anpylar** [comment]
This small snippet shows the problem. 

```
<body onload="brython(1)">
<script type="text/python">
from browser import document
import browser.html

if True:
    class MyH1(object):
        def __init__(self, *args, **kwargs):
            print('I was called')

    h1 = browser.html.tags['H1']
    mynewh1 = type('mynewh1', (MyH1, h1,), {})
    browser.html.tags['H1'] = mynewh1

elem = document.select_one('H1')
print(elem)
</script>

<h1>hello</h1>
</body>
```

which generates the following error in the console

```
Javascript error TypeError: klass.$factory is not a function
    at Object.DOMNode.$factory (brython.js:14927)
    at DOMNode.select_one (brython.js:15271)
    at method (brython.js:6659)
    at eval (eval at $B.loop (brython.js:6534), <anonymous>:109:96)
    at $B.loop (brython.js:6534)
    at $B.inImported (brython.js:6517)
    at $B.loop (brython.js:6542)
    at $B.inImported (brython.js:6517)
    at Object.$B.loop (brython.js:6542)
    at $B.run_script (brython.js:6343)
```

Change `if True` to `if False` to skip the subclassing section and replacement of the tag class in the `browser.html` module and everything works

**Comment by PierreQuentel** [comment]
Thanks for the report, and glad to see that the Anpylar team is still active !

I have marked the issue as fixed but they may be other similar issues with subclasses of browser.html classes, don't hesitate to re-open it if necessary.

**Comment by anpylar** [comment]
Alive, used in several projects which for professional reasons cannot see the light of day.

I think I have found the time to try to adapt it to the much improved Brython.

I don't think the commit is actually what delivers the expected behavior. It removes the error but does not allow the customization of a tag with a subclass when using `select_one` or iterating over the `children` of a node.

The new style to create pythonic objects in Javascript with the `.$factory` is nice, but I think the DOM access code was designed with the old style in mind although the adaptation works for accessing `DOMNode` instances it may need extra rework to fit into the pythonic world.

**Comment by anpylar** [comment]
Issue re-opening is an issue (because it was closed by someone else and not by myself)

In any case there is a pull-request #1780 which addresses the issue by leveraging `$B.$call` from `py_utils.js`, which looks into the nature of the passed argument and uses `$factory` or `$instance_creator` as appropriate, which effectively allows subclasses to take over.

**Comment by anpylar** [comment]
A test snippet with pull request #1780 active

```python
<body onload="brython(1)">
  <script type="text/python">
from browser import document
import browser.html

elem = document.select_one('H2')
print(elem)

class H1:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        print('H1 Subclass in play')

h1 = browser.html.tags['H1']
mynewh1 = type('mynewh1', (H1, h1,), {})
browser.html.tags['H1'] = H1

elem = document.select_one('H1')
print(elem)
  </script>

<h1>hello 1</h1>
<h2>hello 2</h1>
</body>
```

The output

```
<HTMLHeadingElement> 
brython.js:7559 H1 Subclass in play 
brython.js:7559 <__main__.H1 object> 
```

It shows that fetching the `H2` tag returns a standard DOMNode instance whereas, after subclassing `H1`, fetching the `H1` tag returns a instance of the subclass which has been generated using `type`

**Comment by PierreQuentel** [comment]
I have read your PR and re-read the current implementation, and my conclusion is that neither is really correct.

Basically, I don't think it's natural that getting a reference to an _existing_ object (the H1 element), eg by `select_one()`, would trigger the initialization of a _new_ Python object.

My proposal would be:
- to simplify `DOMNode.$factory` so that it just returns the DOM element unmodified (don't set its attribute `__class__`)
- to change `$B.get_class()` in __`py_utils.js`__ so that, among the objects that don't have `__class__` set, the class of DOM nodes that have tagName set is `browser.html.tags[tagName]`

In your example, it means that `H1.__init__()` would not be called, but the dom nodes with tagName "H1" are instances of `mynewh1`.

**Comment by PierreQuentel** [comment]
I have implemented these changes in commit 2467392. It doesn't seem to break anything.

This example succeeds:

```xml
<script type="text/python">
from browser import document, console
import browser.html


class MyH1(object):

    def __init__(self, *args, **kwargs):
        # never called !
        print('I was called')

    def show(self):
        return '<I am a MyH1 object>'

h1 = browser.html.tags['H1']
mynewh1 = type('mynewh1', (MyH1, h1,), {})
browser.html.tags['H1'] = mynewh1

elem = document.select_one('H1')
assert str(elem) == '<HTMLHeadingElement id="myH1">', str(elem)
assert elem.__class__ is mynewh1
assert elem.show() == '<I am a MyH1 object>'
assert isinstance(elem, mynewh1)

elem = document["myH1"]
assert str(elem) == '<HTMLHeadingElement id="myH1">', str(elem)
assert elem.__class__ is mynewh1
assert elem.show() == '<I am a MyH1 object>'
assert isinstance(elem, mynewh1)
</script>

<div id="test">
<h1 id="myH1">essai <span>1778</span></h1>
</div>
```

**Comment by anpylar** [comment]
To my *brython-untrained* eyes, the paradigm change seems groundbreaking. Let me try to elaborate

- I do fully agree that a call to `select_one` or iterating over `children` should not generate a new *Python* class instance each and every time. But the entry poing in `DOMNode.$factory` seems to be there exactly to avoid this

`select_one` ends up calling the factory

```python
    return DOMNode.$factory(res)
```

and `DOMNode.$factory` starts by making a check

```python
    if(elt.__class__ === DOMNode){
        return elt
    }
    if(typeof elt == "number" || typeof elt == "boolean" ||
            typeof elt == "string"){
        return elt
    }
...
...
    if(elt.__class__ === undefined && fromtag === undefined) {
```
Only if `elt` (the DOM element) doesn't carry a `__class__` payload and the `fromtag` flag has not been used, a *Python* class instance will be returned. If the element has been wrapped before by `DOMNode` or a class thereof.

`__class__` not being set directly in the `DOMNode.$factory` but in the actual factory in the `browser.html` module

https://github.com/brython-dev/brython/blob/93cebbf473a72377bd76965d650c0fb1d8fb6067/www/src/builtin_modules.js#L282

As I see it, only once in the lifecycle of an element, will a *Python* object be created and instantiated for the element, which then always returns the already existing wrap.

It may well be that the initial test in `DOMNode.$factory` needs a correction

```python
    if(elt.__class__ === DOMNode){
        return elt
    }
```

This is checking specifically for `DOMNode` and should probably be checking `if elt.__class is a subclass of DOMNode`

**Comment by anpylar** [comment]
Probably with this code ...

```python
    if(_b_.isinstance(elt, DOMNode) {
        return elt
    }
```

**Comment by PierreQuentel** [comment]
In the latest commit, `DOMNode.$factory` is just

```javascript
DOMNode.$factory = function(elt){
    return elt
}
```

**Comment by anpylar** [comment]
Indeed I saw the change, but I think initialization is key. Without proper initialization control subclassing makes no sense.

I have tried some minor code modifications to the previous code, which I believe fit all requirements

  - element (python) objects are only instantiated once when an element is fetched (subclass or not)
  - initialization works for the standard class and subclasses
  - the `$factory`/`makeFactory` conumdrum is solved by using the existing `TagDict` initialization code (in `__new__` and `__init__`)

A clean-up of the code and logging made here and there to trace things is needed and it is late. It will have to wait before being proposed tomorrow or the day after tomorrow.

**Comment by PierreQuentel** [comment]
I still disagree that any kind of "magic" initialisation should be performed when getting a reference to an existing object.

Here is my new proposal, implemented in the current development version:

1 - if an element is in the HTML code for the page, its class is determined by the tag name. For instance, the class of the element inserted by
```xml
<h1>test</h1>
```
is `browser.html.H1`.

2 - new elements can be added to the DOM tree with a (subclass of a) HTML tag class, and in this case, `__init__()` is naturally called

```python
class MyH1(browser.html.H1):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        print('initializing MyH1 object')

    def show(self):
        return '<I am a MyH1 object>'

new_elt = MyH1('new element') # prints the message in __init__
document <= new_elt

# check that the element is an instance of MyH1
assert isinstance(new_elt, MyH1)
assert new_elt.show() == '<I am a MyH1 object>'
```

Since in this case the class cannot be determined by the tag name, an attribute `__class__` is set to the instance.

3 - instead of performing an action when you get a reference to the object, you can explicitely call a function on a selection of items:

```python
for item in document.select(css):
    init(item)
```

This can include setting the class of existing elements if necessary:

```python
for item in document.select('H1'):
    item.__class__ = MyH1
```

**Comment by anpylar** [comment]
> Javascript-based Python wrapper

It's one of the many objects exposed to the Python implementation, which are fully implemented in Javascript (by defining a `dict` and several functions like `$factory`)

No issues. It's a change in the current model and adaptation to it is the way to go.
