### ISSUE TITLE
Bug with int() and tuples?

### ISSUE THREAD

**Issue by conversy** [brython-dev/brython#178]
Hi everyone,

maybe I'm dumb but the following code:

R,G,B = 0, 291.14860763775437, 345.03640062906027
print(R,G,B)
Ri, Gi, Bi = int(R+.5),int(G+.5),int(B+.5)
print(Ri,Gi,Bi)

yields with CPython:

0 291.14860763775437 345.03640062906027
0 291 345

and with Brython 3.1.1:

0 291.14860763775437 345.03640062906027
0.5 291 345

**Comment by PierreQuentel** [comment]
Fixed by commit 35f75b2
