### ISSUE TITLE
zlib decompress bug (I guess)

### ISSUE THREAD

**Issue by l-Fingon-l** [brython-dev/brython#1786]
Hi!
For the sake of concision, let's start with an example: 
```html
<!doctype html>
<html>
    <head>
        <script type="text/javascript" src="brython.js"></script>
        <script type="text/javascript" src="brython_stdlib.js"></script>
    </head>
    <body onload="brython()">
        <script type="text/python">
            import zlib

            size = 3665
            bytes = open('compressed_block.txt', 'rb').read(size)
            data = zlib.decompress(bytes)

            print(data)
        </script>
    </body>
</html>
```
|=================================
Compressed block used in the example above: [compressed_block.txt](https://github.com/brython-dev/brython/files/7297609/compressed_block.txt) (3665B)
The original [uncompressed_block](https://github.com/brython-dev/brython/files/7297610/uncompressed_block.txt) (8192B)
|=================================

![image](https://user-images.githubusercontent.com/70348701/136293750-e0c39eb7-e020-4393-9990-0045513ceb4e.png)
The compressed block is a valid deflate-compressed 8192-byte binary string (3665 as compressed).  

## A little elaboration
I'm trying to move an existing and mature python algorithm to the browser.
* The original algorithm strays from **decompress** towards **decompressobj** as it works with large chunks of data. This particular block is not that big, though.
* The compression method (CM) is 8 -> `78 01` header. Exactly what is supposed by [your implementation of zlib](https://github.com/brython-dev/brython/blob/master/www/src/Lib/zlib.py), I think?
* The original algorithm stores the uncompressed and compressed block size and checks if the size is as expected after the decompression.  

In order to check if the algorithm was still valid I rewrote the zlib implementation a wee bit, eliminating the assertions at **Lib/zlib.py** and precompiled it to ***brython_modules.js*** with `brython-cli --modules`:
```py
785         assert a == a1        =>        # assert a == a1
786         assert b == b1        =>        # assert b == b1
```
The block got parsed. But the next issue was with an algorithm checking whether the uncompressed data is the same as it was expected to be.
And it was not. The original block was 8192 bytes long. The uncompressed one - 8191. Latter comparisons revealed a lot of differences (most of the content, however, was correct, which I found quite exciting):

![image](https://user-images.githubusercontent.com/70348701/136296379-e6c049fe-0cf5-48a9-a2d0-73325eaa6544.png)

I am not yet sure if it is a bug in zlib implementation of Brython or a logic error to allow **decompress** to be used instead of **decompressobj** as is supposed in the original algo.
Worth mentioning, the original version does not work with plain **decompress** and gives you a 
`zlib.error: Error -5 while decompressing data: incomplete or truncated stream`

---
All in all, I would hugely appreciate any early comments, such as if there is a chance the issue would be explored and if so, what could be the realistic dates of it being fixed (a month, a year, a decade? Just so any plans involving the usage of this feature could be made. I totally get if this might not be any of your prioritises for the nearest future).
If any help is needed, I might do my best in order to provide it as well.

Cheers

**Comment by PierreQuentel** [comment]
Just starting to investigate this issue. As you mention, the compressed data cannot be decompressed by `zlib.decompress`, so my first reaction is, it's ok if the Brython version also fails, even if it is with a different error message :-)

Even more puzzling, with CPython:

- it can be decompressed to a 8192 bytes object with `zlib.decompressobj().decompress(data)`
- when compressing again this 8192 bytes object, the only combination of `level` and `wbits` such that the length of `recompressed` in the code below is 3665 is level = 2 and wbits = 11
```python
cobj = zlib.compressobj(level=2, wbits=11)
recompressed = cobj.compress(decomp) + cobj.flush()
print(len(recompressed))
```
- but `recompressed` is not equal to the original in compressed_block.txt...

Complete code is below. Before investigating inside Brython it would be better to understand this behaviour.

```python
import zlib

size = 3665
data = open('compressed_block.txt', 'rb').read()
decomp = zlib.decompressobj().decompress(data)
print(len(decomp))

cobj = zlib.compressobj(level=2, wbits=11)
data1 = cobj.compress(decomp) + cobj.flush()
assert len(data1) == 3665
print(data1 == data)
```

**Comment by l-Fingon-l** [comment]
Thank you so much for the update. Will try to investigate this one a bit more as soon as I'm back home (tomorrow morning).
One little clue that may be useful as well is that the ***encoder*** for the data is using the native C zlib implementation. I don't yet know if that tells anything important.
