### ISSUE TITLE
'data' property missing from WebSocket event

### ISSUE THREAD

**Issue by roger-** [brython-dev/brython#179]
Hi,

The following code seems to give an exception due to `data` not being in the `event` websocket response (latest Chrome, trunk Brython, text data):

``` python
ws = websocket.WebSocket("ws://127.0.0.1:9999")
ws.bind('message', on_message)

def on_message(event):
    console.log(event)
    js = json.loads(event.data) # exception here due to no data attribute
    ...
```

I see properties in `event` like `bubbles`, `cancelBubble`, `currentTarget`, etc. but no actual data.

**EDIT**:

Same behavior in Firefox + IE, and pure JavaScript WS works. The `data` property is being removed when converting a JS event to a Brython `DOMEvent`.

**Comment by PierreQuentel** [comment]
Sorry for the very late answer...

I couldn't reproduce the bug. The example in the documentation works, and it prints `evt.data` in method `on_message`. Can you post a complete example where you get this error ?
