### ISSUE TITLE
`open` does not open files from a virtual file system

### ISSUE THREAD

**Issue by anpylar** [brython-dev/brython#1796]
Test file system

```javascript
__BRYTHON__.add_files({
    "hello.txt": {
        "content": "aGVsbG8gaXMgdGhlIHdheSB0byBnbwo=\n",
        "ctime": 1634418826.57,
        "mtime": 1634418828.0
    }
})
```

Test code
```html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script type="text/javascript" src="brython.js"></script>
  <script type="text/javascript" src="hello.vfs.js"></script>
</head>

<body onload="brython(1)">
<script type="text/python">
hfile = open('hello.txt', 'r')
print(hfile)
hdata = hfile.read()
print(hdata)
</script>
</body>
</html>
```

And the output in the console is: 

```
Javascript error TypeError: Cannot read properties of undefined (reading 'length')
    at $url_open (py_builtin_functions.js:2993)
    at eval (eval at $B.loop (loaders.js:378), <anonymous>:15:51)
    at Object.$B.loop (loaders.js:378)
    at $B.run_script (py2js.js:12939)
    at Object.$B.loop (loaders.js:398)
    at $B.parser._run_scripts (py2js.js:13133)
    at $B.parser.brython (py2js.js:12878)
    at onload ((index):48)
py_exceptions.js:697 test is js exc is recursion error TypeError: Cannot read properties of undefined (reading 'length')
    at $url_open (py_builtin_functions.js:2993)
    at eval (eval at $B.loop (loaders.js:378), <anonymous>:15:51)
    at Object.$B.loop (loaders.js:378)
    at $B.run_script (py2js.js:12939)
    at Object.$B.loop (loaders.js:398)
    at $B.parser._run_scripts (py2js.js:13133)
    at $B.parser.brython (py2js.js:12878)
    at onload ((index):48) TypeError: Cannot read properties of undefined (reading 'length')
py_exceptions.js:160 print stack ok []
py_utils.js:1106 Traceback (most recent call last):
RuntimeError: TypeError: Cannot read properties of undefined (reading 'length')
```

The problem, a long guess, seems to be code that wasn't udpated for a file found in `$B.files` here:
https://github.com/brython-dev/brython/blob/33aeaab551f1b73209326c5a0aecf98642d4c126/www/src/py_builtin_functions.js#L2909-L2919

because the other cases put the result in `result.content`, which is not happening here

**Comment by PierreQuentel** [comment]
Thanks ! I must admit I had completely forgotten this feature...

**Comment by anpylar** [comment]
I think the feature is useful. And a small extension would make it more useful

The current logic (simpflied)

  - Open from `$B.files` if an entry is available there
  - if not and the protocol is not `file` => launch an `XMLHttpRequest`

As a user I may want to `open` a file without going to the network. If the file is not available inside `$B.files` I may want to simply stop there.

For that use case I see two potential implementation options

  - Extra keyword-argument for `open`. Something like: `_only_local` which is a `boolean` with default value `False` to avoid altering the current behavior
     If the file is not in `$B.files` either `None` can be returned or an `Exception` (`FileNotFound`) be raised

  - Expose a function which allows testing for the presence of a an entry in `$B.files`
