### ISSUE TITLE
Typo of Exceptions

### ISSUE THREAD

**Issue by mingxiaowei** [brython-dev/brython#1814]
```
>>> er = IndexError("hello")
>>> er
IndexError('hello')
>>> str(er)
'hello'
>>> repr(er)
"IndexError('hello')"
>>> df = IndexError()
>>> df
IndexError)
>>> str(df)
''
>>> repr(df)
'IndexError)'
>>> KeyError()
KeyError)
```
That was what I got when I tried to construct an exception object. Looks like there's an additional parenthesis in the string returned by the `repr()` method when no message was passed in to the constructor

**Comment by PierreQuentel** [comment]
Thanks for the report @mingxiaowei !
