### ISSUE TITLE
Can't import file module

### ISSUE THREAD

**Issue by stasOrel** [brython-dev/brython#1818]
I am trying to import python file from root directoty (as written in doc), but when i run my project i get error 404, file was not found

And if it has value, i also use flask and run my local server using flask.

**My project directory:**
![projectDir](https://user-images.githubusercontent.com/44466884/141690250-c7e2cf41-8eca-4bd8-834a-e4d557b78608.jpg)

**My Brython code(in index.html):**
```
<script type="text/python" id="script333">
from browser import document, console
import blockchain_active
.....
</script>
```
**Error screenshot:**
![Error404](https://user-images.githubusercontent.com/44466884/141690402-0c4ffbba-0e74-4c54-8f22-3e98308d9eed.jpg)

**Comment by PierreQuentel** [comment]
By default, Brython can only import modules in the standard library (provided you have included __`brython_stdlib.js`__ in the HTML page).

__`blockchain_active`__ is not in it (in fact, a Google seach didn't return anything), so you have to provide the means to import it (check the section [Implementation of import](https://www.brython.info/static_doc/en/import.html)).

Note that if it is a package with C modules in it, Brython will not be able to use it, it can only handle pure-Python modules.
