### ISSUE TITLE
Chained comparison does not mix with list comprehension any more

### ISSUE THREAD

**Issue by coproc** [brython-dev/brython#1820]
`[0 < a < 2 for a in (0,1)]` should give `[False, True]`, but with the latest Brython version an exception is raised:

    NameError: name 'a' is not defined. Did you mean: 'a'?

Also `[(0 < a < 2) for a in (0,1)]` gives the same exception, whereas `[0 < a and a < 2 for a in (0,1)]` behaves as expected.

**Comment by PierreQuentel** [comment]
Thnaks for the report @coproc !

The bug exists in release 3.10.3, but was fixed a few days ago with commit 77b33a97176d61e2db0738af862c67a2c2938b88.

Can you check and close the issue if the bug has disappeared ?

**Comment by coproc** [comment]
Perfect - works again!
