### ISSUE TITLE
Reuse another script module ... is it possible ?

### ISSUE THREAD

**Issue by manatlan** [brython-dev/brython#1822]
I'm trying to import another module (containing a myfunction() method), to do something like that :

```html
<script type="text/python" src="mymodule.py" id="mymodule"></script>

<script type="text/python">
mymodule.myfunction("hello")
</script>
```

It's not possible like that ^^ ...

is there another way to reach my needs (by calling a `__BRYTHON__.internalmethod()` ?!)

It could be great to be natively supported, not ?!

**Comment by PierreQuentel** [comment]
All you have to do is to import the module by its `id`:
```python
from browser import document
import module

document.body <= module.hello()
```

**Comment by manatlan** [comment]
thanks @PierreQuentel  ...
I knew that ;-)

I'd just posted an idea, to enhance brython ... to make it more modular.
(and, for example, to avoid the trouble on import/ajax style ([Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/."))

**Comment by PierreQuentel** [comment]
@manatlan I appreciate the intention, but I don't understand how what you suggest improves modularity.

In the examples you provide, the deprecation message doesn't show.

**Comment by PierreQuentel** [comment]
I am closing the issue. If you have an answer to the question in the message above feel free to reopen it.
