### ISSUE TITLE
ajax and aio in brython append an additional numeric parameter to requests

### ISSUE THREAD

**Issue by a23s4a** [brython-dev/brython#1823]
Hello
I am not sure if it is brython specific or ajax specific but when I do `ajax.get()` or `aio.get()` in my code (the server is django + drf), some string is appended to all of my requests:
The original url is:
"http://127.0.0.1:8080/sdp/api/servicerequests/?engineer=1"
The url sent is:
"http://127.0.0.1:8080/sdp/api/servicerequests/?engineer=1&1637123875183"
This query is still functional and returns the data I expect.
But when I use a pagination it looks even worse:
The paginated response expected is:
```
"{
    "count": 12,
    "next": "http://127.0.0.1:8080/sdp/api/servicerequests/?engineer=1&page=2",
..."
```
The actual paginated response is:
```
"{
    "count": 12,
    "next": "http://127.0.0.1:8080/sdp/api/servicerequests/?1637123875183=&engineer=1&page=2",
 ...
```

When I try to use `response['next']` as a url to query the next slice of data using `ajax.get()` it reaches the server that way:
`"http://127.0.0.1:8080/sdp/api/servicerequests/?1637123875183=&engineer=1&page=2?1637124114154"`

This malforms the request completely and the server does not understand it and returns an error.

Is this the expected behavior? Should I just do some cleanup using urlparse to remove that parameter from the url?

**Comment by PierreQuentel** [comment]
The additional parameter (based on current time) is added to avoid using browser cache: if the file has changed since the last request, `get()` returns the new version.

To avoid this and remove the parameter, set the keyword attribute `cache`:
```python
ajax.get(url, cache=True)
```

**Comment by a23s4a** [comment]
I see, thank you very much!
