### ISSUE TITLE
`json.loads` will returned wrong data.

### ISSUE THREAD

**Issue by tasuren** [brython-dev/brython#1824]
Hello.
I tried to load json like the following on brython.
```json
{"status":200,"message":"ok","data":{"login":true,"user_name":"tasuren#5161","id":634763612535390209,"language":"ja","icon":"https:\/\/cdn.discordapp.com\/avatars\/634763612535390209\/b7ac245fe341cc87873c23e911af8cbd.png?size=1024"}}
```
But `json["data"]["id"]` of the dictionaries returned by `json.loads` were wrong.
```python
{'status': 200, 'message': 'ok', 'data': {'login': True, 'user_name': 'tasuren#5161', 'id': 634763612535390200, 'language': 'ja', 'icon': 'https://cdn.discordapp.com/avatars/634763612535390209/b7ac245fe341cc87873c23e911af8cbd.png?size=1024'}}
```
original: `634763612535390209`
after: `634763612535390200`

Also, the same thing happened with the editor on the official Brython website.

**Comment by tasuren** [comment]
And I tried to dump json like the following on brython.
```python
{'command': 'settest setting_test_channel', 'kwargs': {}, 'guild_id': 771732762503544800, 'channel_id': '773488498518786000', 'user_id': 634763612535390200, 'category': 'guild'}
```
But error happened.
```python
Traceback (most recent call last):
  File https://www.brython.info/tests/editor.py, line 119, in run
    exec(src, ns)
  File <string>, line 3, in <module>
  File VFS.json.py, line 190, in dumps
    return _json.dumps(obj,1,**kw)
TypeError: Object of type int is not JSON serializable
```

I tried this in Python instead of Brython and did not encounter these bug.

**Comment by PierreQuentel** [comment]
Thanks for the report @tasuren !
I rewrote the JSON decoder. The previous version used the Javascript JSON object, which doesn't correctly handle long integers.

**Comment by tasuren** [comment]
> Thanks for the report @tasuren !
> I rewrote the JSON decoder. The previous version used the Javascript JSON object, which doesn't correctly handle long integers.

Thank you for fixing. 👍
