### ISSUE TITLE
the module "aio" should be brython, not in stdlib !

### ISSUE THREAD

**Issue by manatlan** [brython-dev/brython#1825]
Afterwards ... the async/await features are in plain javascript nowadays ...
So the "async/await" brython features should be in the main brython ... not in stdlib.
(It's annoying, to be forced to include "stdlib" to be able to use async/await things)

I know I can streamline my stdlib with brython-cli ... but, by default : aio should be in brython (no in stdlib)

no ?

**Comment by PierreQuentel** [comment]
It's hard to make a statistic, but it's likely that the vast majority of Python programs don't use async / await. I also want to keep __`brython.js`__ as small as possible. For these reasons I don't agree that aio should be included, sorry.
