### ISSUE TITLE
critical bug: non-compliance after the __imul__ operator is overrided

### ISSUE THREAD

**Issue by wkta** [brython-dev/brython#1827]
Imagine I manipulate python objects that are instances of a `Vector2` class
I override the magic method `Vector2.__imul__`
so i can multiply in place vectors by constants:
`a_vector *= lambda`
`another_vector *= gamma`
and this works fine!

But now, if I use not independant variables but a list of objects:
`allvectors = [ Vector2(random.random(), random.random()) for _ in range(33) ]`

the following valid syntax in python does not work properly in Brython.
No error is raised but wrong results are produced:

`allvectors[0] *= lambda`
`allvectors[1] *= gamma`
etc.

**Comment by wkta** [comment]
After more testing I notice that the bug occurs only if `__imul__` has been overrided "in a weird way"
that is, if the instance has been cloned,
modified, then the reference on the new object is returned…

On the contrary if `__imul__` returns a reference on `self`, Brython works fine.

This is still a critical bug since computation results from running the code within the python interpreter differ totally while the source-code is the same. (= non-compliance)

**Comment by wkta** [comment]
Minimal example to reproduce the bug:

    <html>
    <head>
    <meta charset="utf-8">
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/brython@3.10.3/brython.min.js">
    </script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/brython@3.10.3/brython_stdlib.js">
    </script>
    </head>
    <body onload="brython()">
    <script type="text/python">
	import random
	class Vector2:
		def __init__(self,a,b):
			self.x,self.y=a,b
		def clone(self):
			return Vector2(self.x,self.y)
		def __imul__(self,k):
			res = self.clone()
			res.x*=k
			res.y*=k
			return res

	allvectors = [Vector2(random.random(),random.random()) for _ in range(33)]
	print(allvectors[0].x, allvectors[0].x)
	allvectors[0] *= 25.7

	print('imul op. done')
	print(allvectors[0].x, allvectors[0].x)  # shows that brython ignores the imul op.
	</script>
	</body>
	</html>

**Comment by PierreQuentel** [comment]
Thanks for the report @wkta !

To fix the issue I dramatically simplified the implementation of augmented assignments, something I should have done long ago...
