### ISSUE TITLE
the Ajax object returned by ajax.put() does  not seem to contain usable data

### ISSUE THREAD

**Issue by a23s4a** [brython-dev/brython#1828]
According to manual from [brython ajax page](https://brython.info/static_doc/en/ajax.html) "Callback functions take a single argument, the Ajax object. In the function body, the following attributes and methods of this object can be used: `status`, `text`, `json`, `xml`, `read()`"
When I do `ajax.get()` in my code the Ajax object returned from this call really has these methods, so I can use `json_result = req.json` in my callback function and use `req.json` or `json_result` as a dictionary.
`print(req.json)` or `print(req.text)` also shows in the console what I expect to see.
But when I do `ajax.put()` in my code the Ajax object returned seems to be something different:
when I use print(req.json) in my callback function it shows:
```
Traceback (most recent call last):
  File http://127.0.0.1:8080/static/python-scripts/main.py line 153, in my_put_callbackfunc
    print(req.json)
ValueError: bytes must be in range(0, 256)
```
The PUT action itself is executed successfully and I see the correct change to the database object and the browser shows the object returned as json object with the changes I expect.
I do not quite understand if this is the expected behavior.

**Comment by PierreQuentel** [comment]
Sorry for the late reply :-(

I could not reproduce the bug when I tested with a simple example: in the callback function for POST and PUT requests for which the server returns the same JSON string, `req` has the same attributes, including `json`.

Could you provide more information:
- the complete traceback, including the Javascript error stack
- the server response in the browser console, in the "Network" tab

**Comment by a23s4a** [comment]
Hello
Sorry, I did not have time to wait and rewrote the whole frontend to pure javascript
