### ISSUE TITLE
Discrepancy between exec'ing a Python string and a compiled code object visavis context dictionary 

### ISSUE THREAD

**Issue by rbarve** [brython-dev/brython#183]
I find an inconsistency between a compiled code object being exec'd and an unpreprocessed code statement being exec'd in regards to the update of accompanying context dictionary --

Brython 3.1.1 on Netscape 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.39 Safari/537.36

x=4
cd=dict(globals())
cd.update(locals())
exec("x=x+4",cd)
x
4
cd['x']
8
y=5
yd=dict(globals())
yd.update(locals())
co=compile("y=y+4","","exec")
exec(co,yd)
9
yd['y']
5

In CPython:
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.

x=4
cd=dict(globals())
cd.update(locals())
exec("x=x+4",cd)
x
4
cd['x']
8
y=5
yd=dict(globals())
yd.update(locals())
co=compile("y=y+4","","exec")
exec(co,yd)
yd['y']
9
y
5

**Comment by earney** [comment]
This has been fixed in the repo.   If you find a related bug, please open another issue.
