### ISSUE TITLE
Development URLs don't seem to work

### ISSUE THREAD

**Issue by virtuald** [brython-dev/brython#1831]
According to the README, one should be able to include the master version of Brython via:

```html
<script type="text/javascript" src="https://raw.githack.com/brython-dev/brython/master/www/src/brython.min.js"></script>
<script type="text/javascript" src="https://raw.githack.com/brython-dev/brython/master/www/src/brython_stdlib.js"></script>
```

However, I get cryptic errors:

```
RuntimeError: TypeError: $B.create_python_ast_classes is not a function
```

I did figure out that I had to manually include `py_ast.js` in my scripts, but that led to another error, which required another include, and so on. I did eventually hit an error I couldn't figure out, so I've given up for now.

Is the development URL intended to work, or did it work a long time ago but it's broken now? Would be good to remove it from the README (or add some instructions on how to use it).

**Comment by PierreQuentel** [comment]
The README mentions __`brython.js`__, not __`brython.min.js`__ which doesn't seem to be updated often, but anyway I was not able to reproduce the issue, I don't get any error message.

**Comment by virtuald** [comment]
I encounter the error with this test page running locally (python -m http.server) on OSX, with Chrome.

```html
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <script type="text/javascript" src="https://raw.githack.com/brython-dev/brython/master/www/src/brython.js"></script>
    <script type="text/javascript"
        src="https://raw.githack.com/brython-dev/brython/master/www/src/brython_stdlib.js"></script>

</head>

<body onload="brython()">
    <script type="text/python">
    import dataclasses
</script>

</body>

</html>
```

**Comment by PierreQuentel** [comment]
Thanks, I could reproduce this bug. It should be fixed with this commit, once the version on githack is updated.
