### ISSUE TITLE
[Question] how can I Run brython without a server?

### ISSUE THREAD

**Issue by demetere** [brython-dev/brython#1832]
Hello there, I am trying to integrate Brython with my index.html 

It can run on a python server perfectly. I have one brython.py python file and I can run it with the server. Now I want to run it without a python server. What are my options to do that? I don't want to copy the code and include it in index.html. I want to keep a python file but to be able to use it without a python server? 

Is it possible? 
Thanks

**Comment by PierreQuentel** [comment]
Hello,

The limitations when you run Brython without a server are documented [here](https://www.brython.info/static_doc/en/file_or_http.html). Does it answer your question ?

**Comment by demetere** [comment]
> Hello,
> 
> The limitations when you run Brython without a server are documented [here](https://www.brython.info/static_doc/en/file_or_http.html). Does it answer your question ?

So it means that I can not use "<script type="text/python" src="test.py"></script>" that without python server, because with python server I can load files like that. 
I thought maybe there is some way to precompile python file into javascript and load like that.

**Comment by PierreQuentel** [comment]
Precompiling to Javascript is not what Brython is made for, but you can package a set of Python modules / packages in a Javascript script with the command `brython-cli --modules` and load the file generated by this command (__`brython_modules.js`__) in the page.

Then you will be able to import these modules / packages in a program embedded in the page.

```xml
<html>

<head>
<script src="/path/to/brython.js"></script>
<script src="/path/to/brython_modules.js"></script>
</head>

<body onload="brython()">
<script type="text/python>
import any_module_in_brython_modules
</script>
</body>

</html>
```

This works with or without a server.

**Comment by demetere** [comment]
![image](https://user-images.githubusercontent.com/52292287/145091349-ab2debec-9b00-4550-84af-07716b87e69e.png)

This is how the project structure looks like.

I am running `brython-cli --modules` where index.html is and it is generating the `brython_modules.js`, I also tried to run that command in brython folder.  after that, I am loading that file in index.html `<script src="./brython/brython_modules.js"></script>` and ran this `import brython_mesh`. This throws following errors:

`
brython_modules.js:1 Uncaught ReferenceError: __BRYTHON__ is not defined
    at brython_modules.js:1

Traceback (most recent call last):
  File file:///D:/Projects/IntellijIDEA/ib-masternode/scripts/static/index.html##brython_script line 3, in <module>
    import msg_to_mesh
ModuleNotFoundError: msg_to_mesh (warning: cannot import local files with protocol 'file')
`

Am I doing something wrong?

Thanks for helping

**Comment by demetere** [comment]
UPDATE
`from browser.local_storage import storage` error on this was because I have run `brython-cli --modules` in brython folder and not in index.html folder. I changed that and it works now, but I still have the problem of loading brython_mesh. I appreciate your help. Thanks

**Comment by demetere** [comment]
Thank you very much !!! it helped me to solve this issue. Thanks
