### ISSUE TITLE
html.BR() shows <HTMLBRElement>

### ISSUE THREAD

**Issue by UCYT5040** [brython-dev/brython#1833]
```py
from browser import document, html

console = document['console']
console <= f'{html.BR()}Webcon has loaded.'
```
output:
`stuffBeforeThat <HTMLBRElement>Webcon has loaded.`
Why is this?

**Comment by PierreQuentel** [comment]
This is just because `str(html.BR())` is `<HTMLBRElement>`. What would you expect instead ?

**Comment by UCYT5040** [comment]
> This is just because `str(html.BR())` is `<HTMLBRElement>`. What would you expect instead ?

@PierreQuentel 

I would expect '<br>'. How else should I use this element without a "ugly" `+`.

**Comment by PierreQuentel** [comment]
If I understand correctly you would like `f'{html.BR()}Webcon has loaded.'` to be the same as `html.BR() + 'Webcon has loaded'`. 

This is not how f-strings work: the evaluation of an f-string is a string. 

I'm afraid you have no other solution than what you call the "ugly" `+`...
