### ISSUE TITLE
markdown.mark(src) error with make_dist script

### ISSUE THREAD

**Issue by minghuadev** [brython-dev/brython#184]
Hi, Running "../scripts/make_dist.py" from "www" would always cause errors: 

    $ python ../scripts/make_dist.py 
    static doc fr
    Traceback (most recent call last):
      File "../scripts/make_dist.py", line 14, in <module>
        import make_doc  # lint:ok
      File "/home/.../brython-3.1.1/scripts/make_doc.py", line 42, in <module>
        html, scripts = markdown.mark(src)
    AttributeError: 'module' object has no attribute 'mark'

I have installed "Markdown-2.6.2". However the package does not contain a "mark" function that I can find. I looked for a "def mark(...)" in the source code. 
I noticed both "www/src/Lib/markdown2.py" and "www/src/Lib/browser/markdown.py" contain a "mark()" method. Where are those files derived from? How can you successfully run make_dist? 

Thanks.

**Comment by PierreQuentel** [comment]
HI,

Commit 75862ce653f3e8e68509c26b52f0ed6bc1dfd2aa should fix this issue (I saw it on stackoverflow). Can you confirm ?

**Comment by minghuadev** [comment]
Yes the problem is solved by this commit. 

Actually the problem started when I ran the script from the top directory above www/ and it complained no markdown package. I installed a local version of markdown 2.6.2, and eventually figured out to run it under www/.

**Comment by minghuadev** [comment]
Is it safe to ignore the error for no changelog file? 

    [Errno 2] No such file or directory: '/home/.../brython-3.1.1/dist/changelog.txt'
    Warning - no changelog file

**Comment by PierreQuentel** [comment]
Yes, it's just a reminder for me when I generate the files for Brython releases.

**Comment by minghuadev** [comment]
thanks!
