### ISSUE TITLE
How to use it with JavaScript MutationObserver

### ISSUE THREAD

**Issue by redstoneleo** [brython-dev/brython#1851]
Hello, I am new to this project , just wonder how to use it with JavaScript MutationObserver?

**Comment by PierreQuentel** [comment]
Here is an example: 
```python
from browser import document, window, html

def f(mutations, obserser):
    for mutation in mutations:
        for addedNode in mutation.addedNodes:
            checkNode(addedNode)

observer = window.MutationObserver.new(f)

def checkNode(addedNode):
    print('added node', addedNode)

observer.observe(document.documentElement, {
  'childList': True,
  'subtree': True
})

# Add an element
document <= html.H1("Hello world !")
```

Note the line `observer = window.MutationObserver.new(f)`: 
- the global DOM namespace is available as attributes of `browser.window`
- creating an object with a constructor (the equivalent of Javascript's `new Constr()`) is done in Brython with `window.Constr.new()`

Also note that Brython scripts are currently executed on page load (this might change in the future) : they can't observe mutations that happen before the page is completely loaded.
