### ISSUE TITLE
Variables are not correctly added to exec globals object when exec errors

### ISSUE THREAD

**Issue by austin-schick** [brython-dev/brython#1852]
When I run this block of code in Brython:

```python3
code = '''
a = 0
raise Exception()
'''

g = dict()
try:
    exec(code, g)
except:
    pass
print(g['a'])
```

I get `KeyError: a`. It seems that when an exception is raised in `exec(code, g)`, `a` is not added to `g`.

Thanks as always for taking a look @PierreQuentel

**Comment by PierreQuentel** [comment]
Good catch Austin, as usual :-)

**Comment by austin-schick** [comment]
Thanks! :)
