### ISSUE TITLE
Arithmetic expressions evaluating incorrectly in eval

### ISSUE THREAD

**Issue by austin-schick** [brython-dev/brython#1855]
Here's an odd one:

```
assert eval('-2 // 3') == -1
```
and
```
assert eval('-2 % 3') == 1
```

both raise `AssertionError`s on Brython.info. Maybe related to #1819?

Thanks for taking a look, and I hope you're enjoying the holidays!

**Comment by PierreQuentel** [comment]
This is true on brython.info, but the bug is fixed in the development version. It's time to publish a new release...

Happy holidays too ! (I am retired, so everyday is a holiday for me ;-)

**Comment by austin-schick** [comment]
Looks good in the development version!
