### ISSUE TITLE
Incorrect f-string parsing in console

### ISSUE THREAD

**Issue by ed2050** [brython-dev/brython#1863]
Bug is very simple to reproduce in [brython console](https://brython.info/tests/console.html?lang=en):

Brython 3.10.4 on Netscape 5.0 
>>> a = 2
>>> s = f'foo {a}'
>>> s = f'foo { a }'
... 
Traceback (most recent call last):
  File <string>, line 1, in <module>
IndentationError: unexpected indent

### Problem
Brython console parses f-strings incorrectly.  whitespace inside { } in f-strings shold be ignored, as in cpython.  Instead, the console interprets the space as starting a new indent and throws an error.

Brython handles f-strings correctly in scripts.  Bug only appears in console.

**Comment by PierreQuentel** [comment]
Thanks for the report !
