### ISSUE TITLE
commit db2f2a5 makes it impossible to include Brython modules implemented in JavaScript into a package

### ISSUE THREAD

**Issue by moepnse** [brython-dev/brython#1865]
This change makes it impossible to include Brython modules implemented in JavaScript into a package:
https://github.com/brython-dev/brython/blob/7be01d777fa156f8e78577a2216ad91747953b3f/setup/brython/make_package.py#L73

And there is also an indentation error (one space is missing):
https://github.com/brython-dev/brython/blob/7be01d777fa156f8e78577a2216ad91747953b3f/setup/brython/make_package.py#L101

**Comment by moepnse** [comment]
[patches.zip](https://github.com/brython-dev/brython/files/7829656/patches.zip)

**Comment by PierreQuentel** [comment]
Interesting ! In standard Brython, importing a JS module is only possible for those in directory **`/libs`**. How do you import JS modules inside a user-defined package ?

**Comment by moepnse** [comment]
If it is in the VFS, then I can import it as usual with the import statement - without changing the import mechanism.

Please don't change that behavior in the future. 😃
