### ISSUE TITLE
select.py trys to call java.nio

### ISSUE THREAD

**Issue by stuaxo** [brython-dev/brython#1867]
select.py was ported from jython, but still references java.nio

https://github.com/brython-dev/brython/blob/master/www/src/Lib/select.py

**Comment by PierreQuentel** [comment]
You are right, I have removed the code that references this module.

Anyway, like a few other modules, __`select`__ is only included to avoid import errors in modules that import it, it is not meant to do anything useful apart from that (accessing the computer network stack is not possible from the browser).

**Comment by stuaxo** [comment]
Thanks, I wish I could find the page I saw it on to give proper credit, I was browsing and saw someones post on brython + looked like it should be here.
