### ISSUE TITLE
`.sort()` on sliced lists doesn't return `None`

### ISSUE THREAD

**Issue by austin-schick** [brython-dev/brython#1868]
On Brython master, this snippet

```python3
L = [1][::]
assert L.sort() is None
```

raises an assertion error. Instead of returning `None`, the sort method returns the list itself. Interestingly, 

```python3
L = [1]
assert L.sort() is None
```

runs without error. Thanks for taking a look :)

**Comment by austin-schick** [comment]
The same error also occurs for copied lists:

```python3
import copy
L = copy.copy([1])
assert L.sort() is None
```

**Comment by PierreQuentel** [comment]
Thanks once again for the report Austin !
