### ISSUE TITLE
NameError in 'while' loop

### ISSUE THREAD

**Issue by ElonN** [brython-dev/brython#187]
Hi,

I have encountered a wierd error during execution of a while loop:

![python](https://cloud.githubusercontent.com/assets/8389092/7597278/12737b56-f8fb-11e4-82ac-d0719cb8f072.png)

Did I miss something?

**Comment by PierreQuentel** [comment]
Hi,

Thanks for the report, this is the most embarrassing bug in ages... It should be fixed now, I will publish a new version very soon.

**Comment by pdorlov** [comment]
.
