### ISSUE TITLE
How to insert a raw html string?

### ISSUE THREAD

**Issue by fetsorn** [brython-dev/brython#1870]
I've generated a raw SVG string in brython and wanted to insert it in the HTML page with
`document <= svg`
This resulted in a screenful of text, tags were not interpreted and instead were written as text symbols.
Is it possible to insert a raw HTML string in the DOM without using browser.html or browser.svg?
Couldn't find the answer in the docs.

**Comment by fetsorn** [comment]
Ended up rendering the raw svg string in an iframe with
`document <= html.IFRAME(srcdoc=svg)`
Still curious if there are better ways, but closing since the issue is resolved.

**Comment by PierreQuentel** [comment]
You can use `document.write(svg)` or `document.html += svg`, for instance:

```python
from browser import document

svg = """<svg width="400" height="110">
  <rect width="300" height="100" style="fill:rgb(0,0,255);stroke-width:3;stroke:rgb(0,0,0)" />
</svg>"""

document.html += svg
```

**Comment by fetsorn** [comment]
> You can use `document.write(svg)` or `document.html += svg`

Got it, thanks for answering!
