### ISSUE TITLE
How to run interactive console in Android 4.2?

### ISSUE THREAD

**Issue by tellts** [brython-dev/brython#1872]
Hello. I saved the web page to my computer. In Windows 10 in the browser, it starts and works, and on a tablet with a diagonal of 10.1 in the Chrome browser, no text about the development environment is displayed. I tried different versions of other programs and they don't work on the old operating system. Please help all people with such problems. Add support for Android.

**Comment by PierreQuentel** [comment]
Hello,

If I understand correctly, you would like to save a web page with Brython code in it to the tablet, then open the file in the tablet's Chrome browser. Is this correct ?

If so, the web page has to load the Brython core scripts (__`brython.js`__ and __`brython_stdlib.js`__), so these scripts _must also be saved in the tablet_. If you save them in the same directory as the web page, the code to load them should be

```xml
<script src="brython.js"></script>
<script src="brython_stdib.js"></script>
```

Note that there are [limitations](https://www.brython.info/static_doc/en/file_or_http.html), mostly related to importing modules and reading local files, when pages are opened as files, not served from a web server.

**Comment by tellts** [comment]
Hello. I haven't understood your proposed solution yet. I'm learning Python and want to be able to run sample code on a tablet copied from articles saved to my hard drive. I want to use your solution to have a Python that can download and execute code files or, failing that, at least have an interactive Python console on a tablet.
