### ISSUE TITLE
Installing a CPython Package

### ISSUE THREAD

**Issue by jabezborja** [brython-dev/brython#1880]
Hi, Pierre. I want to install a CPython Package. According to the documentation, it is done with this:
```
pip install attrs
brython-cli --add_package attrs
```
However, when I do that, it's creating a Brython package with a name of `attrs.brython.js` on the current directory, not on the CPython Package itself. Thanks in advance!

**Comment by PierreQuentel** [comment]
Hello Jabez,

Sorry to ask, but are you sure you ran `--add_package` and not `--make_package` ? I ask this because `--make_package` creates JS files with the extension __`.brython.js`__.

**Comment by jabezborja** [comment]
Oh sorry, thanks for clarifying!

**Comment by PierreQuentel** [comment]
No worries !
