### ISSUE TITLE
Is it possible to execute interpreter twice ?

### ISSUE THREAD

**Issue by declercq-c** [brython-dev/brython#1881]
Hello,
I opened a first Brython interpreter in a popup window : OK
As I opened a second one, the first one doesn't work anymore. The second is waiting...
Is there a way to close properly an interpreter, before opening a second one ? without refreshing entire page ?
It would be very useful in my project building an IDE over Brython.
Thanks in advance,
Christophe
![InterpreteBrython](https://user-images.githubusercontent.com/28707821/152641901-38156d0a-0c5a-469d-9e09-bba40bcf8b5c.png)

**Comment by PierreQuentel** [comment]
Bien vu, je n'y avais pas pensé ! Ca devrait mieux marcher avec ces commits, il peut y avoir plusieurs interpréteurs ouverts en même temps.
Si ton projet d'IDE est sur Github ça m'intéresse de le suivre.

**Comment by declercq-c** [comment]
Bonsoir,
Merci beaucoup pour la correction. Il reste juste un souci quand l'interprète n'est pas dans une boite de dialogue mais dans un textarea nommé. En fait je souhaiterais remplacer un interprète par un nouveau mais n'arrive pas à fermer le premier. J'obtiens le message suivant à l'ouverture du second :
File VFS.interpreter.py line 198, in blur
    self.dialog.style.zIndex=0
AttributeError: 'Interpreter' object has no attribute 'dialog'
Merci d'avance,
Christophe

**Comment by PierreQuentel** [comment]
Eh oui bien sûr... ça devrait être bon avec ce commit.

**Comment by declercq-c** [comment]
Merci,
Oui c'est parfait. Il ne me reste plus qu'à corriger mon code...
Mon projet n'est pas vraiment un IDE mais plutôt un environnement pédagogique pour découvrir la programmation fonctionnelle en python.
https://iremi974.gitlab.io/block2pyf/
L'exécution de plusieurs interprètes fonctionne bien, il faut juste que je corrige pour que ce soit le dernier lancé qui ait la main. A chaque execution je relance un interprète. Actuellement quand on exécute une deuxième fois après avoir modifié le code, c'est toujours le premier interprète qui répond. Si on exécute plusieurs fois tous les interprètes restent actifs car ils envoient chacun une invite >>>. Je vais essayer de corriger celà.
Encore merci pour votre aide
Bien cordialement,
Christophe
