### ISSUE TITLE
Missing SyntaxError for invalid use of := operator

### ISSUE THREAD

**Issue by schmave** [brython-dev/brython#1886]
In CPython, the following code raises a SyntaxError ("assignment expression cannot rebind comprehension iteration variable 'i'"), but in Brython it runs without error. 

```python
print(i:=i for i in [])
print(i)
```

Brython output:

```
<undefined object>
<Javascript undefined>
```

**Comment by PierreQuentel** [comment]
Thanks for the reports Evan. I confess I'm not sure why this one raises a `SyntaxError` instead of a `NameError` at runtime, but it's a corner case anyway.

**Comment by schmave** [comment]
Thanks for the fixes!
