### ISSUE TITLE
Tell Brython to look at Lib/site-packages directly

### ISSUE THREAD

**Issue by jabezborja** [brython-dev/brython#1887]
Hello, Pierre! Is there a way to tell Brython to look packages on `Lib/site-packages` directly and not to manually look it with himself? Maybe to improve speed more and it's kinda annoying to see a lot of errors on the console when adding a CPython package. Thanks in advance!

**Comment by Froggo8311** [comment]
Have you tried changing your `brython();` to `brython({pythonpath: ["/Lib/site-packages"]});`? Hope this helps.
