### ISSUE TITLE
Javascript Error Thrown Instead of Python Error In Incorrect List Comprehensions

### ISSUE THREAD

**Issue by joshua-baum** [brython-dev/brython#1895]
Small issue I ran into with poorly formatted list comprehensions. If the item name in the list comprehension is invalid, a javascript exception is seen instead of a python error. The following screenshots demonstrate Brython behavior vs Python 3.7.4 running locally:

![Capture](https://user-images.githubusercontent.com/46763926/154411581-5821a5ff-d232-41de-bd4d-8295603da773.PNG)
 
![Capture1](https://user-images.githubusercontent.com/46763926/154411748-a21aad75-de67-40a4-9495-901d23677615.PNG)

**Comment by PierreQuentel** [comment]
Thanks for the report @joshua-baum !
