### ISSUE TITLE
I want try use editor and console,but it's not work

### ISSUE THREAD

**Issue by WadeStack** [brython-dev/brython#1896]
env:
- Windows10
- Python version 3.9.6
- Brython version 3.10.4
- Chrome version 98.0.4758.82

step:
```shell
git clone https://github.com/brython-dev/brython.git
cd brython/www
python -m http.server
```
then,I open chrome visit `http://localhost:8000/`

click `Editor`,the left of page isn't show,I can't input code
![image](https://user-images.githubusercontent.com/40057831/154443887-fd7c9aa1-1602-4147-836b-9e54c7efed6f.png)

and `Console` isn't work,turn on the developer mode, and no error is found
![image](https://user-images.githubusercontent.com/40057831/154444232-a5334101-7743-42a3-8df0-8f2a41a52bc7.png)

What should I do?
Look forward to your reply😃

**Comment by PierreQuentel** [comment]
Thanks for reporting this issue. It was present in a previous commit but should be fixed now. Can you check ?

**Comment by WadeStack** [comment]
> Thanks for reporting this issue. It was present in a previous commit but should be fixed now. Can you check ?
OK，The latest code works fine.Thx
