### ISSUE TITLE
Missing asyncio.queues.Queue

### ISSUE THREAD

**Issue by fpom** [brython-dev/brython#1898]
This class does not appear to be available. I've developed something that seems to work (but I didn't test it thoroughly). Perhaps you'll find it useful: https://gist.github.com/fpom/e74e4c896de4b4ad429ab42cbf631bc4

**Comment by PierreQuentel** [comment]
Merci Franck !

Je ne suis pas très au point sur asyncio, j'ai juste repris ton implémentation (en enlevant la partie liée à #1897). Le test a l'air de passer correctement. Si ça te convient on pourra fermer cette signalisation.

**Comment by fpom** [comment]
Ça marche, merci ! Si j'ai l'occasion de refaire d'autres trucs je les enverrai. Je ne suis pas très au point sur la structure du code Brython alors pas sûr de pouvoir faire un PR propre.
