### ISSUE TITLE
The dictionary implementation is painfully slow

### ISSUE THREAD

**Issue by P2000** [brython-dev/brython#19]
The performance is really suboptimal. Looking at the code, it quickly becomes clear why: To find an object, the whole dictionary is searched in a loop (i.e. https://github.com/brython-dev/brython/blob/e1dc7b4575280dd7a00e3012890c7c2533d48e32/src/py_dict.js#L68). I expected to find some sort of hash map. Don't python objects have __hash__ functions or the like? I don't know, but I guess it would be possible to find something. :-) Anyhow - I converted the hash maps into arrays to solve the performance issues and am very happy with Brython, it is a great project. To who it may concern: Thank you for all the hard work and making it available open source!

**Comment by earney** [comment]
I'm going to close this issue since the new implementation has been put into place.  Feel free to reopen this issue (or create a new one), if a related issue arises.
