### ISSUE TITLE
Brython flusters when asked to write emoji to json.

### ISSUE THREAD

**Issue by ennec-e** [brython-dev/brython#1903]
**Steps to reproduce**

import json
json.dumps('g') # -> '"g"'
json.dumps('🤭') # -> TypeError: Object of type str is not JSON serializable

**Expected Behaviour**

Brython should process emoji to json just like other text without discrimination.

**Comment by PierreQuentel** [comment]
Thanks for the bug report @ennec-e. It is fixed by commit 935ad86.

**Comment by ennec-e** [comment]
thank you : )
