### ISSUE TITLE
Is the support of python relative imports complete?

### ISSUE THREAD

**Issue by wkta** [brython-dev/brython#1907]
(french version for convenience:)
Je construis un projet fondé sur Brython qui contient plus d'une dizaine de petits composants et une structure élaborée… Faire évoluer ce projet est fastidieux (à ma connaissance) si l'on s'abstient d'utiliser les import relatifs!
L'instruction suivante passe sans problème en local, mais ça provoque une erreur via Brython
`from ... import _hub as injec`
Le mécanisme dit de "import relatif" est-il pleinement supporté dans Brython? Merci

_(english:)
I am building a project upon Brython which contains a dozen of small components and an elaborate structure… Evolving this project is tedious (A.f.a.i.k) if restraining oneself from using relative imports!
The following instruction works fine locally, but it raises an error via Brython
`from ... import _hub as injec`
Is the "relative import" mechanism fully supported in Brython? Thank you_

**Error Log**
```
line info undefined
line info undefined
brython.js:7624 Traceback (most recent call last):
  File VFS.importlib/_bootstrap.py line 682, in _load_unlocked
    spec.loader.exec_module(module)
  File katagames_sdk.katagames_engine._sm_shelf.event, line 5
    from ... import _hub as injec
          ^
SyntaxError: invalid syntax
$io.flush @ brython.js:7624
```

***Nota Bene:***
Using:
```
// brython.js brython.info
// version [3, 10, 0, 'final', 0]
// implementation [3, 10, 4, 'final', 0]
```
Also, my `event.py` file is loaded via a call: `importlib.import_module(arg1, arg2)` and not a regular import. Maybe it matters for this problem, or maybe not… I can provide more info if needed.

**Comment by PierreQuentel** [comment]
Merci pour le signalement - ça fait tellement de bien de répondre en français pour une fois !

Il y avait effectivement un problème avec les 3 points, que l'interpréteur confondait avec Ellipsis... Ca devrait fonctionner maintenant.
