### ISSUE TITLE
A function defined in `eval` can't see globals defined later

### ISSUE THREAD

**Issue by Kodiologist** [brython-dev/brython#1909]
Given this (tested on Brython 63bd5dd9f15d6e111eac20d3818b494d96a3503e):

```python
f = eval('lambda: x')
x = 1
print(f())
```

CPython prints `1`, but Brython raises `NameError` for `x`. It works in Brython if you don't use `eval`, or if `globals()` is provided explicitly as the second argument to `eval` (although this should be the default value), or if `x` is defined before `f`.

**Comment by PierreQuentel** [comment]
This bug is fixed with the latest commits (cf. my post [Major rewriting](https://groups.google.com/g/brython/c/ya-hrMCdNUA))
