### ISSUE TITLE
"Structural Pattern Matching" not working for lists

### ISSUE THREAD

**Issue by LEDThereBeLight** [brython-dev/brython#1927]
I believe structural pattern matching is broken (at least for lists -- I haven't tried other data types).

Try this code in either the online editor in the documentation, or in a local installation of Brython 3.10.5:
```
alist = [1,2,3,4]

def length(alist):
    match alist:
        case []: return 0
        case [x, *xs]: return 1 + length(xs)

length(alist)
```

This produces the error:
```
File <Javascript undefined>, line 5
    case []: return 0
           ^
SyntaxError: invalid syntax 
<completed in   2.00 ms>
```

Underscore matches (`case _:`) also do not work.

**Comment by PierreQuentel** [comment]
Thanks for the report @LEDThereBeLight !
