### ISSUE TITLE
How can I pass additionnal argument to a function

### ISSUE THREAD

**Issue by Jocelyn-AGORO** [brython-dev/brython#1928]
I want to pass an argument to my function.
Example:
```python
def do_something(event, id):
    console.log(id)

document['element_id'].bind('click', do_something(...))
```
I want to pass argument when binding

**Comment by jsbueno** [comment]
On Mon, Mar 21, 2022 at 8:00 AM Jocelyn AGORO ***@***.***>
wrote:

> I want to pass an argument to my function.
> Example:
>
> def do_something(event, id):
>     console.log(id)
> document['element_id'].bind('click', do_something(...))
>
> I want to pass argument when binding
>

Python's `functools.partial` should work fine in Brython (and if not it is
a bug that should be reported)


from functools import partial

def do_something(event, id, extra):
    console.log(id)

document['element_id'].bind('click', partial(do_something,
extra="extra argument"))

**Comment by PierreQuentel** [comment]
Other options can be:
- pass a lambda that takes the event object as argument and call a function with other arguments

```python
def f(ev, x):
    print(x)

element.bind('click', lambda ev: f(ev, 'bar'))
```
- set a property of the DOM element and use `event.target` in the callback function to reference the element

```python
def callback(ev):
    print(ev.target.foo)

element.foo = 'bar'
element.bind('click', callback)
```

**Comment by Jocelyn-AGORO** [comment]
Cool Thank you very much.
