### ISSUE TITLE
Problem with exec defining functions

### ISSUE THREAD

**Issue by benjie-git** [brython-dev/brython#1929]
When I define a function inside an exec call, and then later call that function from another exec call, the __globals variable fails to update once the 2nd exec returns.  For example, in the following code:

    vars = {}
    exec("a=1\ndef f(): print(a)", vars)
    print(vars)
    exec("b=2; a=2; f()", vars)
    print(vars)

I expect the 2nd exec() line to print out 2, but instead it prints 1.  Additionally, I expect the final print() line to include a=2, b=2, but instead it includes a=1, and b is missing.

**Comment by PierreQuentel** [comment]
Thanks for reporting this @benjie-git. I can reproduce the bug on brython.info (3.10.5) but it is fixed in the current development version. Can you check ?

**Comment by benjie-git** [comment]
Thanks for the testing help!  With the latest dev versions from https://raw.githack.com/brython-dev/brython/master/www/src/ I get errors about modules not found for _abc, _stat, and _heapq.  But my code runs and works correctly!  Thank you!

**Comment by PierreQuentel** [comment]
About the missing modules : in CPython they are written in C, thus not present in Brython standard distribution, but the modules that use them can handle the case when they are missing: 
- in **`abc.py`**, if **`_abc`** cannot be imported, **`_py_abc`** is imported instead (it is a pure-Python module)
- in **`heapq.py`**, if **`_heapq`** cannot be imported, the Python functions in **`heapq`** are used
- same for **`_stat`** in module **`stat.py`**

**Comment by benjie-git** [comment]
Is there a way to get brython to avoid requesting these c libraries, to speed up loading times, and silence the warnings?

**Comment by PierreQuentel** [comment]
Yes,if you load **`brython_stdlib.js`** in the page, failing to import a module in the standard library takes a microsecond.

**Comment by benjie-git** [comment]
I actually am loading my local copies of both lib/brython.js and lib/brython_stdlib.js in my own lib dir. (Pulled from the latest github revisions.)  Everything works, but I get 24 errors about failing to find _abc, _stat, and _heapq every time I load my page.  I can open a new bug for that.

**Comment by TheLastGimbus** [comment]
Hi there!

@PierreQuentel i have interesting discovery! `exec` works properly (i can use functions defined inside it) on version 3.10.6, but not on 3.10.5 nor 3.10.7 :laughing:

**Comment by PierreQuentel** [comment]
@TheLastGimbus 
Do you have an example where `exec` doesn't work as you expect ?

**Comment by TheLastGimbus** [comment]
Yeah

https://the.lastgimbus.com/shar-zagadka/

Here, i take code from textinput, `exec()` it to get function from it, and execute this function

https://github.com/TheLastGimbus/the.lastgimbus.com/blob/master/static/shar-zagadka/index.html#L60-L64

You can see i have brython 3.10.6

https://github.com/TheLastGimbus/the.lastgimbus.com/blob/master/static/shar-zagadka/index.html#L11

It doesn't work on .5 nor .7, only .6

(This site is a literally single html file, you can download and experiment with it 👍)

**Comment by PierreQuentel** [comment]
Thanks for the example.

If it worked in version 3.10.6, it was a bug, as you can test with this code with CPython:

```python
src = """def shar_funkcja():
  milosc = 6
  return milosc"""

def f():
  # default globals and locals : fails
  exec(src)
  try:
    shar_funkcja
    raise Exception('should have raised NameError')
  except NameError:
    pass

  # pass globals() and locals() : fails  
  exec(src, globals(), locals())
  try:
    shar_funkcja
    raise Exception('should have raised NameError')
  except NameError:
    pass

  # explicit locals : ok
  locs = {}
  exec(src, globals(), locs)
  print(locs['shar_funkcja'])

f()
```

As explained in the [Python documentation](https://docs.python.org/3/library/functions.html#exec), inside a function, you have to pass an explicit `locals` argument to `exec()`. It took me some time to get it right in Brython (and I'm not 100% sure it is...)
