### ISSUE TITLE
site-packages directory should be empty in Brython's distribution

### ISSUE THREAD

**Issue by aroberge** [brython-dev/brython#193]
Other than perhaps a test file (as in test_sp.py), the site-packages directory in Brython's distribution should not include any files, and be left to the end-user to fill with whatever they need.   I found a file in the recent distribution that had the same name as one of my file located in site-packages when I attempted to upgrade Brython from 3.0.0 to 3.1.3.

**Comment by earney** [comment]
I have created a separate repo for brython's pygame.  It is located at:
https://github.com/brython-dev/brython-pygame
