### ISSUE TITLE
json.loads() doesn't unescape newlines properly

### ISSUE THREAD

**Issue by benjie-git** [brython-dev/brython#1930]
For example:

    print(json.loads('["one\\ntwo"]')[0][3])

should output '\n' but instead I get '\' and the next character is 'n'.

**Comment by PierreQuentel** [comment]
Thanks for the report Ben :-)

**Comment by benjie-git** [comment]
Thanks for the speedy fix!  But I notice a few remaining problems:
  - This seems to only fix the first '\\n', etc. of each string.
     json.loads('"one\\ntwo\\nthree\\nfour"') results in "one\ntwo\\nthree\\nfour"
  - This also misses \\' and \\"
     json.loads('"one \\'two\\' three"') results in "one \\'two\\' three"

**Comment by PierreQuentel** [comment]
The latest commit fixes the reported bugs, but I leave the issue open in case you find other bugs.

**Comment by benjie-git** [comment]
It's working great for me now, loading large, fairly complex json docs.  Thank you!!
