### ISSUE TITLE
object.__annotations__ values are string not type objects

### ISSUE THREAD

**Issue by stefanhoelzl** [brython-dev/brython#1932]
In cpython the values of object annotations are type objects
```python
class A:
    value: str

assert A.__annotations__ == {"value": str}, A.__annotations__
```

but in brython this fails, because the annotation value is a string `str` (`A.__annotations__ == {"value": "str"}`)

**Comment by PierreQuentel** [comment]
Thanks for the report Stefan.

If I understand correctly, annotation values will be strings by default in Python 3.11 (in Python 3.10 it is already the case with `from __future__ import annotations`). I don't put this issue on top of the list, unless it's blocking for your project.

**Comment by PierreQuentel** [comment]
With recent commits, Brython now behaves the same as CPython:
- `from __future__ import annotations` is missing, the value is class `str`
- if it is present, it is the string `"str"`
