### ISSUE TITLE
Brython isn't loading modules from brython_stdlib.js

### ISSUE THREAD

**Issue by benjie-git** [brython-dev/brython#1933]
I'm loading my local copies of both lib/brython.js and lib/brython_stdlib.js in my own lib dir. (Pulled from the latest github revisions.)  Everything works, but I get 24 errors about failing to find _abc, _stat, and _heapq every time I load my page.

My directory structure looks like:

index.html
<my_python_files>.py
lib/brython.js
lib/brython_stdlib.js
lib/unicode.txt
lib/<other_js_libraries>.js

**Comment by benjie-git** [comment]
Also to be clear, I'm not building any brython files, just grabbing brython.js and brython_stdlib.js from:
https://github.com/brython-dev/brython/tree/master/www/src

**Comment by PierreQuentel** [comment]
You were right, there was a regression here. With the commit referenced above, the import engine should not try to import modules that are not in the standard library, either with or without **`brython_stdlib.js`**.
