### ISSUE TITLE
Brython error message in French

### ISSUE THREAD

**Issue by ed2050** [brython-dev/brython#1934]
I got a strange error message in the console.  The first line is in French:

```
brython.min.js:1     pas de __file__ ou de file_cache[__file]
brython.min.js:1     Traceback (most recent call last):
  File undefined line 2, in <module>
     ^
IndentationError: expected an indented block after function definition on line 1
```

The cause was two function definitions back to back with a missing body.  You can reproduce the error with this snippet:
```
<script type="text/python">
def foo () :
def bar () :
    pass
</script>
```

So I know the cause and how to fix it.  Was just surprised to see an error message in French.  Is that supposed to be there?

**Comment by PierreQuentel** [comment]
I sometimes write debug messages in my language, sorry about that ;-)

This one is removed in the current development version.

**Comment by ed2050** [comment]
Of course, completely natural.  I only mentioned it for consistency.  The codebase is remarkably mature and consistent thanks to your efforts.
