### ISSUE TITLE
struct.pack/unpack broken(?)

### ISSUE THREAD

**Issue by rocket-pig** [brython-dev/brython#1935]
```
d =struct.pack('8B', 137, 80, 78, 71, 13, 10, 26, 10)
print(d)
```

gets you `b'\x89\x00P\x00N\x00G\x00\r\x00\n\x00\x1a\x00\n'`, which looks curiously like, but not an exact match for, the result of struct.pack with '8H' as format string in 'normal' python.  'Normal' python returns `b'\x89PNG\r\n\x1a\n'` for the same command. Trying to unpack with same format string:
`e = struct.unpack('8B',d)`
results in `StructError: unpack str size does not match format`

...suffice to say, same code that uses struct.pack works fine in 'normal' python, breaks in all sorts of mysterious ways in brython.

What can I do? Anything?

Edit, I just noticed that if I copy/paste the correct result, struct.unpack will correctly unpack it, FWIW its just the .pack that's broken

**Comment by PierreQuentel** [comment]
Thanks for the bug report @rocket-pig !

**Comment by rocket-pig** [comment]
FWIW its not struct, but something deeper. I imported rawutil has all the functionality of struct pack/unpack and still had similar issues.  Im not smart enough to suss out why.  Thanks for your amazing tool.
