### ISSUE TITLE
`json.JSONEncoder` is missing

### ISSUE THREAD

**Issue by vlanore** [brython-dev/brython#1936]
Hello!

I just noticed that `JSONEncoder` is missing from the `json` lib in brython.

For example, if I type the following in the online brython console (https://brython.info/tests/console.html) :
```
Brython 3.10.5 on Netscape 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.82 Safari/537.36
>>> from json import JSONEncoder
Traceback (most recent call last):
  File <string>, line 1, in <module>
ModuleNotFoundError: No module named 'json.JSONEncoder'; 'json' is not a package
```
the class is missing, although the same command works in a non-brython console.

Is this intended ? I was trying to write a custom encoder to handle dataclasses in order to put them in brython object storage.

Thank you for your time and for the great work on brython!

**Comment by PierreQuentel** [comment]
Merci pour le signalement Vincent :-)

J'ai repris la version pur-Python du module **`json.decoder`**, ça risque d'être un peu lent s'il y a de gros fichiers JSON à traiter. Si nécessaire je pourrai faire une version en Javascript un de ces jours.

**Comment by vlanore** [comment]
Merci pour la réaction rapide encore une fois, et pour la correction !

Je confirme que ça fonctionne avec la dernière version. Je ne remarque pas de problème de performance pour le moment (mais c'est sur des petites données) 👍
