### ISSUE TITLE
Bug with type()

### ISSUE THREAD

**Issue by ChameleonRed** [brython-dev/brython#1937]
Try this code:

```
from browser import document,
body = document.select('body')[0]
body <= html.PRE(str(type(str)))
```

Should be:
<class 'type'>

Returns:
None

**Comment by ChameleonRed** [comment]
Recent Firefox + Brython 3.10.5. I see that it works here ->https://brython.info/tests/editor.html?lang=en strange.

**Comment by ChameleonRed** [comment]
It is not problem with type but with str()?

This not works:
```
from browser import document, html

body = document.select('body')[0]

def main():
    body <= html.PRE(str(type(str)))
    
main()
```
Try this here: https://brython.info/tests/editor.html?lang=en

**Comment by PierreQuentel** [comment]
This is because the PRE tag receives the string `<class 'type'>` and the browser interprets this as the tag 
```xml
<class type=''></class>
```

You can see that in the browser inspector.

You get the expected result if you use a TEXTAREA instead of PRE.

**Comment by PierreQuentel** [comment]
With `html.PRE(s)`, `s` is the inner HTML of the element, not the inner text.

You can set the inner text by

```python
from browser import document, html

pre = html.PRE()
pre.text = "<class 'type'>"
document <= pre
```

**Comment by ChameleonRed** [comment]
I was used 'html.escape' and it works now - this is not a bug but HTML.

**Comment by PierreQuentel** [comment]
Ok, I close the issue then. Thanks for the feedback !
