### ISSUE TITLE
interactive console inappropriately adds quotes to objects whose repr doesn't have quotes

### ISSUE THREAD

**Issue by glyph** [brython-dev/brython#194]
brython:

```
>>> 3
'3'
```

CPython:

```
>>> 3
3
```

**Comment by PierreQuentel** [comment]
Glyph,

Thanks for the report. I recently fixed a few bugs in `__repr__` of a few built-in types, and tried to understand what the console does when you just enter a name or a literal. I haven't found the answer in the documentation, do you know if it is described somewhere ?

After fixing this bug the console assumes that 

```
>>> value
``` 

gives the same result as 

```
>>> print(str(repr(value)))
```

but I'm not sure if it's correct.

**Comment by glyph** [comment]
It's equivalent to `print(repr(value))`.  It's documented here: https://docs.python.org/3/library/sys.html#sys.displayhook
