### ISSUE TITLE
json loading of an empty list as a dict value is broken

### ISSUE THREAD

**Issue by benjie-git** [brython-dev/brython#1944]
>>> import json
    >>> json.loads('{"a":[1]}')
    {'a': [1]}

works as expected, but:

    >>> import json
    >>> json.loads('{"a":[]}')
    Traceback (most recent call last):
      File <string>, line 1, in <module>
    Exception: <Javascript TypeError>: Cannot read properties of undefined (reading 'type')

**Comment by PierreQuentel** [comment]
Thanks for the bug report Ben :-)

**Comment by benjie-git** [comment]
Thank you again for another very fast fix!
