### ISSUE TITLE
Packing with with *args, **kwargs for JS function invocation throws `js_attr is not defined`

### ISSUE THREAD

**Issue by anderoonies** [brython-dev/brython#1945]
```py
def f(*args, **kwargs):
  print(*args, **kwargs)
```

behaves like:

```py
f(1, 2, 3)
>> 1 2 3
```

in Python.

In Brython, 
```py
from browser import window

def f(*args, **kwargs):
  window.console.log(*args, **kwargs)
```
is throwing `js_attr is not defined`, originating from here:
https://github.com/brython-dev/brython/blob/c917a5458dba9d01f63f87479ff651966805768e/www/src/js_objects.js#L301-L303

**Comment by chenzhekl** [comment]
I have given your code a try. It seems to work fine at least in the online editor.

https://brython.info/tests/editor.html?code=def%20foo%28*args%2C%20**kwargs%29%3A%0A%20%20%20%20print%28*args%2C%20**kwargs%29%0A%20%20%20%20%0Afoo%281%2C%202%2C%203%2C%204%29

**Comment by anderoonies** [comment]
Ah, sorry—I'm working in an online repl where `print` ends up invoking JavaScript.
It looks like the issue is just with JS interop:
https://brython.info/tests/editor.html?code=def%20foo%28*args%2C%20**kwargs%29%3A%0A%20%20%20%20print%28*args%2C%20**kwargs%29%0A%20%20%20%20%0Afoo%281%2C%202%2C%203%2C%204%29

**Comment by PierreQuentel** [comment]
Calling Javascript functions with keyword arguments is invalid, for reasons explained in the [documentation](https://www.brython.info/static_doc/en/jsobjects.html).

The commit referenced above produces a more explicit error message.
