### ISSUE TITLE
Python code execution with multiple inputs and outputs 

### ISSUE THREAD

**Issue by wfmonster** [brython-dev/brython#1948]
I am working on a project that uses the ace editor in the browser and uses brython to execute the python code. 
I have a console area that outputs the results of the code execution using an exec function. 

I have discovered that when executing code that requires multiple interactions such as multiple `input()` functions and`print()` statements that none of the output is printed to the console area (not an interactive console) until after the full execution of the code. I have discovered this is also true for the web application that you have have at https://brython.info/tests/editor.html?lang=en. 

This behavior makes it difficult to have any complex interaction with the python code as you cannot see the output of any intermediate steps. Is there a way to pipe the output of stdout to the console area during the exec execution?

A simple example is this:

```python
for i in range(0, 3):
    name = input("name: ")
    print(name)
```

This should output intermediate results to the console area as it would when executing python on the commandline. 
> Ask for input
 output : name
> Ask for input
output: name
> Ask for input
output: name

Instead the behavior is as such:
>Ask for input
> Ask for input
> Ask for input
output: name
output: name
output: name

I am also open to an alternative approach all together. Is there a way to pipe a string of python code to the brython console 
and execute it there with user interaction?

I have been attempting to use a Context Manager to pipe the intermediate results of the exec function to the console area with little to no luck.  This is my current python code runner.  Using `python=3.10.0` 

```python 
from browser import document, console, window
from javascript import JSON
import traceback
import sys
from io import StringIO
import contextlib

@contextlib.contextmanager
def stdoutIO(stdout=None):
    old = sys.stdout
    if stdout is None:
        stdout = StringIO()
    sys.stdout = stdout
    yield stdout
    sys.stdout = old


class cOutput:
    encoding = 'utf-8'

    def __init__(self):
        self.cons = document["console"]
        self.buf = ''

    def write(self, data):
        self.buf += str(data)

    def flush(self):
        self.cons.value += self.buf
        self.buf = ''

    def __len__(self):
        return len(self.buf)


if "console" in document:
    cOut = cOutput()
    sys.stdout = cOut
    sys.stderr = cOut


def to_str(xx):
    return str(xx)

def format_error(error):
    split_output = error.split("\n")
    return split_output[0] + "\n" + "\n".join(split_output[3:])


def runcode(*args):
    # global output
    console_output = ""

    editor_value = window.editor.getValue()
    events = window.events

    if not editor_value: return

    document["console"].value=''
    
    with stdoutIO() as s:
        
        try:
            ns = {'__name__':'__main__'}
            exec(editor_value, ns)
            state = 1

        except Exception as exc:
            traceback.print_exc(file=sys.stderr)
            state = 0

        console_output = s.getvalue()
    
    sys.stdout.flush()

    # console_output = document["console"].value

    if(eventtype == RUN_FAIL):
        console_output = format_error(console_output)
    document['output'].innerHTML = "<p> >> " + console_output + "</p>"

    return state


window.runCodeListener = runcode
document['editor_run'].bind('click', runcode)
```

The element that uses this editor 
```html

<!-- ...snip -->
<div class="editor_wrapper">
        <div class="editor_body">
             <div id="ace_editor" class="editor_code"></div>

             <div class="editor_status"> 
                 <div id="messages"></div> 
             </div>
        </div>

        <div id="console" class="editor_console">
            <pre id="output" ></pre>
        </div>
         
        </div>
</div> 

```

**Comment by PierreQuentel** [comment]
This has been asked a number of times, and the answer is unfortunately always the same : because of the browser execution model, a loop with an `input()` cannot change anything in the page (in the DOM tree) until the loop is exited. This is true for equivalent Javascript code.

To achieve this, you have to replace the blocking `input()` function by an asynchronous input box such as those in the gallery: [1](https://www.brython.info/gallery/simulate_input.html) [2](https://www.brython.info/gallery/simulate_input_dialog.html)
