### ISSUE TITLE
Help to undestand code. editor.py and editor.html

### ISSUE THREAD

**Issue by wviana** [brython-dev/brython#1949]
Hello,

First of all, thank you very much for this awesome project.

I'm coding a web page that is pretty close to yours [editor page](https://www.brython.info/tests/editor.html).
So I'm looking into the code to better understand how it works.

I was reading the [view source of editor.html](view-source:https://www.brython.info/tests/editor.html)
Trying to understand what happens when clicking in Run button. I notice that it binds button onclick event into a lambda that receives the params to ignore it and call editor.run()
```python
doc['run'].bind('click',lambda *args: editor.run())
```

But I couldn't find this file browsing Firefox web inspector. So I got into this git, found the editor.py file.
There I didn't find the run method in Editor class. I've seen that this editor module "exports" a editor instance that is constructed by  `make editor` function. Anyways, couldn't find the run method. Could you help me with it? Where is this `editor.run()` coming from?

One other thing I've notice is the file editor.html is not the same I'm seeing in inspect source-code in browser. 
Here in git I've the file just calls the editor.py script. `<script type="text/python" src="editor.py">`, but when seeing the inspect source-code, it shows a page with script tag with a script that does the binding in the buttons. What am I missing here?

Thank you very much for your attention and for brython. :anchor: :snake:

**Comment by wviana** [comment]
Oh, I think I was looking into wrong files. The right ones are www/tests/editor.py and www/tests/editor.html.

**Comment by PierreQuentel** [comment]
Can we close the issue then ?
