### ISSUE TITLE
`_socket.getaddrinfo` not working

### ISSUE THREAD

**Issue by GLanguage** [brython-dev/brython#1950]
I have got a long error in my browser when using brython to connect a server, and I have found that it was because `_socket.getaddrinfo`  returned `None`. So I created a minimal example:

```python
import _socket
print(_socket.getaddrinfo('localhost', 4000))
```

It can work on my Mac locally, but it outputs `None` with brython in the browser. Why is that happening?

**Comment by GLanguage** [comment]
It seems that `_socket.gethostbyname` is not working as well:

```python
import _socket
print(_socket.gethostbyname('localhost')
```

also returns `None`.

**Comment by GLanguage** [comment]
I tried:

```python
import _socket
print(_socket.gethostbyname('does.not.exist.com')
```

It raises a `socket.gaierror` locally, but still returns `None` in the browser. `getaddrinfo` is just the same.

**Comment by GLanguage** [comment]
Oh I see. Socket is not supported in the browser and `_socket.py` in `brython_stdlib.js` is an empty formal file.
But is there an alternative to socket? Like WebSocket or `browser.ajax`? (I'm not quite familiar with them)

**Comment by PierreQuentel** [comment]
Browsers cannot access the low-level network stack, this is why these functions return `None` (the **`socket`** module is present just to avoid `ModuleNotFoundError` in other stdlib modules that import it).

You can use **`browser.websocket`** or **`browser.ajax`**, but there again you will have the limitations imposed by the browser execution model, notably the "same origin" constraints.
