### ISSUE TITLE
ModuleNotFoundError: telebot (warning: cannot import local files with protocol 'file')

### ISSUE THREAD

**Issue by Vamashi** [brython-dev/brython#1951]
Hello, i've tried to import telebot module, writed `python -m brython --add_packages telebot`, but i got error:
`Traceback (most recent call last):
  File file:///C:/Users/someguy/Downloads/telegram%20site%20bot/index.html#script3 line 2, in <module>
    import telebot
ModuleNotFoundError: telebot (warning: cannot import local files with protocol 'file')`

**Comment by PierreQuentel** [comment]
As explained in the [documentation](https://www.brython.info/static_doc/en/file_or_http.html), you should run a web server and load the HTML page with its address starting with `http://` instead of opening it with the File/Open menu.

**Comment by Vamashi** [comment]
I runned it on localhost, but it still not working

**Comment by PierreQuentel** [comment]
I didn't know telebot, so I took a look and saw that it imports requests, which is not supported for reasons explained in the [FAQ](https://www.brython.info/static_doc/en/faq.html)
