### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by estarq** [brython-dev/brython#1956]
https://brython.info/src/identifiers_re.js returns 404.

**Comment by PierreQuentel** [comment]
@estarq This script is not used in the current Brython version. When do you get this 404 error ?

**Comment by estarq** [comment]
@PierreQuentel I got this on [the precompile page](https://brython.info/tests/precompile.html), and I thought that's why `x = 3` doesn't compile to JS.

Console output log:
```
precompile.html:8          GET https://brython.info/src/identifiers_re.js net::ERR_ABORTED 404
py2js.js:13870 Uncaught TypeError: Cannot read properties of undefined (reading 'push')
    at $B.parser._run_scripts (py2js.js:13870:30)
    at $B.parser.brython (py2js.js:13621:9)
    at onload (precompile.html:35:26)
$B.parser._run_scripts @ py2js.js:13870
$B.parser.brython @ py2js.js:13621
onload @ precompile.html:35
```
Those websites link to this script as well:
[speed/show_speed_results.html](https://brython.info/speed/show_speed_results.html)
[speed/upload_speed_results.html](https://brython.info/speed/upload_speed_results.html)
[speed/agg_speed_results.html](https://brython.info/speed/agg_speed_results.html)
[code_coverage/index.html](https://brython.info/code_coverage/index.html)

**Comment by PierreQuentel** [comment]
They are all old scripts that I forgot to remove from brython.info. You can get the same result as **`precompile.html`** with the "Javascript" button on the [editor](https://www.brython.info/tests/editor.html).

**Comment by PierreQuentel** [comment]
I have removed the scripts (except code_coverage for the moment because testing it helped me detect a bug in Brython) and I close the issue. Thanks for the report :-)
