### ISSUE TITLE
math.gamma domain errors under Brython

### ISSUE THREAD

**Issue by ajschult** [brython-dev/brython#1957]
Brython's math.gamma(x) triggers domain errors for values where -n < x < -n+0.5 with n is a non-negative integer.  From the Brython console:

Brython 3.10.5 on Netscape 5.0 (X11)
>>> import math
>>> math.gamma(1.25)
0.9064024770554773
>>> math.gamma(0.75)
1.2254167024651779
>>> math.gamma(0.25)
Traceback (most recent call last):
  File <string>, line 1, in <module>
ValueError: math domain error
>>> math.gamma(-0.25)
-4.9016668098607115
>>> math.gamma(-0.75)
Traceback (most recent call last):
  File <string>, line 1, in <module>
ValueError: math domain error

Fedora's python handles such values fine:

Python 3.10.4 (main, Mar 25 2022, 00:00:00) [GCC 11.2.1 20220127 (Red Hat 11.2.1-9)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import math
>>> math.gamma(1.25)
0.9064024770554773
>>> math.gamma(0.75)
1.2254167024651779
>>> math.gamma(0.25)
3.6256099082219087
>>> math.gamma(-0.25)
-4.90166680986071
>>> math.gamma(-0.75)
-4.834146544295877

**Comment by PierreQuentel** [comment]
Thanks for the report @ajschult.

I have rewritten `math.gamma` and `math.lgamma` by adapting their implementation in the CPython module [mathmodule.c](https://github.com/python/cpython/blob/main/Modules/mathmodule.c).
