### ISSUE TITLE
Brython chokes on valid script id

### ISSUE THREAD

**Issue by ed2050** [brython-dev/brython#1958]
Brython chokes when script id contains a dash, as in example below.
Dash (-) is a valid html character for ids and frequently used across the web.

No useful error messages are produced.  Brython dies with the following error, without identifying the line or text causing the problem:

> Firefox - Javascript error SyntaxError: missing ) after formal parameters

> Chrome  - Javascript error SyntaxError: Arg string terminates parameters early

**Example**
Put this text in an html doc and watch brython choke when you open it.  Fun!

```
<html>
<head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/brython/3.10.5/brython.min.js">
</script>
    <script type="text/python" id="this-sucks">
    print ('hello world')
    </script>

</head>

<body onload="brython();">
    <h1>Brython barfs!</h1>
    <p>
    Open the console and watch brython barf all over everything.
    </p>
</body>
</html>
```

**Comment by PierreQuentel** [comment]
A funny one, thanks !
