### ISSUE TITLE
IndentationError is reported with Traceback which is not consistent with Python

### ISSUE THREAD

**Issue by zwz** [brython-dev/brython#1959]
I tested the code in https://brython.info/tests/editor.html
```
n = int(input('value: '))
ifx
  n = 1
```
It reports:
```
Traceback (most recent call last):
  ...
  File <string>, line 3, in <module>
IndentationError: unexpected indent
```

While with the code
```
n = int(input('value: '))
ifx:
  n = 1
```
it reports:
```
  File <Javascript undefined>, line 2
    ifx:
         ^
SyntaxError: invalid syntax (empty annotation) 
```
which is more consistent to Python.

IMO, trackback means the program runs without any syntax error.
However, `n = int(input('value: '))` does not run at all in the first case.
If you test the code with `python test.py` on you computer, you will see something quite similar to the second case:
```
  File "test.py", line 3
    n = 1
    ^
IndentationError: unexpected indent
```
No traceback and more informative.

So I think IndentationError should be treated like a syntax error.

**Comment by PierreQuentel** [comment]
Thanks for the report @zwz . The commit referenced above fixes the examples, but it's hard to imagine all the possible syntax / indentation errors; if you find other one don't hesitate to comment this issue or create a new one.

**Comment by zwz** [comment]
@PierreQuentel 
So quick.
I will, I like the project.
