### ISSUE TITLE
a scope error is handled differently from CPython

### ISSUE THREAD

**Issue by LuKC1024** [brython-dev/brython#1961]
This program prints `So far, n is 0` before raising an `UnboundLocalError`. This behavior is different from CPython, which doesn't print.

```python
xs = ["a", "a", "b", "a", "c"]
n = 0
def count(xs):
    for x in xs:
        print("So far, n is", n)
        n += 1
count(xs)
```

**Comment by PierreQuentel** [comment]
Thanks for the bug report @LuKC1024 !
