### ISSUE TITLE
brython does not work in the Brave browser.

### ISSUE THREAD

**Issue by DwayneDibley** [brython-dev/brython#1965]
I used the brave browser to try and run some of the examples and received many errors:
    - ReferenceError: bool is not defined
    - ReferenceError: bytearray is not defined
    -  etc.

If this cannot be easily fixed, it may well be a good idea to have a brython browser compatibility list on the homepage to help noobs like me not waste their time.

Of course switching to firefox solved the problem for me.

Thanks...

**Comment by PierreQuentel** [comment]
I have just downloaded Brave (on Windows 10), the whole [test suite](https://brython.info/tests/index.html) passes without error.

Can you try this suite on your machine ? Or send an url where I can reproduce the errors you mention ?

**Comment by DwayneDibley** [comment]
Mea Culpa, found the problem.

I was running the browser with "Pause on caught exceptions" turned on as I always do when developing. Brython obviously has some handled exceptions internally when running.  Turned this off and everything works fine.

Sorry Guys.

FYI: I ran the test suite on Brave Version 1.35.104 and MacOs Catalina 10.15.7, no errors.

Once again sorry for wasting your time.

**Comment by PierreQuentel** [comment]
No worries !
