### ISSUE TITLE
TypeError on Android

### ISSUE THREAD

**Issue by shark-in-a-hat** [brython-dev/brython#1969]
Using 3.10.6 (copied form the repo today, bc003e6 )
```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script type="text/javascript" src="brython.js"></script>
        <title id="title"> Brython Audio Test</title>
        
    </head>    
    <body lang="en-US" onload="brython({debug:1, indexedDB:0})" >

        <audio id="music_player">
            <source src="song1.mp3" type="audio/mpeg">
        </audio>

        <button type="button" id="play_button"> Play  </button>
        <button type="button" id="song1"> Song 1 </button>
        <button type="button" id="song2"> Song 2 </button>

        <script type="text/python">
            from browser import document as doc
            from browser import bind

            def play(event):
                doc['music_player'].play()                

            def change(event):
                song_url = event.target.id+'.mp3'
                music_player = doc['music_player']
                music_player.src = song_url
                music_player.load()
                music_player.play()

            doc['play_button'].bind('click', play)
            doc['song1'].bind('click', change)
            doc['song2'].bind('click', change)

        </script>
    </body>
</html>
```
This is a small example of how I wanted to play some audio in the browser. This works fine on Firefox and Chrome on Windows10, but gives out a Type error when trying to run on Android. Chrome and Firefox on Android has no console, so I can't tell if the error is the same there, but Kiwi Browser (a chrome clone) spits out this and plays nothing:

```
TypeError: Cannot read properties of undefined (reading 'split')
	at warn (brython.js:13128:47)
	at DOMNode.__setattr__ (brython.js:13141:48)
	at Object.$B.$setattr (brython.js:6916:1)
	at change6 (eval at $B.loop (brython.js:4588:12), <anonymous>: 90:4)
	at HTMLButtonElement.<anonymouse> (brython.js:13154:58)
```

I would normally say it's an Android quirk, can't be helped, but this code used to work back on 3.10.4 (can't say what exact version, but I still have the brython.js saved locally - so maybe there's a way to extract any more details from it - I just don't know how).

**Comment by PierreQuentel** [comment]
I have uploaded the html page as **`test_1969.html`**, **`brython.js`** and the mp3 in a folder /www in the "Phone" drive of my mobile, opened Samsung Internet and entered _file:///sdcard/www/test_1969.html_ in the address bar, the song plays.

I couldn't test with Chrome or Firefox because I don't know where to put the files and which url I should enter (it doesn't seem to work the same as Samsung Internet).

**Comment by shark-in-a-hat** [comment]
Thanks for the fix. I can confirm it works now.
