### ISSUE TITLE
Regression in datetime tests (strptime)

### ISSUE THREAD

**Issue by schmave** [brython-dev/brython#1970]
This test from test_datetime doesn't pass right now: 

```python
from datetime import datetime
date = "Thu, 26 Aug 2021 00:00:00 GMT"
dt = datetime.strptime(date, "%a, %d %b %Y %H:%M:%S GMT")
assert dt == datetime(2021, 8, 26, 0, 0)
```

I see the same behavior with 3.10.6 and also the latest master branch.

**Comment by PierreQuentel** [comment]
Hello Evan,

The test passes for me, both on brython.info editor and with the latest dev version. What is the value of `dt` for you ?

**Comment by schmave** [comment]
Oh, strange! Maybe it is browser-specific somehow. 

dt is `2021-09-26 00:00:00` for me, in Chrome v102 on a Mac.

**Comment by schmave** [comment]
I see the same value with Firefox v101 on a Mac as well.

**Comment by PierreQuentel** [comment]
I haven't found where this could come from. Could you try [this page](https://www.brython.info/tests/test_strptime.html) ? The result for me is :

```
locale is C
shortmonths: Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec 
```

If it's the same for you, maybe we could make a live debugging session on Zoom ?

**Comment by schmave** [comment]
Thanks for taking a look! I'm happy to help debug this if I can. I see this on your test page:

```
locale is C
shortmonths: Dec,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov
```

**Comment by PierreQuentel** [comment]
Thanks Evan, I think I understand. Can you try again with the new version of the same page ?

**Comment by schmave** [comment]
Looks good. I now see:

```
locale is C
shortmonths: Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec
```
