### ISSUE TITLE
phaser demo on brython.info broken due to https/http mixed content failure

### ISSUE THREAD

**Issue by godmar** [brython-dev/brython#1973]
https://www.brython.info/gallery/phaser.html
is broken due to mixed content (http/https) being disallowed; I believe setting:

```python
 this.load.setBaseURL('//labs.phaser.io')
```
instead of
```python
 this.load.setBaseURL('http://labs.phaser.io')
```
might fix that.

**Comment by PierreQuentel** [comment]
Good catch @godmar ! I have updated brython.info, it should be ok now.

**Comment by godmar** [comment]
[runaround-with-brython.zip](https://github.com/brython-dev/brython/files/8933731/runaround-with-brython.zip)

BTW, I ported another small Phaser example to Brython (see attachment); this is translated from [Emanuele Feronota's blog](https://www.emanueleferonato.com/2020/08/13/html5-prototype-of-run-around-game-builth-with-phaser-with-no-physics-engines/)

**Comment by PierreQuentel** [comment]
Very cool demo ! I have uploaded it on [brython.info](http://brython.info/gallery/runaround-with-brython/runaround.html). 

Would you like your real name to appear ?

**Comment by godmar** [comment]
Sure, no problem.  I don't know if there's a copyright issue with Emanuele's work, though. Let's make sure to give him proper credit.

**Comment by PierreQuentel** [comment]
You are right, I have sent him an email. I only know you Github account, what is your name ?

**Comment by godmar** [comment]
Godmar Back (godmar@gmail.com)
