### ISSUE TITLE
$DebuggerCtx has no ast() function

### ISSUE THREAD

**Issue by schmave** [brython-dev/brython#1978]
Running this code on brython.info gives an error:

```python
if 1 == 0:
    __debugger__
```

```
Traceback (most recent call last):
  File https://brython.info/tests/editor.html?lang=en#tests_editor, line 29, in lambda_q98a6a4b_4
    doc['run'].bind('click',lambda *args: editor.run())
  File https://brython.info/tests/editor.py, line 124, in run
            traceback.print_exc(file=sys.stderr)
Exception: <Javascript TypeError>: ctx.ast is not a function
<completed in  14.00 ms>

```

**Comment by PierreQuentel** [comment]
Thanks Evan. The name `__debugger__` probably had a special meaning in the early days of Brython...

**Comment by schmave** [comment]
Oh yeah, I actually still find it very useful when debugging issues. It (used to) insert a Javascript `debugger` statement in the generated Python code so that you could easily jump into the compiled output. Is it possible to put it back with that behavior?

**Comment by PierreQuentel** [comment]
Ah, I had forgotten about it. The commit above restores the previous behaviour.

**Comment by schmave** [comment]
Wonderful, thank you!
