### ISSUE TITLE
sum() last argument is used as the accumulator for bytes` lists.

### ISSUE THREAD

**Issue by haael** [brython-dev/brython#198]
When I perform this sequence:
    > l = [b"x", b"y", b"z"]
    > sum(l[1:], l[0])
    b'xyz'
the result of the sum is correct, but the value of l becomes:
    > l
    [b'xyz', b'y', b'z']
as if the second argument l[0] was used as a mutable accumulator.

Interestingly enough, this does not happen when using strings in place of bytes.

By the way, Python3 documentation states that sum() can not be a used to concat strings.

**Comment by earney** [comment]
haael,
Thanks for posting the issue.

It seems that bytes cannot be used with the function sum as shown below...

```
>>> l
[b'x', b'y', b'z']
>>> sum(l, l[0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: sum() can't sum bytes [use b''.join(seq) instead]
>>> sum(l, 0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for +: 'int' and 'bytes'
>>> sum(l, 'a')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: sum() can't sum strings [use ''.join(seq) instead]
```
so I've modified the sum function to perform more like the CPython version.  Thanks for making us aware of the inconsistencies..
The modified version has been pushed to the repo.
