### ISSUE TITLE
Uncaught ReferenceError: __BRYTHON__ is not defined at brython_stdlib.js:1:1

### ISSUE THREAD

**Issue by zwz** [brython-dev/brython#1982]
I am using Edge (version 103.0.1264.51) browser on MacOS.

Brython is loaded with
```
<script src="brython.js"></script>
<!-- <script>console.log(__BRYTHON__)</script> -->
<script src="brython_stdlib.js"></script>
```

It reports error `Uncaught ReferenceError: __BRYTHON__ is not defined at brython_stdlib.js:1:1`.

And I refresh the page many times.  The error appears/disappears randomly.

If I uncomment the second `<script>`,  it always reports `Uncaught ReferenceError: __BRYTHON__ is not defined`.

It seems that `__BRYTHON__` does not take place immediately after loading "brython.js". 
There is a delay.

**Comment by PierreQuentel** [comment]
Sorry for the late answer.

I can't reproduce the bug, the console shows the object `__BRYTHON__` (except of course if there is no script **`brython.js`** at the url specified in <script src="brython.js">`, in which case I get the error message you report).

**Comment by zwz** [comment]
It seems that it happens only in Edge (version 103.0.1264.51) browser on MacOS.
