### ISSUE TITLE
Brython 3.10.6 python-to-javascript engine bug?

### ISSUE THREAD

**Issue by zwz** [brython-dev/brython#1983]
I tried the code in console with Brython 3.10.6
```
__BRYTHON__.python_to_js(`
class Test:
    def __init__(self):
        pass
`)
```
It reports error: `TypeError: undefined is not an object (evaluating 'module_id.replace')`

While it works with Brython 3.10.5.

How to make it work with the new version?

**Comment by PierreQuentel** [comment]
I don't think it would have worked in any Brython version, because the backtick ( ` ) is not valid in Python.

Inside a Javascript script the code works.

**Comment by zwz** [comment]
Yes, I have the code in the "console" tab of browser devtools.
It works for 3.10.5, but not for 3.10.6.

**Comment by PierreQuentel** [comment]
It works for me on Firefox and Chrome
![issue_1983](https://user-images.githubusercontent.com/3447215/179205127-864e90e5-2122-4adf-9b76-32f04f05a414.png)

**Comment by zwz** [comment]
That is weird.
I test on safari (15.5) 
![截屏2022-07-16 下午6 23 18](https://user-images.githubusercontent.com/897156/179351073-8a49e34e-529f-40f9-843c-b16d0814ed8d.png)

and edge (103.0.1264.51)
![截屏2022-07-16 下午6 21 14](https://user-images.githubusercontent.com/897156/179351072-af8f1da0-8b00-426e-bc1d-7e5bc6e12def.png)

**Comment by PierreQuentel** [comment]
My mistake, sorry: I tested with the current development version, not with release 3.10.6... 

I could reproduce the bug with 3.10.6 but it is fixed in the development version. Can you confirm ?

**Comment by zwz** [comment]
Confirmed.
