### ISSUE TITLE
Module defined in inline <script> tag should be executed only after it was imported by main

### ISSUE THREAD

**Issue by shlomil** [brython-dev/brython#1984]
Given the following html:
```
<body onload="brython()">
<script type="text/python" id="file1">
print("file1 executed")
def do():
  print("file1 do")
</script>
<script type="text/python">
print("main exec")
import file1
file1.do()
</script>
</body>
```
the output is:
```
file1 executed
main exec
file1 do
```
but placing the code in files an running with python3 the output is:
```
main exec
file1 executed
file1 do
```
AFAIK a module is not supposed to be executed before it is imported.
using Brython 3.10.6

**Comment by PierreQuentel** [comment]
Thanks for repoting this @shlomil. You are right, this is not how imports generally work in Python. 

In Brython, scripts with type = text/python are always executed. The ability to import them by their id is an answer to a question that has been asked from time to time : how can a script use names defined in another one ? Using `import` in this case seemed the most natural (a little like in CPython some modules are loaded before the interpreter starts, and this can be customized by PYTHONSTARTUP or the **`site`** module).

Would you have another suggestion ?

**Comment by shlomil** [comment]
@PierreQuentel Thank you for your work on this cool project. Using import is the only logical way I see but I would expect actual execution will occure only after the import. OTOH, changing this behaviour does have the potential to confuse people who just wanted to use a proper id for their script tag. Maybe the solution would be adding some custome data-* attribute to tell brython to delay execution until imported or, even better - let the user specify a full path and  file name to be added virtually (to the VFS?) and load it by demand when imported, this way you could list full modules with multiple files using the script tags.

**Comment by denis-migdal** [comment]
Hi,

> let the user specify a full path and file name to be added virtually (to the VFS?) and load it by demand when imported, this way you could list full modules with multiple files using the script tags.

Nowadays, we can use a [`<link rel="preload" href="file1.py" as="???" />`](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel/preload) to prefetch dependencies without executing them. Maybe Brython could somehow make use of that ?

Another solution would be to add a new `<script type="text/python-module"></script>` to tell Brython to only execute it upon first importation by another file ?

Cordially,
