### ISSUE TITLE
[Suggestion] Expanded cache control options

### ISSUE THREAD

**Issue by xanthics** [brython-dev/brython#1985]
Currently, at least from what I can find in the documentation, cache supports `true` or `false` with no granularity.  My proposal is to expand cache options to also support a custom version number so that a page can take advantage of cache, while also being able to quickly be aware of a new version of a resource.

Currently
```html
<body onload="brython({debug: 1, pythonpath: ['/', './', '../'], cache: true})">
[...]
<script type="text/python" src="py_modules/main.py"></script>
</body>
```

With this implementation I can do manual cache control by adding a `?timestamp` to prompt grabbing updated versions of main.py, or using the version that caches up to 30 days.

However I run in to issues with code like
```python
	# get guide strings
	if lang == 'es':
		from py_modules.items_es import ilist
	elif lang == 'de':
		from py_modules.items_de import ilist
	elif lang == 'fr':
		from py_modules.items_fr import ilist
	else:
		from py_modules.items_en import ilist

	for el in doc.get(selector="[data-lang]"):
		el.text = ilist[int(el.attrs['data-lang'])]
```

As each of those files are ~330 kB, I'd prefer to cache them unless there is a change in the original file.  Those files are usually static, but can have some changes on a "every few months" cycle.  However it is also important that once there is a change in those files that the client is immediately aware of it, otherwise other code will misbehave.  

Is the best option here to change the name of the files themselves (eg `items_fr_v2`) as they are updated?  Or would it make sense to add another parameter to `brython()` when cache=true to allow a custom version query string on resources?

**Comment by PierreQuentel** [comment]
Salut Jeremy ;-)

Part of the problem here is the time to parse modules with big literal dictionaries such as **`items_en.py`**. 

The 2 commits referenced above reduce this time from more than 5 seconds to around 0.5 secs, which could hopefully reduce the need for a more complex cache option.

**Comment by xanthics** [comment]
Checking in that I'm currently waiting for the next release to check this out.  I've tried and failed to install the github files

![image](https://user-images.githubusercontent.com/3137623/188215717-adb43ae2-00d0-4da8-b518-946a0bc4cd98.png)

(Need access to brython-cli for make_modules)

**Comment by PierreQuentel** [comment]
It might be because make_dist must be executed in its own folder, and because setup requires an additional argument (`python setup.py sdist` or `python setup.py install`)

**Comment by xanthics** [comment]
Running `make_dist` in its folder was the issue.

The speed improvements are quite noticeable and the file sizes are good.  The processing time for swapping out languages is quite acceptable now also 👍.  For this project the existing cache control options is now sufficient, thank you.

Site in question [https://gw2crafts.net/beta/armorcrafting.html?lang=fr&ui=fr](https://gw2crafts.net/beta/armorcrafting.html?lang=fr&ui=fr) (I have advertising on my site, so I'd recommend ublock origin or suchlike if you visit).
