### ISSUE TITLE
Binary shift operators don't work as expected

### ISSUE THREAD

**Issue by haael** [brython-dev/brython#199]
The results of binary shift operators << and >> are different in Brython than in CPython when exceeding 32-bit precision.

For instance:
1 >> 32
In CPython: 0
In Brython: 1

When using the << operator on positive integers Brython sometimes yields negative integers. This never happens in CPython.

**Comment by PierreQuentel** [comment]
This is for the same reason as issue #200 : for big integers you can use the `long_int` module

```
>>> LongInt(1) >> LongInt(32)
LongInt('0')
```
