### ISSUE TITLE
PyPDF2 using Brython

### ISSUE THREAD

**Issue by stefnotch** [brython-dev/brython#1992]
I was trying to get PyPDF2 to run in the web browser. To do so, I used Brython to create a `PyPDF2.brython.js` (following the https://brython.info/static_doc/en/brython-packages.html tutorial). 

Then, I imported it
```py
<script src="brython.js"></script>
<script src="brython_stdlib.js"></script>
<script src="PyPDF2.brython.js"></script>
```
and did a little smoke test to see if it worked
```html
<script type="text/python" id="script0">
    from browser import document, alert
    from PyPDF2 import PdfReader

    def hello(ev):
        alert("Hello !" + PdfReader.__name__)

    document["button_alert"].bind("click", hello)
    </script>
```

![image](https://user-images.githubusercontent.com/10220080/184178846-4727f966-8916-46d6-b554-9aa9ed5c61d0.png)

after haphazardly commenting out said import in the library and recreating the `PyPDF2.brython.js`, I ended up with a different error

![image](https://user-images.githubusercontent.com/10220080/184178703-1e79c22e-c318-45e9-86db-c8fea3c38754.png)

To make debugging a bit easier:
1) Install PyPDF2
2) `brython-cli make_package PyPDF2` (though I directly imported Brython and called its APIs, bypassing the CLI)
3) Put the resulting file here and open the `demo.html`
[data.zip](https://github.com/brython-dev/brython/files/9310099/data.zip)

**Comment by stefnotch** [comment]
And for completeness, I avoided installing Python for this, since I wanted to use it in a toolchain that doesn't have a hard dependency on Python. Especially since installing Python on Windows has a terrible UX.

Steps:
1) Download Python (not easy to make cross-platform, which sucks)
2) Download Brython <https://pypi.org/project/brython/#files>
3) Copy the `brython` folder to some accessible location
4) Download <https://pypi.org/project/PyPDF2/#files>
5) Copy that to an accessible location. Current example structure
python-3.10.6-embed-amd64/
python-3.10.6-embed-amd64/brython/
python-3.10.6-embed-amd64/brython/make_package.py
python-3.10.6-embed-amd64/brython/*
python-3.10.6-embed-amd64/PyPDF2/
python-3.10.6-embed-amd64/PyPDF2/*
6) Execute
from brython.make_package import make
make("PyPDF2", "./PyPDF2/PyPDF2", None, "./PyPDF2.brython.js")
7) Now you have a "PyPDF2.brython.js"

**Comment by stefnotch** [comment]
(Relevant question I found on Stackoverflow: https://stackoverflow.com/questions/67239804/how-to-call-python-function-in-html-tag )

**Comment by PierreQuentel** [comment]
Thanks for the report @stefnotch !

The commits above fix a few bugs that caused the errors you mention. Unfortunately, PyPDF2 can't work in Brython currently because it uses the stdlib xml package, which is not supported because it relies on a .pyd file (pyexpat.pyd) and I haven't found a replacement so far.

**Comment by stefnotch** [comment]
@PierreQuentel Thank you for the fixes, much appreciated. The xml dependency is quite unfortunate, I suppose there's no easy work-around here.

Re-implementing [expat](https://github.com/python/cpython/tree/main/Modules/expat) seems like a significant amount of effort, for not all that much benefit. Compiling to to WebAssembly ([like this](https://github.com/python/cpython/tree/main/Modules/expat)) might be ever so slightly easier, but shipping WebAssembly with Brython seems out of scope for now.

And I sadly couldn't find a drop-in replacement for the xml package.
