### ISSUE TITLE
python_to_js doesn't work on master

### ISSUE THREAD

**Issue by schmave** [brython-dev/brython#1996]
Calling `python_to_js("x = 1 + 2")` returns:

```js
(function() {
 var $locals___main__ = {}
// Javascript code generated from ast
var $B = __BRYTHON__,
_b_ = $B.builtins,
locals_exec = $B.imported["exec"],
locals = locals_exec,
$top_frame = ["exec", locals, "exec", locals]
locals.__file__ = '<string>'
locals.__name__ = 'exec'
locals.__annotations__ = $B.empty_dict()
locals.__doc__ = _b_.None
locals.$f_trace = $B.enter_frame($top_frame)
$B.set_lineno(locals, undefined)
var stack_length = $B.frames_stack.length
try{
$B.set_lineno(locals, 1)
var v1 = $B.rich_op('__add__', 1, 2)
locals_exec.x = v1
$B.leave_frame({locals, value: _b_.None})
}catch(err){
$B.set_exc(err)
if((! err.$in_trace_func) && locals.$f_trace !== _b_.None){
locals.$f_trace = $B.trace_exception()
}
$B.leave_frame({locals, value: _b_.None})
throw err
}
}())
```

`$B.imported["exec"]` is undefined, so this code crashes when assigning to `locals.__file__`. I think this is due to a change more recent than d084f7b. 

Thanks for any help you can provide.

**Comment by schmave** [comment]
Wonderful, thanks for all the fixes!

**Comment by PierreQuentel** [comment]
Thank you for all the reports Evan !

Since `python_to_js()` is not documented, I changed its interface so that `exec(js_code)` returns the globals of the Python program. 

For instance:
```javascript
var globs = eval(__BRYTHON__.python_to_js("x = 1 + 2"))
console.log(globs.x) // 3
```

**Comment by schmave** [comment]
Returning the globals seems nice. I discovered that python_to_js doesn't work properly if you run two different python programs without calling python_to_js() in between:

```js
xcode = __BRYTHON__.python_to_js('x = 1 + 2')
ycode = __BRYTHON__.python_to_js('y = 1 + 2')
eval(xcode)
ns = eval(ycode)
```

At the end of this JS code, `ns.x` and `ns.y` are both equal to 3. I would expect that `ns.y` would be undefined.
