### ISSUE TITLE
How to reuse the same code on backend and frontend?

### ISSUE THREAD

**Issue by LeeSoftRu** [brython-dev/brython#1999]
As an example i would like to:

- use the same dataclasses in a server logic and in brython
- it's critical to get autocomplition in both part of the project for these dataclasses

**Comment by LeeSoftRu** [comment]
The best solution I've found so far is:
```
project/
    DataClasses/
    web/
      ui.py
        from DataClasses import *
      ui.html
        <script type="text/python" src="../DataClasses/__init__.py" id="DataClasses"></script>
    server.py
      from DataClasses import *
```

**Comment by LeeSoftRu** [comment]
But when i am move the dataclasses into separate files
```
project/
    DataClasses/
      __init__.py
      SomeDataclass1.py
      SomeDataclass2.py
```
i get an error: `DataClasses is not a package`

**Comment by aehlke** [comment]
Did you figure it out?

**Comment by nacho00112** [comment]
May be the `brython-cli make_package` is the tool that help in this cases,
I never used it but i know it generates a loadable script from a package.
