### ISSUE TITLE
Big integers have only 56 bits of precision

### ISSUE THREAD

**Issue by haael** [brython-dev/brython#200]
Long integers with more than 56 significant bits are broken.

> 0x123456781234567812345678
In CPython: 5634002657842756053938493048
In Brython: 5.634002657842756e+27

> hex(0x123456781234567812345678)
In CPython: '0x123456781234567812345678'
In Brython: '0x123456781234560000000000'

**Comment by PierreQuentel** [comment]
For performance reasons, Brython implements integers as Javscript numbers, which are "safe" only in the range [-2\*\*53, 2\*\*53]. For integers out of this range, there is a module `long_int` with a class `LongInt` that you can use in this example : 

```
>>> from long_int import LongInt
>>> x = LongInt('123456781234567812345678', 16)
>>> print(x)
LongInt('5634002657842756053938493048')
```

This will be documented in version 3.1.4.
