### ISSUE TITLE
Undefined name: 'ast_options' in scripts/make_ast_classes.py

### ISSUE THREAD

**Issue by cclauss** [brython-dev/brython#2004]
Fixed in #2011

$ `flake8 --select=E9,F63,F7,F82 --show-source scripts/make_ast_classes.py`
```
scripts/make_ast_classes.py:33:47: F821 undefined name 'ast_options'
            ast_types[ast_type] = {'options': ast_options}
                                              ^
```

**Comment by PierreQuentel** [comment]
I don't understand why the name is tagged "undefined" by flake8, it is defined in the rest of the code.

**Comment by cclauss** [comment]
The variable is used on a line before it is used.  See #2011 for the simple fix.

**Comment by PierreQuentel** [comment]
The line where `ast_options` is used is never reached before the name is actually defined (otherwise the code would break).

**Comment by cclauss** [comment]
Yes, the _current_ logic prevents the undefined variable situation but what happens if there is a change to the logic?  A compiler would enforce the same safeguards as `flake8` as a precaution against breakage in future code changes.

**Comment by PierreQuentel** [comment]
If there is a change to the logic, the program will fail, and the devoloper will fix the bug...

I will accept the PR, but I am not pleased to have to change valid Python code only because a style guide enforces it.
