### ISSUE TITLE
Module `random` lacks `randbytes` function

### ISSUE THREAD

**Issue by Syndace** [brython-dev/brython#2016]
Hi,

I believe the JavaScript replacement for the `random` module lacks the `randbytes` function.

**Comment by Syndace** [comment]
Hey, thanks, that was amazingly fast!

I think there are two typos in your implementation though: `randint` in `var $ = $B.args('randint', 2,` should probably read `randbytes` instead, and the `ValueError` message should probably say `bytes` instead of `bits`. Also maybe add a simple call to `www/tests/test_random.py` for completeness?

**Comment by PierreQuentel** [comment]
Thanks, done !
