### ISSUE TITLE
`bytes()` doesn't call `__bytes__` magic method

### ISSUE THREAD

**Issue by Syndace** [brython-dev/brython#2017]
Snippet:

```Python3
class Foo:
    def __bytes__(self) -> bytes:
        return b"Bar"

print(bytes(Foo()))
```

This should print `b'Bar'`, but crashes instead with `TypeError: 'Foo' object is not iterable`.

**Comment by PierreQuentel** [comment]
Thanks for the bug report ! It was fixed by commit 19732699bad62fb079b2b41c47e8b6d78d3464a9
