### ISSUE TITLE
`unittest.mock` cannot be imported

### ISSUE THREAD

**Issue by Syndace** [brython-dev/brython#2019]
Hi,

if I understand the [stdlib documentation](https://brython.info/static_doc/en/stdlib.html) correctly, `unittest.mock` should be available, but trying to import it fails with a different error depending on how the import is attempted:

```HTML
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <script src="https://raw.githack.com/brython-dev/brython/master/www/src/brython.js"></script>
        <script src="https://raw.githack.com/brython-dev/brython/master/www/src/brython_stdlib.js"></script>
    </head>
    <body onload="brython()">
        <script type="text/python">
            # Raises `ImportError: cannot import name 'mock'`:
            from unittest import mock

            # Fails on JavaScript level with `TypeError: klass.$infos is undefined`:
            import unittest.mock
        </script>
    </body>
</html>
```

**Comment by schmave** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [RecursionError doesn't include a stack trace (Brython bug)](https://trello.com/c/6VWkM6rN/931-recursionerror-doesnt-include-a-stack-trace-brython-bug)

**Comment by Syndace** [comment]
Thanks! I've also never seen `__class__` as a property, Python really is a dynamic language :D

Yes, I guess that asyncio is a problem that will only continue growing over time, since it's part of the standard library. Maybe the best move would be to implement as much of asyncio as possible and raise from those functions that can't be provided in the Browser environment.
