### ISSUE TITLE
RecursionError "too much recursion" doesn't include any stack info

### ISSUE THREAD

**Issue by schmave** [brython-dev/brython#2021]
Running this code in the online editor:

```python
def f():
    f()
    
f()
```

prints:

```
Traceback (most recent call last):
  File https://brython.info/tests/editor.html?lang=en#tests_editor, line 29, in lambda_926sqjta_4
    doc['run'].bind('click',lambda *args: editor.run())
  File https://brython.info/tests/editor.py, line 124, in run
            traceback.print_exc(file=sys.stderr)
RecursionError: too much recursion
<completed in 776.00 ms>
```

In CPython 3.10, I get:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in f
  File "<stdin>", line 1, in f
  File "<stdin>", line 1, in f
  [Previous line repeated 996 more times]
RecursionError: maximum recursion depth exceeded
```

The removal of duplicate frames doesn't really matter to me, but it would be great to get at least some line info so that you can tell where your error is. Thanks!

**Comment by schmave** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [RecursionError doesn't include a stack trace (Brython bug)](https://trello.com/c/6VWkM6rN/931-recursionerror-doesnt-include-a-stack-trace-brython-bug)

**Comment by PierreQuentel** [comment]
Thanks Evan. The Brython engine relied on Javascript to raise recursion errors, but since the frames stack is managed by Brython, it is much more efficient to raise `RecursionError` when its size is above a threshold (I took 1000, like CPython default). This is what the commit implements.

The duplicate frames are shown 3 times in the error trace like with CPython.

**Comment by schmave** [comment]
This is wonderful, thanks!

**Comment by PierreQuentel** [comment]
Reopening, things to fix in different contexts (editor, console, etc...)
