### ISSUE TITLE
Absolute value sometimes converts floats to ints

### ISSUE THREAD

**Issue by lsands50** [brython-dev/brython#2024]
This code prints 2.5 in Python, but in Brython it prints 2:

```
x = -5
x /= 2
print(abs(x))
```

**Comment by PierreQuentel** [comment]
Thanks for the report @lsands50 !

The bug exists in the current release (3.10.6) but is fixed in the current development version. Can you check ?

**Comment by schmave** [comment]
Yes, I just double checked that this is fixed.
