### ISSUE TITLE
Function not passing parameter correctly

### ISSUE THREAD

**Issue by mrwwalmsley** [brython-dev/brython#203]
The following code is not working correctly.
it's actually modifying the value of a primitive variable passed into a function, even if the variable has a different name inside and outside the function.

For example, try running the code below and type 25 as the price and 10 as the discount.

The message says:
The new price after a 10% discount on $22.50 is $22.50

It should say:
The new price after a 10% discount on $25.00 is $22.50

    # Function to force numeric input
    def force_number(message):
      while True:
        try:
          number = float(input(message))
          break
        except ValueError:
          print("Please enter a number!")
      
      return number
 
    #This function calculates the price after a discount and returns it. It takes 2 parameters: price and discount.
    def calc_discount(price, discount):
      #Turn the discount % into a decimal
      discount_value = discount / 100 
  
      #Calculate the amount to discount and take off price
      discount_amount = price * discount_value
      price -= discount_amount
  
      return price
  
    #Ask the user for the price and discount amount
    price2 = force_number("Please enter the price of the item e.g. 29.99: ")
    discount = force_number("Please enter the % discount e.g. 10: ")
 
    #Calculate new price and inform the user
    new_price = calc_discount(price2, discount)
    print("The new price after a {:.1f}% discount on ${:.2f} is: ${:.2f}.".format(discount, price2, new_price))

**Comment by dkosbie** [comment]
Here is a simpler version of the same bug:
```
def f(z):
  z += 1
  return z

x = 1.0

print(x is f(x)) # True in Brython, False in Python
```

**Comment by PierreQuentel** [comment]
This one was not easy to fix !

Its cause was that float objects were implemented as _mutable_ objects, so the result for floats was the same as for lists : 

```
def f(z):
    z += [1]
    return z

x = [0]

print(x is f(x)) # True in Brython and CPython
```

To make floats _unmutable_, while keeping them of a different type than integers, I have implemented them with the Javascript class `Number` : `x = 1.2` is translated into `x = new Number(1.2)`

I had to change all the places where floats are used in the Brython scripts, and there are a few of them... The latest commits pass all the built-in tests and fixes this issue, but I can't be sure it doesn't introduce any regression.

Thanks,
Pierre
