### ISSUE TITLE
Cross Site Scripting (DOM Based)

### ISSUE THREAD

**Issue by YeisonCardona** [brython-dev/brython#2035]
Running the code generated by `brython-cli install` (and any other Brython implementation), and then loading a URL like this:

`http://localhost:8000/#jaVasCript:/*-/*%60/*\%60/*'/*%22/**/(/*%20*/oNcliCk=alert(5397)%20)//%0D%0A%0d%0a//%3C/stYle/%3C/titLe/%3C/teXtarEa/%3C/scRipt/--!%3E\x3csVg/%3CsVg/oNloAd=alert(5397)//%3E\x3e`

Results in executing JavaScript code.

This appears in the ZAP reports as several issues with "Cross Site Scripting (DOM Based)", and are considered as a **high risk vulnerabilities**.

**Comment by PierreQuentel** [comment]
Thanks for the report @YeisonCardona , I will fix that as soon as possible.

**Comment by PierreQuentel** [comment]
This was fixed by commit 147cf7d8c49ed9118a4c11ceb54e54f6544ecb7e.
I will publish a new version shortly.

**Comment by PierreQuentel** [comment]
Version 3.10.7 is now published.

If you find other such vulnerabilities, please report them, I will of course put them on top of the to do list.
