### ISSUE TITLE
Checkbox Documentation

### ISSUE THREAD

**Issue by Akshu-on-github** [brython-dev/brython#2040]
## Problem Summary
It's unclear whether the input from checkboxes is supported. From what I can see, the `text`, `value` and `html` attributes for `document[id]` are all null for a checkbox (`<input type="checkbox" id="Fantasy">Fantasy`). If checkboxes are supported, I'd suggest adding an example under the form element code demo. If not, perhaps we could add a note that conveys the scope of the form elements supported by Brython along with whether or not the aforementioned elements are being worked on.

**Comment by PierreQuentel** [comment]
Thanks for the suggestion, I have added an item in the demo page.

Here is a short example: 
```xml
<input type="checkbox" id="cb">


<script type="text/python">
from browser import bind, document

@bind("#cb", "click")
def click(ev):
    print(ev.target.checked)
</script>
```

As a general rule, if Brython does not provide a custom API, you can always use the DOM API. This is what the example shows : the checkbox state is read from the boolean attribute `checked`.
