### ISSUE TITLE
No error raised when there are not enough values to unpack

### ISSUE THREAD

**Issue by schmave** [brython-dev/brython#2048]
Both of these lines raise exceptions in CPython, but do not do so in Brython. 

```python
[a, b] = [1]
(a, b) = (1,)
```

**Comment by PierreQuentel** [comment]
Thanks Evan. This has probably worked in previous versions...

**Comment by schmave** [comment]
Yeah, I assume it probably has. But with all the ways people can find to write invalid Python code, it's hard to know :) Thanks for the quick fix.
