### ISSUE TITLE
Ajax module for file sends are not usable as they are

### ISSUE THREAD

**Issue by mnealer** [brython-dev/brython#2051]
Hi

The ajax.send() and ajax.file_upload don't work very well, for file uploads.

Ajax.send() does not appear to use the FormData object for formatting and thus won't accept files, despite the documentation saying it will. There is no 'elt' object linked to a Javascript file object, so the documentation is wrong.

On the file_upload() it work, sort of, but does not appear to allow for modifying the header. I'm using Django and I need to send the csrf token in the header, or if I was using form based api tokens, I would need to add the token to the post, but file_upload() does not appear to allow for additional data, or header mods.

As such, when it comes to sending a form that includes one or more file uploads, the Ajax module doesn't seem to be able to cope.

Sorry if I'm wrong here, my JS is not strong, but I spent quite a bit of time trying to get this to work, with no luck

**Comment by PierreQuentel** [comment]
Thanks for the report @mnealer 
The commits referenced above should improve the ability to send files. If you find related issues, feel free to comment this issue or create a new one.
