### ISSUE TITLE
math.hypot doesn't work properly

### ISSUE THREAD

**Issue by jokoon** [brython-dev/brython#2053]
With brython:

`print(math.hypot(-68.75, -47.75)) # nan`

With JS:

`Math.hypot(-68.75, -47.75); // 83.70558523778446`

Not really sure what is happening

**Comment by coproc** [comment]
brython's `math.hypot` currently doesn't seem to work with `float` input

**Comment by PierreQuentel** [comment]
Thanks for the reports @jokoon and @coproc , should be ok now.

**Comment by jokoon** [comment]
No, thank you for the fix!
