### ISSUE TITLE
Unexpected output from JS functions which return lists of floats

### ISSUE THREAD

**Issue by austin-schick** [brython-dev/brython#2059]
If I write this JS code in my browser console

```
window.f = () => [0.1, 0.1];
```

and then run this Brython code

```
from browser import window
print(window.f())
```

the output is `[nan, nan]`. I expected the output here to be `[0.1, 0.1]`. 

Thanks for taking a look!

**Comment by PierreQuentel** [comment]
Thanks for the report Austin. The commit is a rewriting of the way Javascript lists can be accessed or modified by Brython code, with transparent type conversions.

**Comment by austin-schick** [comment]
Thanks Pierre! This looks very useful.
