### ISSUE TITLE
Custom `NameError` contains extra text in its message

### ISSUE THREAD

**Issue by austin-schick** [brython-dev/brython#2060]
Calling `raise NameError('test')` with CPython 3.10 produces the message `NameError: test`.

The same code run with Brython 3.10.7 produces the message `NameError: name 'test' is not defined.`

This is preventing us from creating `NameError`s with custom explanations and suggestions, but it’s a nitpicky bug and certainly not a blocking issue. I’m reporting it just so there’s a record of the problem :)

Thanks!

**Comment by PierreQuentel** [comment]
The issue revealed that the "suggestion" feature introduced in Python3.10 was not managed at the right place in Brython.
