### ISSUE TITLE
Bug when awaiting in an argument to a function call

### ISSUE THREAD

**Issue by Syndace** [brython-dev/brython#2067]
```Python
from browser import aio

async def coro():
    return "coro"

def takes_two_args(a, b):
    return a, b

async def test_awaited_arg():
    print(takes_two_args(await coro(), "second_arg"))

aio.run(test_awaited_arg())
```

This code produces two errors:

- A Python exception: `TypeError("takes_two_args missing 1 positional argument: 'b'")`
- A JavaScript exception: `TypeError: table is undefined`

The code works when `test_awaited_arg` is written like this instead, which should not make a difference:

```Python
async def test_awaited_arg():
    coro_result = await coro()
    print(takes_two_args(coro_result, "second_arg"))
```

**Comment by goffi-contrib** [comment]
Hi @PierreQuentel , this bug seems stalled, but it is a blocker for one of the use case we have with our project (using some backend code in the frontend). Is there anything preventing a fix? Thanks!

**Comment by PierreQuentel** [comment]
Bonjour Jérôme,

In fact the code works for me with the current version, I should have closed the issue. But since you ask I suppose that the bug is still there for you ?

**Comment by goffi-contrib** [comment]
No I haven't tried recently, I've asked because the bug is still open (sorry I should have checked first). The given code works for me on brython.info console, so I guess this bug can be closed.

@Syndace  is it fine by you?

Sorry for the noise and thanks for the quick (as usual!) feedback @PierreQuentel .

**Comment by Syndace** [comment]
Yes, seems fixed, thanks
