### ISSUE TITLE
In reference to the issue in #2047 Web3 Support for Brython 

### ISSUE THREAD

**Issue by Jyo561Python** [brython-dev/brython#2068]
@PierreQuentel, Sorry for the inconvenience  
See I was trying to build a blockchain application using brython but to connect the frontend to smart contracts we require the web3.py library or the ethers-py library
so I tried importing Web3.py but it showed to be an error  
![Screenshot 2022-10-01 1 36 11 PM](https://user-images.githubusercontent.com/104563458/193399724-70d5244a-8647-43a0-9cfe-e3437dfce6ae.png)

it says module not found

so I asked for its support 
Can you please suggest some ways to use web3 along with Brython?

_Originally posted by @Jyo561Python in https://github.com/brython-dev/brython/issues/2047#issuecomment-1264286705_

**Comment by PierreQuentel** [comment]
Thanks for the reminder.

To use a Python library, you have to install it in your CPython environment, usually with `pip install web3`, then install it in your Brython distribution with `brython-cli add_package web3`. This is documented [here](https://www.brython.info/static_doc/en/install.html).

It doesn't seem that you followed these steps. I did, but found that unfortunately this package uses CPython packages or modules that are not available in Brython (at least **`xml`** and **`asyncio`**).

The conclusion is that web3 is not usable with Brython :-(((
