### ISSUE TITLE
New int implementation: & and | operators behave as signed 32-bit integers

### ISSUE THREAD

**Issue by haael** [brython-dev/brython#207]
The behaviour of & and | operators is compatible with CPython only for numbers from range -0x80000000 to 0x7fffffff. This coincides with the binary representation of signed 32-bit integer.

When 32nd bit of the output is set, Brython yields negative numbers.

    for x in range(0x7ffffff0, 0x8000000f):
        assert x & x == x, "%s & %s == %s" % (hex(x), hex(x), hex(x & x))
        assert x | x == x, "%s | %s == %s" % (hex(x), hex(x), hex(x | x))

When trying to use integers longer than 32 bits, they get truncated to 32 bits.

    for x in range(0x17ffffff0, 0x17fffffff):
        assert x & x == x, "%s & %s == %s" % (hex(x), hex(x), hex(x & x))
        assert x | x == x, "%s | %s == %s" % (hex(x), hex(x), hex(x | x))

**Comment by earney** [comment]
A fix for this has been pushed to the repo.

**Comment by earney** [comment]
Please open another issue if you find a related problem.
