### ISSUE TITLE
Large integers act as floats

### ISSUE THREAD

**Issue by dkosbie** [brython-dev/brython#209]
```
# 1. Large integers act as floats with approximate results

print(10**16-1) # 10000000000000000 in Brython, 9999999999999999 in Python

print(10**16 == 10**16-1) # True in Brython, False in Python

# 2. Even larger integers are even stringified as floats

s = str(10**21)
print(s) # "1e+21" in Brython, "1000000000000000000000" in Python
```

**Comment by dkosbie** [comment]
Well, I just saw this:
  https://github.com/brython-dev/brython/issues/200

Sorry for the redundancy.  That said, I wonder about the Brython design decision to incorrectly implement large integers, since it appears to be a deliberate decision to be incompatible with Python.  So one could take fully-working Python code, run it in Brython, and not crash or otherwise get a hint that something went wrong, while obtaining wrong answers.

This may not seem like too big a deal to some folks, but it certainly is to others -- for example, several of the faculty members I have discussed this with (in trying to get them to consider moving from Python to Brython in our Intro CS course) say it's an outright dealbreaker for them.  Bummer.

In any case, I hope you find a way to make Brython fully Python-compatible on this issue.

**Comment by PierreQuentel** [comment]
Hi,

Thanks for the report. This topic was raised several times and as you probably saw on the Google group has made dramatic progress in the last days. The current development version now passes the tests in your report. More testing is needed, if you find things that don't work please report them here.

Can we close this issue ?

**Comment by dkosbie** [comment]
Hi Pierre.  Thanks for the quick reply, and good work!  And yes, issue closed.  :-)

David
