### ISSUE TITLE
ast.literal_eval is broken

### ISSUE THREAD

**Issue by arnakke** [brython-dev/brython#2098]
Brython 3.11.0 :

    >>> import ast
    >>> ast.literal_eval("{'a': 1.2}")
    {"'a'": <Javascript Number object: 1.2>}

Note the single quotes around `a`.

CPython 3.11.0:

    >>> import ast
    >>> ast.literal_eval("{'a': 1.2}")
    {'a': 1.2}

**Comment by PierreQuentel** [comment]
Thanks for the report @arnakke !
