### ISSUE TITLE
Suggestion: discussions in GitHub (or any other platform than Google group)

### ISSUE THREAD

**Issue by BobSquarePants** [brython-dev/brython#2099]
First of all, **big huge thank you** to all the [contributors](https://github.com/brython-dev/brython/graphs/contributors) for bringing this project to life !

##### I can't understand that the Internet Browsers are still ONLY relying on JavaScript to interact with the DOM. (but that's another discussion)

Talking about discussion, too bad Brython peoject only use a [google group](https://brython.info/groups.html) as for forum :/
As it let the peoples that [don't want to use the GAFAM ](https://degooglisons-internet.org/en/)out of the loop
Could the creators of this GitHub repository open the discussion tab/feature of Github ? (or host a [regular forum](https://flaskbb.org/) )

I'm willing to give my support for this extra channel of communication.

( Sorry to have used the this repository Issues , but I didn't had another way to reach the community :/ )

B0B

**Comment by PierreQuentel** [comment]
Thanks for the compliments and the suggestion.

If the reason for changing the forum tool is to avoid using the GAFAM, then GitHub is not a good choice because it now [belongs to Microsoft](https://news.microsoft.com/announcement/microsoft-acquires-github/), the M in GAFAM.

**Comment by BobSquarePants** [comment]
Thank you Pierre for your feedback.

Yeah I know that sadly Microsoft acquired GitHub :'(

So we might look for another solution ? FlaskBB, FluxBB ?

**Comment by PierreQuentel** [comment]
FlaskBB and FluxBB are tools to create discussion engines, not alternatives to Google Groups, ie sites where we could create a new discussion group.

I am not comfortable with the Brython Google Group, but not because it is a GAFAM product, more because it doesn't look nice, and inserting code examples is much harder than here on Github.

If you know alternatives that are more adapted to discussions about software development I am open to suggestions. I could also ask advice on the Google Group itself.

**Comment by BobSquarePants** [comment]
Thanks Pierre,
With both xxBB with can host our own server and therefore have a space of discussion like https://dev1galaxy.org based on FluxBB

Maybe you could give a try of the GiyHub discussion (it's easy to insert code, and a discussion can later on be converted as an issues, so easier to track real issues.)

**Comment by BobSquarePants** [comment]
Github discussions are available :) ( thx btw )

https://github.com/brython-dev/brython/discussions
