### ISSUE TITLE
Split Site into another repo

### ISSUE THREAD

**Issue by juancarlospaco** [brython-dev/brython#21]
- Split Site into another repo, to keep it simple and cleaner.
- The Web part has nothing to do with Brython Code itself.
- I was thinking of 1 repo for the Web, the whole web, so we can keep improving it.
- As I suggest, Move all https://github.com/brython-dev/brython/tree/master/site to https://github.com/brython-dev/web

I think we should have two repos,  one for brython source, and the site
tests, unit tests, code coverage, etc (developer stuff).

The second one should be all the other stuff under site (gallery, examples,
documentation, editor, console, etc). (user stuff).

*( Moved from Original Bug at https://github.com/PierreQuentel/brython/issues/9 )*

:octocat:

**Comment by glyph** [comment]
I actually *love* the fact that Brython's repo comes "out of the box" with documentation, an interactive console, editors, tools, etc.  It's a very good "out of the box" experience.  So I think I might be against resolving this issue :smile: .

**Comment by earney** [comment]
I am fine with the current setup.  It has it's flaws, but so do other layouts.

Should we close this issue, or is there a group of people that feel strongly FOR this issue?
