### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by BobSquarePants** [brython-dev/brython#2100]
Hi,

On https://brython.info/static_doc/en/browser.html we can read at the bottom
> browser.window
>     an object that represents the browser window 

is there somewhere more documentation about it ?
is browser.window have any functions, arguments ? where can I found out ?

Thanks.

**Comment by PierreQuentel** [comment]
Thanks for the report, I have added a link in the documentation to the [MDN page](https://developer.mozilla.org/en-US/docs/Web/API/Window) that describes the object `window`.
