### ISSUE TITLE
What is the EV in the Mouse events example page ?

### ISSUE THREAD

**Issue by BobSquarePants** [brython-dev/brython#2101]
Hi,
In the example https://www.brython.info/static_doc/en/mouse_events.html

We can read

> def mouseenter(**ev**):

But what is the EV argument ? I don't find it in the documentation

Thanks.

**Comment by PierreQuentel** [comment]
The [documentation page about events](https://www.brython.info/static_doc/en/events.html) says that the callback argument `ev` is an instance of the class `DOMEvent`, and it has a section about `DOMEvent` objects. 

Besides the information in this page, the section links to the related [MDN page](https://developer.mozilla.org/en-US/docs/Web/API/Event) for more details. 

There are so many possible attributes and methods, depending on the event type and the target element, that it is impossible to describe everything inside the Brython documentation, but the DOM API described in the MDN pages is supported.
