### ISSUE TITLE
How use the event.inputType with Brython ?

### ISSUE THREAD

**Issue by BobSquarePants** [brython-dev/brython#2102]
Hi everyone,
I'm currently learning / testing Brython.

I'm trying to get the status ( event.inputType ) like on this page 
https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_inputevent_inputType

with Bryhton

I've tried 

```
def change(event):
    document["StatusDisplay"].innerHTML = event.inputType

document["TheInput"].bind("change", change)
```
but I got:  _AttributeError: 'DOMEvent' object has no attribute 'inputType'_

the html page:
```
 	<input type="text" placeholder="Enter what ever" id="TheInput"><br>>	
	<span id="StatusDisplay">nothing yet.</span>
```

Any ideas ?

**Comment by BobSquarePants** [comment]
I've found (with luck only !)

```
def change(event):
    document["StatusDisplay"].innerHTML = event.inputType

document["TheInput"].bind("input", change)
```

I don't find the MDN page really clear, where could I found all the event trigger than I can use with .bind ? (like change, input etc..

Thanks.

**Comment by PierreQuentel** [comment]
I suggest that you invest some time getting familiar with the MDN documentation, it may look unclear at first but it's by far the most complete and up-to-date documentation about the Web API supported by Brython (and by Javascript of course).

You have a complete list of events at the end of the [page](https://developer.mozilla.org/en-US/docs/Web/Events#event_listing) referenced in the Brython documentation about events.

For instance, for all HTML elements, this page points to a [specific page](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement#events) which describes the events they support.

For a specific attribute such as `inputType`, you can also use the search engine at the top right corner of each MDN page. In 2 clicks you are at the page that explains everthing you need to know about it, with examples of use.

Unfortunately, all the examples are written in Javascript, but the translation to Brython should be straighforward. For instance, the example on this page would become (untested):

```python
from browser import document

def logInputType(event):
    log.text = f'Input type: {event.inputType}'

log = document['log']
editable = document.select_one('div[contenteditable]')
editable.bind('input', logInputType)

```

**Comment by BobSquarePants** [comment]
Thank you Pierre !
