### ISSUE TITLE
How select all the td of a specific table ? (trough ID)

### ISSUE THREAD

**Issue by BobSquarePants** [brython-dev/brython#2103]
Hi everyone,

is it possible to select all the TD tag of a table that have a ID 
```
<table id="mytable">
<tr><td>1<td></tr>
<tr><td>2<td></tr>
</table>
```

I've tried `document.select('td.#mytable').title = "test"`
but this is incorrect selector :/

any ideas ?

https://www.brython.info/static_doc/en/access.html

**Comment by BobSquarePants** [comment]
I've found !

`document.select('#tblproposal td')`

May be that example could be added in the documentation ?

https://www.brython.info/static_doc/en/access.html

**Comment by PierreQuentel** [comment]
Thanks for the suggestion @BobSquarePants !
