### ISSUE TITLE
aio fails in worker threads

### ISSUE THREAD

**Issue by cetoli** [brython-dev/brython#2104]
trying aio.Future() in a worker thread fails with the message:
File "VFS.browser.aio.py", line 2, in <module>
    from browser import window
ModuleNotFoundError: No module named 'browser.window'
Maybe because window is not defined or forbidden in worker threads.
A naive fix is removing the apparently useless import. This seems to  solve the issue.

**Comment by PierreQuentel** [comment]
Thanks for the report @cetoli !
