### ISSUE TITLE
compare int and floats

### ISSUE THREAD

**Issue by lefranco** [brython-dev/brython#2106]
Brython 3.11 : comparing (in a sort) floats and int cause an error
(this error does not happen on brython 3.9)

**Comment by PierreQuentel** [comment]
Thanks for reporting this @lefranco .

I can't reproduce the issue, this code 
```python
t = [1, 2.5, -6, 0.77]
t.sort()
print(t)
```
correctly sorts the table, on the [brython.info editor](https://www.brython.info/tests/editor.html) (release 3.11.0) and with the current development version.

Can you give an example where you get this error ?

**Comment by lefranco** [comment]
messages = [
    (0, 0, 21297, 0, 1668458546, [3], 'Salut. Je viens vers toi car tu n\'as pas participé à la discussion via "déclarer". L\'esprit de la partie est de négocier aux yeux et aux oreilles de tous, donc si tu préfères ne pas jouer dis-le moi et je trouve un remplaçant.\nKakitaievitch'),
    (0, 0, -1, 4, 1668492913.9685664, [], 'Le joueur spygame avec ce rôle a quitté la partie...'),
    (0, 0, -1, 3, 1668768064.764172, [], 'Le joueur Poungi avec ce rôle a quitté la partie...'),
    (0, 0, -1, 5, 1668768069.2738423, [], 'Le joueur gammeFabric avec ce rôle a quitté la partie...')
]

messages.sort(key=lambda m: (m[4], m[1]), reverse=True)

# this will raise 
# TypeError: unorderable types: int() >= float()
# most peculiar since comparing float and int does make sense....

**Comment by lefranco** [comment]
this will raise 
TypeError: unorderable types: int() >= float()
most peculiar since comparing float and int does make sense....

**Comment by PierreQuentel** [comment]
Tant mieux si ça t'a été utile, c'est le but !

Effectivement ton exemple plante sur brython.info avec la version 3.11.0, mais le bug a dû être corrigé depuis (je ne sais pas quand) parce que le code fonctionne normalement avec la version de développement courante. Tu peux vérifier ?

**Comment by lefranco** [comment]
Je ne peux pas vérifier. J'installe brython sur un lubuntu 2210. Je récupère la version 3.11 de brython et j'ai le problème.
Je ne sais pas installer la version de développement courante (et je ne préfère peut être pas le faire puisque je suis en quelque sorte en production.)

J'ai constaté un autre bug (que j'ai également contourné dans mon code), qui est probablement (mais pas certainement) le même...

Sur la console brython :


```
Brython 3.11.0 on Netscape 5.0 (Windows)
>>> import enum
>>> class MyEnum(enum.Enum):
...     ONE=enum.auto()
... 
>>> MyEnum.ONE
<MyEnum.ONE: <object object>>
>>> MyEnum.ONE.value
<object object>
>>> 

```

Dans un terminal Linux

```
Python 3.10.7 (main, Nov  2 2022, 18:49:29) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import enum
>>> class MyEnum(enum.Enum):
...     ONE=enum.auto()
... 
>>> MyEnum.ONE.value
1
>>> type(MyEnum.ONE.value)
<class 'int'>


```

**Comment by PierreQuentel** [comment]
Le bug que tu as signalé a été corrigé assez rapidement, mais je me suis aperçu en le traitant de ce comportement bizarre:

```python
import enum
class MyEnum(enum.Enum):
    ONE = enum.auto()
    assert ONE == 1
```

Bizarre parce que `enum.auto()` renvoie un objet qui n'est pas l'entier 1. A force de creuser dans la doc j'ai fini par me rendre compte que l'implémentation des classes était bancale depuis le début... J'ai donc tout réécrit et ce test fonctionne maintenant.

Je ferme le rapport, si tu as d'autres remarques tu peux commenter ou en ouvrir un autre.

Encore merci !
Pierre

**Comment by lefranco** [comment]
brython.js:5735 Traceback (most recent call last):
  File "[VFS.index.py](http://vfs.index.py/)", line 245, in lambda_ye3b7n5f_162
    button.bind("click", lambda e, i=possible_item_name: load_option(e, i))
                                                         ^^^^^^^^^^^^^^^^^
  File "[VFS.index.py](http://vfs.index.py/)", line 189, in load_option
    mygames.render(PANEL_MIDDLE)
            ^^^^^^^^^^^^^^^^^^^^
  File "[VFS.mygames.py](http://vfs.mygames.py/)", line 800, in render
    my_games('en cours')
  File "[VFS.mygames.py](http://vfs.mygames.py/)", line 465, in my_games
    def key_function(g): return (g[1]['nopress_game'], g[1]['nopress_current'])  # noqa: E704 # pylint: disable=multiple-statements, invalid-name
TypeError: unorderable types: bool() >= bool()
$io.flush @ brython.js:5735
brython.js:7975 Uncaught Error
    at _b_.TypeError.$factory (eval at $B.$make_exc (brython.js:7754:5), <anonymous>:185:15)
    at list.__lt__ (brython.js:12787:50)
    at brython.js:13023:121
    at cmp (brython.js:12953:29)
    at makeAscendingRun (brython.js:6022:53)
    at tim_sort (brython.js:6250:14)
    at Object.tim_sort_safe [as $TimSort] (brython.js:6262:1)
    at list.sort (brython.js:12960:4)
    at sorted (brython.js:7207:15)
    at brython.js:5726:27

**Comment by lefranco** [comment]
I am dealing with the issue by converting everything to ints before comparing.
However it would be nice to have the fix to check all is correct now.
Since I have Brython 3.11.0, that would be version 3.11.1 ?
