### ISSUE TITLE
Can we use the DOM Events Load and pageshow ?

### ISSUE THREAD

**Issue by BobSquarePants** [brython-dev/brython#2117]
example

```python
window.bind("resize", afunction)
window.bind("load", afunction)
window.bind("pageshow", afunction)
```

it seem not working for me.

**Comment by PierreQuentel** [comment]
The "resize" event does work for me with a script like
```python
from browser import window

def resize(ev):
  print('resize')

window.bind('resize', resize)
```

I don't think "load" or "pageshow" can work because the Brython scripts are executed after the HTML page is loaded, their execution is triggered by a call to function `brython()` in `<body onload="brython()">`.

**Comment by BobSquarePants** [comment]
Thank you @PierreQuentel 

Sorry I was too fast in my writing, indeed `resize` work(ed) !

Too bad for `load` and `pageshow` ... I hope we will find a workaround ? 
I pray for python to be natively supported by web browser :crossed_fingers:
