### ISSUE TITLE
Problem with ajax

### ISSUE THREAD

**Issue by rpietsch1953** [brython-dev/brython#2118]
In version 3.10.7 ajax.form_data() does not work. (I am aware that you know this)
In version 3.11.0 this problem is solved, but it now creates now an error on ajax.file_upload() in the same program. No errors with 3.10.7

[JavaMessages.txt](https://github.com/brython-dev/brython/files/10121768/JavaMessages.txt)

**Comment by PierreQuentel** [comment]
Thanks for the report @rpietsch1953. 

Can you provide an example that produces this error ? The stack is not enough for me to understand where the bug is.
