### ISSUE TITLE
External Modules not being imported?

### ISSUE THREAD

**Issue by SaiShubham624** [brython-dev/brython#2119]
I am trying to import the "pafy" module into a script but I am getting the ModuleNotFoundError. I tried several ways to fix this like putting it in the project-name/brython/Lib/site-packages, but then it says it can't found the urllib.request.build-opener saying it's not a package. As far as I am aware, urllib should be present in the standard distribution then why it isn't importing from there?

I also used the command of 'make_package' but still getting the same error, any idea?

When I try to import pafy, I get this error:

![Pafy-Import-Error](https://user-images.githubusercontent.com/71695244/205430566-6c6a495a-3b77-4300-b036-d69f93a9dc71.png)

and when I put it in the Lib/site-packages, I get this error:

![Urllib-Import-Error](https://user-images.githubusercontent.com/71695244/205430602-47126bdc-f89c-476d-ac0f-13c192fe68cc.png)

I just started using Brython, so I am not really used to it, am I doing something wrong?

Any help will be appreciated!

**Comment by PierreQuentel** [comment]
Hello,

Browsers can't send arbitrary HTTP requests for security reasons, so unfortunately this package will not be usable, neither in Brython nor in any Python-in-the-browser implementation.

**Comment by SaiShubham624** [comment]
Umm, isn't there any workaround to make it work? I mean, if there is, I think it might help.

But, thanks for the clarification! I now at least know what I was doing wrong

**Comment by PierreQuentel** [comment]
Unfortunately not, browsers can only send Ajax requests to the same domain (except if the site allows cross-domain requests, but few do).
