### ISSUE TITLE
"import copyreg" fails

### ISSUE THREAD

**Issue by glyph** [brython-dev/brython#212]
looking at current master, if I do `import copyreg` interactively, I get

```
Traceback (most recent call last):
  module __main__ line 70
    doc["add_main"].bind('click', add_main)
  module editor line 102
    traceback.print_exc(file=sys.stderr)
  module exec_143 line 1
    import copyreg
  module copyreg line 29
    _HEAPTYPE=1<<9
ValueError: argument of long_int is not a safe integer
```

Executing just `1<<9` at a prompt causes this exception as well.

**Comment by glyph** [comment]
Or, for that matter, `<<` on *any* two integers.

**Comment by PierreQuentel** [comment]
This is strange, I just cloned the current development version (commit 0b6fcff) and couldn't reproduce the bug : 

```
Brython 3.1.4 on Netscape 5.0 (Windows)
>>> import copyreg
>>> 2 << 7
256
>>> 
```

**Comment by glyph** [comment]
I was testing 3c39364.

**Comment by glyph** [comment]
OK, just tested again on ae62bfb; same behavior. The issue appears to manifest only on Safari - it works on Firefox and Chrome.  I guess I should always report browser versions whenever I have a JavaScript issue.

**Comment by PierreQuentel** [comment]
I don't have Safari, but it is probably because py_long_int.js uses the non-standard attribute `Number.MIN_SAFE_INTEGER`. I replaced it by the explicit value -(2**53-1). If this doesn't solve the problem, please reopen the issue.

**Comment by glyph** [comment]
Looks like the issue is fixed!

**Comment by glyph** [comment]
For what it's worth, `Number.MIN_SAFE_INTEGER` is `undefined` on safari; I tested version 8.0.7.
