### ISSUE TITLE
Generator `.throw(e, None)` and `.throw(e, None, None)` mishandle already-instantiated exception

### ISSUE THREAD

**Issue by mentalisttraceur** [brython-dev/brython#2123]
Using [the embedded console on the Brython webpage](https://brython.info/tests/console.html?lang=en):

```python
>>> def g(): yield
>>> 
>>> g().throw(Exception("foo"), None)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: 'Exception' object is not callable
>>> 
>>> g().throw(Exception("foo"), None, None)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: 'Exception' object is not callable
```

The expected (what CPython does) behavior is for it to just raise `Exception("foo")`, same as it would if we didn't pass the second or third argument at all:

```python
>>> g().throw(Exception("foo"))
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Exception: foo
```

The CPython logic for determining when the first argument is allowed to be an exception seems to be based on the second argument **either** being not passed in **or** `None`.

This is not a significant issue and the workaround in calling code is short and simple, but it can cause unexpected and not-obvious breakages deep inside code that otherwise works, and I presume the fix would be trivial for someone who is already familiar where and how `.throw` is implemented in Brython.

**Comment by PierreQuentel** [comment]
Thanks for the report @mentalisttraceur !
