### ISSUE TITLE
`typing` module not up-to-date

### ISSUE THREAD

**Issue by Syndace** [brython-dev/brython#2128]
Hi,

the `typing` module doesn't seem to be up-to-date. I noticed because the following fails, which should work in Python 3.11:

```Python
from typing import ForwardRef

ForwardRef("test", is_class=True)
```

**Comment by PierreQuentel** [comment]
Thanks @Syndace . **`typing`** was still in version 3.10 and upgrading to 3.11 revealed a bug.
