### ISSUE TITLE
Range in Brython Accepts Floats as Arguments, Crashes in Python 3

### ISSUE THREAD

**Issue by tstentz** [brython-dev/brython#213]
Hi guys! 

I noticed that this code:

for i in range(0, 1.2):
    print(i)

prints: 
0
1

However, the same code in Python 3 crashes. Python 3 reports that: "'float' object cannot be interpreted as an integer." 

Thanks!

Tara and Christian

**Comment by kikocorreoso** [comment]
This is an easy-fix, if someone new want to help with the Brython development this is an easy to get involved.

See here: https://github.com/brython-dev/brython/blob/master/www/src/py_builtin_functions.js#L1113

**Comment by kikocorreoso** [comment]
It seems this is already fixed in master by a previous commit :-)

**Comment by tstentz** [comment]
Great, thanks!
