### ISSUE TITLE
[`Interpreter`-only?] `__exit__` of context manager in suspended generator gets spontaneously called

### ISSUE THREAD

**Issue by mentalisttraceur** [brython-dev/brython#2130]
Using [the embedded console on the Brython webpage](https://brython.info/tests/console.html?lang=en):

```python
>>> class ContextManagerExample:
...     def __enter__(self):
...         print(f'entering! {self!r}')
...     def __exit__(self, exception_type, exception, traceback):
...         print(f'exiting! {self!r} {exception_type!r} {exception!r} {traceback!r}')
... 
>>> def g():
...     with ContextManagerExample():
...         yield 1
...         yield 2
...         yield 3
... 
>>> 
>>> i = g()
>>> next(i)
entering! <<module>.ContextManagerExample object>
1
>>> i
<generator object>
>>> exiting! <<module>.ContextManagerExample object> None None None

```

We can confirm that `__exit__` is actually running each time by adding some mutable state - in this example, I used a global integer counter that `__exit__` increments and then prints, and we can see it goes up each time I just evaluate `i`. (Note that the copy-paste is complicated by an unrelated bug: exit output line gets interpreted as if it was my input to the interpreter, and since the interpreter doesn't let me delete it I just plow through by hitting the Enter key):

```python
>>> counter = 0
>>> class ContextManagerExample:
...     def __enter__(self):
...         print(f'entering! {self!r}')
...     def __exit__(self, exception_type, exception, traceback):
...         global counter
...         counter += 1
...         print(f'exiting! {self!r} {counter!r}')>>> i = g()
>>> next(i)
entering! <<module>.ContextManagerExample object>
1
>>> i
<generator object>
>>> exiting! <<module>.ContextManagerExample object> 1

Traceback (most recent call last):
  File "<string>", line 1
    exiting! <<module>.ContextManagerExample object> 1
           ^
SyntaxError: invalid character '!' (U+0021)

>>> i
<generator object>
>>> exiting! <<module>.ContextManagerExample object> 2

Traceback (most recent call last):
  File "<string>", line 1
    exiting! <<module>.ContextManagerExample object> 2
           ^
SyntaxError: invalid character '!' (U+0021)

>>> 
```

**Comment by mentalisttraceur** [comment]
Note that the generator isn't actually *closed* in this case, it is merely `__exit__` that gets an extra premature call.

After the above examples, you can just run:

```python
>>> next(i)
2
```

**Comment by mentalisttraceur** [comment]
This bug seems to *only* happen in the REPL, so probably specific to `Interpreter`.

Running similar test code in `node_bridge.js` and in [the embedded editor on the Brython page](https://brython.info/tests/editor.html) does not reproduce it.

**Comment by PierreQuentel** [comment]
Thanks @mentalisttraceur 

I have changed the implementation of the interpreter, the issue with the missing line break was a regression.

The commit fixes it, and the main issue which is that the context manager was exited.
