### ISSUE TITLE
String encode utf-8 boundary case errors

### ISSUE THREAD

**Issue by mircea3** [brython-dev/brython#2137]
The following test cases are failing. The problem seems to be in `py_bytes.js`, where `<` should be changed to `<=`.

```
assert '\u007f'.encode('utf-8') == b'\x7f'
assert '\u07ff'.encode('utf-8') == b'\xdf\xbf'
assert '\uffff'.encode('utf-8') == b'\xef\xbf\xbf'
```

**Comment by PierreQuentel** [comment]
Thanks for the report and for finding where the bug was 👍
