### ISSUE TITLE
InfoDialog causes ValueError

### ISSUE THREAD

**Issue by lefranco** [brython-dev/brython#2139]
Code :

```
def info_dialog(mess):
    """ info_dialog """

    height_dialog = round(len(mess.split('<br>')) * 15)
    width_dialog = round(max(map(len, mess.split('<br>'))) * 5)

    top_val = max(0, window.innerHeight // 2 - height_dialog // 2)
    left_val = max(0, window.innerWidth // 2 - width_dialog // 2)

    alert(f"{top_val=}")  # 314
    alert(f"{left_val=}")  # 115

    assert(isinstance(top_val, int))
    assert(isinstance(left_val, int))

    InfoDialog("Information", mess, top=top_val, left=left_val, remove_after=config.REMOVE_AFTER)

```

Result :

  **File "VFS.browser.widgets.dialog.py", line 117, in __init__
    self.top=top
ValueError: top value should be an integer, not float**

You get this error with Edge navigator (probably some more)
Not with Firefox (otherwise I would have detected much earlier)
You do not seem to get it the first time 

At first I trusted InfoDialog to center the window on screen (as it promises)
I encountered the issue
I tried very hard to circumvent the problem by calculating the position
 I thought I had managed to get rid of it

Halas, it still occurs (after a few calls)

Help!
This is very annoying !

Initial code (when encountering the problem for the first time) :

```
def info_dialog(mess):
    """ info_dialog """

    # config.REMOVE_AFTER == 5

    InfoDialog("Information", mess,  remove_after=config.REMOVE_AFTER)

```

**Comment by lefranco** [comment]
Switching from InfoDialog to Dialog does not solve the problem.

**Comment by PierreQuentel** [comment]
This is strange. Could you provide a complete example with what you put in `mess` ? I cannot reproduce the issue.

This works correctly for me on Firefox, Chrome and Edge (I reloaded the page a couple of times)

```python
from browser import window, alert
from browser.widgets.dialog import InfoDialog

def info_dialog(mess):
    """ info_dialog """

    height_dialog = round(len(mess.split('<br>')) * 15)
    width_dialog = round(max(map(len, mess.split('<br>'))) * 5)

    top_val = max(0, window.innerHeight // 2 - height_dialog // 2)
    left_val = max(0, window.innerWidth // 2 - width_dialog // 2)

    alert(f"{top_val=}")  # 314
    alert(f"{left_val=}")  # 115

    assert(isinstance(top_val, int))
    assert(isinstance(left_val, int))

    InfoDialog("Information", mess, top=top_val, left=left_val, remove_after=3)

mess = """petit<br>essai"""

info_dialog(mess)
```

**Comment by lefranco** [comment]
Sorry, I cannot provide a minimal code that produces the issue.
However, I can explain how I managed to get around it ("contourner")
I copied the dialog.py from the github repository and included in my sources
[mydialog.zip](https://github.com/brython-dev/brython/files/10353738/mydialog.zip)
(attached)
I "corrected" (adapted it actually) and all seems to work now.

The key of everything I reckon is in :
`top += document.scrollingElement.scrollTop`
changed to :
`top += round(document.scrollingElement.scrollTop)`

I also noticed an issue with the remove_after which I did not have before, so I stopped using it by safety.
I am convinced you get a float value in scrollTop in Edge browser (but cannot prove it)

regards

**Comment by PierreQuentel** [comment]
Thanks, I have included you correction in the commit referenced above.

Which values passed to `remove_after` produces an error ?

**Comment by lefranco** [comment]
I use the mydialog.py as attached in a previous post. (mydialog.zip)
Removed the assert protection line 222
I pass 5 (5 seconds)
`     mydialog.InfoDialog("Information", mess, remove_after=5)
`
I get this error (Edge)
```
brython.js:5437 
        
       Uncaught Error
    at _b_.TypeError.$factory (eval at $B.$make_exc (brython.js:7754:5), <anonymous>:185:15)
    at $B.args (brython.js:5437:21)
    at close1532 (eval at VFSLoader.exec_module (brython.js:9455:13), <anonymous>:268:44)
    at method (brython.js:4860:12)

```

**Comment by lefranco** [comment]
Ok my fault.
Influenced by some code checker I had changed 

```
    def close(self, *args):
        self.remove()

```
to 

```
    def close(self, _):
        self.remove()
```

My mystake.
