### ISSUE TITLE
async-for crashes or misbehaves unless the iterable's __aiter__() returns self

### ISSUE THREAD

**Issue by cjlee112** [brython-dev/brython#2148]
The Python language ref states that iterating over an object obj using async-for first calls its `obj.__aiter__()` method to obtain an asynchronous iterator object `ait`, and then calls `ait.__anext__()` repeatedly until it raises `StopAsyncIteration`.  However, Brython does not do this.  Instead, Brython async-for tries to call `obj.__anext__()` repeatedly until it raises `StopAsyncIteration`.  Obviously, if `obj` has no `__anext__` method, this just crashes.  In any case, the iteration results will only be correct in cases where `obj.__aiter__()` just returns `self`, in which case `ait.__anext__` and `obj.__anext__` are the same thing!

Here is a simple test you can run in the Brython console to see this problem:

```
from browser import aio

async def agen():
    print('called the right __anext__')
    yield 2

class Foo(object):
    def __aiter__(self):
        return agen()
    async def __anext__(self):
        print('called the wrong __anext__')
        raise StopAsyncIteration

async def testme():
    async for i in Foo():
        print(i)

aio.run(testme())
```

**Comment by cjlee112** [comment]
The www/src/ast_to_js.js code for async-for seems to make exactly the mistake described above (i.e. it calls obj.__anext__() instead of ait.__anext__()).  The fix looks really simple.  I will try submitting a pull request to fix this.

**Comment by PierreQuentel** [comment]
I have merged the PR, thanks again !
