### ISSUE TITLE
Sets Operate +=

### ISSUE THREAD

**Issue by Fireheart182** [brython-dev/brython#215]
In Python 3, the += operator is undefined for Sets. However, this function is allowed in Brython.

**Comment by edwdryer** [comment]
The same holds for set addition. 
    s = set()
    b = set()
    d = s + b
This is defined in Brython but not in Python 3.

**Comment by PierreQuentel** [comment]
Thanks for the report. I took the fix proposed by Edward, but only for operator + ; operator - is actually supported by sets, it's the same as method `difference`
