### ISSUE TITLE
Question: Brython call python code

### ISSUE THREAD

**Issue by jr751** [brython-dev/brython#2152]
I was wondering, Is it possible for Brython to call some Python function or script that the web user can't see. For example, lets say you want to have a website where there would be a button that allowed the web user to upload an image. Then you have a Python script that processes the image in some way once the image has been uploaded and then displays the modified image on the website. But you don't want the web user to be able to see the Python code that does the image processing. Maybe you want to keep the image processing methods used proprietary for example. Can that be done with Brython? If so, How would that be done?

**Comment by PierreQuentel** [comment]
It is not easy to give a simple answer to such questions. 

The browser has access to the script code running on the client side, and to hide it from the end user you have to make it difficult to understand (that's called "obfuscation"). This usually means that this code is generated from the "real" code (the one you develop) by an obfuscating program.

Anyway, a determined end user will always have the possibility to find the logic of your code.

For more information you can take a look at these discussions on Stackoverflow, they apply to Javascript but the logic is the same for any client-side language

https://stackoverflow.com/questions/6869312/how-do-i-hide-javascript-code-in-a-webpage
https://stackoverflow.com/questions/32484681/how-to-secure-or-hide-my-javascript-code
https://stackoverflow.com/questions/194397/how-can-i-obfuscate-protect-javascript
