### ISSUE TITLE
Performance Issue

### ISSUE THREAD

**Issue by shark-in-a-hat** [brython-dev/brython#2153]
I know this might not be very helpful but some of the recent changes made an app of mine run significantly slower, to the point where the browser (Firefox) pops up a warning that the script is slowing the page down. 

The program is ~4k lines of (mostly bad) code and I don't think posting it here would benefit anyone, and so far I haven't been able to make a minimal test case nor to narrow down what part of it is causing the lag - if someone can tell me how to benchmark this sort of thing I could maybe make a more helpful report.   

While the script does some strange svg rendering and deals with a large dictionary, the lag appears when just clicking on a button that that should basically only pull some values from a dict and update the DOM.

**Comment by PierreQuentel** [comment]
Thanks for reporting this. It is very annoying since the objective of the recent changes of dict and set implementation was to make some of the operations much faster...

Could you find the commit that changes the speed of you application ? It might be 30555490737831e721297f1bb549bc409fb52d8e, the one with the major change in the implementation of dicts.

If you can't post the whole script, could you at least post the callback function for the click that makes the browser hang, and an idea of the structure of the dictionary (type of the keys and values, number of items) ?

**Comment by shark-in-a-hat** [comment]
I'm no longe sure if it is a Brython issue.  
I just tested 4 different version (commits from 16th, 19th, 20th and 23rd of Jan) and non of them give me a slowdown warning like before. It might have been a Firefox issue, or something unrelated that just happened to magically fixed itself at the exact same time as I changed the filenames. 
If there is a change in performance - it's not noticeable in my test case.
I'm going to close the issue and maybe ask to reopen it again in the future if/when I have a repeatable example.

**Comment by shark-in-a-hat** [comment]
I've updated Brython on my end today again and I'm afraid I have to reopen this issue. 

Adding timing debug like this:
```python
__start_time = data.performance.now()
# rest of the code
__end_time = data.performance.now()
print(f'show_details() took {__end_time-__start_time} ms to execute.')
```
I got these results using today's build:
```
show_details() took 2196 ms to execute.
show_details() took 2431 ms to execute.
write_node() took 12271 ms to execute.
```
and these results with a old build:
```
show_details() took 123 ms to execute.
show_details() took 119 ms to execute.
write_node() took 1507 ms to execute.
```
It's an order of magnitude slower. 


After making a minimal example just using the same data I have in my real program I got this:
```python
t0 = data.performance.now()
x=0
global plot
for name, node in plot.items():
    x+=1
t1 = data.performance.now()
print(f'took {t1-t0} ms to execute.') 
```
with the new version: `took 2107 ms to execute.`
with the old version:  `took 79 ms to execute.`

My 'plot' dictionary is constructed from a javascript object that lives in a separate file - that file is currently 2 794KB in size, big but not Big Data big, 15 628 keys.
```html
<script type="text/javascript" src="../data/plot.txt"></script>
```

```python
global plot
plot = dict(window.plot)
```
This conversion is done once just so that I can use plot.items() later. The global is use because... well, I don't know... to annoy Python programmers, I guess? 

The structure of the dictionary/javascript object looks like this:
```javascript
var plot = {
    "pre_new_game" : {
        "txt" : "The game uses an auto-save system, starting a new game will {RED('ERASE ALL AUTO-SAVES')} (but not manual savefiles)! Do You want to start a new game? ",
        "no_save" : 1,
        "choice" : [["True", "Start New Game", "new_game"], ["True", "Cancel", "back_to_main"]],
        "cmd" : ["music('like_the_synth')", "parallax_imgs(('img/parallax/class_l0.webp', 'img/parallax/class_l1.webp', 'img/parallax/class_l2.webp'))"]
    },
    "new_game" : {
        "txt" : "Would You like to see a short tutorial going over the basics of the User Interface? ",
        "img" : "img/title/title_free.webp",
        "choice" : [["True", "Show Tutorial", "tutorial_1"], ["True", "Skip", "prologue_jump"]],
        "cmd" : ["init_new_save()"]
    }
}; 
```
It's a dictionary with string keys and dictionaries for values. The sub-dictionaries have again string only keys and the values are either strings (usually 100-500 letters long), occasional ints and also list of strings and list of list of strings (as show on the example above).  

I'm attaching a modified copy of this troublesome dict in a zip file - it should have a structure identical to what I use, but all text has been replaced with a  placeholder string for legal reasons.

[plot_placeholder.zip](https://github.com/brython-dev/brython/files/10696252/plot_placeholder.zip)

Hope this helps figuring out what's wrong.

**Comment by PierreQuentel** [comment]
Thanks for reopening the issue and for the detailed explanation and sample code / data, it was very helpful.

I have changed the implementation of iteration on dict views and the speed seems to be the same as in version 3.10.7. Can you check ?

**Comment by shark-in-a-hat** [comment]
Yes, that definitely helped. 
The test that run previously at 2000-2100ms and  60-79ms now runs at 25-30ms, so it's not only as fast as it was, it is now even faster. 
Good job!
