### ISSUE TITLE
Thread.is_alive() always True without first calling joint()

### ISSUE THREAD

**Issue by longnetwork** [brython-dev/brython#2163]
```python
from threading import Thread

def job():
    print('executed')

t = Thread(target=job, daemon=True)
t.start()
# t.join(0)
# ... big work
t.is_alive();  # always True if join() is commented out
```

**Comment by PierreQuentel** [comment]
I'm afraid I can't do much for this bug. The **`threading`** module is present only to avoid import errors in the stdlib modules that import it, but it doesn't do anything useful in the browser environment, which is mono thread. The equivalent is using [Web Workers](https://www.brython.info/static_doc/en/browser.worker.html).

Unless someone volunteers to fix this bug in the next days I will have to close it as "won't fix", sorry.
