### ISSUE TITLE
Catch errors

### ISSUE THREAD

**Issue by webdevelopland** [brython-dev/brython#2164]
How to catch all errors from python code?  
Example:
```html
<html>
<head>
<meta charset="utf-8">
<script src="https://cdn.jsdelivr.net/npm/brython@3.11.1/brython.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/brython@3.11.1/brython_stdlib.js"></script>
</head>
<body onload="brython()">
<script type="text/python">
  def
</script>
</body>
</html>
```

There's an obvious syntax error in the python code, but I can't catch it with js.  
try-catch doesn't work. window.onerror also doesn't work.  
Is there some brython event to do that maybe?

**Comment by PierreQuentel** [comment]
Why do you want to catch an exception _with js_ ? When you load the HTML page you have the Python exception in the browser console.

**Comment by webdevelopland** [comment]
I'm working on online python compiler. I want to display the error inside UI.

**Comment by PierreQuentel** [comment]
You can write the compiler with Brython. You will be able to catch the error with

```python
try:
    exec(source)
except Exception as exc:
    print(exc)
```

or use the **`traceback`** module, it is in Brython standard distribution.

**Comment by webdevelopland** [comment]
This is an interesting approach! I have the `source` code as js variable, I assume that would be the way to run it:
```javascript
const py = `
source = """
${source}
"""
try:
    exec(source)
except Exception as exc:
    print(exc)
`;

this.script = document.createElement('script');
this.script.type = 'text/python';
this.script.text = py;
document.head.append(this.script);
brython();
```

**Comment by webdevelopland** [comment]
> or use the traceback module

Sorry, I'm new to python and Brython. How can I run the traceback module?

**Comment by PierreQuentel** [comment]
As for all the Python standard library modules, it is documented online: [https://docs.python.org/3/library/traceback.html](https://docs.python.org/3/library/traceback.html)

**Comment by PierreQuentel** [comment]
> This is an interesting approach! I have the source code as js variable, I assume that would be the way to run it:

You don't have to write anything in Javascript (this is what Brython is about). For an example, you can take a look at the code of the [online editor](https://www.brython.info/tests/index.html), it's 100% Python code.

**Comment by webdevelopland** [comment]
Unfortunately, I'm stuck with js here. The compiler is part of bigger app, which is full js. Also I'm much more experienced with js, then with python.  
Yet, the [online editor](https://www.brython.info/tests/index.html) is a great example of what I'm working on. I'll learn it.

**Comment by webdevelopland** [comment]
Thank you @PierreQuentel for all your help, especially for a quick answer. I appreciate it!
