### ISSUE TITLE
Handling of math.log() error cases

### ISSUE THREAD

**Issue by pm3512** [brython-dev/brython#2168]
I believe there are some minor differences between how Brython and Python handle invalid arguments for `math.log()` and related functions.
1. Calling `math.log2()` on a negative number returns a `ValueError` without a message (in Python, the message is `math domain error`)
2. Calling `math.log()` with a negative base returns `nan` (should raise `ValueError: math domain error`)
3. Calling `math.log()` with base 0 returns `-0.0` (should raise the same exception)
4. Calling `math.log()` with base 1 returns `inf` (should raise `ZeroDivisionError: float division by zero`)

Thank you in advance for fixing!

**Comment by PierreQuentel** [comment]
Thanks for the bug report @pm3512 !
