### ISSUE TITLE
Exception: <Javascript TypeError>: js_attr.toString is not a function

### ISSUE THREAD

**Issue by benjie-git** [brython-dev/brython#2194]
Ever since the following commit, brython crashes for me in my rather large project.
https://github.com/brython-dev/brython/commit/7c8da9487a491397987ac42d576090a086b4601c

I unfortunately have not been able to build a minimal test case to trigger the error.

The issue seems to happen on this line:
https://github.com/brython-dev/brython/commit/7c8da9487a491397987ac42d576090a086b4601c#diff-766a8e6709ecee5361c7b50b15c4290cab5e2d386ef1512be99eda2ad5521753R572

I get the error: Exception: <Javascript TypeError>: js_attr.toString is not a function

It looks like when testing whether js_attr is a class, we perform a slightly unsafe .toString() method call on a value that may not support toString().  Or maybe the object has a toString attribute that is not a function??

The offending line is:
   if(js_attr.toString().startsWith('class ')){

if I change it to:
    if(js_attr && js_attr.toString && typeof js_attr.toString === 'function' && js_attr.toString().startsWith('class ')){

it fixes my problem.  But this is probably an inelegant solution, and might be masking a deeper problem.

**Comment by PierreQuentel** [comment]
Thanks for the report Ben !

Did you test the latest development versions ? In a later commit (980019d218ad875cfe0e86349898e2722a72d42c) I have modified the line to
```javascript
if(js_attr !== null && js_attr.toString().startsWith('class ')){
```
I don't remember the exact use case that made me change this line but it's probably similar to yours.

Does this fix your issue ? If not, what is the value of `js_attr` ?

**Comment by benjie-git** [comment]
Thanks!  I did try out the latest (I binary searched revisions between current as of yesterday, and the last release), and unfortunately that null check fix did not fix my problem.  My fix patched onto https://github.com/brython-dev/brython/commit/7c8da9487a491397987ac42d576090a086b4601c works for me, but when I add the same fix to the current development version, I'm still having other, possibly related problems, which I haven't had time to dig into yet.  I'll try to add info about that later today.  Thanks as always for your responsiveness!

**Comment by benjie-git** [comment]
Update: The other issue is an unrelated regex problem, and I just opened another issue on that.  

This issue seems to be that when js_attr contains one of my own python objects, it does not define toString().  I updated my fixed line to:

```javascript
    if(js_attr !== null && js_attr.toString !== undefined && js_attr.toString().startsWith('class ')){
```

which is a bit slimmed down, and still works.  But maybe you'd rather add toString() to python objects?

**Comment by PierreQuentel** [comment]
In the commit referenced above I have added yet another test:

```javascript
    if(js_attr !== null &&
            js_attr.toString && 
            typeof js_attr.toString == 'function' &&
            js_attr.toString().startsWith('class ')){
```

I am just wondering how a Python object can become the attribute of a Javascript  object. Can you explain the structure of your program ? Is there a communication between a Brython program and Javascript code ?

**Comment by benjie-git** [comment]
Yes!  I'm doing a lot of interaction between python code and js libraries.  I'm also storing a python object (the one that was causing the crash) into a window attribute, as a way to make it globally accessible.  Maybe that was the cause?

**Comment by PierreQuentel** [comment]
In the commit referenced above I have changed (and hopefully improved ;-) the interaction between Python and Javascript. It should limit the cases when the issue you found happens.

**Comment by PierreQuentel** [comment]
I am closing the issue, although I am aware that there is room for improvement in the interaction between Python and Javascript.
