### ISSUE TITLE
multiple assignment bug

### ISSUE THREAD

**Issue by benjie-git** [brython-dev/brython#2198]
In python, the following are all valid:
```python
a = 1
a = 1, 2
a, b = 1, 2
a, b = 1+1, 2+2
a = 1+1, 2+2
```

but the last example fails in brython.

**Comment by benjie-git** [comment]
There is still a related case that is failing.  Any multiple assignment where the initial element begins with a negative sign, like:

```python
x=1,1   # works
x=-1,1  # fails
```

Fails with:
SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='?

**Comment by PierreQuentel** [comment]
Thanks, I have fixed this bug too. I leave the issue open in case you find other similar bugs.

**Comment by benjie-git** [comment]
Thank you!  With these fixes, brython is now successfully running code that has been processed by python-minifier.  It seems to slightly improve the speed of initial load of my code, and the 2nd load, for some reason, and then 3rd+ are about the same as un-minified code, which is what I would expect once the transpiled code is cached.
