### ISSUE TITLE
Problem when using keys with the ' character in dict 

### ISSUE THREAD

**Issue by jibalamy** [brython-dev/brython#2200]
Hello,

I encounter problem when using keys with the ' character in dict.

Here is an example (tested today in the Bython console online):

>>> d = {"Corriger les erreurs d'extraction" : 1}
>>> d[list(d.keys())[0]]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: Corriger les erreurs d'extraction

Notice that the problem disappear if the ' character is removed.

Thank you for providing Brython!
Jiba

**Comment by PierreQuentel** [comment]
Thanks for the report @jibalamy !

The problem was not visible in the latest development version because of a change in the implementation of dictionary, but the initial cause of the bug was still there. The commit referenced above fixes it.
