### ISSUE TITLE
`unbind` missing from object created with `new()`

### ISSUE THREAD

**Issue by goffi-contrib** [brython-dev/brython#2201]
Hello,

I'm currently using the WebRTC API with Brython, and for that I create a `RTCPeerConnection` with something like this:
```python
from browser import window


pc = window.RTCPeerConnection.new()
```

Then, instead of using JavaScript's `addEventListener`, I'm using Bryhon's `bind` as explained at https://www.brython.info/static_doc/fr/events.html . It works as expected, and then my event callbacks are called.

However when the call is finished and I'm cleaning the instance, I want to use the `unbind` method with something like `pc.unbind("track", "self.on_track")`, but it doesn't exist, here is the message in the console:
```
AttributeError: 'Javascript Map' object has no attribute 'unbind'
```

If I use JavaScript's `removeEventListener`, it works though.

This can be tested directly on https://www.brython.info/tests/console.html with Brython 3.11.2:
```python
Brython 3.11.2 on Netscape 5.0 (X11)

Type "help", "copyright", "credits" or "license" for more information.

>>> from browser import window


>>> pc = window.RTCPeerConnection.new()


>>> pc.bind


<function >

>>> pc.unbind


Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Javascript Map' object has no attribute 'unbind'
```

The expected result when entering `pc.unbind` would be `<function >` as for `bind`

**Comment by PierreQuentel** [comment]
Merci Jérôme,

In the commit referenced above I have added the method `unbind(event[, func])` to remove the binding set by `bind(event, func)`, or all the bindings for the event if `func` is not specified. Additionaly, the method `bindings()` of JS objects returns a dictionary with all the bindings set for the object.

I tested it on a `XMLHTTPRequest` object, it seems to work. Can you test with your example ?

**Comment by PierreQuentel** [comment]
I am closing the issue, feel free to comment again if something is still wrong.

**Comment by goffi-contrib** [comment]
@PierreQuentel sorry I forgot about this and didn't test. I'll reopen if something is wrong, but it should be fine. Thanks!
