### ISSUE TITLE
Python http.client with socket for android apps

### ISSUE THREAD

**Issue by nacho00112** [brython-dev/brython#2205]
I know that brython can't use socket due to browser limitations, but what about
brython android? i don't know very much about this theme,
but it seems that in android the brython apps are wrapped
with a java code that opens the brython app with the help of the android webview library,
Brython can't use socket but of course java can, Could this open a possibility for us in brython android apps?
Like java serving as a intermediary for doing http requests?
Could the webview allow that?
Please clarify me

**Comment by moepnse** [comment]
Besides Brython, there are several other ways to use Python on Android:
https://wiki.python.org/moin/Android

If you still want to use Brython, then you could use Cordova:
https://cordova.apache.org/
https://tecnobillo.com/sections/python-en-android/cordova-brython/cordova-brython.html – you may need google translate. 🙃 
https://github.com/blocshop/sockets-for-cordova

I haven't used Cordova yet, so I can't offer you any further help at this time.

**Comment by nacho00112** [comment]
> Besides Brython, there are several other ways to use Python on Android: https://wiki.python.org/moin/Android
> 
> If you still want to use Brython, then you could use Cordova: https://cordova.apache.org/ https://tecnobillo.com/sections/python-en-android/cordova-brython/cordova-brython.html – you may need google translate. 🙃 https://github.com/blocshop/sockets-for-cordova
> 
> I haven't used Cordova yet, so I can't offer you any further help at this time.

Don't worry my native language is spanish, i readed the tecnobillo page and seems good but i have a problem i'm working in the termux android app a linux emulator, it does not have the sdk nor ndk only some sdk essentials and thanks to that and some scripts i can build brython apps as shown in the tutorial, but cordova downloads both the sdk and ndk i already tried but i couldn't because that, so my only option is to use the way shown in the tutorial

**Comment by nacho00112** [comment]
May be i should investigate about the webview library and see if there's a possibility to allow internet usage

**Comment by nacho00112** [comment]
> https://developer.android.com/develop/ui/views/layout/webapps/webview
> 
> > To bind a new interface between your JavaScript and Android code, call [addJavascriptInterface()](https://developer.android.com/reference/android/webkit/WebView#addJavascriptInterface(java.lang.Object,%20java.lang.String)), passing it a class instance to bind to your JavaScript and an interface name that your JavaScript can call to access the class.
> 
> That's what i talking about, we can't use this?

If we implement _socket.py and _ssl.py with the help of this we could get working even the `requests` library, isn't so

**Comment by nacho00112** [comment]
But using higher level java interfaces instead and create our own `requests` based on them seems to be a best option
