### ISSUE TITLE
I would like to use promises to work with web workers.

### ISSUE THREAD

**Issue by moepnse** [brython-dev/brython#2208]
Hello,

while googling about web workers I found the following resource: https://brython.info/static_doc/en/webworker.html
But sadly it seems abandoned. But why?

I would like to use promises to work with web workers. Can we bring it back?
Here is a small sample:
```python
w = ww.create_worker('ui/web_workers/formatter.py')

async def ww_format(string, **context):
    msg = w.Message("format","string", context)
    formatted_str = await w.post_message(msg, want_reply=True)
    return formatted_str
```

Thanks!

**Comment by moepnse** [comment]
Or an interface like:
```python
w = ww.create_worker('ui/web_workers/formatter.py')
formatted_string = await w.format('<ui-page name="oid_%oid%_machine'></ui-page>, {"oid": "0x0551"})
```

**Comment by PierreQuentel** [comment]
You can use the generic function `aio.event()` in code like:
```xml
<script class="webworker" type="text/python" id="ww_formatter">
# Worker script
from browser import bind, self

def lower(msg):
    return msg.lower()
    
@bind(self, 'message')
def message(ev):
    func, data = ev.data
    self.send(globals()[func](data))
</script>

<script type="text/python">
# Main script
from browser import aio, worker, document

async def lower(worker):
    worker.send(('lower', document['text'].value))
    ev = await aio.event(worker, 'message')
    document['lowered'].value = ev.data

def ready(w):
    document['btn'].bind('click', lambda ev, w=w: aio.run(lower(w)))

worker.create_worker('ww_formatter', ready)
</script>

<input id="text"><button id="btn">lower</button>
 <input id="lowered">
```

Note that in this example the communication between main script and worker script uses a specific protocol:
- main script sends a 2-element tuple (function_name, argument)
- worker script executes the function with the argument and sends back the result

There is no default protocol in the current version of **`browser.worker`**, I think it's better to let users define one if they need it
