### ISSUE TITLE
hasattr broken for js objects and __len__

### ISSUE THREAD

**Issue by ed2050** [brython-dev/brython#2219]
hasattr is broken for js objects.  hasattr __len__ always returns true :
```
import browser
hasattr (browser.console, '__len__')
True
>>> len (browser.console)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Javascript Object' object has no attribute '__len__'
```

Why it matters: I have a function that receives arbitrary messages that can contain js or brython objects.  If it's an object with a length (string, list, dict, etc) then I log it.  Can't do that when jsobjects always report true.

Not urgent.  I worked around by checking `isinstance (javascript.JSObject) and hasattr (__len___)`.

Happens in both brython 3.8.9 and latest 3.11.2

**Comment by PierreQuentel** [comment]
Hi Edward,

In a series of recent commits I have modified the implementation of Javascript objects. It has many impacts, including on the topics you mention in discussion #2226 (I don't forget it !). 

One of the consequences is that now `__len__` should only be available for JS objects whose prototype has `length`.

**Comment by PierreQuentel** [comment]
I am closing the issue, if you think it should remain open please comment again.
Thanks !
