### ISSUE TITLE
brython_stdlib.js seems to be broken

### ISSUE THREAD

**Issue by moepnse** [brython-dev/brython#2224]
Hello!

The space between return and f-strings is missing in several lines.
```python
  File "VFS.collections/__init__.py", line 733
    returnf'{self.__class__.__name__}()'
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
```

Thanks for your time!

**Comment by PierreQuentel** [comment]
Thanks @moepnse , should be ok with the latest commit. It was a side effect of working on Python 3.12 where there is a new implementation of f-strings.
