### ISSUE TITLE
Can't call Array.from in brython

### ISSUE THREAD

**Issue by ed2050** [brython-dev/brython#2225]
Can't call window.Array.from in brython console.  Raises invalid syntax error.  Probably an issue with the token parser thinking from is a reserved word?

If you get Array.from indirectly with getattr, then calling it works just fine.  See example below from latest console.

I can confirm same thing happens in brython 3.8.9.  Script won't even parse, despite window.Array.from not being called til later.

### Console
```
>>> l = [2,3,4,3,53,5,35,345,345]
>>> m = win.Array.from (l)
  File "<stdin>", line 1
    m = win.Array.from (l)
                  ^^^
SyntaxError: invalid syntax
>>> m = getattr (win.Array, 'from') (l)
>>> m
[2, 3, 4, 3, 53, 5, 35, 345, 345]
```

**Comment by PierreQuentel** [comment]
Brython is as compliant as possible with the Python language specification, and for the moment keywords such as `from` cannot be used as attributes, function or method names, etc.

Guido himself suggested to remove this constraint when the new PEG parser was introduced, but it was not supported by the steering counsil.

So unfortunately there is no other solution than to use `gettattr(obj, 'from')`. It is the same with the indexedDB API where an object has a method `continue`.

**Comment by ed2050** [comment]
Thanks for explaining.  That's a good reason.  Hard to argue with that.

One difference though - the python steering council doesn't have to worry about interfacing with javascript.  Perhaps a bit more flexibility might help in this environment?

I fully support 100% compliance with not allowing free-standing variables named after keywords.  This restriction satisfies the intent of the Python rule.

To me, it's a different situation when an object is inherited that already has a member named for a keyword.  `object.from` could be allowed while `from` by itself is and should be banned.  That would satisfy the python rule while recognizing the compromises inherent in running atop another language.

I see the value both in following python where appropriate, and in deviating when necessary. 
 Whatever you choose is fine.

For the PSC, it seems silly of them to forbid things in one context that are doable in another, when there's no risk of confusion.  `object.from` is forbidden but `setattr (object, 'from', {})` is perfectly fine.  Now they've broken access symmetry: `object.foo` and `getattr (object, 'foo')` no longer mean the same thing.  Why?  Just so object.from isn't mistaken for a from statement, which could never happen?  Is that a better result?  Apparently PSC thinks so.

**Comment by PierreQuentel** [comment]
I couldn't find the discussion about this proposal, I only found [this post](https://mail.python.org/archives/list/python-committers@python.org/thread/SQC2FTLFV5A7DV7RCEAR2I2IKJKGK7W3/) where Guido suggests to start a thread about "contextual keywords", but there is no such thread in the list.

So maybe it's not a formal decision of the SC rejecting a PEP, and I don't remember the exact reasons why the discussion ended with a general disagreement on the proposal, but the fact is that in the current version of the Python language, and for the foreseeable future, `object.from` raises a `SyntaxError`, whereas `getattr(object, 'from')` is ok.

This reminds of a bug report (#805) in 2018 when someone told me (to my surprise) that a decorator syntax that was valid in Brython
```python
 @document['test'].bind('click')
```
was not valid in the Python language. I had to adapt Brython to be Python-compliant, but a few years later a [PEP](https://peps.python.org/pep-0614/) was approved that made the syntax valid.

Hopefully it will also be the case for keyword reuse some time...

**Comment by ed2050** [comment]
@PierreQuentel thanks I missed that discussion from 2018!  I like the solution you found there.  Might use it in some future scripts.  I usually do `doc ['element'].bind (func)` to keep related events together, but decorator syntax is handy too.

You can close this issue now.  Thanks.
