### ISSUE TITLE
Can't check if a `null` javascript object `is None`

### ISSUE THREAD

**Issue by goffi-contrib** [brython-dev/brython#2227]
Checking if a javascript object is None results in a javascript Exception.

## Steps to reproduce

- Go to Brython online console (checked with https://www.brython.info/tests/console.html, `Brython 3.11.2 on Netscape 5.0 (X11)` on Firefox `116.0.3` on Archi Linux).
- enter the following instructions:
```
>>> from browser import window
>>> peer_connection = window.RTCPeerConnection.new()
>>> peer_connection.remoteDescription is None
```

## Expected Result

As `remoteDescription` is `null` at this point, the console should print `>>> True`

## Actual Result

There is a Javascript exception with this on the Brython console:
```
Traceback (most recent call last):
Exception: <Javascript TypeError>: a is null

>>> 
```

And this on the browser console:
```
Javascript error
 TypeError: a is null
    $is https://www.brython.info/src/py_utils.js:1087
    anonymous https://www.brython.info/src/py_builtin_functions.js line 779 > Function:4
    eval https://www.brython.info/src/py_builtin_functions.js:791
    call1 https://www.brython.info/src/py_utils.js:1196
    handle_line278 https://www.brython.info/src/py_import.js line 226 > Function:1973
    method https://www.brython.info/src/py_object.js:309
    keypress243 https://www.brython.info/src/py_import.js line 226 > Function:1680
    method https://www.brython.info/src/py_object.js:309
    callback https://www.brython.info/src/py_dom.js:1121
py_exceptions.js:414:17
$B.$is@https://www.brython.info/src/py_utils.js:1087:8
anonymous@https://www.brython.info/src/py_builtin_functions.js line 779 > Function:4:11
_b_.eval@https://www.brython.info/src/py_builtin_functions.js:791:28
$B.$call1/<@https://www.brython.info/src/py_utils.js:1196:31
handle_line278@https://www.brython.info/src/py_import.js line 226 > Function:1973:45
method@https://www.brython.info/src/py_object.js:309:40
keypress243@https://www.brython.info/src/py_import.js line 226 > Function:1680:119
method@https://www.brython.info/src/py_object.js:309:40
DOMNode.bind/callback@https://www.brython.info/src/py_dom.js:1121:24
py_exceptions.js:415:17
frames 
Array [ (5) […], (5) […] ]
py_exceptions.js:416:17
```

**Comment by PierreQuentel** [comment]
The commit reference above fixed the bug, but the test should be `is javacript.NULL` instead of `is None`

**Comment by goffi-contrib** [comment]
@PierreQuentel thanks for the quick fix (as usual :) ). I thought that Javascript `null` was automatically converted to `None` by Brython. In which case should I use `javascript.NULL` then?

**Comment by goffi-contrib** [comment]
Oh I see that you have updated the doc. So I guess when it's a pure JS object like here, I have to use `Javascript.NULL`.

**Comment by PierreQuentel** [comment]
Yes that's it, and I have also documented that if the Javascript value is `undefined` it should be tested against `javascript.UNDEFINED`. Thanks for the bug report once again Jérôme !
