### ISSUE TITLE
`int(0.0000005)` returns 5 instead of 0

### ISSUE THREAD

**Issue by lsands50** [brython-dev/brython#2228]
In Brython, `int(0.0000005)` returns 5 instead of 0. With any fewer 0's, eg. `int(0.000005)`, the function returns 0 as expected. Other numbers close to 0 also cause problems. For example, `int(0.0000001)` returns 1, `int(0.0000002)` returns 2, etc.

Thanks for taking a look!

**Comment by PierreQuentel** [comment]
Thanks for the report @lsands50 !
