### ISSUE TITLE
Code working on python3 but not under Brython

### ISSUE THREAD

**Issue by thetopic** [brython-dev/brython#223]
The code below works on python3 but not under Brython

```python
class Test:

    @property
    def clicked(self):
        return self.func

    @clicked.setter
    def clicked(self, callback):
        self.func = callback

t = Test()
t.clicked = lambda: print("clicked")
t.clicked()
```

**Error**

Internal Javascript error: TypeError: func.apply is not a function
  module 'exec_143' line 14
t.clicked()

**Comment by PierreQuentel** [comment]
This was fixed in revision 71283c4de19d0fc5335746b2b44c59e57aeab95e
