### ISSUE TITLE
DOMStringMap should returns "None" instead of raising "AttributeError" when key does not exist

### ISSUE THREAD

**Issue by denis-migdal** [brython-dev/brython#2245]
Hi,

An HTML element can have `data-*` attributes that can be accessed either through `self.dataset.*` or `self.getAttribute('data-*')`.

If `data-color` does not exist :

```python
self.getAttribute('data-color') # returns None (OK)
```
```python
getattr(self.dataset, 'color', None) # returns None (OK)
```
```python
if "color" in self.dataset: # is always False even if data-color exists.
```
```python
self.dataset.color # raise AttributeError (NOK), cf below
```
```python
self.dataset.toto = "tutu" # works
```

```
Traceback (most recent call last):
  File "http://localhost:3000/Examples/TP3.html#__main__", line 3, in <module>
    defineCustomElements('my-div', '/components/Examples/TP3/')
  File "http://localhost:3000/components/components.py", line 164, in defineCustomElements
    aio.run(internalDefineCustomElements(tagname, path, tagtype) )
  File "http://localhost:3000/components/components.py", line 156, in internalDefineCustomElements
    webcomponent.define(tagname, WebComponentClass)
  File "http://localhost:3000/components/components.py", line 93, in __init__
    self.init()
  File "/components/Examples/TP3//index.py", line 13, in init
    self.dataset.color
         ^^^^^^^^^^^^^
AttributeError: 'Javascript DOMStringMap' object has no attribute 'color' brython.js:14596:56
```

Cordially

**Comment by PierreQuentel** [comment]
Hello,

The commit referenced above fixes 2 issues related to this report, but I don't agree that `self.dataset.color` should return `None` instead of raising `AttributeError` : in Python, when an attribute doesn't exist, this exception is raised.

This is different from the DOM API where, as you observed, `element.getAttribute('color')` is `None`.

**Comment by PierreQuentel** [comment]
Sorry, I also disagree : it's only if the behaviour was different from what a Python developer expects that it would require documentation.

Searching a key in a dictionary or an attribute in an object has nothing exceptional in Python, nevertheless `dict[key]` raises a `KeyError` if the key is absent and `getattr(obj, attr)` raises `AttributeError`.

**Comment by denis-migdal** [comment]
I still think it might be confusing for some devs, e.g. ones that comes from WebDev, trying to use Brython.

However, I'm closing this issue as it is now solved.
