### ISSUE TITLE
window.Date == window.Date returns False [Potential HUGE performances increase]

### ISSUE THREAD

**Issue by denis-migdal** [brython-dev/brython#2249]
Hi,

I noticed that :
```python
print('Date=Date', window.Date == window.Date )
```
Is giving :
```
Date=Date False
```

I do not exactly understand how Brython is doing, but I think it creates a new wrapper each time an attribute is asked :
https://github.com/brython-dev/brython/blob/master/www/src/js_objects.js

If it is the case, and if this isn't already done, I think that using a **Proxy** might helps a lot to prevent issues and increase Brython performances while reducing memory usage :
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy

To prevent 2 proxies being unequal while pointing to the same target, maybe redefined '==' to compare the target ?

Also, to prevent re-building a proxy each time it is needed, a **Symbol** could be added to the target object pointing to a proxy ?
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol

Then, if a proxy exists, returns it, else build a new one.

Also, I think this might be related to #2248

Cordially,

**Comment by denis-migdal** [comment]
I succeeded to reproduce this :
```javascript
class X {}

class Z {
	constructor() {
	    this.x = X
	}

	get me() {
		return this.x
	}
}

let z = new Z();
window.x = z
```
```python
print(window.Date == window.Date)
print(window.x == window.x)
print(window.x == window.x.me)
print(window.x.me == window.x.me)
```
Gives :
```
False
True
False
False
```

**Comment by denis-migdal** [comment]
This is also dangerous is JS modify an object when used in python :
```javascript
class X {
	get time() {
		return Date.now()
	}
}

class Z {
	constructor() {

		this.x = new X();
	}

	
}

let z = new Z();
window.x = z

setTimeout(() => { z.x.toto = 43 }, 5000)
```
```python
x = window.x
x2 = window.x.x

def printt():
	print("x" in x)
	print("toto" in x.x)
	print("toto" in x)

setTimeout(printt, 7000)
```
Produces :
```
True
True
False
```

**Comment by denis-migdal** [comment]
I tried to trick Brython by modifying an object in JS, while using it with Python. I expected the python object to not have something that I modified/added.

It seems clear that a wrapper is created each time an attribute is accessed. But it seems this wrapper's attributes are updated... is a Proxy already used internally and I didn't saw it ? Or do you use something else to update the wrapper ?

**Comment by denis-migdal** [comment]
**_Note :_** if you do not want to modify the target object by adding a Symbol, [WeakMap](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap) and [WeakRef](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakRef) can also be used (an object used as a key can be garbage collected, then the entry will be removed).

In proxy, you can also a [proxy get trap](https://stackoverflow.com/questions/51096547/how-to-get-the-target-of-a-javascript-proxy).

So maybe using 2 WeakMap :
- getProxy (key = target, value = proxy) : proxy will be kept alive as long as target is alive ?
- getTarget (key = proxy, value = WeakRef<target>) : to avoid memory leak ?

cf also https://developer.mozilla.org/en-US/docs/Web/JavaScript/Memory_management


[FinalizationRegistry](FinalizationRegistry) can also be used to call function when a value is liberated.
Could be used to debug and test the presence of memory leak when testing the life cycle of the Proxy and its target ?

**Comment by denis-migdal** [comment]
Thanks, I confirm that now `window.Date == window.Date`.


Could you confirm whether a new wrapper is created at each access to the same object (this could be very important performances wise) ?

**Comment by PierreQuentel** [comment]
Salut Denis ;-)

In the commit referenced above, I have modified method `__eq__` of JSObj instances so that `window.Date == window.Date` is true. It also gives the same results as Javascript for your other examples:

```python
from browser import window

print(1, window.Date == window.Date) # True
print(2, window.x == window.x) # True
print(3, window.x == window.x.me) # False
print(4, window.x.me == window.x.me) # True
```

```javascript
class X {}

class Z {
	constructor() {
	    this.x = new X()
	}

	get me() {
		return this.x
	}
}

let z = new Z();
window.x = z

console.log(window.Date === window.Date) // true
console.log(window.x == window.x) // true
console.log(window.x === window.x.me) // false
console.log(window.x.me === window.x.me) // true
```

Management of Javascript data in Brython is a difficult topic... Using a proxy might be a good solution for some use cases but a blocking point for others, and a proxy around an object always slows down execution compared to using the object itself.

**Comment by denis-migdal** [comment]
Hi, thanks for you answer.

> Could you confirm whether a new wrapper is created at each access to the same object (this could be very important performances wise) ?
Seems the answer is yes, which cause the following bug :

```python
x = {}
m = window.Map.new()
m.set(x, 42)

print( m.get(x) )
```
Gives `<Javascript undefined>`

Stangely enough
```javascript
class X {}

x = new X();

map = new Map();

map.set(x, 42)

window.map = map
window.x = x
```
```python
x = window.x
print( window.map.get(x) )
```

Is correct.


> Management of Javascript data in Brython is a difficult topic... Using a proxy might be a good solution for some use cases but a blocking point for others, and a proxy around an object always slows down execution compared to using the object itself.

I understand. Strangely enough data seem correctly synchronized so as long as it works ;)
But I think you should use `WeakMap` and `WeakRef` to cache your wrapper to prevent it from being build multiple time for a same object (you should have huge memory perf increase as well as some execution speed increase).

**Comment by denis-migdal** [comment]
In the next days, I'll try to put a non-enumerable Symbol property in JS object converted to Python in order to prevent wrapper duplications + to allow Brython <=> JS symmetry.

**Comment by denis-migdal** [comment]
Couldn't fix it, too much copies done, a bit chaotic.
Conversions needs to be cleaned before fixing it.

Lot of functions are wrapped many times, it is a bit dirty. Another solution need to be found for functions.

**Comment by PierreQuentel** [comment]
Salut Denis,

Je reviens sur des tickets ouverts depuis longtemps. Avec toutes les modifications depuis faites sur **`jsobjects.js`** la résolution de celui-ci était assez simple.
