### ISSUE TITLE
Creating async callbacks in Brython for JS function (need aio.create_task ?)

### ISSUE THREAD

**Issue by denis-migdal** [brython-dev/brython#2251]
Hi,

Let the following JS function taking as parameters an async callback :
```javascript
window.foo = async function(faa, c) {
	p = faa(c)
	console.log(c, p)
	await p.then(e => e)
	console.log(c, 'ended')
}
```

How to create an async function for it in Brython ?
```python
async def toto(a):
	print(a, 'toto')

foo(toto, "a")
```
Gives :
```
a
Object { __class__: {…}, "$args": Arguments, "$func": async toto102()
 }
Uncaught (in promise) TypeError: p.then is not a function
```
(ofc `toto` will never be called).

```python
async def toto(a):
	print(a, 'toto')

def toto2(a):
	return aio.run(toto(a))

foo(toto2, "b")
```
Gives :
```
b toto
b null
Uncaught (in promise) TypeError: p is null
```

I think solution could either be :
- a `aio.create_task()` returning a Promise (that could also depreciate `aio.run()` as it'll be more coherent regarding asyncio usage cf https://groups.google.com/u/1/g/brython/c/mBqfr9auat8).
- a conversion of <coroutine> to Promise when given to JS code (but that could lead to very strange behavior e.g. trying to store a coroutine to a Map would start it execution) / and potentially JS async function converted to return <coroutine> in Brython ?
- creating new keywords ? `async_js def foo():` to create JS async functions in Brython or `async_bry def foo():` to create python async functions in Brython ?
- embracing JS async, and create a function `aio.create_coroutine(fct, args)` to create aio coroutine ?

Cordially,

**Comment by PierreQuentel** [comment]
Thanks again Denis !

When calling a Javascript function `window.foo`, the Python arguments are converted to Javascript objects. The fix converts the Python async function into a JS function that, when called, returns the expected Javascript `Promise`.

**Comment by denis-migdal** [comment]
Not so fast xD

```python
async def toto():
	print('ok')

window.x = toto
print(toto)
print(window.x())
```
is giving :
```
<function toto>
ok
<Javascript object: [object Promise]>
```

When going back JS to Brython, I think the javascript object should be converted back to a `<coroutine>` to keep the symmetry between Brython => JS and JS => Brython.


Also, it would be quite a shame having to load `aio` (or the whole brython_stdlib.js) just to execute an asynchronous Brython function. Could a `javascript.execute_coroutine(<coroutine>): <Promise>` be a way of doing it ?

**Comment by denis-migdal** [comment]
Previous issue is now fixed.
