### ISSUE TITLE
Improve print() when printing HTMLElement

### ISSUE THREAD

**Issue by denis-migdal** [brython-dev/brython#2255]
Hi,

In, JS, when printing an HTMLElement, the browser console enables to (cf image):

- see the element properties by clicking on it
- to see where it is on the page, its margin and padding by hovering on it ;
- to open the inspector on the element position in the DOM by clicking on the square-like thingy. 

However, it is not the case when using `print()` in brython :
```html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf8"/>
		<title>X</title>
		<!-- Dependancies required to define custom Elements -->
		<!--<script type="text/javascript" src="/Brython-3.X/brython.js" defer></script>-->
		<!-- online version -->
		<script src="https://raw.githack.com/brython-dev/brython/master/www/src/brython.js"
			crossorigin="anonymous" defer>
		</script>
		<script type="text/python" src="/components/components.py" id="components"></script>
		<!-- -->
		<script type="text/python">
			from components import defineCustomElements;
			from browser import console;
			from browser import html;
			from browser import window;

			#// define your custom elements here :
			window.console.log('console', window.document.querySelector("h1") )
			print('print DOM', window.document.querySelector("h1") )
			print('print BRY', html.H1() )
			window.console.log('proposal', '<HTMLHeadingElement (', window.document.querySelector("h1"), ') >' )
		</script>
	</head>
	<body>
		<h1>Mon super site Web</h1>

	</body>
</html>
```

(cf image in next message).

I think this might be due to an implementation of print like :
```javascript
function print(...args):
      console.log(args.join(" "))
```
When it should be :
```javascript
function print(...args):
      console.log(...args)
```

Is it is not possible, I propose to modify the printing of HTMLElement (cf proposal).

![Capture d’écran_2023-10-02_18-42-10](https://github.com/brython-dev/brython/assets/16555663/a14a1464-8fa8-45e5-b2e4-1c09cff85520)

Cordially,

**Comment by PierreQuentel** [comment]
Making `print()` write something else than strings to the standard output (by default, the browser console) would not be compliant with the [Python function documentation](https://docs.python.org/3/library/functions.html#print):

> Print objects to the text stream file, separated by sep and followed by end. sep, end, file, and flush, if present, must be given as keyword arguments.

> All non-keyword arguments are converted to strings like [str()](https://docs.python.org/3/library/stdtypes.html#str) does and written to the stream, separated by sep and followed by end. Both sep and end must be strings; they can also be None, which means to use the default values. If no objects are given, [print()](https://docs.python.org/3/library/functions.html#print) will just write end.

To have the same result as with `console.log`, just use `window.console.log` as in your example - I use it a lot when debugging.

**Comment by denis-migdal** [comment]
Ok. In such cases, should documentation explicitly advises to use, when possible, `console.log()` instead of `print()` for better output formatting ?

I'm thinking about [this page](https://brython.info/static_doc/en/syntax.html).

If no, I'll close this issue.
