### ISSUE TITLE
problem with sort

### ISSUE THREAD

**Issue by rpietsch1953** [brython-dev/brython#2256]
There is an problem with "sort" a dictionary. This problem was not on older Versions of Brython but occur on 3.11 and 3.12.

Example:
print(
    dict(
        sorted(
            {
                '0': {'Name': '✋ HTV: ! HTV (StT)'}, 
                '6': {'Name': 'Radio: OE1 (DVBC)'},
                '7': {'Name': 'TV: ORF 2 N (DVB-C)'},
                '-1': {'Name': ' Alle'}
                
            }.items(),
            key=lambda item: str(item[1]['Name']),
            reverse=False
            )
        )
    )
correkt output:{'-1': {'Name': ' Alle'}, '6': {'Name': 'Radio: OE1 (DVBC)'}, '7': {'Name': 'TV: ORF 2 N (DVB-C)'}, '0': {'Name': '✋ HTV: ! HTV (StT)'}}
Brython output:{'0': {'Name': '✋ HTV: ! HTV (StT)'}, '6': {'Name': 'Radio: OE1 (DVBC)'}, '7': {'Name': 'TV: ORF 2 N (DVB-C)'}, '-1': {'Name': ' Alle'}}

**Comment by PierreQuentel** [comment]
Thanks for the report @rpietsch1953  !
