### ISSUE TITLE
Array of Array not properly synchronized (JS => Brython) !

### ISSUE THREAD

**Issue by denis-migdal** [brython-dev/brython#2261]
Hi,

```html
<!DOCTYPE html>
<html>
    <head>
        <!-- Required meta tags-->
        <meta charset="utf-8">

        <title>X</title>

        <!-- Brython -->
        <script src="https://raw.githack.com/brython-dev/brython/master/www/src/brython.js"></script>
        <script src="https://raw.githack.com/brython-dev/brython/master/www/src/brython_stdlib.js"></script>

        <script type="text/python">

            from browser import window

            a = window.a
            a0 = window.a[0]

            def foo():
                print(a[0][0], a0[0], a[1])

            window.setTimeout( foo, 2000)
        </script>

        <script>
            let a = [ [false,false] , false ];

            window.a = a;
            window.a0 = a[0];

            setTimeout( () => {a[0][0] = true, a[1] = true}, 1000)
        </script>
    </head>
    <body>
    </body>
</html>
```
Is giving `True False True` when it should be `True True True`.

I think this is due to (?) :
- [ ] [2249] Cache wrappers (using `WeakMap` and  `WeakRef`) created by Brython to prevent recreating them at each access ([more info](https://github.com/brython-dev/brython/issues/2249#issuecomment-1741802743))
   - Would solve performances issues (mainly memory consumption), would also significantly reduce execution time in some cases (see [2260]).
   - Would likely solve bug [2249] on Map get/set ([more info](https://github.com/brython-dev/brython/issues/2249#issuecomment-1741812785))
   - Would likely solve bug [2254] on `unbind(window.foo)` ([more info](https://github.com/brython-dev/brython/issues/2254#issuecomment-1742406608))

**Comment by denis-migdal** [comment]
Notice that objects are properly synchronized :
```
<!DOCTYPE html>
<html>
    <head>
        <!-- Required meta tags-->
        <meta charset="utf-8">

        <title>X</title>

        <!-- Brython -->
        <script src="https://raw.githack.com/brython-dev/brython/master/www/src/brython.js"></script>
        <script src="https://raw.githack.com/brython-dev/brython/master/www/src/brython_stdlib.js"></script>

        <script type="text/python">

            from browser import window

            a = window.a
            a0 = window.a[0]

            def foo():
                print(a[0][0], a0[0], a[1])

            window.setTimeout( foo, 2000)
        </script>

        <script>
            let a = {0: {0:false,1:false} , 1: false };

            window.a = a;
            window.a0 = a[0];

            setTimeout( () => {a[0][0] = true, a[1] = true}, 1000)
        </script>
    </head>
    <body>
    </body>
</html>
```

**Comment by denis-migdal** [comment]
Maybe due to the copy made here :
```javascript
if(Array.isArray(jsobj)){
        return $B.$list(jsobj.map(jsobj2pyobj))
    }
```

If you rewrite Python access `array[X]` to `array.at(X)` (I assume you already have a function like that ?), you could implement it as something like that ?
```
if(Array.isArray(jsobj)){
        return $B.$list(jsobj, jsobj.map(jsobj2pyobj)) // this.jsArray = jsobj , this.pyArray = jsobj.map(jsobj2pyobj)
    }
    
function at(idx) {
      let pyobj = this.pyArray[idx];
      let jsobj = this.jsArray[idx];
      if(pyobj === jsobj || pyobj.jsobj === jsobj) // no changes
           return pyobj
      else // object has been updated, we need to convert it.
          return this.pyArray[idx] = jsObj2pyObj(jsobj) // I assume jsObjpyObj sets this.jsobj on the produced result.
}
```

Access would be slower but it'll solve synchronization issues (?).

You could also make it lazy for better performances when creating the py array :
```javascript
if(Array.isArray(jsobj)){
        return $B.$list(jsobj) // => set this.pyArray to []
    }
```
Hence, `jsObj2pyObj` would only be called upon first access.

Could also be HUGE performances increase for creation (with little to no access), especially when this is an array of arrays.

**Comment by denis-migdal** [comment]
**Note** : could be solved by https://github.com/brython-dev/brython/issues/2269#issuecomment-1755725213

**Comment by PierreQuentel** [comment]
Encore merci Denis, à force tout ça va finir par marcher correctement !

**Comment by denis-migdal** [comment]
> Encore merci Denis, à force tout ça va finir par marcher correctement !

Rhôooo je vais plus pouvoir m'amuser à tout casser :'(



C'est moi qui te remercie pour ton travail et ta réactivité. ;)
