### ISSUE TITLE
Regression: csv module cannot be imported in Brython 3.12

### ISSUE THREAD

**Issue by rayluo** [brython-dev/brython#2278]
Bonjour, @PierreQuentel . It is exciting to see Brython 3.12 released no long after Python 3.12!

Unfortunately, one of my Brython project that was using `csv` module is now broken.

Repro:

Create a foo.html with the content below:
```html
<body id="body" onload="brython()">
</body>

<!-- The following 2 lines loads latest Brython which is 3.12 -->
<script src="https://cdn.jsdelivr.net/npm/brython@3/brython.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/brython@3/brython_stdlib.min.js"></script>
<script type="text/python">import csv</script>
```

Error shown in browser's console:
```
Traceback (most recent call last):
  File "http://localhost:8000/foo.html#__main__", line 1, in <module>
    import csv
ImportError: cannot import name 'QUOTE_STRINGS' from '_csv' (VFS._csv.py). Did you mean: '[object Object]'?
```

Workaround is to downgrade Brython back to 3.11.

**Comment by denis-migdal** [comment]
I reproduced this issue on the dev version.

Note: @rayluo you do not need to write `onload="brython()"` anymore with 3.12 ;)

**Comment by denis-migdal** [comment]
At [Lib/_csv.py:66](https://github.com/brython-dev/brython/blob/master/www/src/Lib/_csv.py#L66) :
````python
QUOTE_MINIMAL, QUOTE_ALL, QUOTE_NONNUMERIC, QUOTE_NONE = range(4)
````
I guess `QUOTE_STRINGS` was expected to be defined here ?

Though I do not find `QUOTE_STRINGS` symbol anywhere in this file. 

At [Lib/csv.py:12](https://github.com/brython-dev/brython/blob/master/www/src/Lib/csv.py#L12)
````python
from _csv import Error, __version__, writer, reader, register_dialect, \
                 unregister_dialect, get_dialect, list_dialects, \
                 field_size_limit, \
                 QUOTE_MINIMAL, QUOTE_ALL, QUOTE_NONNUMERIC, QUOTE_NONE, \
                 QUOTE_STRINGS, QUOTE_NOTNULL, \
                 __doc__
````
`QUOTE_STRINGS` is only used again at line 19 of the same file.


`QUOTE_STRINGS` seems to be an addition of Python 3.12, however it doesn't seem implemented in `_csv.py`, maybe the file should be updated ?

> Add [csv.QUOTE_NOTNULL](https://docs.python.org/fr/dev/library/csv.html#csv.QUOTE_NOTNULL) and [csv.QUOTE_STRINGS](https://docs.python.org/fr/dev/library/csv.html#csv.QUOTE_STRINGS) flags to provide finer grained control of None and empty strings by [csv.writer](https://docs.python.org/fr/dev/library/csv.html#csv.writer) objects.
https://docs.python.org/fr/dev/whatsnew/3.12.html

**Comment by PierreQuentel** [comment]
Merci Ray ! Denis was right, there were missing values in **`_csv.py`**
