### ISSUE TITLE
[FEATURE] Authorize top level await by default (equiv to python -m asyncio by default?) ?

### ISSUE THREAD

**Issue by denis-migdal** [brython-dev/brython#2279]
Hi,

Currently we can't write :
````python
async def foo():
    print('ok');

await foo();
````
````
    await foo();
    ^^^^^^^^^^^
SyntaxError: 'await' outside function
````

However, this is possible in Python (with `python -m asyncio`) :
- https://piccolo-orm.com/blog/top-level-await-in-python/
- https://docs.python.org/fr/3/library/asyncio.html

Currently, as the Browser already has an event loop, Brython is faking the `asyncio.run()`, in a way that isn't coherent with the behavior of `asyncio`. I argue that having the behavior of `python -m asyncio` would be more coherent as "Brython code is running on the Browser that already has an event loop" would be like `python -m asyncio` : "Python code is running on asyncio that provides an event loop". Therefore asyncio event loop would be the Browser event loop.

> The asyncio.run() is a Python function used to run a coroutine in an event loop. This function creates an event loop, runs the coroutine in the event loop, and finally closes the event loop when the coroutine is complete.
> Note: asyncio.run() **should only be used once** in a program and is intended as a convenient function to run asynchronous functions in a simple, single-threaded manner.

Instead, we could use [`asyncio.create_task`](https://docs.python.org/3/library/asyncio-task.html#asyncio.create_task), that would be more close to the current behavior in Brython ?
- cf https://bbc.github.io/cloudfit-public-docs/asyncio/asyncio-part-2.html#tasks

To reproduce the behavior of `create_task` () :

> If you do it in asynchronous code then the event loop is already running (since it is currently executing your asynchronous code), and when it next gets the opportunity (ie. next time your current task pauses) it might make the new task active.

````javascript
function create_task( coroutine ) { // no needs for async as it returns a Promise.
    console.log('called');
    return new Promise( (r,err) => {
      setTimeout( () => {
          if( canceled )
               err('canceled');
          console.log('starts executing')
          // execute coroutine here
          r( ???? );
      }, 0);
   }
}

create_task(  ..... );
console.log('after');
````

**EDIT:** after each `await` \ `yield` in `async` function, we could verify if we are inside a task and if this task has been canceled, then, we could raise an exception or return (?), to stop the execution ?

**OR**

- in the stack, add the last awaited promise inside the task : `task_stack.$last_await = p;` before each `await p`, so that we can call its `err` callback when canceling the task, therefore ending immediately the last `await`, and after the await, if canceled, raise an exception `TaskCanceled`, that will be propagated until the first `create_task` that will catch it (should also be done before/after `yield`) ?

Could be simplified by wrapping the `await ...` inside a `stack.$await(...)`, that'd handle, if inside a task :
- recording it as the last await
- exposing the `err` callback
- calling the `err` callback if the task is canceled.
- if the underlying Promise is canceled due to `TaskCanceled`, resolve to `err`, etc.

Note that :
> When you do it in synchronous code, however, chances are that the event loop is not yet running.

Which is not our case, so we are safe.

Cordially,

**Comment by PierreQuentel** [comment]
If we allowed top-level `await`, what would happen with `import module_with_top_level_await` ?

**Comment by denis-migdal** [comment]
> If we allowed top-level `await`, what would happen with `import module_with_top_level_await` ?

We'll have to check with the behavior of CPython `python -m asyncio`.

Gonna check that.

**Comment by PierreQuentel** [comment]
Top-level await is not standard Python. I am not a total beginner at the language, and didn't know that it was allowed by `python -m asyncio`. 

I have no strong argument to break compliance with Python for this feature:
- it would not change the way `import` is implemented, because of non-top level imports and because you couldn't import a module with top-level await
- I would be very uncomfortable having to explain that the feature is supported in scripts written in a <script> tag, but not with the same code imported from a Python module

My conclusion is not in favour of this proposal.

**Comment by denis-migdal** [comment]
Ok. I guess the Brython way of doing it would be :
```python
from browser import aio # requires stdlib_brython.js

async def main(): # all our "top level" code needs to be in this function.
     message = await fetch("...") # an asynchronous function defined somewhere
     print(message)

if __name__ == "__main__":
    aio.run( main() )
```

Then, could we at least have `aio` put in `brython.js` instead of `stdlib_brython.js` ?

Or alternatively to have a `@js_async` decorator :
```python
from browser.javascript import js_async

@js_async
async def main():
     message = await fetch("...") # an asynchronous function defined somewhere
     print(message)
     
if __name__ == "__main__":
    main() # starts running, returns a JS Promise
```


Indeed, in WebDev, asynchronism is very frequent (mainly due to AJAX/fetch queries), and is at the core of the language.
Therefore I argue we should be able to execute asynchronous functions without having to rely on `brython_stdlib`.

It is therefore not a matter of implemented a python standard library, but to provide a core feature for Brython due to the Web Dev environment. Hence why I argue it should be in `brython.js` instead of `brython_stdlib`.

`aio` also provides `ajax`, `event` and `sleep`.


**Another unrelated question :** shouldn't `aio.ajax` be depreciated and replaced by a `aio.fetch` in `asyncio` ?

**Comment by PierreQuentel** [comment]
You could get the same result without **`aio`**:

```python
from browser import window

def load(url):
    def func(f):
        def read(resp):
            resp.text().then(f)
        window.fetch(url).then(read)
    return func

@load('/src/Lib/bisect.py')
def main(s):
    print(s)
```

**Comment by denis-migdal** [comment]
> You could get the same result without **`aio`**

Not if `fetch` is e.g. a python async function.


Moreover, for JS async functions, using a chain of `.then()` is quite dirty, that's why Javascript added `await`.
If you have 2-3 `fetch` to do, it becomes quite horrible to read (and to write) :

```python
def load(url):
    def func(f):
        def read(resp):
            resp.text().then(f)
        window.fetch(url).then(read)
    return func

@load('/src/Lib/bisect.py')
def main(s):
    print(s)

    @load('/src/Lib/bisect2.py')
    def main2(s):
         print(s)
         
         @load('/src/Lib/bisect3.py')
         def main3(s):
               print(s)

         main3()
    main2()
``` 

The following code is way nicer to read :
```python
async def load(url):
    answer = await window.fetch(url)
    return await answer.text()

async def main():
    print( await load('/src/Lib/bisect.py'  ) )
    print( await load('/src/Lib/bisect2.py') )
    print( await load('/src/Lib/bisect3.py') )

aio.run( main() )
# or
main() # if @js_async to convert Python async function into a JS async-like function
# or
browser.run( main() ) # or whatever
``` 

I'm looking at `aio`. I didn't saw it had a quite heavy python part.

Implementing `browser.run()` would be only a few lines, just moving `aio.run` to `browser`, and use `browser.run` in `aio.run` :
```javascript
function run(coro){
    var handle_success = function(){
            $B.leave_frame()
        },
        handle_error = $B.show_error

    var $ = $B.args("run", 3, {coro: null, onsuccess: null, onerror: null},
            ["coro", "onsuccess", "onerror"], arguments,
            {onsuccess: handle_success, onerror: handle_error},
            null, null),
        coro = $.coro,
        onsuccess = $.onsuccess,
        onerror = $.onerror

    if(onerror !== handle_error){
        function error_func(exc){
            try{
                onerror(exc)
            }catch(err){
                handle_error(err)
            }
        }
    }else{
        error_func = handle_error
    }

    var save_frame_obj = $B.frame_obj
    $B.coroutine.send(coro).then(onsuccess).catch(error_func)
    $B.frame_obj = save_frame_obj
    return _b_.None
}
```

`@js_async` decorator could also be implemented with very few lines :
```javascript
function js_async(fct) {
    return await function(){
           return await $B.promise( js_async(fct) )
    }
}
```


**Question :** what is the difference between `browser.aio.ajax` and `browser.ajax` ?
Is one recommended ? Is `browser.ajax` inside `brython.js` ?

**Comment by PierreQuentel** [comment]
In commit 4f2c0bf38e643130652b2d9af16e3be4fd4ae7c8 I have moved most of the code of **`browser.aio`** in **`builtin_modules.js`**. It makes **`brython.js`** bigger, but you can't have the butter and the money of the butter ;-)

**`browser.ajax`** is not in **`brython.js`**. The only modules included in **`brython.js`** are those in **`builtin_modules.js`** : **`browser, browser.html, javascript, _sys, _warnings`** and now **`browser.aio`**

**Comment by denis-migdal** [comment]
Thanks ^^

The difference in `brython.js` doesn't seem to be very big :
- 907kB vs 929kB, so ~22kB (+2%).

But yeah someday, once lot of issues are closed, I'll start looking at the 50k line of code to fix stuffs.


Well, that's one more issue closed ;)
Thanks for your work.
