### ISSUE TITLE
How can we use brython in react js component ?

### ISSUE THREAD

**Issue by kavinsharma** [brython-dev/brython#2282]
I am trying to create a online python code editor and planning to use ace code editor and brython for executing the code in runtime ? need help how can we integrate brython in react.js

**Comment by denis-migdal** [comment]
Hi,

I'd want to use `javascript.py2js(src)` to convert the python code to JavaScript, then use `eval()` to execute it ?

https://brython.info/static_doc/3.12/fr/javascript.html


Cordially,
