### ISSUE TITLE
Ahead Of Time compilation in Brython?

### ISSUE THREAD

**Issue by dr-gavitron** [brython-dev/brython#2290]
Wondering if AOT possible in Brython?

**Comment by denis-migdal** [comment]
As Brython is transpiling Python to JS, it is possible to save the generated JS into a file.

Unfortunately, I am not sure whether the current way of doing so is easy to use.
If I'm not wrong the current `make_dist` is putting the Python code into a JS file.



I opened an issue to suggest a feature that would allow to easily use AOT (I have to post a final draft I am currently working on) :
https://github.com/brython-dev/brython/issues/2276

**Comment by PierreQuentel** [comment]
@dr-gavitron 

If by AOT you mean pre-translation of Brython code to Javascript, this is both not available and built-in through an indexedDB cache. More information in the [FAQ](https://www.brython.info/static_doc/3.12/en/faq.html)

**Comment by denis-migdal** [comment]
> If by AOT you mean pre-translation of Brython code to Javascript, this is both not available and built-in through an indexedDB cache. More information in the [FAQ](https://www.brython.info/static_doc/3.12/en/faq.html)

Well he can use [`__BRYTHON__.pythonToJS()`](https://brython.info/static_doc/3.12/fr/jsobjects.html) in a pipeline to convert his Python code to JS and save it into a file, then he can use [`load()`](https://brython.info/static_doc/3.12/fr/jsobjects.html) to execute the JS at the good time ?

**Comment by dr-gavitron** [comment]
> > If by AOT you mean pre-translation of Brython code to Javascript, this is both not available and built-in through an indexedDB cache. More information in the [FAQ](https://www.brython.info/static_doc/3.12/en/faq.html)
> 
> Well he can use [`__BRYTHON__.pythonToJS()`](https://brython.info/static_doc/3.12/fr/jsobjects.html) in a pipeline to convert his Python code to JS and save it into a file, then he can use [`load()`](https://brython.info/static_doc/3.12/fr/jsobjects.html) to execute the JS at the good time ?

Have you tried this? Why I'm interested in AOT is: making things faster by omitting the translation phase... this should be a built-in feature and not by collecting cache js...

**Comment by denis-migdal** [comment]
> Have you tried this? Why I'm interested in AOT is: making things faster by omitting the translation phase... this should be a built-in feature and not by collecting cache js...

Well I already succeeded in executing JS code generated by the [editor](https://brython.info/tests/editor.html?lang=fr), in a little dirty way (I use a `setTimeout()`).

I can try a small exemple with theses functions.

**Comment by denis-migdal** [comment]
Here an exemple, there are timing issues (that hope will be solved soon):

````html
<html>
	
	<head>
		<script src="https://raw.githack.com/brython-dev/brython/master/www/src/brython.js"></script>

		<!-- STEP 2: put the JS into a script -->
		<script>

			function FCT() {
// Javascript code generated from ast
var $B = __BRYTHON__,
_b_ = $B.builtins,
locals_python_script_0 = $B.imported["python_script_0"],
locals = locals_python_script_0,
frame = ["python_script_0", locals, "python_script_0", locals]
frame.__file__ = 'undefined#python_script_0'
locals.__name__ = 'python_script_0'
locals.__doc__ = _b_.None
locals.__annotations__ = locals.__annotations__ || $B.empty_dict()
frame.$f_trace = $B.enter_frame(frame)
$B.set_lineno(frame, 1)

var _frame_obj = $B.frame_obj,
stack_length = $B.count_frames()
try{
$B.set_lineno(frame, 1);
$B.$call(_b_.print, [0,0,25])('Hell, no words !')
$B.leave_frame({locals, value: _b_.None})
}catch(err){
$B.set_exc(err, frame)
if((! err.$in_trace_func) && frame.$f_trace !== _b_.None){
frame.$f_trace = $B.trace_exception()
}
$B.leave_frame({locals, value: _b_.None})
throw err
}
return locals}


			setTimeout( FCT, 500 );
</script>
		<script>
			// STEP 1: generate the JS
			console.log( __BRYTHON__.pythonToJS("print('Hell, no words !')") );

		</script>
	</head>
	<body>
		
	</body>

</html>
````

**Comment by denis-migdal** [comment]
And here an exemple with load :
````html
<html>
	
	<head>
		<script src="https://raw.githack.com/brython-dev/brython/master/www/src/brython.js"></script>

		<!-- STEP 2: put the JS into a file -->
		<script type="text/python">
			# STEP 3: load the file in Brython to avoid timing issues
			from browser import load

			load('/test_ast.js')
		</script>
		<script>
			// STEP 1: generate the JS
			console.log( __BRYTHON__.pythonToJS("print('Hell, no words !')") );

		</script>
	</head>
	<body>
		
	</body>

</html>
````

**Comment by PierreQuentel** [comment]
Of course, _technically_ you can find ways to generate JS code, store the result in a JS file (it will be around 10 times bigger than the Python source) and use it instead of the original Brython code.

It's just that it's not how Brython is designed; it is meant to be as easy to use a Javascript, without any precompilation phase. Edit the script, reload the page, et voilà !

**Comment by denis-migdal** [comment]
>  Edit the script, reload the page, et voilà !

Well, now there are tools that reloads the page for you :P

You could have a `brython-cli watch` that could do (if you choose to do so) all the Brython => JS conversion for you when a file change, and a live server that'd reload the page for you ;).

> it will be around 10 times bigger than the Python source

I am wondering, what is the relative cost between downloading 10x more of source code (compressed) and building the JS from the Brython source code ?


I think it could be great for Brython to enable both usage :
- the first, simpler one.
- the second, for more advanced uses and integration with other WebDev tools (bundler, tree shaking, etc).

**Comment by dr-gavitron** [comment]
I have a doubt... I have seen brython application takes lots of memories around 80-90 MB... You can see it in the performance tab of developer's tools... does the pre-generated javascript takes that much resources? And what are the speed benchmark wrt native python and native(vanilla) javascript

**Comment by denis-migdal** [comment]
> I have a doubt... I have seen brython application takes lots of memories around 80-90 MB...

I'll soon make some micro-optimizations in Brython's code, which should reduce a little memory usage.
There are a lot of non-preallocated arrays and other stuff like that I will track (50k lines to look at xD).

But note that lot of optimizations were made in the past months (dev version) :
- load time went from 200ms to 20ms (and a big chunk linked to unicode support were removed).
- argument parsing is now speed up.
- etc.

> And what are the speed benchmark wrt native python and native(vanilla) javascript

Brython, and any other technologies used to convert Python will never come close to vanilla JavaScript.
Still, this is fast enough for the need of a Web Pages (DOM manipulations are slow).

Indeed :
- either you transform Python into WASM, but you need to ship a Python engine with it. So it becomes very big, and you need some "bridges" in order to be able to manipulate DOM (WASM has no access to DOM).
- or you convert Python code into JS code, but due to differences in the languages, you have to do some heavy operations to mimic normal Python behavior. The advantage of Brython is that he is 100% behavior-compatible with CPython.

I don't know the current differences between Python and Brython.
I think functions call are slower, but some operations are faster (JS being faster than Python).

**Comment by PierreQuentel** [comment]
There is a built-in [speed test comparison between Brython and CPython](https://www.brython.info/speed_results.html) available from the home page of brython.info

**Comment by denis-migdal** [comment]
I'm curious, what is now the functions/methods call cost in the dev version ?

In the git, `speed/make_report.html` is returning:
````
Erreur d’analyse XML : aucun élément trouvé
Emplacement : http://localhost:8000/cgi-bin/store_speed.py
Numéro de ligne 1, Colonne 1 : store_speed.py:1:1
````

**Comment by PierreQuentel** [comment]
> I'm curious, what is now the functions/methods call cost in the dev version ?

Sorry I don't understand this question

For the error message : do you use `server.py` as web server ?

**Comment by denis-migdal** [comment]
> > I'm curious, what is now the functions/methods call cost in the dev version ?
> 
> Sorry I don't understand this question

If I'm not wrong, the report in brython.info was built using the last released version, so three weeks ago.

I was wondering what was the numbers with the current code on github (so the dev version, the one we are working on).


> For the error message : do you use `server.py` as web server ?

Yep.

**Comment by PierreQuentel** [comment]
> I was wondering what was the numbers with the current code on github (so the dev version, the one we are working on).

I ran the speed test with your new version of `$B.args0` before merging the PR, it was around 25% faster than the old version.

If you use **`server.py`** I don't know what causes the error message. I just cloned the repo and ran _/speed/make_report.html_, it worked without any error.

**Comment by denis-migdal** [comment]
> If you use **`server.py`** I don't know what causes the error message. I just cloned the repo and ran _/speed/make_report.html_, it worked without any error.

I made some tests. I think this is due to :
````python
#!c:/python37/python.exe
````
Indeed, I'm on Linux...

I think that instead of `os.execve(scriptfile, args, env)` it should be better to execute the command "python3 scriptfile [...]" or something like that ?

**Comment by ed2050** [comment]
> There is a built-in [speed test comparison between Brython and CPython](https://www.brython.info/speed_results.html) available from the home page of brython.info

Nice comparison.  Reading that page hurts my brain though.  Numbers on right blur together with code.
If you add this to the page it becomes much more readable:
```
td[align="right"] { padding-right: 2em; }
```

**Comment by denis-migdal** [comment]
@dr-gavitron 
This should enable you to make AoT translation : https://github.com/denis-migdal/Brython-AOT

Can you test it to see if it solves your issue ?
