### ISSUE TITLE
"bizarre" message in browser console when using pythonpath

### ISSUE THREAD

**Issue by JamesHutchison** [brython-dev/brython#2291]
When I set the python path I get a console message with "bizarre" everytime the page loads.

```
bizarre (2) ['http://127.0.0.1:8000/static/brython', 'https://cdn.jsdelivr.net/npm/brython@3.12.0/Lib/site-packages']
```

This is from:

```javascript
window.onload = function() {  brython({debug: 1, pythonpath: ['/static/brython']}); }
```

**Comment by PierreQuentel** [comment]
@JamesHutchison 

Sorry, I can't reproduce the issue. Can you give a minimal version of the HTML page that gives you this message ?

**Comment by JamesHutchison** [comment]
Thanks for checking into this! This seems to reproduce the issue:

`brython_bug.html`
```html
<html>

<head>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/brython@3.12.0/brython.min.js"></script>
    <script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/brython/3.12.0/brython_stdlib.min.js"></script>
    <script type="text/javascript">
        window.onload = function () { brython({ debug: 1, pythonpath: ['/static/brython'] }); }
    </script>
    <script type="text/python" src="/static/brython/hashing.py" id="hashing"></script>
</head>

</html>
```

Sanic server:

`brython_bug.py`
```python
import sanic
from sanic import Sanic, text

app = Sanic("BrythonBug")

app.static("/static", "./static", name="static_files")


@app.get("/")
async def hello_world(request):
    return await sanic.file("brython_bug.html")


if __name__ == "__main__":
    app.run()
```

Directory structure:
`./static/brython/*` contains the Brython files. Here's `hashing.py`

```python
import hashlib


def sha256(message) -> str:
    # Convert the string to bytes
    message_bytes = message.encode("utf-8")

    # Compute the sha256 hash
    hash_obj = hashlib.sha256(message_bytes)

    return hash_obj.hexdigest()
```

I have another bug as well. I'll get a Codespace set up for you so its easy to reproduce.

**Comment by denis-migdal** [comment]
Can't reproduce it either.

I didn't test it with the Sanic server through.

**Comment by JamesHutchison** [comment]
I've created a codespace configuration that allows you to very easily reproduce this bug and one other other (I'll make a ticket for the other one). You can get it on the branch I just created.

https://github.com/JamesHutchison/brython/tree/bug-repo

In github simply click on the green "code" button and then the codespaces tab, then create a new codespace on the current branch.

In the visual studio code that opens, after the postCreateCommand finishes running, go the "run config" button and run "Run Bug Repro Server". Then just go to localhost:8000 and open the chrome console.

**Comment by denis-migdal** [comment]
Okay, I reproduced the bug in the codespace.

I just noticed, why your CDN for `brython_stdlib.js` isn't the same as the one for `brython.js` ?
This is not the thing causing the issue, but this is a little strange.

Could you use `brython.js` instead of `brython.min.js` so that we can see which line is causing the issue ?
Did you tried without the Sanic server ? To see if it causes the bug ?

**Comment by JamesHutchison** [comment]
I'm not at my computer right now but your codespace is your copy of the code and you're free to modify it, test a fix, etc

I think when I tried this using local files instead of hosting it on a web server I wasn't seeing the bug. I'm under the impression the file protocol imports and the web imports do not follow the same code path.

IIRC if you search for "bizarre" there's an place in the import logic where if pythonpath is provided then it does a search for something in the import path and if it can't find it then it logs this message. Seemed like a probable culprit.

**Comment by denis-migdal** [comment]
> I think when I tried this using local files instead of hosting it on a web server I wasn't seeing the bug. I'm under the impression the file protocol imports and the web imports do not follow the same code path.

Nope, I already tested it with a fake web server (`browser-sync`) and it didn't raise an error.

I think it is more likely that Brython is searching for a package in the PATH, first in `http://127.0.0.1:8000/static/brython`, and that Sanic is responding with a message that Brython isn't expecting.

**Comment by denis-migdal** [comment]
Here the header when using `browser-sync` :
````
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: public, max-age=0
Last-Modified: Thu, 26 Oct 2023 23:18:27 GMT
ETag: W/"e7-18b6e483395"
Content-Type: application/octet-stream
Content-Length: 231
Date: Fri, 27 Oct 2023 06:44:18 GMT
Connection: keep-alive
Keep-Alive: timeout=5
````

Here the header when using Sanic:
````
HTTP/2 200 
date: Fri, 27 Oct 2023 06:41:25 GMT
content-type: text/x-python; charset=utf-8
content-length: 232
cache-control: no-cache
last-modified: Fri, 27 Oct 2023 04:07:52 GMT
x-content-type-options: nosniff
ratelimit-limit: HttpRequestRatePerPort:3000/m
ratelimit-remaining: HttpRequestRatePerPort:2999
ratelimit-reset: HttpRequestRatePerPort:29s
x-report-abuse: https://msrc.microsoft.com/report/abuse
x-ms-ratelimit-limit: 
x-ms-ratelimit-remaining: 
x-ms-ratelimit-used: 1
x-ms-ratelimit-reset: 
x-robots-tag: noindex, nofollow
referrer-policy: same-origin
vssaas-request-id: bec57e26-7247-4dcf-9987-238e3c40d9cd
strict-transport-security: max-age=31536000; includeSubDomains
x-served-by: tunnels-prod-rel-uks1-v3-cluster
X-Firefox-Spdy: h2
````

Could it be the content-type that disturbs Brython (?).

**Comment by PierreQuentel** [comment]
I could reproduce the bug with the example you gave, thanks !

The reason for this message was probably that an internal value (the script directory) was not correctly set. With the commit referenced above you should not see it anymore.

I wasn't lucky with the options you suggest to test the code:
- I probably miss something obvious but on codespaces I don't see any "run config" button anywhere on the page (cf. attached screen image)
![codespaces](https://github.com/brython-dev/brython/assets/3447215/2851f238-1daf-4fd5-ba4f-1dcb3e487007)

- sanic wouldn't start on my PC with this message, and I was too lazy to investigate
```
D:\brython\JamesHutchison\bug_repro>sanic bug
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python312\Scripts\sanic.exe\__main__.py", line 4, in <module>
  File "C:\Python312\Lib\site-packages\sanic\__init__.py", line 6, in <module>
    from sanic.app import Sanic
  File "C:\Python312\Lib\site-packages\sanic\app.py", line 55, in <module>
    from sanic.application.state import ApplicationState, ServerStage
  File "C:\Python312\Lib\site-packages\sanic\application\state.py", line 13, in <module>
    from sanic.server.async_server import AsyncioServer
  File "C:\Python312\Lib\site-packages\sanic\server\__init__.py", line 5, in <module>
    from sanic.server.runners import serve
  File "C:\Python312\Lib\site-packages\sanic\server\runners.py", line 6, in <module>
    from sanic.config import Config
  File "C:\Python312\Lib\site-packages\sanic\config.py", line 13, in <module>
    from sanic.errorpages import DEFAULT_FORMAT, check_error_format
  File "C:\Python312\Lib\site-packages\sanic\errorpages.py", line 26, in <module>
    from sanic.pages.error import ErrorPage
  File "C:\Python312\Lib\site-packages\sanic\pages\error.py", line 3, in <module>
    import tracerite.html
  File "C:\Python312\Lib\site-packages\tracerite\__init__.py", line 1, in <module>
    import pkg_resources
  File "C:\Python312\Lib\site-packages\pkg_resources\__init__.py", line 2191, in <module>
    register_finder(pkgutil.ImpImporter, find_on_path)
                    ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
```

Not directly related, but since version 3.12.0 you can set `pythonpath` without calling `brython()` in Javascript, either at page level

```xml
<brython-options pythonpath="/static/brython"></brython-options>
```

or for each script with
```
<script type="text/python" src="/static/brython/hashing.py" id="hashing" pythonpath="/static/brython"></script>
```

**Comment by JamesHutchison** [comment]
![run-config-button](https://github.com/brython-dev/brython/assets/122519877/5b2183e7-b598-4c29-8240-4921f86373bd)

Play button w/ bug on the left
Then play button next to "Run Bug Repro Server" drop down at the top

Alternatively, can press f5 at any point in time as there is only one run configuration

You can then click on "Open in Browser" when it appears on the lower right, or just open a browser to localhost:8000
![lower-right-message](https://github.com/brython-dev/brython/assets/122519877/e89a800c-4acc-44a1-8fb3-2b6194934711)

**Comment by JamesHutchison** [comment]
Also Sanic doens't support 3.12 yet

https://github.com/sanic-org/sanic/issues/2836

**Comment by PierreQuentel** [comment]
I did try this button, but got this error message at the bottom right of the screen
![codespaces2](https://github.com/brython-dev/brython/assets/3447215/a5011531-2d71-42e6-949d-82d75ceacda4)

**Comment by JamesHutchison** [comment]
Looks like both bug 1 and bug 2 (https://github.com/brython-dev/brython/issues/2294) are fixed? I'm not seeing any console errors now.

**Comment by JamesHutchison** [comment]
Sometimes the async nature of things getting set-up in the dev container results in erroneous errors. Since mypy is just for type checking I'd just ignore it.

**Comment by PierreQuentel** [comment]
After a few tries I found the "Run bug repro server" button, but when I hit it I get another error message
![codespaces3](https://github.com/brython-dev/brython/assets/3447215/c097bf57-2b64-406a-b449-87e62284f91f)

**Comment by JamesHutchison** [comment]
Since this where it binds the socket maybe the port is in use by an already running instance? You could try stopping and starting the codespace so it's in a clean state

**Comment by JamesHutchison** [comment]
I used two codespaces with public ports to emulate fetching the file from a CDN (resulting in a different host) and things look good. Thanks @PierreQuentel for jumping on this so quickly!
