### ISSUE TITLE
Formatted string literals

### ISSUE THREAD

**Issue by clairvoyante** [brython-dev/brython#2293]
In https://docs.python.org/3/reference/lexical_analysis.html#f-strings :
```
>>> f"abc{a # This is a comment }"
... + 3}"
'abc5'
```
>Changed in version 3.12: Prior to Python 3.12, comments were not allowed inside f-string replacement fields.

Brython 3.12.0(https://brython.info/tests/console.html?lang=en) :
```
Brython 3.12.0 on Netscape 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.61
Type "help", "copyright", "credits" or "license" for more information.
>>> f"abc{a # This is a comment }"
... + 3}"
... 
```

**Comment by clairvoyante** [comment]
IMHO, We require ```a=2``` prior of :
```
>>> f"abc{a # This is a comment }"
... + 3}"
'abc5'
```

**Comment by PierreQuentel** [comment]
@clairvoyante You are right, this failed with release 3.12.0, but the bug was fixed since then and the code should work with the current development vesion. Can you check ?

**Comment by denis-migdal** [comment]
> @clairvoyante You are right, this failed with release 3.12.0, but the bug was fixed since then and the code should work with the current development vesion. Can you check ?

I checked, the issue is solved in current dev version.
