### ISSUE TITLE
Trailing slash in query parameter confuses Brython on current path

### ISSUE THREAD

**Issue by JamesHutchison** [brython-dev/brython#2294]
If you have a query parameter that ends in a forward slash, Brython will interpet the whole URL, including the query parameter, as the current path. When it does an import, it'll try to do this import:

`localhost:8000/login?redirect_uri=/` -> `localhost:8000/login?redirect_uri=/mymodule.py`

This of course will get a 200 status, and then Brython attempts to execute the HTML and fails, which then breaks everything.

Currently the workaround is to do something like `quote('/', safe='')` to prevent the trailing slash.

You can easily reproduce the bug on this branch:

https://github.com/JamesHutchison/brython/tree/bug-repo

Just create a new codespace on the branch and then run the "Run Bug Repro Server" run configuration, or alternatively open a fresh terminal and run `cd bug_repro; sanic bug` then just visit the web server that starts up.

This is "bug 2". The error should be obvious in the chrome console. Thanks!

**Comment by PierreQuentel** [comment]
Closing this issue with the same comment as #2291.
