### ISSUE TITLE
[Feature/Opti] Using Python module written in C inside Brython

### ISSUE THREAD

**Issue by denis-migdal** [brython-dev/brython#2296]
Hi,

One strength of Python is the use of module written in C to boost up performances.
Unfortunately, existing C python modules can't be used in Brython, requiring to rewrite them in JavaScript, which can be time consuming.

Due to that, re regex seems quite slow according to some issues : #1592.

One solution would be to convert C python modules into WASM, and them call such functions in JS.
Currently, there is no guarantee that converted modules would be fast (e.g. if we convert python re module into WASM).
BUT, it would allow quick C python module conversions that could always be rewritten in JS later if necessary.

Therefore I think this would be a nice addition to Brython.
This issue is dedicated into finding how we could achieve that.

Cordially,

**Comment by denis-migdal** [comment]
Interesting link to test: https://openhome.cc/eGossip/WebAssembly/C2Wasm.html
Re module C source code: https://github.com/python/cpython/tree/main/Modules/_sre

**Comment by denis-migdal** [comment]
Current command for re module :
````shell
emcc cpython/Modules/_sre/sre.c -o hello.html -sEXPORTED_FUNCTIONS=_toto -sEXPORTED_RUNTIME_METHODS=cwrap -Icpython/Include
````

Notes:

- There are still some errors, I'm working on it and will update this message.
- We'll have to add `-O3`option later.
- We'll have to find which functions to exports + their parameters/return value format (or to create another function we'll call).

**Comment by denis-migdal** [comment]
Other links :
- https://github.com/python/cpython/blob/main/Tools/wasm/README.md
- https://docs.python.org/dev/using/configure.html#cmdoption-with-emscripten-target

**Comment by denis-migdal** [comment]
New test :

- Install : https://github.com/python/cpython/blob/main/Tools/wasm/README.md#manually
- First compilation : https://github.com/python/cpython/blob/main/Tools/wasm/README.md#cross-compile-to-wasm32-emscripten-for-browser
- `emmake make Modules/_sre/sre.o`

It produces a `./Modules/_sre/sre.o` ?
=> Then use it in a main.c file ???

**Comment by denis-migdal** [comment]
To use it ?
_test.c:_
````c
void PyInit__sre(); # not working currently.

int main() {
        PyInit__sre();

}
````

````shell
emcc -o Test.html -sEXPORTED_FUNCTIONS=[_main,_PyInit__sre] -sEXPORTED_RUNTIME_METHODS=cwrap test.c ./*/*.o ./*/*/*.o ./*/*/*/*.o
````

**Comment by denis-migdal** [comment]
@PierreQuentel Seems to work quite well, but `PyInit__sre` is giving me an infinite loop, I think there is something to initialize.

I think it'd be better to get the function we need directly.
We can modify the file and remove some `static` to be able to export some functions.

Can you tell me which functions you'd need for Python Regex ?

Also, it could be great to be able to integrate JS/WASM modules as Python modules.

**Comment by PierreQuentel** [comment]
2 MB ? Yes that's too much...

Another issue with WASM modules is that they can only be loaded asynchronously. This means that they all shoud be loaded in memory on Brython startup so that Python import statements remain synchronous.

**Comment by denis-migdal** [comment]
Tried some opti flags (`-Oz -sWASM_BIGINT -sFILESYSTEM=0 -flto`), the wasm file is still quite big with 1.4MB...
It seems sre.c has too many dependencies.

Still, emscriptem is interesting, but not for sre.c it seems.

**Comment by denis-migdal** [comment]
I'm closing this issue as it seems the generated WASM file will always be too big for `sre.c`.

Users wanting to make use of WASM can always use the JS API from Brython.
I guess that making a special Brython API for that isn't worthing it.

**Comment by denis-migdal** [comment]
I'll suggest a student project on it to see if they can remove the dependencies to reduce the wasm file size, and then look at the performances.
