### ISSUE TITLE
Random numbers that doesn't seems to be really random

### ISSUE THREAD

**Issue by fmaida** [brython-dev/brython#230]
I tried to write this code in the online editor at brython.info and run it

https://gist.github.com/fmaida/422aa5d1f1edaed2ab47

It's a very simple code that simulates a certain number of dice throws; at the end it indicates roughtly how many times each of the six faces of a dice has appeared.

No matter how many times I run it and how many throws I simulate under Brython, it seems that the number "1" is appearing way more times than the other numbers:

**For example, this is the result after a simulation of 50,000 dice throws:**

STATISTICS ON 50000 DICE THROWS
-----------------------------
**1 : 10606 (21.2%)**
2 : 7015 (14.0%)
3 : 7376 (14.8%)
4 : 7195 (14.4%)
5 : 8633 (17.3%)
6 : 9175 (18.4%)

While the numbers 2-6 have appears in quite the same number of occurrences, number 1 appears a lot, a lot more (21% of the times). I tried the same code under CPython and the results are more homogeneous as each number seems to be choosen with a similar frequency (there is never a gap greater than 1% between the less frequent number and the most frequent number). 

**This is the result produced by the same code under cpython:**

1 : 8557 (17.1%)
2 : 8241 (16.5%)
3 : 8386 (16.8%)
4 : 8256 (16.5%)
5 : 8363 (16.7%)
6 : 8197 (16.4%)

I'm not a Python expert so I'm not sure if this is a bug. Maybe I should have used some "randomize" function before launching the script. Could you tell me if this is a normal behaviour, please ?

Thank you

**Comment by PierreQuentel** [comment]
Thanks for the report !

I gave up the random.py module and started a Javascript version (libs/random.js). Commit 2c7a1e22c3ec5aac4360548d73c05f65464d4e2b should fix this bug. Can you check ?

\- Pierre

**Comment by fmaida** [comment]
Thank you. I'll try the new source code tomorrow

**Comment by fmaida** [comment]
I just downloaded the master and tried it with the same source code; here are the new results for 50,000 dice throws:

STATISTICS ON 50000 DICE THROWS
-----------------------------
1 : 8236 (16.5%)
2 : 8228 (16.5%)
3 : 8447 (16.9%)
4 : 8484 (17.0%)
5 : 8218 (16.4%)
6 : 8387 (16.8%)


It's not only working perfectly, but it's also **blazing fast**. From brython.info it took almost 3 minutes to run it, while on this new version it took about half a second. Amazing! Thank you very much!

**Comment by PierreQuentel** [comment]
Good news, thank you for the feedback !
