### ISSUE TITLE
Can't `load` Swiper JS Library

### ISSUE THREAD

**Issue by goffi-contrib** [brython-dev/brython#2309]
Hello,

I'm using [Swiper](https://swiperjs.com) in my Brython-powered project, however since version `10.0`, I can't use `browser.load` anymore to load it.

This can be tested in Brython's official console:

```
>>> from browser import load,window
>>> load("https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js")
>>> window.Swiper
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
<class 'AttributeError'>: 'Javascript Window' object has no attribute 'Swiper'
```

However if I use version `9` or anterior, it works:
```
>>> from browser import load,window
>>> load("https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.js")
>>> window.Swiper
<class '__main__.J'>
```

Both tested on official Brython website with `Brython 3.12.0 on Netscape 5.0 (X11)`.

If you check https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js you can see that a `Swiper` var is defined with:
```
var Swiper=function(){[...]}();
//# sourceMappingURL=swiper-bundle.min.js.map
```
So I expect this to create the `Swiper` variable in `window` as in previous version. Note that it was defined in a different way in Swiper<10, but still it should work with latest version. So it looks like a bug in `load` implementation.

**Comment by denis-migdal** [comment]
Indeed, top level variables declared by `var` should have a global scope.

To fix it I assume there are 2 solutions :
- in the implementation of `load()`, add a new `script` tag instead of using `eval`.
- in the implementation of `load()`, after the execution of `eval`, fetch the new symbols defined in `this` ?

**Comment by PierreQuentel** [comment]
Until Swiper version 9, `eval(swiper_source)` would set `window.Swiper`, but it is no more the case in the newer versions. I'm afraid the blocking function `browser.load()` can't be used.

A solution is to use the ES6 module version of Swiper, and load it with `javascript.import_modules()`, which is asynchronous.

```python
from javascript import import_modules

swiper_url = "https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.mjs"

def callback(swiper):
    swiper.Swiper.new('.swiper', {
      'direction': 'vertical',
      'loop': True,

      # If we need pagination
      'pagination': {
        'el': '.swiper-pagination',
      },

      # Navigation arrows
      'navigation': {
        'nextEl': '.swiper-button-next',
        'prevEl': '.swiper-button-prev',
      },

      # And if we need scrollbar
      'scrollbar': {
        'el': '.swiper-scrollbar',
      }
    })

import_modules([swiper_url], callback)
```

**Comment by goffi-contrib** [comment]
Alright, thanks @PierreQuentel . If it's not possible with `load` I guess this issue can be closed.
