### ISSUE TITLE
Reading frame from null

### ISSUE THREAD

**Issue by BoryaGames** [brython-dev/brython#2320]
So, I have this code:
```python
from browser import aio

async def a():
  await ""
  try:
    info = ""
  except:
    ...
  b(info)

def b(info):
  print("ok")

aio.run(a())
```

Expected:
Get "ok" in console.

Got:
Python.js:10247 $import browser
Python.js:10248 use VFS ? true
Python.js:10249 use static stdlib paths ? true
Python.js:8601 handle error undefined undefined
Python.js:8602 stack []
Python.js:8603 TypeError: Cannot read properties of null (reading 'frame')
    at $B.resolve_local (Python.js:15647:24)
    at a5 (eval at $B.loop (Python.js:5214:12), <anonymous>:59:99)

This bug works if you await something, then create a variable in try, and use this variable as argument.

**Comment by denis-migdal** [comment]
Your code has an error, you can't await a string.

This should raise the following error :
```
TypeError: object str can't be used in 'await' expression
```

Indeed, I got some `$B.frame_obj is null` errors on the dev version in other cases.
Brython launches an error but is unable to print it due to `frame_obj` being null inside `show_error`.

**Comment by BoryaGames** [comment]
Used as an example, you can await anything and error will still exist.

**Comment by denis-migdal** [comment]
Errors seems to come from :
```
$B.resolve_local=function(name,position){
var frame=$B.frame_obj.frame # frame_obj seems to be null here.
```

Gotta investigate more.

**Comment by denis-migdal** [comment]
> Used as an example, you can await anything and error will still exist.

Not in the current dev version
```
from browser import aio

async def c():
    pass

async def a():
  await ""
  try:
    info = ""
  except:
    pass
  b(info)

def b(info):
  print("ok")

aio.run(a())
```

**Comment by denis-migdal** [comment]
`$B.promise = function(obj)` doesn't check the type of `obj`, and therefore returns an empty string which is then awaited.

But that doesn't raise an error in JS, so this isn't the thing that raises the observed error. Strange.

**Comment by denis-migdal** [comment]
`await $B.promise('')`
Is somehow setting `$B.frame_obj` to `null`.

**Comment by denis-migdal** [comment]
WTF I'm becoming crazy :
```javascript
        console.log('B', $B.frame_obj);
        let x = $B.promise('');
        
        console.log('Z', $B.frame_obj);
      await x;
        console.log('C', $B.frame_obj);
```

Prints :
```
B not null
<the messages printed inside promise()>
Z not null
C null
```

**Comment by denis-migdal** [comment]
Okay, I got it.

```javascript
  $B.$call($B.$getattr_pep657(locals___main__.aio, 'run', [0,0,7]), [4,4,12])($B.$call(locals___main__.a, [8,8,11])())
  console.log('out');
```
```
Z <not null>
out
C null
```

Somehow, when we call `await`, we leave `aio.run()`.

Which shouldn't be the case as JS promised are supposed to be eager (strange behavior).

**Comment by denis-migdal** [comment]
The bug is due to this WTF behavior of JavaScript. When we await in an async function, the behavior is not more eager, and the following code is executed :
``` javascript
foo = async function() { console.log("foo") }
faa = async function() { await foo(); console.log('faa') }
test = function() { faa(); console.log('test') }
```
```
foo
test
faa
```

This cause `await $B.promise("")` to make the Browser start executing the code after `aio.run()`, which likely set `$B.frame_obj` to `null`.

This may be partially due to the fact that `$B.promise` doesn't verify the type of its argument (in Python and exception is raised if we await a str). And therefore doesn't produce a `coroutine`.

**Comment by denis-migdal** [comment]
One possible fix could be to surround `await` like that :
```javascript
const frame_obj = $B.frame_obj
await ...
$B.frame_obj = frame_obj
```

But I assume this won't solve the fact that `aio.run()` returns too soon ?

**Comment by denis-migdal** [comment]
@PierreQuentel I may be wrong, but I may have found a solution to the inability of JS to wait inside synchronous functions :
WASM functions calls seems to be synchronous, and it seems we can synchronously wait inside WASM functions (sleep, mutex, etc).

If it works, it might solve some issues that Brython has.

**Comment by BoryaGames** [comment]
Yeah, it won't.

**Comment by denis-migdal** [comment]
I assume a solution would be to :
- depreciate `aio.run()` in the browser main thread as we have no way of blocking execution ;
- add a `aio.start()` that'd return a JS `promise` or a python `Future` (note: should we convert in jsobj2pyobj promise into Future ?) ?
- in WebWorker, change the behavior of `aio.run()` :
  - use [`Atomics.wait`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Atomics/wait) (?) for a synchronous wait.
  - I assume we have to execute the function inside another thread as a synchronous wait would prevents execution of the function.

**Comment by denis-migdal** [comment]
Another way to do so, is to change the architecture of Brython :

- By default execute all the code inside a WebWorker (which can synchronously wait when necessary).
- Do the DOM operations in the browser main thread, indicating which functions must be executed in the main thread with a decorator e.g. "@gui".
- Convert calls of "@gui" functions from the WebWorker and calls of WebWorker from "@gui" functions to an message (so with some limitations on the parameters we can send/receive...)
- Forbid WebWorker sync function calls from "@gui" function. And use `Atomics.wait` when calling sync "@gui" functions from WebWorker ?

OR the opposite using "@webworker" decorator.
OR using "@webworker" and "@gui", and functions without decorators would be in both side ?

But this would cause issue with shared data (SharedArrayBuffer only take binary data).

**Comment by denis-migdal** [comment]
@PierreQuentel I think this issue is not completely over :

```python
async def a():
     await ""
 
import asyncio as aio
aio.run(a())
```

Should produce the following error :
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "<stdin>", line 2, in a
TypeError: object str can't be used in 'await' expression
```


Moreover, as `aio.run()` is asynchronous according to the documentation, it should be renamed as `aio.start()` to have a correct semantic. Else, if we want to be close to asyncio API, then the name could be `aio.create_task()`.

**Comment by denis-migdal** [comment]
I also think you might have missing a `return` ?
```javascript
    var save_frame_obj = $B.frame_obj
    async function f(){
        await obj
        // restore frame obj
        $B.frame_obj = save_frame_obj
        return obj
    }
    f() // did you meant return f() ?
```

**Comment by PierreQuentel** [comment]
You are right Denis, `await ''` should have raised an error (in Javascript, it doesn't). The second fix should be ok. Can you confirm @BoryaGames ?

**Comment by BoryaGames** [comment]
Yes, everything ok. Thanks :)
