### ISSUE TITLE
Json Parse Error

### ISSUE THREAD

**Issue by IRACK000** [brython-dev/brython#2322]
#### Hi, I'd like to report about an error that I encountered related with Json Parsing.
I am not sure that the error I will mention is intened or not because that bug is kind of like implementation difference between CPython3 and Brython.

> Environment
> - Brython Version: 3.11.3
> - Module: json
> - User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Whale/3.23.214.10 Safari/537.36
> - JS Runtime: V8 11.8.172.16

I tried to load a json below:
<pre>
data = {
    "teams": ["Alpha", "Beta", "Gamma", "Delta", "Epsilo", "Zeta", "Eta", "Theta", "Iota"],
    "values": {
        "first": [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
        "second": [40.87381431445818, 16.728945099166428, 0.0, 33.860304685254383, 24.31733256682955, 0.0, 0.0, 0.0, 0.0],
        "third": [0.000000000000000, 23.771198620293188, 56.02184535786146, 33.860304685254383, 65.39235412474849, 0.0, 0.0, 74.21672894509916, 0.0],
        "final": [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    }
}
</pre>

with this code:
```python
dataset = json.loads(data)
```

But the result dict object is not what I expected.
![image](https://github.com/brython-dev/brython/assets/81044362/c1f1b27a-6641-4279-9004-f281dfa5066f)

---
All of datas typed as float weren't properly parsed while json loading and operating this way is not the way that CPython works.
What I tried to correct this is:
```python
dataset = json.load(raw_data, parse_float=lambda x: float(x))
```
And then I got well-converted data.
This is not a big bug and can be corrected with a simple solution to developers who uses brython but I think implementation difference with CPython3 may cause some unexpected logical error for many library.

Thank you for your contribution to the web community, and I look forward to hearing from you. Please let me know if the bug is not reproduced well.

V/R

**Comment by denis-migdal** [comment]
I do not reproduce this error on the current dev version :


```python
data = '{\n"teams": ["Alpha", "Beta", "Gamma", "Delta", "Epsilo", "Zeta", "Eta", "Theta", "Iota"],\n    "values": {\n        "first": [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],\n        "second": [40.87381431445818, 16.728945099166428, 0.0, 33.860304685254383, 24.31733256682955, 0.0, 0.0, 0.0, 0.0],\n        "third": [0.000000000000000, 23.771198620293188, 56.02184535786146, 33.860304685254383, 65.39235412474849, 0.0, 0.0, 74.21672894509916, 0.0],\n        "final": [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]\n    }\n}'


import json
dataset = json.loads(data)

print(dataset)
```

```
{'teams': ['Alpha', 'Beta', 'Gamma', 'Delta', 'Epsilo', 'Zeta', 'Eta', 'Theta', 'Iota'], 'values': {'first': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 'second': [40.87381431445818, 16.728945099166428, 0.0, 33.860304685254383, 24.31733256682955, 0.0, 0.0, 0.0, 0.0], 'third': [undefinede-16, 23.771198620293188, 56.02184535786146, 33.860304685254383, 65.39235412474849, 0.0, 0.0, 74.21672894509916, 0.0], 'final': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]}}
```

**Comment by PierreQuentel** [comment]
Thanks for the report @IRACK000 !

The commit referenced above should fix the issue, which was more apparent when using `console.log(json.loads(data))` than with `print(json.loads(data))`, where the only bug was the value printed as `undefinede-16`.

Of course the fix is only visible in the development version.

If it's ok for you can you close the issue ?

**Comment by IRACK000** [comment]
Yes, sure!
Thank you for your quick response😄
