### ISSUE TITLE
Error While Using built-in function 'reversed'

### ISSUE THREAD

**Issue by IRACK000** [brython-dev/brython#2323]
#### Hi, again. I splitted bug report even though this was occur with the same data that I mentioned in issue #2322 since this is not about json related problem.

For this bug, I am pretty sure that this way of operation is not intened and I failed to indicate the cause and to find a solution to fix this problem.

> Environment
> - Brython Version: 3.11.3
> - Module: built-in function
> - User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Whale/3.23.214.10 Safari/537.36
> - JS Runtime: V8 11.8.172.16

<pre>
data = {
    "teams": ["Alpha", "Beta", "Gamma", "Delta", "Epsilo", "Zeta", "Eta", "Theta", "Iota"],
    "values": {
        "first": [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
        "second": [40.87381431445818, 16.728945099166428, 0.0, 33.860304685254383, 24.31733256682955, 0.0, 0.0, 0.0, 0.0],
        "third": [0.000000000000000, 23.771198620293188, 56.02184535786146, 33.860304685254383, 65.39235412474849, 0.0, 0.0, 74.21672894509916, 0.0],
        "final": [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    }
}
</pre>

I tried to reverse the order of data['values'] and I use this code below:
```Python
dict(reversed(data['values'].items()))
```
But, this not works; just returns empty dictionary as the result.
I also tried with <code>reversed(list(data['values'].keys()))</code> to check the Brython does not support dictionary reversing but this also returns a empty list.
: So, my conclusion is: Brython has an error related built-in function 'reversed'

Please look over about this.
Thank you.

V/R

**Comment by IRACK000** [comment]
Oh, and list method .reverse() works fine, fortunately.

**Comment by denis-migdal** [comment]
I reproduced this error on the current dev version.

**Comment by PierreQuentel** [comment]
Thanks for reporting this bug @IRACK000 !
