### ISSUE TITLE
Cannot dynamically insert the brython.min.js/brython_stdlib.min.js by js

### ISSUE THREAD

**Issue by 15921483570** [brython-dev/brython#2327]
1. Prepare a blank html with `<header>` and `<body>`.

2. If the script `<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/brython@3.12/brython.min.js"></script>` is already in the html, then if I run the js code below in the console will print 666.

```js
const p = document.createElement('script');
p.text = `print("666")`;
p.type = "text/python";
p.async = false
document.body.appendChild(p);
```

3. If the `brython.min.js` is not in `<head>`, then if I run the js code below in the console will print only `s1`, without 666.

```js
var s1 = document.createElement("script");
s1.type = "text/javascript";
s1.src = "https://cdn.jsdelivr.net/npm/brython@3.12/brython.min.js"
s1.async = false;
s1.onload = function(e){console.log("s1")};
document.head.appendChild(s1);

const p = document.createElement('script');
p.text = `print("666")`;
p.type = "text/python";
p.async = false
document.body.appendChild(p);
```

Is there a way to dynamically import `brython.min.js` and python script to take effect?

**Comment by PierreQuentel** [comment]
You don't have to simulate the creation of a `<script>` tag, just run the Python source code with `__BRYTHON__.runPythonSource`:

```javascript
var py_code = `print("666")`

var s1 = document.createElement("script");
s1.type = "text/javascript";
s1.src = "/src/brython.js"
s1.async = false;
s1.onload = function(e){
  console.log("s1");
  __BRYTHON__.runPythonSource(py_code)
};
document.head.appendChild(s1);
```
