### ISSUE TITLE
New problem with array slicing

### ISSUE THREAD

**Issue by benjie-git** [brython-dev/brython#2341]
I'm using a webworker and sending messages between it and the main page.  I pass messages in the form ["command", *arg] in both directions, and then slice the list to get the command and the args.  When arriving at the main thread's onmessage, I receive evt.data as a list.  But when a message arrives at the webworker's onmessage, I receive evt.data as a javascript.Array.

This worked fine up through brython 3.12.0, but 3.12.1 is broken for me.  I narrowed the problem commit down to this one from October 11:

    https://github.com/brython-dev/brython/commit/ba6d67c8decfb424c746215979ed789ad29f158b

After this commit, when attempting evt.data[1:] when evt.data is a javascript.Array, I get the following error:

    TypeError: 'slice' object cannot be interpreted as an integer

I can work around this by using list(evt.data) and then my code works again.  Is this change intended?  If so I can leave in my workaround.

**Comment by PierreQuentel** [comment]
Thanks for the report Ben, and sorry for the regression...
