### ISSUE TITLE
Brython 3.20 adds an extra "/" to some paths

### ISSUE THREAD

**Issue by cetoli** [brython-dev/brython#235]
This circumvents some servers to find the module. Python server is lenient and finds it. GAE server fails with 404.

## Test Code

```python
from browser import ajax

```
### Expected
127.0.0.1 - - [31/Jul/2015 17:45:13] "GET /lib/brython320/brython.js HTTP/1.1" 200 -
127.0.0.1 - - [31/Jul/2015 17:45:14] "GET /lib/brython320/Lib/browser/ajax.py?v=0 HTTP/1.1" 200 -
127.0.0.1 - - [31/Jul/2015 17:45:14] "GET /lib/brython320/libs/_ajax.js?v=1 HTTP/1.1" 200 -
### Actual

**There is an extra slash before _Lib_**

127.0.0.1 - - [31/Jul/2015 17:45:13] "GET /lib/brython320/brython.js HTTP/1.1" 200 -
127.0.0.1 - - [31/Jul/2015 17:45:14] "GET /lib/brython320//Lib/browser/ajax.py?v=0 HTTP/1.1" 200 -
127.0.0.1 - - [31/Jul/2015 17:45:14] "GET /lib/brython320/libs/_ajax.js?v=1 HTTP/1.1" 200 -

## Test Environment

Brython version: 3.20

Ubuntu Gnome 14.04 - Firefox 39

**Comment by olemis** [comment]
Have you tested the version in master ?

**Comment by PierreQuentel** [comment]
The bug should have been fixed by commit d6e81374f245b77198c1a190319b94b6dbbfb194, pushed on July 5.

**Comment by cetoli** [comment]
I tested on the version downloaded from this link https://github.com/brython-dev/brython/releases/download/3.2.0/Brython3.2.0-20150701-214155.zip

**Comment by olemis** [comment]
I'm closing this ticket since this is working for me using latest version in master branch . Previous zip files are frozen . There is no hope in waiting for us to change them . Instead you can try to upgrade your Brython installation by either checking out master branch or waiting for next release .
