### ISSUE TITLE
Current brython is not caching main thread modules into indexedDB

### ISSUE THREAD

**Issue by benjie-git** [brython-dev/brython#2350]
My web app is ~18k lines of brython code, divided between the main thread and a web worker.  I compile it all into a brython_modules.js file, and use indexedDB cacheing.  In both dev and production, when running brython 3.11.3, my app loads in about under 1 sec, but takes over 2 sec to load when running 3.12.x (current master).

Once it's up and running, my brython code runs about 20% faster on 3.12.x.

When I inspect IndexedDB->brython-cache->modules I see that only the modules used by my web worker are being cached in indexedDB.  The modules used only by my main thread are not in the cache.

**Comment by PierreQuentel** [comment]
Thanks once again for the report Ben !

**Comment by benjie-git** [comment]
Thanks, with this fix, brython 3.12.x is now working just as well, and faster than 3.11.3 for me!
