### ISSUE TITLE
Problems with Babylon.js , looking for official support

### ISSUE THREAD

**Issue by KennyAWT** [brython-dev/brython#2351]
Hi, I'm working on a game with babylon.js but I've been having difficulty getting it to work with Brython. After a good time of trial and error I realize that babylon.js can only work up to version 3.8.9, after that we had special changes.

1) a complete rewrite of the generators implementation.
2) a rewrite of the interface with Javascript objects, mainly in the js_objects.js script
3) the json module, previously based on a slow pure Python package, is replaced by a much faster Javascript version

I think my problem is that Brython doesn't recognize Babylon objects, I think there is something wrong in point 2, or it's me who can't integrate babylon.js correctly.

I can be happy if it is possible to have an official support like Three.js or a sample (demos), how can I make this work or a possible solution in the next versions? Thank you !

**Comment by PierreQuentel** [comment]
Hi,

Thanks for the report. There is no official support of any specific Javascript framework, all of them should work with Brython, but you are right, there seems to be an issue with Babylon in previous versions.

Fortunately the latest Brython release supports it, I have tried an example from the Babylon tutorial an uploaded it [on the gallery](http://brython.info/gallery/babylon2_brython.html).

**Comment by KennyAWT** [comment]
Hello ,

It's good to know that I'm not the one who simply couldn't integrate Brython with babylon.js. I was trying with the latest version of Brython but I still have the same problem when I open the gallery, the Brython version still shows me a blank screen while the Babylon (javascript) version works brilliantly.

I hope to see more examples of this integration in the near future or some examples with the code.

These are some screen captures . Thank you ! 

![1](https://github.com/brython-dev/brython/assets/12687460/a4c4e8cc-c0f9-4964-88bc-d3046a8a6c13)
![2](https://github.com/brython-dev/brython/assets/12687460/d2c5a0d9-4fc6-45f5-a6ef-1d86c3c3f592)

**Comment by PierreQuentel** [comment]
There was an issue with CORS headers (not related to Brython), it should be ok now. Can you check ?

**Comment by KennyAWT** [comment]
It's still the same, with 3.8.9 it already works but with the latest version and the following ones it doesn't, the same with the gallery.

This time I was using different browsers, with the same result, white screen.

![1](https://github.com/brython-dev/brython/assets/12687460/123b16d7-2b9c-4423-ab57-5263cd76a4e3)
![2](https://github.com/brython-dev/brython/assets/12687460/6359c5e3-8b41-491b-a6cb-22069138dc48)

**Comment by PierreQuentel** [comment]
Sorry, I only tested on Firefox, but Chrome failed. The error messages suggest another cross-origin issue. I modified the tag to load the Babylon and jQuery scripts, the demo now works for me on Firefox, Chrome and Edge.

**Comment by KennyAWT** [comment]
yes , now its working fine :) in my browsers , this is the latest version from the cdn or from github ? because in github we have until Brython 3.12.1 build , or its the same  .

Thank you !

**Comment by PierreQuentel** [comment]
It's the latest version, 3.12.1.
Thanks again !
