### ISSUE TITLE
Bug in JSON on very small float number (e.g. 1e-06)

### ISSUE THREAD

**Issue by jibalamy** [brython-dev/brython#2355]
Hello,

I encounter a bug in Brython's JSON deserialization on float numbers expressed as negative exponential, for example:

>>> import json
>>> json.loads("1e-06")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "VFS.json/__init__.py", line 323, in loads
    return _json.loads(s,**kw)
JSONDecodeError: Extra data: line 1 column 6 (char 5)

The same example works well in plain Python.

Jean-Baptiste Lamy

**Comment by PierreQuentel** [comment]
Merci Jean-Baptiste !
