### ISSUE TITLE
[web site] `Standard distribution` link is 404

### ISSUE THREAD

**Issue by goffi-contrib** [brython-dev/brython#2359]
In current 3.12 version of the documentation in brython.info, the `Standard distribution` link leads to a 404 error, either in English or in French:

- https://www.brython.info/static_doc/3.12/en/stdlib.html
- https://www.brython.info/static_doc/3.12/fr/stdlib.html

If we replace `3.12` by `3.11` the page is there:
- https://www.brython.info/static_doc/3.11/en/stdlib.html

**Comment by PierreQuentel** [comment]
Merci Jérôme, je les ai téléchargés sur le site.
