### ISSUE TITLE
sys.excepthook() never terminates

### ISSUE THREAD

**Issue by jibalamy** [brython-dev/brython#2360]
Hello,

When calling sys.excepthook() after an exception is catched, it never terminates and the following of the code is never executed.

For example when running the following in Brython:

```
try:
  0/0
except:
  sys.excepthook(*sys.exc_info()); print("OK")
```

"OK" is never shown; while it is in plain Python.

Best regards,
Jiba

**Comment by PierreQuentel** [comment]
Thanks for the report @jibalamy !
