### ISSUE TITLE
JS error when passing a function to a math function

### ISSUE THREAD

**Issue by schmave** [brython-dev/brython#2361]
With the Brython online editor (v3.12.1), running the following code raises a JS exception.

```python
import math
def f(): 
    pass
math.sqrt(f)
```

CPython 3.12 raises this error: `TypeError: must be real number, not function`

This happens for almost all functions in the math library, not just sqrt. 

Thanks for taking a look!

**Comment by austin-schick** [comment]
`float(lambda: None)` throws the same error and prints the same message in the console. I think that may be one step closer to the root cause.
