### ISSUE TITLE
Brython 3.2.0 zip is missing jqueryui css tree

### ISSUE THREAD

**Issue by cetoli** [brython-dev/brython#237]
The zip version at https://github.com/brython-dev/brython/releases/download/3.2.0/Brython3.2.0-20150701-214155.zip
is missing Lib/jqueryui/css

3.1.0 is missing as well, did not check the other distribution files (3.1.1, 3.1.2, 3.1.3, tar.gz, tar.bz2 etc) , though

**Comment by PierreQuentel** [comment]
Thanks for the report. This is fixed for the next version.
