### ISSUE TITLE
to_dict() problem with float values

### ISSUE THREAD

**Issue by benjie-git** [brython-dev/brython#2371]
The following code makes a surprise conversion from a float to an empty dict, using the current brython code (and not in brython 3.12.1):

```python
import browser
a = '{"num":1, "val":2.3}'
o = browser.window.JSON.parse(a)
print(o.num, o.val)   # prints 1 2.3
print(o.to_dict())   # prints {'num': 1, 'val':  {}}
```

**Comment by PierreQuentel** [comment]
Thanks for the report Ben !

**Comment by benjie-git** [comment]
Thanks for the fix!  My ~20k line brython app is running smoothly and fast these days!
