### ISSUE TITLE
Getting a string field from a JSObject that starts with "class " raises an error

### ISSUE THREAD

**Issue by benjie-git** [brython-dev/brython#2373]
Getting any JSObject field containing a string that begins with "class " raises a TypeError

```python
a = '{"line": "class is in session"}'
o = context.JSON.parse(a)
print(o.to_dict()['line'])  # Prints "class is in session"
print(o.line)  # JavascriptError: TypeError: Cannot convert undefined or null to object
```

This is a wild one!

**Comment by denis-migdal** [comment]
This is indeed strange
```python
from browser import window

a = '{"line": "class is in session"}'
o = window.JSON.parse(a).to_dict()
print(o["line"]) 
```
is working.
It also works if we use `json.loads()`.

I also tested 
```python
from browser import window

a = '{"line": "class is in session"}'
o = window.JSON.parse(a)
print(o.to_dict()['line'])  # Prints "class is in session"
print(o.line)  # JavascriptError: TypeError: Cannot convert undefined or null to object
```
With other JS and Python reserved keywords, it works. Strange that the issue is only with "class".

If we do :
```python
from browser import window

a = '{"line": "class is in session"}'
o = window.JSON.parse(a)
print(o.to_dict()['line'])  # Prints "class is in session"
x = o.line
print(x)  # JavascriptError: TypeError: Cannot convert undefined or null to object
```
The error appear at line 6, so this is an issue while fetching the attribute.

If we `window.console.log(o)`, the JS object seems correct.

If we add a `"line2": "toto"`, `o.line2` works, but `o.line` still doesn't work.


This is indeed a strange one.

**Comment by PierreQuentel** [comment]
Thanks for the report. The cause was a test to determine if a Javascript object is a class, defined by the keyword `class`; the test was only if `obj.toString()` starts with the string "class ", without testing first if `type obj == 'function'`...

**Comment by denis-migdal** [comment]
> The cause was a test to determine if a Javascript object is a class, defined by the keyword `class`; the test was only if `obj.toString()` starts with the string "class ", without testing first if `type obj == 'function'`...

Wouldn't `a.__proto__ === Object.prototype` be a little more reliable ?

**Comment by PierreQuentel** [comment]
> Wouldn't `a.__proto__ === Object.prototype` be a little more reliable (for an object that isn't a class) ?

The [documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/proto) says that `obj.__proto__` is deprecated.

**Comment by denis-migdal** [comment]
> The [documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/proto) says that `obj.__proto__` is deprecated.

Indeed, it is now replaced by `Object.getPropertyOf(obj)`, i.e. `Object.getPropertyOf(obj) === Object.prototype`.

TBF, they won't remove `__proto__` as they need it for compatibility purposes. However, it wasn't added to Deno.
