### ISSUE TITLE
[BUG]  comparison chaining  |  unpacking assignment

### ISSUE THREAD

**Issue by kotnen** [brython-dev/brython#2374]
I found two somewhat major bugs in the Brython implementation of the Python language.

## 1. Comparison chaining

From the Python documentation ([§6.10](https://docs.python.org/3/reference/expressions.html#comparisons)):
> Comparisons can be chained arbitrarily, e.g., x < y <= z is equivalent to x < y and y <= z, except that y is evaluated only once (but in both cases z is not evaluated at all when x < y is found to be false).
> Formally, if a, b, c, …, y, z are expressions and op1, op2, …, opN are comparison operators, then a op1 b op2 c ... y opN z is equivalent to a op1 b and b op2 c and ... y opN z, except that each expression is evaluated at most once.

According to the previous excerpt, the expression `a in b == c` should be equivalent to `a in b and b == c`.  And indeed, CPython evaluates the expression as such.  However, Brython incorrectly evaluates this as `a in (b == c)`.

## 2. Unpacking assignment

Brython for some reason breaks when a star name is used in a position other than the last in an unpacking assignment.  For example,
```py
a, *b = [] # this should fail (and it does), because there aren't enough elements in the iterable

a, *b = [1] # Brython accepts this, because the star name is in the last position

*a, b = [1] # CPython accepts this, but Brython doesn't.
            # Brython fails with the error "ValueError: not enough values to unpack (expected 2, got 1)"

a, *b, c = [1, 2] # CPython accepts this, but Brython doesn't.
                  # Brython fails with the error "ValueError: not enough values to unpack (expected 3, got 2)"
```

I'm not sure why this happens, but I'd guess that it's because the star name checking is special-cased to look at the last position only, instead of looking in all of the positions as it should.

##
If you have any questions, or need more details, please don't hesitate to ask me, as I'm happy to help out.

##
Cheers from Canada.

**Comment by PierreQuentel** [comment]
Hi @kotnen,

Thanks for the reports !

The commit referenced above fixed the second bug. 

I could reproduce the first one with the current release (3.12.1) on brython.info, but it is fixed in the current development version (as a consequence of the new parser implementation).

**Comment by kotnen** [comment]
Hello @PierreQuentel,

I'm glad to know that the report was helpful!  I'll go ahead and close this issue now, since both issues are fixed.

Cheers from Canada.
