### ISSUE TITLE
Error creating a Protocol class with a collections.abc base class

### ISSUE THREAD

**Issue by tjnaughton** [brython-dev/brython#2375]
Hi,

When using structural subtyping (in the context of static type checking) a subprotocol can be defined using multiple protocol base classes. Brython seems to support this, and raises an appropriate exception if a non-protocol base class is used, such as `int`.

```
Brython 3.12.1 on Netscape 5.0 (X11; Ubuntu)
Type "help", "copyright", "credits" or "license" for more information.
>>> from typing import Protocol
>>> class AnotherP(Protocol): pass
>>> class MySubP(AnotherP, Protocol): pass  # no TypeError, as expected
>>> class MySubP(int, Protocol): pass  # TypeError, as expected
File "<stdin>", line 1, in <module>
  File "VFS.typing.py", line 1806, in __new__
    raise TypeError(
TypeError: Protocols can only inherit from other protocols, got <class 'int'>
>>> 
```

However, according to the Python docs (https://typing.readthedocs.io/en/latest/spec/protocol.html#merging-and-extending-protocols)) some (possibly all -- it's not clear from the docs) abstract base classes in `collections.abc` can be regarded as protocols in the context above. So the following exception raised by Brython is inconsistent with Python:

```
Brython 3.12.1 on Netscape 5.0 (X11; Ubuntu)
Type "help", "copyright", "credits" or "license" for more information.
>>> from typing import Protocol
>>> from collections.abc import Sized
>>> class MySized(Sized, Protocol): pass
File "<stdin>", line 1, in <module>
  File "VFS.typing.py", line 1806, in __new__
    raise TypeError(
TypeError: Protocols can only inherit from other protocols, got <class '_collections_abc.Sized'>
>>>
```

These statements do not raise an exception with Python:

```
Python 3.12.1 | packaged by Anaconda, Inc. | (main, Jan 19 2024, 15:51:05) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from typing import Protocol
>>> from collections.abc import Sized
>>> class MySized(Sized, Protocol): pass
... 
>>> 
```

Great work, Brython is an amazing achievement!

**Comment by PierreQuentel** [comment]
Thanks for the report and for the kind words !

The issue was caused by an incorrect setting of classes attribute `__module__` when the module explicitely defines a `__name__`.
