### ISSUE TITLE
'alias' parameter of the 'import_js' function from the 'javascript' module is no more recognized

### ISSUE THREAD

**Issue by epeios-q37** [brython-dev/brython#2382]
Hello,

By testing #2381, I came across following problem.

The code used for testing:
```python
import javascript, browser

javascript.import_js("atlastk_20240209.js", alias="atlastkjs")

browser.alert("Success")
```

The 3.12.**1** link: https://faas.q37.info/brython/?version=3.12.1&code=import%20javascript%2C%20browser%0A%0Ajavascript.import_js(%22atlastk_20240209.js%22%2C%20alias%3D%22atlastkjs%22)%0A%0Abrowser.alert(%22Success%22)

Clicking on *Run* displays "Success.", meaning the importation was successful.

The 3.12.**3** link: https://faas.q37.info/brython/?version=3.12.3&code=import%20javascript%2C%20browser%0A%0Ajavascript.import_js(%22atlastk_20240209.js%22%2C%20alias%3D%22atlastkjs%22)%0A%0Abrowser.alert(%22Success%22)

Clicking on *Run* displays an error message. It seems that there is a problem with the `alias` parameter.

Same problem with the development version.

**Comment by PierreQuentel** [comment]
The commit above should fix the bug. You can make your code work by passing the alias as a positional argument instead of keyword : `javascript.import_js("atlastk_20240209.js", "atlastkjs")`
