### ISSUE TITLE
Scroll to "end" of block instead of default "start"

### ISSUE THREAD

**Issue by ondrejj** [brython-dev/brython#2383]
Brython console on brython.info looks good, when running on a large page. When using on smaller page, automatic scrolling always scrolls to currently typed command and result of previous command is hidden. Same problem for inspector, this problem is present also on larger monitors, because documentation page is large.

You can avoid unnecessary scrolling by using block=end or block=nearest attribute, for example:

`self.zone.lastChild.scrollIntoView({"block": "end"})`

Also for some situations it would be nice to have behavior="smooth" ability for console output. Consider adding this as option or at least ability to override on Interpreter class.

Thank you.

**Comment by PierreQuentel** [comment]
Thanks for the suggestion @ondrejj , it looks better this way !
