### ISSUE TITLE
Importing the 'html' module raises an error

### ISSUE THREAD

**Issue by epeios-q37** [brython-dev/brython#2386]
Hello,

I have following error when importing the *html* module:

```
Traceback (most recent call last):
  File <string>, line 1, in <module>
  File VFS.html/__init__.py, line 6, in <module>
    from html.entities import html5 as _html5
JavascriptError: ReferenceError: SurrogatePair is not defined
```

To reproduce the error: https://brython.info/tests/editor.html?code=import%20html

Occurs with the development version too.

**Comment by PierreQuentel** [comment]
Merci !

**Comment by manatlan** [comment]
got the same error

**Comment by PierreQuentel** [comment]
You are using the latest release, 3.12.2. The fix applies to the current development version, and will be available in the next release.

In the meantime you can use the development version instead of the current release
```xml
<script src="https://raw.githack.com/brython-dev/brython/master/www/src/brython.js"
        crossorigin="anonymous">
</script>
<script src="https://raw.githack.com/brython-dev/brython/master/www/src/brython_stdlib.js"
        crossorigin="anonymous">
</script>
```
