### ISSUE TITLE
Improve precompile tool

### ISSUE THREAD

**Issue by olemis** [brython-dev/brython#239]
Implemented in #222 . Further details TBD .

**Comment by glyph** [comment]
Still waiting for those further details :). I tried a few things but could not get it to work at all. How am I supposed to run this?

**Comment by olemis** [comment]
There is [simple pre-compilation tool](https://github.com/brython-dev/brython/tree/master/www/tests/precompile.html) aimed at translating Python code to its internal js equivalent . You should be able to use it to build your own [VFS file](https://github.com/brython-dev/brython/blob/master/www/tests/test_pyc.vfs.js) that you can [load](https://github.com/brython-dev/brython/blob/master/www/tests/test_import.py) afterwards.

Regarding improvements , we are the ones waiting for users to tell us what needs to be improved in the pre-compilation workflow .

**Comment by glyph** [comment]
@olemis - I'm still a bit lost.

> There is a simple pre-compilation tool aimed at translating Python code to its internal js equivalent . You should be able to use it to build your own VFS file that you can load afterwards.

It looks like `precompile.html` just works on a single python module pasted into a text field on a web page.  The tricky part, for me, is getting this code to run in an environment that can see the *actual* filesystem, where my `pip install`'ed files live, and convert them into a `.vfs.js`; pasting hundreds of modules into a text field is a non-starter.  I am not really sure how to get started with `node.js` to run this, since `scripts/node_bridge.js` just gives me this error when I start it:

```
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '../src/brython.js'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.<anonymous> (.../Brython/scripts/node_bridge.js:31:13)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
```

**Comment by glyph** [comment]
> Regarding improvements , we are the ones waiting for users to tell us what needs to be improved in the pre-compilation workflow .

Well, if you are waiting :smile: , here is what *I* want from the pre-compilation workflow: 

```console
$ mkvirtualenv -p `which python3` my-brython-project
$ . my-brython-project/bin/activate
$ pip install brython
$ pip install foo
$ pip install bar
$ pip install baz
$ cat > my_project.py
import foo
import bar
import baz
def do_fun_brython_stuff():
    "use foo, bar, baz..."
^D
$ brythonify --package=foo --package=bar --package=baz --script=my_project.py --output=my_project.vfs.js
$ cat > my_project.html
<html>
<script src="my_project.vfs.js" />
<body onload="brython()">
</body>
</html>
^D
$ scp my_project.html my_project.vfs.js my-server.example.com:
$ open https://my-server.example.com/my_project.html
```

**Comment by glyph** [comment]
To explain that workflow a bit better: I want to be able to have a tool which does all the work of enumerating all the Python files that need to be translated, translating them, putting them into a `.vfs` file, and including `brython.js` itself, possibly.  I want it to be distributed via `pip`, as a regular python package, not something I have to `git clone` myself.

I would work on this myself, except I can't figure out how to get to the basic first level of what `node_bridge.js` is supposed to do, allowing me to run brython code in a command-line context.  If I could do that, I could happily put together a Python program (run with CPython or PyPy) which could feed each module to a VFS builder.

**Comment by glyph** [comment]
Is there any more documentation on this yet?

**Comment by olemis** [comment]
I've not been able to take a look into this yet . Sorry . I'm hoping to have time to do something about it in the next few days .

**Comment by glyph** [comment]
Thanks for the update!  No need to apologize; I know open source is hard.  I am *very* excited to see what you come up with :).

To maybe refine that workflow a little bit:

```
$ mkvirtualenv -p `which python3` my-brython-project
$ . my-brython-project/bin/activate
$ cat requirements.txt
brython==999.999
foo==1.0
bar==2.6
baz==3.7
$ pip install -r requirements.txt
$ cat > my_project.py
import foo
import bar
import baz
def do_fun_brython_stuff():
    "use foo, bar, baz..."
^D
$ brythonify --requirement=requirements.txt --script=my_project.py --output=my_project.vfs.js
$ cat > my_project.html
<html>
<script src="my_project.vfs.js" />
<body onload="brython()">
</body>
</html>
^D
$ scp my_project.html my_project.vfs.js my-server.example.com:
$ open https://my-server.example.com/my_project.html
```

Even better would be for `my_project` to have its own `setup.py` that describes it as a package, just as if I were doing a server-side Python app.  The key thing is to provide the same kind of tooling that `pip` provides, or piggyback on `pip` as much as possible, to include everything from a particular setuptools "distribution", and only do optimization (pruning unused modules, for example) after things are already working well.

**Comment by trengere** [comment]
is it not possible to precompile list comprehension (eg [i*i for i in range(10)])
i am using the 'test/precompile.html' tool
or am I doing something wrong...
works if i translate it to 

res = []
for i in range(10):
    res.append(i*i)

**Comment by PierreQuentel** [comment]
I think we can close this thread, #491 also deals with precompilation.
