### ISSUE TITLE
Serious string formatting error with floats

### ISSUE THREAD

**Issue by stroobandt** [brython-dev/brython#2403]
In the [online Brython console](https://brython.info/tests/console.html?lang=en), type the following statement:

    '%.*E' % (1, 0.9999)

It yields: `'1.0E-02'`

Doing the same in `ipython` (v3.8.10) yields the correct answer, which is of course: `'1.0E+00'`

This error will seriously upset scientific results and should receive priority attention from the debugging team!

**Comment by stroobandt** [comment]
Another example:

    float('%.3g' % 9.99999e-06)

Brython yields: `1e-07`

Whereas iPython correctly yields: `10E-6`

**Comment by PierreQuentel** [comment]
Thanks for the report @stroobandt !
