### ISSUE TITLE
Uncaught SyntaxError: Identifier 'nonlocal_stmt_type' has already been declared (at brython.min.js:1:1)

### ISSUE THREAD

**Issue by shawnmcpeek** [brython-dev/brython#2405]
I apologize if this is addressed elsewhere as this is my first time using brython. In my index.html I added the cdn links as instructed.
In my python_dev.component.jsx I have the following block of code:
  useEffect(() => {
    if (selectedProject) {
      const scriptElement = document.createElement("script");
      scriptElement.src =
        "https://cdn.jsdelivr.net/npm/brython@3/brython.min.js"; // Brython CDN URL
      scriptElement.onload = () => {
        window.BrythonRunner = {
          runScript: (script) => {
            window.__BRYTHON__.run_script(script);
          },
        };
      };
      document.body.appendChild(scriptElement);
    }
  }, [selectedProject]);
  
 I do the following steps:
 npm start (to start react)
navigate to python dev page- click on a card:
I get an error in the window and the console says:
Uncaught SyntaxError: Identifier 'nonlocal_stmt_type' has already been declared (at brython.min.js:1:1)

It seems like an issue with a file in cdn, but I could also be completely wrong. 

Here is a link to the github [https://github.com/shawnmcpeek/newdevsite](url)

**Comment by PierreQuentel** [comment]
Hi Shawn,

The message suggests that the Brython engine is already loaded in the page. You can add a test at the beginning of `useEffect()`, something like

```javascript
    if (selectedProject) {
      if(window.__BRYTHON__){
        window.BrythonRunner = {
          runScript: (script) => {
            console.log('run script', script)
          },
        };
        return
      }
```

Inside `runScript`, you cannot use `__BRYTHON__.run_script()` the way you do. You should first get the source code of the Python script (`ping.py` for instance), then execute it with  `__BRYTHON__.runPythonSource(src)` as explained in the [documentation page](https://brython.info/static_doc/3.12/en/jsobjects.html).

Don't hesitate to comment again if there is still something not working as you expect.

**Comment by shawnmcpeek** [comment]
@PierreQuentel That did help, a lot, thank you. I am not getting that error, so that is a lot of progress. 

If you can help me, that'd be great.  As you can probably see in my repository, I am running react, and I have a jsx. On this are cards for each project I want to show off. When a user clicks a card, it tells them more about the certain project, and has a "run script" button. What I want is that they click "run script" and a window opens running the python script. It isn't doing this and all I'm getting is frustrated.  Any advice?

**Comment by PierreQuentel** [comment]
After a few trials I could make the Disney quiz work.

You have to move the Python scripts (here `quizgame.py`) in the folder `public` so that a fetch to the url _http://localhost:3000/quizgame.py_ returns the file content.

Then edit your code to
```javascript
window.BrythonRunner = {
  runScript: (script) => {
    var url = 'http://localhost:3000/' + script.substr(2)
    window.fetch(url).then(
        function(resp){
            resp.text().then(window.__BRYTHON__.runPythonSource)
        }
    )
  },
};
```

You will have to adapt your scripts to the browser context, but this is another story...

Hope this helps !
