### ISSUE TITLE
Error getting attribute DOMEvent.data, in iOS browsers with iOS<16.0

### ISSUE THREAD

**Issue by benjie-git** [brython-dev/brython#2409]
In my main app and web workers, I bind the 'message' event to a method, and get the event's data attribute.  This works on Chrome, and the latest Safari, but as of recent brython, this no longer works in older iOS browsers (all of which are WebKit/Safari based).

I try to run:
```python
    def OnMessage(self, evt):
        data = evt.data  # This crashes
        ...

```

I get a `ReferenceError: Can't find variable: Worker` coming from py_dom.js: line 354

```javascript
            }else if(ev.target instanceof Worker){
```

when I change this line to:

```javascript
            }else if(typeof Worker !== 'undefined' && ev.target instanceof Worker){
```

then it works again in older iOS Safari browsers.

**Comment by PierreQuentel** [comment]
Thanks Ben !
