### ISSUE TITLE
Function modifying original arguments value

### ISSUE THREAD

**Issue by aaronmatenga** [brython-dev/brython#241]
When I pass in an argument to a function and then return a value, it's actually modifying the original value, even if I give them different names inside the function.

Here is an example:

```
# Function to force numeric input
def force_number(message):
  while True:
    try:
      number = float(input(message))
      break
    except ValueError:
      print("Please enter a number!")
      
  return number
 
#This function calculates the price after a discount and returns it. It takes 2 parameters: price and discount.
def calc_discount(price, discount):
  #Turn the discount % into a decimal
  discount_value = discount / 100 
  
  #Calculate the amount to discount and take off price
  discount_amount = price * discount_value
  price -= discount_amount
  
  return price
  
#Ask the user for the price and discount amount
price = force_number("Please enter the price of the item e.g. 29.99: ")
discount = force_number("Please enter the % discount e.g. 10: ")
 
#Calculate new price and inform the user
new_price = calc_discount(price, discount)
print("The new price after a {:.1f}% discount on ${:.2f} is: ${:.2f}.".format(discount, price, new_price))
```

If I run this code and put a $25 price and a 10% discount, it will output the following:
"The new price after a 10% discount on $22.50 is $22.50"
when it should display:
"The new price after a 10% discount on $25.00 is $22.50"
So the variable "price" that is being passed into the function "calc_discount" has been modified.

Also, if I modify the "force_number" function to return a literal number (e.g. 25) then the program will work as expected.

**Comment by PierreQuentel** [comment]
I can't reproduce the bug with the current version on the repository, I get the expected result. Which version are you using ?

It reminds me of a very embarrassing bug with floats (#203) but it was fixed a few weeks ago.

**Comment by aaronmatenga** [comment]
Oh, yup. It's working.

Thanks
