### ISSUE TITLE
[BUG]  Errors in the new parser

### ISSUE THREAD

**Issue by kotnen** [brython-dev/brython#2410]
I have found two bugs in the new parser:

1. `JavaScriptError: ReferenceError: SurrogatePair is not defined` is raised when using `"\U"` unicode string escapes for values bigger than `"\U0000FFFF"`.
2. `JavascriptError: ReferenceError: $token is not defined` is raised when using escapes (such as `"\u"`, `"\x"`, etc.), if not all of the arguments aren't provided.  For example, `"\u"`, `"\Uabc"`, etc.

**Comment by PierreQuentel** [comment]
Thanks for the report @kotnen !

The first bug exists in the latest release but was fixed since. The commit referenced above fixes the second one.
