### ISSUE TITLE
Still can not import "local" files in webworker code

### ISSUE THREAD

**Issue by shlomil** [brython-dev/brython#2412]
This issue is a duplicate for issue #2402 which was closed and can't be reopened.
Webworker throws the same error upon import, tested on latest devel branch 70a2145

**Comment by PierreQuentel** [comment]
It's strange, I tried with this code and got no error:

```xml
<!doctype html>
<html>
<head>
<meta charset="utf-8">

<script src="https://raw.githack.com/brython-dev/brython/master/www/src/brython.js"
        crossorigin="anonymous">
</script>
<script src="https://raw.githack.com/brython-dev/brython/master/www/src/brython_stdlib.js"
        crossorigin="anonymous">
</script>

</head>
<body>

<script type="text/python" class="webworker" id="worker">
from browser import bind, self
from some_module import some_func

@bind(self, "message")
def message(evt):
    result = 'pong' if evt.data == 'ping' else evt.data
    workerResult = f'Result: {result}'
    self.send(workerResult)

</script>

<script type="text/python">
from browser import worker

def ready(w):
  print('ready')
  w.send('ping')

def message(ev):
  print(ev.data)

worker.create_worker("worker", onready=ready, onmessage=message)
</script>

</body>
</html>
```
The page is loaded by an http request, not by opening the local file.

**Comment by shlomil** [comment]
The exact above code fails for me. This probably needs further investigation...

So more details:
If I change the script source to jsdeliver's brython 3.12.2 it doesn't fail.
I'm testing on my localhost using a python3 commandline single line webserver ... no https - might be related to some restrictions on webworders? OTOH 3.12.2 still works fine.
chrome version: Version 122.0.6261.128 (Official Build) (64-bit)
Think of any other information that might be helpful?

*(yes, ofcourse it's not a local file, I should have written that it's simulating including "local file")

**Comment by PierreQuentel** [comment]
I have uploaded [the page](http://brython.info/tests/issue2412/issue_2402.html) on the Brython site. It works for me, tested on Firefox, Chrome and Edge.

**Comment by shlomil** [comment]
and [this is the same but with 3.12.2](https://lobogen.com/issue_2402_3.12.2.html) that works on all cases

**Comment by PierreQuentel** [comment]
I think I got it, there was a bug when the html page is located at server root. Can you try with the latest version ?

**Comment by shlomil** [comment]
Yes, indeed. 
I can confirm that the latest vertion form git solved the issue on both my localhost and on remote.
Thank you very much :)
