### ISSUE TITLE
Recent commit breaks modifying jsObject from brython code

### ISSUE THREAD

**Issue by benjie-git** [brython-dev/brython#2420]
Starting with this commit: https://github.com/brython-dev/brython/commit/7ad09ad18f833744f291995ced224ad707a90e45

My code no longer runs correctly.  I'm still trying to figure out exactly what is going wrong, but here is an example:

I call into a js library to get a menubar definition (a map/dict of names to menu items, and sub-items).  I change the sub-items list of one of the menu items, and call the library's update() method to rebuild the menubar.  This works before the above commit, but afterwards the library does not see the changes to the menu sub-items.  Maybe my brython code is receiving a copy of the dict, so changes to it aren't reflected in the js library's copy?

I'll try to put together a minimal test case, but I don't have much time right now.

**Comment by moepnse** [comment]
Hello @benjie-git! Can you please provide us with a small example that reproduces the error?

Thank you!

**Comment by benjie-git** [comment]
Ok, I finally have an example / test case for this one.  In recent brython versions, since the commit referenced above:

I can run the following JS:
```javascript
window.jsObj = {item: {}};
window.GetTest = function () { return window.jsObj; };
window.PrintTest = function () { console.log("JS:", window.jsObj.item['sub']); };
```

and then the following brython:
```python
from browser import window

window.GetTest().item = {'sub': []}
window.GetTest().item['sub'] = [1, 2]
print("Py:", window.GetTest().item['sub'])
window.PrintTest()
```

and I get:
```
Py: [1, 2]
JS: []
```

but they should both show `[1, 2]`.

**Comment by benjie-git** [comment]
This issue is fixed when I remove these two newly added lines:

```python
pyobj[JSOBJ] = jsobj
jsobj[PYOBJ] = pyobj
```

[from here](https://github.com/brython-dev/brython/commit/7ad09ad18f833744f291995ced224ad707a90e45#diff-766a8e6709ecee5361c7b50b15c4290cab5e2d386ef1512be99eda2ad5521753R291).

But I imagine that breaks the issue that they were added to fix.

**Comment by benjie-git** [comment]
This is still broken for me using the latest brython code.

**Comment by PierreQuentel** [comment]
Sorry about that. It should be ok now.

**Comment by benjie-git** [comment]
This test case was fixed, but I still have a related problem.  I'm using a js library function that takes a JSObject, and fails if it contains unknown fields.  When I pass a brython dict into this js function, it fails because although it still sees the intended fields, it also finds an additional, and unexpected 'Symbol(PYOBJ)' field.

**Comment by PierreQuentel** [comment]
Interesting... Usually symbols don't appear when iterating on an object's keys. Can you tell me which library it is so that I can reproduce the issue ?

**Comment by benjie-git** [comment]
This is coming up when using the ace js text editor, when I send back results to the provided callback after I generate results from a request for an autocomplete list.  But it's easy to reproduce without using that library:

I can run the following JS:
```javascript
window.PrintObj = function(o) {
    console.log(o);
}
```

and then the following brython:
```python
from browser import window

o = window.Object.new({"value": 1})
window.PrintObj(o)
```

and I get:
```
{value: 1, Symbol(PYOBJ): {…}}
```

whereas using previous versions of brython, I get:
```
{value: 1}
```

**Comment by benjie-git** [comment]
Or if this new behavior of including this symbol when passing a dict to a js function is intended, I can work around it with a js function to clean the object of symbol fields in the rare case that the js function cares.

**Comment by PierreQuentel** [comment]
With the commit above, no extra attribute is added to the Javascript object. Hopefully this will fix the issue.

The solution is not optimal since it uses a JS Map as a mapping between the JS object and its Python corresponding object, which might lead to memory issues. But I hope that the use case will not be too frequent. If there is a better solution I am all ears !

**Comment by benjie-git** [comment]
This is very interesting.  This fix did not help, so I dug more into what's happening inside the ace js library.  After the commit that this issue is originally discussing (https://github.com/brython-dev/brython/commit/7ad09ad18f833744f291995ced224ad707a90e45), this js library callback receives an array of brython dicts, instead of an array of js objects.  Before that commit, it correctly receives js objects.

This means that the problem I'm seeing now is not due to the Symbol(PYOBJ) field in the js object, it's that these js objects are being converted back to brython dicts while calling the js callback, so I think you can safely revert your last change adding the JS Map.  (Yay!)  And I'll try to figure out what is so special about this library that is causing the problem.  I haven't been able to put together a simple test case that shows this problem yet.

In my brython code, I run:
```python
# acList is a list of stings
# callback is a js function I received earlier, to which I must send a list of objects, each with a "value" field.
compData = [window.Object.new({"value": w}) for w in acList]
# at this point in both older and newer brython, compData is a nice clean list of js objects
callback(javascript.NULL, compData)
# but since the problem commit, the callback() function receives a list of brython dicts, so brython must be converting
# the js objects back to brython dicts during this call -- but only the copy passed into the callback function.  
# locally, compData is still an array of js objects.  And when I try this by calling my own functions in 
```

But if instead, I create and pass in a js Array of js Objects, it does not get converted, and works normally.  This workaround is actually fine for me, although I feel that some edge case is still very slightly broken.
```python
compData = window.Array.new(*[window.Object.new({"value": w}) for w in acList])
callback(javascript.NULL, compData)  # Works as expected
```

**Comment by PierreQuentel** [comment]
Another attempt in commit [239647b](https://github.com/brython-dev/brython/commit/239647b0349fc9f4a8fec69778bdee0aafaba233)

**Comment by benjie-git** [comment]
Yes!  This fixed the issue for me.  Thank you again!

**Comment by PierreQuentel** [comment]
Yippee !
