### ISSUE TITLE
`<Javascript undefined>` when parameter name starts with double underscore in methods

### ISSUE THREAD

**Issue by hardcore-sushi** [brython-dev/brython#2434]
The following code produces a strange `<Javascript undefined>`:
```py
class A:
    def f(self, __v):
        print(__v)

A().f(1)
```
I noticed it only happens when the parameter name starts with `__`. However functions defined outside classes work fine.

**Comment by PierreQuentel** [comment]
Thanks again Matéo. It was a bug in the implementation of Python "name mangling".
