### ISSUE TITLE
Cannot convert sting to UTF16

### ISSUE THREAD

**Issue by mbasaglia** [brython-dev/brython#2438]
I'm struggling with encoding strings to UTF16.

If I try this
```py
"a".encode("utf_16_le")
```
I get 
```
TypeError: 'utf_16_le' codec returns UndefinedType, not bytes
```

(I get the same error by using the `bytes` constructor)

Encoding to UTF8 works fine though

**Comment by PierreQuentel** [comment]
Thanks for the report @mbasaglia !

The commit fixes the bug and also implements utf_16_be and utf-32 encoding / decoding, but still some work ahead (error handling among others).
