### ISSUE TITLE
How to test stuff from src/Lib/test/* ?

### ISSUE THREAD

**Issue by alanjds** [brython-dev/brython#244]
Hi.

I saw that [text_xmlrpc.py](https://github.com/brython-dev/brython/blob/master/www/src/Lib/test/test_xmlrpc.py) got added on commit https://github.com/brython-dev/brython/commit/7b9ead9f30030c8ccf336e939f0b4cff02ec2fd1. How can I run it as a test?

I tried the steps on .trevis.yml, but is not testing this stuff for now.

**Comment by olemis** [comment]
I'm working on this in a separate branch . For the moment , please, follow ticket #240 .

**Comment by olemis** [comment]
Anyway , it should be possible to do so by executing in the console code similar to this .

```
>>> from unittest.loader import defaultTestLoader
>>> suite = defaultTestLoader.loadTestsFromName('test.test_xmlrpc')
Traceback (most recent call last):
AttributeError: 'module' object has no attribute 'test_xmlrpc'
```

Unfortunately at present it crashes . 

```
>>> import test.test_xmlrpc
Traceback (most recent call last):
ImportError: test.test_xmlrpc
>>> 
```

**Comment by alanjds** [comment]
Thanks.
