### ISSUE TITLE
Question about input event

### ISSUE THREAD

**Issue by clach04** [brython-dev/brython#2444]
From reading https://brython.info/static_doc/3.12/en/keyboard_events.html I can see keyboard events. When I read the first entry I'm reading there is some sort of input has changed (in form/document), am I misreading this?

> `input` 
> triggered when the value of an <input> or <textarea> element is modified, or the content of a `contenteditable` element is modified

I'd love to be able to make use of this, for now I'm traping keyboard events and then checking for Enter, this feels overly complicated.
* my change https://github.com/clach04/brython_tip_calc/commit/48ba56ce60b8bc8c4f87fa7f8e1d0d6231fce8da
* my app https://clach04.github.io/brython_tip_calc/

**Comment by PierreQuentel** [comment]
This paragraph was written long ago, maybe "input" was a keyboard event then, but the current [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent) doesn't mention it now. I have removed it from the Brython doc page.

You might want to use the ["beforeinput" event](https://developer.mozilla.org/en-US/docs/Web/API/Element/beforeinput_event)
