### ISSUE TITLE
setTimeout type change

### ISSUE THREAD

**Issue by shark-in-a-hat** [brython-dev/brython#2445]
I'm not sure if this is a bug, or just the consequence of Javascript and Python clashing, but it gave me some headache and a hard-ish to debug problem. Here's a sample code:
```<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <script type="text/javascript" src="brython.js"></script>
    </head>
    <body>
        <script type="text/python">
            from browser import window as win

            def is_bomb(point):
                bombs = [(1,2), (3,4)]
                if point in bombs:
                    print('BOOM!')
                else:
                    print('You are safe.')    

            win.setTimeout(is_bomb, 100, (1,2))
        </script>
    </body>
</html>
```

Running this will print out 'You are safe.' because the (1,2) Python tuple is turned into a Javascript Array and while that array holds the same data as the original tuple it is not the same (at least for membership tests). 

This was quite unexpected for me, especially that if you pass an instance of a custom class to setTimeout it will preserve it:
```python
from browser import window as win

class Foobar:
    def __init__(self, value):
        self.value = value                

    def __repr__(self):
        return f'Foobar object holding a: {self.value}'       

def print_type(thing):
    print(type(thing))            

win.setTimeout(print_type, 100, Foobar((1,2))) #<class '__main__.Foobar'>
win.setTimeout(print_type, 200, tuple((1,2)))  #<class 'javascript.Array'> 
win.setTimeout(print_type, 300, list((1,2)))   #<class 'javascript.Array'>
win.setTimeout(print_type, 400, set((1,2)))    #<class 'set'> 
win.setTimeout(print_type, 500, {'foo':'bar'}) #<class 'dict'>
```
I think that it used to change a dict into a javascript object, because that's how I initially bumped into this issue, but I've messed about with my original code and also updated Brython and can no longer replicate that. 

Anyways - If it can't be fixed, it should at least be documented.

**Comment by PierreQuentel** [comment]
Thanks @shark-in-a-hat. Lists and tuples are now handled like other Python types.
