### ISSUE TITLE
Error: custom pathname is not respected when importing module from root url

### ISSUE THREAD

**Issue by lebalz** [brython-dev/brython#2449]
Hi @PierreQuentel 

I am currently working on a new implementation of an interactive Brython codeblock for Markdown pages. The new possibility with `__BRYTHON__.runPythonSource("...",{pythonpath:["/somepath1/", "/somepath2/"]})` is really handy and cool!

This works as expected - in my case, i specify the static folder `/bry-libs/` and every module is looked up there, as long as i'm not on the origin url (e.g. `localhost:3000` or generally when the page is served directly from root `/`). In this case, i get an error when importing e.g. the module `brython_runner`, which is located under `/bry-libs/brython_runner.py`:

JS-Code:
```js
const code = `
import brython_runner
print('hello world')`

window.__BRYTHON__.runPythonSource(code, { pythonpath: ["/bry-libs/"]})
```
Error in the console:

```
File "http://localhost:3000/brython_runner.py", line 10
    </head>
IndentationError: unindent does not match any outer indentation level
```
Note that the request url did not include the specified `pythonpath`.

The weird thing is, that the exact same code works whenever the page is served from a different path than `/` (e.g. from `/localhost:3000/demo`) - then it looks up the correct location `http://localhost:3000/bry-libs/brython_runner.py` and everything works as intended.

Do you have any idea, what could lead to this error?

**Comment by lebalz** [comment]
I did a small repro of the Bug: https://github.com/lebalz/brython-repro-exec-script-bug


https://github.com/brython-dev/brython/assets/22354689/4780feb3-bf8f-45dc-8d76-e93be479d9c1

**Comment by PierreQuentel** [comment]
Thanks for the report and the demo ! I think the bug is fixed with the commit above.

**Comment by lebalz** [comment]
Hi @PierreQuentel 
Thanks for the fix, this works now :)
