### ISSUE TITLE
Brotli compression for brython.js and brython_stdlib.js

### ISSUE THREAD

**Issue by mardon86** [brython-dev/brython#2457]
I think it's very burdensome to download brython.js + brython_stdlib.js altogether for ~5.5MB 
What if we pre-compress these files using [brotli](https://github.com/google/brotli) then users only need to embed the loader script (e.g. brython-loader.js) on their html page.
This script loader contains a function to perform an ajax request to retrieve the compressed files, a brotli decoder and a function to load the uncompressed brython scripts.
I have tried compressing brython.js + brython_stdlib.js which was originally ~5.5Mb to only ~983KB,
The Brotli decoder script is ~152KB. So the total is ~1.1MB, which is not too heavy for users

What do you think ?

**Comment by PierreQuentel** [comment]
Thanks for the suggestion @mardon86, but servers already transparently compress these scripts, and the browser decompresses them : if you load [brython.info home page](https://brython.info), you will see that **`brython.js`** is compressed from 1.18 to 0.23 Mb and **`brython_stdlib.js`** from 4.14 to 0.93 Mb.
