### ISSUE TITLE
ImportError(s): Wrong assumptions of RPyC or compatibility issues? 

### ISSUE THREAD

**Issue by alanjds** [brython-dev/brython#246]
I am trying to bring [RPyC](https://github.com/tomerfiliba/rpyc) client to Brython, but had some ImportErrors:

1) The line `exec("execute = exec")` works on console, but not when being imported. Is this a Brython issue?

``` python
Brython 3.2.1 on Netscape 5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.155 Safari/537.36
>>> import rpyc.lib.compat
Traceback (most recent call last):
  module __main__ line 2
  (...)
  module rpyc.lib.compat line 11
    exec("execute = exec")
ImportError: rpyc
```

2) The module `io` have not the `BytesIO` module, but does have a `StreamIO`. This is a Brython issue, right?

``` python
>>> import rpyc.lib.compat  # after "patched" the 1) error...
Traceback (most recent call last):
  module __main__ line 2
  (...)  
  module rpyc.lib.compat line 43
    from io import BytesIO
ImportError: cannot import name 'BytesIO'
```

3) The Brython module `errno` have not the constant `EWOULDBLOCK`. Is this a Brython issue? The Python docs says that some constants can not exist on all platforms IIUC. Should patches land on RPyC or on Brython?

``` python
>>> import rpyc.core.stream  # after "patched" the 2) error...
Traceback (most recent call last):
  module __main__ line 2
  (...)
  module rpyc.core.stream line 18
    retry_errnos = (errno.EAGAIN, errno.EWOULDBLOCK)
ImportError: rpyc
```

4) The builtin `next` can be overwritten on console, but not by imports. This is a Brython issue, right?

``` python
>>> import rpyc.core.stream  # after "patched" the 3) error...
Traceback (most recent call last):
  module __main__ line 2
  (...)
  module rpyc.core.protocol line 12
    from rpyc.lib.compat import pickle, next, is_py3k, maxint, select_error
ImportError: rpyc
>>> from rpyc.lib.compat import pickle, next, is_py3k, maxint, select_error
Traceback (most recent call last):
  module __main__ line 2
  (...)
  module rpyc.core.protocol line 12
    from rpyc.lib.compat import pickle, next, is_py3k, maxint, select_error
ImportError: cannot import name 'next'
```

**Comment by alanjds** [comment]
The main question here is: what is Brython and what is RPyC issue?

I had not (yet) enough knowledge to fix Brython issues, but will fix RPyC ones if I know what ones is theirs.

**Comment by alanjds** [comment]
HI. Any thoughts on the questions?

**Comment by kikocorreoso** [comment]
There are several modules used by rpyc that are not available on Brython:
* ssl, plumbum, gtk, pygtk, nose, fuse, gobject, safegtk, notify, Queue, daemon, lockfile,...

If you do not solve these dependencies it is difficult to bring rpyc to Brython.

OTOH, Brython runs on the client. What would be the useful of rpyc in a Brython project? I don't see the connection. Maybe you can explain briefly what you want to achieve so we can try to provide better answers.

Also, it seems rpyc is in 'maintenance mode' as there are only some PRs merged by the owner during the last years.

And also, just out of curiosity, what is the difference between rpyc and a ssh connection?

**Comment by alanjds** [comment]
RPyC is a symmetric remote processing tool. It allows objects on one Python to be available on another Python. This way, I can put a CPython running on Android, connect Brython@webview and code the app with all the power of C-compiled extensions.

It is different than an SSH connection by transferring back and forth the needed stuff on the fly. It just uses SSH to transfer the stuff. See the 1st paragraph [here](https://rpyc.readthedocs.org/en/latest/#rpyc-transparent-symmetric-distributed-computing).

RPyC have some "optional" weak dependencies, as all this gtk stuff for example. The harder to break is plumbum, which provides a communication channel with the mothership. But the plan is to reimplement this channel using Brython's websocket.

I am trying to port only the RPyC "client" to Brython. No gobject, notify, daemon, etc will be needed.

**Comment by alanjds** [comment]
Why it got closed?

Still open question: About 1), 2), 3) and 4) what are Brython issues and what are not?

**Comment by jonathanverner** [comment]
2) should no longer be a problem
3) is probably a bug in Brython
1, 4) No idea, would have to test it locally, right now I only have a browser.

**Comment by PierreQuentel** [comment]
@alanjds 
Once in a while I take a look at the oldest open issues and generally close them, supposing that the author has lost interest. In this case I was wrong, so I have re-opened it and will take a look at issues 1, 3 and 4.

**Comment by PierreQuentel** [comment]
Issue 1 seems to be fixed : I put this in test_issue_246.py

```python
exec("execute = exec")
execute("x = 1")
```

then this worked correctly in a test page : 
```python
import test_issue_246
assert test_issue_246.x == 1
```

**Comment by PierreQuentel** [comment]
Issue 4 also seems to be solved. I added this in test_issue_246.py : 

```python
def next(x):
    return 2 * x
```

and this works in the test page : 
```python
from test_issue_246 import next

assert next(5) == 10
```

**Comment by PierreQuentel** [comment]
Since commit 0975f89 fixes issue 3 and issue 2 was fixed months ago, can we close the issue ?

**Comment by alanjds** [comment]
Thanks @jonathanverner and @PierreQuentel. Will close it.

I would reopen if found anything with this. Or create another issue for new problems if I find some.
