### ISSUE TITLE
Reduce to a minimum failed AJAX requests for module imports

### ISSUE THREAD

**Issue by olemis** [brython-dev/brython#247]
Overall strategy is described below . It all starts by constraining the number of locations searched when trying to import a module, including searches that are sure not to find anything . Below I list some common instances and proposed solutions

 - files with the extension .js in places other than /src/libs

We have to support this . Under some circumstances js modules might even serve as an equivalent of CPython extension modules written in C.

 - files with the extension .py in /src/libs
 - files with the extension .pyc.js

Both these scenarios, and others e.g. looking for .js in src/Lib , will be solved by adding at load time `UrlPathFinder` objects with expected file types (i.e. src/libs=js , src/Lib=py
 src/site-packages=py, ...) in `sys.path_importer_cache` . We already know what's gonna be there in advance so we do not need to iterate over irrelevant file types . That's exactly what
 `sys.path_importer_cache` is for .

Exhaustive search will be performed by default for user-defined path entries , though . Nevertheless , in order to allow users to specify equivalent optimizations I'll provide two shortcut functions for URL path finder (path + file type) as well as VFS path finder .

- files in /src/Lib or /src/libs when the option static_stdlib_import is set : if this is the case, the search has already been done by finder_stdlib_static

In that case we shall remove those path entries from sys.path rather than hard-coding this into the import machinery .

My idea is to restore support for .pyc.js files after doing so since they will be harmless should the necessary steps be performed (will be explained once I publish the solution) .

@earney @PierreQuentel what d'u think ?

**Comment by PierreQuentel** [comment]
We all share the same concern about minimising the number of tries when importing a module. 

Another aspect is that imports must be done with the same simple syntax as in standard Python : `import some_module`. I don't want to ask users to specify the location and type of the module for each import.

For the standard library, with static_stdlib_import, the mapping between module name and extension is stored in stdlib_paths, so the extension can be what we want, including maybe .pyc.js for precompiled modules (if this can be achieved some day).

For user-defined or third party modules in site-packages or the current script location, the default must be to only search scripts with the extension .py (this makes at most 4 calls for each import, which is already expensive). I don't exclude support of user-defined, importable Javascript modules, but this should be carefully documented : the structure of these modules is very specific, and the way to import them would also require something specific (maybe that's what you have in mind with "shortcut functions for URL path finder").

**Comment by olemis** [comment]
@PierreQuentel customization of `sys.path` is [quite well documented in docs](https://docs.python.org/2/library/sys.html#sys.path) . Import location (as stated by standards) and type (a bit more important for Brython, considering performance) customisations do not have to be done for each module , but for each user-defined path different from standard locations , should the user decide that this is what they want to do (e.g. load modules from CDN , maybe possible some day)

OTOH , when `static_stdlib_import ` is set all other aspects of import optimisations are null because module search is performed by a meta-finder (instead of a path finder) . That's why I suggested not to add those paths to `sys.path` under such circumstances .

OTOH I do not why you say four calls for site-packages modules ? AFAICT they should be two , one for '.py' and another for '__init__.py' .

**Comment by PierreQuentel** [comment]
> OTOH I do not know why do you count four calls for site-packages modules ? AFAICT they should  be two , one for `.py` and another for `__init__.py` .

@olemis : if a module is not in the stdlib, you have to search (at most) 2 locations in site-packages _and_ 2 other ones in the current script directory.

**Comment by PierreQuentel** [comment]
Can  you give an example of a _user-defined path, different from standard locations_ ? You mention CDN as a future possible target, but what would be the use at the moment ?

**Comment by olemis** [comment]
Any deployment involving a single location for loading Brython core (e.g. for maximizing browser cache hits) , and multiple web sites using specific py modules would be a candidate ; but the most important fact is that one of compliance with specs . That's what `sys.path` is for so, this logic should be supported .

**Comment by olemis** [comment]
The other major example is URLs pointing to `.vfs.js` files but those are handled more efficiently .

**Comment by olemis** [comment]
@PierreQuentel please feel free to reopen this ticket if you come up with further optimizations .

**Comment by olemis** [comment]
BTW , I added `_importlib.optimize_import_for_path(path, filetype)` in order to provide hints to the import machinery when searching for a given module at a given `path` , thus restricting attempts to match `filetype` .
