### ISSUE TITLE
Exceptions doesn't have info

### ISSUE THREAD

**Issue by thewh1teagle** [brython-dev/brython#2471]
As you can see in the screenshot, I made the same calls from the same objects. one called from brython and one called from the console in js.
With js call, I can understand the error. from Brython it just tells there's an error without explain.
![image](https://github.com/brython-dev/brython/assets/61390950/08e59d85-adb3-43d2-bf60-906824414257)

**Comment by PierreQuentel** [comment]
I'm sorry but the screenshot is not enough to understand the issue. Can you give a code sample in Brython that doesn't give the expected error information ?
