### ISSUE TITLE
Bug with regular expressions with `\s` inside []

### ISSUE THREAD

**Issue by alextretyak** [brython-dev/brython#2472]
There is a bug with regular expressions containing `\s` inside the character class.

Try this code in the [Brython console](https://brython.info/tests/console.html):
```
import re
re.sub(r'/\*[\s\S]*?\*/', '', 'a/*b c*/')
```
It outputs `'a/*b c*/'`, but the correct Python implementation outputs `'a'`.

In JavaScript, the same regular expression works correctly:
```
'a/*b c*/'.replace(/\/\*[\s\S]*?\*\//, '')
```
will output `'a'`.

I can work around this problem in Brython by using `re.DOTALL`:
```
import re
re.sub(r'/\*.*?\*/', '', 'a/*b c*/', re.DOTALL)
```
However, this is not always acceptable.

**Comment by PierreQuentel** [comment]
Thanks for the report @alextretyak !
