### ISSUE TITLE
[CPython compliance] 500 is 500 should print a `SyntaxWarning` / `a+c` should be `False` if both equals to 500.

### ISSUE THREAD

**Issue by denis-migdal** [brython-dev/brython#2475]
Hi,

I found out a quite strange Python subtlety.

The `is` keyword checks if the objects has the same references... as we would expected.
However, it raises a `SyntaxWarning` if used with literals :
```
>>> 500 is 500
<stdin>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
True
```

This is explained by the fact that, in Python, `int` from -5 to 256 are pre-allocated and cached.
It means that:
```
>>> a=1
>>> b=1
>>> a is b
True
```
and
```
>>> a=500
>>> b=500
>>> a is b
False
```

I do not know if you want to implement the latter behavior, but I think you might want to implement the `SyntaxWarning` ?

**Comment by PierreQuentel** [comment]
Thanks Denis. The `SyntaxWarning` is raised at compile time and does not depend on the value, it shows both for `0 is 0` and `500 is 500`

The other behaviour (`a is b` true or false depending on the integer value) is an implementation detail, it doesn't have to be the same as in CPython. I didn't make extensive tests but for integers, in Brython the test is always true for "safe" integers (below 2**53 -1) and false for big integers.
