### ISSUE TITLE
`NetworkError` in `import` statement in version 3.12.4

### ISSUE THREAD

**Issue by alextretyak** [brython-dev/brython#2480]
Hi,

I'm serving my project's source files directly from GitHub, and everything worked fine in Brython 3.12.3.

But in version 3.12.4 there is a `NetworkError` in `import symasm` statement.

You can check it out for yourself:
[Webpage using Brython 3.12.3](https://symasm.github.io/) — works correctly
[Webpage using Brython 3.12.4](https://symasm.github.io/3.12.4/) — does not work

**Comment by PierreQuentel** [comment]
Thank you Alexander. I will publish a new release shortly.

Not related, but I see you still use the "old" version to pass options : `<body onload=brython({...})>`. The recommended way is now to specify options with the `<brython-options>` tag, or with attributes for each script.

In your example the syntax would be
```xml
<body>
<script type="text/python" pythonpath='https://raw.githubusercontent.com/symasm/symasm/main/'>
...
</script>
```
