### ISSUE TITLE
Can't send SharedArrayBuffers between threads

### ISSUE THREAD

**Issue by benjie-git** [brython-dev/brython#2481]
@PierreQuentel - I see a new problem now, starting with [this commit](https://github.com/brython-dev/brython/commit/de39e16e1f1edf4fc54f48ea8499d7d64fb6eb43):  sending a SharedArrayBuffer from the main thread to a worker is broken.  It now arrives as an empty object.

```html
    <script type="text/python" class="webworker" id="testWorker">

from browser import self, bind

@bind(self, "message")
def message(evt):
    self.console.log(evt.data)

    </script>
```

```html
    <script type="text/python" id="__main__">

from browser import window, worker

def on_ready(myWorker):
    sab = window.SharedArrayBuffer.new(8)
    myWorker.send(sab)

worker.create_worker("testWorker", on_ready, None)

    </script>
```

logging shows just `{}` instead of `SharedArrayBuffer(8)`

I'm afraid testing this is a bit of a pain, as it requires the following headers to be served along with the test page.
```python
{"Cross-Origin-Opener-Policy": "same-origin",
  "Cross-Origin-Embedder-Policy": "require-corp"}
```

**Comment by EricEisaman** [comment]
> This example is fixed, thank you @PierreQuentel ! But I still see what seems like a related issue. This code:
> 
> ```python
> from browser import window
> bcastChannel = window.BroadcastChannel.new("TestChannel")
> bcastChannel.postMessage("hi there")   # This works.  The following should too, but does not.
> bcastChannel.postMessage(["hi", "there"])
> ```
> 
> Throws the error:
> 
> ```
>   File "test.html#__main__", line 4, in <module>
>     bcastChannel.postMessage(["hi", "there"])
> JavascriptError: DataCloneError: Failed to execute 'postMessage' on 'BroadcastChannel': function(self,attr){if(self.__dict__&&$B.$isinstance(self.__dict__,_b_.dict)&&_b_.dict.$contains_string(self.__...<omitted>...)} could not be cloned.
> ```
> 
> But anything serializable should be valid to send through `postMessage()`.

Perhaps related to circular references in the processing of the Array object literal.

**Comment by benjie-git** [comment]
This is working great for me now.  Thank you again for your responsiveness!
