### ISSUE TITLE
cannot import name 'Openai' from 'openai'

### ISSUE THREAD

**Issue by lishaozheng** [brython-dev/brython#2482]
<!doctype html>
<html>

<head>
<meta charset="utf-8">
<script type="text/javascript" src="brython.js"></script>
<script type="text/javascript" src="brython_stdlib.js"></script>
</head>

<body>
<script type="text/python">
from browser import document
import time
from openai import Openai
openai1 = OpenAI(api_key="", base_url="https://api.chatanywhere.com.cn/v1")

a = "sdfs"
document <= f"{a}"
</script>
</body>

</html>

报错：
brython.js:11026 Traceback (most recent call last):
  File "Brython-3.12.4/index.html#__main__", line 3, in <module>
    from openai import Openai
ImportError: cannot import name 'Openai' from 'openai' (http://127.0.0.1:8848/Brython-3.12.4/openai.py)

**Comment by PierreQuentel** [comment]
The package is not in the standard distribution, please read section "installing a CPython package" in the [documentation](https://www.brython.info/static_doc/3.12/en/install.html). 

Note that Brython can only handle Python code, if your package has scripts written in C it will not be supported.
