### ISSUE TITLE
Brython's `set_loop_timeout` not working within asynchronous code

### ISSUE THREAD

**Issue by urous3814** [brython-dev/brython#2483]
While developing my code, I encountered an issue where the webpage becomes unresponsive and irrecoverable when an infinite loop is executed in async mode. While searching for a solution, I found a related discussion [here](https://github.com/brython-dev/brython/issues/289). I tried applying the suggestions to my code, but it didn't work as expected.

Here's my code:

```python
from browser import document, window, aio, console, timer

# Set loop timeout
timer.set_loop_timeout(10)

...

def processInput(event=None):
    global input_values
    # Clear previous output
    document["mainConsole"].innerHTML = ""
    # Execute the script
    aio.run(exec_script())

async def exec_script():
    try:
        ${solutiontext}  # This may include an infinite loop
    except BrythonNotRunningError:
        on_compile_done()
        return
    except Exception as e:
        print(f"Error: {e}")
    finally:
        on_compile_done()

processInput()
```

The problem is that when the `solutiontext` variable contains an infinite loop like `while(1):`, the entire webpage freezes. It seems that the `set_loop_timeout(10)` option doesn't work within the asynchronous function `exec_script()`.

How can I prevent or handle infinite loops in asynchronous Brython code?

**Comment by denis-migdal** [comment]
Async code is still executed in the main thread.
If you really want an infinite loop put it in a WebWorker.

Else, you can use `requestAnimationFrame` or `setInterval`.

**Comment by urous3814** [comment]
What I'm wondering is if there's a way to add a timeout to a loop in a script that's run with `aio.run`, as infinite loop like while(1): in aio.run causes the entire website to freeze. And I've tried the `set-loop-timeout` but it doesn't working. Since the code being executed is user-provided within an asynchronous environment I've set up, I don't know what code will be executed. I'm curious if there is a way to detect this kind of situation or if there are any error handling or timeout mechanisms available.

**Comment by EricEisaman** [comment]
Perhaps using a race.  

General idea:

```
async function performOperationWithTimeout(operation, timeoutDuration) {
    const operationPromise = operation(); // Assuming operation returns a promise
    const timeoutPromise = timeout(timeoutDuration).then(() => {
        throw new Error(`Operation timed out after ${timeoutDuration} ms`);
    });

    try {
        await Promise.race([operationPromise, timeoutPromise]);
        console.log('Operation completed successfully');
    } catch (error) {
        console.error(error.message);
    }
}
```

**Comment by denis-migdal** [comment]
There is a way if the code is executed in a WebWorker, or if you put a condition in your loop, e.g. `if( Date.now() > ?) return/break;`. Maybe also if you execute it in an iframe ?

**Comment by urous3814** [comment]
@EricEisaman The code you provided is based on JavaScript, and I don't know how to use promises in a Brython environment. I tried a few things and even ran the code below, but it resulted in the following error:
`Error occurred: 'coroutine' object is not callable`

Here is the code:

```python
async def perform_operation_with_timeout(operation, timeout_duration):
    # Perform the asynchronous operation.
    operation_future = aio.Future()
    operation_task = aio.run(operation(), on_result=operation_future.set_result, on_exception=operation_future.set_exception)
    
    # Set the timeout.
    timeout_future = aio.Future()
    aio.timer.set_timeout(lambda: timeout_future.set_result("timeout"), timeout_duration * 1000)  # timeout_duration is in seconds
    
    # Wait for the asynchronous operation and timeout.
    done, pending = await aio.wait(
        [operation_future, timeout_future],
        return_when=aio.FIRST_COMPLETED
    )
    
    if timeout_future in done:
        # Timeout occurred
        operation_future.set_exception(Exception(f"Operation timed out after {timeout_duration} seconds"))
        print(f'Operation timed out after {timeout_duration} seconds.')
    else:
        # Operation completed successfully
        result = await operation_future
        print('Operation completed successfully:', result)
```

Can you provide some advice on how to handle this situation?

**Comment by denis-migdal** [comment]
> Perhaps using a race.

A race only enables to not wait for a promise for too long. Still, the async function is executed in the main thread.
Therefore, it won't prevent the main thread from being stuck in an infinite loop.

**Comment by EricEisaman** [comment]
@denis-migdal 
Good point.  I wonder if there is a way to adapt this pattern of thinking to Brython. It would require careful consideration of Brython's asynchronous model, which differs from JavaScript's Promise-based model.

**Comment by denis-migdal** [comment]
It may be possible for Brython to check at each line/loop if a timeout occurred to then break of everything, but that'd be quite heavy performance-wise.

**Comment by urous3814** [comment]
@denis-migdal The method you mentioned might be a bit inefficient, but it worked excellently compared to the other options. To help others who might be facing the same issue, I'm sharing my code below.

**JavaScript Part:**

```javascript
let newSolutionText = [];

for (let i = 0; i < solutiontext.length; i++) {
    let line = solutiontext[i];
    let trimmedLine = line.trim();

    // Check if the line contains a for or while statement with a colon
    if (/\b(for|while)/.test(trimmedLine) && trimmedLine.includes(':') && !line.trim().startsWith('#')) {
        newSolutionText.push(line); // Add the for/while line

        if (i + 1 < solutiontext.length) {
            let nextLine = solutiontext[i + 1];
            
            // Count the number of leading spaces in the next line
            let leadingSpaces = nextLine.match(/^\s*/)[0].length;
            newSolutionText.push(' '.repeat(leadingSpaces) + 'SYS_TimeoutCheck()'); // Add the next line with the same indentation as the for/while line
        }
    } else {
        newSolutionText.push(line); // Add non-for/while lines
    }
}
newSolutionText = newSolutionText  
    .map(line => "        " + line) // Add indentation
    .join('\n');
```

**Brython Part:**

```python
...
import time
...
class TimeOutError(Exception):
    pass

def SYS_TimeoutCheck():
    if SYS_TimeoutTime < time.time():
        raise TimeOutError("Timeout Occurred: Infinite Loop Detected")
...
def processInput(event=None):
    global SYS_TimeoutTime
    start_time = time.time()
    SYS_TimeoutTime = start_time + 5
    aio.run(exec_script())
...
async def exec_script():
    try:
        ${newSolutionText}
    except TimeOutError:
        print("Timeout Occurred: Infinite Loop Detected")
        on_compile_done()
        return  
    except Exception as e:
        print(f"Error: {e}")
    finally:
        processInput()
```
