### ISSUE TITLE
Uncaught DOMException: Failed to execute 'createObjectStore' on 'IDBDatabase'

### ISSUE THREAD

**Issue by Mxuan01** [brython-dev/brython#2488]
Most of the time, all is fine, but once a user encounters the bug, the bug appears frequently:

```
Uncaught DOMException: Failed to execute 'createObjectStore' on 'IDBDatabase': The database is not running a version change transaction.
    at idb.onupgradeneeded
```

After reading the code, I think the bug should be here:

![image](https://github.com/user-attachments/assets/e3c62431-eeb3-4a03-8109-69574fa1e14f)

The same goes for `$B.idb_open_promise`.

**Comment by PierreQuentel** [comment]
Thanks for the report @Mxuan01 

With the commit above I think the risk of such bugs is reduced, but it's hard to be sure. If you still see them can you report again ?

**Comment by Mxuan01** [comment]
> Thanks for the report @Mxuan01
> 
> With the commit above I think the risk of such bugs is reduced, but it's hard to be sure. If you still see them can you report again ?

Ok, I will

**Comment by PierreQuentel** [comment]
I am closing the issue. If the bug still occurs please comment again.
Thanks again !
