### ISSUE TITLE
Bug in closure when reusing/masking variable names

### ISSUE THREAD

**Issue by jibalamy** [brython-dev/brython#2494]
Hello,

I am encountered a bug with Brython, when using and masking variables in closure. 

The following HTML/Brython code demonstrates the bug:

```
<!doctype html>
<html>

<head>
<meta charset="utf-8">
<script type="text/javascript" src="brython.js"></script>
<script type="text/javascript" src="brython_stdlib.js"></script>
</head>

<body>
<script type="text/python">
from browser import document, timer

def f():
  record = "A"
  def g():
    print(record)
    record_list = ["B"]
    response = [ record for record in record_list ]
    print(response)
  g()
  
f()

</script>
</body>

</html>
```

In the bowser log, I obtain the following:

```
A
['A']
```

While, if you run the f() function in plain Python, you get:

```
A
['B']
```

Notice that, if you remove the reference to the "record" variable in g() (in the first print), the result changes.

**Comment by PierreQuentel** [comment]
Thanks for reporting this (tricky) issue @jibalamy !
