### ISSUE TITLE
Wrong associativity for ** (should be right-to-left, is left-to-right)

### ISSUE THREAD

**Issue by dkosbie** [brython-dev/brython#250]
This example:

print(2**3**4)

As per here (https://docs.python.org/3/reference/expressions.html (Section 6.15)):  "Operators in the same box group left to right (except for exponentiation, which groups from right to left)."

Thus, the above code should right-associate and print 2**(3**4), or 2417851639229258349412352, but instead it seemingly left-associates and prints (2**3)**4, or 4096.

Thanks!

David

**Comment by dkosbie** [comment]
Note that the code example unfortunately formatted strangely.  (2 ** 3 ** 4) came out as (2**3**4).  The code sample is:

  print(2 ** 3 ** 4)

The bug report is otherwise correct.  Sorry for the confusion, and thanks again.

David

**Comment by PierreQuentel** [comment]
Thanks for the report, should be fixed now.
