### ISSUE TITLE
Insufficient documentation for usage of custom packages made with brython-cli

### ISSUE THREAD

**Issue by temphedgehog** [brython-dev/brython#2508]
I've been attempting to launch a game in browser with Brython. The game is made with Panda3D engine (Python).

I followed instructions on how to package it and put the files on a Flask server. All the files are in `static` directory.
After loading the index.html I can see in the console it's looking for files that are nowhere to be found:

![Screenshot from 2024-11-01 21-23-57](https://github.com/user-attachments/assets/b8a5b568-84f9-4c5b-bd34-56016580cada)

Unfortunately there isn't enough information about how to deal with this. The only files that were loaded without issues are `brython.js`. I don't think `panda3d.brython.js` file was loaded OK due to errors in the console.

**Comment by PierreQuentel** [comment]
It's hard to give a detailed answer with the little information you provide, but anyway you won't be able to use Panda3D with Brython because it is not a pure-Python package (there are all sorts of .dll and .exe files in it)
