### ISSUE TITLE
str.casefold() recently broke

### ISSUE THREAD

**Issue by benjie-git** [brython-dev/brython#2515]
When I try to run casefold, for example: 
```python
"Hello".casefold()
```

I get `TypeError: set.remove() takes exactly 2 arguments (1 given)`

This worked very recently but is currently broken.

**Comment by PierreQuentel** [comment]
Sorry about that Ben, I am changing the argument parsing of methods of built-in types for performance and left a few typos like this one. Thanks for reporting !
