### ISSUE TITLE
copy.copy(x) returns alias and not a copy

### ISSUE THREAD

**Issue by dkosbie** [brython-dev/brython#252]
Hi all.  Here's an example:

```
import copy
a = [1]
b = copy.copy(a)
a[0] = 42
print(a)      # [42], right
print(b)      # [42], wrong, should be [1]
print(a is b) # True, wrong, should be False
```

This problem is not just for lists, but any mutable data structures (sets, dicts, etc).  copy.copy(x) is seemingly just returning a reference (alias) back to x.

Interestingly, copy.deepcopy(x) seems to work just fine.

Thanks.

David

**Comment by PierreQuentel** [comment]
Hi,

I get the correct result with the current development version, so I suppose you are using version 3.2.0 ? This bug was fixed in commit 7b8f8e912ab6754a0d5830e0edfe6d5e80c704d2 a few weeks ago.

**Comment by dkosbie** [comment]
Hi Pierre.  Indeed, this was using the released version 3.2.0.  Glad to hear you fixed it already, and sorry for the duplication.

We'd like to run off the current development version, but so far we've not had success compiling it.  (clone and make) does not successfully build for us.  So, a couple quick questions:

* Is there a better place than this issue-tracking forum where we can ask dev-related questions that aren't "issues"?

* Is there a how-to-build document or more generally a how-to-be-a-brython-dev document somewhere?

* Failing those, can you describe the standard build environment that you use?

Thanks again for all your great work.  This is an exciting project with lots of potential.

Best regards.

David
---------
David Kosbie
Associate Teaching Professor
Computer Science Department
Carnegie Mellon University

**Comment by olemis** [comment]
@dkosbie 
mailing list : brython@googlegroups.com
IRC : #brython @ freenode.net

**Comment by olemis** [comment]
@dkosbie 
mailing list : brython@googlegroups.com
IRC : #brython @ freenode.net

**Comment by olemis** [comment]
@dkosbie 
mailing list : brython@googlegroups.com
IRC : #brython @ freenode.net

**Comment by dkosbie** [comment]
Hi Olemis.  Thanks for the pointers.  Good to know!

David
