### ISSUE TITLE
Requesting a public interface to the Python parser

### ISSUE THREAD

**Issue by ddcc4** [brython-dev/brython#2520]
Hi,

Brython seems to have the best Python parser implementation of all the Python-to-JavaScript projects. But it's a bit hard to use if I just want a Python parser without the rest of the JS translation. (I'm looking for a JavaScript implementation that takes a Python program string and gives me an AST.)

I believe that in the older versions of Brython, you could do:
```javascript
parser = new $B.Parser(python_code, filename, 'file');
ast = parser.parse();
```

But it looks like the implementation was recently restructured, and now we have to do something like this to get the AST:
```javascript
parser = new $B.Parser(python_code, filename, 'file');
ast = $B._PyPegen.run_parser(p);
```

So this request is just to have a stable public function that we can call to invoke the parser to get an AST.

Also, is there an update on `brython_standard_parser.js`? Is it totally obsolete now? It looks like the parser in `python_parser.js` still implements the old `Parser.parse()` interface, but it doesn't seem usable with the current Brython implementation. Should `brython_standard_parser.js` just be deleted from the project now?

Finally, there are a few minor quality-of-life improvements that would make things nicer for users who just want to use the Brython parser. For example, `py2js.js` adds an `onload` hook that we can't turn off if we just want to use Brython for parsing. And I was trying to see if there's a smaller subset of files that I could use if I just wanted parsing without JavaScript execution, but it looks like there are enough cross-dependencies that I can't remove any of the files.

**Comment by PierreQuentel** [comment]
Thanks for the comments and proposals David, and for the initial compliment :-)

`brython_standard_parser.js` was a version of a PEG parser developed a long time ago, it worked but was too slow to replace the "hand-made" parser used at the time. I had forgotten to remove it, it's done now.

In the second commit referenced above I have introduced a function `__BRYTHON__.pythonToAST(src)` meant to be used in Javascript programs, it takes the Python source code `src` and returns a Javascript object with the same structure as the Python AST. Is this ok for you ?

I have no solution for the problems you mention in the last paragraph:
- I try to limit the options to the strict minimum, the use case that would justify an option to enable / disable the `onload` hook is too specific IMO
- as you noticed there are too many cross-references between Brython core modules to remove any of them, solving this issue would require a huge refactoring and it's clearly not something I put on the todo list

**Comment by ddcc4** [comment]
> In the second commit referenced above I have introduced a function __BRYTHON__.pythonToAST(src) meant to be used in Javascript programs, it takes the Python source code src and returns a Javascript object with the same structure as the Python AST. Is this ok for you ?

Yes, that is perfect. Thank you very much!
