### ISSUE TITLE
Ace editor misconfigured in demo page

### ISSUE THREAD

**Issue by thejoshwolfe** [brython-dev/brython#2523]
Thanks for creating this software! It's enabling me to teach high schoolers Computer Science via the [CMU Desktop Graphics](https://academy.cs.cmu.edu/desktop) curriculum. Looking into their technology stack led me to this repo, and I ran into an issue on the editor demo page.

It looks like there's a conflict between the sample code:
```python
for i in range(10):
	print(i)
```

and the editor settings here: https://brython.info/tests/editor.html , which i believe is this source code: https://github.com/brython-dev/brython/blob/master/www/tests/editor.html

I believe the problem is that the Ace editor is configured to use 4-space indentation, but the code sample uses a hard tab. Confusingly, the editor very thoroughly hides the 4-spaces of indentation from the user: moving the cursor around jumps as though there are hard tabs. This led me down an hour-long debugging rabbit hole where i was getting a bogus IndentationError with what looked like perfectly correct indentation.

To reproduce the problem, start with the default code sample (incognito window, for example), then put the cursor after the `:` and hit Enter. Type any line of code, like `pass`, and we've created the problem.

Copypasting the code into this github issue reveals the problem:

```python
for i in range(10):
    pass
	print(i)
```

but in the Ace editor, there I could not find any way to distinguish between the indentation of the two lines. The cursor and selection behavior is identical to what you would expect from hard tabs on both lines.

Deleting and re-entering the indentation in front of the `print(i)` statement (e.g. Shift+Tab, Tab) solves the problem by canonicalizing the indentation to 4-spaces:

```python
for i in range(10):
    import time
    print(i)
```

I was convinced there must have been something wrong with the Brython parser when i first encountered this problem, but it turned out to be an editor bug. Given that the interactive demo is crucial for making good first impressions, this seems like a problem worth reporting in the Brython repo. :wave: 

I'm not experienced with the Ace editor, so I'm not sure if configuring it is possible. Another possible solution might be to change the example code to use spaces like the editor expects. I haven't looked into the level of effort into either of these options.

Thanks again for this software package!

**Comment by PierreQuentel** [comment]
Thanks for the report Josh ! The bug has been present since the early days of Brython but no one had ever reported it.

I have fixed it by replacing the tab in the example code by 4 spaces.
