### ISSUE TITLE
struct.pack() raises an OverflowError when it shouldn't

### ISSUE THREAD

**Issue by NYKevin** [brython-dev/brython#263]
This raises:

    Brython 3.2.0 on Netscape 5.0 (Windows)
    >>> import struct
    >>> struct.pack('>q', 42)
    Traceback (most recent call last):
      module __main__ line 2
        qs_lang, language = header.show('../')
      module __main__17 line 141
        traceback.print_exc()
      module exec_64 line 1
        struct.pack('>q', 42)
      module _struct line 360
        result += [format['pack'](var,format['size'],endianness)]
    OverflowError: Number:42 too large to convert
    >>>

But in CPython 3.4.1, it doesn't:

    Python 3.4.1 (v3.4.1:c0e311e010fc, May 18 2014, 10:38:22) [MSC v.1600 32 bit (Intel)] on win32
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import struct
    >>> struct.pack('>q', 42)
    b'\x00\x00\x00\x00\x00\x00\x00*'
    >>>

Since 42 is clearly small enough to fit in a 64-bit `long long`, ISTM that CPython is right and Brython is wrong.

**Comment by p-i-** [comment]
This report stems from http://stackoverflow.com/questions/32209092/space-efficient-deserialise-array-of-myclass-instances and https://groups.google.com/forum/?hl=en#!topic/brython/jZqtDRxKB8U
