### ISSUE TITLE
print(random.choice("ab")) crashes

### ISSUE THREAD

**Issue by dkosbie** [brython-dev/brython#268]
Hi all.  Here's a snippet with the issue:
```
import random
print(random.choice("ab"))
```
In standard Python3, this randomly prints "a" or "b".  In Brython, it crashes.

Thanks!

David

**Comment by PierreQuentel** [comment]
Thank you for the report !

This was fixed in commit 96ad0872266e7db7c10e35fdb0a9a00fd0ba4ad2. I am working on the test in the CPython test suite (`/Lib/test/test_random.py`) and fixing other bugs.
