### ISSUE TITLE
Inclusion of a `CustomTag` in the html module

### ISSUE THREAD

**Issue by kikocorreoso** [brython-dev/brython#27]
As suggested by @JamesHutchinson and in order to allow users use custom tags the following could be added to the html module:

```
from browser.html import CustomTag

mytag = CustomTag('EXPERIMENTALHTML5TAG')
```

Ideas, suggestions, pros, cons,...?

**Comment by olemis** [comment]
@kikocorreoso @juancarlospaco at present [web components polyfills](http://webcomponents.org/polyfills/) should be useful to add support for custom tags (et al.) in browsers with no native implementation . In fact both xtags and polymer claim to rely upon it .

**Comment by Ordiel** [comment]
So... would it be a good idea to reopen this now?
