### ISSUE TITLE
string.format() error

### ISSUE THREAD

**Issue by aaronmatenga** [brython-dev/brython#271]
There is a problem with the string.format function.

If I run this code: ```print("Number: {:.1f}".format(20))```
I get this error:
```
Traceback (most recent call last):
  module __main__ line 70
    doc["add_main"].bind('click', add_main)
  module editor line 102
    undefined
  module editor line 1
    print("Number: {:.1f}".format(20))
ValueError: Unknown format code 'f' for object of type 'int'
<completed in   6.00 ms>
```

If I change the number to 20.0 like this: ```print("Number: {:.1f}".format(20.0))```
It runs, but gives this incorrect output: ```Number: 2e+1.0```

If I format the number to 2dp like this: ```print("Number: {:.2f}".format(20.0))```
It gives the correct output: ```Number: 20.00```

Thanks

**Comment by aaronmatenga** [comment]
Hi,

Does the live editor (http://brython.info/tests/editor.html) use the latest
version of brython? If so, then this issue hasn't been fixed yet.

Thanks,
Aaron

**Comment by PierreQuentel** [comment]
No, brython.info uses the current official release, 3.2.1 at the moment. The bug is fixed in the current development version in the Github repository.
