### ISSUE TITLE
__del__ is not called

### ISSUE THREAD

**Issue by rdb** [brython-dev/brython#275]
This does not seem to cause `__del__` to be called:
```python
class A(object):
    def __del__(self):
        print("DEL CALLED")
a = A()
a = None
```
Am I correct in assuming that this is because Brython does not implement reference counting?  I am creating Brython wrappers for a C++ game engine, and it is imperative that I am able to implement lifetime management.

If there is interest in such a feature, I might be interested in helping to implement it, if I can manage to find the time.  I imagine this could be done by creating $ref() and $unref() methods, calls to which would be injected by py2js.

**Comment by PierreQuentel** [comment]
I confess I didn't know that `__del__` was called in this case. Brython relies on Javascript for garbage collection, so you're right, it doesn't implement reference counting. I don't see it as a top-priority feature, but I'm ok if you can work on it, I'm just worried by the possible overhead of calling methods during the life cycle of an objects.

**Comment by aroberge** [comment]
In addition to the above example, here are two more that result in `__del__` being called in Python but not in Brython:
```python
class A(object):
    def __del__(self):
        print("DEL CALLED")
a = A()
del a
```
and
```python
class A(object):
    def __del__(self):
        print("DEL CALLED")
def test():
     a = A()
test()
```

**Comment by aroberge** [comment]
Using the editor on Brython's site, I have looked at the code generated by
```python
del a
```
The most important part appears to be the following line
```javascript
 delete $locals___main__["a"];
```

If this was replaced by something like
```javascript
try {
    getattr(getattr($locals___main__["a"],"__del__"),"__call__")();
} catch (e) {}
 delete $locals___main__["a"];
```
I believe that it would come quite a bit closer to give the expected behaviour for the cases I have mentioned previously.

**Comment by rdb** [comment]
No, that won't work.  That would also erroneously call __del__ in this case:

    a = b
    del b

Even though it should not.  The only way to solve this is to implement some form of reference counting, given that JavaScript does not currently support finalizers.

**Comment by aroberge** [comment]
On Thu, Dec 24, 2015 at 9:06 AM, rdb <notifications@github.com> wrote:

> No, that won't work. That would also erroneously call *del* in this case:
>
> a = b
> del b
>
> Even though it should not.
>
Good point; I should have thought of that.

**Comment by AbdealiJK** [comment]
I thought you anyway should not rely on `__del__` being called in CPython either - http://stackoverflow.com/questions/6104535/i-dont-understand-this-python-del-behaviour

**Comment by jsbueno** [comment]
Yes  -I think it wouldbe better to proper document that  __del__ is not
called in Brython than to re-wire
everything with reference counting, which will have a heavy impact both on
the code base
and performance - just to enable destructors which every Pythonista know
to be unreliable.

If one needs things to get called in order to free resources, he should use
try:...finally or
contexts ("with" statement). I think both work in Brython.

**Comment by rdb** [comment]
Maybe, but keep in mind that this makes integration with any ASM.js extension modules impossible (such as those implemented in C/C++).  That closes an awful lot of doors.

In particular we were hoping to use brython as scripting language for our WebGL 3D engine, which is written in C++.  It seems that this is not possible due to the lack of reference counting, so we've moved on to transpiling the CPython VM to ASM.js in order to get Python in the browser, which does work well.

**Comment by jsbueno** [comment]
brython is as a thin-layer over javascript as possible.
Javascript does nto do the __del__ thing -

Maybe here could be a special baseclass to be used that would have refernce
counting and a working del?
Would that work for your project?

**Comment by rdb** [comment]
Selective reference counting works, but since in most cases the code generator can't make too many assumptions about the type of object, you still have to pepper the generated code and the built-in functions with ref and unref calls.  I suppose making it an optional feature would work.

**Comment by PierreQuentel** [comment]
This is really too hard to implement in Brython. I'm afraid I have to close this issue without a solution ; I will mention it in the documentation.
