### ISSUE TITLE
off-by-one on last value assigned in for loop over range

### ISSUE THREAD

**Issue by dkosbie** [brython-dev/brython#280]
Hi again.  Here's a code snippet for this issue:
```
for n in range(5):
    pass
print(n)
```
Expected: 4
Observed: 5

Thanks, as always!  :-)

David

**Comment by dkosbie** [comment]
Hi Pierre.  We are still seeing this bug in the most-recent download from rawgit.  Are you sure it was fixed and released?
Thanks.
David

**Comment by PierreQuentel** [comment]
David,

I think I solved it, but didn't add a test in the test suite, so I didn't noticed it had gone back... Sorry about that, should work ok now.

Thanks !
\- Pierre

**Comment by dkosbie** [comment]
Hi Pierre. Great!  Thanks again!  :-)

David
