### ISSUE TITLE
Incorrect line no if error is in while condition

### ISSUE THREAD

**Issue by amrdraz** [brython-dev/brython#281]
![screen shot 2015-09-08 at 3 18 51 pm](https://cloud.githubusercontent.com/assets/1708559/9735730/335459e0-563d-11e5-9df0-8c92dcc4856f.png)

Brython inserts line_info before each line of code is executed
however when looping this is an issue as the line where the condition is checked is never revisited

in this example the error does not occur on line 8 but line 5
however since line_info is not updated at the last line was 8

this was an issue I faced while injecting code with the debugger and worked around it by injecting a trace call with the while statement line number before the closing braces

however during normal runtime I can't go around it and would wind up reporting an incorrect line which will confuse non experts

the solution is to place a `;$locals.$line_info=` with the line number of the while statement right before the closing brackets,  just before line 29 in this case.

**Comment by PierreQuentel** [comment]
Thanks for the report and suggesting the solution ! 

I also fixed the same kind of issue with `for` loops, like in this example :

```python
class A:
    def __iter__(self):
        self.counter = 0
        return self
    
    def __next__(self):
        self.counter += 1
        if self.counter>5:
            1/0
        return self.counter

for x in A():
    print(x)
```
