### ISSUE TITLE
from browser.pydom import get

### ISSUE THREAD

**Issue by miguelalarcos** [brython-dev/brython#284]
gives me the error:
```
Traceback (most recent call last):
  module __main__ line 70
    undefined
  module editor line 102
    undefined
  module editor line 1
    from browser.pydom import get
ImportError: cannot import name 'get'
```

I've followed the examples I've found about `pydom`.

**Comment by PierreQuentel** [comment]
Hi,

Many thanks for the report !

pydom was removed from package browser some time ago, so the problem here was that `import browser.pydom` should have raised `ImportError`. I fixed this in the commit reference above.

**Comment by miguelalarcos** [comment]
Is `pydom` imported from another module or is it dead? Thanks for your attention.

**Comment by kikocorreoso** [comment]
I think it is dead but maybe it is better to ask @earney 

BTW, you could use directly jQuery.

Read this thread for more info: https://groups.google.com/forum/#!msg/brython/qQWt01ilLYo/L-0PBsF8ehIJ

**Comment by miguelalarcos** [comment]
ah, ok thanks. I will use `pyquery.py` from [brython-pyquery](https://bitbucket.org/billyearney/brython-pyquery)

**Comment by earney** [comment]
I haven't done anything with pydom in quite a while, so it is probably safe
to consider it dead..
