### ISSUE TITLE
"a".count("") hangs

### ISSUE THREAD

**Issue by dkosbie** [brython-dev/brython#288]
Hi all.  Here is the code:
```
print("a".count(""))
```
Expected:  2
Observed: [hangs]

Thanks!

David

**Comment by PierreQuentel** [comment]
This is true on brython.info (ie version 3.2.1), but I get the correct result with the latest version (after commit 11795ede87466f461d0c776974523ed3fb32e930, also available through rawgit. Can you check which version you tested this on ?

**Comment by dkosbie** [comment]
Hi Pierre.  In fact, I was using a version from a week or so ago.  I just updated to the latest/greatest, and indeed the problem is gone.  Great!  Sorry for the misdirect, and nice job!  :-)

David
