### ISSUE TITLE
DOMParser cannot be instantiated via JSConstructor

### ISSUE THREAD

**Issue by toyg** [brython-dev/brython#291]
```python
import javascript
DOMParser = javascript.JSConstructor(window.DOMParser)
dp = DOMParser()
```
results in 

    Internal Javascript error: TypeError: undefined is not an object (evaluating 'self.func.bind')
    module 'editor' line 3
     dp = DOMParser()

**Comment by kikocorreoso** [comment]
The following example adapted from [here](http://www.w3schools.com/XML/dom_intro.asp) is working for me:

```
from browser import window
from javascript import JSConstructor

dp = JSConstructor(window.DOMParser)()

text = """<bookstore><book><title>Everyday Italian</title><author>Giada De Laurentiis</author><year>2005</year></book></bookstore>"""

xmlparser = dp.parseFromString(text, "text/xml")
print(xmlparser.getElementsByTagName("title")[0].childNodes[0].nodeValue)
```

You can test it [here](http://brython.info/tests/editor.html?lang=en).

**Comment by toyg** [comment]
Could it be that I didn't import browser.window in my original tests, but referred to "window" directly? I guess I mistakenly used the pure-javascript window object. 

Considering ElementTree and other XML modules in stdlib don't seem to be usable, maybe this snippet should go in the cookbook.

Thanks for your help!
