### ISSUE TITLE
list.count when take in 2 arg should crash

### ISSUE THREAD

**Issue by bernie850204** [brython-dev/brython#292]
a = [ 2, 3, 5, 2, 6, 2, 2, 7 ]
print("a          =", a)
print("a.count(1) =", a.count(1))
print("a.count(2) =", a.count(2))
print("a.count(3) =", a.count(3,7)) #Brython gives 1 while standard python gives syntax error

**Comment by kikocorreoso** [comment]
I close the issue as it is fixed on #293 

If you it's not fixed, please, re-open the issue.
