### ISSUE TITLE
Slice assignment with step a[i:j:k] = b

### ISSUE THREAD

**Issue by dkosbie** [brython-dev/brython#299]
Hi again.  For us, this is lower-prio, but alas, here it is:
```
a = [1, 2, 3]
a[0:3:2] = [ 4, 5 ]
print(a)
```
Expected: [4, 2, 5]
Observed: [4, 5]

Thanks again.

David

**Comment by PierreQuentel** [comment]
Thank you for the reports, precious as always !

I have started using more systematically the built-in CPython test suite, located in Lib/test, to detect and fix bugs. Brython now passes most of the tests for str, list, set and frozenset types. I plan to go on with the other built-in types, then work on modules in the stdlib.
