### ISSUE TITLE
tuples are mutable

### ISSUE THREAD

**Issue by dkosbie** [brython-dev/brython#301]
Hi all.  This one was buried in #297 (tuples acting as lists), and while the other items in that issue were resolved, this one seems to still be active...
```
t = (1, 2)
t[0] = 42  # should crash: TypeError: 'tuple' object does not support item assignment
print(t) 
```
Expected: crash
Observed: (42, 2)

Also, I think it's a great plan to use the CPython test suite.  That's basically the gold standard...

And thanks again for your rapid turnaround on these issues.  We really appreciate it!

David

**Comment by kikocorreoso** [comment]
There is some messy code here. I will fix it and then ask @PierreQuentel to dig deeper in order to improve the code.
