### ISSUE TITLE
for in has extra and missing line_info depending on the case

### ISSUE THREAD

**Issue by amrdraz** [brython-dev/brython#305]
![screen shot 2015-09-29 at 9 31 23 pm](https://cloud.githubusercontent.com/assets/1708559/10175899/d5c808b0-66f1-11e5-877e-5ce6fe58583d.png)

So if you have a for in with a iterator

    l = [2,3,55,6]
    for i in l:
        print(i)

you would get 2 line_info trace set before the loop starts

```    
    $locals___main__["l"]=[2,3,55,6];
    ;$locals.$line_info="3,__main__";
    $locals["$next96"]=getattr(iter($locals___main__["l"]),"__next__");

    ;$locals.$line_info="3,__main__";
while(1) {
 try{
        $locals___main__["i"]=$locals["$next96"]();
    }
    catch($err){if($B.is_exc($err,[StopIteration])){delete $locals["$next96"];break;}else{throw($err)}}
    ;$locals.$line_info="4,__main__";
    getattr(print,"__call__")($locals___main__["i"]);
    $locals.$line_info="3,__main__";
}
```

and if you have for in called on a function that returns an iterator _specifically range()_

```
for i in range(len(l)):
    print(l[i])
```

you get

```
;$locals.$line_info="7,__main__";
function $f97(){
    $locals___main__["i"]=0;
    var $stop_97=$B.$GetInt(getattr(len,"__call__")($locals___main__["l"])),
        $next97= $locals___main__["i"],
        $safe97= typeof $next97=="number" && typeof $stop_97=="number";
    while(true){
        if($safe97 && $next97>= $stop_97){break}
        else if(!$safe97 && $B.ge($next97, $stop_97)){break}
        $locals___main__["i"] = $next97
        if($safe97){$next97+=1}
        else{$next97=$B.add($next97,1)}
        ;$locals.$line_info="8,__main__";
        getattr(print,"__call__")($B.list_key($locals___main__["l"], $locals___main__["i"]));
    }
}
var $res97=$f97();
```

which does not append a `;$locals.$line_info="7,__main__";` before the end of the generated while loop like every other loop

**Comment by amrdraz** [comment]
it really isn't an issue that causes any error other than make my debugger rely on small quirks and special cases than just trace based on the appearance of line_infos

unlike the other similar issue I had reported with the while loop, with the for loop there probably won't be an issue other than inconsistency of code output with the current state of affairs. errors will probably always be reported correctly

**Comment by PierreQuentel** [comment]
Amr,

Thanks for reporting this. I have added the missing line info in `range()` loops, but not removed the duplicate ones for other loops : it's necessary to have it before getting the attribute `__next__` and removing it before the while loop would be a special case among all other "while" loops. If you think it should absolutely be removed feel free to reopen the issue.
