### ISSUE TITLE
SVG element from SVGElement.getIntersectionList cannot be put into a dict

### ISSUE THREAD

**Issue by conversy** [brython-dev/brython#306]
Hello,

I get this exception:

module __main__35 line 389
    hits.add(h)
AttributeError: object has no attribute __eq__

with this code:

hits_ = svgelt.getIntersectionList(selection_rect.getBBox(), scene)
#hits = set(hits_)
hits = set()
for h in hits_:
	hits.add(h)

**Comment by kikocorreoso** [comment]
Could you provide a complete example to try to reproduce the issue?

**Comment by conversy** [comment]
sure:


<svg id="panel"></svg>
<script type="text/python">
from browser import document, svg

titre = svg.text('Titre', x=70, y=25, font_size=22,
                 text_anchor="middle")
cercle = svg.circle(cx=70, cy=120, r=40,
                    stroke="black",stroke_width="2",fill="red",id="foo")
panel = document['panel']
panel <= titre
panel <= cercle

selection_rect = svg.rect(x=0, y=0, width=1000, height=1000, stroke_width=1, stroke="black", fill=None)
panel <= selection_rect
hits_ = panel.getIntersectionList(selection_rect.getBBox(), panel)

hits = set(hits_) # this instruction will fail
print(hits)

</script>

**Comment by conversy** [comment]
Well I tried to bissect a litlle bit. It seems that...
- ...2.1.0 does work
- ...2.2.0 does not work

**Comment by kikocorreoso** [comment]
I think you mean 3.1.0 and 3.2.0

It seems `hits_` is a js object. A direct conversion to a `set` shouldn't work out of the box. A `list` works.

In the brython console I typed the following (activate the 'main' div button as it is used by the code):

```
from browser import document, svg, window

document['main'].html = """<svg id="panel"></svg>"""

titre = svg.text('Titre', x=70, y=25, font_size=22,
                 text_anchor="middle")
cercle = svg.circle(cx=70, cy=120, r=40,
                    stroke="black",stroke_width="2",fill="red",id="foo")
panel = document['panel']
panel <= titre
panel <= cercle

selection_rect = svg.rect(x=0, y=0, width=1000, height=1000, stroke_width=1, stroke="black", fill=None)
panel <= selection_rect
hits_ = panel.getIntersectionList(selection_rect.getBBox(), panel)

hits = list(hits_) # this instruction will fail
for hit in hits:
    print(hit)
```

And it returns

```
<DOMNode object type 'ELEMENT' name 'text'>
<DOMNode object type 'ELEMENT' name 'circle'>
<DOMNode object type 'ELEMENT' name 'rect'>
```

I hope it helps.

**Comment by conversy** [comment]
no I really mean 2.1.0 and 2.2.0. I have tested it again to make sure.

So there was a change between 2.10 and 2.2.0 that prevents, not constructing a dict directly (which I could avoid), but putting svgelements in a dict (and my code relies on that).
Either this change is a mistake, or it's a change of policy, in which case I have to change my code.

Thanks for helping !

**Comment by PierreQuentel** [comment]
I tried Kiko's code in the editor and got : 

`AttributeError: 'DOMNode' object has no attribute 'getIntersectionList'`

It seems that `getIntersectionList` is no longer implemented in Firefox, see [this issue](https://bugzilla.mozilla.org/show_bug.cgi?id=501421)

This is confirmed by the fact that this Javascript code

```xml
<script>
alert(document.getElementById('panel').getIntersectionList)
</script>
```

pops up 'undefined'
