### ISSUE TITLE
urllib is not working

### ISSUE THREAD

**Issue by cetoli** [brython-dev/brython#308]
## Test Code

```python
import urllib.request
response = urllib.request.urlopen('http://python.org/')
```
### Expected
Ok
### Actual

```python

Internal Javascript error: NS_ERROR_FAILURE: <[Exception... "Failure"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: http://www.brython.info/src/py_import.js line 140 > eval :: ajax.$dict.send :: line 68"  data: no]>
<completed in 548.00 ms>

```

## Test Environment

Brython version: 3.2.2 (on line editor)

Ubuntu Gnome 14.04 - Firefox 40

**Comment by PierreQuentel** [comment]
I also get an error in this case, but it's because of the cross-origin policy : in a script running in a domain you can only access the urls in the same domain.

I tried in the console with 

```python
import urllib.request
response = urllib.request.urlopen('editor.py')
print(response.read())
```

There was no such error, but response was not set correctly, this was fixed in the commit referenced above. I now get the source code of `editor.py` as expected.

The implementation of urllib.request is still minimal. Do you prefer to leave this issue open, or to create another one if other features of this module are required ?

**Comment by aroberge** [comment]
In spite of the cross-origin policy, it is still possible to access URL from other domains.  I have done this sucessfully using jquery by using
https://github.com/aroberge/reeborg/blob/master/src/js/aa_utils.js#L196

**Comment by kikocorreoso** [comment]
the following works:

```
`library = "brythonmagic"
url = 'https://pypi.python.org/pypi/{}/json'.format(library)
print(url)
info = open(url).read()
print(info)
```
Tested http://brython.info/tests/editor.html?lang=en some seconds ago.

**Comment by stroobandt** [comment]
Could we reopen this?
kikocorreoso's example works because the response happens to be a single json entity.
However what about this:
```python
url = 'http://lgdc.uml.edu/common/DIDBGetValues?ursiCode=DB049&charName=foF2'
print(url)
info = open(url).read()
print(info)
```
On <http://brython.info/tests/editor.html?lang=en>, it results in the following error:
```
[Exception... "Cannot modify properties of a WrappedNative"
nsresult: "0x80570034 (NS_ERROR_XPC_CANT_MODIFY_PROP_ON_WN)"
location: "JS frame :: http://brython.info/src/py_exceptions.js :: $B.exception :: line 253"  data: no]
```

**Comment by PierreQuentel** [comment]
As you probably know, [cross-origin requests](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing) (ie Ajax requests from domain A to a url in domain B) are possible, but only if the server in domain B returns specific headers.

Kiko's example works because the server at _https://pypi.python.org/pypi_ sends the response header `Access-Control-Allow-Origin: *`, which allows Ajax requests from all origins.

The servers in Carlo's and Serge's example don't send this header, so the Ajax calls fail. 

Unfortunately André's example is no more on line but I'm also sure it's the same thing, the server sent the CORS header.

**Comment by aroberge** [comment]
On Mon, May 2, 2016 at 5:04 PM, Pierre Quentel <notifications@github.com>
wrote:

> As you probably know, cross-origin requests
> <https://en.wikipedia.org/wiki/Cross-origin_resource_sharing> (ie Ajax
> requests from domain A to a url in domain B) are possible, but only if the
> server in domain B returns specific headers.
>
> Kiko's example works because the server at *https://pypi.python.org/pypi
> <https://pypi.python.org/pypi>* sends the response header Access-Control-Allow-Origin:
> *, which allows Ajax requests from all origins.
>
> The servers in Carlo's and Serge's example don't send this header, so the
> Ajax calls fail.
>
> Unfortunately André's example is no more on line but I'm also sure it's
> the same thing, the server sent the CORS header.
>

Actually, my code is still online ... however, I'm using Javascript for
most of my site, and Brython only for Python execution, so it may not be
useful for pure Brython sites.

I am using CORS; the code I use for ajax requests (other than
Python/Brython imports) is a modification of the basic jQuery ajax code

https://github.com/aroberge/reeborg/blob/master/src/js/utils/cors.js

André

**Comment by stroobandt** [comment]
Thank you for answering, Pierre. I was indeed suspecting cross-origin related matter.
HOWEVER, quoting from your [Wikipedia reference about cross-origin requests](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing):

> For AJAX and HTTP request methods that can modify data (usually HTTP methods other than GET, [...] ), the specification mandates that browsers "preflight" the request, [...]

All, I am trying to achieve is a GET request, so there should be a way to do is as a GET request, even when the server is not sending any special header. The only question is how?

**Comment by stroobandt** [comment]
When I try the following GET request code on <http://brython.info/tests/editor.html?lang=en>,
I no longer get any errors.
However, neither do I see the desired text in the output, apart from  `<completed in  56.00 ms>` and all in spite of my `print(req.text)` commands.
Am I again overlooking something obvious? I just need a little more help with this. Thanks in advance!
```python
from browser import document as doc
from browser import ajax

def on_complete(req):
    if req.status==200 or req.status==0:
        print(req.text)
        doc["main"].html = req.text
    else:
        print(req.text)
        doc["main"].html = "error "+req.text
        
def get(url):        
    req = ajax.ajax()
    req.bind('complete',on_complete)
    # pass the arguments in the query string
    req.open('GET',url,True)
    req.set_header('content-type','application/x-www-form-urlencoded')
    req.send()

get('http://lgdc.uml.edu/common/DIDBGetValues?ursiCode=DB049&charName=foF2')
```

**Comment by stroobandt** [comment]
The reason for the above code not working, is the following error I get in Chromium:
> XMLHttpRequest cannot load http://lgdc.uml.edu/common/DIDBGetValues?ursiCode=DB049&charName=foF2. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://brython.info' is therefore not allowed access.

This looks like an implementation bug to me. According to [Wikipedia](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing), GET requests should always be allowed, despite the absence of  any `Access-Control-Allow-Origin` header from the resource.

**Comment by stroobandt** [comment]
For a GET request to pass without any `Access-Control-Allow-Origin` header from the resource server, I will need to get rid of all custom headers in my GET request to stay within the green:
![flowchart](https://upload.wikimedia.org/wikipedia/commons/c/ca/Flowchart_showing_Simple_and_Preflight_XHR.svg)
No luck yet with `req.set_header('custom-xid-header', None)`
Any custom header removal tricks for my request are more than welcome!

**Comment by stroobandt** [comment]
Even though [certain request headers can be removed](https://stackoverflow.com/questions/2464192/how-to-remove-http-specific-headers-in-javascript), those of interest are [protected by the browser](http://stackoverflow.com/a/9223680/2192488). So the above was a bit of wishful thinking from my behalf.

The only way around this for resources that are outside one's reach of control, is by running a proxy script on your own server. The [AJAX Cross Domain](http://www.ajax-cross-domain.com/) script looks particularly nice.

Luckily, [Brython can read JavaScript objects](http://brython.info/static_doc/en/jsobjects.html), but perhaps one should delve into the ACD Perl code to see if it can spit out native Brython objects.

**Comment by stroobandt** [comment]
OK, I got JSON AJAX Cross Domain requests working at <http://hamwaves.com/nvis/en/index.html>.
The use of a proxy at the server is inevitable though.

**Comment by JiangLan2333** [comment]
Hi, I also got an error when importing the urllib.parse.
I tried in the console with
`import urllib.parse`
but got 
`ImportError: cannot import name 'unicode_iscased`

**Comment by JiangLan2333** [comment]
Also when I tried in the console with 

`req = urllib.request.Request()`

I got

`AttributeError: 'module' object has no attribute 'Request'`
