### ISSUE TITLE
Multiline string declaration

### ISSUE THREAD

**Issue by aaronmatenga** [brython-dev/brython#315]
Declaring a multiline string like the following should cause an error:

```
my_string = "This string
should not
be valid"
```

However, it is running as though it were declared correctly. As far as I know, the correct ways to declare a multiline string are:

```
my_string = """This string
should
be valid"""

my_string = ("This string"
"should"
"be valid")
```

Is there something I am missing?

**Comment by PierreQuentel** [comment]
Thanks for the report. This bug must have been there for ages !
