### ISSUE TITLE
[bug] eval doesn't take -1

### ISSUE THREAD

**Issue by amrdraz** [brython-dev/brython#318]
`eval()` throws an error if I enter `-1` or any number starting `-`
![screen shot 2015-10-23 at 11 21 30 am](https://cloud.githubusercontent.com/assets/1708559/10688996/7040ef86-7978-11e5-9699-0bf63cce8e00.png)

**Comment by PierreQuentel** [comment]
Thanks Amr. Those little unary operators are a nightmare to implement.
