### ISSUE TITLE
[bug] error reporting for miss indented else and elif

### ISSUE THREAD

**Issue by amrdraz** [brython-dev/brython#320]
the brython parser does not report a proper python syntax error when encountering a mis indented else or elif

it throws an Internal Javascript error (with no line info) when it should throw a syntax error with proper line

![screen shot 2015-10-26 at 1 17 28](https://cloud.githubusercontent.com/assets/1708559/10718585/5d30f8ba-7b7f-11e5-8aae-e0453eebda01.png)

**Comment by PierreQuentel** [comment]
Thanks for the report. I also fixed other similar bugs, eg "except" not following "try", "finally" not following "try", "except" or "else", etc.
