### ISSUE TITLE
[enhancement] not reporting overfllow error

### ISSUE THREAD

**Issue by amrdraz** [brython-dev/brython#321]
The following piece of code

```
int(float(100)**float(1000))
```

The python console throws this error

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: (34, 'Result too large')
```

brython interpreter throws

```
Internal Javascript error: TypeError: $B.LongInt.$dict.$from_float is not a function
  module 'exec_17' line 1
int(float(100) ** float(100))
```

**Comment by kikocorreoso** [comment]
`OverflowError` is platform dependent on CPython. 

Do you have any idea about how this could be performed in JS?

Do you have any idea if the different browsers on different platforms are different regarding this?

Do an `OverflowError` be enough when brython/js returns `Infinity`?

I can see a lot of corner cases managing this but I don't have enough knowledge.

**Comment by PierreQuentel** [comment]
Currently `int(float(100)**float(1000))` returns `Infinity`, I think it's ok for the platform where Brython runs.
