### ISSUE TITLE
Multiple zero integer literals (e.g. 00...) cause syntax error

### ISSUE THREAD

**Issue by Ernest0x** [brython-dev/brython#322]
I was playing with brython editor (brython version 3.2.2) and found out that a multiple zero value causes a syntax error instead of being handled as a single zero value input as it is the case with CPython (tried with both 3.5.0 and 2.7.10).

CPython:
``` 
>>> print(00)
0
```

Brython (3.2.2):
```
Traceback (most recent call last):
  module __main__ line 71
    undefined
  module editor line 99
    traceback.print_exc(file=sys.stderr)
  module __main__ line 1
    print(00)
       ^
SyntaxError: invalid syntax
<completed in  14.00 ms>
```

According to the [standard](https://docs.python.org/3.5/reference/lexical_analysis.html#integer-literals), multiple zero integer literals are indeed allowed.

**Comment by kikocorreoso** [comment]
PR #323 fixes this issue.

If you find any related issue, please, open again this issue.

**Comment by PierreQuentel** [comment]
Thank you Kiko. I'm glad I waited until someone else fixes this ;-)

**Comment by kikocorreoso** [comment]
And we get a new contributor (@Ernest0x)  fixing my bugs.(#324)!!

:-D
