### ISSUE TITLE
Traceback on list comprehension in sys.py

### ISSUE THREAD

**Issue by rbarve** [brython-dev/brython#325]
Included a utility module bry_utils in Lib in local install; which imports sys and then imported bry_utils in a script tag in the src for a frame; and I get the below traceback. 

```
Traceback (most recent call last):
  module __main__ line 2
    import bry_utils
  module bry_utils line 1
    import sys
  module sys line 44
    version ='.'.join (str (x )for x in __BRYTHON__ .version_info [:3 ])
  module sys line 2
    from _sys import *
ImportError: [bry_utils]
```

**Comment by kikocorreoso** [comment]
Could you post your `bry_utils` module and a minimum example of the html code where it raises the error?

**Comment by rbarve** [comment]
bry_utils:
=========
import sys
import traceback
from javascript import JSConstructor, console
from javascript import JSConstructor, JSObject
from browser import document, window


idForTextArea = None

def setupLogTextArea(TextAreaId):
   global idForTextArea
   idForTextArea = TextAreaId

def write(data):
   if (window.jQuery!= None) and (idForTextArea!=None) :
      JQ=window.jQuery
      JQ('#'+idForTextArea).val(JQ('#'+idForTextArea).val() + "\n"+ data)
   else:
      console.log(data)


sys.stdout.write = sys.stderr.write = write

============
html frag -- is the src for a child frame created by including some js libs in head:
=========
      /static/libs/jquery/dist/jquery.min.js,
      /static/libs/jquery-ui/jquery-ui.custom.min.js',
      /brython/src/brython.js,
      /brython/src/acorn.js,
      /brython/src/interpreter.js,
      /brython/src/maindebugger.js,
      /brython/src/py_VFS.js,
========
maindebugger.js is main.js from debugger dir
py_VFS incorporates the directory debugger which I make a subdir of src/Lib
followed by a brython script also in head whose first two lines  :
========
import bry_utils
import debugger  #playing with recent debugger

**Comment by kikocorreoso** [comment]
This line:

`sys.stdout.write = sys.stderr.write = write`

is provoking a 

`RecursionError`

Maybe the error is related with this. `import sys` works for me with no issues...

Please, can you change that and let me know if it works? Maybe, if you explain what you want to do with the *stderr* and/or *stdout* we can provide a better solution.

**Comment by kikocorreoso** [comment]
@rbarve Could this issue be closed?
