### ISSUE TITLE
http://www.brython.info/gallery/sort_table.html - not working

### ISSUE THREAD

**Issue by jnowl** [brython-dev/brython#331]
Not working in FF or i.e.
FF shows page, but no data, i.e. does not show anything

**Comment by kikocorreoso** [comment]
Neither on Chrome.

It works in the git repo. It seems a problem in the deployment.

@PierreQuentel Could you have a look on it? I don't see any errors in the js console when I access the page on bython.info.

**Comment by PierreQuentel** [comment]
Hi,

Thank for the report. There was a bug that I noticed after updating brython.info and fixed a few weeks ago, as Kiko says it works in the current development version. I close the issue.

**Comment by jnowl** [comment]
Thanks for the tool!
