### ISSUE TITLE
Update of www/doc/en/dev_env.md to FR

### ISSUE THREAD

**Issue by kikocorreoso** [brython-dev/brython#333]
Update for development environment doc to French.

This [file](https://github.com/brython-dev/brython/blob/master/www/doc/fr/dev_env.md) should be updated with the latest changes in the [english version](https://github.com/brython-dev/brython/commits/master/www/doc/en/dev_env.md).

**Comment by aroberge** [comment]
This issue appears to have been addressed by a commit done by @PierreQuentel on Nov. 21.

**Comment by kikocorreoso** [comment]
The main idea of this issue was to encourage other people to help with the project creating easy-to-fix issues...

**Comment by aroberge** [comment]
I understand ...   I was going to fix it myself but hit a bump on the road as I had not made my own fork of Brython, but only a copy.  When I attempted to update, I realized this as I (obviously) did't have permission to do so.  It is only then that I noticed that Pierre had fixed this.
