### ISSUE TITLE
[enhancement] list.sort(key=func) calls func() twice per comparison

### ISSUE THREAD

**Issue by cben** [brython-dev/brython#337]
When sorting with a custom `key` function, current `$qsort()` code path ends up calling the function twice per comparison:
https://github.com/brython-dev/brython/blob/3.2.3/www/src/py_list.js#L446-L450

It'd be much faster to call it just once per element, and only use __le__ during sorting (probably using 2 arrays and swap()ping on both in parallel).
I've got a 14sec -> 1.5sec speedup on sorting just 184 elements, by coding decorate-sort-undecorate in my python source (my comparison function computed a list comprehension).

I could write a PR but not soon.

**Comment by kikocorreoso** [comment]
@cben This would be very welcome!! Thanks.

Performance improvements are always a big win.

**Comment by PierreQuentel** [comment]
Hello,

I am reviewing old issues and don't think a PR was submitted for this. Do you think you can write one ?

Thanks,
Pierre

**Comment by cben** [comment]
Thanks for the reminder, forgot about it.  Will try in the next few days.
26 марта 2016 г. 16:59 пользователь "Pierre Quentel" <
notifications@github.com> написал:

**Comment by PierreQuentel** [comment]
I close the issue, please submit a PR when the fix is done.
