### ISSUE TITLE
Internal Javascript Error should be a NameError

### ISSUE THREAD

**Issue by aroberge** [brython-dev/brython#338]
The following program
```python
def plus():
    global a
    print(a)

plus()
```
yields
```
Internal Javascript error: TypeError: Cannot read property '$nat' of undefined ...
```
instead of
```
NameError: name 'a' is not defined
```

Apologies for the piecemeal reporting of these types of bugs.  I am finding them as I'm attempting to write a tutorial for beginners, making sure that I cover all relevant context.   Note that I do not plan (so far) to cover the use of ``nonlocal``; there could be other scope related problems lurking there.

**Comment by PierreQuentel** [comment]
Merci André. These are issues that should not still be present after 3 years of development...

It was also the opportunity to discover that this code : 

```python
def f():
    global x
    x = 1
f()
print(x)
```
binds the name `x` in the global namespace.

**Comment by aroberge** [comment]
On Thu, Dec 3, 2015 at 11:45 AM, Pierre Quentel <notifications@github.com>
wrote:

> Merci André. These are issues that should not still be present after 3
> years of development...
>


Brython users are more experienced programmers that would not make these
silly mistakes.


> It was also the opportunity to discover that this code :
>
> def f():
>     global x
>     x = 1
> f()print(x)
>
> binds the name x in the global namespace.
>
Oh, excellent!
