### ISSUE TITLE
Syntax error raised when using Firefox but not Chrome.

### ISSUE THREAD

**Issue by aroberge** [brython-dev/brython#345]
When importing one of my modules, I get a SyntaxError raised by Brython when used in Firefox but not when used in Chrome.  This can be seen by going to http://reeborg.ca/world.html

The error raised in Firefox is:
```
Traceback (most recent call last):
  module __main__ line 5
    import common_def
  module common_def line 3
    from highlight import insert_highlight_info
SyntaxError: invalid syntax,highlight,30,1,watch = indent + watch_string
```
The offending line appears to be
https://github.com/aroberge/reeborg/blob/master/src/python/highlight.py#L30

I have tried to reformat my code in various ways, including commenting out everything related to "watch" in that function (and replacing the return on the last line).   Again, everything works well with Chrome but with Firefox, I get the following traceback:
```
Javascript error Exception { message: "", result: 2147500037, name: "NS_ERROR_FAILURE", filename: "http://cdn.rawgit.com/brython-dev/b…", lineNumber: 9752, columnNumber: 0, inner: null, data: null, stack: "DOMNodeDict.__getattribute__/func</…" }
```
Apparently, NS_ERROR_FAILURE are "common" when using Firefox.

I've looked at what happend when increasing the debug level to 10, but didn't see anything that seemed particularly useful.

I've tried loading different versions of brython, but always got the same error.   As far as I know, Firefox was still working when I was using a version of Brython hosted "locally" with my python modules located in Lib/site-packages ... but that may be a red-herring.  However, if thought to be useful, I could try to do this again and see if it makes a difference.

**Comment by aroberge** [comment]
The problem is with Firefox (v 42.0 only?), not Brython.

Keeping my own modules, I reverted back to using an old version of Brython (implementation [3, 2, 0, 'alpha', 0]) which I had been using for a long time without problems; instead of loading it from the CDN, I had the entire distro running locally, and imported my modules from /Lib/site-packages.  It doesn't work with Firefox.

I even tried a much older version (that used Brython's implementation [3, 0, 0, 'final', 0]) and which I had kept on my site (under http://reeborg.ca/world_old.html).  Again, it doesn't work with Firefox v 42.0.

Running Brython's server (and testing in editor.html) with Firefox 42.0 runs just fine.

I do not know how to provide a simpler test case at this point.

**Comment by aroberge** [comment]
I have managed to narrow down the source of the problem to a single module I wrote, but this is not enough (yet) to make it worth for a Brython core developer to investigate. Still, I believe it is useful to document this issue in case others encounter something similar.

The issue is present with the newer Firefox version (43).  The code works fine with Chrome, Opera and Microsoft Edge.  By using a `try/except` clause, I can effectively disable the offending module (without doing browser detection in Python) and have most of the functionality work when using Firefox.

**Comment by kikocorreoso** [comment]
Quite weird!!

**Comment by aroberge** [comment]
In investigating it further and rewriting some code, my try/except approach no longer works.  I asked a question on the brython discussion list in order to find a better approach.

**Comment by aroberge** [comment]
I believe that the source of the error is the use of the name "watch" as a variable name.  I would like if someone could confirm this.  I used python -m http.server to run these files.   In the html file, a function is called with the argument "watch". With Firefox, an error appears in the console.  If I change the name to something else (e.g. `awatch`) the error disappears.  

Here's the content of an html file which you can use to reproduce the problem (copy-pasted from my editor):
```html
<!DOCTYPE HTML>
<html lang="en">
<head>
<meta charset="utf-8">

<title>Dumb test</title>
<script type="text/javascript"
    src="http://cdn.rawgit.com/brython-dev/brython/3c551ae3bf6d29191f7f62bf0d2ce987d70fc340/www/src/brython.js">
</script>

</head>
<body onload="brython({debug:1, pythonpath:['/src/python']})">

<script type="text/python3">
from browser import window
from _importlib import optimize_import_for_path
optimize_import_for_path('/src/python', 'py')
from import_test import test

def a_test(watch):
     test(var_watch)
</script>

</body>
</html>
```

And here's the imported python file
```python
def test(var_watch):
    pass
```

**Comment by kikocorreoso** [comment]
I confirm it on FF43.0.1

It seems it is related with [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/watch).

More context: 

https://github.com/janl/mustache.js/issues/442

http://www.bennadel.com/blog/2854-angularjs-in-firefox-typeerror-missing-argument-1-when-calling-function-b-get.htm

...
