### ISSUE TITLE
hashlib.(md5, sha1...).hexdigest() always returns the same value

### ISSUE THREAD

**Issue by frwendling** [brython-dev/brython#353]
Hi, 

I tried to display the md5/sha1/etc... of a string dynamically but it always return the same value.

Example with md5: (doesn't work with stable release as well)

```html
<html>
    <head>
    <script type="text/javascript" 
    src="https://cdn.rawgit.com/brython-dev/brython/master/www/src/brython.js">
    </script>

    </head>
    <body onload="brython(1)">
        <input id="text"/>
        <span id="result"></span>
        <script type="text/python">
        from browser import document, alert
        from hashlib import md5
        

        def getresult(event):
            plop = document['text'].value
            alert(plop)
            alert(md5(plop).hexdigest())
        
        document['text'].bind('keyup', getresult)
        </script>
    
    </body>
</html>
```

At first i thought that i did something wrong, so i tried directly in the console and the problem is still here : 

![2015-12-21-113646_1268x332_scrot](https://cloud.githubusercontent.com/assets/6283304/11929027/2ca6fcf0-a7d8-11e5-8c34-3f87ef3777ba.png)

**Comment by PierreQuentel** [comment]
Thank you for the bug report. The hashlib module works better but I don't use it at all, so if you find other issues you can reopen this issue.
