### ISSUE TITLE
Compilation failure when a function parameter is a JS reserved word.

### ISSUE THREAD

**Issue by ioctl79** [brython-dev/brython#355]
The following script fails to compile:

def foo(enum): pass

**Comment by ioctl79** [comment]
Fails on the interactive console, too, of course.

<img width="1260" alt="screen shot 2015-12-29 at 1 14 51 am" src="https://cloud.githubusercontent.com/assets/7168016/12030785/99b92312-adc9-11e5-92ca-0f80f5755943.png">

**Comment by kikocorreoso** [comment]
Hi,

I think it is failing due to the use of a debugger added some months ago (https://github.com/brython-dev/brython/blob/e4fa8fa38f7ab297caa042264f0204d69435207e/www/tests/debugger/acorn.js#L399).

Right now I can't but this afternoon (in Western Europe) I could have a look.

BTW, there are better names for a variable :stuck_out_tongue_winking_eye:

**Comment by ioctl79** [comment]
Unfortunately, this is generated code (from protobuf) =)

**Comment by kikocorreoso** [comment]
Having a (slightly) deeper look it seems it could be related with how function arguments are parsed. `enum` can be used in other brython contexts without any problem but it fails when it is included in a function argument, lambda function, class method,... It works as a function keyword:

For instance, the following works:
```python
def foo(enum = None):pass

def foo(_enum):
    enum = _enum
```

The following fails:
```python
# example1
class kk:
    def __init__(self, enum):
        pass

## example 2
lambda enum: enum

## example 3
def foo(enum): pass
```

It happens the same with other ES5 reserved words like `extends`,...

**Comment by PierreQuentel** [comment]
Hi,

Brython stores a list of Javascript reserved identifiers in the list `$B.forbidden` in __py2js.js__ (it replaces `var` by `$$var` for instance). Unfortunately the list is not normalised, at least I couldn't find an official one. Adding 'enum' to the list solves the problem. Kiko, can you fix this and add other reserved names if necessary ?

**Comment by kikocorreoso** [comment]
Of course.

I found some issues with other var names.

I will fix it tomorrow if I find the time.

**Comment by kikocorreoso** [comment]
I think it should be fixed now. 

@ioctl79 if you find any new issue, please, reopen the issue.

Happy new year.
