### ISSUE TITLE
Full unicode support for identifiers

### ISSUE THREAD

**Issue by aroberge** [brython-dev/brython#358]
A while ago, Brython's unicode support was improved to allow for (some) utf-8 encoded identfiers; however, its support is not as complete as that of Python.  For example, the following Korean example works with Python
```python
def 안녕하세요():
    print("hello")
    
안녕하세요()
```
but not with Brython.  Note that the comparable javascript code
```javascript
function 안녕하세요(){
    alert("hello");
    }

안녕하세요();
```
also produces the desired result.  It would be helpful if Brython's unicode support could be improved to allow the use of any utf-8 encoded identifier considered to be valid by Python.

If I could be pointed out where the current unicode handling is done (I scanned py2js and could not find it), I could attempt to help with this issue.

Edit: I gather that the relevant code is in https://github.com/brython-dev/brython/blob/master/www/src/identifiers_re.js

**Comment by aroberge** [comment]
I realize that valid Javascript identifiers are not exactly the same as Python valid identifiers but could the current regex be replaced by https://github.com/mathiasbynens/mothereff.in/blob/master/js-variables/tools/javascript-identifier-regex.js (with the exclusion of `$` of course).  This would likely mean that more valid Python identifiers would be recognized as such.  In particular, the Korean example I gave would be recognized as being valid:
https://mothereff.in/js-variables#%EC%95%88%EB%85%95%ED%95%98%EC%84%B8%EC%9A%94

**Comment by PierreQuentel** [comment]
André,

Thinking again about this, I realised that there is a very simple solution : test if a succession of characters in the Python source is a valid Javascript identifier by testing if `eval("dummy."+name)` raises an exception.

It is actually a little more complex ('$' is valid in Javascript but not in Python, if `name` ends with a whitespace or `;` the `eval` doesn't raise an exception) but it seems to work - the code with Korean character works in the latest commit 0435f841b2e896cbc90253108e3b9545aa091c66.

Moreover, the script __identifiers_re.js__ is no longer needed, a few bytes less in __brython.js__ !

**Comment by aroberge** [comment]
Merci! :-)
