### ISSUE TITLE
Deploying without installing no longer works with Webkit-based browsers

### ISSUE THREAD

**Issue by stroobandt** [brython-dev/brython#359]
I deployed a number of applications using "Deploying without installing" as outlined in the documentation: http://www.brython.info/static_doc/en/deploy.html

However, this no longer works with Webkit-based browsers. The following fatal XMLHttpRequest errors are thrown up:
```
+ Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.
	brython_dist.js:4032
+ XMLHttpRequest cannot load file:///home/serge/public_html/hamwaves.com/zc.circular/en/zc.circular.py. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.brython @ brython_dist.js:4032
	brython_dist.js:4032
+ Uncaught NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'file:///home/serge/public_html/hamwaves.com/zc.circular/en/zc.circular.py'.
```

Modern browsers block cross-domain XMLHttpRequest.
Here is a suggestion for the Brython developers how to handle this cross-origin XMLHttpRequest issue: http://www.html5rocks.com/en/tutorials/cors/

Looking forward to see this working again! Thanks!

**Comment by serge-stroobandt** [comment]
"Deploying without installing" is a must-have feature as it fosters adoption. See for example the speed by which http://www.mathjax.org/ got adopted as an API.

Eventually, by resolving this issue it should also be possible to develop Brython applications without running a local server.

**Comment by aroberge** [comment]
I can (indirectly) confirm that this is something very useful to have and fairly easy to implement (with one caveat and one possible downside mentioned below). I needed this in my mixed Javascript/Brython app and implemented it as follows:
```javascript
// from http://stackoverflow.com/questions/15005500/loading-cross-domain-html-page-with-jquery-ajax
$.ajaxPrefilter( function (options) {
  if (options.crossDomain && jQuery.support.cors) {
    var http = (window.location.protocol === 'http:' ? 'http:' : 'https:');
    options.url = http + '//cors-anywhere.herokuapp.com/' + options.url;
  }
});
```
Caveat: this is not sufficient to make it possible to run my app without running a local server BUT it allows me to load (Python, json) files from other domains.

On some very rare occasions, loading has (temporarily) failed as the heroku server appeared to be unavailable.

**Comment by kikocorreoso** [comment]
Some possibilities:

* The easy way would be to create your own *brython_dist.js* file per project (it is what I did [here on a small side project](https://github.com/kikocorreoso/map2wiki/blob/master/src/static/brython_dist.js)). This has its own caveats as if it is a *.py* file from the stdlib it is connected with a lot of modules and sometimes it is not easy to know the real dependencies. But you don't need *CORS* nor a server.

* Other way would be to make async ajax work as sync requests... o_O

* Wait to transpile until all imports are made. I don't see an easy way to do it as python files that need to be traspiled can have other imports.

* Other possibility would be to use requireJS with all the *.py* files already precompiled to JS???

Other ideas?

**Comment by PierreQuentel** [comment]
Serge,

Sorry for the late answer. Could you give a short example when you get this error ?

If I put this content in an html file in folder "gallery" of a clone of the Brython repository : 

```html
<!doctype html>
<html>

<head>
<meta charset="utf-8">
<script type="text/javascript" src="http://brython.info/src/brython_dist.js"></script>
</head>

<body onLoad="brython(1)">
<script type="text/python">
# import from Brython distribution
from browser import alert, document, html

# import a local file
import import_test

# open a file in the same folder
document <= html.PRE(open('ui_menu.py').read())
</script>
</body>
</html>
```

and I open this file in the browser (With "File/Open file..." in Firefox) everything works as expected : import of a local script, reading a local file.

**Comment by PierreQuentel** [comment]
Hi,

In the latest release the ajax module has been reset to the Javascript version, because of an issue with Safari (#373). It probably fixes this issue too ; can you try you code with this version and tell us if we can close this issue ?

**Comment by stroobandt** [comment]
Dear Pierre,

You got it right! This fixed the issue. I tested <http://hamwaves.com/zc.square/en/index.html> with [Vivaldi](https://vivaldi.com/) beta 3, which is a browser based on Webkit. I will point all my calculators in production back again to <http://brython.info/src/brython_dist.js>

I am also happy to read that Safari is supported again. Thanks for all the good work!

**Comment by PierreQuentel** [comment]
Thanks for the feedback, and glad that it works again !
