### ISSUE TITLE
isidentifier() returns wrong result

### ISSUE THREAD

**Issue by aroberge** [brython-dev/brython#360]
Brython recognizes a subset of valid Python identifiers; however, its `isidentifier()` string method is not consistent.  If you run the following example in the Brython editor
```python
André = 1 
print(André)
print('André'.isidentifier())
```
The result will be
```python
1
False
```
showing that Brython does recognize `André` as a valid identifier, even though the `isidentifier()` string method does not.

**Comment by PierreQuentel** [comment]
André,

I have made `isidentifier` compliant with the Brython parser. It uses regular expression  patterns defined in the script identifiers_re.js. I made it some time ago, based on a subset of all the Unicode categories that should be accepted in an identifier (the full list is defiined in PEP 3131). It would be possible to extend it, but at the price of much bigger regular expressions and maybe a longer parsing time.

**Comment by aroberge** [comment]
On Tue, Jan 5, 2016 at 11:45 AM, Pierre Quentel <notifications@github.com>
wrote:

> André,
>
> I have made isidentifier compliant with the Brython parser. It uses
> regular expression patterns defined in the script identifiers_re.js. I made
> it some time ago, based on a subset of all the Unicode categories that
> should be accepted in an identifier (the full list is defiined in PEP
> 3131). It would be possible to extend it, but at the price of much bigger
> regular expressions and maybe a longer parsing time.
>

I have some Korean users on my site (it is actually being translated into
Korean including the Python tutorial for beginners).  However, korean words
are not recognized as valid identifiers.   They can use Javascript to write
programs with Korean identifiers ... and it would be nice if they could do
the same for Python.

I am wondering if it would be possible to proceed in two steps which I can
represent symbolically (I know it would not be like this in practice) as:

try:
     parse_identifier_based_on_simple_regex(...)
except UnrecognizedSymbol:
     parse_identifier_based_on_more_complicated_regex(...)

The simpler regex used could be even one that only accept ascii characters
(basically, what was allowed in Python 2) and would presumably lead to even
faster parsing time than Brython currently has.  The more complex regex
would only likely be invoked very rarely by most people ... but could make
Brython useable more widely.
