### ISSUE TITLE
Subclassing list

### ISSUE THREAD

**Issue by andy31lewis** [brython-dev/brython#364]
Hi again

A subclass of list always gets initialised as an empty list:

Brython 3.2.4 on Netscape 5.0 (X11)
>>>class A(list):
...     def __init__(self, x):
...         list.__init__(self, x)
... 
>>> z = A([1,2,3])
>>> z
[]

Thanks

Andy

**Comment by PierreQuentel** [comment]
I can't reproduce this bug. The following code

```python
class A(list):
    def init(self, x):
        list.__init__(self, x)

z = A([1,2,3])
print(z)
```

actually prints `[1, 2, 3]`
