### ISSUE TITLE
All attributes of class subclassed from svg object are converted to strings

### ISSUE THREAD

**Issue by andy31lewis** [brython-dev/brython#365]
Hi

Not sure whether this is a bug or just known, inevitable behaviour.  Minimal example below - rlist is intended to be a list, but is silently converted to a string.

By the way, I hope you don't mind me reporting these things (the last 3 issues are from me) - I just thought it's better to report anything like this.  If you want to close them as not worth fixing that's fine.

Thanks for Brython - it's great!

Andy

>>> import browser.svg as svg
>>> class C(svg.circle):
...     def __init__(self, r):
...         self.rlist=[]
...         self.rlist.append(r)
... 
>>> a = C(5)
Traceback (most recent call last):
AttributeError: 'str' object has no attribute 'append'

**Comment by PierreQuentel** [comment]
Andy,

Thanks for the report, it's very helpful. This bug should be fixed, I will look at the other ones you reported shortly.

\- Pierre

**Comment by andy31lewis** [comment]
Wow! I've never known a project whee bugs get fixed so fast!

Thanks

Andy
