### ISSUE TITLE
Pythonic API for IndexedDB

### ISSUE THREAD

**Issue by olemis** [brython-dev/brython#368]
Writing IndexedDB code ends up in a lot of spaghetti code e.g. multiple callbacks involved . Having a more pythonic API would be nice .

**Comment by PierreQuentel** [comment]
It would be nice to have this more Pythonic interface but I doubt it is possible : you can't transform an asynchronous program into a synchronous one.

By the way, the demo I have just added (gallery/library.html) doesn't use the indexed_db module : it just takes `window.IDB` if it exists.

**Comment by olemis** [comment]
yeah , I guess there should be a way to work around this ... I have other priorities now , but at some time in the future I'll take a look into this .

**Comment by olemis** [comment]
> By the way, the demo I have just added (gallery/library.html) doesn't use the indexed_db module : it just takes window.IDB if it exists.

So I wonder , is `indexed_db` module working as expected ? I found a test module for it , but I'm not sure of test coverage .
