### ISSUE TITLE
[bug] time.ctime hard coded to +2:00 UTC

### ISSUE THREAD

**Issue by Hasimir** [brython-dev/brython#369]
So it I'm assuming development occurs principally in Western Europe, or at least for the time module.  Here is the output on a local instance of the server for time.gmtime correct to UTC, time.localtime correct, but time.ctime is incorrect (by 9 hours).

    >>> sys.version
    '3.3.0 (default, 2016-01-24 19:39:23.880175) \\\\n[Javascript 1.5] on Brython'
    >>> import time
    >>> time.time()
    1454004386.108
    >>> time.asctime(time.gmtime())
    'Thu Jan 28 18:12:07 2016'
    >>> time.asctime(time.localtime())
    'Fri Jan 29 05:12:27 2016'
    >>> time.ctime()
    'Thu Jan 28 20:12:42 2016'
    >>>

And here is the same commands on a native CPython session:

    Python 3.5.1 (default, Jan  2 2016, 01:13:43)
    [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import time
    >>> time.time()
    1454005146.516937
    >>> time.asctime(time.gmtime())
    'Thu Jan 28 18:19:23 2016'
    >>> time.asctime(time.localtime())
    'Fri Jan 29 05:19:35 2016'
    >>> time.ctime()
    'Fri Jan 29 05:19:44 2016'

And finally, the pydoc output for time.ctime:

    ctime(...)
	ctime(seconds) -> string

	Convert a time in seconds since the Epoch to a string in local time.
	This is equivalent to asctime(localtime(seconds)). When the time tuple is
	not present, current time as returned by localtime() is used.

So ... you didn't by any chance happen to precompile the majority of the standard library modules on a system set to your local timezone?  ;)

If locking ctime in to a build server's timezone can't be avoided, though, then it would peobably be best to use UTC time since pretty much everyone can readily identify that one.  Though standard functionality would obviously be preferred.

I do wonder, though whether or not there might be some advantage in incorporating some of the work already completed for the PyPy project.  Specifically to get versions of the standard library implemented entirely in Python.  If they can run in Brython then it ought to be possible to make Brython do anything PyPy can, possibly even running an entire PyPy instance with Brython.  I've got no idea how well that will work (or how badly it could crash), but it can'thurt (much) to try.

**Comment by PierreQuentel** [comment]
Thanks for the report. `time` is implemented as a pure Python module (in __Lib/time.py__) and I just rewrote the `ctime` function as

```python
def ctime(timestamp=None):
    return asctime(localtime(timestamp))
```

A couple of pure Python modules replacing those implemented in C for CPython are actually borrowed from PyPy, for instance `_csv.py`

**Comment by Hasimir** [comment]
Yep, it's behaving itself here now:

Brython 3.2.5 on Netscape 5.0 (Macintosh)
>>> import time
>>> time.asctime(time.gmtime())
'Thu Feb  4 12:02:13 2016'
>>> time.asctime(time.localtime())
'Thu Feb  4 23:02:23 2016'
>>> time.ctime()
'Thu Feb  4 23:02:56 2016'
>>> import sys
>>> sys.version
'3.3.0 (default, 2016-01-31 21:01:41.903375) \\\\n[Javascript 1.5] on Brython'
>>> 

Cheers!  :)

As for the PyPY thing, it makes perfect sense to me, no point reinventing the wheel after all.
