### ISSUE TITLE
ajax gallery example broken in Safari

### ISSUE THREAD

**Issue by glyph** [brython-dev/brython#373]
To reproduce:

1. visit http://brython.info/gallery/ajax.html
2. click any button
3. see error in web console:

[Log] TypeError: undefined is not an object (evaluating 'self.func.bind') (brython.js, line 4917)

**Comment by glyph** [comment]
This seems to work OK in Chrome and Firefox.

**Comment by PierreQuentel** [comment]
Thanks for mentioning this. I'm having a hard time fixing this (the only Apple product I have is an iPhone 4) but I'm almost sure that it is related to the fact that for Safari, XMLHttpRequest is not a function ; this case is not correctly handled by JSConstructor. It will be fixed shortly.

**Comment by glyph** [comment]
Thanks. I can run whatever experiments you like in my instance of Safari, and I might be able to get you access to a Mac OS X virtual machine.  Travis-CI supports Mac builds, so you can add mac builders to your CI and have them spawn safari in the background...

**Comment by glyph** [comment]
As far as XMLHttpRequest being a function:

```
> typeof XMLHttpRequest
< "object" = $2
```

**Comment by PierreQuentel** [comment]
For want of a better solution, I have restored the previous implementation of the Ajax module as a Javascript module instead of the pure-Python module.

**Comment by glyph** [comment]
I checked the brython.info website after seeing this update, and it's still broken there. Do you have a schedule of deploys to the public site?

**Comment by PierreQuentel** [comment]
I keep the brython.info synchronised with the latest Brython release. I published 10 versions in 2015, the last one was a month ago. The next one will probably be published before the end of February.
