### ISSUE TITLE
script tag Loading sequence bug

### ISSUE THREAD

**Issue by githob605608886** [brython-dev/brython#374]
This is modified, pay attention to view the commit record

See Project:

https://github.com/githob605608886/brython_cn.git

https://github.com/githob605608886/brython_cn/commit/13365b79ba5201c4ef25605f2927f9acd1b8cd2e

**Comment by githob605608886** [comment]
brython  version 3.2.4

ok method Change brython.js 4150-4155 Line code：
---------
 /* change->2-1 */
/*ext_scripts.push({name:module_name,url:$elt.src})*/
var temp_ext_scriptcode = []
temp_ext_scriptcode.push({name:module_name,url:$elt.src})
load_ext(temp_ext_scriptcode)
/* change->2-1 end */
}else{
var $src=($elt.innerHTML ||$elt.textContent)
inner_scripts[module_name]=$src
$B.$py_module_path[module_name]=$href
run_script({name: module_name,src: $src,url: $href})
}}}}

/*load_ext(ext_scripts)*/
/* change->2 Done */
}
---------

change 4106 Line code:
-----
req.open('GET',script.url,false)    //change>1
-----

**Comment by olemis** [comment]
It'd help if you could submit a `diff -u` illustrating the changes , see [gitdiff](https://git-scm.com/docs/git-diff) or [diff](https://en.wikipedia.org/wiki/Diff_utility#Unified_format)

**Comment by githob605608886** [comment]
@olemis  I will not use Git   

    Can help me modify the code

**Comment by PierreQuentel** [comment]
I'm sorry but I don't understand which problem you are trying to solve with this pull request. Could you give an example, preferably with a small piece of code that causes this problem ?

**Comment by githob605608886** [comment]
# hello.py:
`
from browser import alert
def test():
    alert('this is hello')

`
# demo:
`
<script type="type/python3" src="hello.py"></script>
<script type="text/javascript">
brython();
<script>
<script type="type/python3">
test() # No function
</script>
`

**Comment by githob605608886** [comment]
@PierreQuentel 

# step 1
**4061 Line Change**
> req.open('GET',script.url,false)

# step 2

<https://github.com/githob605608886/brython_cn/commit/13365b79ba5201c4ef25605f2927f9acd1b8cd2e>  
**4147 -4148 Line**
> add package name,Attributes as ***data-py-package***  
>>from \* import \*  
import *

**4061,4150,4155**  
**These three lines are changing script loading order, otherwise the above code is wrong**

**Comment by githob605608886** [comment]
@PierreQuentel 

**Sorry, 4061 lines of code, I do not have time to change, you retrieve BUG cause I have a question submitted**

**Comment by PierreQuentel** [comment]
There is an error in your code

```
<script type="type/python3">
test() # No function

</script>
```

The type should be `"text/python3"`, not `"type/python3"`

**Comment by githob605608886** [comment]
@PierreQuentel 

###  ->_<-   
### Is not Google translate the problem, cause you can not understand  
### I'm saying bug not this "type/python3"  

### I'm saying below ,Demo and step

[demo](https://github.com/githob605608886/brython_cn/tree/master/demo)


# step 1
**4061 Line Change**
> req.open('GET',script.url,false)

# step 2

<https://github.com/githob605608886/brython_cn/commit/13365b79ba5201c4ef25605f2927f9acd1b8cd2e>  
**4147 -4148 Line**
> add package name,Attributes as ***data-py-package***  
>>from \* import \*  
import *

**4061,4150,4155**  
**These three lines are changing script loading order, otherwise the above code is wrong**

**Comment by githob605608886** [comment]
@PierreQuentel 

## If you use this [project](https://github.com/brython-dev/brython)

## Here the code is wrong


# hello.py:

>from browser import alert
def test():
>>alert(”this is hello“)


# demo

>  \<script type="text/python3" src="hello.py"></script>
>  \<script type="text/python3">
>test() # No function  
>  \</script>
>  \<script type="text/javascript">brython();\</script>

**Comment by PierreQuentel** [comment]
The commit referenced above should fix the bug. It runs the scripts in the order that they are defined in the html page.

Each script runs in its own namespace, so a name defined in the script `hello.py` can't be used directly in another script. You must set it as an attribute of the global object `window` : 

```python
from browser import alert, window
def test():
    alert("this is hello")

window.test = test
```

In the other script the code should be : 

```python
<script type="text/python3">
from browser import window
window.test()
</script>
```

Another strange thing in your code is that you call the function `brython()` inside a Javascript code : 

```
<script type="text/javascript">brython();</script> 
```

when the standard way is to call it on page load : 

```
<body onload="brython()">
```

Thank you for the bug report !
\- Pierre

**Comment by githob605608886** [comment]
@PierreQuentel 

This method is not I expected
So at the expense of freedom

Each script tag, should you need to define a name space
Instead \__main\__，__main__2，__main__3，__main__4...

e.g：
```xml
<script type="text/python3" src="hello.py" data-py-package="hello">
```

**Comment by PierreQuentel** [comment]
This is actually the best way to use the module `hello.py` : instead of loading it by

```
<script type="text/python" src="hello.py"></script>
```

it's much better to import it like in your second example, which has worked in all Brython versions for ages.

I'm still not sure of what you really want anyway, your English is hard to understand.
