### ISSUE TITLE
Bug in console

### ISSUE THREAD

**Issue by aroberge** [brython-dev/brython#377]
Using the Python console http://www.brython.info/tests/console.html, the following code raises a NameError:

```python
a = 1
for i in range(3):
  a += i
```

**Comment by githob605608886** [comment]
Namespace Error

method

locals()['x']+=i

**Comment by githob605608886** [comment]
This is my project, modify some BUG
Package and label script load order
Defines the name of the new package


https://github.com/githob605608886/brython_cn
