### ISSUE TITLE
eval() does not work properly (possible bug)

### ISSUE THREAD

**Issue by BartolomeSintes** [brython-dev/brython#379]
Hi,
I am just a Brython beginner, so I apologise if this is not a Brython error:
The following html
<!DOCTYPE html>
<html>
<meta charset="utf-8">
<head>
<script type="text/javascript" src="http://brython.info/src/brython_dist.js"></script>
<script type="text/python3">
from browser import document
document["result"] <= str(eval("not 2 < 1 and False"))
</script>
</head>
<body onload="brython(2)">
  <p id="result">eval("not 2 < 1 and False") : </p>
</body>
</html>
generates this result
eval("not 2 < 1 and False") : True
But in IDLE eval("not 2 < 1 and False") is False
Is this a Brython bug? Or am I doing something wrong?
Thanking you in advance,

**Comment by BartolomeSintes** [comment]
<p>Sorry. The html code is the following one</p>
<p>&lt;!DOCTYPE html&gt;<br />
&lt;html&gt;<br />
&lt;meta charset="utf-8"&gt;<br />
&lt;head&gt;<br />
&lt;script type="text/javascript"
src="http://brython.info/src/brython_dist.js"&gt;&lt;/script&gt;<br />
&lt;script type="text/python3"&gt;<br />
from browser import document<br />
document["result"] &lt;= str(eval("not 2 &lt; 1 and False"))<br />
&lt;/script&gt;<br />
&lt;/head&gt;<br />
&lt;body onload="brython(2)"&gt;<br />
&lt;p id="result"&gt;eval("not 2 &lt; 1 and False") : &lt;/p&gt;<br />
&lt;/body&gt;<br />
&lt;/html&gt;</p>

**Comment by PierreQuentel** [comment]
Hi,

Welcome to Brython, and thank you for the report. I suppose you tested the code in the online console at brython.info ; a similar bug was reported recently (#371) and fixed ; the current version in the Github repository now gives the correct result for `eval("not 2 < 1 and False")`. Can you check, and if it's the case close the issue ?

\- Pierre

**Comment by BartolomeSintes** [comment]
Hi, Pierre:
Thank you very much for your fast answer. 
I have tested eval("not 2 < 1 and False") in the online console and it does give the right answer. But I have tried another expression in the online console and the result seems to be incorrect
eval("not 9 <= u and u == 0", { "u" : 7})
online console: True vs IDLE: False
Do you prefer that I open another issue with the second expression.
I have found these expressions because I am preparing a lesson for my students, for practicing logical expressions. You can see it at http://www.mclibre.org/consultar/python/ejercicios/ej_booleanos.html The page is written in Spanish but I think you can understand it easily.
This is my first page with Brython and I have been checking everything was OK. Simple expressions as the ones that appear in exercise 1 and 2 are evaluated OK by Brython. But expressions like the ones that appear in exercise 3 are not evaluated properly by Brython. I think that I have solved the problem adding () after every not in my code.
I wrote my first Brython program last Saturday, but I already think it will be very useful to me in my Python lessons. Thank you very much for your wonderful work.

**Comment by PierreQuentel** [comment]
Hi,

I tested this on the latest development version, the result is actually `False`, like with CPython. 

When you do
```
>>> import sys
>>> sys.version
``` 
in the console, what is the result ?

**Comment by BartolomeSintes** [comment]
In Brython http://brython.info/tests/console.html?lang=en
sys.version is 3.3.0 (2016-01-16 09:01)
eval("not 9 <= u and u == 0", { "u" : 7})
True
In IDLE
sys.version
'3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:54:25) [MSC v.1900 64 bit (AMD64)]'
eval("not 9 <= u and u == 0", { "u" : 7})
False
I would say that the correct eval is False as
not 9 <= u and u == 0
should be evaluated as
(not 9 <= u) and (u == 0)
shouldn't it?

**Comment by PierreQuentel** [comment]
You are using the version on brython.info, which is not the same as the latest development version that you get with a "git clone" from this Github site.

The version on brython.info is the latest stable release, currently version 3.2.4 released on Jan. 16, as the result of `sys.version` says. The development version is by nature less stable. The next release (3.2.5) should be published before the end of February, and brython.info will be updated to this version.

**Comment by PierreQuentel** [comment]
I think the bug is fixed, so I close the issue. Feel free to reopen it if necessary.
