### ISSUE TITLE
Turn this "fork" into a standalone repository

### ISSUE THREAD

**Issue by BlaXpirit** [brython-dev/brython#382]
It may be undesirable to have the project's main repository act as a fork on GitHub. Not only is this "fork" brand confusing or even discouraging to see, but it also has side effects, like contributions to the projects now showing up in profiles.

> To detach the fork and turn it into a standalone repository on GitHub, contact <a href="https://github.com/contact">GitHub support</a>.
> &mdash; [Source](https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/#commit-was-made-in-a-fork)

**Comment by olemis** [comment]
FWIW I see no problem with keeping it the way it is , thus closing this issue . I may be wrong . @PierreQuentel if you think otherwise just reopen this issue .

**Comment by PierreQuentel** [comment]
After reading Oleh's post I asked the Github support to make brython-dev/brython a standalone repository. It's on its way.
