### ISSUE TITLE
platform.system throws errors

### ISSUE THREAD

**Issue by AbdealiJK** [brython-dev/brython#383]
When trying to do `platform.system()` brython throws an error. Would be nice to catch this and give a value like "browser" or "brython" or so.

```
Brython 3.2.4 on Netscape 5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/47.0.2526.73 Chrome/47.0.2526.73 Safari/537.36
>>> import platform
>>> platform.system()

Internal Javascript error: TypeError: Cannot read property '__class__' of undefined
>>> 
```

**Comment by PierreQuentel** [comment]
Hi,

Thanks for reporting this. In the commit referenced above I have written a minimalist, Brython-specific version of the platform module. There is not much information we can get about the platform with Javascript. If you think the results can be improved please reopen this issue.
