### ISSUE TITLE
os.path.expanduser throws errors

### ISSUE THREAD

**Issue by AbdealiJK** [brython-dev/brython#384]
The function `os.path.expanduser()` throws the following error:

```
Brython 3.2.4 on Netscape 5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/47.0.2526.73 Chrome/47.0.2526.73 Safari/537.36
>>> import os
>>> os.path.expanduser("~/a")
Traceback (most recent call last):
AttributeError: 'module' object has no attribute 'getuid'
```

I'm not sure what the expected output should be in such cases. But it'd be good to allow the user to set the HOME directory and use that ? Or maybe we can simply make it the current directory ?

**Comment by olemis** [comment]
Obviously there is no notion of user directory on the browser . First option looks better to me since it provides a more consistent configuration across , say , a website with multiple pages . Nonetheless it is possible to rely upon a naming convention to determine a default value, approximately as follows 

```
path = userFolderConfig()
if path is None:
  parts = window.location.pathname.split('/');
  path = []
  for part in parts:
    if part.startswith('~'):
      # Stop if there is an item in path starting with tilde char
      break
    else:
      path.append(part)
  else:
     path = ('', '') # Fallback to web site root instead 
path = '/'.join(path)
```

**Comment by kikocorreoso** [comment]
Should these kind of system functionality be removed or changed to throw an Exception?

**Comment by olemis** [comment]
IMHO , neither of them . If we want to be compatible with as many libs as possible then IMO we should work around this i.e. never fail .

**Comment by AbdealiJK** [comment]
@kikocorreoso 's observation about "should these throw an error" is actually very note worthy.

Hence, I think it may be wise to have a `monkeypatch` option - which makes brython do fixes for these sort of common issues which are not important for a pure brython app but are needed for existing libs that are being run on brython.

**Comment by PierreQuentel** [comment]
The commit referenced above fixes the issue by making `expanduser(path)` always return `path`. Another solution would have been to set `os.envion['HOME']` to `__BRYTHON__.brython_path` (the path where the code Brython scripts such as __brython.js__ stand) but I'm not sure if it's a better solution. Feel free to reopen the issue if necessary.
