### ISSUE TITLE
multiprocessing support in brython

### ISSUE THREAD

**Issue by AbdealiJK** [brython-dev/brython#385]
I'm wondering if it's possible to "mock" multiprocessing using javascript. JS is anyway asynchronous.

So, a few thoughts on that:
- Override `multiprocessing.cpu_count()` to 1 so that programs that auto detect this number.
  
  Note that `multiprocessing.cpu_count()` anyway doesnt guarantee to return a value and can throw `NotImplementedError` - so, it's alright if this is not done, but it'd be good to let the user know there's one cpu maybe ?
- It'd be great to mock the `multiprocessing` module so that `Process()`, `Manager()`, `Queue()` etc. can be used.
  
  I think this would be easy because JS can have multiple async functions running - it's similar to how multiprocessing works ?

**Comment by the1337guy** [comment]
With stuff like web workers now, I think multiprocess can be a reality. 👍

**Comment by jonathanverner** [comment]
Brython now has support for asyncio style coroutines, which are already quite useful. However, to do real multiprocessing, one would need to use [Webworkers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers). Without them, Javascript essentially has no multiprocessing --- there can only be one piece of Javascript executing at any given moment and there is no way to interrupt a running function and run a different one. To see what I mean, consider the following piece of code:

```javascript
setTimeout(function() { 
    while(1)  {console.log(1);} 
}, 0)
```

which will completely lock up your browser even though the function is supposedly executed asynchronously. With webworkers,  multiprocessing becomes possible, but there will have to be some changes to Brython, before we can support them (see #589). In the meantime, I will close this bug and redirect discussion to the issue #589 to keep it in one place.
