### ISSUE TITLE
On Webkit based browsers, all attributes of class subclassed from svg object are converted to strings

### ISSUE THREAD

**Issue by andy31lewis** [brython-dev/brython#386]
Hi again

This is the same issue as #365; it is fixed for most browsers but not those based on Webkit - which is mostly the browsers used on Apple devices - iPhone, iPad, Safari on Macbook etc.  Because I don't have any Apple devices I have been testing on Midori which has quite a nice developer console.

To test: 

``` python
class C(svg.circle):
    def __init__(self, r):
        self.number = 7
        self.rlist = []

a = C(5)
type(a.rlist)
type(a.number)
```

Both attributes are reported as type 'str'.

Thanks again.

Andy

**Comment by andy31lewis** [comment]
Returning to this after a couple of years, I find that the problem is fixed - whether by changes to Webkit, or to Brython, I don't know.  But anyway, this issue can be closed.
Thank you for the continual improvements to Brython.

**Comment by jonathanverner** [comment]
Thanks for reporting back @andy31lewis !
