### ISSUE TITLE
hash collisions between different classes, and between classes and instances.

### ISSUE THREAD

**Issue by tiggerntatie** [brython-dev/brython#388]
class A():
        pass
    
    class B():
        pass
    
    a1 = A()
    a2 = A()
    
    print(hash(A) == hash(B))
    print(hash(A) == hash(a1))
    print(hash(A) == hash(a2))

Brython 3.2.4 produces:

True
True 
False
 
Python 3.4.3

False
False
False

This may be related to #387

**Comment by tiggerntatie** [comment]
The behavior noted here occurs when used in, for example, the [Brython editor](http://brython.info/tests/editor.html?lang=en). If the code is executed *a second time*, without reloading the page, then the result is correct.

**Comment by tiggerntatie** [comment]
For example, for the following:

    class A():
        pass
  
    class B():
        pass
  
    a1 = A()

    print(hash(A))
    print(hash(B))
    print(hash(a1)) 
    a2 = A()
    print()
    print(hash(A))
    print(hash(B))
    print(hash(a1))
    print(hash(a2))

Produces the following the first time it runs:

-9007199254740992
-9007199254740992
-9007199254740992

-9007199254740992
-9007199254740992
-9007199254740991
-9007199254740990

Classes and instance all have the same hash value. When a *second* instance of class A is created, the class hashes remain the same, but now the first instance has *changed* its hash value and the second instance has a unique hash.

On running a *second* time:

-9007199254740989
-9007199254740990
-9007199254740991

-9007199254740989
-9007199254740990
-9007199254740990
-9007199254740989

Both classes and the first instance have unique hashes. When a second instance is created, the classes retain their original hashes, but the first instance reverts to match one of the class hashes, and the second instance now matches the other class hash.

**Comment by PierreQuentel** [comment]
Eric,

There was something wrong with the implementation of hash() : the value set for the first user-defined class was -9007199254740992, ie -2**53, then decremented by 1, but in Javascript -2**53-1 is equal to -2**53 !

I changed the implementation in the commit referenced above, it seems to fix the bug.

Thanks
