### ISSUE TITLE
Either pygame example or pygame port is broken

### ISSUE THREAD

**Issue by scythargon** [brython-dev/brython#390]
http://localhost:8000/gallery/pygame/chimp.html

gives you next error:
```
module __main__ line 69
    self.rect.midtop = pos
AttributeError: 'Rect' object has no attribute'midtop'
```

though setters seems to work

**Comment by Lightning3105** [comment]
I'm surprised you got that far, I cannot even seem to import the Pygame port. I opened an issue on the pygame repository: https://github.com/brython-dev/brython-pygame/issues/1

**Comment by kikocorreoso** [comment]
PyGame is not maintained at the moment.

Maybe you can check a js lib to create games with Brython and/or have a look to the wiki: https://github.com/brython-dev/brython/wiki/Brython%20in%20the%20wild

**Comment by PierreQuentel** [comment]
I close this issue since it is not related to Brython itself but to a specific package.

Thanks,
\- Pierre
