### ISSUE TITLE
bind does not catch javascript events

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [brython-dev/brython#398]
Javascript can catch events from brython, but brython cannot catch events from javascript.

<!DOCTYPE html>
<html>
<head>
	<title></title>

	<meta charset="UTF-8">

	
	<script type="text/javascript" src="http://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.1.min.js"></script>

	<script type="text/javascript" src="http://www.brython.info/src/brython.js"></script>

</head>
<body id="body" onload="brython({debug:1})">

	<script type="text/javascript">
		var para = document.createElement("asdf");
		para.id = "python_node";
		var element = document.getElementById("body");
		element.appendChild(para);

		var event = new CustomEvent('python_function_call');

		// // Listen for the event.
		// document.getElementById(para.id).addEventListener('javascript_function_call', 
		// 	function (e) {console.log("js caught"); console.log(e);}, false);

		// // Listen for the event.
		// document.getElementById(para.id).addEventListener('python_function_call', 
		// 	function (e) {console.log("js caught"); console.log(e);}, false);

		$( document ).ready(function(){
			console.log("ready");
			document.getElementById(para.id).dispatchEvent(event);
		});

		function throw_event(){
			console.log("throw_event")
			document.getElementById(para.id).dispatchEvent(event);
		}
	</script>

	<script type="text/python">
		from browser import document, console, DOMEvent

		console.log("python loaded")

		def python_staging(event):
			console.log("py got it")

		element_id = 'python_node'
		# console.log(document[element_id])

		# new_ele = document.createElement('qwer')
		# new_ele.id = 'game'
		# document['body'].appendChild(new_ele)

		# document['game'].bind('python_function_call', python_staging)

		event_name = 'python_function_call'
		# event = DOMEvent(event_name)
		# document[element_id].dispatchEvent(event)

		event_name = 'javascript_function_call'
		event = DOMEvent(event_name)
		document[element_id].dispatchEvent(event)

		document[element_id].bind(event_name, python_staging)

	</script>	

	<button type="button" onclick="javascript: throw_event()">Python Event</button>
</body>
</html>

**Comment by PierreQuentel** [comment]
Hello,

There must be some parts missing in your code. What is `document.getElementById("body")` supposed to be ?

**Comment by BebeSparkelSparkel** [comment]
Hey sorry about this. The $(document).ready was not waiting until the python code was loaded so the brython event listener was not loaded when the event was created. I don't think you'll be able to change the jquery ready function.
