### ISSUE TITLE
Import performance regression starting in 3.2.4, also in 3.2.5

### ISSUE THREAD

**Issue by cforger** [brython-dev/brython#403]
Hello,

Whilst upgrading a project from Brython 3.1 to current source, I noticed an extreme slowdown in the performance to import my custom modules. 

I took the time to test every Brython release between 3.1 and 3.2.5, and I can confirm that the speed degradation starts in 3.2.4, and is present in 3.2.5 - Perhaps a debugging or similar command has been left on?

I thought it may have been my brython({debug:2}) level, but with this turned off, it's still just as slow.

With debug:2 on , here's a printout of times to compare how slow the modules load between 3.2.3 and 3.2.5

Let me know how I can assist - I've got all the versions loaded and available via symlinks so I can switch fairly quickly.  

Thanks. 

3, 2, 5, 'final', 0]
brython.js:4966 3.2.5

brython.js:4078 module gui.display translated in 3141 ms
brython.js:4078 module gui.panel translated in 730 ms
brython.js:4078 module gui.control_panel translated in 979 ms
brython.js:4078 module gui.dumpmi translated in 120 ms
brython.js:4078 module gui.search_grid translated in 2213 ms
brython.js:4078 module gui.edit_grid_columns translated in 1495 ms
brython.js:4078 module gui.main_menu translated in 1032 ms
brython.js:4078 module gui.search_grid_detail translated in 675 ms
brython.js:4078 module gui.detail translated in 5005 ms
brython.js:4078 module common.events translated in 143 ms
brython.js:4078 module common.events translated in 62 ms
brython.js:4078 module datetime translated in 16010 ms
brython.js:4078 module time translated in 3924 ms
brython.js:4078 module time translated in 20 ms
brython.js:4078 module time translated in 17 ms
brython.js:4078 module time translated in 16 ms
brython.js:4078 module time translated in 17 ms
brython.js:4078 module time translated in 18 ms
brython.js:4078 module time translated in 14 ms
brython.js:4078 module gui.listpanel translated in 134 ms
brython.js:4078 module gui.search_grid_selected translated in 246 ms
brython.js:4078 module gui.selected translated in 423 ms
brython.js:4078 module gui.addlist translated in 592 ms
brython.js:4078 module gui.help translated in 38 ms
brython.js:4078 module gui.user_settings translated in 129 ms
brython.js:4078 module gui.import_contacts translated in 3115 ms
brython.js:4078 module gui.contacts translated in 1259 ms
brython.js:4078 module gui.login translated in 555 ms
brython.js:4078 module gui.alert translated in 340 ms

[3, 2, 3, 'final', 0]
brython.js:4792 3.2.3

brython.js:3954 module gui.display translated in 134 ms
brython.js:3954 module gui.panel translated in 25 ms
brython.js:3954 module gui.control_panel translated in 27 ms
brython.js:3954 module gui.dumpmi translated in 4 ms
brython.js:3954 module gui.search_grid translated in 102 ms
brython.js:3954 module gui.edit_grid_columns translated in 22 ms
brython.js:3954 module gui.main_menu translated in 27 ms
brython.js:3954 module gui.search_grid_detail translated in 20 ms
brython.js:3954 module gui.detail translated in 162 ms
brython.js:3954 module common.events translated in 7 ms
brython.js:3954 module common.events translated in 1 ms
brython.js:3954 module datetime translated in 539 ms
brython.js:3954 module time translated in 70 ms
brython.js:3954 module time translated in 1 ms
brython.js:3954 module time translated in 1 ms
brython.js:3954 module time translated in 1 ms
brython.js:3954 module time translated in 1 ms
brython.js:3954 module time translated in 10 ms
brython.js:3954 module time translated in 1 ms
brython.js:3954 module gui.listpanel translated in 4 ms
brython.js:3954 module gui.search_grid_selected translated in 15 ms
brython.js:3954 module gui.selected translated in 10 ms
brython.js:3954 module gui.addlist translated in 14 ms
brython.js:3954 module gui.help translated in 3 ms
brython.js:3954 module gui.user_settings translated in 3 ms
brython.js:3954 module gui.import_contacts translated in 82 ms
brython.js:3954 module gui.contacts translated in 15 ms
brython.js:3954 module gui.login translated in 30 ms
brython.js:3954 module gui.alert translated in 9 ms

**Comment by cforger** [comment]
Update:

I've tracked it down to the revision that is slow:

Jan 4 - c135dec7ea12d5bcfa0ae237f60d1cc566b85352 - Fast
Jan 5 - 0435f841b2e896cbc90253108e3b9545aa091c66 - Slow
Jan 5 (#2) - 34b749e573256706f239924abb3349833a094e5e - Fast

Anything after 0435f841b2e896cbc90253108e3b9545aa091c6 is slow. I'm looking to see if I can find the problem.

**Comment by cforger** [comment]
Found it.

This code snippet:

```
if(name==""){if($B.re_XID_Start.exec(car)){name=car 
pos++
while(pos<src.length && $B.re_XID_Continue.exec(src.charAt(pos))){name+=src.charAt(pos)
pos++}

```
is orders of magnitude faster than this one, which replaced it.

```
if(name=="" && car!='$'){try{eval("dummy."+car+"=0")
var idpos=pos+1
while(idpos<src.length){var idcar=src.charAt(idpos)
if(idcar==' '||idcar=='\n'||idcar==';'||idcar=='$'){name=src.substring(pos,idpos)
break}
try{eval("dummy."+src.substring(pos,idpos+1))
idpos++}catch(err){name=src.substring(pos,idpos)
break}}}catch(err){}
if(name){pos +=name.length
```
When I restore this code plus the definition of $B.re_XID_Start and continue, speed is returned to Brython. 

You can browse here: 

https://github.com/brython-dev/brython/commit/0435f841b2e896cbc90253108e3b9545aa091c66

I don't fully understand the intent of the new code vs. the old (comments anyone? :) ) but it makes Brython unusable for my code, as I'm importing some fairly large modules.

**Comment by cforger** [comment]
Restoring the old code on the current MASTER code also speeds it up - Though my testing is limited because of the issues with websocket that I also reported - On to that next.

**Comment by PierreQuentel** [comment]
Hello,

Thanks for the report, and finding where the problem is. This code was changed to solve issue #358 (full unicode support for identifiers). The speed penalty is not as important on my PC (Windows 7 with Firefox) but I'm going to try to change the algorithm to speed it up.

**Comment by PierreQuentel** [comment]
The commit referenced above should improve the speed while still supporting all Unicode identifiers. Can you test ?

**Comment by cforger** [comment]
Yes, that works - Thanks. 

Any chance of leaving comments in the code that explains the thought behind the new code changes? I know we want minimized code for JS perf, but any code minimizer can strip those.

**Comment by PierreQuentel** [comment]
Thank you, I have added a short comment and closed the issue.
