### ISSUE TITLE
Error in math module 

### ISSUE THREAD

**Issue by olemis** [brython-dev/brython#406]
After running both the QUnit test runner (see #405) and the interactive test index I get this error in `math` test case .

```
[FAILED] - <class 'AssertionError'>
1 != 0 : Failure detected for module 'test_math.py'

Traceback (most recent call last):
  module unittest.case line 491
    return self.run(*args, **kwds)
  module unittest.case line 439
    self._executeTestPart(testMethod, outcome, isTest=True)
  module unittest.case line 384
    function()
  module brython_test_utils.unittest line 18
    status, tstart, tend, msg = utils.run_test_module(self.modname,
  module brython_test_utils line 89
    return run(src)
  module brython_test_utils line 79
    msg = traceback.format_exc()
  module $exec_4053 line 19
    assert math.asin(0.5) == 0.5235987755982989
AssertionError: AssertionError

@ 43 ms
Expected: 	
true
Result: 	
false
Diff: 	
trufalse
Source: 	
    at Object.<anonymous> (http://127.0.0.1/brython/www/tests/qunit/unittest.js:15:16)
Brython : Modules: Brython test module 'storage' (1)Rerun
```

**Comment by PierreQuentel** [comment]
Salut Olemis !

I don't understand where the issue is. In the interactive console, `assert 1 != 0` passes.

**Comment by olemis** [comment]
Salut Pierre !

The relevant lines in traceback description are 

```
  module $exec_4053 line 19
    assert math.asin(0.5) == 0.5235987755982989
AssertionError: AssertionError
```

... the check for `1 != 0` is an internal  (i.e. QUnit) assertion . That will be displayed every time a failure is detected , but the error will be described in the traceback . I tried to remove internal `unittest` but the stdlib code filtering these lines is not working (see #410 ) .

**Comment by PierreQuentel** [comment]
I also tested this, and the following code passes in the editor :

```python
import math
assert math.asin(0.5) == 0.5235987755982989
```

**Comment by olemis** [comment]
see http://stackoverflow.com/questions/8929005/unittest-sometimes-fails-because-floating-point-imprecision

**Comment by kikocorreoso** [comment]
Should this be used for some unittests: https://docs.python.org/3.5/library/unittest.html#unittest.TestCase.assertAlmostEqual ?

Floats are a pain in the ass, maybe an acceptable float precision well defined in the docs would be enough?
