### ISSUE TITLE
Error : no attribute put for [object IDBDatabase]

### ISSUE THREAD

**Issue by olemis** [brython-dev/brython#407]
After running both the QUnit test runner (see #405) and the interactive test index I get this message logged in the console as a consequence of running `storage` test case . Despite this fact the later is not reported as a failure .

```
py_utils.js:833 event:  <DOMEvent object> target <DOMNode object type 'undefined' name 'undefined'>

py_utils.js:833 event type:  upgradeneeded

py_utils.js:833 e.oldVersion:  0

py_utils.js:833 e.newVersion:  3

py_utils.js:833 Marsha <JSObject wraps [object IDBDatabase]>

js_objects.js:362 Traceback (most recent call last):
  module $exec_3976 line 60
      req = db.put(_rec, _kid)
      AttributeError: 'no attribute put for [object IDBDatabase]'
```

**Comment by PierreQuentel** [comment]
Can you explain which code produces this error message ?

I have added an IndexedDB demo in the gallery and removed the one in the test suite. In the demo, the method `put` seems to be correctly called on the store object.

**Comment by olemis** [comment]
@PierreQuentel I'm not familiar with that test code . Nonetheless it seems to me that the error is raised from within an event callback method .

**Comment by olemis** [comment]
@PierreQuentel could you reproduce this issue when running the QUnit test suite ? This error is not rendered in the test results web page but in console output .
