### ISSUE TITLE
some logical expressions are incorrectly evaluated

### ISSUE THREAD

**Issue by BartolomeSintes** [brython-dev/brython#412]
On February I reported the [bug 379](https://github.com/brython-dev/brython/issues/379). Brython 3.2.4 didn't evaluate properly logical expressions. In some cases, Brython 3.2.5 seems to behave incorrectly too.

In Brython console http://brython.info/tests/console.html?lang=en
sys.version : '3.3.0 (default, 2016-02-28 21:52:46.465636) \\\\n[Javascript 1.5] on Brython'
not True and not False or True
is evaluated as 
False
but in IDLE
sys.version
'3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:54:25) [MSC v.1900 64 bit (AMD64)]'
not True and not False or True
is evaluated as 
True

I have found other expressions evaluated incorrectly by Brython console.
False and not False or True
False and not False or not False
False and not True or True
False and not True or not False
not True and not True or True
not True and not True or not False
not True and not False or True
not True and not False or not False

It seems that the not operator is involved in the bug, as (False and False or True) is evaluated properly, but (False and not False or True) is evaluated incorrectly.

Thanking you in advance
Bartolomé Sintes

**Comment by PierreQuentel** [comment]
Thanks for the report. You are right, it was a problem with the `not` keyword.

**Comment by BartolomeSintes** [comment]
Glad to help you improving Brython ;-)
