### ISSUE TITLE
How-to use py2js.js?

### ISSUE THREAD

**Issue by atommixz** [brython-dev/brython#413]
How can I use this from Linux terminal?
```
$ js24 www/src/py2js.js 
www/src/py2js.js:7861:0 ReferenceError: __BRYTHON__ is not defined
```

**Comment by PierreQuentel** [comment]
None of the individual scripts such as py2js.js is supposed to be run as a stand alone script, they are all included in brython.js. Take a look at the section "How Brython works" in the wiki.
