### ISSUE TITLE
Undocumented features of `options` object input parameter of `brython` function

### ISSUE THREAD

**Issue by kikocorreoso** [brython-dev/brython#417]
There are some features of the `options` object used as input for the `brython` function that are not documented in the docs and the comments in the code could be a little vague description.

I have seen you could use:

* `options.open`: What is the intended use for this? Is it a path to be used to open files using `$url_open` on **py_builtin_functions.js**?
* `options.CORS`: By default it is `false`. What happens when it is `true`? Should it throw a warning or be setted to `false` when the option is setted to other thing different to `true` or `false`?
* `options.re_module`: Should it throw a warning or be setted to `jsre` when the option is setted to other thing different to `pyre` or `jsre`?

Please, @PierreQuentel , could you clarify this and I can update the docs?

Thanks.

**Comment by PierreQuentel** [comment]
Sorry for the late answer.

All these options were added long ago and by other contributors, so I'm not absolutely sure, but by reading the code : 

- I don't understand what `CORS` does, I have removed it
- `open` is meant to specify an alternative implementation of the builtin function `open`, for instance one which would use local storage. But for compatibility with Python this should be implemented by setting `__builtins__.open` - which currenlty doesn't work. When it does I will also remove the option `open`

The `re_module` option is documented in py2js.js : 
```javascript
    // Allow user to specify the re module they want to use as a default
    // Valid values are 'pyre' for pythons re module and 
    // 'jsre' for brythons customized re module
    // Default is for brython to guess which to use by looking at 
    // complexity of the re pattern
```
I don't think it should be kept. If a user wants to use the Javascript engine, which can be the case for performance issues, a better way is to explicitely use the Javascript constructor `RegExp` : 
```python
from browser import window
from javascript import JSConstructor

jsre = JSConstructor(window.RegExp)
mo = jsre(r'a(.*)e').exec('aBCDe')
print(mo)
```

**Comment by kikocorreoso** [comment]
I added a milestone to remove the `open` and `re_module` options in brython v3.2.8. Meanwhile, there are some info in the docs and a deprecation warning in the console. See #428 

The idea would be to left this issue open until release 3.2.7 and after that fix this (remove the `open` and `re_module`) on master.
