### ISSUE TITLE
Debug: Index out of range in elif reports the wrong line number

### ISSUE THREAD

**Issue by tiggerntatie** [brython-dev/brython#420]
Brython 3.2.6:

    x = [0]
    if 1 == x[0]:
       pass
    elif 0 == x[1]:
       pass

Reports the error on the wrong line:
 
    Traceback (most recent call last):
      module editor line 100
        traceback.print_exc(file=sys.stderr)
      module $exec_155 line 2
        if 1 == x[0]:
    IndexError: list index out of range

**Comment by PierreQuentel** [comment]
Thanks Eric !

The fix also gives the correct line number for pathological code such as

```python
exc = []

try:
    1/0
except exc[1]:
    pass
```
