### ISSUE TITLE
SVG Demos not working

### ISSUE THREAD

**Issue by psychemedia** [brython-dev/brython#426]
The SVG demos in the [`module browser.svg` doc pages](http://brython.info/static_doc/en/svg.html) don't seem to be working in either Chrome or Safari on a Mac.

On clicking example buttons, Console reports error at *brython.js:4973*:

    Traceback (most recent call last):
      module __main__ line 12
        elt = ev.target.parent.children[ix+1]
    IndexError: list index out of range

**Comment by PierreQuentel** [comment]
Thanks for the report, I have fixed the bug and updated brython.info
