### ISSUE TITLE
[Question] Build script for `brython.js`

### ISSUE THREAD

**Issue by 0xFireball** [brython-dev/brython#427]
In [How Brython Works](https://github.com/brython-dev/brython/wiki/How-Brython-works), you mention:

brython.js is the minified concatenation of individual scripts that handle specific tasks, either at compile time (generation of Javascript code from Python source : done in py2js.js) or at run time (for instance, implementation of all Python built-in objects, eg in py_list.js for list and tuple, py_string.js for str, etc). The development is done on the individual scripts, not on brython.js.

Is there a build script to update the `brython.js` file after I edit files such as `py_list.js`?

**Comment by PierreQuentel** [comment]
Yes, this is done by __/scripts/make_dist.py__

**Comment by 0xFireball** [comment]
Oh sorry didn't see that; thanks.

**Comment by PierreQuentel** [comment]
No wonder you didn't see it, I added the mention of make_dist.py after reading your report :-)

**Comment by 0xFireball** [comment]
Thank you so much!

Sent from Outlook<https://aka.ms/qtex0l>




On Thu, May 12, 2016 at 11:39 PM -0700, "Pierre Quentel" <notifications@github.com<mailto:notifications@github.com>> wrote:


No wonder you didn't see it, I added the mention of make_dist.py after reading your report :-)

-
