### ISSUE TITLE
JS functions cannot be used as decorators

### ISSUE THREAD

**Issue by caryoscelus** [brython-dev/brython#429]
Attempt to use JS function (imported through `window` module) as decorator leads to error like this:

```
Traceback (most recent call last):
RuntimeError: TypeError: $id7 is not a function
```

Since

```python
@decorator
def f():
    ...
```

and

```python
def f():
    ...
f = decorator(f)
```

should produce the same result according to https://www.python.org/dev/peps/pep-0318/, this seems to be a bug, even if such usage can be rare or discouraged.

**Comment by PierreQuentel** [comment]
The use case should not happen very often, but I agree that it should work.
