### ISSUE TITLE
Put Brython on NPM?

### ISSUE THREAD

**Issue by ckcollab** [brython-dev/brython#430]
Heyo! Thanks for releasing this project, really appreciate it.

I was looking to include this on another project and was pretty shocked to see it's not on NPM yet! I would add the package myself, but the concern is it won't be up-to-date with the latest Brython.

**Comment by PierreQuentel** [comment]
Good idea ! I have published a first version (3.2.6) on NPM. I'm new to this so I probably missed a few things (forgot to put LICENCE.txt and README). If you find other issues please tell me, I will update the package when version 3.2.7 is released.

Thanks

**Comment by ckcollab** [comment]
Woo! Thanks so much, really appreciate it :)
