### ISSUE TITLE
Geolocation example broken in most WebKit browsers; not in Firefox, nor Internet Explorer

### ISSUE THREAD

**Issue by stroobandt** [brython-dev/brython#432]
The [geolocation example](http://www.brython.info/gallery/geo.html) in the [Gallery](http://www.brython.info/gallery/gallery_en.html) is broken in most [WebKit](https://en.wikipedia.org/wiki/WebKit)-based browsers.
I tested the latest stable Chromium, Vivaldi and Opera.
The latest Firefox, Pale Moon and --older-- Safari (5.1) and Chrome (49) browsers remain unaffected.
WebKit browsers are not asking whether to share your location and as a result remain in the `nonavi(error)` state.
Here is another page to test Brython geolocation: <http://hamwaves.com/nvis/en/index.html>

**Comment by stroobandt** [comment]
I also tested Internet Explorer 11. Geolocation works fine on it.

**Comment by kikocorreoso** [comment]
chrome and chromium are not the same browser except for this analytics and other stuff google adds to the former?

**Comment by stroobandt** [comment]
@kikocorreoso Yep, but I am talking about the latest stable Chromium 50 (not working) versus the older Chrome 49 (working). I would really appreciate if you could also try out the [gallery example](http://www.brython.info/gallery/geo.html), just to make sure I am not overlooking something.

**Comment by PierreQuentel** [comment]
A search on the Internet suggests that this is not on the Brython side, but a decision to remove location support for "non-secure" origins (HTTP) and only keep it for HTTPS. See [this question](http://stackoverflow.com/questions/32720308/navigator-geolocation-getcurrentposition-no-longer-working-in-safari-mobile-afte) on stackoverfow, with a link to [Chromium](https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-powerful-features-on-insecure-origins).

**Comment by stroobandt** [comment]
You are truly amazing Pierre! I could never imagine something like that. Here is the [reference document](https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-powerful-features-on-insecure-origins).

> Geolocation — [requires secure origins as of M50](https://developers.google.com/web/updates/2016/04/geolocation-on-secure-contexts-only)

Well, if I want to remain on the cheap, I guess I will be forced to look into [Let's Encrypt](https://letsencrypt.org/), accompanying renewal scripts, etc. It really is a never ending story...
