### ISSUE TITLE
Should some std libs be removed as they do not have sense in a client side context?

### ISSUE THREAD

**Issue by kikocorreoso** [brython-dev/brython#439]
There are some libs included in the Brython stdlib that are not useful in a client side environment:
- argparse
- cmd
- gc
- doctest??
  *...

Should them be removed and specify so in the docs?

@PierreQuentel what do you think about it?

**Comment by PierreQuentel** [comment]
I had to include these modules in the Brython distribution because they are imported by useful modules. For instance, `os` imports `subprocess`, which itself imports `gc`...

**Comment by kikocorreoso** [comment]
Maybe we should start creating more independent modules for brython trying to isolate this behavior, importing things that are not so useful in brython that ends slowing down some imports and adding more Kb's to the brython distributions and higher memory use in the brython 'runtime'.

Maybe we could create some milestiones for Brython 4.0.0 including more standalone scripts (when possible and where it has sense) and documenting this.

**Comment by qsantos** [comment]
I'd like to bring attention to the 15 MiB `test/` module in `Lib/`. Although some regression tests might be awful for the development of Brython, I doubt they should be included within a web application.

**Comment by PierreQuentel** [comment]
`test/` is only included in the "Brython site mirror" zip file ; it is not in the smaller zip files recommanded for deployment, and of course not in `brython_dist.js`.

**Comment by kikocorreoso** [comment]
@qsantos This folder (*test/*) is not included in the *brython.js*, *brython_dist.js* or *py_VFS.js*

**Comment by qsantos** [comment]
It's included within `Lib/`, which is used by brython.js, which is is used in the examples of the documentation.

**Comment by mscuthbert** [comment]
doctest can be useful even in a server-side environment, for testing that a system is functioning properly in Brython.  It's not a top importance module, but definitely not something to be on the "never" list.

**Comment by kikocorreoso** [comment]
@mscuthbert Yes, it is important in a dev environment but not in production.
