### ISSUE TITLE
What is the intended use of async.js?

### ISSUE THREAD

**Issue by kikocorreoso** [brython-dev/brython#440]
What is the intended use of *www/src/async.js*?

I see the file created in the repo by @earney some time ago. What was the intended use of this? 
Is it related with async/await in CPython 3.x? Is it finished? Is it necessary to dedicate some work to it? Should it be removed from the *brython.js* and or *brython_dist.js* as it seems it is not finished work?

**Comment by PierreQuentel** [comment]
Billy started work on this some time ago but it was never finished. I agree that we can remove async.js.
