### ISSUE TITLE
Incorrect parsing of __getitem__ arguments

### ISSUE THREAD

**Issue by kikocorreoso** [brython-dev/brython#443]
The following works in CPython 3.x:

``` python
class Pepe:
    def __getitem__(self, *args):
        args = args[0]
        print(args)

pepe = Pepe()

pepe[1,0,0:10:2]
```

And it returns:

```
(1, 0, slice(0, 10, 2))
```

In Brython, depending the input it returns an output but it is incorrect except in basic uses:

The following works as expected:

```
pepe[0]
pepe[0:10:1]
```

But the following doesn't work:

```
pepe[0, 0:10:1] # returns an incorrect slice
pepe[0,0] # returns an incorrect slice
pepe[0,:] # raises a syntax error
pepe[0,1,1,1,2,3,4,:] # raises a syntax error
```

I've been diving in the code but I can't find when `__getitem__` is called in this case. I had a look here:
- https://github.com/brython-dev/brython/blob/master/www/src/py_utils.js#L505 : but it seems it is not using this code.
- https://github.com/brython-dev/brython/blob/master/www/src/py_range_slice.js#L278 : I also had a look to the slice implementation with no luck.

@PierreQuentel If you can't find the time, please, could you point me to the correct place to try to solve this?

**Comment by PierreQuentel** [comment]
Kiko,

I don't like it when people give classes the name of Real Madrid players ;-)

Nevertheless, I tried your example. `pepe[1,0,0:10:2]`  is translated into

```javascript
getattr($locals___main__["pepe"],"__getitem__")(slice(tuple([1,0,0]),10,2))
```

So the problem is in the Python parser, somewhere in function `transition()` of py2js.js.

**Comment by kikocorreoso** [comment]
hahahahaha

Pepe is not saint on my book (he is nasty and not fair). I tend to call classes with simple names in spanish I don't know way.

Ok, I will try to have a look on `transition` to check if I can fix it.

Thanks for the hint.
