### ISSUE TITLE
Communication with JS

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [brython-dev/brython#444]
Is there a way to speed up the process of having JS call a python function than the code that is attached?

This allows JS to call a python function. Receive a value from the python function. Then pass that value into a JS callback.

The lag time can be 10 seconds.

### js_call_python.js
    function call_python_function(function_name, input_arguments, callback){
        if (input_arguments.constructor !== Array){
            input_arguments = [input_arguments];
        }
        for (var i = input_arguments.length - 1; i >= 0; i--) {
            if (typeof input_arguments[i] == "string"){
                input_arguments[i] = "'" + input_arguments[i] + "'";
            }
        }

        var return_event_name = guid()
        var event = new CustomEvent('python_function_event',
            {detail: {
                python_function: function_name,
                arguments: input_arguments,
                return_event: return_event_name
            }}
        );

        function remove_python_listener(ev){
            callback(ev.return_value);
            document.removeEventListener(ev.type, remove_python_listener);
        }

        document.addEventListener(
            return_event_name,
            remove_python_listener
        );
        document.dispatchEvent(event);
    };

    function guid() {
      function s4() {
        return Math.floor((1 + Math.random()) * 0x10000)
          .toString(16)
          .substring(1);
      }
      return s4() + s4() + '-' + s4() + '-' + s4() + '-' +
        s4() + '-' + s4() + s4() + s4();
    }

### js_call_python.py
    from browser import document, console, DOMEvent

    console.log("python loaded")

    def python_staging(event):
        run_string = event.detail.python_function
        run_string += '('
        for argument in event.detail.arguments:
            run_string += argument + ','
        if len(event.detail.arguments) > 0:
            run_string = run_string[0:-1]
        run_string += ')'

        exit_event = DOMEvent(event.detail.return_event)
        exit_event.return_value = eval(run_string)
        document.dispatchEvent(exit_event)

    document.bind('python_function_event', python_staging)

**Comment by kikocorreoso** [comment]
could you add a minimum working example (e.g., all embedded in an HTML page) to better understand what you want to do in order to try to find the best way to do so?

**Comment by BebeSparkelSparkel** [comment]
Here's a really simple example. Everything here could easily be done with brython but it illustrates what I'm trying to do.

This will run from file.

    <script type="text/javascript" src="http://brython.info/src/brython.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>

    <body onload="brython()">
        <input type="number" name="num_in" value="5">
        <button>Click</button>
    </body>

    <script type="text/javascript">
        $().ready(() => {
            $('button').click(() => {
                // do_something is the python function to run
                // $('input').val() is the argument for the python function
                // ret_val => {$('input').val(ret_val)} is the callback function which recives the value that the python function returned
                call_python_function('do_something', $('input').val(), ret_val => {$('input').val(ret_val)})
            })
        })
    </script>

    <script type="text/python">
        from browser import document, console, DOMEvent

        console.log("python loaded")

        def do_something(input1):
            return float(input1) * 6

        def python_staging(event):
            arguments = ''
            for arg in event.detail.arguments:
                arguments += arg + ','
            # removes last comma
            if len(event.detail.arguments) > 0:
                arguments = arguments[0:-1]

            exit_event = DOMEvent(event.detail.return_event)
            exit_event.return_value = eval('function(arguments)'
                .replace('function', event.detail.python_function)
                .replace('arguments', arguments))
            document.dispatchEvent(exit_event)

        document.bind('python_function_event', python_staging)
    </script>

    <script type="text/javascript">
        function call_python_function(function_name, input_arguments, callback){
            if (input_arguments.constructor !== Array){
                input_arguments = [input_arguments];
            }
            for (var i = input_arguments.length - 1; i >= 0; i--) {
                if (typeof input_arguments[i] == "string"){
                    input_arguments[i] = "'" + input_arguments[i] + "'";
                }
            }

            var return_event_name = guid()
            var event = new CustomEvent('python_function_event',
                {detail: {
                    python_function: function_name,
                    arguments: input_arguments,
                    return_event: return_event_name
                }}
            );

            function remove_python_listener(ev){
                callback(ev.return_value);
                document.removeEventListener(ev.type, remove_python_listener);
            }

            document.addEventListener(
                return_event_name,
                remove_python_listener
            );
            document.dispatchEvent(event);
        };

        function guid() {
          function s4() {
            return Math.floor((1 + Math.random()) * 0x10000)
              .toString(16)
              .substring(1);
          }
          return s4() + s4() + '-' + s4() + '-' + s4() + '-' +
            s4() + '-' + s4() + s4() + s4();
        }
    </script>

**Comment by kikocorreoso** [comment]
For me there isn't the lag you are suffering. It is almost immediate.

Could you tell us your environment (OS, browser, versions,...)?

On the other hand, why not just made the python function available via window? Something like:

```python
from browser import window

def do_something(input1):
    return float(input1) * 6

window.do_something = do_something
```

This way, you can use directly the python function in the js workspace.

**Comment by BebeSparkelSparkel** [comment]
That solution is so much better than mine. 
Thank you.

Also, the example I provided didn't have any lag for me either, but when I have many more larger js libraries loaded the lag increased dramatically.
