### ISSUE TITLE
Loading of encodings is not working

### ISSUE THREAD

**Issue by Mego** [brython-dev/brython#445]
In [my project that uses Brython](https://github.com/Mego/CodePageKeyboard), the [standard encodings](https://docs.python.org/3/library/codecs.html#standard-encodings) are consistently failing to load:

![image](https://cloud.githubusercontent.com/assets/853264/16209485/e312c204-36fc-11e6-9e30-bad060b2f433.png)

**Comment by PierreQuentel** [comment]
I'm not too sure of how rawgit manages all the files in a project repository, but in this case you'd rather include `brython_dist.js` instead of `brython.js`, so that importing modules from the standard library don't require Ajax calls : 
```
<script src="https://cdn.rawgit.com/brython-dev/brython/master/www/src/brython_dist.js"></script>
```

**Comment by Mego** [comment]
The README should be updated then: https://github.com/brython-dev/brython#zero-install-

**Comment by kikocorreoso** [comment]
Let us know if now it is more understandable: https://github.com/brython-dev/brython#zero-install-

If you want to modify or include whatever just make a PR or if you think know it is ok, please, close the issue.

Thanks.
