### ISSUE TITLE
copy.copy does not work for sets (or dictionaries)

### ISSUE THREAD

**Issue by dkosbie** [brython-dev/brython#451]
bug: copy.copy does not work for sets (or dictionaries)
code:
```
    import copy
    s = {1}
    t = copy.copy(s)
    print(t)
```
expected: {1}
observed: Error: un(shallow)copyable object of type <class 'set'>

Thanks.

David Kosbie
Associate Teaching Professor
Computer Science Department
Carnegie Mellon University

**Comment by PierreQuentel** [comment]
Many thanks for all the reports !
