### ISSUE TITLE
Class name as dictionary key fails

### ISSUE THREAD

**Issue by tiggerntatie** [brython-dev/brython#453]
The code:

    class A():
        pass
     
    d = {A:1}
    print(d[A])

Output, Python 3.4.3:

    1

Output, Brython 3.2.7:

    KeyError: <class 'A'>

**Comment by PierreQuentel** [comment]
I have fixed this to solve issue #451 ; can you check on the latest development version ?

**Comment by tiggerntatie** [comment]
This appears to be OK in the latest editor/console of the Brython distribution, but I can't get this latest brython.js to operate with runpython.com. I may have another look at it in a couple of weeks.

**Comment by tiggerntatie** [comment]
Looks good!
