### ISSUE TITLE
About the main file

### ISSUE THREAD

**Issue by x09326** [brython-dev/brython#454]
Hi, I'm a member of [cdnjs](https://cdnjs.com).
Thank you for you guys to update npm version.

I still have a problem.
Could you tell me which files I should host on cdnjs?
Because there are so many files, then I'm not sure which files I should add.

https://github.com/cdnjs/cdnjs/issues/8312

**Comment by PierreQuentel** [comment]
If you can't add all the files, then you can just add brython.js and brython_dist.js.

Thanks,
Pierre
