### ISSUE TITLE
Regression in dictionary comprehensions in Brython 3.2.7

### ISSUE THREAD

**Issue by andy31lewis** [brython-dev/brython#455]
Hello

I only know about this because a user of one of the games on my website contacted me to say the game had stopped working.

I have tried  to create a small piece of example code but have been unable to do so.

But if you go to http://mathsanswers.org.uk/games/dominate/index.html, and try dragging a domino onto the board, you will see the row and column totals update correctly.  That is because I have switched to using Brython 3.2.6 on my own server.

To see the error, go to http://mathsanswers.org.uk/games/dominate/index2.html, which uses the version of Brython from cdn.rawgit.com and drag a domino.  This will fail with "UnboundLocalError: local variable 'boardwidth' referenced before assignment" at line 2 in what must be an automatically generated module.

Sorry I can't pin down the problem any better than that.

Andy

**Comment by PierreQuentel** [comment]
Thanks for the report. I could reproduce the bug, the commit referenced above fixes it.

**Comment by andy31lewis** [comment]
Thanks very much for the speedy fix!
