### ISSUE TITLE
`from something import *` causes `Cannot read property '$nat' of undefined` on editor

### ISSUE THREAD

**Issue by paulo-raca** [brython-dev/brython#457]
When I execute `from xxx import *` on the online editor, things are imported as expected and everything works, but at the end of the execution I get an `Internal Javascript error: TypeError: Cannot read property '$nat' of undefined`

E.g., if I run 

```
from math import *
print(pi)
```

The output is 
```
3.141592653589793

Internal Javascript error: TypeError: Cannot read property '$nat' of undefined
  module 'editor' line 97
        exec(src, ns)
<completed in   5.00 ms>

```

**Comment by PierreQuentel** [comment]
I can't reproduce the error. In the [editor](http://localhost:8000/tests/index.html?lang=fr) at brython.info, this code prints the value of  π, but doesn't print the error message you mention. If it does for you, can you specify the Brython version and the browser ?

**Comment by paulo-raca** [comment]
Thanks for looking into it

Brython version: 3.2.7
Browser is Google Chrome version 50.0.2661.94 (64-bit) on an Ubuntu Linux Machine,
Screenshot: http://i.imgur.com/IFUXQmD.png

**Comment by paulo-raca** [comment]
Thanks!
