### ISSUE TITLE
start up performance (again)

### ISSUE THREAD

**Issue by alsoeric** [brython-dev/brython#461]
I'm still experiencing significant startup delays. I originally reported this on the Google group for brython but it's probably time for an official bug report.

I'm experiencing delays on the order of 50 to 60 seconds when loading up my brython application. I discovered that Firefox let me save the trace for performance issues and in that trace (see attached) I found a very long wait for some form of event handler call back in brython line 4106. Don't know if that's part of my code or part of the basic brython environment. The problem seems to show up when my module loads up urllib.parse..

Unfortunately, I don't have enough knowledge of brython to be able to debug what's happening. Any assistance in understanding would be appreciated and I'm willing to take on the effort to continue debugging this problem.

If I can't find a way of attaching the performance trace file, you can find it here on Google Drive. [https://drive.google.com/folderview?id=0B-HXyERXK9hLYUljMi1qRFoyeDQ&usp=sharing](url)

**Comment by alsoeric** [comment]
[slowbrython.zip](https://github.com/brython-dev/brython/files/379853/slowbrython.zip)
here's the compressed version of the Firefox performance trace

**Comment by PierreQuentel** [comment]
I don't know how to interpret this json. Could you give a url pointing to the script that takes so long to load ?

**Comment by alsoeric** [comment]
I don't have this running on a public machine. Let me see if I can put together a test case. In the meantime, if you load up Firefox, turn on the developer tools, choose the performance menu entry. When the performance panel comes up, on the left hand side you will see a button labeled import. Import slow brython.JSON there. Then you build the see the activity and timeline. In the meantime, I'll try to create a test case I can upload.

**Comment by alsoeric** [comment]
Okay, here's a test case. It's a little broken in that I don't understand why the H2 is not showing but if you look at it with a code inspector you will see that it does indeed change as the brython code says it should.

Another interesting thing I just noticed is that when the web console is turned on, it takes approximately 15 seconds to load up between the 'import fajax' print statement and the one after (import browser). If the web console is not active it only takes about 4 seconds but I've seen this go as high as 40 seconds even without a console.

I've tried to run this in chrome for comparison and it won't let me. It says 

brython.js:4138 XMLHttpRequest cannot load file:///C:/Users/eric/Documents/mobaxterm/home/Projects/brython_test/webapp/slowload.py. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.load_scripts @ brython.js:4138brython @ brython.js:4244onload @ slowload.html:23
brython.js:4125 Uncaught Error: cannot load script __main__ at : error 0

I'll add a bottle script to make it more like it's coming from a Web server.
[webapp.zip](https://github.com/brython-dev/brython/files/379895/webapp.zip)

**Comment by alsoeric** [comment]
ok here is the bottle-as-a-webserver version.
```
[eric.aho] ➤ python3 slowbottle.py
2016-07-23 14:12:51,941 - root - DEBUG - running
2016-07-23 14:12:51,941 - root - DEBUG - got data
Bottle v0.12.9 server starting up (using WSGIRefServer())...
Listening on http://localhost:8086/
Hit Ctrl-C to quit.
```
use this url in your browser
`http://localhost:8086/webapp/slowload
`
[webapp.zip](https://github.com/brython-dev/brython/files/379912/webapp.zip)

**Comment by PierreQuentel** [comment]
Thanks for the example. I also got very slow response times, but things were much better with a local version of brython_dist.js ; it seems that the rawgit CDN takes a long time to serve files, and if you use brython.js instead of brython_dist.js, there is an Ajax request to the CDN for every import.

**Comment by alsoeric** [comment]
I switched over to using a local copy on my server and I'm still seeing the 40+ second delay in the middle. 

I print out a bunch of log statements with timestamps and perform a Delta calculation with each entry. Here is what I have 4 timings between the start of the imports and the ends.

mdash -- starting import Timestamp: 2016-07-24 20:55:21 0:00:00
 brython_dist.js:4969:48
mdash -- ending import Timestamp: 2016-07-24 20:56:03 0:00:42.171000
 brython_dist.js:4969:48

From previous debugging attempts, it looked like this delay was from my friendly_Ajax code and specifically when loading urlib.parse. 

One clue is that there is  a huge  dom event and a function call in the middle of the delay. Is there any way I can figure out what is triggering this long delay? If I'm reading the information from the performance test correctly, brython.js 4137 is the call back that takes a long time. 

I'm trying to figure out a way I can give you access to the actual application so you can see what I'm doing. Personally I don't think it's my code because the delay happens in the import sequence of the application. I think I'm triggering a latent bug although, I will say I have been wrong before. :-)

**Comment by PierreQuentel** [comment]
I made a test with the latest version of Brython, the loading time is a few seconds, even with the RawGit CDN. I close the issue, feel free to reopen it if necessary.
