### ISSUE TITLE
Extending Classes for Javascript

### ISSUE THREAD

**Issue by ashes999** [brython-dev/brython#464]
I'm trying to write a Python class that plays nicely with MelonJS. Currently, MelonJS defines some classes, like `ScreenObject`:

```javascript
me.ScreenObject = me.Object.extend(
    /** @scope me.ScreenObject.prototype */
    {
      reset: function() { ... }
      destroy: function() { ... }
      ...
    })
```

It expects me to pass an object to one of its functions. Later, it calls `obj.reset.apply(arg1, arg2)` on that object.

I tried creating a class like this, but `reset` is undefined in JS:

```python
class ScreenObject:
  def reset(self):
    pass
```

I also tried:

```python
class MyScreen(melonjs.ScreenObject):
  ...
```

I get an error that `Object passed as base class is not a class`.

Is there any way for me to directly extend their Javascript classes? I also considered inheritance by composition (keep an instance of `melonjs.ScreenObject` inside my class and delegate calls to it), but that won't work unless MelonJS can call` myobj.reset()` et all.

**Comment by ashes999** [comment]
While hacking away at an MCVE, I found something that may work. It's a hack, and IMO an ugly one, but it gets me somewhere.

The root of it is that this Python object:

```python
class PyClass:
  def reset(self):
    pass
```

Looks like this in the JS debugger:
```javascript
{
  __class__ = {
    reset: function() { ... }
  }
}

All I need to do is copy/move `myObj.__class__.reset` to `myObj.reset`. I can actually do this by iterating all the properties and assigning them with `eval`:

```javascript
function copyBrythonMethodsToObjectRoot(bryObj) {          
  for (var m in bryObj.__class__) {
    eval("window.target." + name + " = window.target.__class__." + name);            
  }
}
```

I'll see if this works with my actual project code. 

Is there a better way to do this?

**Comment by ashes999** [comment]
This doesn't work well. For example, it doesn't inherit sub-subclass properties. I can't do this for every object and sub-object I create in Brython.

Is there a way to extend a Javascript "class" in Brython? I don't know enough about classes in JS, except to say that I don't fully understand how they decided to implement classes and inheritance in their framework (MelonJS).

**Comment by kikocorreoso** [comment]
To use a JS lib from the python namespace first you need to make the lib accesible. You could do so in the following way (supposing you've already added `<script src="melonJS.js">` somewhere in your page):

```
from browser import window

me = window.me # here we make accesible melonJS to the python namespace
```

If you want to use a js class you need to use `JSConstructor`. For example:

```
from browser import window
from javascript import JSConstructor

me = window.me # here we make accesible melonJS to the python namespace
screen_obj = JSConstructor(me.ScreenObject)()
```

I hope it helps.

**Comment by kikocorreoso** [comment]
BTW, this is not a Brython issue and it is better to ask this on the mail list: https://groups.google.com/forum/#!forum/brython :smile:

**Comment by ashes999** [comment]
Thanks for the clarification. I'll try it out and post some feedback. I actually already tried `JSConstructor`, but apparently not with the right syntax/parameters, because it didn't work for me.

Sorry about opening issues on GitHub! The mailing list seems very low-traffic, and I thought GitHub is a better place to post questions. 

I'll post to the mailing list if I have any follow-up questions about this.
