### ISSUE TITLE
Context-defined variable not declared

### ISSUE THREAD

**Issue by qsantos** [brython-dev/brython#465]
I have encountered the following bug in [the console](http://www.brython.info/console.htmlclas) (originally on `with open(filename) as f:`):

```
>>> class A:
...   def __enter__(self): return self
...   def __exit__(self, type, value, traceback): pass
... 
>>> with A() as x:
...   print(x)
... 
Traceback (most recent call last):
  module __main__ line 159
    traceback.print_exc()
  module $exec_58 line 2
    print(x)
NameError: x
>>> 
```

---

I think I found another bug while trying to add debug messages:

```
>>> class A:
...   def __enter__(self): return self
...   def __exit__(self, type, value, traceback): print("exit")
... 
>>> with A() as x:
...   print(x)
... 
exit
Traceback (most recent call last):
  module __main__ line 159
    traceback.print_exc()
  module $exec_83 line 2
    print(x)
  module $exec_78 line 3
    def __exit__(self, type, value, traceback): print("exit")
  module __main__ line 66
    doc['code'].value += str(data)
TypeError: 'str' object cannot be interpreted as an integer
```

**Comment by qsantos** [comment]
Thanks for the fix!

That was a pretty big change! What's the relation with asynchronous imports?

**Comment by PierreQuentel** [comment]
It's totally unrelated. I had started working again on asynchronous imports, with modifications to one of the Brython scripts (py2js.js) and I had to modify the same script to fix this issue. I should have done 2 distinct commits, but was too lazy for that ;-)

**Comment by qsantos** [comment]
Alright, thanks for the explanation!
