### ISSUE TITLE
input() uses JS's prompt() even in REPL

### ISSUE THREAD

**Issue by qsantos** [brython-dev/brython#468]
Using Javacript's prompt() can make sense, but, when using Brython's terminal, I would expect `input()` to work like in REPL. Within py_builtin_functions.js, I see that `input()` can handle files in stdin:

``` javascript
//not a direct alias of prompt: input has no default value
function input(src) {
    var stdin = ($B.imported.sys && $B.imported.sys.stdin || $B.stdin);
    // $B.stdout.write(src); // uncomment if we are to mimic the behavior in the console
    if (stdin.__original__) { return prompt(src); }
    var val = _b_.getattr(stdin, 'readline')();
    val = val.split('\n')[0];
    if (stdin.len === stdin.pos){
        _b_.getattr(stdin, 'close')();
    }
    // $B.stdout.write(val+'\n'); // uncomment if we are to mimic the behavior in the console
    return val;
}
```

 Looking at console.py however, I see that the console is not implemented as a file-like object.
- do you agree that input() should be configurable to work like in REPL?
- should that be the default when a terminal is in focus?
- is rewriting console.py to serve a file-like object okay?

I would need some time to familiarize myself more with Brython anyway.

**Comment by jonathanverner** [comment]
Unfortunately, input in python is a synchronous call which is impossible to implement in Javascript. The same problem is with imports, which currently use the deprecated synchronous http requests...

**Comment by qsantos** [comment]
Oh, I had not thought about that. Maybe there would be some way to split the current function in two and use the second half as a callback? But then, that would be an even larger change. If I think of something, I'll comment here.

**Comment by qsantos** [comment]
For reference, the proper way would be to use async/await but they are only planned for ES7. In the mean time, the cleanest way is [generators](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Iterators_and_Generators) from ES6 (which can be compiled to ES6). [Here for some examples.](https://ponyfoo.com/articles/understanding-javascript-async-await).

What is your opinion on using generators?

**Comment by jonathanverner** [comment]
Yes, in theory it could be implemented using generators (Brython currently supports Python's yield statement), but you would still need to modify the python code to be aware of this. It is reasonably straightforward to implement input as a generator and be able to write code like the following:

a = yield input("...")
print(a)

You still need to wrap the calling code in a method which takes care of continuing after getting the input (see e.g. the decorator interruptible in https://github.com/jonathanverner/brython-misc/blob/master/client/python_packages/lib/async.py).

**Comment by qsantos** [comment]
Well, that might be done on the Javascript side, by using a special object. In pseudo-Javascript, this:

```python
input()
```

would become

```javascript
yield InputCalledMagicMarkerObject
```

whenever a Javascript function would be detected to be a generator, it would need a wrapper like so:

```javascript
iterator = generator()
while (true) {
    ret = next(iterator)
    if (ret == InputCalledMagicMarkerObject) {
        // a miracle happens
    } else {
        // classical Python generator, go on with the interpretation
    }
}
```

Now, regarding the miracle, if `g()` calls `f()` and `f()` calls `input()`, then `g()` must become a generator and we must change the call to `f()` to a "yield from". It is definitely extremely complex, but that might actually work.

**Comment by PierreQuentel** [comment]
Unfortunately I don't think this can be done. Javascript is mostly non-blocking : you can't stop the execution of a script for N seconds, or stop it until the user clicks on a button or hits the Enter key, and then _execute the next instruction_. All you can do is _run a function_ after some time has passed (with `setTimeout` and the like) or when the event occurs (with an event listener).

```python
time.sleep(n)
(rest of block)
```
must be translated to something like
```javascript
setTimeout(n, function(){
    (translation of rest of block)
})
```
A simulation of `time.sleep()` could be :

```javascript
t0 = new Date()
while(true){
    if((new Date())-t0)>N){break}
}
```
and this was actually implemented in previous versions of Brython, but it freezes the CPU, and it only works for the first call to `time.sleep()`.

Similarly, for `input()`, the equivalent of :

```python
x = input()
some_python_code
```

would be something like

```javascript
(dynamically create a DIV with an input field "entry")
entry.addEventListener('keyPress', function(ev){
    if(ev.which == 13){
        x = entry.value
        (translation of some_python_code)
    }
})
```

In this case, replacing `input()` by an infinite `while` loop in Javascript such as
```javascript
while(true){
    if(entry_is_done()){break}
}
(translation of some_python_code)
```
(whatever you put in a function `entry_is_done()`) never gives back control, ie you never reach the line `(translation of some_python_code)`. Using a generator doesn't solve this problem.

The only solution that I found which is compliant with how `input()` is supposed to work is to use `prompt()`, which is a blocking function.

At least this is the result of all the things I tried to simulate a blocking beheviour. If you have better solutions I would be very happy to know !

**Comment by qsantos** [comment]
It's actually technically possible with the recent generators from ES5/ES6 and future async functions from ES7. With a generator, you could do something like:

```javascript
function pyFunction1() {
    // ...
    var x = yield InputCall
    // ...
}
```

where `InputCall` would be a magic value. Then you would do something like:

```javascript
function init() {
   // ...
   current_program = pyFunction1();
   resumeExecution();
}
function resumeExecution() {
  var yielded = current_program.next();
  if (yielded == InputCall) {
  } else {
    // ...
  }
}
function onReturn() {
    resumeExecution();
}
```

Now, the issue is that any translated function calling `pyFunction1()` must now also be a generator. The simplest is probably to make any translated function a Javascript generator. Similarly, with async functions, all translated functions must become async functions.

So it is actually possible, but definitely very complex.

**Comment by qsantos** [comment]
In my particular case, I only use `input()` in two places. One is not *that* important, and the other is through a call to `code.interact()`, which is basically the last thing executed in the script.

Although `input()` would be hard to implement, it may be somewhat easy to implement `code.interact()` and the related functions so that they interrupt the execution of the script and resume the normal execution of the REPL (with a minor state change). Even if not perfect, that should handle quite a few situations.

**Comment by zwz** [comment]
I want to customize `input()` and find this issue.

> Similarly, for `input()`, the equivalent of :
> 
> ```python
> x = input()
> some_python_code
> ```
> 
> would be something like
> 
> ```js
> (dynamically create a DIV with an input field "entry")
> entry.addEventListener('keyPress', function(ev){
>     if(ev.which == 13){
>         x = entry.value
>         (translation of some_python_code)
>     }
> })
> ```

@PierreQuentel

I was thinking, if this python code
```python
x = input()
some_python_code
```

could be translated into 

```js
function myinput(){
      return new Promise(function(resolve, reject){
         (dynamically create a DIV with an input field "entry")
         entry.addEventListener('keyPress', function(ev){
         if(ev.which == 13){
             resolve(entry.value)
         }
      })
})
(async function(){
   x = await myinput() 
  (translation of some_python_code)
})()
```

**Comment by PierreQuentel** [comment]
This would mean that the translation egine (Python -> Javascript) would treat a call to `input()` differently from any other function call, only based on the identifier `input`. But then, what if your code defines `my_input = input` and then you call `my_input()` ?

Besides, if the `input()` is inside a function

```python
def f():
    return input()
```

with your suggestion, this would be translated to

```javascript
function f(){
    return await someAsyncFunction()
}
```

which would be a syntax error because the Javascript function is not asynchronous.

**Comment by zwz** [comment]
Well, what if the translation engine(Python -> Javascript) translates any python function to an `async` function, and a function call to an `await` call？
Then 
```
def f():
    myinput()
    return input()
```
is translated to
```
async function f(){
    await myinput()
    return await someAsyncFunction()
}
```

**Comment by PierreQuentel** [comment]
I have tested this option, and the result is an impressive decrease in performance.

**Comment by zwz** [comment]
In my case, performance decrease is tolerable, since the code is simple (just for education).

I am wondering if it is a good idea to add an option for the engine to enable the `async/await` translation, or even more we can tell the engine which functions should be translated with `async/await`.

It would help many people including me to customize Brython.

**Comment by PierreQuentel** [comment]
The Python language reference states that functions must be explicitely declared asynchronous with the keyword `async`. Brython is as compatible to the reference as possible, so an option to transform all or some "regular" functions to asynchronous is excluded (besides being terribly difficult to implement, and generating terribly confusing bugs even if it was implemented).
