### ISSUE TITLE
Calling brython() outside of body tag onload

### ISSUE THREAD

**Issue by hir3npatel** [brython-dev/brython#478]
Hi,

Instead of doing this:

`<body onload="brython()">
`

I'd like to do this:

```
> <script>
>     setTimeout(function(){ 
>         var script = document.createElement('script');
>             script.src = "/static/brython/brython.js";
>             script.onload = function () {
>                 brython({debug:1, pythonpath:["/static/brython/Lib"]});
>             };
> 
>             document.head.appendChild(script);
>     }, 5000);
>     </script>
```

The reason for this is that my brython code on the page imports re, which is a slow import. If I call brython() in the body onload, the page does not render a thing until all the imports are fetched. I'd like to show a loading indicator on the page while brython initialises.

The issue I have with the second method, is that libraries do not get searched as per the pythonpath passed to the function. brython.js fetches fine, and executes, but then tries to get other libraries such as browser.ajax, from url "/Lib/browser/ajax.py", and not "/static/bython/Lib/browser/ajax.py" as I'd expect. I end up with an ImportError.

Is this a known issue, or am I using it incorrectly, or is there a way to work around it?

**Comment by qsantos** [comment]
You are using it correctly. Brython stores the paths within `$B.path` but seems to ignore it while importing modules. The way it determines the URL seems fairly complex; I would expect everything to be handled at a single point (`$download_module()`), but it does not seem to work like that. Maybe @PierreQuentel can help?

**Comment by PierreQuentel** [comment]
The import mechanism is indeed very complicated, even for me... I have made a few modifications, can you test if things get better with the latest development version ?

**Comment by hir3npatel** [comment]
I can't say there is a noticeable difference. I am trying it on one of my complex pages involving more imports than usual. I am also trying out your suggestions on 491 to compile just used modules, and perhaps pre-compile to js.

**Comment by PierreQuentel** [comment]
There is no clear conclusion for the moment on this issue. I close it, feel free to re-open it if necessary.
