### ISSUE TITLE
DOMEvent on anchor tag does not fire

### ISSUE THREAD

**Issue by hir3npatel** [brython-dev/brython#495]
Hi, I am trying to do the following, upon a handler for an ajax request, to get the browser to show or prompt to save a pdf file which is the response from the ajax call.

``````
    ```
    blob = JSConstructor(window.Blob)
    b = blob([req.text])

    createUrl = JSObject(window.URL.createObjectURL)
    url = createUrl(b)

    a = html.A()
    a.href = url
    a.download = "report.pdf"
    a.dispatchEvent(DOMEvent('click'))
    ```
``````

This works except that the click event is not fired, and the browser (chrome) does not open the pdf or prompt to save. There are no errors in the console. If I give the a tag some text, and append it onto the dom, and manually click it after the ajax response, then it opens the pdf as I expect it to. I would however not like to have to put an extra link onto the dom and make the user click again.

Any ideas or comments or suggestions? Thanks.

**Comment by jonathanverner** [comment]
Just doing `a.click()` instead of `a.dispatchEvent(...)` works for me...

**Comment by hir3npatel** [comment]
It works here too. Thanks!

But is the dispatchEvent() supposed to work? The documentation at the end of this page suggests so:
http://brython.info/static_doc/en/events.html

If so, is it a bug, or else should the documentation be changed?

I have also not seen things like .click() in the docs, so it's not immediately clear how to do events beside dispatchEvent.

**Comment by PierreQuentel** [comment]
The problem with your example is that `DOMEvent("click")` does not refer to a valid event : `DOMEvent` is a wrapper around `window.Event` but a click is an instance of `window.MouseEvent`

This modified code works for me : 
```python
from browser import window, html
from javascript import JSConstructor

Blob = JSConstructor(window.Blob)
MouseEvent = JSConstructor(window.MouseEvent)

b = Blob(['abcdef'])

createUrl = window.URL.createObjectURL
url = createUrl(b)

a = html.A('test')
a.href = url
a.download = "report.pdf"

a.dispatchEvent(MouseEvent('click'))
```

**Comment by hir3npatel** [comment]
Ah, I should have been using MouseEvent, thanks for the correction. It wasn't clear to me from the docs though, so maybe an example anchor tag click in the docs could be useful. Thanks for clearing it up.

**Comment by PierreQuentel** [comment]
The documentation has been updated. Thanks again !
