### ISSUE TITLE
Brython does not parse weirdly split tuple comprehension

### ISSUE THREAD

**Issue by jonathanverner** [brython-dev/brython#499]
The following code

``` python
list_of_data = [1,2,3]
list_of_data = (
        bytes(data) if isinstance(data, memoryview) else data
        for data in list_of_data)
```

parses just fine in Python 3.4 but Brython compilation results in

``` python
module $exec_160 line 3
  bytes(data) if isinstance(data, memoryview) else data
               ^
IndentationError: unexpected indent
```

**Comment by PierreQuentel** [comment]
The commit referenced above fixes the bug, but the code still has a problem : 

```
print(list(list_of_data))
```
raises an exception because the same name is used for the generator expression and the list referenced inside it. I keep the issue open until this is fixed.

Thanks !

**Comment by jonathanverner** [comment]
Thanks for the quick fix!

**Comment by PierreQuentel** [comment]
The commit referenced above fixed the remaining issue.
