### ISSUE TITLE
Name errors not reported in console

### ISSUE THREAD

**Issue by tiggerntatie** [brython-dev/brython#505]
In Brython 3.2.7 console:

    >>>print(undefinedvariable)

does not display an error. No new prompt is displayed and the console needs to be restarted.

Expected output:

    >>> print(undefinedvariable)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    NameError: name 'undefinedvariable' is not defined

Similarly, attempting to use undefined object attributes has a similar result. e.g.:

    >>>print("".undefinedmethod())

**Comment by PierreQuentel** [comment]
This is very embarrassing... but it seems that the bug has disappeared in the current development version. Can you try ?
