### ISSUE TITLE
does it support all packages?

### ISSUE THREAD

**Issue by suriyaJaay** [brython-dev/brython#508]
i try to work with below example in brython 

import numpy as np
import matplotlib.pyplot as plt

x = np.arange(0, 5, 0.1);
y = np.sin(x)
plt.plot(x, y)
plt.show()

but it show the following error in editor

Traceback (most recent call last):
  module editor line 100
    traceback.print_exc(file=sys.stderr)
  module $exec_160 line 1
    import numpy as np
ImportError: No module named numpy
<completed in 1342.00 ms>

and also i need to know does it support all default and custom packages ? 
pls consider this query it would be more userfule  if brython have R programming playground

**Comment by jonathanverner** [comment]
Unfortunately, numpy does not work in Brython (and, as far as I can tell, it would be very hard to make it work, as it is implemented in C and not in Python). You might try [emscripten](http://kripken.github.io/emscripten-site/) which theoretically should work, though I have no idea, whether it works in practice.

**Comment by PierreQuentel** [comment]
In the documentation there is a [comparison](http://brython.info/static_doc/en/stdlib.html) between Brython and CPython standard library
