### ISSUE TITLE
is set_loop_timeout working ?

### ISSUE THREAD

**Issue by wagnerf42** [brython-dev/brython#510]
hi, I'm using http://brython.info/tests/editor.html?lang=fr

I type the following code:

```
from browser.timer import set_loop_timeout
set_loop_timeout(1)
while True:
    pass
```

on first run, I need to kill the script but
subsequent runs (I re-click the exec button) work ok.
however if I refresh the webpage then again
the first run does not work

since the function is not really documented it might be in an work-in-progress state ?

**Comment by jonathanverner** [comment]
I think it was recently removed, see commit 3f37f2f85ff71816867300cac60abba5dd902f1f

**Comment by PierreQuentel** [comment]
Bad luck, really... 

I introduced this in reply to issue #289. After telling the author of the issue that I had added `set_loop_timeout` , I got no feedback from him, no one ever mentioned this function and I didn't document it. When preparing version 3.2.8 I saw that the checkbox "loop timeout" on the tests home page was still there, and as I thought no one was interested I removed it, and all the associated code, with no warning except in the commit mentioned by Jonathan.

I don't think I will re-introduce it, all the more if it didn't work.

**Comment by ankhuve** [comment]
Hi @PierreQuentel ,
I would love this functionality to be reintroduced, would that be possible? 

I'm currently trying to implement it myself by looking at your commit but seeing as the rest of the codebase has changed a bit since 2016, I'm guessing I will run into a couple of problems on the way.

**Comment by wagnerf42** [comment]
hi, 

just to say we finally managed to do that outside of brython using web workers. 

so, if you really need it you should not be stuck. 

Frederic 



De: "Erik Forsberg" <notifications@github.com> 
À: "brython-dev/brython" <brython@noreply.github.com> 
Cc: "frederic wagner" <frederic.wagner@imag.fr>, "Author" <author@noreply.github.com> 
Envoyé: Lundi 5 Mars 2018 09:56:43 
Objet: Re: [brython-dev/brython] is set_loop_timeout working ? (#510) 



Hi [ https://github.com/pierrequentel | @PierreQuentel ] , 
I would love this functionality to be reintroduced, would that be possible? 

I'm currently trying to implement it myself by looking at your commit but seeing as the rest of the codebase has changed a bit since 2016, I'm guessing I will run into a couple of problems on the way.

**Comment by ankhuve** [comment]
Glad to hear that!
Using web workers was my initial thought as well before I found this thread. Are you able to share your solution (or parts of it)?

**Comment by ankhuve** [comment]
@wagnerf42 Do you think you could share part of your solution of running Brython using web workers? Having issues with imports at the moment with our attempt!

**Comment by jonathanverner** [comment]
@ankhuve did you look at [http://www.brython.info/static_doc/en/webworker.html]? I have recently reworked `asyncio` and after that is merged, I will need to update the documentation slightly, but this should allow you to use webworkers in Brython.  If not then I'll try looking at it (eventually ;-))
