### ISSUE TITLE
About the main files in version 3.2.1 & 3.2.2

### ISSUE THREAD

**Issue by x09326** [brython-dev/brython#511]
Hi, I'm trying to host this lib on [cdnjs](https://cdnjs.com).

But the main files **brython_dist.js** and **brython.js** in version 3.2.1 and 3.2.2 can't be minified.
Could you help me to figure it?
Thanks.
https://github.com/cdnjs/cdnjs/pull/8453

**Comment by PierreQuentel** [comment]
Hello,

These versions are getting old, I don't think it's useful to host them any more. Anyway, these files are already minified ; when applying uglifyjs you won't decrease the size by more than 5%.
