### ISSUE TITLE
Preparing data to be processed in JS

### ISSUE THREAD

**Issue by gromgull** [brython-dev/brython#512]
I am trying to write brython code to use with angular. I.e. I want to implement the angular controllers, etc. in Brython, but have Angular manipulate the DOM etc. 

This seems awkward, because preparing data that should be processed in JavaScript is difficult. 

A basic example: 

```<html>
    <head>
        <script type="text/javascript"
                src="https://cdn.rawgit.com/brython-dev/brython/3.2.2/www/src/brython_dist.js">
        </script>
        <script type="text/javascript"
                src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.6/angular.js"></script>

        <script type="text/python">

         from browser import document, window

         def main_controller(scope):
             scope['things'] = [ dict(label=str(x), value=x*10) for x in range(10) ]

         angular = window.angular

         mod = angular.module('myApp', []);

         mod.controller('MainCtrl', [ '$scope', main_controller ] )

         angular.element(document).ready(lambda : angular.bootstrap(document, ['myApp']))

        </script>

    </head>
    <body ng-controller="MainCtrl" onload="brython()">

        <ul>
            <li ng-repeat="t in things">
                {{ t.label }} = {{ t.value }}
            </li>
        </ul>

    </body>
</html>
```

Here the Brython code prepares a list of dicts, and these should be processed by angular. But it doesn't work out. 

My best attempt has been to "inject" the `Object()` constructor into `window` from js and use `JSConstructor` with this. This works if I do: `windows.myvar = JSConstructor(window.Object)(dict(a=2))` in Brython, and then `window.myvar` is a normal JS object. 

However, if it's in a list it gets wrapped somehow. 

Am I missing something stupid? There is no reverse function of `js_obj.to_dict()` ?

**Comment by kikocorreoso** [comment]
It seems this is not a brython issue.

It is better to post questions/doubts in the mail list: https://groups.google.com/forum/m/?fromgroups#!forum/brython
