### ISSUE TITLE
Stubbed functions documented as covered

### ISSUE THREAD

**Issue by LordRatte** [brython-dev/brython#515]
I recently tried to use chdir and mkdir from os but I couldn't see any visible effect. The standard distributions list has posix and os as supported. After much searching I stumbled across the source code and saw that most of these functions were stubbed.
`brython/www/src/Lib/posix.py`

Can we really say that it's been ported if it just runs `pass`?

**Comment by kikocorreoso** [comment]
For security reasons some file system operations are not allowed in a client side environment. Brython cannot overpass this.

OTOH, Brython has to mimic some behaviour in order to provide other functionality that has sense in a browser.
