### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'test_ugl.js' using make_dist.py

### ISSUE THREAD

**Issue by kikocorreoso** [brython-dev/brython#517]
When I run:

```
python make_dist.py # scripts folder
```

I get:

```
../www/src/unicode.min.js: 1: ../www/src/unicode.min.js: uglifyjs: not found
Traceback (most recent call last):
  File "make_dist.py", line 104, in <module>
    with open('test_ugl.js') as fobj:
FileNotFoundError: [Errno 2] No such file or directory: 'test_ugl.js'
```

Are there any clear instructions about what do I need from node in order to run _make_dist.py_.

Maybe an option avoiding the 'uglification' of the files for development purposes is a good idea.

**Comment by PierreQuentel** [comment]
Hi Kiko,

Do you have uglifyjs installed on your PC ? For each Brython source file __test_ugl.js__ is generated at the previous line, by a call to 

```
uglifyjs <brython_source_file> -c -o test_ugl.js
```

**Comment by kikocorreoso** [comment]
I have it but it is not working as it is asking for more dependencies ¿?

Is uglifyjs the only needed package to make it work?

**Comment by PierreQuentel** [comment]
Well, normally yes, I just did `npm install uglifyjs` if I remember correctly.

Anyway I'm not sure I will keep it, it doesn't minify much more than my own Javascript minifyier - which is buggy, but ok for Brython files.

**Comment by kikocorreoso** [comment]
@PierreQuentel  Have you tried [jsmin](https://pypi.python.org/pypi/jsmin), a pure python js minifier? It seems is maintained.

Let me know your plans about uglifyjs. I think, IMHO, that if most of the toolchain should be on the Python side it would be better. Maintain a node and python toolchain for basic stuff can be painful.

**Comment by PierreQuentel** [comment]
@kikocorreoso 
I didn't know it ; I tried to replace my own `javascript_minifier` by `jsmin`, unfortunately the version of __brython.js__ generated by this script raises a Javascript error when loaded...
