### ISSUE TITLE
October update of brython_dist.js throws SyntaxError: Unexpected token <(…)

### ISSUE THREAD

**Issue by stroobandt** [brython-dev/brython#518]
Since the Tue 04 Oct 2016 16:21:01 CEST update of <https://brython.info/src/brython_dist.js>,
I am experiencing an Uncaught Error on <http://hamwaves.com/propagation/en/index.html>

	SyntaxError: Unexpected token <(…)
	brython_dist.js:4157 Javascript error SyntaxError: Unexpected token <(…)
	brython_dist.js:4954 Traceback (most recent call last):
	RuntimeError: SyntaxError: Unexpected token <
	brython_dist.js:4128 Uncaught Error
	2brython_dist.js:6906 Uncaught Error

The only instance where I am using a strictly less than `<` is in
<http://hamwaves.com/propagation/ssne+fof2+muf.py> on line 116:

        if(distance < nearest):

Even when there is no geolocation available, this used to work.

I am not experiencing this problem with a subset of the code:
<http://hamwaves.com/propagation.prediction/en/index.html>

**Comment by stroobandt** [comment]
Error messages remain unaltered when changing the code to:

        if(distance <= nearest):

So the `SyntaxError: Unexpected token <(…)` may well originate from inside `brython_dist.js`

**Comment by PierreQuentel** [comment]
Sorry about that. It was a side effect of the work on issue #491

**Comment by stroobandt** [comment]
No problem. I have to thank you Pierre, for the great work you do, the very quick resolution and the speedy point release!
