### ISSUE TITLE
Using brython with Jinja, Flask, few issues

### ISSUE THREAD

**Issue by afidegnum** [brython-dev/brython#519]
HI, I have an issue, 

I have successfully inserted brython script into the jinja template which is working, however i am finding difficult inserting jinga template tags inside the brython script.

any workaround ?

**Comment by PierreQuentel** [comment]
Can you give an example of what doesn't work as you would expect ?

**Comment by PierreQuentel** [comment]
Until you provide more information I close the issue, don't hesitate to reopen it if necessary.

**Comment by Frick-David** [comment]
Gonna comment as I seem to be having an issue with flask and jinja templating. I am not entirely sure what is happening but I get an error about recursion keeps happening with end. I am pretty sure my Brython code is correct. The only thing I can think of is that on page load brython interferes with jinja somehow
