### ISSUE TITLE
Brython cannot strip out bracket characters

### ISSUE THREAD

**Issue by imeida** [brython-dev/brython#521]
Hi. I found some issue today.

I'm running Brython version 3.2.8.
When I run a code like this...

```
a = '[1,2,3]'  
print(a.strip(']'))  
print(a.strip('3]'))

```

It should print the following on the screen.

```
[1,2,3
[1,2,
```

But I got this instead.

```
[1,2,3]    #The ']' is not stripped out.
[1,2,      #Output correct.
```

And another example is...

```
b = '[1,2,3]}'
print(b.strip('}'))
print(b.strip(']}'))
```

It should print

```
[1,2,3]
[1,2,3
```

But I got this instead.

```
[1,2,3]     #Output correct.
[1,2,3]}    #The ']}' characters are not stripped out.
```

Is this a known issue or do you have anyway to fix this?

Best regards.

**Comment by PierreQuentel** [comment]
Thanks for reporting this !
