### ISSUE TITLE
error fetching dependent files for datetime.datetime.strptime

### ISSUE THREAD

**Issue by hir3npatel** [brython-dev/brython#526]
Most dependencies seem to get the url correct:

> https://10.0.0.38/static/brython/Lib/re.py?v=1478676059897
> https://10.0.0.38/static/brython/Lib/locale.py?v=1478676059380
> https://10.0.0.38/static/brython/Lib/datetime.py?v=1478676379226

But if I use datetime.datetime.strptime in an ajax call, it seems to try and fetch dependencies at the wrong url:

> https://10.0.0.38/client/_locale.py?v=1478676466886 (_locale.py does not exist in my latest brython zip file extract?)
> https://10.0.0.38/static/brython/Lib/site-packages/_locale.py?v=1478676466930 (in my zip extract, Lib/site-packages has an empty dir called "ui", and nothing else?)
> https://10.0.0.38/static/brython/Lib/site-packages/_locale/__init__.py?v=1478676466953 (no such file)
> 

code that is using strptime tries to format a 8601 date in the response, as follows:
`datetime.datetime.strptime(o['created'],"%Y-%m-%dT%H:%M:%S.%f%z")`

**Comment by kikocorreoso** [comment]
I can't see any call to `_locale` module in the repo (except in a test).

Please, could you post the code raising the error, the distribution/version/... of brython you are using, a minimum example to reproduce your steps and the error,...?

**Comment by hir3npatel** [comment]
Version is the latest release, the top of my brython.js file says:

> // brython.js brython.info
> // version [3, 3, 0, 'alpha', 0]
> // implementation [3, 2, 8, 'final', 0]
> // version compiled from commented, indented source files at github.com/brython-dev/brython
> 

To reproduce:

> mkdir test
> mkdir test/static
> (place brython folder extract into test/static/brython)
> touch file test/index.html

Put this contents in to index.html

```
<head>
<script src="/static/brython/brython.js"></script>
</head>
<body onload="brython()">
<script type="text/python">
import datetime

datetime.datetime.strptime("2006-12-122T14:55:00.000000+00:00","%Y-%m-%dT%H:%M:%S.%f%z")
</script>
</body>
```

Start sample webserver in folder test, with: python -m SimpleHTTPServer

In the browser go to localhost:8000

It fetches brython.js without issues. It then tries to fetch other related files that fail, here are some of my webserver logs when I load index.html

> "GET /static/brython/brython.js HTTP/1.1" 200 -
> "GET /_locale.py?v=1478710179307 HTTP/1.1" 404 -
> "GET /_locale/__init__.py?v=1478710179325 HTTP/1.1" 404 -
> "GET /static/brython/Lib/site-packages/_locale.py?v=1478710179340 HTTP/1.1" 404 
> "GET /static/brython/Lib/site-packages/_locale/__init__.py?v=1478710179353 HTTP/1.1" 404 -

**Comment by kikocorreoso** [comment]
Do you get any error on the js console of your browser?

I think this is the expected behavior. If you do:

```
import sys
print(sys.path)
```

You can see the places where brython will look for modules when you use an `import`

**Comment by hir3npatel** [comment]
Ah you are right, I did not spot the error closely enough. It is complaining that the string does not match my format in the strptime line. I'm doing something wrong here:

`"2006-12-122T14:55:00.000000+00:00","%Y-%m-%dT%H:%M:%S.%f%z"`

Sorry for the bug and noise, not a brython issue then. The 404's threw me off.
