### ISSUE TITLE
http://brython.info/ OFFLINE

### ISSUE THREAD

**Issue by Tset-Noitamotua** [brython-dev/brython#528]
Your official site seems to be offline.

**Comment by andmart** [comment]
Forbidden

You don't have permission to access / on this server.

**Comment by PierreQuentel** [comment]
Thanks, it's the same for me. I don't know why, I have sent a message to the web hosting company

**Comment by PierreQuentel** [comment]
The site works again.

**Comment by Tset-Noitamotua** [comment]
Thanks for info.

Do you know how long your site was offline? You might want to try some services that check your site's online status and notify you about downtimes.

**Comment by PierreQuentel** [comment]
The logs start showing 403 errors about 24 hours ago. It's the first time it happened in more than 4 years, but yes, I will susbcribe to such service

**Comment by kikocorreoso** [comment]
It is happening again!!!

**Comment by PierreQuentel** [comment]
Yes, and this time the hosting company sent me a mail saying that it is because of the script __/cgi-bin/timeout.py__ which has been detected as a security issue !!! It's been on the site for years, and when the site was blocked yesterday they didn't tell me it was because of that. I'm angry !

**Comment by kikocorreoso** [comment]
Now I'm accessing again.
It is weekend, don't be :angry:
