### ISSUE TITLE
sys.path can't be modified

### ISSUE THREAD

**Issue by BrenBarn** [brython-dev/brython#531]
Looks like some recent change broke sys.path.  I just pulled the latest to my local repo and when I use it and do something like this:

	import sys
	print("Before", sys.path)
	sys.path.insert(0, "https://whatever.com/whatever")
	print("After", sys.path)	

It prints the same thing both times.  I also notice that if I do `x = sys.path` and then `y = sys.path`, then `x is y` is False.  Perhaps that is related.

**Comment by BrenBarn** [comment]
It appears to be due to [this commit](https://github.com/brython-dev/brython/commit/26a36e3ba0bdd2983793ee48b87aa48e2ffe2a11).

**Comment by jonathanverner** [comment]
Hmm, that commit also broke the CI tests. In particular the test in `test_import.py` which tries to `import hello ` after modifying `sys.path`:

```python
# Add VFS file URL at the beginning of import search path
vfs_url = __BRYTHON__.brython_path + '../tests/test.vfs.js'
sys.path.insert(0, vfs_url)

from hello import *
```

**Comment by PierreQuentel** [comment]
I had noticed that this test didn't pass, but now it does, at least in the editor (I just cloned the repo to check). I don't know why it doesn't in the CI test.

**Comment by jonathanverner** [comment]
Your latest commit passes in the CI! Thanks for fixing it... :-)
