### ISSUE TITLE
asyncio import is not working in the console

### ISSUE THREAD

**Issue by baoboa** [brython-dev/brython#535]
the code block in www/doc/en/asyncio.md is not working in the console (3.2.9)

>Brython 3.2.9 on Netscape 5.0 (X11)
import asyncio
Traceback (most recent call last):
  module __main__ line 134
    traceback.print_exc()
FileNotFoundError: No module named 'asyncio'

**Comment by jonathanverner** [comment]
Thanks for the report. I will try to look into this, but I am not sure that I will have time before Christmas.

**Comment by baoboa** [comment]
i was interest in the topic so i did a test , i am in no hurry 

a question , can we expect to plug the event loop to the asyncio mainloop ?

**Comment by PierreQuentel** [comment]
It's my fault, I forgot to upload the `asyncio` and `concurrent` packages on brython.info...

It should work now, but the loading time is awfully long : there are no less than 95 (yes, ninety five) modules to import...

**Comment by baoboa** [comment]
i can import, thanks

@jonathanverner 
another point, in www/doc/en/asyncio.md return is not at t.value() but t.result() if i look at standard python3.5
