### ISSUE TITLE
list(OrderedDict.keys()) results in `ReferenceError: $locals_collections is not defined`

### ISSUE THREAD

**Issue by Bystroushaak** [brython-dev/brython#536]
```python
from collections import OrderedDict
from browser import alert

a = OrderedDict(hello=1)
alert(list(a.keys()))
```

Causes following error:

![snimek obrazovky na 2016-12-14 18-47-38](https://cloud.githubusercontent.com/assets/227282/21193831/ebf9fe70-c22d-11e6-8da1-d641ef98fc29.png)

Expected output:

```python
['hello']
```

## System

Chromium Version 53.0.2785.143 Built on Ubuntu , running on LinuxMint 18 (64-bit).

Brython version used:

- Brython3.2.9-20161127-142438.tar.bz2
- http://brython.info/src/brython_dist.js

## Replication

Paste the snippet from the beginning of the issue to the http://brython.info/tests/console.html?lang=en

![snimek obrazovky na 2016-12-14 18-53-39](https://cloud.githubusercontent.com/assets/227282/21194031/b01d81f0-c22e-11e6-9f41-edc07758b6a7.png)

**Comment by PierreQuentel** [comment]
The example works as expected with the latest development version. Can you confirm ?

I think the bug was fixed in commit 55ccac49636e2fd61dad6a91632fe25096512863.

**Comment by Bystroushaak** [comment]
Yes, it seems to be working. Is there any description on how to build the single file distribution from the cloned repository?

**Comment by PierreQuentel** [comment]
You can generate it with the script `scripts/make_dist.py`, but you can also download the files at rawgit, for instance https://cdn.rawgit.com/brython-dev/brython/master/www/src/brython_dist.js

**Comment by Bystroushaak** [comment]
Thak you!
