### ISSUE TITLE
onchange event atribute missing?

### ISSUE THREAD

**Issue by Huyston** [brython-dev/brython#538]
Hello,

I'm trying to produce an element <input id="1" onchange="func()">, however the onchange doesn't atribute doesn't work, producing only <input id="1">.

Is the implementation missing for onchange or is there another way of doing this?

**Comment by Huyston** [comment]
I've looked into the code and I saw that the bind method is enforced and the event shouldn't start with "on". I tried .bind('onchange',func) when the correct is .bind('change',func)

All working now, sorry for opening an issue.

**Comment by PierreQuentel** [comment]
No worries William, glad that the documentation was helpful !
