### ISSUE TITLE
Bug: expansion of f(*my_args, a, b) inverses order of arguments

### ISSUE THREAD

**Issue by hrehfeld** [brython-dev/brython#542]
See the following test case:

    def test(*args):
        print(str(args))

    if __name__ == '__main__':
        a01 = [0, 1]

        test(*a01, 2, 3)

        args = a01 + [2, 3]
        test(*args)

with python 3.5.2 prints:

    (0, 1, 2, 3)
    (0, 1, 2, 3)

but with brython:

    (2, 3, 0, 1)
    (0, 1, 2, 3)

My Brython version is 3.3.0 from bower.

**Comment by PierreQuentel** [comment]
Thanks for the report. This syntax was introduced in Python 3.5 and Brython is 3.3ish, but there's no reason not to include it.

**Comment by hrehfeld** [comment]
Thanks!

(Are you sure this is a 3.5 feature? lxml.builder is built heavily around it: http://lxml.de/api/lxml.builder.ElementMaker-class.html )

**Comment by PierreQuentel** [comment]
This is what I get with Python 3.4 : 
```
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:44:40) [MSC v.1600 64 bit (AM
D64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> def test(*args):
...  print(args)
...
>>> a01 = [0, 1]
>>> test(*a01, 2, 3)
  File "<stdin>", line 1
SyntaxError: only named arguments may follow *expression
>>>
```
