### ISSUE TITLE
Scoping oddity: "for k in range(k)" leads to skipping the loop

### ISSUE THREAD

**Issue by vpavlenko** [brython-dev/brython#545]
Dear Brython developers,

I've found another issue while testing solutions on https://snakify.org/. Please, have a look:

![2017-01-09_22-22-30](https://cloud.githubusercontent.com/assets/1491908/21779989/f6a486be-d6ba-11e6-9001-3b41293cf310.png)

```
print('BEGIN')
k = 3
for k in range(k):
    print(k)

print('END')
```

Could you have a look and see if there's a quick fix you could make? Alternatively, we could look into it ourselves, if you could point us to possible bug causer.

Thanks,
Vitaly

**Comment by PierreQuentel** [comment]
Merci Vitali !
