### ISSUE TITLE
Operators **=, //= and so on don't work on float variables

### ISSUE THREAD

**Issue by vpavlenko** [brython-dev/brython#549]
Dear @PierreQuentel ,

Thanks for all the fixes you rapidly made so far! While using Brython in our course, we encountered some more bugs. Here's one of them:

![2017-01-13_18-34-11](https://cloud.githubusercontent.com/assets/1491908/21935590/26163260-d9bf-11e6-80a7-645dafc0f1a0.png)

```
a = 5.0
a **= 2
print(a)
```

Sorry for possibly stupid question aside. I assume some repos like PyPy, Jython or Cython could have more tests to cover all weird corner cases we're hitting. Did you try to find such tests and add it to Brython repo?

Thanks,
Vitaly

**Comment by PierreQuentel** [comment]
Brython includes an integrated test suite which is mostly made out of bug reports.

There is also the integrated CPython test suite : if you load _/tests/unittests_ in the browser, you have a page with a selection of many of these tests (they are located in __Lib/test__). For each test a report is printed with detailed information on tests that don't pass.

I used this a lot at a time to fix bugs on built-in types. I don't know if this bug would have been detected with test_float.py though.
