### ISSUE TITLE
Variable name shadowed in list comprehension scope crashes: [s for s in s]

### ISSUE THREAD

**Issue by vpavlenko** [brython-dev/brython#553]
One more catch from Snakify.org QA department:
```
s = 'abc'
print([s for s in s])
```

![2017-01-17_00-14-57](https://cloud.githubusercontent.com/assets/1491908/21999253/2cfe1a24-dc4a-11e6-813a-44bde53cb39c.png)

**Comment by PierreQuentel** [comment]
Спасибо !

This one is a little more difficult to fix, and it has something in common with issue #499. I hope to fix both soon.
