### ISSUE TITLE
def f(arg=input()) with substituted sys.stdin throws an error

### ISSUE THREAD

**Issue by vpavlenko** [brython-dev/brython#555]
I'm really sorry to show you more and more tricky sources. Somehow our Python learners keep inventing that as a part of their solutions on https://snakify.org:

![2017-01-21_16-26-00](https://cloud.githubusercontent.com/assets/1491908/22174732/751d4b68-dff6-11e6-8a95-bb1dbc0fb61b.png)

```
import io
import sys

sys.stdin = io.StringIO('something that should be printed')

def f(arg=input()):
    print(arg)

f()
```

**Comment by PierreQuentel** [comment]
Congratulations to your learners, they are very creative !

It seems that the fix of issue #554 also fixes this one, can you confirm ?

**Comment by vpavlenko** [comment]
The bug is fixed with the newest brython.js locally, but is present on https://brython.info/tests/editor.html

Is the Editor on brython.info always using the newest brython.js from master branch?

**Comment by PierreQuentel** [comment]
No, brython.info is always running the latest stable version.

**Comment by PierreQuentel** [comment]
but I have recently added an [online editor page](http://brython.info/tests/latest.html) that runs the latest, unstable development version

**Comment by vpavlenko** [comment]
Thanks for adding the latest editor. I confirm, the bug is gone now.

**Comment by PierreQuentel** [comment]
не за что !
