### ISSUE TITLE
A set isn't properly cloned by "a = set(b)" statement - sharing the storage with origin?

### ISSUE THREAD

**Issue by vpavlenko** [brython-dev/brython#558]
Hi @PierreQuentel !

Hope you're doing well. Our students continue chasing corner cases :)

![2017-02-06_13-26-43](https://cloud.githubusercontent.com/assets/1491908/22643587/389e870c-ec70-11e6-8342-7de774d5f958.png)

**Comment by PierreQuentel** [comment]
Thanks ! This one was easy, I'm sure you could have fixed it yourself ;-)
