### ISSUE TITLE
Classmethods called from instances of derived classes are passed wrong class parameter.

### ISSUE THREAD

**Issue by jonathanverner** [brython-dev/brython#560]
The following code fails the second assert in Brython (but passes in CPython).
```python
class Base:
    @classmethod
    def test(cls):
        return cls
        
class Derived(Base):
    def __init__(self):
        pass
        
assert Derived.test() == Derived
d = Derived()
assert d.test() == Derived
```
The reason is that `d.test()` calls `Base.test` with the class `Base` as first parameter instead
of the correct `Derived` class.

**Comment by PierreQuentel** [comment]
This was fixed by commit 4fd73dccea95dd6c6d694f4909eaf2582a038a12
