### ISSUE TITLE
Booleans don't work as zero and one: False + True should be 1

### ISSUE THREAD

**Issue by vpavlenko** [brython-dev/brython#563]
@PierreQuentel Thanks for all the great work you've been doing! I'm not sure if Python-on-frontend will take over the world, but it's cool to give peace a chance :)

Could you please have a look at the other bug I've found recently?

![2017-02-11_20-46-09](https://cloud.githubusercontent.com/assets/1491908/22856058/62564ee8-f09b-11e6-8831-f45edaa6ff42.png)

**Comment by PierreQuentel** [comment]
Thanks for the report.

I'm convinced that Python will be present in the browser some day, and if it is, it will have to be 

1) a real Python implementation, not "Python-like" : it's too hard to explain and to remember the differences between a Python-like language and real Python
2) as easy to use as Javascript, inside <script> tags, without precompilation with a Python program

I'm not sure Brython will be the definitive solution, but until someone comes with a better Python implementation, I hope it is at least a good tool to experiment, define an API for DOM interaction and extend the community of "Python in the browser" developers.
