### ISSUE TITLE
Wrong result type for operation mixing floats and ints

### ISSUE THREAD

**Issue by pchampin** [brython-dev/brython#564]
In the Brython console, I get:
```python
  >>> x=2
  >>> .5*x
  1
  >>> type(_)
  <class 'int'>
```
while in any other Python interpreter that I tried, I get:
```python
  >>> x=2
  >>> .5*x
  1.0
  >>> type(_)
  <type 'float'>
```

Note that 
* if I replace ``x=2`` with ``x=3``, I correctly get 1.5, of type float (so the bug is only type-related; the results seem to always be mathematically correct);
* if I replace ``.5*x`` with ``.5*2``, I correctly get 1.0, of type float (so the bug seems to be related to the use of a *variable*).

**Comment by PierreQuentel** [comment]
Merci Pierre-Antoine !

Je ne dois pas être loin de battre mon record de vitesse de correction ;-)
