### ISSUE TITLE
how to import my python moudule?

### ISSUE THREAD

**Issue by saintthor** [brython-dev/brython#565]
brython.js:6924 XMLHttpRequest cannot load file:///home/zzz//empty/Brython-3.3.1/Lib/site-packages/terminal.py?v=1487406086874. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.

i want to import a python module named terminal.py. it is in the same dir with demo.html. but always get errors as above.
in demo.html, to import os or sys are ok.
how to fix it?

**Comment by PierreQuentel** [comment]
Brython uses Ajax calls to import modules (except those of the standard library like os or sys, which are already loaded in brython_stdlib.js). As the error message says, Chrome doesn't support Ajax calls when the script is opened as a file ; you must start an HTTP server and load the script in HTTP.

The most simple is to run `python -m http.server 8000` to start a server on port 8000, then load your HTML page in the browser by _http://localhost:8000/page.html_

**Comment by jonathanverner** [comment]
See also https://www.thepolyglotdeveloper.com/2014/08/bypass-cors-errors-testing-apis-locally/ for other potential options. Also note that the above command requires your python to be python 3. If your python is still in the 2 series, change it to `python -m SimpleHTTPServer`.

**Comment by saintthor** [comment]
thanks. it works.

another problem, it seems i can not use reduce func?

**Comment by saintthor** [comment]
i can import my python module now.
but, it cost 4 seconds every time on loading the web page. is there anyway to load it faster?

**Comment by PierreQuentel** [comment]
Unfortunately we haven't found a way to make imports faster, although much thought has been put into it (see for instance the long discussion in issue #491)

**Comment by PierreQuentel** [comment]
By the way, the number of lines in the logs is confusing : with debug mode set to 2 or above, when a module is imported, there is a message "module XXX translated in N ms", but if there are list comprehensions, lambdas, generator expressions etc. in the module, the Python to Javascript engine generates the same message, with the time taken to translate these code blocks. 

I have just modified the log to print only one message for the module.

**Comment by saintthor** [comment]
list comprehensions, lambdas, generator expressions 

yes, i used all of these.

i found the biggest trouble is functiontools. i do no longer use the reduce func then reduce the load time to about 200 ms.

thank you.
