### ISSUE TITLE
http://brython.info/gallery/ajax.html Synchronous XMLHttpRequest deprecated

### ISSUE THREAD

**Issue by bmsleight** [brython-dev/brython#566]
In both firefox [51.0.1 (64-bit)] and Chrome [Version 55.0.2883.87 B] 

Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/  brython.js:6905:43

brython.js:formatted:13400Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

Hence example no longer working.

**Comment by PierreQuentel** [comment]
Sorry for the late reply. This is due to the way `import` works in Brython : it uses synchronous Ajax calls. But this is just a warning by the browser, and it doesn't break any code. If your example doesn't work, can you explain in more details what this example is, and the error message you get ?

**Comment by bmsleight** [comment]
Thanks for the reply. Breaks the code for me [51.0.1+build2-0ubuntu0.16.04.1]

See these screencasts...
http://imgur.com/a/bUf5e
http://imgur.com/a/cp0Ic

When visiting http://brython.info/gallery/ajax.html previously the (empty) get updated.

**Comment by PierreQuentel** [comment]
There was a bug in the Ajax demo, but not related to the warning, which is still there, and will be there until the browser vendors remove it.

**Comment by bmsleight** [comment]
Thanks for the bug fix and for Brython. 
BMS
