### ISSUE TITLE
math.fsum return wrong precision 

### ISSUE THREAD

**Issue by ehere** [brython-dev/brython#567]
From python3 document
https://docs.python.org/3/library/math.html#math.fsum

```python
import math 
print(math.fsum([.1, .1, .1, .1, .1, .1, .1, .1, .1, .1]))
```

It should print 1.0 but it print 0.9999999999999999.

**Comment by PierreQuentel** [comment]
Thanks for the report.
I fixed the bug by translating in Javascript the function `msum()` of an [Active State Cookbook recipe](https://code.activestate.com/recipes/393090/).
