### ISSUE TITLE
Gallery Sample 'Turtle' on Brython Website Doesn't work

### ISSUE THREAD

**Issue by jeffreybian** [brython-dev/brython#568]
After the turtle sample page is opened, it kept prompting "Processing, please wait" in the middle of the page.

Env Info: 
- Brython 3.3.1 on Netscape 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

**Comment by jonathanverner** [comment]
This should be fixed in master (commit cb296df97a2f3daaa7e7b23d1a6ae05886e085b3).

**Comment by PierreQuentel** [comment]
Thanks for the report, I have uploaded the correct version of the `turtle` module.
