### ISSUE TITLE
Dict implementation is incorrect and slow

### ISSUE THREAD

**Issue by joaoventura** [brython-dev/brython#57]
Dict implementation is not compliant with CPython on some cases, for instance:

Brython
>a = {[1,2]: 2}
>print(a[[1,2]])
>> 2

CPython
>a = {[1,2]: 2}
>> TypeError: unhashable type: 'list'

>print(a[[1,2]])
>> TypeError: string indices must be integers

Also, the dict implementation is quite slow by being based on JS Arrays. This jsperf (http://jsperf.com/dict-vs-array-lookup) compares array lookup vs direct dict lookups and dict lookups is almost 2000% faster for a case of a key not in the beginning of the keys array. This indicates that an approach based on JS dicts would take advantage of proportional increases in speed.

I am willing to implement something like this, but would need to discuss it because I'm not fully aware of some of Brython's internal mechanisms.

**Comment by earney** [comment]
I'm going to close this now, since the new dict implementation has been put into place.   Please reopen this issue (or create a new one), if issues are discovered.
