### ISSUE TITLE
Can we have a stable URL for cdn.rawgit.com, please?

### ISSUE THREAD

**Issue by stroobandt** [brython-dev/brython#570]
I just switched over to the latest stable zero install on `cdn.rawgit.com`, which works great.
It convinced me to write even more online calculators in Brython.

However, to keep maintenance work on the different [Brython calculators of my website](http://hamwaves.com/calculators/en/index.html) low, it would be wonderful to have a `stable` URL for the latest stable release, like `https://cdn.rawgit.com/brython-dev/brython/stable/www/src/brython.js`

PS: The current development version does have an invariable `master` URL: `https://cdn.rawgit.com/brython-dev/brython/master/www/src/brython.js`

> Zero install !
> 
> The most simple way to get started, without anything to install, is to use the distribution available online through rawgit. You can either choose the latest stable release :
> 
> <script type="text/javascript"
>     src="https://cdn.rawgit.com/brython-dev/brython/3.3.1/www/src/brython.js">
> </script>

**Comment by PierreQuentel** [comment]
Hi Serge,

I haven't found this feature in rawgit documentation. You can use the brython.info site (_brython.info/src/brython.js_ and _/src/brython_stdlib.js_) : it's not a CDN but since the files seldom change, you'll get a 304 reply most of the time.

cdnjs also references brython but not yet with the new distribution mode (__brython.js__ and __brython_stdlib.js__), hopefully they wil soon.

**Comment by stroobandt** [comment]
According to the `rawgit.com` documentation, [branches are not allowed, only tags are allowed](https://github.com/rgrove/rawgit/blob/master/FAQ.md#how-long-does-the-cdn-cache-files-how-can-i-make-it-refresh-my-file).

So, the solution might be as simple as creating an extra git tag called `stable`.

When a new stable version is released, simply [delete this remote tag and then use it again](https://wptheming.com/2011/04/add-remove-github-tags/) to point to the new stable version.

Another, entirely different solution would be to create a redirection with a stable URL on <https://brython.info/> towards the CDN.
