### ISSUE TITLE
Problem with loading separate file with brython.js

### ISSUE THREAD

**Issue by hube12** [brython-dev/brython#571]
Hello,

I have some error each time i want to use a separate python file in my code. It does the same for the example of kanban (not changed anything) in the gallery.
**Here the error message on chrome:** 

_Uncaught Error: cannot load script __main__ at file:///C:/Users/""/Desktop/brython-3.3.1/www/gallery/kanban.py: error 0_

**And on Firefox** 

 Erreur d’analyse XML : mal formé
Emplacement : file:///C:/Users/""/Desktop/brython-3.3.1/www/gallery/kanban.py
Numéro de ligne 1, Colonne 2 :  kanban.py:1:2

L’utilisation d’XMLHttpRequest de façon synchrone sur le fil d’exécution principal est obsolète à cause de son impact négatif sur la navigation de l’utilisateur final. Consulter http://xhr.spec.whatwg.org/ pour plus d’informations.  brython.js:6905:43

Error:   brython.js%20line%206233%20%3E%20eval:97:409
	_b_.RuntimeError file:///C:/Users/""/Desktop/brython-3.3.1/www/src/brython.js%20line%206233%20%3E%20eval:97:409
	run_script file:///C:/Users/""/Desktop/brython-3.3.1/www/src/brython.js:4118:6
	callback file:///C:/Users/""/Desktop/brython-3.3.1/www/src/brython.js:4088:1

Error:   brython.js%20line%206233%20%3E%20eval:49:373
	_b_.ImportError file:///C:/Users/""/Desktop/brython-3.3.1/www/src/brython.js%20line%206233%20%3E%20eval:49:373
	$importer/timer< file:///C:/Users/""/Desktop/brython-3.3.1/www/src/brython.js:6901:7

(the file is still on the right directory and i can read it in the browser by clicking it, but i dont understand the load script ___main___ error)

**Comment by PierreQuentel** [comment]
Hi,

The message suggests that you are reading the file with your browser. Try starting a web server (eg __server.py__ provided in the Brython distribution) and load the page by entering the url in the browsers address bar.

The issue is that some browsers don't support Ajax calls when the protocol is `file:///`, and loading external scripts with `<script type="text/python" src="script.py">` requires an Ajax call.

Hope this helps !

**Comment by hube12** [comment]
Hi,
Thanks for the reply, it worked but it's still slow even after selecting only the module i wanted to import.
So i have decided to go back to put all in the html file and import the complete stdlib.
Have a nice day

PS: Peut-être que vous devriez le rajouter a la doc (http://www.brython.info/static_doc/fr/intro.html)
