### ISSUE TITLE
list.sort is not stable in Brython

### ISSUE THREAD

**Issue by andy31lewis** [brython-dev/brython#572]
Hi

In Python, sorting is guaranteed to be stable (since Python 2.2). So
```python
words = ["Bed", "Axe", "Cat", "Court", "Axle", "Beer"]
words.sort()
words.sort(key=len, reverse=True)
print(words)
```
first sorts alphabetically, and then by descending length, but the second sort keeps the alphabetical order for words of the same length, resulting in:
```
['Court', 'Axle', 'Beer', 'Axe', 'Bed', 'Cat']
```

But Brython gives:
```
['Court', 'Beer', 'Axle', 'Axe', 'Cat', 'Bed']
```
Not a big issue to me, but I thought I would mention it, as it could matter to some people.

Andy

**Comment by mscuthbert** [comment]
I'm guessing that this can be closed now? :-)

**Comment by PierreQuentel** [comment]
Yes, we forgot to close the issue when Jonathan fixed it.
