### ISSUE TITLE
"viewBox" keyword argument to html.SVG() appears casefolded in the DOM

### ISSUE THREAD

**Issue by tjnaughton** [brython-dev/brython#579]
Hi,
Brython is an amazing project. Congratulations everyone.

A call to
`html.SVG(viewBox='0 0 200 200')`
results in this DOM element with an erroneously casefolded "viewbox" attribute
`<svg viewbox="0 0 200 200"></svg>`
which does not function correctly.

The html file attached illustrates the problem. It can be verified that if the DOM is edited in the browser and the correct case "viewBox" entered, the svg object functions correctly. Thanks!
[viewBox_example.html.txt](https://github.com/brython-dev/brython/files/917358/viewBox_example.html.txt)

**Comment by PierreQuentel** [comment]
Thanks for the report, I wasn't aware that these attributes were case-sensitive.

**Comment by tjnaughton** [comment]
Thanks for the quick and positive response!
