### ISSUE TITLE
next() does not seem to work in a Brython  generator object

### ISSUE THREAD

**Issue by theodox** [brython-dev/brython#583]
in Brython:
 
    >>> fred = (i for i in [1,2,3,4])  
    >>> fred.next()
    [1, 0]
    >>> fred.next()
    [1, 0]
    >>> 

In vanilla python:

    >>> fred = (i for i in [1,2,3,4])
    >>> fred.next() 
    1   
    >>> fred.next()
    2
    >>> fred.next()
    3

**Comment by benjaminrigaud** [comment]
Brython is based on Python3 : generators don't have next method.

The Brython code should fail with this error: 
`AttributeError: 'generator' object has no attribute 'next'`

The built-in `next` is working as expected.

**Comment by jsbueno** [comment]
Indeed, the Python 3 form, `__next__` works: 
```
Brython 3.3.1 on Netscape 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36
>>> a = (i for i in (7,8,9))
>>> a.__next__()
7
>>> a.__next__()
8
>>> a.__next__()
9
```

**Comment by theodox** [comment]
doh, my bad.
