### ISSUE TITLE
installing python 3rd library.

### ISSUE THREAD

**Issue by faststare** [brython-dev/brython#585]
let's say, I want to use native pandas library with brython. how I install the pandas library with brython.js? and use in my script tag.

**Comment by kikocorreoso** [comment]
Brython can work with pure python packages. Pandas (and numpy, matplotlib, scipy,...) contains a lot of Cython code (C, C++) that should be ported to Python and/or javascript to make it work.

OTOH, if you have a lot of data to process maybe it is a better idea to do it server side and then only show on the client side the results (a table, a plot,...) à la Jupyter.

**Comment by faststare** [comment]
I'm using electron framework but I can't access the electron api (example I have script tag that require to electron when I import the electron from window. no api register when I printing it/writing to p tag).

**Comment by kikocorreoso** [comment]
I'm sorry but I'm not familiar with electron. [nteract](https://github.com/nteract/nteract) is using electron. Maybe you could inspect how they (nteract team) are solving this or you can post some code to show us what you are trying to achieve or you can ask in an electron forum.

**Comment by faststare** [comment]
https://pastebin.com/N6GGQvDF here is my vanilla js. can you give me some idea how I achieve with brython?

**Comment by faststare** [comment]
nevermind, I already re-clone it with brython.

**Comment by kikocorreoso** [comment]
Could you openly share what you did in order others can learn?

Thanks.
