### ISSUE TITLE
Redirecting stderr continues printing to console

### ISSUE THREAD

**Issue by finaiized** [brython-dev/brython#586]
I've successfully redirected stdout by using the following:

```
import sys 
from browser import document

def write(data):
    outputEl = document["output"]
    outputEl.innerText = data
sys.stdout.write = write
```

However, when I attempt to redirect stderr, by changing the last line to `sys.stderr.write = write`, it continues printing to console.

**Comment by kikocorreoso** [comment]
It is working for me:

```python
import sys 
from browser import document

def write(data):
    outputEl = document["output"]
    outputEl.innerText = data
sys.stderr.write = write
  
a() # this doesn't exist and the error is printed in the element with id="output"
```
Please, could you post the code you are using and what is the result you are expecting?
Thanks.

**Comment by finaiized** [comment]
Ah, yes. It has to do with how I'm using Brython. I'm trying to evaluate Python code from a textarea and running it - see https://jsfiddle.net/09qvexu9/1/ for an example. If I type `a()` in the textarea and click the button, the error only shows up in the console, but if I switch `stderr` to `stdout` and type `print("OK")`, "OK" shows up in the output div as expected. Not sure if this is a bug or intended behaviour.

**Comment by kikocorreoso** [comment]
Have a look [here](https://jsfiddle.net/1g8Lbxza/) for a working example.

**Comment by finaiized** [comment]
Thanks!
