### ISSUE TITLE
Running Brython exec in WebWorker

### ISSUE THREAD

**Issue by finaiized** [brython-dev/brython#589]
I was wondering if it is possible to run `exec` in a WebWorker so it doesn't lock up the UI thread. Right now, if I wanted to dynamically translate some Python code that contained a tight loop, the browser would lock up until the loop was done. Instead, I was thinking that were the execution to run on a background process, periodic `postMessage`s could update the UI correspondingly. I noticed there was a test at https://github.com/brython-dev/brython/blob/master/www/tests/web_worker_tests.html but it is broken because it still attempts to access `document` from the Web Worker.

**Comment by jonathanverner** [comment]
I started working on this (in the [webworkers](https://github.com/jonathanverner/brython/tree/webworkers) branch in my [fork](https://github.com/jonathanverner/brython)). It seems that it won't be as hard as I expected, but right now I don't have much time, so I am not sure when I submit a pull request :-)

**Comment by PierreQuentel** [comment]
@jonathanverner 
Do you think we can close this issue now that your webworker module has been added ?
