### ISSUE TITLE
Bug of input() ?

### ISSUE THREAD

**Issue by victorfence** [brython-dev/brython#590]
Hello, I found the input() function is implemented by wrapping the prompt function of browser

When I exec sush python code:
v = input("message")
And, when I click cencel button, an error raised:
Internal Javascript error: TypeError: <TypeError: $args[(nb_pos - 1)] is null>
This happens in both version 3.3.1 and 3.3.2.

After a little hack
I think this line of function input should be changed:
if (stdin.__original__) { return prompt(src); }
to
if (stdin.__original__) {return $B.JSObject(prompt(src, ''))}

Please have a confirm, thank you.

**Comment by PierreQuentel** [comment]
Thanks for the report, you were almost right for the solution : it should have been

```javascript
if (stdin.__original__) { return prompt(src) || '' }
```
