### ISSUE TITLE
Performance Question

### ISSUE THREAD

**Issue by imnvr** [brython-dev/brython#591]
Hello, I'd like to ask what is the performance like currently and if it's likely to improve soon.

**Comment by PierreQuentel** [comment]
It's hard to give a general answer, like for "what is the performance of Python currently ?" Can you be more specific ? what do you find currently too slow ?

For a start you can take a look at [this post](https://groups.google.com/forum/?fromgroups#!topic/brython/vmlvPqPn7Yw) in the Google group.

**Comment by imnvr** [comment]
I am quoting some other user: "Ok, there is the performance issue, but things are getting better ; the release I'm currently working on (3.2.7) runs the pystone test 2.5 faster than 3.2.6. It's still 15 times slower than CPython, but in the early days it was thousands of times slower."

When it will get at least as fast as CPython ?

**Comment by PierreQuentel** [comment]
I honestly don't know if it will. But I'm pretty sure it's fast enough for what Brython is made for, web client programming.
