### ISSUE TITLE
Pow Error

### ISSUE THREAD

**Issue by barsiman** [brython-dev/brython#592]
Hi, I'm trying to run this line in brython : pow(97, 1351,723) and the resault is "nan".
I realized that the problem is with the pow(97,1351) because the resault is too big (when I run it I get "inf").
When i run this line pow(97, 1351,723)  in python everything is working fine. It is crucial to me that this line will work so is there a way to make this line work in brython ?

**Comment by PierreQuentel** [comment]
Thanks for the report. I have improved the algorithm to compute pow with a 3rd argument.
