### ISSUE TITLE
global property name for js object.

### ISSUE THREAD

**Issue by bit-garden** [brython-dev/brython#594]
it seems a syntax error is thrown when you try to access a property of an instance of a js object called global. How would one work around that?

```print(some_js_object.global)```

**Comment by PierreQuentel** [comment]
Yes, `global` is a keyword in Python and can't be used as a variable or attribute name, like `class`, `from`, etc.
But you can use the syntax

```python
print(some_js_object["global"])
```

**Comment by bit-garden** [comment]
Ah, I didn't know accessors were in place like that. Thanks
