### ISSUE TITLE
file write function

### ISSUE THREAD

**Issue by faststare** [brython-dev/brython#595]
I'm testing a open function/class but It's does not include writing a object to a file.
any example for this feature?

**Comment by PierreQuentel** [comment]
Brython code is converted into Javascript, and for security reasons Javascript runs scripts in a sandboxed environment that forbids writing to the file system. If you want to store data you can use cookies, local storage or IndexedDB.

**Comment by faststare** [comment]
If js runs in a browser, it is. But its different story when it runs on node but js callback is not newbie friendly. Thats why I use, It brython as if full implementation of python. But it seems that I need to more on. Anyway, Its a great scripts.
