### ISSUE TITLE
bool() should error with too many arguments

### ISSUE THREAD

**Issue by edwdryer** [brython-dev/brython#597]
For example:
```python
print(bool(42,42))
```
should evaluate to :
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> TypeError: bool() takes at most 1 argument (2 given)

but instead evaluates to:
> True

**Comment by PierreQuentel** [comment]
Thanks for reporting this. It is also the case with most of the builtin functions in py_builtin_function.js, I will have to fix them.

**Comment by edwdryer** [comment]
No problem! Yeah I noticed a bunch of cases like this but only reported this one. 

Also just a heads up I'll be submitting roughly 10 (unrelated) issues in the next couple of days. Thanks for getting to these ones so quickly :)
