### ISSUE TITLE
Templating in Brython?

### ISSUE THREAD

**Issue by pascallando** [brython-dev/brython#599]
Hello guys, and congratulations for this great work: it's a real pleasure to finally work with a comfortable language in the browser…

My question is about templating: in almost all apps I build client side, I need to format templates (walk over dicts, check conditions, replace values…). 

Here is an example of such a template I used to code with **Riot.js**:

```javascript
<ul>
    <li each={ tag in tags }>{ tag.text }</li>
</ul>
```

On server side Python, I usually use **Jinja** to achieve this.

How do you proceed in Brython code? Python's string `format()` is a very limited solution (no loops, no conditions…). Importing Jinja in Brython program seems touchy…

Thank you very much in advance!

**Comment by jonathanverner** [comment]
I have started working on a library to do precisely this (https://github.com/jonathanverner/circular) but then real life intervened... You can try looking at it, but it will definitely need some work to make it generally usable.

**Comment by the1337guy** [comment]
If you are used to working with Jinja(2), I guess you would love Nunjucks, try it out, it's made by Mozilla (yay Python supporters!)...

**Comment by PierreQuentel** [comment]
It's a good idea !

I have started a templating engine called [patrom](https://github.com/PierreQuentel/patrom) (yet another Breton word ;-).

I wanted to try something that used plain HTML syntax, not [[double brackets]] or {{double curly braces}} like most templating engines, and no endblock markers.

I have started porting it to Brython, I will probably push the result one of these days. If you have any feedback on this project you can post it here or on its issue tracker.

**Comment by benjaminrigaud** [comment]
I started evaluating Jinja2 on Brython: few issues have been opened (and resolved) in the past weeks. I'll continue my work as soon as possible.

A fork will be required: some features (like bytecode cache) will not be compatible with Brython.

**Comment by PierreQuentel** [comment]
After many trials and errors , I have a working version of the browser.template module (see the [documentation](https://github.com/brython-dev/brython/blob/40301e54a5267fbd5572c3e9314a65125017d74e/www/doc/en/template.md)). It is vaguely inspired by vue.js.

I have also added a version of the "sort table" demo using it, is is much more concise than the version with __browser.html__ to generate HTML code.

Feedback is very much welcome. I will also post a message on the Google group.

**Comment by pascallando** [comment]
Hum, nice piece of code Pierre. Will give it a try and provide you with some feedback. Thanks again for your great work!

**Comment by pkemarco** [comment]
Thanks, okay.

2017-12-25 18:03 GMT+01:00 Pascal Lando <notifications@github.com>:

**Comment by PierreQuentel** [comment]
With the `template` module and [Anpylar](https://www.anpylar.com/), I think we can close the issue.
