### ISSUE TITLE
print sep,end issues

### ISSUE THREAD

**Issue by edwdryer** [brython-dev/brython#606]
```python
print('\0','','\0',sep='+') #displays escaped characters
print('a\n','b',sep=None) #Adds None instead of empty
print('a\n','b',end=None) #Adds None instead of empty
```

**Comment by PierreQuentel** [comment]
Many thanks for this report and the other ones, it's very helpful and I have learnt a few things about Python (the reverse order for comparison with subclasses...)

The commit referenced above improves the result of the test cases, but there is still an issue with escaped characters such as `\1`, which Javascript prints as an empty square, not as the symbol ☺ like Python.
