### ISSUE TITLE
addClass / removeClass ?

### ISSUE THREAD

**Issue by filantus** [brython-dev/brython#608]
Hi! Thank you for truly great work!

I looking for addClass and removeClass methods, like in jQuery and found this page - https://github.com/brython-dev/brython/blob/master/www/doc/en/pydom/addClass.md
but this is not work:
`Traceback (most recent call last):
  module __main__ line 1
    from browser.pydom import get
ImportError: cannot import name 'get'`

Can you please suggest how use it correct or any alternatives?

**Comment by PierreQuentel** [comment]
This page is related to a module that is not part of the distribution, I will remove it.

To add of remove classes to or from an element, you should use the standard DOM methods attached to the attribute `classList` of DOM elements. You can see examples in the [demo page](http://brython.info/demo.html?lang=en).

**Comment by filantus** [comment]
Wow, great! Thank you very much!
