### ISSUE TITLE
Request: Please provide a brython_turtle.js file to avoid ajax calls.

### ISSUE THREAD

**Issue by MarkusBordihn** [brython-dev/brython#609]
It would be great if you could provide/generate an brython_turtle.js file similar to the brython_stdlib.js file to avoid any ajax calls and possible cross domain issues.

**Comment by davidkwast** [comment]
I think Brython already can do that, but you will have to do by yourself.

Look at Optimization topic at http://www.brython.info/static_doc/en/import.html

> To optimise imports, if Brython was installed by pip, you can generate a file brython_modules.js which only holds the modules used by the application.
>
> For that, open a console window, navigate to the application directory and execute
>
> python -m brython --modules
> 
> Note that this program parses the Brython code in all the scripts, modules and HTML pages of the directory and its sub-directories. The CPython version used must be compliant with this Brython code : for instance if there are f-strings in the Brython code, CPython 3.6+ is required, otherwise you would get syntax errors.
