### ISSUE TITLE
Function annotations order with default arguments

### ISSUE THREAD

**Issue by bit-garden** [brython-dev/brython#610]
According to [PEP-3107](https://www.python.org/dev/peps/pep-3107/) Annotations must come before default argument assignments. 

This behavior isn't checked in Brython 3.3.2. You can have it either way which can cause problems if code is taken from brython and ran on Cpython

CPython:
```
>>> def test(a=5:int)->int:return a
  File "<stdin>", line 1
    def test(a=5:int)->int:return a
                ^
SyntaxError: invalid syntax
>>> def test(a:int=5)->int:return a
...
>>>
```

**Comment by PierreQuentel** [comment]
Thanks for the report, and sorry for the late fix, I had other issues in the meantime.
