### ISSUE TITLE
ImportError: cannot import name 'ElementPath'

### ISSUE THREAD

**Issue by see01995** [brython-dev/brython#612]
Code：

    <script src="D:\test\brython-master\www\src\brython_dist.js"></script>
    <script type="text/python">
             import xml.etree.ElementTree

Report errors：
SyntaxError: Expected '{' for module xml.etree.ElementPath
Error for module xml.etree.ElementTree
Traceback (most recent call last):
ImportError: cannot import name 'ElementPath'

**Comment by PierreQuentel** [comment]
Thanks for the report. The bug was caused by code like

```python
def f():
    for elem in result:
        if condition:
            yield elem
            break
```

**Comment by see01995** [comment]
I sync latest code to run, but it still report error:
SCRIPT16389: 
File: brython_dist.js, Line: 7022, Column: 1
![capture](https://user-images.githubusercontent.com/11477609/27730396-ac17a4d6-5dbb-11e7-9490-37871076599d.PNG)
