### ISSUE TITLE
ImportError: cannot import name 'expatbuilder'

### ISSUE THREAD

**Issue by see01995** [brython-dev/brython#613]
Code：

<script src="D:\test\brython-master\www\src\brython_dist.js"></script>
<script type="text/python">
         import xml.dom.minidom

Report errors：
Error for module xml.parsers.expat
Error for module xml.dom.expatbuilder
Traceback (most recent call last):
ImportError: cannot import name 'expatbuilder'
SCRIPT16389: 
File: brython_dist.js, Line: 4130, Column: 34

**Comment by see01995** [comment]
Code：
1:<script src="D:\test\brython-master\www\src\brython_dist.js"></script> 
2:<script type="text/python"> 
3:             import xml.dom.minidom 
4:             dom = xml.dom.minidom.parse("cd_catalog.xml")

Report errors： 
Error for module xml.parsers.expat 
Error for module xml.dom.expatbuilder 
Traceback (most recent call last): ImportError: cannot import name 'expatbuilder' SCRIPT16389: File: brython_dist.js, Line: 4130, Column: 34

**Comment by PierreQuentel** [comment]
I have worked on this issue and found two bugs in Brython core scripts, but I can't fix the issue : CPython relies on a module __pyexpat__ which is written in C, and I haven't found a pure-Python version. I'm afraid I'll have to put the "won't fix" label on this one.

Fortunately there is a workaround : modern browsers support the class [DOMParser](https://developer.mozilla.org/en-US/docs/Web/API/DOMParser) which parses XML content. You can use it like in the code below : 

```python
from browser import window
parser = window.DOMParser.new()

src = open("cd-catalog.xml").read()
tree = parser.parseFromString(src, "application/xml")

root = tree.firstChild

def show(node, indent=0):
    if hasattr(node, "tagName"):
        print(indent * '  ', node.tagName)
        for child in node.childNodes:
            show(child, indent + 1)
    elif node.text.strip():
        print(indent * '  ', node.text)

show(root)
```
