### ISSUE TITLE
Hidden extra 'length' attribute in namedtuples

### ISSUE THREAD

**Issue by tjnaughton** [brython-dev/brython#614]
Hi,

With Python 3.6.0, consider the following expected behaviour where I define an attribute with the name "length" in a namedtuple:
```
>>> from collections import namedtuple
>>> N = namedtuple('N', 'spam, length, eggs')
>>> n = N(5, 6, 7)
>>> n.length
6
```

However, when I run the same code using the console on www.brython.info (Brython 3.3.2) the behaviour is different:
```
>>> from collections import namedtuple
>>> N = namedtuple('N', 'spam, length, eggs')
>>> n = N(5, 6, 7)
>>> n.length
3
```

which I suggest is a bug because ``n.length`` should return 6 in this instance. This `length` attribute (that takes precedence over my own `length` attribute) seems to be present by default in every Brython namedtuple, as verified by running this code on the console on www.brython.info :
```
>>> M = namedtuple('M', 'a, b, c')
>>> m = M(5, 6, 7)
>>> m.length
3
```

but running these three lines should raise an attribute error (as it would with Python).

This unexpected `length` attribute with Brython namedtuples seems hidden from the the `dir` function:
```
>>> dir(m)
['__add__', '__and__', '__bases__', '__class__', '__contains__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__doc__', '__eq__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__gt__', '__hash__', '__init__', '__initialized__', '__iter__', '__le__', '__len__', '__lshift__', '__lt__', '__mod__', '__module__', '__mul__', '__name__', '__ne__', '__new__', '__or__', '__pow__', '__repr__', '__rshift__', '__setattr__', '__setitem__', '__slots__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__xor__', '_asdict', '_fields', '_make', '_replace', 'a', 'b', 'c', 'clear', 'copy', 'count', 'index']
>>> m.length
3
```

Would it be possible to remove this unexpected `length` attribute from Brython namedtuples, please? Thanks!

**Comment by jsbueno** [comment]
A "lenght" attribut is a javascript"cism"  and certianly has no need to be
there in Brython data structures.

In Python (and tehrefore, the compatbile Brython)  you should just use the
"len" built-in to retrieve the lenght of a container - len(n) - this in
turn should call the object's `__len__` method if there is one.
