### ISSUE TITLE
Unneeded parameters not raising an exception when creating instances of user-defined classes

### ISSUE THREAD

**Issue by tjnaughton** [brython-dev/brython#615]
Hi,

I'd like to report an issue with Brython 3.3.2 on the basis that behaviour that differs from Python without a browser-related reason can be considered a bug. With Brython, in at least one special case, unneeded parameters can be passed when creating instances of user-defined classes.

The expected behaviour with Python is:

```
>>> class MyClass:
...    spam = 'Spam'
...
>>> MyClass(5)
TypeError: object() takes no parameters
```

however, running the same code with Brython reveals different behaviour:

```
>>> class MyClass:
...    spam = 'Spam'
...
>>> MyClass(5)
<__main__.MyClass object>
```

It would be great if Brython could raise a TypeError the same as Python in this special case. Thanks for all of the great work!

**Comment by perkinslr** [comment]
This is a problem during class creation too.  

    class MyClass(spam='foo'):
        pass

During the class creation, `spam` gets put into the kwargs, but the only thing that gets used for is checking for metaclasses.  I'm about to see if I can add __init_subclass__ support, since I use that heavily and it is the only holdup on using brython.  I may be able to fix this issue at the same time, as I think they are similar.

**Comment by perkinslr** [comment]
Looks like this only applies when using the default `__init__` function.  The default `__init__` function is implemented in javascript directly, not translated from python, so it follows javascripts conventions on extra arguments.  If you define your own `__init__` method, it throws the appropriate errors when the wrong number of arguments are given.

A check in py_type.js to make sure no arguments are given when using the builtin `__init__` would fix this (inside `$instance_creator`).

**Comment by PierreQuentel** [comment]
Thanks @tjnaughton for reporting and @perkinslr for ideas on how to fix it.

For the moment Brython is not 3.6 compliant, it's closer to 3.3 or 3.4. If implementing `__init_subclass__` is not too hard I'm not against it but for the moment the fix referenced above raises the same message as Python 3.4 when a keyword argument other than `metaclass` is passed to a class.

**Comment by perkinslr** [comment]
Implementing `__init_subclass__` and the other half of the same PEP looks to be fairly simple.  Basically `type.__new__` gets extended to call `__init_subclass__`, as defined in the parent class, on the new class right after `type.__init__` finishes.  It then iterates over the new class's attributes and checks if they implement the descriptor protocol, if they do, it calls `__set_name__` on the attribute.  

It looks like most of the super useful things from later python versions have been implemented already, but I think I'll open an issue to track what's been implemented and what hasn't.
