### ISSUE TITLE
metaclass missing functionality

### ISSUE THREAD

**Issue by mementum** [brython-dev/brython#617]
Installation done via: `pip install brython` and using local files for testing (as opposed to CDN from `rawgit`)

The following things seem to be missing:

  - Invocation of `__init__`
  - Invocation of `__call__`

During __new__, if the dictionary/namespace is modified, it is not taken into account for the creation of the new class. Use case

  - Base class has an attribute named `attrs` which is a dictionary
  - New subclass has also an entry named `attrs` which is a dictionary
  - During `__new__`, one receives `attrs` in the dct/namespace parameter of `__new__`. It should be possible to get the `attrs` and merge them (via the usual dictionary method `update`), so that the final generated class has the complete `attrs`

There is an alternative way to achieve the above which also doesn't work:

  - `pop` the `attrs` from the dct
  - call `super(x, y).__new__(....` and let the base class create the `attrs`
  - Update the latter with the popped `attrs` from above

 One can even think about using `setattr` to set the final `attrs` in the new class, but it doesn't also work

**Comment by mementum** [comment]
In `py_type.js`

```
    // Create the class dictionary
    var class_dict = {
        __name__ : class_name.replace('$$',''),
        __bases__ : bases,
        __dict__ : cl_dict
    }

    // set class attributes for faster lookups
    var items = $B.$dict_items(cl_dict);
    for(var i=0;i<items.length;i++){
        class_dict[items[i][0]] = items[i][1]
    }
```

This is done before invoking the `factore`, which is done with `cl_dict`. The factory is correctly identified as the `__new__` from the metaclass, later

```
    // Get method __new__ of metaclass
    var meta_new = $B.$type.__getattribute__(metaclass.$dict,'__new__')
    
    // Create the factory function of the class
    if(meta_new.__func__===$B.$type.__new__){
        var factory = _b_.type.$dict.__new__(_b_.type, class_name, bases, cl_dict)
    }else{
        var factory = meta_new(metaclass, class_name, bases, cl_dict)
    }
```

But `__new__` has no way to change the fact that the items have already been set (it doesn't even have access to `class_dict`. This renders the actions in `__new__` ineffective, because modifying the dictionary which goes up to `type.__new__` has no effect: the items have already been set.

**Comment by mementum** [comment]
Commenting this out in `py_type.js` does the trick

```
    // set class attributes for faster lookups
    var items = $B.$dict_items(cl_dict);
    for(var i=0;i<items.length;i++){
        class_dict[items[i][0]] = items[i][1]
    }
```

Because any well behaved metaclass defining `__new__` has to end up calling `type.__new__`, which already contains code to set the class attributes for faster lookups

**Comment by mementum** [comment]
With regards to `__init__` in the metaclass.

  - If defined, this should be invoked after `var factory = meta_new(..)` to give it a chance to init the class.
  - Actually the fixing of attributes in the class (for compatibility with CPython) has to happen after `__init__` has been called

With regards to `__call__` in the metaaclass the following code is in place

```
$B.$type.__getattribute__=function(klass, attr){

    switch(attr) {
      case '__call__':
        return $instance_creator(klass)
```

But `instance_creator` goes directly to fetch the `__new__` and `__init__` for instantiation (those two not to be confused with the methods of the same name in the metaclass)

This prevents overriding the standard `__call__` in the metaclass. One should consider having a default `type.__call__` which if not overridden will simply call `__new__` and `__init__`. But the user should be given a chance to override `__call__`

**Comment by PierreQuentel** [comment]
Many thanks for reporting this, and even more for fixing the bug :-)

There are a few side effects (with \_\_slots\_\_ and abstract methods) that I will fix shortly.

**Comment by mementum** [comment]
Great project and reporting a problem without devoting a couple of minutes (even not speaking native Javascript) to see why it in't working is the least.

**Comment by PierreQuentel** [comment]
Do you think we can close this issue ?

**Comment by mementum** [comment]
Just noticed that this commit: aba3bc1d111f4c057d169fa2651809f611b1b1ca references the PR #618 from above.

Let me summarize:

  - `metaclass.__new__` is for sure a lot more like python and as such the issue can be for sure closed

In any case I will look how to best add support for:

  - `metaclass.__init__`
  - `metaclass.__call__`

The latter being the most important of the two, because it allows full control of instantiation (a typical use case is instance manipulation after the instance is finished with `__init__`,
