### ISSUE TITLE
browser.html - Creation of any tag and text tags

### ISSUE THREAD

**Issue by mementum** [brython-dev/brython#624]
The code in `builtin_modules.js` generates a set of wrappend DOM Objects for the *HTML 4.x* and *HTML 5* tags. Unluckily, the code for it is wrapped in an anonymous function, which forbids end users from creating tags which are also wrapped in a python class.

Although creating a tag is possible with `document.createElement`, the following is proposed:

  - Decouple the code from the anonymous function
  - Pack it into  `_make_tag` (or `_maketag`) inside the `browser.html` module
  - Create a branch in the `SVG` vs regular element, to also allow the creation of *text* elements (akin to `document.createTextNode`) with a proposed name of `_TEXT`

The use of underscore `_` before `maketag` and `TEXT` is to avoid a collision with actual tags defined by the user (which will be also stored in the `browser.html` module for consistency)

**Comment by mementum** [comment]
Added (not willingly ... git magic) to PR #620 the aforementioned functionality

**Comment by mementum** [comment]
Moved to independent Pull Reuest #633

**Comment by PierreQuentel** [comment]
If I understand correctly you would like to add custom HTML tags, besides those that are defined in the HTML standard. Can you explain what would be the use case for that ?

For text elements you don't need a specific tag, you can just use native types (strings, numbers) and insert them in the document with code like

```python
element <= "my text here"

line = "My" + html.I("test") + "here"
```

**Comment by mementum** [comment]
**Custom Tags**

In HTML5 you can have custom tags. The standard tags are already seen as Python objects.

A custom tag should be (from the end user perspective) functionally equivalent. That can be achieved by exposing the functionality that creates the standard "tags" and allowing end users to access the same functionality via `_maketag`

The only caveat here:

  - Custom tags must feature a `-` which is not a valid character for Python identifiers

This could be *circumvented* by doing something like:

  - creating an additional module for example: `browser.tags` or `browser.html.tags` which would hold the additional tags

This module would expose 2 things:

  - The `_maketag` function to create custom tags
  - A `[]` (`__getitem__`) interface to fetch the actual custom tags. One can then do

    ```
    # during initialization
    mycustomtag = browser.tags._maketag('my-custom-tag')
     ...
    # elsewhere in the code
    mycustomtag = browser.tags['my-custom-tag']
    ```
One could even consider that access to the `[]` operator would directly create the custom tag if not existing.

**Comment by mementum** [comment]
**Text Tag**

Of course you can already insert text directly, but if one has an object, one can later reference it. Of course this could also fall under the category: *custom tag* for later manipulation, which would actually remove the need a custom tag.

**Comment by PierreQuentel** [comment]
If we want to introduce custom elements, it takes more than creating a class with the name of a custom tag ; there should also be a way to define the elements interface, as described in this [blog post](https://developers.google.com/web/fundamentals/getting-started/primers/customelements). I would be ok with it, but it requires writing the equivalent of

```javascript
class AppDrawer extends HTMLElement {
    // custom element API definition here
}
```
Are you ok to work on it ?

**Comment by PierreQuentel** [comment]
__TextNode__
Sorry if this sounds dumb, but why would you want to keep a reference to a text node ?

**Comment by mementum** [comment]
> TextNode
> Sorry if this sounds dumb, but why would you want to keep a reference to a text node ?

If one has an element with several children and also *text*, then the `text` attribute returns the combined *text* of the children plus the actual *text*

A templating engine addressing `text` would ideally treat the children and the actual *text* in a separate ways. This is possible if *text* has been added as a **TextNode** (or something similar, see next approach)

An alternative approach is to have a *custom element*, because the browser will ignore it, but the templating engine could do something with it.

**Comment by mementum** [comment]
> If we want to introduce custom elements, it takes more than creating a class with the name of a custom tag ; there should also be a way to define the elements interface, as described in this blog post. I would be ok with it, but it requires writing the equivalent of

> ```
> class AppDrawer extends HTMLElement {
>    // custom element API definition here
> }
> Are you ok to work on it ?

Probably I miss the actual point, but the idea behind something like `_maketag` in the pull-request already solves the problem (like I say, probably I am misunderstanding your goal and the blog post).

Example:

```
mynewtag_proto = browser.html._maketag('my_super_tag' )

class mynewtag(mynewtag_proto):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        print('do something')
```

Actually for multiple tags the approach can be generalized with a *MixIn*

```
mynewtag_proto = browser.html._maketag('my_super_tag' )

class MixIn::
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        print('do something')

mynewtag = type('mynewtag', (MixIn, mynewtag_proto), {})
```

The actual interface is user defined one and can be fully implemented in a general manner with a MixIn and later with specific subclassing.

Since I probably shot completely off target, let me know how much.

**Comment by mementum** [comment]
Understanding the concerns about introducing an artificial *text* tag and having concerns about having an spurious `_maketag` (a function and not an HTML tag) as part of the `browser.html` module, I will be closing this ticket (and the associated pull request) and reformulating it in much simpler and reduced terms
