### ISSUE TITLE
Internal Javascript error when parsing invalid python code

### ISSUE THREAD

**Issue by haitaoli** [brython-dev/brython#638]
The following code causes internal javascript error:
```
for j (1, 30):
  print (5)
```

`Internal Javascript error: TypeError: <TypeError: Cannot read property 'type' of undefined>`

**Comment by PierreQuentel** [comment]
Thanks for the report. This code should raise the expected `SyntaxError` now.

**Comment by haitaoli** [comment]
Thanks for the quick fix.
