### ISSUE TITLE
Travis CI broken

### ISSUE THREAD

**Issue by mementum** [brython-dev/brython#650]
https://github.com/brython-dev/brython/blob/c7a5ffb77f8b395e1cc9e6a4fb385a2934a80dcb/www/src/py_type.js#L683-L685

These lines break Travis CI.

Introduced with commit: e7a15aa8ee7739bb7d60de5dfe7352c191a2fe72

**Comment by mementum** [comment]
The pull-request is a check to see that changing line 685 restores Travis CI.

**Comment by PierreQuentel** [comment]
The bug should be fixed with commit 8a34dd3fff0c59488c80cd3b1ba88501b42ddb94.

**Comment by mementum** [comment]
A look at the latest build in *Travis CI* [Build 861](https://travis-ci.org/brython-dev/brython/builds/266224303) shows it does. But it also shows that it undoes #645 by reintroducing again conditional function declaration which breaks `PhantomJS` test cases in *Travis CI*

`py_type.js` after the commit:
https://github.com/brython-dev/brython/blob/8a34dd3fff0c59488c80cd3b1ba88501b42ddb94/www/src/py_type.js#L37-L44

Cherry picking commit 24cfd227545f342d2f0b188ed791d7cafcc7aedc on `master` should be enough to fully fix Travis CI.

**Comment by mementum** [comment]
Or even better, just added #656 which re-applies the merge of #645 which is a single commit. No need to cherry pick, just merge.

**Comment by mementum** [comment]
And with it *Travis CI* is fully restored. See [Build 862](https://travis-ci.org/brython-dev/brython/builds/266231996) for PR #656
