### ISSUE TITLE
SyntaxError, Unbalanced bracket when comment added on line

### ISSUE THREAD

**Issue by kikocorreoso** [brython-dev/brython#658]
The following:

```python
kk = [i for i in [
        1,  # 1st quadrant
        2
]]
```

Raises a `SyntaxError`, while the following (without the comment):

```python
kk = [i for i in [
        1, 
        2
]]
```

works fine in Brython. The use of parenthesis inside instead of brackets also raises the same error.

Both examples above work fine in CPython.

If we use parenthesis outside it provides a `1, #RangeError: repeat count must be non-negative` ¿?:

```python
kk = (i for i in [
        1, # a comment
        2
])
```

Without the comment it works fine. I suppose it is a related issue. The example above also works on CPython.

**Comment by PierreQuentel** [comment]
Thanks Kiko,

My little finger tells me you've found this in test_cmath...

**Comment by kikocorreoso** [comment]
> My little finger tells me you've found this in test_cmath...

Good catch, Sherlock 🔍
