### ISSUE TITLE
[Feature] DOMNode auto-generates tags from browser.html

### ISSUE THREAD

**Issue by mementum** [brython-dev/brython#666]
When one is doing something like:
```
nodes = node.get(selector='h1')
```
The returned nodes are instances of `DOMNode`. But the tags have actually been created (in most cases) using the classes in `browser.html`.

With pull request #665, `DOMNode` will try to wrap the elements in one of the tags (classes) available in  `browser.html.tags`

**Comment by PierreQuentel** [comment]
What problem is this supposed to solve ?

**Comment by mementum** [comment]
It's not a problem, hence the tagging as *Feature*. For example

```
div = browser.html.DIV()
h1 = browser.html.H1()
div <= h1
```
In this case `h1` has undergone the `__init__` defined in `makeTagDict`

2nd case

```
div = browser.html.DIV()
div.innerHTML = '<h1></h1>'
h1 = div.get(selector='h1')[0]
```

This 2nd `h1` is an object which has not undergone `__init__`

Although the different may seem trivial or non-existent, this is the foundation for the same behavior when more complex `__init__` functions have been defined when, for example, `browser.html.H1` has been subclassed.

**Comment by PierreQuentel** [comment]
I still don't see the difference - maybe it's related to the issue number ;-)

With this code
```python
from browser import document, html

div = html.DIV()
h1 = html.H1('test 1')
div <= h1
document <= div
item1 = document.select('H1')[0]

div = html.DIV()
div.innerHTML = '<h2>test 2</h2>'
document <= div
item2 = document.select('H2')[0]

print(item1, item1.__class__)
print(item2, item2.__class__)
print(dir(item1) == dir(item2))
```
I get the same result in both cases, and the last line prints `True`.

Using a subclass will certainly lead to different results, but it's an expected behaviour.

**Comment by mementum** [comment]
> Using a subclass will certainly lead to different results, but it's an expected behaviour.

But that's the goal (mostly worked out): supporting subclasses. Example (both in one by just changing `False` to `True`

```
from browser import document
import browser.html as html


class H1(html.H1):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._myattribute = 'myattribute'

    def mymethod(self):
        print('simply mymethod')


if False:
    div = html.DIV()
    h1 = H1('test 1')
    div <= h1
    document <= div
    item1 = document.select('H1')[0]
    print('item1._myattribute:', item1._myattribute)
else:
    div = html.DIV()
    h1 = H1('test 1')
    div.innerHTML = '<h1>test 1</h1>'
    document <= div
    item1 = document.select('H1')[0]
    print('item1._myattribute:', item1._myattribute)
```

The final goal would be something like
  - put the `H1` subclass in the `tags` dictionary
  - when inserted, for example as in the snippet with `innerHTML`, and retrieved with `select`
  - have an instance that still supports the methods and attributes of the subclass

The pull-request will be updated with some extra changes (for example: `dict.__new__` was not taken into account because the regular *tags* actually don't use it, because everything is in the `factory`)

**Comment by mementum** [comment]
The pull-request has been updated with support for subclasses by `dict.__new__` to do the same as the `factory` (it was falling short of) and giving tags (subclasses or not) to identify the wrapping by featuring an attribute named

  - `_wrapped`

The `tags` attribute is now attached to `DOMNodeDict` and the `$` has been removed to let external applications access the attribute from *Python* code.

The flag `elt_wrap` has been renamed to `$elt_wrap` because there is no need for it to be accessible, since it is a temporary value which is reset to `undefined` as soon as it is seen and taken into account.

The changes trigger 4 failures out of 144 in the *Travis-CI* tests in all 4 cases the text of the test is:

  - `Testing deployment of .pyc.js files`

Any hint?

**Comment by mementum** [comment]
Hint found and typo corrected.

**Comment by PierreQuentel** [comment]
Ok, that's more clear to me, I have merged the PR. Thanks !
