### ISSUE TITLE
The commit for a partial fix of #649 introduces regressions

### ISSUE THREAD

**Issue by jonathanverner** [brython-dev/brython#668]
The commit 5125fd11484c78cb460b7a77bf3560ab6775bb6b (a partial fix for #649) makes the unittest framework crash (actually prevents importing `select`). The problem seems to be that select has a class `poll` which has a method of the same name (`poll`) and the code introduced by this commit thinks that this is an error (it would be, if I was using the name of the class as an rvalue, but defining a method, the name is used as an lvalue!)

**Comment by jonathanverner** [comment]
No problem :-) Good night

**Comment by PierreQuentel** [comment]
Fixed in commit 5c2fdac8e85702660a99b5b5bf667c4d173b201a

**Comment by jonathanverner** [comment]
Thanks!
