### ISSUE TITLE
is operator differs on floats

### ISSUE THREAD

**Issue by jonathanverner** [brython-dev/brython#669]
In CPython

```python
assert 0.1 is 0.1
```

passes while in Brython it does not.

**Comment by PierreQuentel** [comment]
Javascript is an endless source of fun : 
```
> new Number(1) === new Number(1)
false
> new Number(1) == new Number(1)
false
```

**Comment by jsbueno** [comment]
I don't think this is a bug at all. That in CPuthon "0.1 is 0.1" can be considered an implementation detail.

Brython have to ensure that `a = 0.1; assert a is a` - but the underlying implementation is free to create new number instances.
As far as I am concerned this is not-a-bug.

**Comment by jonathanverner** [comment]
Technically you are right (per the following paragraph from python [docs](https://docs.python.org/3/reference/datamodel.html):

> Even the importance of object identity is affected in some sense: for immutable types, operations that compute new values may actually return a reference to any existing object with the same type and value, while for mutable objects this is not allowed. E.g., after `a = 1; b = 1`, `a` and `b` may or may not refer to the same object with the value one, depending on the implementation, but after `c = []; d = []`, `c` and `d` are guaranteed to refer to two different, unique, newly created empty lists. (Note that `c = d = []` assigns the same object to both `c` and `d`.)

On the other hand, I ran across this since the unit tests for the standard `cmath` library have the following assert:

```python
c = 3.14 + 1j
assert complex(c) is c)
del c
```

which relies on the fact that complex(c) is the same object as c, which, according to the docs, is technically an implementation detail of CPython. But it is still tested in the standard unittests...
