### ISSUE TITLE
Escape sequence \N does not work in strings

### ISSUE THREAD

**Issue by jonathanverner** [brython-dev/brython#670]
According to Python Docs "\N{unicode character name}" should evaluate to the unicode character. To implement this, one would need a [mapping](http://unicode.org/Public/UNIDATA/UnicodeData.txt) of names to unicode code-points. Hiowever I am not sure it is worth the trouble (and the additional size of the mapping file...) What do others think?

**Comment by PierreQuentel** [comment]
I agree that it should be added since it's legal Python. We must find a way to make the loading of __UnicodeData.txt__ optional (it's 1.7 Mb !) and if possible reduce its size, it has a lot of redundancy.

**Comment by PierreQuentel** [comment]
I added a minimal version of __UnicodeData.txt__, called __unicode.txt__, in folder __/src__. It is limited to the code values on 4 digits, which should cover most use cases.
The file is 527 kB. It is only loaded if the source code parser finds a string with the sequence `\N{`. It will be included in the release files for the next version.

**Comment by jonathanverner** [comment]
@PierreQuentel very nice!!
