### ISSUE TITLE
Bitwise operations with negative numbers differ from CPython

### ISSUE THREAD

**Issue by jonathanverner** [brython-dev/brython#672]
The following assert which passes fine in CPython

```python
assert (-20 & (2**31-1)) - (-20 & (2**31)) == -20
```

fails in Brython.

I encountered this issue while trying to change Brython's hash functions for numbers to match the Python ones. The reason I did this was that some hash tests in test_complex failed and I wanted to rectify that, but that meant also reimplementing hashes for floats...

**Comment by imnvr** [comment]
Paid a 10 dollar bounty for this here:
https://www.bountysource.com/issues/49097443-bitwise-operations-with-negative-numbers-differ-from-cpython
