### ISSUE TITLE
Brython does not mangle private attribute names

### ISSUE THREAD

**Issue by jonathanverner** [brython-dev/brython#673]
Defining a class like so

```python
class A:
	def __init__(self):
		self.__x = 20
```

Python "mangles" the `__x` private attribute name by prepending `_A__` to it, e.g. the following passes in CPython:

```python
a = A()
assert a._A__x == 20
```

while it fails in Brython, because Brython doesn't mangle private attribute names (i.e. attributes starting with a double underscore). See [Section 9.6](https://docs.python.org/3.6/tutorial/classes.html) of the Python documentation.

**Comment by imnvr** [comment]
Paid a 15 dollar bounty for this here:
https://www.bountysource.com/issues/49097974-brython-does-not-mangle-private-attribute-names
