### ISSUE TITLE
Embedding objects in HTML Elements as attributes

### ISSUE THREAD

**Issue by mementum** [brython-dev/brython#674]
This is much more a *for discussion* topic, than a report issue, because it is unclear what the expected behavior should be

Use case
```python
import browser.html as html

a = html.H1('hello', myattribute={'mykey': 'myvalue'})
print('a.myattribute is:', a.myattribute, type(a.myattribute))
print('a.myattribute dir:', dir(a.myattribute))

b = html.H1('hello', myattribute=['mykey', 'myvalue'])
print('b.myattribute is:', b.myattribute, type(b.myattribute))
print('b.myattribute dir:', dir(b.myattribute))
```

And the output is:

```
a.myattribute is: [object Object] <class 'str'>
toString ƒ (){return 'string!'}
a.myattribute dir: ['0', '1', '10', '11', '12', '13', '14', '2', '3', '4', '5', '6', '7', '8', '9']
b.myattribute is: mykey,myvalue <class 'str'>
toString ƒ (){return 'string!'}
b.myattribute dir: ['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9']
```

Neither the attempt to embed a `list` or a `dict` seem to have succeded.

A possibly very naive expectation would be to embed them and recover them as they were. Of course: an HTML Element knows nothing about Python and its objects

**Comment by PierreQuentel** [comment]
Setting arbitrary attributes was already possible with
```python
a = html.H1('hello')
a.myattribute = {'mykey': 'myvalue'}
```
In the commit referenced above I have adapted the html tags constructor to do the same.

Thanks for the suggestion !
