### ISSUE TITLE
Python Shell help() method results in exception

### ISSUE THREAD

**Issue by 1kastner** [brython-dev/brython#678]
I wanted to read some documentary in the Python Shell which uses brython under the hood.
There I encountered the following issues:
 
    >>> help(str)
    NameError: name 'ActiveXObject is not defined
      module '$exec_81' line 1
    help(str)' is not defined

    >>> help(random.random)
    ''

While the second is a valid behavior if the documentation is not copied from the CPython distribution, the first does not look beautiful at all and as far as I have grasped the concept of brython, it should behave like python and only throw errors which conform with the specifications.

**Comment by imnvr** [comment]
Paid for a 10 dollar bounty here:
https://www.bountysource.com/issues/49245734-python-shell-help-method-results-in-exception

**Comment by jonathanverner** [comment]
This seems to work now (both in the online console and in the editor)... @1kastner: Can you please check with a recent version of Brython?

**Comment by 1kastner** [comment]
The `help(str)` issue is solved on [0] and I guess after an update also at [1].

[0] https://www.brython.info/tests/console.html
[1] https://chrome.google.com/webstore/detail/python-shell/gdiimmpmdoofmahingpgabiikimjgcia?hl=en

By the way, is it part of the plan to have full documentation for whatever CPython offers documentation for?
