### ISSUE TITLE
super().__getattribute__ does not work properly

### ISSUE THREAD

**Issue by jonathanverner** [brython-dev/brython#680]
The following code runs fine in CPython, but fails in Brython:

```python
class A:
	def __getattribute__(self, name):
		return super().__getattribute__(name)
		
	def test(self):
	    pass
		
A().test()
```

Running this in the editor results in

```python
Traceback (most recent call last):
  module editor line 100
    traceback.print_exc(file=sys.stderr)
  module <module> line 8
    A().test()
  module <module> line 3
    		return super().__getattribute__(name)
AttributeError:object 'super' has no attribute 'undefined'
<completed in  10.00 ms>
```

**Comment by imnvr** [comment]
Paid for a bounty for this here: https://www.bountysource.com/issues/49470479-super-__getattribute__-does-not-work-properly

**Comment by PierreQuentel** [comment]
What is this "bounty" thing ? Needless to say, I refuse that anybody (me included, of course) gets paid for anything related to Brython.

**Comment by benjaminrigaud** [comment]
@PierreQuentel : this may requires a discussion :) It is sane for any OSS project to be able to be funded.

**Comment by PierreQuentel** [comment]
It might require a discussion with other people, and I respect them, but not with me.

**Comment by PierreQuentel** [comment]
@imnvr 
Is it possible to remove all these issues from "bountysource" ? If so please do.

**Comment by jonathanverner** [comment]
@PierreQuentel: Thank you for the very fast fix!!
