### ISSUE TITLE
List comprehension split across two lines raises a SyntaxError

### ISSUE THREAD

**Issue by jonathanverner** [brython-dev/brython#681]
It seems that Issues #553 and #499 strike back. The following code throws a syntax error on me in Brython:

```python
found = [x for x in ['a','b','c']
                     if x and not x.startswith('-')][-1]

 module $exec_164 line 1
  found = [x for x in ['a','b','c']
                                                                                         ^
SyntaxError:invalid syntax
```

**Comment by PierreQuentel** [comment]
It could have been a regression, but there are tests for these issues in the built-in test suite (in __issues.py__) and they still passed. The problem was the subscription on a list or dict literal with a negative number ; it's strange that the bug was never discovered before.
