### ISSUE TITLE
Exception when calling JavaScript function with "None" as an argument

### ISSUE THREAD

**Issue by schlarpc** [brython-dev/brython#683]
Any function will do, but you can easily see with a built-in one like `window.alert`.

Example:

```
>>> import browser
>>> browser.window.alert(None)

Exception:Cannot read property '$nat' of null
  module '$exec_74' line 1
import browser
```

Using Brython 3.3.3.

**Comment by PierreQuentel** [comment]
You should call `browser.alert()`, not `browser.window.alert()`.

If an attribute of `window` is a function, the underlying Javascript function is called with its Python arguments translated to Javascript objects with the table described in the [documentation](http://brython.info/static_doc/en/jsobjects.html) ; here, `None` is translated to `null`, hence the result you get.

**Comment by PierreQuentel** [comment]
The commit referenced above fixes the bug that happened when passing `None` as argument.
Thanks for the report !
