### ISSUE TITLE
I need some help

### ISSUE THREAD

**Issue by computinginschools** [brython-dev/brython#686]
Sorry to have to admit this, but I need some simple implementation help with Brython. I run a teaching website for high school computer science and I'm trying to embed a simple Brython console on some of the pages to allow the students to try out console commands.

So, I've created a repository (https://github.com/computinginschools/trython) where I've used the console demo from the brython website as a template to create console.htm so that I can embed this page in an iframe (it's a google site and I can only embed iframes).

When I'm at school, it works fine - no javascript errors, console displays perfectly in both IE and Chrome. At home, however, I get tonnes of Javascript errors ...

![2017-09-26 19_24_53-site notes - the computing cafe](https://user-images.githubusercontent.com/24505885/30877126-a4a30d24-a2f0-11e7-9e16-fa8bf19292cb.png)

... and the iframe is blank. I probably should be able to sort this out myself, but I have no idea what's wrong - sorry and thanks for your help.

The webpage, console.htm, is hosted on github pages at ...

https://computinginschools.github.io/trython/console.htm

Mark

**Comment by jonathanverner** [comment]
It seems that the version of Brython you are including ([stable/www/src/brython.js, brython_stdlib.js](https://cdn.rawgit.com/brython-dev/brython/stable/www/src/brython.js)) has some problems. Try using the master branch ([master/www/src/brython.js, brython_stdlib.js](https://cdn.rawgit.com/brython-dev/brython/master/www/src/brython.js))...

**Comment by computinginschools** [comment]
Yes - thank you so much. That works great now :) I still find it strange that the stable branch worked fine at work but didn't work at home even using the same browser. Strange.

**Comment by computinginschools** [comment]
I've noticed something interesting - I'm teaching about strings and lists so when I try to create a string to split, I get this ...

![2017-09-27 00_01_41-brython interactive mode](https://user-images.githubusercontent.com/24505885/30888196-16f05000-a317-11e7-81b6-eea7a90c04d7.png)

... which seems peculiar to the variable 'message'. I don't get the same response from other variables. Can anyone explain this?

**Comment by PierreQuentel** [comment]
Thanks for reporting this. It's a bug with variable names that must be aliased with 2 leading $ because of conflicts with Javascript names. I'll fix it later today.
