### ISSUE TITLE
Accessing brython.info is very slow from China

### ISSUE THREAD

**Issue by leafonsword** [brython-dev/brython#688]
I knew many websites were blocked in China(including brython.info), so I use a proxy to access these websites; But brython.info is to slow to show. While other websites( like github、google) could be opened; Does brython.info has some problem in web server or network?

**Comment by PierreQuentel** [comment]
Loading the brython home page takes like 1-2 seconds here (in France). I don't know for other countries but it's never been reported, so it could be specific to your country.
