### ISSUE TITLE
Issue accessing global variables

### ISSUE THREAD

**Issue by dkosbie** [brython-dev/brython#690]
Hi all.  The code below demonstrates a bug in accessing global variables.  As of 29-Sep-2017, this bug is produced when run with this brython version:
    https://cdn.rawgit.com/brython-dev/brython/stable/www/src/brython.js
But it is not produced with this brython version:
    https://cdnjs.cloudflare.com/ajax/libs/brython/3.3.20/brython.js

It should print 42 all 4 times, but in the buggy version, the first (straightforward) case fails, claiming the global variable is not defined:

` 

    def setSomeGlobal():
        global someGlobal
        someGlobal = 42

    setSomeGlobal()

    def getSomeGlobal():
        return someGlobal

    # Directly accessing the global will fail:

    try: print('someGlobal -->', someGlobal)  # Error: name 'someGlobal' is not defined
    except Exception as e: print('Error:', e)

    # But "indirectly" accessing the global succeeds:

    print('globals()["someGlobal"] --> ', globals()["someGlobal"]) # 42 (ok)
    print('getSomeGlobal() --> ', getSomeGlobal())                 # 42 (ok)
    print('(lambda:someGlobal)() --> ', (lambda:someGlobal)())     # 42 (ok)`

Thanks!

David

**Comment by jonathanverner** [comment]
The stable tag is old (3.3.2). The bug appears to be fixed in master.

**Comment by dkosbie** [comment]
Great, and sorry for the outdated bug report.

One question, though:  Is there a preferred cdn url that projects using Brython (such as ours) should use to get the most-current stable version?

Thanks!

David

**Comment by PierreQuentel** [comment]
I get the same bug on brython.info (version 3.3.4) and on the current development version. The code works fine in the editor, but not in the console.

**Comment by PierreQuentel** [comment]
The latest stable version is at https://cdn.rawgit.com/brython-dev/brython/stable/www/src/brython.js

**Comment by dkosbie** [comment]
Good to know, thanks.  So we were in fact using the right stable version (whew), which unfortunately was exhibiting this bug.

Thanks again.

David

**Comment by PierreQuentel** [comment]
@jonathanverner 
How do you get this version number with the stable tag ? For me it's 3.3.4.

**Comment by PierreQuentel** [comment]
The commit referenced above fixes most of the issues, except the last one with `lambda`

**Comment by jonathanverner** [comment]
@PierreQuentel  I am not sure, it was probably my mistake, sorry for the confusion.

**Comment by dkosbie** [comment]
Hi all.  Quick q:  is the following an example of the same bug or a new bug:

global s
s = 0
s = s + 1 # works
s += 2    # fails: NameError:
print(s)  # 3 expected

Thanks.

David

**Comment by PierreQuentel** [comment]
I have fixed this bug and other ones I found, but I am almost sure that this issue will be reopened sooner or later...

**Comment by darthglowball** [comment]
I can't acces global functions from one script in other scripts. I have two scripts in the main html body:

    <script type="text/python">
      from browser import alert

      def function_a():
          alert("function a")
      
      global function_b
      def function_b():
          function_a()
          alert("function b")
          
    </script>
    <script type="text/python">
      function_b()
    </script>

In Chrome the error is:
`Traceback (most recent call last):
NameError: name 'function_b' is not defined
brython.js:5028 Uncaught Error
    at Object._b_.NameError.$factory (eval at $make_exc (brython.js:7382), <anonymous>:101:327)
    at Object.$B.$global_search (brython.js:5690)
    at eval (eval at $B.loop (brython.js:5012), <anonymous>:11:17)
    at $B.loop (brython.js:5012)
    at $B.loop (brython.js:5017)
    at $B.inImported (brython.js:5002)
    at $B.loop (brython.js:5018)
    at IDBOpenDBRequest.idb_cx.onsuccess (brython.js:4982)`

The globals are not found in the second script's globals(). They aren't in browser.window either (would that be a good place for Python globals?) A workaround is by putting your globals in `__BRYTHON__` (I haven't had any name clashes with internal Brython variables, so it seems safe?). Still really annoying though to do it like that.

**Comment by PierreQuentel** [comment]
Like in CPython, the scripts are run each in its own namespace ; sharing the same namespace for all scripts would cause terrible bugs.

To share variables between scripts you can use the object `browser.window` : 

```xml
<script type="text/python">
from browser import alert, window

def function_a():
  alert("function a")

def function_b():
  function_a()
  alert("function b")

window.function_b = function_b
</script>

<script type="text/python">
from browser import window

window.function_b()
</script>
```
