### ISSUE TITLE
Instance variable's __dict__ not clearing

### ISSUE THREAD

**Issue by dkosbie** [brython-dev/brython#691]
Hi all.  Here is some sample code to demo the bug:

[Note: this is not formatting correctly, and the double-underscores for dict are not appearing.  But when I use the <> to insert code, it all appears on one line (see next comment).  Sorry...]

```python
class C(object): pass
c1 = C()
c1.x = 42
c1.__dict__.clear()
print(c1.__dict__) # prints { 'x': 42}, but {} is expected
```

A slight twist is illuminating:

```python
class C(object): pass
c2 = C()
c2.x = 42
c2.__dict__ = dict()
print(c2.__dict__) # prints {'x': 42, '__dict__': {}}
```

What is `__dict__` doing in the dict?  It seems `__dict__` is being treated like a normal instance variable somehow, or some such.

Anyhow, thanks as always for your great help.

David

**Comment by dkosbie** [comment]
Argh.  I'm having editing problems here.  When I use the <> to insert code, it seems to place it all on one line.  But when I didn't do that and left the code at the top-level, as above, it removed the double-underscores.  Drats.  So I'll include the code here again in <> and hope it formats properly:

First example:

`class C(object): pass
c2 = C()
c2.x = 42
c2.__dict__ = dict()
print(c2.__dict__) # prints {'x': 42, '__dict__': {}}`

Second example:

`class C(object): pass
c2 = C()
c2.x = 42
c2.__dict__ = dict()
print(c2.__dict__) # prints {'x': 42, '__dict__': {}}`

Sorry for the confusion, and thanks again.

David

**Comment by jonathanverner** [comment]
@dkosbie Inline code is enclosed in \` (backtick), display code is inserted by starting a line with \`\`\`language_name (three backticks followed by the name of the language, e.g. python) and ending the block using \`\`\` on a single line. 

For example: \`\_\_dict\_\_\` gives `__dict__` and

\`\`\`python
def test(a,b):
    print(a,b)
\`\`\`

Gives

```python
def test(a,b):
    print(a,b)
```

**Comment by dkosbie** [comment]
@jonathanverner: very helpful.  thanks!  :-)
