### ISSUE TITLE
AttributeError: object has no attribute __ARGV

### ISSUE THREAD

**Issue by chfw** [brython-dev/brython#695]
With Brython 3.3.4, I am getting 
<img width="648" alt="screen shot 2017-10-16 at 08 43 29" src="https://user-images.githubusercontent.com/4280312/31600387-255d593a-b24e-11e7-877f-84e36c7e3099.png">

However, the same setup with Brython 3.3.2, it runs OK.

I have been reducing the number of modules goes into brython_modules.js. So, could you please help me identify which module did I missed to include in brython_modules.js? As long as I knew the name, I can included it by myself.

Here's my current list of modules:

```
reprlib
_weakrefset
builtins
operator
browser.ajax
re
itertools
json
codecs
io
sys
sre_parse
time
datetime
sre_constants
genericpath
stat
_collections
random
copyreg
sre_compile
traceback
os
abc
pprint
collections.abc
_weakref
_sre
__future__
_codecs
_ajax
heapq
keyword
_abcoll
_dummy_thread
math
collections
uuid
posix
posixpath
errno
_thread
```

**Comment by jcubic** [comment]
I've got the same error when I imported sys, it's working in dev version.

**Comment by PierreQuentel** [comment]
Do you really mean version 3.2.4 ? It was published in January 2016, the current version is 3.3.4.

**Comment by chfw** [comment]
@PierreQuentel , I am sorry. It is 3.3.4 and no issues found with 3.3.2. I updated the description too.

**Comment by PierreQuentel** [comment]
@chfw and @jcubic 
Can you give a sample of Brython code that produces this error ? `import sys` works on brython.info so it must be something else.

**Comment by jcubic** [comment]
if you use this demo https://codepen.io/jcubic/pen/QqJxqZ?editors=1000 and change master to stable in settings/js you'll get:
```
Error for module sys
Traceback (most recent call last):
AttributeError: object has no attribute __ARGV
```
maybe it's happening when you try to get `sys.implementation.version`
