### ISSUE TITLE
Exceptions thrown printing various dunder attributes

### ISSUE THREAD

**Issue by mjayfrancis** [brython-dev/brython#699]
Spotted while trying to get `inspect.getmembers()` working:
This is more of a nitpick than I anticipated as it does actually appear to work now - but printing the returned results throws exceptions
(e.g. just `inspect.getmembers(int)` in the interactive shell throws an exception - but it's from printing the result, not inside the function)

The issue appears to be that various \_\_dunder\_\_ methods don't have a working `__repr__()` / `__str__()`

Using the test function:
```
def try_print_members(obj):
    for m in dir(obj):
        try:
            print(m, getattr(obj, m))
        except Exception as e:
            print("\nError printing ", m)
            print(e)
            print()
```

**Test 1:**
```
>>> try_print_members(int)
...
Error printing  __eq__
<TypeError: self.$infos is undefined>
...
Error printing  __hash__
<TypeError: self.$infos is undefined>
...
Error printing  __ne__
<TypeError: self.$infos is undefined>
...
Error printing  __setattr__
<TypeError: self.$infos is undefined>
...
Error printing  toString
'int' object has no attribute 'toString'
```

(`toString` above appears to be a separate issue - not clear why it's there in the attributes of `int` to begin with as Python doesn't have one - is this leakage from Javascript?)

**Test 2:**
```
class Foo:
    def foo(self): pass
```

```
>>> try_print_members(Foo)
...
Error printing  __dict__
<TypeError: self.$infos is undefined>
...
```

**Comment by PierreQuentel** [comment]
Thanks for reporting this.

The `toString` method was not a leakage from Javascript, it was probably added for debugging a long time ago and I forgot to remove it...
