### ISSUE TITLE
The `Bytes` type is missing some methods. 

### ISSUE THREAD

**Issue by jonathanverner** [brython-dev/brython#705]
The `bytes` type is missing the following methods: `(r)index`, `endswith`, `count`, `(r)partition`, `rfind`, `center`, `l/rjust`, `capitalize`, `expandtabs`, `isalnum`, `isalpha`, `isdigit`, `islower`, `isspace`, `istitle`, `isupper`, `splitlines`, `swapcase`, `title`, `zfill`. Some of these are probably too obscure (center, expandtabs, capitalize...) but some might be useful. 

Implementing them should not be hard, but I am currently not planning to do it, as I have no use for them. However, I think it is a perfect issue for someone who would like to start contributing to get his feet wet :-) If someone does take it up, [here](https://docs.python.org/3/library/stdtypes.html?highlight=bytes#bytes) are the CPython docs of these functions. The Brython implementations should be written in Javascript and put into the [py_bytes.js](https://github.com/brython-dev/brython/blob/master/www/src/py_bytes.js) file which lives under in the `www/src` subdirectory of brython's root directory.

**Comment by TheLastTech** [comment]
This look interesting!

**Comment by PierreQuentel** [comment]
All the missing methods have been added now, so I am closing the issue.
