### ISSUE TITLE
Problem running node_bridge.js

### ISSUE THREAD

**Issue by clarktlaugh** [brython-dev/brython#707]
I would like to be able to use brython from nodejs (not in a browser window) to execute python code, and was trying to get started using the pre-existing node_bridge.js.  When I run it, I get the following:

Should I be doing something different?  It looks like brython(when initializing) is looking for DOM elements, which aren't going to be there when running in nodejs.

PS C:\Users\laughlcl\source\brython\scripts> node node_bridge.js hello.py
undefined:22
var $href=$B.script_path=_window.location.href
                                         ^

TypeError: Cannot read property 'href' of undefined
    at eval (eval at <anonymous> (C:\Users\laughlcl\source\brython\scripts\node_bridge.js:38:6), <anonymous>:22:42)
    at eval (eval at <anonymous> (C:\Users\laughlcl\source\brython\scripts\node_bridge.js:38:6), <anonymous>:70:14676)
    at Object.<anonymous> (C:\Users\laughlcl\source\brython\scripts\node_bridge.js:38:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)

**Comment by jonathanverner** [comment]
Right now this is not possible. However, the [work](https://github.com/brython-dev/brython/pull/662) on WebWorkers should make it relatively easy to support node.js too  (the webworker doesn't have access to the dom which I had to work around). The idea would be to introduce a new boolean variable `isNode` (or, even better, a variable `js_platform` which would unify the checks for webworkers and node.js) and then hide all the code which relies on the dom behind an if-check. These should be relatively easy to find as they should already be hidden behind a check for `isWebWorker`. Most of them are in the [www/src/py2js.js](https://github.com/brython-dev/brython/blob/master/www/src/py2js.js) but a few are also in [www/src/brython_builtins.js](https://github.com/brython-dev/brython/blob/master/www/src/brython_builtins.js) and [www/src/py_utils.js](https://github.com/brython-dev/brython/blob/master/www/src/py_utils.js). Also you would need to provide a dummy `_window` object, but that shouldn't be too hard (i.e. it should have a `location.href` property and possibly something else, but not much).  

Looking at changes from the [pull-request](https://github.com/brython-dev/brython/pull/662) for WebWorkers should give you an idea of what is necessary.

If you manage to make it work, it would be great if you could contribute your changes back :-) And don't hesitate to ask questions if something is not clear :-)

**Comment by kaydelaney** [comment]
Hey there. So I gave adding Node support to Brython a shot and ended up with this: https://github.com/kaydelaney/brython/commit/46fa31fb554c4451057e3b4a622def5785fc1bd7

Seems to work okay from the little testing I've done, though I haven't tried anything too extensive.
One thing I was curious about: I might have expected the following to be true
```javascript
let result = __BRYTHON__.run_script('return 3', '__main__', true);
expect(result).to.equal(3);
```
but this doesn't seem to be the case. Is there any way to access the return value of an executed python script?

**Comment by alexander255** [comment]
@kaydelaney: Could you make a PR with your changes, seems very useful to me. Also, in your example, what is the type of the returned value? Could it be some kind of BigInt by any chance?

**Comment by PierreQuentel** [comment]
@schmave Can we close this issue ?

**Comment by schmave** [comment]
Yes, running Brython in Node works for me now.

**Comment by PierreQuentel** [comment]
Ok, thanks
