### ISSUE TITLE
Enhancement to the turtle module

### ISSUE THREAD

**Issue by aroberge** [brython-dev/brython#709]
I would like to suggest the following enhancements to the turtle module:

1. Make the id of the div and of the svg element become adjustable parameters instead of being
hard-coded as they currently are.
2. Add a function to enable easy configuration of the adjustable parameters in the turtle module.
3. Add a function to enable restarting drawings
4. If possible, add a way to enable interactive drawings at an Interpreter prompt.

I have already implemented the first three features (see below), and you can see a demo by going to http://reeborg.ca/reeborg.html?lang=en&mode=python&url=/src/worlds/blank.json
This will select a blank world, suitable for drawing with the turtle module. You will need to click on the "reload" button 
![image](https://user-images.githubusercontent.com/629698/32634071-5efcc14a-c580-11e7-8f51-a36633f30aba.png)

to dismiss the popup window and be ready to run some code.  

I suggest you enter and run some code like the following in the Python code editor:
```py
import my_turtle as turtle
no_highlight()

turtle.set_defaults(
    canvwidth = 620,
    canvheight = 540,
    turtle_div_id = "canvas-wrapper")

def demo(restart=False):
    if restart:
        turtle.restart()
    t=turtle.Turtle()
    t.width(3)
    for c in ['red', 'blue', 'yellow', 'green', 'purple', 'brown']:
        t.color(c)
        t.forward(50)
        t.left(60)
    turtle._Screen().end()
    
demo()
```
(You can probably simply use copy/paste.)

Run it multiple times, each time reloading the world. (The first time you run, no drawing will be done and another popup window will be shown which you can ignore.) As you reload, you will see the screen being cleared **but** when you run it, you will see drawings from previous runs being drawn again, in a cumulative fashion.

However, by running
```py
demo(True)
```
the previous drawings will be effectively deleted from the history.

## My implementation

You can see my implementation of the previously mentioned enhancement at https://github.com/aroberge/reeborg/blob/master/src/python/my_turtle.py
I essentially copied the code from the Brython distribution and made some minor adjustments.

### 1. Personalized div and svg canvas ids

Starting at line 26 (https://github.com/aroberge/reeborg/blob/master/src/python/my_turtle.py#L26) I added two additional parameters to allow the user to choose their own preferred id for the enclosing div and svg canvas.

This is used starting at line 86 (https://github.com/aroberge/reeborg/blob/master/src/python/my_turtle.py#L86) up to line 95.

### 2. Function to defined personalized parameters

Since `_CFG` has a name indicating a private parameter, thus subject to change, I suggest the addition of a function such as I defined on line 30 (https://github.com/aroberge/reeborg/blob/master/src/python/my_turtle.py#L30)

### 3. Deleting previous drawings

As shown in the demo, running some code many times result in a cumulative drawing being done, with the full history in a given session retained.  This can be avoided by defining a function I called `restart()` which is defined on line 2998 (https://github.com/aroberge/reeborg/blob/master/src/python/my_turtle.py#L2998)

### 4. Enabling interactive interaction

Using a Python REPL (available from the menu at the top of the page of my demo program), I found that I could use the turtle module ... but that it was not possible to show the result of a single line instruction. I've attempted to define a `show()` function so that I could have something like:
```py
>>> t.forward(100)
>>> show()
>>> t.left(90)
>>> show()
>>> # etc.
```
but only the first call to `show`, which was essentially the same as `turtle._Screen.end()` would work.

**Comment by PierreQuentel** [comment]
@aroberge 

I am not the author of the turtle module, it's Billy (@earney), he would have a more expert opinion than I.

I agree with the changes you propose, with a miror comment : passing the container and svg with their ids seems less natural to me than passing the objects themselves
```python
turtle.set_defaults(
    canvwidth = 620,
    canvheight = 540,
    turtle_div = document["canvas-wrapper"] # rather than turtle_div_id = "canvas_wrapper"
)
```

Another thing that could be improved is how to end the drawing : calling method `end` of the private class `turtle._Screen` hurts the eye. Could you propose something better ?

Thanks for your work on this, if you can file a Pull Request I will merge it.

**Comment by aroberge** [comment]
Passing the objects themselves also seems like a better idea to me. As for the method `end`, I would suggest to hide it inside a function named `show()` or `render()`.  Given the intended target audience, I suggest that `show()` would be a better choice.

Given @earney's role I would prefer to wait at least a couple of days to hear from him, before I prepare a Pull Request myself.  I've noted a fair bit of unused code (undefined functions or methods called elsewhere) and am wondering if the module should not be cleaned up a bit (which I would volunteer to do).  [Most of what I noted was flagged by my linter.]
