### ISSUE TITLE
Could brython's documentation available in github?

### ISSUE THREAD

**Issue by leafonsword** [brython-dev/brython#710]
Official site "brython.info" is very slow from China, so could brython's documentatio also be available in github's wiki section?

**Comment by jonathanverner** [comment]
You can browse the documentation [in the repository](https://github.com/brython-dev/brython/tree/master/www/doc/en). Or, if you clone the repository, you can get a local version of www.brython,info by running

```bash
$ python3 server.py
```

in the root directory of the clone (this will run a simple webserver on localhost:8000 with a copy of the Brython website served from your computer). 

Having the documentation in two places would probably lead to it being out of date in one of them.
