### ISSUE TITLE
Unreachable code after return statement

### ISSUE THREAD

**Issue by aroberge** [brython-dev/brython#712]
Using Brython 3.3.4, according to the developer's console in Firefox (v. 58), there is some unreachable code after a return statement on line 546. This can be seen by opening the console and going to http://brython.info/tests/editor.html?lang=en.

**Comment by notzoom** [comment]
@aroberge I have tried that as well and can confirm it.

**Comment by PierreQuentel** [comment]
The warning happened in the Javascript code generated in some rare cases: 
```python
def f():
    try:
      return 1
    finally:
      return 2

def f():
    for x in y:
        return
```
