### ISSUE TITLE
Using Brython to Build Firefox WE Addons

### ISSUE THREAD

**Issue by skeledrew** [brython-dev/brython#713]
I've been searching and reading a lot but can't quite figure how to access Brython from a web extension content or background script. I think there's a way to do this but I'm not very good at JavaScript. Can we have an example of using it in a regular JS file and running a Python script from within? Or if there's any modification required to make such use easier that would be nice. I think it would immediately make Brython attractive to wannabe addon developers who mainly use Python (like me).

**Comment by xisx** [comment]
I am in need of a similar answer, would appreciate if someone could get back to us.

**Comment by jonathanverner** [comment]
Unfortunately, this is probably somewhat nontrivial. 

One part you have to be aware of is that you definitely need to change the [content-security-policy](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Content_Security_Policy) because the default policy disallows `eval` which Brython uses heavily. 

However, there will be probably other things, possibly requiring somewhat involved changes to Brython. Unfortunately, right now I don't have the time to investigate this more closely :-(

**Comment by xisx** [comment]
@jonathanverner Is it an option in this case to have Brython just translate your Python code to JS so that you can embed it easily as an extension ?

**Comment by jonathanverner** [comment]
@xisx Theoretically yes. At some point there was some effort to make a py2js compiler based on node.js but I don't think it is in a finished state. Anyway, it shouldn't be a problem to do the compilation "by hand" (see the [editor section](http://www.brython.info/tests/editor.html?lang=en) on the website --- it has a button which allows you to see the compiled javascript)... It shouldn't be too hard to use a headless browser (e.g. phatnomjs or some such) to even automate this. You would also need to package the Brython "runtime" --- the helper functions which are used in the compiled javascript. But it shouldn't be hard to figure out what is needed by trial and error.

The main problem would be dealing with imports which currently dynamically download the python code and compile it at runtime...

**Comment by xisx** [comment]
@jonathanverner  Ok, I have tried that but the JS code is not readable at all - could/should that change and output readable JS code ?

**Comment by jonathanverner** [comment]
@xisx Outputting readable JS code is not a goal of Brython.

**Comment by PierreQuentel** [comment]
I am closing this old issue. If someone wants to contribute ideas and (even better) code to this thread, feel free to re-open it.

**Comment by andrewchenshx** [comment]
As a python developer, I am in need of a similar answer. 
i wish brython would provide a magic function(say brython_magic_compile_to_js) so i could use it as following:
file 1:manifest.json
"content_scripts": [
  {
    "matches": [<all_urls>],
    "js": ["brython_content.js"]
  }
]

file 2:brython_content.js
brython();  
brython_magic_compile_to_js('your_py_file.py');

file 3:your_py_file.py
#your python code goes here
