### ISSUE TITLE
Subclassing of rich comparison broken for numbers

### ISSUE THREAD

**Issue by mementum** [brython-dev/brython#714]
https://github.com/brython-dev/brython/blob/2dc902ec3b40b09f35ab3ac6161bff0492f476fc/www/src/py_utils.js#L1304-L1321

This was introduced with commit: 2dc902ec3b40b09f35ab3ac6161bff0492f476fc

And breaks test unit: `test_numbers.py`. Actually this: https://github.com/brython-dev/brython/blob/385e27cbe3be587274259c656b3ed6a00a0ad9b9/www/tests/test_numbers.py#L124-L147

The code speeds up comparison when no subclassing has happened, But if subclassing is in place, using `x.valueOf` removes that information.

The speedup should have a safety check before entering the code to make sure that none of the numbers have subclassed any of the rich comparison operators. That would probably be really burdersome. A check to see if the number has been subclassed. If not (the most usual case) the speed up can be applied.

**Comment by PierreQuentel** [comment]
I noticed the bug, but I think I fixed it with commit 8bf0a44b89529b7c4938887a049af5d0e4ebe98f. __test_numbers.py__ works for me in the current development version.

**Comment by mementum** [comment]
Indeed. It was difficult to track because the commit happened after the other commit which causes #715 (All testcases fail)

Cherry picking 8bf0a44b89529b7c4938887a049af5d0e4ebe98f produces a clean run in Travis-CI.
