### ISSUE TITLE
Travis-CI build completely broken (all test cases fail)

### ISSUE THREAD

**Issue by mementum** [brython-dev/brython#715]
https://github.com/brython-dev/brython/blob/b4c50b5500bad4a2cefdecd4fbb637e5b13b3e8b/www/src/js_objects.js#L157

breaks the entire Travis-CI build.

Introduced with this commit: b4c50b5500bad4a2cefdecd4fbb637e5b13b3e8b

**Comment by PierreQuentel** [comment]
@olemis can you take a look ?

I have temporarily disabled Travis-CI.
