### ISSUE TITLE
big integers

### ISSUE THREAD

**Issue by jlaurens** [brython-dev/brython#719]
Hi there,
is there a plan to support big integers ?
TIA

**Comment by PierreQuentel** [comment]
Hi,

Big integers have been supported since version 3.2.0. Since you ask, it's probably that you have tried and it didn't work as you expect ; can you give an example ?

**Comment by jlaurens** [comment]
I think I have misunderstood something, I thought pyschool.net was some kind of official brython gallery due to the [brython examples](http://pyschool.net/gallery/brython/index.html) given there. And pyschool breaks big ints.

Of course, when using the brython interactive console, things work as I expected.
Thanks for your reply
