### ISSUE TITLE
brython.info TLS certificate is invalid

### ISSUE THREAD

**Issue by wsanchez** [brython-dev/brython#721]
This error comes up when loading `https://brython.info`:

```python
SSLError(CertificateError("hostname 'brython.info' doesn't match either of 'ssl14.ovh.net', 'www.ssl14.ovh.net'",),)
```

**Comment by PierreQuentel** [comment]
Thanks for reporting this. I think it works now, can you check and close the issue if it's ok ?

**Comment by jonathanverner** [comment]
https://www.brython.info shows as secure here...

**Comment by wsanchez** [comment]
Awesome! Thanks for the quick turn-around.
