### ISSUE TITLE
svg.text attributes casefolded in DOM

### ISSUE THREAD

**Issue by tjnaughton** [brython-dev/brython#722]
When creating a svg.text object, the some attributes (at least attributes 'textLength' and 'lengthAdjust') appear casefolded (e.g. 'textlength' and 'lengthadjust') when the DOM is inspected. Both Firefox 57 and Chrome 63 require the original (non-casefolded) versions. Tested with Brython 3.3.4. The attached .html file can be used to verify a fix.
[svg_text_example.html.txt](https://github.com/brython-dev/brython/files/1544575/svg_text_example.html.txt)

**Comment by PierreQuentel** [comment]
Thanks for reporting this !

**Comment by tjnaughton** [comment]
Great stuff, thanks!
