### ISSUE TITLE
Weird Console List Issue

### ISSUE THREAD

**Issue by xisx** [brython-dev/brython#723]
```
list = []
for i in list:
    print i
```

 module $exec_74 line 2
  
                  ^
SyntaxError:invalid syntax

If you do it in CPython it just does nothing and this is throwing a cryptic error so I thought I should report it.

**Comment by jonathanverner** [comment]
Brython implements  Python 3. In Python 3 `print` is no longer a statement but a normal function (see https://docs.python.org/3.0/whatsnew/3.0.html), so you are missing parentheses around `i`. CPython 3 throws a Syntax error (albeit with a tad bit more information) so Brython behaves correctly.

**Comment by xisx** [comment]
I understand but don't you think a proper error message should have been given instead of a cryptic one ?

**Comment by jonathanverner** [comment]
Sure the message could be improved, but it does say "Syntax error". The module ($exec_74) comes from the way how the console is implemented. Perhaps we should reopen this, @PierreQuentel? CPython's SyntaxError gives the following `SyntaxError: Missing parentheses in call to 'print'` in this case...

**Comment by xisx** [comment]
@jonathanverner  Yeah I really believe personally that the message should not be cryptic.
