### ISSUE TITLE
Observation on nested string formatting args -- not necessarily a bug

### ISSUE THREAD

**Issue by tjnaughton** [brython-dev/brython#727]
Hi Pierre,
Since you mentioned in the Google group "For the next release I plan to work on the main differences with the latest versions of Python" I thought it might not be too cheeky to submit (this, and others today) a few minor differences between Brython and Python behaviour I've noticed...
 
This is how the Python 3 documentation suggests how to nest string formatting arguments using kwargs:

```
>>> '{:>{width}}'.format('hi', width=5)
'   hi'
```

Brython implements this perfectly as per the Python documentation. However, Python (tested with Python 3.3 and Python 3.6) also allows this (possibly undocumented) non-"kwargs" version:

```
>>> '{:>{}}'.format('hi', 5)
'   hi'
```

With Brython, this non-"kwargs" version raises a ValueError.

I wish to just point this out as an observation, rather than call it a bug.

**Comment by PierreQuentel** [comment]
I just tested the code above, and it works ! I have no idea when the issue was fixed, but I am closing it.
