### ISSUE TITLE
tuple unpacking regression

### ISSUE THREAD

**Issue by tjnaughton** [brython-dev/brython#729]
Hi,

The following code:
```
>>> a= (1, 2, 3)
>>> head, *tail = a
```
raises "NameError: name 'tail' is not defined".
This code works fine with Brython 3.3.2 so the regression was introduced sometime after that release. Thanks!

**Comment by PierreQuentel** [comment]
Thanks, the test suite was badly missing a check for this...

**Comment by tjnaughton** [comment]
Great, thanks!
