### ISSUE TITLE
Minor turtle issues

### ISSUE THREAD

**Issue by aroberge** [brython-dev/brython#739]
The existing turtle module is an excellent adaptation of CPython's tkinter-based version that uses Scalable Vector Graphics (svg) for drawing including animations and is perfectly usable for simple demonstrations.

However, as I explored it, I found quite a few missing methods, some of which might not make much sense to implement in this browser version, but not all. I will document them here as I go along, as well as the progress done on a branch in my fork (https://github.com/aroberge/brython/tree/fix/master/turtle739).

*  [x] 1. at https://github.com/brython-dev/brython/blob/master/www/src/Lib/turtle.py#L3020 , `document[_CFG["turtle_canvas_id"]]` can raise a KeyError exception if the `restart()` function is called twice in a row.
* [x] 2. `write` (https://github.com/brython-dev/brython/blob/master/www/src/Lib/turtle.py#L2777) should allow the user to set the font. However, the font information is  not passed on to `svg.text` (https://github.com/brython-dev/brython/blob/master/www/src/Lib/turtle.py#L338). Similarly for the `align` parameter.
* [x] 3. Calling Turtle with "blank" as the default shape appears to be causing an error. This is for a turtle using a gif for its image. It will be removed.
* [x] 4. Setting speed to zero should result in immediate drawing; instead nothing is drawn. The fastest animation seems to be set to a duration of 0.1 s (https://github.com/brython-dev/brython/blob/master/www/src/Lib/turtle.py#L201), while svg supports animation duration in the range of ms (https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/dur)
* [x] 5. Many existing configuration settings are absolutely irrelevant (and ignored); they should be removed.
* [x] 6. `left()` appears to be turning "right" instead.
* [x] 7. The mode settings (logo, standard, world) appears to be ignored.
* [x] 8. CPython's version has a bug (https://bugs.python.org/issue23660) which I filed almost 3 years ago on behalf of another user; this bug is still not fixed but it should be in the Brython's version.
* [x] 9. In the Brython demo, it might be useful to add an output print "window" either for direct use by the turtle user or to report errors.
* [x] 10. The code run when the module is imported as `__main__` is irrelevant for Brython and has been removed.
* [x] 11. The CPython turtle module has an `undo()` method which does not really makes sense in the current context. It, and all the associated objects (such as `undobuffer`) will be removed.
* [x] 12. With the CPython turtle, in both the standard and logo mode, the y coordinate increases towards the top of the screen, whereas it increases towards the bottom with the Brython turtle.
* [x] 13. When using CPython, the turtle itself is drawn the same when changing the line thickness; however this is not the case with Brython's turtle.
* [x] 14. The `dot()` method does not produce a circle and appears to suspend any running program.
* [x] 15. If `write()` is the very first method called before any other turtle drawing, nothing gets written, nor drawn afterwards.
* [x] 16. The `bgcolor()` method does not do anything.
* [x] 17. The `stamp()` method does not do anything.
* [x] 18. `begin_fill()` and `end_fill()` are ignored.
* [x] 19. If two or more turtles are on the screen, only one is shown while  a drawing is done; this is unlike the CPython version.
* [x] 20. The function based version (i.e. anonymous turtle) is not available.
* [x] 21. With `penup()`, the moving turtle is currently not drawn when moving.
  

## Efficiency consideration

This following should be done as a second pass (perhaps in a different branch) after all the relevant methods have been done.

Currently, each time a turtle is moved, a "new" turtle shape is created and drawn on the screen as a separate svg element, moved, and, unlike in the CPython case, disappears from the screen after a drawing is done.  It should be possible to repeatedly use the turtles that have been created by:

1. setting `fill` to `freeze` after an animation has been done.
2. setting `fill` to `remove` when another animation is desired.
3. perform the animation
4. set `fill` to `freeze` again

In addition to being more efficient, as we would reuse an existing svg element rather than creating and adding a new one each time, this would likely mimic better the behavior of the CPython turtle.

A further consideration might be to see if `clear` and `reset` for a given turtle could not be implemented by setting the visibility attribute of previously drawn elements.

**Comment by jonathanverner** [comment]
Thanks for reporting and working on this!

**Comment by aroberge** [comment]
Due to differences between SVG and Tkinter, there will definitely be differences between the Brython turtle module and the CPython one. For instance, whereas one can have an undo mode with CPython, used to remove objects added in an interactive session, the same cannot be done with Brython.

However, the counterpart can also be true: there are some features easily implemented in SVG that could not be done with the Tkinter-based turtle module.  I will keep track here of some possible features to implement.

* [ ] 1. Be able to rotate text in 3-d. (https://developer.mozilla.org/en-US/docs/Web/SVG/Element/text)
* [ ] 2. Have a different outline color for text.
* [ ] 3. Have a different outline color for the circle drawn by the `dot()` method.
* [ ] 4. With SVG, it is possible to set the text length. (see demo at bottom of https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/textLength)

**Comment by aroberge** [comment]
@PierreQuentel Do you have any objections to me adding features to Brython's turtle module which are not available in CPython's version?  The converse is going to be true: there are features of CPython's version that cannot be reproduced using Brython's version ( -- at least, I cannot see how to implement all the features, like the `undo()` method).  Having some additional features that can produce nicer looking graphics might counteract any negative impression caused by the missing features.

**Comment by PierreQuentel** [comment]
@aroberge 
Yes that's fine for me, can you write a documentation page with the major differences between the CPython version and this one ?
There was a [post on Reddit](https://www.reddit.com/r/Python/comments/7mo2l8/turtle_module_drawing_a_randomised_landscape/) a few days ago about a program made with turtle, do you think it could work with the Brython version ?

**Comment by aroberge** [comment]
@PierreQuentel That post on Reddit was my motivation to have a closer look at the turtle module. It is my goal to be able to reproduce it if possible - I still cannot even though I've re-implemented most of the missing functions.

As for the documentation: I'm adding a selection of demos (chosen from a drop down menu) including some that will document all the differences between the Brython version and the CPython version, listing all the methods from https://docs.python.org/3/library/turtle.html#turtle-methods

**Comment by aroberge** [comment]
![image](https://user-images.githubusercontent.com/629698/34482405-2ad9b4b2-ef8e-11e7-994b-75cacb2c6c46.png)

The reddit post code using my current version.

**Comment by aroberge** [comment]
Just because people like pictures ... Using CPython's version, I set the pen width to 30 and drew a black line, and then set the pen width to 3 and drew the same distance over: the "line" drawn has rounded edges.
![image](https://user-images.githubusercontent.com/629698/34482846-05459600-ef91-11e7-8f8c-5b39bf347781.png)

Using the current version with Brython, I get the following:
![image](https://user-images.githubusercontent.com/629698/34482895-5cb38b4a-ef91-11e7-9c3b-b3e41ae29f86.png)

This likely explains the difference between the image I obtained using the code from the reddit post and the image posted there.

I will try to change the "line" drawing method to reproduce the CPython's case **but** add an additional option parameter (`rounded_lines` or similar), set to True by default but could be changed by the user.

**Comment by aroberge** [comment]
Can't resist posting an updated picture. :-) 
![image](https://user-images.githubusercontent.com/629698/34567930-8ee25f06-f13a-11e7-9447-743ceb4b10e7.png)

**Comment by jonathanverner** [comment]
Wow, nice!

**Comment by aroberge** [comment]
Once the pull request is accepted, this issue can be closed as far as I am concerned.

**Comment by PierreQuentel** [comment]
The Pull Request has been merged. Encore merci André :-)

**Comment by aroberge** [comment]
There seems to be a problem ... I've updated my local copy of the repository and the last example (Procedural version: comparison with CPython), it no longer works.  I'll need to have a look at what went wrong.

**Comment by PierreQuentel** [comment]
@aroberge I am reviewing old issues and wondering if keeping this one in the issue tracker still makes sense. What do you think ?

**Comment by aroberge** [comment]
@PierreQuentel Tu peux fermer le tout selon moi. Merci!
