### ISSUE TITLE
Event unbind raises exception: cannot set property <event> of undefined

### ISSUE THREAD

**Issue by zhaorz** [brython-dev/brython#745]
Using version 3.40, unbinding an event results in the follow exception:

```
Brython 3.4.0 on Netscape 5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36
>>> window.document.body.bind('click', lambda: print('hey'))
<HTMLBodyElement object>
>>> window.document.body.unbind('click')

Exception: Cannot set property 'click' of undefined
  module '$exec_74' line 1
window.document.body.unbind('click')
>>> 
```

This behavior was *not* observed in 3.3.5. The exception is raised for both built-in events and custom events.

Cheers,
Richard

**Comment by jonathanverner** [comment]
Does not happen in 3.4.1 anymore. I think this was fixed in 6bb204c74e6d7b9ff15ab35cf14828e53019f0c8. If you encounter the error with 3.4.1, please reopen.
