### ISSUE TITLE
Current build: can not set width of HTML Element

### ISSUE THREAD

**Issue by Slebi** [brython-dev/brython#747]
In the current build the following html document fails:
```
<html>
	<head>
		<script type="text/javascript" src="/brython/brython.js"></script>
		<!--<script type="text/javascript" src="https://cdn.rawgit.com/brython-dev/brython/3.4.0/www/src/brython.js"></script> -->
  		<script type="text/python">
from browser import document as doc

print("test_div.width: {}".format(doc['test_div'].width))
doc['test_div'].width = 400
print("test_div.width: {}".format(doc['test_div'].width))
  		</script>

	</head>
	<body onload="brython(1)">
		<div id='test_div' style='border:solid'>HALLO</div>
	</body>
</html>
```

The error message is:
```
Traceback (most recent call last):
  module __main__ line 2
    print("test_div.width: {}".format(doc['test_div'].width))
AttributeError: style.width is not set for <HTMLDivElement object>
```

The code works as expected with the release version 3.4.0.
Thanks!

**Comment by PierreQuentel** [comment]
I'm not sure what you think should be the expected result. In a recent commit I changed it to be more like `style.width`. If it is not set yet, `style.width` is the empty string, and I think it's better to raise an exception (`AttributeError`) in this case than returning the value of `offsetWidth`, which was the case in 3.4.0.

**Comment by Slebi** [comment]
Thank you for this clarification! Now I am unsure how to implement the following scenario:
I have a div-element with a width of 100%. I want to adapt the contents of this element according to its width in pixels. The width in pixel depends on the browser window size. For a small window I want to display a small version of the contents. How can I implement this?

**Comment by Slebi** [comment]
Now I understood your comment. To read back the current width I have to use `offsetWidth`. So the following code works as expected:
```
<html>
	<head>
		<script type="text/javascript" src="/brython/brython.js"></script>
		<!--<script type="text/javascript" src="https://cdn.rawgit.com/brython-dev/brython/3.4.0/www/src/brython.js"></script> -->
  		<script type="text/python">
from browser import document as doc

print("test_div.width: {}".format(doc['test_div'].offsetWidth))
doc['test_div'].width = 400
print("test_div.width: {}".format(doc['test_div'].offsetWidth))
  		</script>

	</head>
	<body onload="brython(1)">
		<div id='test_div' style='border:solid 1px;'>HALLO</div>
	</body>
</html>
```

Maybe the documentation (https://www.brython.info/static_doc/en/attributes.html) should be adapted?
Thank you!
