### ISSUE TITLE
exec() and eval() access globals

### ISSUE THREAD

**Issue by dkosbie** [brython-dev/brython#748]
Code Sample:
```
y = 42
g = { 'x':0 }
exec('print(y)', g) # exec the code using globals defined in g

# Expected: NameError: name 'y' is not defined
# Observed: prints 42
```

Note that exec is using the provided dictionary, as this shows:
```
y = 42
g = { 'x':0, 'y':99 }
exec('print(y)', g) # prints 99, as expected
```

It just seems to fallback on the global namespace, which it seemingly should not.

Thanks.
David

**Comment by dkosbie** [comment]
Also: the same examples above work/fail the same way if you replace 'exec' with 'eval'.  Thx.

David

**Comment by PierreQuentel** [comment]
The code works as expected in the editor, the bug happens in the console.

**Comment by jonathanverner** [comment]
@PierreQuentel For me the code doesn't work in the editor. I.e. the first example prints `42` instead of failing with a `NameError`.

**Comment by PierreQuentel** [comment]
You are right @jonathanverner, I certainly messed up when I tested.

The bugs seems to be fixed, but it might break something else in the console, I haven't found a way to run tests automatically for it (and I never use it myself except when bugs are reported...)
