### ISSUE TITLE
Sorting fails for list of floats

### ISSUE THREAD

**Issue by dkosbie** [brython-dev/brython#753]
Hi all.  Here is a problem:

```
a = [1.0, 1.0, 1.0, 1.0, 1.0, 0.5, 1.0, 0.5, 0.5, 1.0,
     0.5, 0.5, 0.5, 1.0, 0.5, 0.5, 0.5, 0.5, 1.0, 0.5,
     0.5, 0.5, 0.5, 0.5, 1.0, 0.5, 1.0, 0.5, 0.5, 0.5,
     0.6, 1.0]
print(sorted(a))

# Expected: works (prints a sorted version of values in a)
# Observed: Exception: mergeHigh preconditions were not respected
```

It seems to involve floats.  Consider:
```
a = [10, 10, 10, 10, 10,  5, 10,  5,  5, 10,
      5,  5,  5, 10,  5,  5,  5,  5, 10,  5,
      5,  5,  5,  5, 10,  5, 10,  5,  5,  5,
      6, 10]
print(sorted(a)) # this works as expected
```

Thanks.

David

**Comment by jonathanverner** [comment]
There seems to be a problem with the sort implementation (a version of the Timsort algorithm). I will need to go over it and check it, but that will take me a bit of time...

**Comment by dkosbie** [comment]
Thanks.

For now, as a patch, we're converting the floats into ints first, which
seems to avoid the issue, though naturally that's a bit dicey.

I appreciate your help, as always.

David

**Comment by schmave** [comment]
Looks like this is due to an error in the underlying sorting library, which no one has stepped up to fix: 

https://github.com/mziccard/node-timsort/issues/14

I made a quick change to catch assertion failures in timsort and use native JS Array.sort() in those cases. Let me know what you think.

**Comment by PierreQuentel** [comment]
The bug seems to be fixed, I close the issue.
