### ISSUE TITLE
Can brython safely run untrusted code?

### ISSUE THREAD

**Issue by x13machine** [brython-dev/brython#754]
I don't want infinite loops crashing the web page.

**Comment by jonathanverner** [comment]
Unfortunately, there's no way to prevent or detect infinite loops (try googling the 'Halting problem'). 
Also, this is not really an Issue, it is more appropriate for the [mailing list](https://groups.google.com/forum/#!forum/brython) so I will close it. If you have any further questions, please ask them on the list :-)

**Comment by x13machine** [comment]
I mean like if it runs for like 30ms it'll kill the script.

**Comment by jonathanverner** [comment]
Not easily. However, you could try executing the code in a webworker (and set an appropriate CSP policy). Brython has some support for webworkers (see the docs). Anyway, the main difficulties are the same as for running untrusted javascript. The advice given [here](https://www.softfluent.com/blog/dev/Executing-untrusted-JavaScript-code-in-a-browser) applies.
