### ISSUE TITLE
String format problem with classes

### ISSUE THREAD

**Issue by tjnaughton** [brython-dev/brython#755]
Tested using the online console:
```
>>> '{}'.format(int)
```
raises `Exception: spec is undefined`.

An exception is also raised for user defined classes, e.g:
```
>>> class C:
...   pass
... 
>>> print('{}'.format(C))
Traceback (most recent call last):
  module __main__ line 145
    traceback.print_exc()
  module <module> line 1
    print('{}'.format(C))
TypeError: __format__ missing 1 positional argument: 'spec'
>>> 
```

Thanks!

**Comment by PierreQuentel** [comment]
Thanks you for reporting the bug. The commit makes `str(klass)` more compliant with CPython: for built-in classes it is `"<class 'int'>"`, for user-defined classes `"<class '`\_\_main\_\_.C'>"

**Comment by tjnaughton** [comment]
Great, thanks very much!
