### ISSUE TITLE
AnPyLar Launch

### ISSUE THREAD

**Issue by anpylar** [brython-dev/brython#756]
Not an issue ... just wanted the *Brython* community to know that *AnPyLar* (which builds on *Brython*) has launched.

*AnPyLar* is an *Angular-Like* frontend web framework but fully written in Python.

See it at: https://www.anpylar.com

Thx for *Brython*

**Comment by PierreQuentel** [comment]
I am speechless... Congratulations for this work, it can bring more people to think than Python in the browser is now an option. Good luck !

**Comment by auvipy** [comment]
I checked it and looks so promising! I am going to give anpylar a serious try in my personal project

**Comment by anpylar** [comment]
A Playground has been added: https://playground.anpylar.com

**Comment by anpylar** [comment]
This was meant only as an announcement and several days have already gone by. Closing it.

Reopen it as informative if anyone feels it would be of value to keep it visible.
