### ISSUE TITLE
str evaluation shouldn't give precedence to __repr__ instead of __str__ on ancestor

### ISSUE THREAD

**Issue by jurjanpaul** [brython-dev/brython#760]
Given

```
class A(object):
   def __str__(self):
       return "an A"

class B(A):
    def __repr__(self):
       return '<B>()'

b = B()
print(str(b))
```

'\<B>()' is printed by Brython (3.4), where CPython would print 'an A', which is the intended behaviour. This obviously also impacts string formatting and string substitution with instances of B.

**Comment by jurjanpaul** [comment]
Or even simpler (as a test in test/issues.py):
```
class A:
    def __str__(self):
        return 'an A'
class B:
    pass

assert str(B()) == 'an A'
```

**Comment by jurjanpaul** [comment]
I found the implementation of `str`in py_string.js and see that the idea is in there. But for now its details are beyond me still. :-)

**Comment by PierreQuentel** [comment]
Thanks for the report.

The bug was not in __py_string.js__ but in __py_object.js__, more precisely in method `__getattribute__` of Python objects. When resolving `__str__` , if it was missing in one of the parent classes of an object, and this class had a method `__repr__`, the program didn't search a method `__str__` further up in the class parents.

**Comment by jurjanpaul** [comment]
Thanks very much for the fix!

Interesting though to have this fallback implemented in `__getattribute__`. CPython simply raises an AttributeError in case the `__str__` attribute is requested on an object that doesn't have it. 

(I first came to this project with the 'expectation'/hope that everything would work the same as long as no I/O, C-modules or host platform forbidding stuff is involved, so that my existing code would run as-is).

**Comment by PierreQuentel** [comment]
Could you give an example of "_CPython simply raises an AttributeError in case the `__str__` attribute is requested on an object that doesn't have it_" ?

This code
```python
class A:
   def __repr__(self):
       return "an A"

print(A().__str__())
```
prints "an A" with CPython and doesn't raise `AttributeError`, although the class doesn't have `__str__`.

**Comment by jurjanpaul** [comment]
Oops, I'm sorry! My mistake. I got that in a python2.7 shell. :-(
Python3 indeed behaves, for all practical purposes, as it is implemented here.

**Comment by PierreQuentel** [comment]
No problem :-)

In any case, every time Brython doesn't behave like CPython we consider it a bug, except in the few cases mentioned in the [documentation](http://www.brython.info/static_doc/en/syntax.html).
