### ISSUE TITLE
instead of __str__ an object's __repr__ is invoked when passed into a formatting string (when no conversion flag is specified)

### ISSUE THREAD

**Issue by jurjanpaul** [brython-dev/brython#761]
The following fails:
```
class A:
    def __str__(self):
        return 'an A'

assert '{0}'.format(A()) == 'an A'
```

because currently `$ObjectDict.__format__` delegates to `__repr__` instead of `__str__` (which is the CPython default).

**Comment by jurjanpaul** [comment]
If you agree, I would like to provide the patch as a pull request.

**Comment by PierreQuentel** [comment]
I agree :-)
