### ISSUE TITLE
Trailing commas don't raise syntax error

### ISSUE THREAD

**Issue by syl0506** [brython-dev/brython#763]
Trailing commas doesn't raise a syntax error. 

<img width="978" alt="screen shot 2018-01-15 at 1 37 13 pm" src="https://user-images.githubusercontent.com/17005319/34956913-3d14ba3a-f9f9-11e7-93ce-13ecbc0db8d5.png">

Thanks!
Erika

**Comment by PierreQuentel** [comment]
Thanks for the report !
