### ISSUE TITLE
Problem with accessing value of message from websocket

### ISSUE THREAD

**Issue by kajzur** [brython-dev/brython#764]
Hi! I have that code:
```
    def _on_message(self, msg):
        data = msg.data
        print (data)
```

and 

```
    def _on_open(self, evt):
        self.ws.bind('message', self._on_message)
        self.ws.send(self._get_start_message())

    def start_upload(self):
        self.ws = WebSocket(self.url)
        self.ws.bind('open', self._on_open)
```

And when I try access to "data" property in msg variable in _on_message function I have a error:
```

Uncaught Error
    at Object._b_.AttributeError (eval at $make_exc (brython.js:6564), <anonymous>:25:421)
    at Object.$B.$getattr (brython.js:5731)
    at Object._on_message8 (eval at run_py (brython.js:7351), <anonymous>:174:42)
    at WebSocket.instance_method (brython.js:4586)
```

My code is using ofcourse 
`
from browser.websocket import WebSocket
`

Is this a bug or I doing something wrong? I don't have this problem when I mark on_message as @staticmethod and remove "self" argument.
Version: 3.4.0

**Comment by PierreQuentel** [comment]
Hi,

It seems to be the same issue as in this [discussion](https://groups.google.com/forum/?fromgroups=#!topic/brython/RN7Olfn9GJg) on the Google group. Have you tired with the latest development version ?

**Comment by kajzur** [comment]
Not yet - I will try today.

**Comment by PierreQuentel** [comment]
This is an old issue ; I close it hoping that it has been fixed. If no, don't hesitate to reopen it.
