### ISSUE TITLE
library support request: attrs

### ISSUE THREAD

**Issue by glyph** [brython-dev/brython#766]
One of the major reasons that I want to eventually have a python-in-the-browser option is so that I can easily share complex data structures between the frontend and the backend.

Problem: I currently define all my complex data structures with https://github.com/python-attrs/attrs, and brython cannot import this code :).

I think this is a great library to try to get Brython to run unmodified, because it is doing lots of standard Python and platform detection at startup time, and using various standard library modules; yet, it does no I/O, requires no other libraries; it's purely for defining data structures, so it should work just as well in Brython as in CPython.

Just a few things I hit while trying to import it:

- `functools.partial()`
- `sys.version_info`
- `platform.python_implementation()`

None of these things seem hard to implement individually but there are probably a dozen of them before it will import.

Thanks again for brython!

**Comment by PierreQuentel** [comment]
I have started working on this, I found a few bugs that were easy to fix, but there is one which requires a lot of work : when the method `__init__` of a class is reset, the constructor is not modified in the current version of Brython. To fix it, I have to change the way classes are implemented... I hope that I will have finished this week-end.

**Comment by PierreQuentel** [comment]
In branch "rewrite_classes", this code now works correctly: 

```python
import attr

@attr.s
class SomeClass(object):
    a_number = attr.ib(default=42)
    list_of_numbers = attr.ib(default=attr.Factory(list))

    def hard_math(self, another_number):
        return self.a_number + sum(self.list_of_numbers) * another_number


sc = SomeClass(1, [1, 2, 3])
print(SomeClass(a_number=1, list_of_numbers=[1, 2, 3]))

assert sc.hard_math(3) == 19
assert sc == SomeClass(1, [1, 2, 3])
assert sc != SomeClass(2, [3, 2, 1])
```

**Comment by PierreQuentel** [comment]
The code now works on the master branch. @glyph, can you confirm and if so close the issue ?

**Comment by glyph** [comment]
Hi @pierrequintel! Thanks so much for fixing this.  I don’t have a lot of free time these days, but I will test it when I can. Are there any particular instructions for running master I should be aware of? I `pip install brython` everywhere nowadays, so I am not clear on any necessary build steps any more...

**Comment by PierreQuentel** [comment]
@glyph : After you have installed brython and attrs with pip, in a new directory run : 

```
python -m brython --install
python -m brython --add_package attr
```
Then you should be able to run the code above in a Brython-enabled HTML page.

**Comment by glyph** [comment]
It doesn't work.

- When I try it with the released version of Brython, I get
  ```
  [Log] Traceback (most recent call last): (brython.js, line 5070)
  undefined: No module named '__future__'
  [Error] Error
  	callback (brython.js:4259)
  ```
  in a browser
- `pip install -U git+https://github.com/brython-dev/brython.git` fails
- when I do a local checkout of Brython and try `pip install -U ../Brython/setup`, that works, but then I get this:
  ```
  Installing Brython in an empty directory
  Traceback (most recent call last):
    File "/Homebrew/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/Homebrew/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/Users/glyph/.virtualenvs/BryTry/lib/python3.6/site-packages/brython.py", line 81, in <module>
      shutil.copyfile(os.path.join(src_path, path), path)
    File "/Users/glyph/.virtualenvs/BryTry/lib/python3.6/shutil.py", line 120, in copyfile
      with open(src, 'rb') as fsrc:
  FileNotFoundError: [Errno 2] No such file or directory: '/Users/glyph/.virtualenvs/BryTry/lib/python3.6/site-packages/data/demo.html'
  ```

**Comment by PierreQuentel** [comment]
Here is an example of HTML file that works for me : 

```xml
<html>

<head>
<meta charset="utf-8">
<script src="brython.js"></script>
<script src="brython_stdlib.js"></script>
</head>

<body onload="brython(1)">
<script type="text/python">
import attr

@attr.s
class SomeClass(object):
    a_number = attr.ib(default=42)
    list_of_numbers = attr.ib(default=attr.Factory(list))

    def hard_math(self, another_number):
        return self.a_number + sum(self.list_of_numbers) * another_number


sc = SomeClass(1, [1, 2, 3])
print(SomeClass(a_number=1, list_of_numbers=[1, 2, 3]))

assert sc.hard_math(3) == 19
assert sc == SomeClass(1, [1, 2, 3])
assert sc != SomeClass(2, [3, 2, 1])
</script>

</body>

</html>
```
It's possible that you didn't include __brython_stdlib.js__ in your script (if I remove it I also have an error message related to a missing `__future__` module)

**Comment by glyph** [comment]
> Why install from the Git repository, not just with pip install brython ? The master branch is not the latest released version.

I thought you were asking me to test the git version :)

**Comment by glyph** [comment]
> It's possible that you didn't include brython_stdlib.js in your script (if I remove it I also have an error message related to a missing __future__ module)

That is indeed the problem; when I add `brython_stdlib.js`, attrs works fine!

@hynek - time to add brython to attrs' CI? :)
