### ISSUE TITLE
Is it possible to use wasm as the backend?

### ISSUE THREAD

**Issue by exaos** [brython-dev/brython#767]
As [this news](https://blog.mozilla.org/blog/2017/11/13/webassembly-in-browsers/) mentioned, almost all browsers are now shipped with **wasm** (a.k.a., WebAssembly) support. I just guess that the performance of brython may be boosted if it can use something like `py2wasm.js` instead of `py2js.js`.
I am not familiar with wasm and brython both, and now trying to understand them. I will be sorry if this issue brings a noise instead of an idea.

**Comment by nherriot** [comment]
That's a great point. Web assembly should open up the browser to different languages.
You are reducing another layer - so would be nice to see how much this would improve runtimes.

**Comment by jonathanverner** [comment]
Actually, the way Brython is implemented (transpiling to javascript with a similar structure to the original python code --- i.e. a Python class is converted to a Javascript class with some magical methods added) doesn't seem amenable to improvement using wasm... I guess the wasm approach would be much more interesting to the [Batavia](https://pybee.org/project/projects/bridges/batavia/) project (which implements a python bytecode interpretter in javascript) or the [PyPyJs](http://pypyjs.org/) project. I will close this Issue now but thanks for the suggestion and link...
