### ISSUE TITLE
Failed to execute 'send' on 'XMLHttpRequest'

### ISSUE THREAD

**Issue by see01995** [brython-dev/brython#771]
Hi:
I follow the below page to run brython with webview on android:
https://github.com/brython-dev/brython/wiki/Writing-an-Android-application

but it reported:
Traceback (most recent call last):
RuntimeError: NetworkError: Failed to execute 'send' on 'XMLHttpRequest':
Failed to load 'http://www.snic.net/cn/visit_exhibition.php?month=2017-11'.

Related code:
from urllib import request
page = request.urlopen('http://www.snic.net/cn/visit_exhibition.php?month=2017-11')

**Comment by see01995** [comment]
add the following code to fix this issue：
        webview.settings.allowFileAccessFromFileURLs = true
        webview.settings.allowUniversalAccessFromFileURLs = true

**Comment by jonathanverner** [comment]
Thanks for reporting the fix! We'll try to update the documentation, but I will reopen the bug until we do so :-)

**Comment by PierreQuentel** [comment]
I have been trying to run this code with various settings on the `webview` object, but couldn't complete an Ajax call to a site that I know supports cross-origin requests (http://api.open-notify.org/iss-now.json)  from a WebView, although it works like a charm from a basic web page served by a server on localhost. If anyone has a working solution, please report it here.

**Comment by jupiterbjy** [comment]
Still can't open any of links on brython, sadly. Is there any fixes yet?

```python
Brython 3.9.2 on Netscape 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36

>>> from urllib import request
>>> req = request.urlopen("https://www.youtube.com/")
Traceback (most recent call last):
Exception: <Javascript NetworkError>: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://www.youtube.com/'.
>>>
