### ISSUE TITLE
import six fails

### ISSUE THREAD

**Issue by aparamon** [brython-dev/brython#777]
The following minimal script fails for me
```python
import six
print(dir(six))
```
with message
```pytb
Traceback (most recent call last):
  module __main__ line 1
    import six
  module six line 316
    moves = _MovedItems(__name__ + ".moves")
  module six line 127
    super(_LazyModule, self).__init__(name)
TypeError: object() takes no parameters
```
It is expected that module `six` can be imported (or better: implemented in brython_stdlib.js?) because many interesting Python packages depend on it.

**Comment by PierreQuentel** [comment]
Thanks for the suggestion. With this commit, I could run a few basic tests with the `six` module. If you find other bugs, feel free to reopen the issue.

**Comment by aparamon** [comment]
**Thank you for your awesome work, Pierre!**

I've checked and `six` is now imported seemingly fine. However further tests revealed a problem, most likely in `six` module. My test is
```
import urllib3
```
which, after long albeit successful processing of `ipaddress.py`, fails with message
```
Traceback (most recent call last):
AttributeError: '_SixMetaPathImporter' object has no attribute 'find_spec'
```
So far I couldn't come up with a minimal example to reproduce it. `_SixMetaPathImporter` was created to perform some very black magic ;-)

**Comment by aparamon** [comment]
The problem is most likely in the following line:
https://github.com/brython-dev/brython/blob/a688b3452d7977edd6c4f8fcd7127a87438d3324/www/src/py_import_hooks.js#L27
Object `_SixMetaPathImporter` doesn't have `find_spec` attribute indeed, but it was expected that the default `null` from the call above would take effect.
Hmm, I'm having a hard time trying to invent a minimal example. Is it correct that `_SixMetaPathImporter` is getting injected into global import handling system upon `import six`, somehow?

**Comment by aparamon** [comment]
The minimal example is
```python
import six
from six.moves import range
print(range(12))
```

**Comment by PierreQuentel** [comment]
Thanks for reporting again :-)

`_SixMetaImportedPath` doesn't define `find_spec()` and in this case, the import machinery is supposed to search a method `find_module()` which in turn calls a method `load_module()`...

**Comment by aparamon** [comment]
**Thank you for your enormous commitment and great work!**

The last attempt was very close ;-) Another issue discovered: for
```python
import six
print(dir(six.moves))
from six.moves.http_client import *
```
Brython outputs
```pytb
['BaseHTTPServer', 'CGIHTTPServer', 'SimpleHTTPServer', 'StringIO', 'UserDict', 'UserList', 'UserString', '__doc__', '__name__', '_dummy_thread', '_thread', 'builtins', 'cPickle', 'cStringIO', 'configparser', 'copyreg', 'dbm_gnu', 'email_mime_base', 'email_mime_image', 'email_mime_multipart', 'email_mime_nonmultipart', 'email_mime_text', 'filter', 'filterfalse', 'getcwd', 'getcwdb', 'getoutput', 'html_entities', 'html_parser', 'http_client', 'http_cookiejar', 'http_cookies', 'input', 'intern', 'map', 'queue', 'range', 'reduce', 'reload_module', 'reprlib', 'shlex_quote', 'socketserver', 'tkinter', 'tkinter_colorchooser', 'tkinter_commondialog', 'tkinter_constants', 'tkinter_dialog', 'tkinter_dnd', 'tkinter_filedialog', 'tkinter_font', 'tkinter_messagebox', 'tkinter_scrolledtext', 'tkinter_simpledialog', 'tkinter_tix', 'tkinter_tkfiledialog', 'tkinter_tksimpledialog', 'tkinter_ttk', 'urllib', 'urllib_error', 'urllib_parse', 'urllib_robotparser', 'xmlrpc_client', 'xmlrpc_server', 'xrange', 'zip', 'zip_longest']

Traceback (most recent call last):
  module __main__ line 10
    from six.moves.http_client import *
AttributeError: 'NoneType' object has no attribute 'load_module'
```
It's probably not quite easy to fix as `http.client` is missing in Brython, but it would be great if diagnostics were a bit more precise.

BTW, would you consider implementing `httplib` (the client part) someday?
