### ISSUE TITLE
os.listdir() can't work

### ISSUE THREAD

**Issue by see01995** [brython-dev/brython#778]
code：
print('-------')
print(os.getcwd())
print('-------')
print(os.listdir())
print('-------')

log：
/-------
file:///D:/git/Exhibition
/-------
None
/-------

os.listdir() can't work

**Comment by PierreQuentel** [comment]
We are limited by what a browser can and can't do ; in this case, there is no way a browser can list all the files in a directory. `os.listdir()` should raise `NotImplementedError` instead of returning `None`.
