### ISSUE TITLE
  It is recommended to add the loader of the webpack

### ISSUE THREAD

**Issue by githob605608886** [brython-dev/brython#779]
### old using module 
brython.js
```
root=$B.py2js(script.src,script.name,script.name,'__builtins__')
js=root.to_js()
```

### new 
```
root=$B.py2js(script.src,script.name + $B.UUID(),script.name + $B.UUID() ,'__builtins__')
js=root.to_js()
```

# 

Add webpack's Vue loader
```html

<template>
....
</template>

<script lang="brython">
.....
<script>
```

**Comment by PierreQuentel** [comment]
I'm afraid I don't understand what you propose and why you think it's an improvement. Can you elaborate ?

**Comment by PierreQuentel** [comment]
I close the issue, if you can give more information please reopen it.

**Comment by olemis** [comment]
I'll take a look into this since looks like an interesting feature . The thing would be to load a js module from [webpack modules cache](https://github.com/webpack-contrib/cache-loader) and automatically wrap it as a Brython module object , as well as exported fields recursively ...
