### ISSUE TITLE
exec/globals is broken

### ISSUE THREAD

**Issue by aroberge** [brython-dev/brython#782]
In the current development version (3.4.1) there is a bug which appears to be caused by `exec/globals()` being broken.  I found this bug while running the test of the revised turtle module (see #739 which I reopened).  I've attempted to create a test case that reproduces what I observe in the Turtle module; it might be possible to reduce it further.

The code below will take existing methods from a class and make them available as functions.

1. Create the following file in the site-package folder  (I call it greetings.py when running the tests)

```py
class Greetings:
    default = None
    def __init__(self):
        print("Greetings initiated.")
    def hello(self):
        print("Hello!")
    def bonjour(self):
        print("bonjour")

fns = ['hello', 'bonjour']

_func_body = """\
def {name}():
    if {obj} is None:
        {obj} = {init}
    return {obj}.{name}()
"""
def _make_global_funcs(functions, cls, obj, init):
    for methodname in functions:
        def_str = _func_body.format(obj=obj, init=init, name=methodname)
        exec(def_str, globals())

_make_global_funcs(fns, Greetings, 'Greetings.default', 'Greetings()')
```

2. Here's what I get when running the code with CPython (3.6) or Brython 3.4.0 (on reeborg.ca)

```
>>> python
Python 3.6.1 ...
>>> from greetings import *
>>> hello()
Greetings initiated.
Hello!
>>> bonjour()
bonjour
```

3. Here's what I get when running the same code on a local version of Brython 3.4.1, either in the Console or the Editor.
```
Traceback (most recent call last):
  module editor line 100
    traceback.print_exc(file=sys.stderr)
  module <module> line 2
    hello()
  module <module> line 3
    if Greetings.default is None:
NameError: name 'Greetings' is not defined
```

**Comment by aroberge** [comment]
This also does not appear to work with Brython 3.5.0 RC1, but with a different result than that mentioned above.

**Comment by PierreQuentel** [comment]
Fortunately the bug was not in `exec()` (those ones are usually hard to fix...) but related to the attribute name `default`, which is aliased by the Brython engine because it is a reserved word in Javascript.
