### ISSUE TITLE
Documentation links are broken!

### ISSUE THREAD

**Issue by robertpro** [brython-dev/brython#784]
http://brython.info/doc/en/index.html
http://brython.info/doc/es/index.html
http://brython.info/doc/fr/index.html

**Comment by PierreQuentel** [comment]
I don't know where you got these links, but the correct ones are with _static_doc_ instead of _doc_, and there is no _index.html_.
[http://brython.info/static_doc/en/intro.html](http://brython.info/static_doc/en/intro.html)

**Comment by robertpro** [comment]
[README.md](https://github.com/brython-dev/brython/blob/master/README.md) 
Lines: 139, 140 & 141
