### ISSUE TITLE
Missing docs about the editor module

### ISSUE THREAD

**Issue by Grahack** [brython-dev/brython#788]
Hi,
I can't find any information about the `editor` module used [here](http://brython.info/tests/editor.html?lang=en).
I thought there could be a link from [this page](http://brython.info/static_doc/en/intro.html?lang=en), beside the `browser` module. Am I right?

**Comment by aroberge** [comment]
I believe that you are referring to https://github.com/brython-dev/brython/blob/master/www/tests/editor.py which is not part of Brython itself, and is simply a module to make use of the ACE editor (https://ace.c9.io/) for testing.

**Comment by Grahack** [comment]
OK then, I thought it was a reusable module but I'll copy-paste the `editor.py` and tweak it to my needs.
