### ISSUE TITLE
can't import inspect in safari

### ISSUE THREAD

**Issue by mwbmwb** [brython-dev/brython#79]
code:

import inspect

result:
Traceback (most recent call last):
  module importlib line 21
    _bootstrap._setup(sys, _imp)
  module importlib._bootstrap line 1721
    builtin_module = BuiltinImporter.load_module(builtin_name)
  module importlib._bootstrap line 495
    module = fxn(*args, **kwargs)
  module importlib._bootstrap line 508
    module = fxn(self, *args, **kwargs)
  module importlib._bootstrap line 1131
    module = _call_with_frames_removed(_imp.load_dynamic,
AttributeError: 'BuiltinImporter' object has no attribute 'path'
<completed in 1155.00 ms>

**Comment by PierreQuentel** [comment]
This is an old issue that no one commented. I can't test on Safari. I close the issue, but feel free to reopen it if necessary
