### ISSUE TITLE
e.info is corrupted

### ISSUE THREAD

**Issue by vladyslav-savchenko** [brython-dev/brython#790]
Hello,

**First of all, thank you for so beautiful and useful framework! I really like it!**

Making some customization of tracebacks I have found this strange behavior.
I will try to explain it below.

**Right behavior:**
```
>>> something
```

```
Traceback (most recent call last):
  module __main__ line 98
    	_main()
  module __main__ line 74
    	something
NameError: name 'something' is not defined
```

**Wrong behavior (incorrect detected line 76 with "raise" is printed out):**
```
>>> try:
... 	something
... except:
... 	raise
```

```
Traceback (most recent call last):
  module __main__ line 100
    	_main()
  module __main__ line 76
    		raise
NameError: name 'something' is not defined
```

**Wrong behavior (incorrect line 77 with code line is printed out):**
```
>>> try:
... 	something
... except KeyError as e:
... 	pass
... except IndexError as e:
... 	pass
```

```
Traceback (most recent call last):
  module __main__ line 98
    	_main()
  module __main__ line 77
    	except IndexError as e:
NameError: name 'something' is not defined
```

**Wrong behavior (corrupted content of e.info):**
```
>>> try:
... 	something
... except Exception as e:
... 	print('TRACEBACK: {{', e.info, '}}')
```

```
TRACEBACK: {{ Traceback (most recent call last):
  module __main__ line 95
    	_main()
  module __main__ line 76
    		print('TRACEBACK: {{', e.info, '}}') }}
```

I think the content of `e.$stack` is somehow corrupted.

**Comment by PierreQuentel** [comment]
Thanks for the compliment, and for the report :-)

The commit referenced above gives a more correct result, but I realize that the attribute `info` should not exist... I will have to fix this later.
