### ISSUE TITLE
Potential bug in 3.5.0rc1

### ISSUE THREAD

**Issue by aroberge** [brython-dev/brython#792]
I've tried the release candidate with my code and it fails on some of my automated tests. 

Running a single test "by hand", I see that Brython fails with the following message:
```
pas de py_src pour common
brython.js:6422 

TypeError: Cannot read property 'split' of undefined
    at Object.$B.exception (http://localhost:8700/offline/brython/brython.js:6423:32)
    at Object.$B.is_exc (http://localhost:8700/offline/brython/brython.js:6445:8)
```
which occurs in the brython source at
```
if($B.$py_src[mod_name]===undefined){console.log('pas de py_src pour '+mod_name)
console.log(js_exc)}
var lines=$B.$py_src[mod_name].split('\n'),msg=js_exc.message.toString()
...
```

I suspect that `common` refers to my `common.py` module which I use to invoke Brython's `exec` to have it translate some Python code into Javascript and then execute it. https://github.com/aroberge/reeborg/blob/master/src/python/common.py#L219

I do not understand the logic of having a test to see if py_src is undefined (and log in the console) immediately followed by asking to split py_src - which is guaranteed to fail when py_src is undefined.

**Comment by PierreQuentel** [comment]
It's true, the message (in French...) was there for debugging and I forgot to remove it when I found why the value was sometimes undefined.

In a recent commit I replaced this piece of code. Can you try with the latest version ?

**Comment by aroberge** [comment]
I have downloaded the latest version of brython.js and brython_stdlib.js and I still have over 40 errors when I run my integration tests. However, if I run some of the seemingly problematic examples as a normal user, everything seems to be fine.  So, it will likely take more work of my part to figure out what is the cause of the errors.  I see four types of errors, all dealing with exceptions.  They might very well be all related.

To recap the context: I run some simple Python **or** Javascript programs to make a virtual robot move. The underlying layer is written in Javascript. The end of the execution is **always** signaled by an exception/error, which I then interpret as either a successful completion or as a problem (either a Python error, such as SyntaxError, or as a problem like the robot running into a wall). If it is a Python error, I attempt to do a simple error analysis to give a simplified error message to the user (translating some information into French, for example). 

I've tried to run some diagnostic code and I found something that might perhaps give a clue as to what has changed in Brython and how I can fix my code.

Other than Python errors (SyntaxErrors, IndentationErrors, etc.), errors are first raised in the Javascript layer.

Here's a simplified version of a typical Javascript Error that could be raised, where I do not show the human language choices, and only show the English version.

```js
RUR.ReeborgError = function (message) {
    if (test_to_see_if_python_is_used ){
        try {
            return ReeborgError_en(message);
        } catch (e) {
            // IMPORTANT: this try/catch was introduce as early diagnostic and left, but ignored
           // as it never seems to occur ... except NOW.
         }
    }
    this.name = "ReeborgError";
    this.message = message;
    this.reeborg_shouts = message;
};
```

And here is what the Python exception code looks like

```py
class ReeborgError(Exception):
    def __init__(self, message):
        self.reeborg_shouts = message
        self.message = message
        super().__init__(message)

    def __str__(self):
        return self.reeborg_shouts
window['ReeborgError_en'] = ReeborgError     # similar code for the French version ...
```

Now, in the try/catch code above, I see the following error message
```
TypeError: ReeborgError_en is not a function
```

I do need to run some more tests ...

**Comment by aroberge** [comment]
Correction to previous report: when I was running single tests by hand, I was mistakenly using the "old" version ... if I use the RC, I see the errors.  I will investigate further to try to narrow down what is going on.

**Comment by aroberge** [comment]
I have created a "minimal" working example in a separate repository.  By "minimal" I mean the shortest code that I could come with which both reproduces the error I see **and** which uses the rather convoluted logic I use in my own site  (including creating a separate global namespace), when I support running user programs written using either Python or Javascript.  I have done so in an attempt to ensure that any solution that would fix the problems on this "minimal" version would also carry over for my own case.

The repository is https://github.com/aroberge/shared_tests

To try the different Brython version, you need to edit the html file and replace 3.3.4 by 3.5.
With the 3.5 version, some diagnostic code is logged in the browser console.

**Comment by aroberge** [comment]
In the previously mentioned repository, I have added an even simpler example, where I do not attempt to reproduce everything that is in my code.  I suspect that, if this simpler example is fixed, the other one will be as well.

**Comment by PierreQuentel** [comment]
Once again, many thanks for the very clear explanations and examples. I think I see what is going wrong.

In your Javascript code, you create an exception from the Python class `MyException_en` by

```javascript
return window.MyException_en(message);
```

This worked in the previous versions because the Javascript object that represents a Python class was a function. In version 3.5 it is an object such that, to call it, you must use the global function `__BRYTHON__.$call` : 

```javascript
return __BRYTHON__.$call(window.MyException_en)(message);
```

With this change I could run both examples in the repository.

**Comment by aroberge** [comment]
This **almost** works for me.  I've updated the file minimal_test_brython3.5rc1.html in my test repository to illustrate what doesn't work.  

In my program, I use the exception name (either for my custom exception, or for the standard Python exceptions) to inform the student about the problem with their code.
![image](https://user-images.githubusercontent.com/629698/36934359-a62314ce-1ebe-11e8-87b9-be5849ed1ca0.png)
, 

If you try the revised example, with Brython 3.3.4, you will see that `MyException` is correctly extracted. However, with Brython 3.5, what is shown is `BaseException`. 

The field where `create_exception()` appears is editable. If I attempt to run a program with a SyntaxError or a NameError, it is properly identified by Brython 3.5; it is only my own created exceptions whose name is incorrectly identified.

I could modify my exceptions to add another custom attribute that I could use for my own exceptions. However, this would not work for programs written by users who wish to explore how to use exceptions in Python.

**Comment by aroberge** [comment]
I have added a second example in the file minimal_test_brython3.5rc1.html which shows that it is only when I pass the information to the Javascript layer and analyze it there that the problem occurs with the name identification. This is likely all that is needed for the users of my site.

While I would prefer to have a way to easily get the original exception name, I am quite sure that I can find a workaround and can deal with the new behavior, since my use of Brython is definitely not typical.

If you want to close this issue, that would be fine with me.  Of course, if you have some suggestions to offer as to how I should deal with this problem without adding another custom attribute, I would gladly consider them.

**Comment by PierreQuentel** [comment]
I have tested the updated examples.

When I click "Exec Python" I get this on the document : 
```
BaseException: Happily creating an exception
```

With the "Second example" button I get : 
```
Ok, MyOtherException caught
Ok, MyException caught
```
Do you get the same result ? I have tested with 3.5.0rc1 on rawgit and with the current development version.

**Comment by aroberge** [comment]
Yes, I do get the same result with Brython 3.5.  However, the first one
(Exec Python), with Brython 3.3.4 gives

MyException: Happily creating an exception.

So, the exception name propagates correctly with Brython 3.3.4 but not with
Brython 3.5.0rc1.  But I can live with that as I have an idea for
implementing a work around.

**Comment by aroberge** [comment]
Ok, I found a workaround to recover the exception name, and implemented it in my test repo.  Closing the issue.

**Comment by PierreQuentel** [comment]
To get the exception name you used `e.__name__`, which should raise an `AttributeError` (I will fix this) ; it should be `e.__class__.__name__`
