### ISSUE TITLE
set |= other does not update inplace

### ISSUE THREAD

**Issue by zed** [brython-dev/brython#797]
```python
>>> def update(set_, other):
...     set_ |= other
... 
>>> a, b = {1, 2}, {2, 3}
>>> update(a, b)
>>> a
set({1, 2})
```

but the expected result:

```python
>>> a |= b
>>> a
set({1, 2, 3})
```

Calling [`set.update`](https://docs.python.org/3/library/stdtypes.html#frozenset.update) directly works:
```python
>>> a, b = {1, 2}, {2, 3}
>>> def update_update(set_, other):
...     set_.update(other)
... 
>>> update_update(a, b)
>>> a
set({1, 2, 3})
```

**Comment by zed** [comment]
I see there are no inplace versions of operators (such as `set.__ior__`, `set.__iand__`) in [`py_set.js`](https://github.com/brython-dev/brython/blob/f51804c2e79acc54dddfe356965170e439ce0d12/www/src/py_set.js) e.g., the intersection op also fails:

```python
>>> a, b = {1,2},{2,3}
>>> def intersection_update(a, b):
...     a &= b
... 
>>> intersection_update(a, b)
>>> a
set({1, 2})  # XXX fail: should be {2}
>>> a & b
set({2})
>>> a &= b
>>> a
set({2})
```

**Comment by jonathanverner** [comment]
This shouldn't be too hard to fix if anyone wants to get his feet wet in Brython development. As mentioned by @zed, we need to implement the "inplace" operators in [py_set.js](https://github.com/brython-dev/brython/blob/f51804c2e79acc54dddfe356965170e439ce0d12/www/src/py_set.js) and add some tests to the testsuite at [test_set.js](https://github.com/brython-dev/brython/blob/f51804c2e79acc54dddfe356965170e439ce0d12/www/tests/test_set.py). The implementation should not be hard as it can use the already existing methods of set (e.g. update, ...) Unfortunately, I currently don't have the time to fix this :-(

**Comment by PierreQuentel** [comment]
Many thanks @zed for the report and the fix.

There is still a slight difference with the expected behavior ; according to the specification of set, _the non-operator versions of union(), intersection(), difference(), and symmetric_difference(), issubset(), and issuperset() methods will accept any iterable as an argument. In contrast, their operator based counterparts require their arguments to be sets_

So, with CPython : 
```
>>> s = {1, 2}
>>>
>>> s &= range(6)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for &=: 'set' and 'range'
```
and in current version of Brython : 
```
Brython 3.5.0 on Netscape 5.0 (Windows)
>>> s = {1, 2}
>>> s &= range(6)
>>> s
{1, 2}
```

Can you fix this issue ?

**Comment by zed** [comment]
My mistake. I should have mentioned the difference explicitly. I blame wishful thinking on my part. I prefer the behavior consistent with how `list` behaves:
```python
>>> L = [1]
>>> L + range(2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can only concatenate list (not "range") to list
can only concatenate list (not "range") to list
>>> L += range(2)  # no TypeError, equivalent to L.extend(range(2))
>>> L
[1, 0, 1]
```

The current Python behavior for sets is inconsistent with how `list` behaves:

```python
>>> S = {1}
>>> S | range(2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for |: 'set' and 'range'
unsupported operand type(s) for |: 'set' and 'range'
>>> S |= range(2)  # XXX inconsistent!
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for |=: 'set' and 'range'
unsupported operand type(s) for |=: 'set' and 'range'
>>> S |= set(range(2))
>>> S
{0, 1}
```

Here's a [possible fix (enforce CPython behavior)](https://github.com/zed/brython/commit/2929b6a7d4d47d2206038aaec56a532a879653cb) (I don't know how well it fits with the rest of the brython code).
