### ISSUE TITLE
How to load module from external file that on different path/server?

### ISSUE THREAD

**Issue by jcubic** [brython-dev/brython#800]
I've ask this question on StackOverflow [How to import python library from url in Brython])https://stackoverflow.com/questions/46789547/how-to-import-python-library-from-url-in-brython/49387627?noredirect=1#comment85854916_49387627) in mean time I've found that StringIO in python 3 and in Brython is in in io module but just in case I will need to import another module (maybe my own) I want to know how to do this.

**Comment by PierreQuentel** [comment]
I think that the [new feature](https://groups.google.com/forum/?fromgroups=#!topic/brython/EfBUmkrdgXA) introduced in 3.7.5 answers the question, so I close this issue.
