### ISSUE TITLE
Crash (Page lock) with simple script 

### ISSUE THREAD

**Issue by andrewdove1** [brython-dev/brython#803]
I am new to brython and also python. All the examples I tried work fine but when I tried my own dynamically loaded script  the page locked up and brython is in an infinite loop.

Here is my page

<!DOCTYPE html>
<html lang="en">
<head>
    <script type='text/javascript' src='./dist/ThirdParty/jquery-1.11.1.min.js'></script>
    <script src="Brython-3.5.0/brython.js"></script>
    <script src="Brython-3.5.0/brython_stdlib.js"></script>
    <script src='test1.js' type='text/javascript'></script>
</head>
<body onload='brython()'>
    <textarea id="pyinput"></textarea>
    <button id="mybutton">Run it</button>
</body>
</html>

Here is my script

function run_python(src){
    // dynamically create an invisible DIV with type="text/python3"
    var py_script = document.createElement('div');
    py_script.id = 'id1';
    py_script.style.visibility = 'hidden';
    py_script.type = 'text/python3';
    // set DIV content to Python source code
    py_script.textContent = src;
    document.body.appendChild(py_script);
    // run brython(), searching Python code in DIV tags
    brython({debug:10,ipy_id:['id1']});
    // clean up
    document.body.removeChild(py_script);
}

$(document).ready(function () {
    $('#mybutton').on('click', function () {
        var text = $('#pyinput').val();
        run_python(text);
    });
});

When I type the following into pyinput
print('hello world')

then click the 'Run it' button brython goes into an infinite loop in the following (formatted) code (around line 3031)

            var search_ids = ['"' + innermost.id + '"']
            var gs = innermost
            while (true) {
                if (gs.parent_block) {
                    if (gs.parent_block.id == "__builtins__") {
                        break
                    }
                    gs = gs.parent_block
                }
                search_ids.push('"' + gs.id + '"')
            }

gs.parent_block is undefined so the loop never terminates

Since I am new I assume I am giving brython invalid input and any advice on the correct input would be appreciated. However, I would not expect such simple input to cause this problem.

(if it helps I am using the latest chrome browser, 64 bit 65.0.3325.162

**Comment by jonathanverner** [comment]
Actually, you shouldn't put your Python code into `<div>` tags but into `<script>` tags! I suspect that what happens is that Brython is stuck in an infinite loop trying to find a (nonexistent)  `<script>` tag with the given id. See if changing the `<div>` to a `<script>` helps. 

On the other hand I think this probably also counts as a bug in Brython (it should handle the case when it can't find the code gracefully)...

**Comment by andrewdove1** [comment]
I changed the div tag to a script tag and got the same result.

I originally got my idea from this post
https://groups.google.com/forum/#!msg/brython/xLv55qq-L1s/mcwmI6-pEhcJ
with slight changes to use the actual documented API.

**Comment by jonathanverner** [comment]
Unfortunately, that post is quite dated... Anyway, when I have the time I'll try to look at your code and see whether I can find what the problem is, but I probably won't be able to do that before this weekend. :-(

**Comment by PierreQuentel** [comment]
This was terrible... The bug didn't happen if you removed the `ipy_id` key in the arguments of `brython()` (it is intended for use inside a IPython/Jupyter notebook) but it was not a reason to make the browser enter an infinite loop.
