### ISSUE TITLE
TypeError: create_module() takes 2 positional arguments but more were given

### ISSUE THREAD

**Issue by netice** [brython-dev/brython#807]
Hello

I have written my own import hook in brython 3.5.0 bellow
and received wrong arguments from brython
that cause
TypeError: create_module() takes 2 positional arguments but more were given

```python
###################################
class DDERPHook(object):

    @classmethod
    def create_module(self, spec):
        return _new_module(spec)
###################################
```

I added a debug to check the arguments and found that

```python
###################################
class DDERPHook(object):

    @classmethod
    def create_module(self, spec, *args, **kwargs):
        console.debug(['create_module:', self, spec, args, kwargs])
        return _new_module(spec)
###################################
```
brython send two self to the method create_module (self, self, spec)

   
`
`

**Comment by netice** [comment]
the same import hook code work in brython 3.4.1

**Comment by netice** [comment]
this issues is in 
py_import_hooks.js
which pass another "_loader" to the arguments
```javascript
                                                                                                                                               
 61     // Create module object                                                                                                                     
 62     if(!$B.is_none(_loader)){                                                                                                                    63         var create_module = _b_.getattr(_loader, "create_module", _b_.None)                                                                     
 64         if(!$B.is_none(create_module)){                                                                                                         
 65             module = $B.$call(create_module)(_loader, spec)                                                                                   
 66         }                                                                                                                                                
```
line 65 must be fix to
'''javascript
 module = $B.$call(create_module)(spec)
```

**Comment by jonathanverner** [comment]
Thanks for reporting this and figuring out what is wrong!! Can you make a pull-request? If not, I'll try to look at it later this week and implement your fix.

**Comment by netice** [comment]
Sorry I don't have the right to push the fix.

**Comment by Lonami** [comment]
@netice you can also edit the file from within GitHub. Go to the file and click the "edit" button. It will fork and make a pull request for you (unless this was fixed already).

**Comment by PierreQuentel** [comment]
Thanks for reporting and finding the fix. I didn't test if it solves the problem you mention; if it doesn't please reopen the issue.
