### ISSUE TITLE
random.gammavariate(alpha,beta) fails when alpha=1

### ISSUE THREAD

**Issue by DavidCBailey** [brython-dev/brython#809]
random.gammavariate(alpha,beta) works fine for alpha≠1, but fails for alpha=1 because of a typo in random.js.

For example, If I run (at https://www.brython.info/tests/editor.html) 
```
from random import gammavariate
print(gammavariate(1.1,2))
print(gammavariate(0.9,2))
print(gammavariate(1.0,2))
```
the output I get is
```
1.982739603544254
3.6407850919446485
TypeError: undefined is not an object (evaluating 'self.__class__.__name__')
```
The bug is in line 452 of random.js (https://github.com/brython-dev/brython/blob/master/www/src/libs/random.js)
```
450:     }else if(alpha == 1.0){
451:        // expovariate(1)
452:        var u = _random()
453:        while(u <= 1e-7){u = self._random()}
454:        return -Math.log(u) * beta
```
Line 452 should be
```
452:        var u =self._random()
```
I fixed this in my local  brython_stdlib.js, but don't currently have enough familiarity with git to easily submit this fix myself to github.

**Comment by Lonami** [comment]
Click the "fork" button on this repository, then `git clone` the project. Make the changes, `git commit -a`, and then `git push`. From your repository, click "make pull request". You can also click the edit button from within this repository if you can do it from GitHub.

**Comment by jonathanverner** [comment]
@Lonami thanks for writing up instructions :-)

**Comment by PierreQuentel** [comment]
Thanks for the report and the fix :-)
