### ISSUE TITLE
Obsolete documentation page still available

### ISSUE THREAD

**Issue by aroberge** [brython-dev/brython#81]
The address
http://www.brython.info/doc/tutorial/en/src/brython_doc.html
(note the "www") points to a really old, static version of the documentation.

**Comment by juancarlospaco** [comment]
I cant reproduce, I cant Generate or find THAT obsolete file..., 
maybe it went missing from an old Build/Deploy on the Web Server, 
I think that @PierreQuentel is the only one that can check it on Prod Server.

**Comment by aroberge** [comment]
I just clicked on the link again and found that it leads me to an obsolete file.  It is not something that is part of the repository - but seems to be left over from some older configuration of the webserver.

**Comment by PierreQuentel** [comment]
It's a page that was removed from the distribution long ago, but that I didn't erase on the brython.info site

Can't we just leave it, for nostalgia ?

**Comment by kikocorreoso** [comment]
@aroberge Me too.

@PierreQuentel I think you are who have access to that.

**Comment by aroberge** [comment]
My suggestion, if you want to keep it (and I can understand why), would be to perhaps change the name of the file (original_brython_doc.html perhaps) - not simply relying on the extra www to hide it.

**Comment by PierreQuentel** [comment]
The folder doc/tutorial is deleted
