### ISSUE TITLE
Problems with unquote from urllib

### ISSUE THREAD

**Issue by AZweifels** [brython-dev/brython#810]
Nice work with brython! I started using it for executing python code in a small web app. However, I noticed some strange behaviour when unquoting urls:
`from urllib.parse import unquote
print(unquote('foo%20bar'))`
Result:
`foor`

Tested locally as well as with the console [1].
[1] http://brython.info/tests/console.html?lang=en

**Comment by PierreQuentel** [comment]
Thanks for the report. The bug was in the hash of bytes objects.
