### ISSUE TITLE
if __mul__ fails, __rmul__ not being used

### ISSUE THREAD

**Issue by andy31lewis** [brython-dev/brython#813]
Hi
When running this bit of code:
```python
class Point(object):
    def __init__(self, coords):
        self.coords = coords

    def __str__(self):
        return str(tuple(self.coords))

    def __mul__(self, other):
        if type(other) in [list, tuple]:
            return Point([xi*yi for (xi, yi) in zip(self.coords, other)]) 
        else:
            return NotImplemented

    def __rmul__(self, other):
        if type(other) in [list, tuple]:
            return Point([xi*yi for (xi, yi) in zip(self.coords, other)]) 
        else:
            return NotImplemented

P = Point((3,4))
print (P*[-2, 3])
print ([-2, 3]*P)
```
CPython prints (-6, 12) in both cases.  The second time, it finds that a list doesn't know how to multiply a Point, so it tries to right-multiply the Point by the list, using Point's __rmul__ method.
Brython does the first print correctly, but for the second one it gives:
TypeError: can't multiply sequence by non-int of type 'Point'
ie it gives up without trying the right-multiplication.

Thanks!

Andy

**Comment by PierreQuentel** [comment]
Thank you Andy !
