### ISSUE TITLE
Impossible to import urlencode from urllib.parse in brython_modules mode

### ISSUE THREAD

**Issue by benjaminrigaud** [brython-dev/brython#817]
When using brython_modules.js

`from urllib.parse import urlencode` doesn't work
`import urllib.parse as urlparse; urlparse.urlencode` works

**Comment by PierreQuentel** [comment]
Merci beaucoup :-)

I have had very few reports with the use of brython_modules.js, this is very helpful ! I think the bug is fixed, but of course you can reopen the issue if it's not the case.
