### ISSUE TITLE
Boolean attribute of subclass of DIV class cannot be initialised to False

### ISSUE THREAD

**Issue by andy31lewis** [brython-dev/brython#821]
See this code:
```python
from browser import document, html

class A(html.DIV):
    def __init__(self, mybool):
        #html.DIV.__init__(self, "Test")
        #document["main"] <= self
        self.mybool = mybool

x= A(True)
print (x.mybool)
x.mybool = False
print (x.mybool)

y = A(False)
print (y.mybool)
```
Output:
```
True
False
Traceback (most recent call last):
  module <module> line 15
    print (y.mybool)
AttributeError: 'A' object has no attribute 'mybool'
```
If the attribute is initialised to True, all is as expected. And it can be subsequently changed to False with no problem.  But if we try to initialse it to False, it seems to vanish.

(It makes no difference whether or not the object has been added to the document - there is no change if the commented lines are included.  It also makes no difference which html (or svg) object it is - I tried with P, BUTTON, svg.circle as well.)

Thanks as always,
Andy

**Comment by PierreQuentel** [comment]
I have removed the code that caused this bug, but it's been written so long ago that I don't remember why it was there...
