### ISSUE TITLE
javascript.JSConstructor & JSObject deprecation

### ISSUE THREAD

**Issue by benjaminrigaud** [brython-dev/brython#822]
When importing JSConstructor from javascript I get a console warning:

`"javascript.JSConstructor" is deprecrated. Please refer to the documentation.`

I couldn't find anything in the documentation, Is there something newer I should use?

In addition, are we able to subclass a Javascript class?

```python
from javascript import JSConstructor

BaseClass = JSConstructor(window.Something)
class MyClass(BaseClass):
   pass
```

It fails with an `
"Object passed as base class is not a class"`

Ben

**Comment by jonathanverner** [comment]
I think that JSConstructor is not needed anymore. You should simply be able to do:

```python
    from browser import window

    s = window.Something()
```

(though I am not perfectly sure, would need @PierreQuentel to confirm)

Subclassing a Javascript class is currently not supported. Its not clear what the semantics should be, but it would be cool if we were able to devise something...

**Comment by benjaminrigaud** [comment]
Thank you :)

`my_class = window.something.new` looks like the way to go?

**Comment by PierreQuentel** [comment]
Merci @benjaminrigaud !

`JSObject` and `JSConstructor` have been deprecated for so long that I have removed their description in the document a few months ago (commit a9c399d) ; in the commit referenced above I have changed the deprecation message.

They can be replaced this way : 
```python
# old school
from browser import window
from javascript import JSObject, JSConstructor

ls = JSObject(window.localStorage)
ls.setItem("color", "blue")
regexp = JSConstructor(window.RegExp)
re = regexp("^<a (.*=>$")
```

```python
# up to date
from browser import window

ls = window.localStorage
ls.setItem("color", "blue")
regexp = window.RegExp.new
re = regexp("^<a (.*)>$")
```
Of course, in both cases you have to know if the Javascript object is a constructor or any other object ; there is no way to guess if a Javascript function is a constructor (like `RegExp`) or a function (like `Math`).

I leave the issue open for the second part of your question: is it possible to subclass a Javascript constructor ?

**Comment by PierreQuentel** [comment]
@benjaminrigaud 

With the commits referenced above, the example below works: 
```xml
<script>
function klass(x){
    this.x = x

    this.add = function(y){
        return this.x + y
    }
}
</script>

<script id="ascript" type="text/python">
from browser import window

JSClass = window.klass

class A(JSClass):
    pass

a = A(5)
assert a.x == 5
assert a.add(7) == 12
</script>
```
I am pretty sure that inheritance from a Javascript constructor would not work as expected in some cases, but it this enough to close the issue ?

**Comment by benjaminrigaud** [comment]
@PierreQuentel : It looks really nice.

I don't have time to test it yet : I'll open issues if required :)

Thank you.
