### ISSUE TITLE
Problems with the case of attributes of subclasses of HTML or SVG elements

### ISSUE THREAD

**Issue by andy31lewis** [brython-dev/brython#829]
Hi again
It took me a while to figure out why some of my attributes were working fine, and others not...
Firstly when subclassing from HTML elements:
```python
from browser import document, svg, html

class A(html.DIV):
    def __init__(self):
        self.uV = 5
        self.Xyz = "mystring"

p = A()
print (p.XYZ)
print (p.xyz)
print (p.Xyz)
print (p.uV)
print (p.uv)
```
Output:
```
mystring
mystring
mystring
5
Traceback (most recent call last):
  module <module> line 13
    print (p.uv)
AttributeError: 'A' object has no attribute 'uv'
```
A numeric attribute is case sensitive as expected, but a string attribute is case insensitive.

Now when subclassing from SVG elements:
```python
from browser import document, html, svg

class B(svg.circle):
    def __init__(self):
        self.uV = 6
        self.Xyz = "anotherstring"

q = B()
print (q.uV)
print (q.xyz)
print (q.Xyz)
```
Output:
```
6
anotherstring
Traceback (most recent call last):
  module <module> line 11
    print (q.Xyz)
AttributeError: 'B' object has no attribute 'Xyz'
```
Again numeric attributes work as expected, but this time string attributes must be referred to as all lower case, no matter how they were defined.

Thanks again,
Andy

**Comment by andy31lewis** [comment]
@PierreQuentel 
Ah, that's interesting, I didn't know that. I assumed the Python case-sensitivity would apply.  So in the first example, p.uv should not fail?
Thanks for responding.

**Comment by andy31lewis** [comment]
Thank you, Pierre.  Now the SVG attributes work as expected (case-sensitive).

For the HTML attributes, Xyz="mystring" is still case-insensitive as before.  But now uV=5, even if defined as mixed-case, has to be referred to as lower case:
```python
class A(html.DIV):
    def __init__(self):
        self.uV = 5

p = A()
print (p.uv)
print (p.uV)
```
gives
```
5
brython.js:5287:49
Traceback (most recent call last):
  module __main__ line 9
    print (p.uV)
AttributeError: 'A' object has no attribute 'uV'
```

By the way, do you think the case-insensitivity of attributes of HTML classes should be mentioned in the documentation?  Something like (on the browser.html page):
[After "In the following link you can find the index of HTML tags with references (DRAFT)"]. "Note that attributes of these classes, and any classes subclassed from them, will be case-insensitive as per the HTML specification.  This applied whether they are HTML attributes such as src or user-defined attributes.  One exception is Class (see below)."

**Comment by PierreQuentel** [comment]
Even after the latest commit, there is something wrong with the management of DOM element. Currently it is a mix between the standard DOM method `setAttribute()` / `getAttribute` (which sets case-insensitive attributes for HTML elements and case-sensitive attributes for SVG attributes) and the standard Javascript attribute management with `element.attr = value` or `value = element.attr`, which is always case-sensitive.

What makes things more complicated is that for some attributes (eg `id`), setting the Javascript attribute also sets the HTML element attribute, and for others (eg `style`) the Javascript attribute (`element.style`) refers to the tag attribute `style`...

I propose to change the current implementation : 
- `elt.key = value` will be limited to standard attribute setting of Python objects (case-sensitive)
- introduce a dict-like attribute `attr` to DOMNode instances, to manage DOM elements attributes ; the attributes will be case-insensitive for HTML and case-sensitive for SVG

For instance, setting an arbitrary HTML attribute would be
```python
element.attr["abc"] = value
assert element.attr["aBc"] == value # case-insensitive
element.attr["foo"] # raises KeyError
```
and setting an attribute to the Python object
```
element.uV = 5 # case-sensitive
assert element.uV == 5
element.uv # raises AttributeError
```

**Comment by andy31lewis** [comment]
Wow, that would be quite a big change!  I'm sorry, I didn't mean my bug report to generate such a lot of work for you.  I have just made a rule for myself: "for HTML elements, only use lowercase attributes" which seems to get round any problems and work for me.
So, if I understand you correctly, this would work something like:

```python
from browser import document, svg, html

class A(html.DIV):
    def __init__(self):
        html.DIV.__init__(self, title="mydiv", style={"color":"blue"})
        self.Xyz = "mystring"

p = A()
assert p.xyz == "mystring" #Fails, Python attribute is case sensitive
assert p.title == "mydiv" #Fails, title is an HTML attribute not a Python one
assert p.attr["Title"] == "mydiv" #Succeeds since HTML attribute is case insensitive
p.attr["ID"] = "divID" #Succeeds
assert p.attr["id"] == "divID" #Succeeds
p.attr["uV"] = 5 #Fails, no HTML attribute called uV
p.uV = 5 #Succeeds, can create arbitrary Python attributes
assert p.attr["style"]["color"] == "blue" #Succeeds
#I'm guessing this is what the syntax would be since attr and style are both dictionaries?
p.attr["style"]["backgroundColor"] = "yellow" #Succeeds
#Still using Javascript-style CSS attributes I assume?

class B(svg.circle):
    def __init__(self):
        svg.circle.__init__(self, cx=100, cy=50, r=40, stroke_width=5)
        self.uV = 5

q =B()
assert q.uV == 5 #Succeeds
assert q.cx == 100 #Fails, cx is an svg attribute
assert q.attr["cX"] == 100 #Fails, svg attribute is case sensitive
q.attr["stroke"] = "blue" #Succeeds
q.attr["ID"] = "circleID" #Fails this time since id is now an XML attribute and therefore case-sensitive?
q.ID = "circleID" #Succeeds since this is creating a Python attribute
q.id = "circleID" #Fails, can't have a Python attribute with the same name as an svg one?
# Or maybe you can? (Even if it would be a bad idea!)
```
Is that what you are intending?  Of course, this would not be backward-compatible so would mean users rewriting their code.  But if you think the current situation requires this change, better to do it sooner rather than later to minimise the amount of code which needs rewriting.

**Comment by andy31lewis** [comment]
Thinking some more about this, are you sure such a big change is really necessary? After all, no-one else has raised the current behaviour as an issue, only me. :worried: And I am quite happy with my self-imposed rule: "for HTML classes, and subclasses of them, only use lower case attributes".  Maybe you could just add something like that to the documentation.  Much less work for you, and for Brython users who wouldn't have to rewrite their code.  That would be my suggestion.

**Comment by PierreQuentel** [comment]
I am trying several solutions, based on a clear distinction between a DOM element _attributes_ (those initialized inside a tag : `<input value="foo">`, or set by the DOM method `element.setAttribute(key, value)`) and _properties_ (set by the DOM / Javascript syntax `element.attr = value`).

In the current state of the repository:
- `elt.x = value` sets the property
- `value = elt.x` reads the property
- `elt.attrs["x"] = value` sets the attribute
- `value = elt.attrs["x"]` reads the attribute

Properties are always case-sensitive ; attributes are case-insensitive for HTML elements and insensitive for SVG elements.

Attribute values are always strings ; property values can be any Python type.

To set `stoke` or `stoke-width` :
```python
elt.attrs["stroke"] = "blue"
elts.attrs["stroke-width"] = 2
```

This would replace the previous syntax:
```python
elt.stoke = "blue"
elt.stroke_width = 2
```

Those would still be valid (ie wouldn't raise exceptions) but would have no effect on the element. Maybe for some current attribute names a deprecation message could be sent.

Would that be ok ?

**Comment by andy31lewis** [comment]
@PierreQuentel 
Hi Pierre
To be honest, I am not totally clear about the distinction you are making.  For example,
```html
<img id="myimg1" style="width:200px" />
<script type="text/javascript">
    myimg1 = document.getElementById("myimg1")
    myimg1.src = "hues.png"
</script>
```
has the same effect as
```html
<img id="myimg2" src="hues.png" style="width:200px" />
```
even though in one case src is set by Javascript syntax, and in the other inside a tag.

Are you saying that one would use a different syntax within a Brython script to read or change the src attribute, depending on how it was originally set?  And what if one were going to set it *for the first time* from within a Brython script.

To be honest, I rather regret raising this issue in the first place - it is making a lot of work for you, and I am not sure that the proposed solution will be an improvement on the current implementation (3.5.1); the issues with that can be avoided by making sure that all attributes of HTML and SVG classes are lower-case. (I would be guided by the old colloquialism "If it ain't broke, don't fix it." :smile:)

**Comment by andy31lewis** [comment]
@PierreQuentel 
Hi again
I have been testing using the following files, which include both HTML and SVG elements created both in the HTML and by Brython, and HTML, SVG and CSS attributes set by stylesheet, by tag, by Javascript and by Brython (so trying to cover all the possible cases):
```html
<html>
<head>
    <meta charset="utf-8">
    <title>Brython Test</title>
    <link rel="stylesheet" href="test.css" type="text/css" />
    <!--
    <script src="https://cdn.rawgit.com/brython-dev/brython/3.5.1/www/src/brython.js"></script>    
    <script src="https://cdn.rawgit.com/brython-dev/brython/3.5.1/www/src/brython_stdlib.js"></script>
    -->
    <script src="https://cdn.rawgit.com/brython-dev/brython/master/www/src/brython.js"></script>    
    <script src="https://cdn.rawgit.com/brython-dev/brython/master/www/src/brython_stdlib.js"></script>
    <script type="text/python" src="test.py"></script>
    
    <style>
    div.myclass1 {
        float: left;
        position:relative;
        height: 400px;
        width:300px;
    }
    </style>
</head>

<body onLoad="brython(1)">
    <div id="div1" class="myclass1" style="background-color:cyan;">
    </div>
    <div id="div3" style="background-color:cyan;">
        <script type="text/javascript">
            div3 = document.getElementById("div3")
            div3.className = "myclass1"
        </script>
        <img id="myimg1" style="width:200px" />
        <img id="myimg2" src="BlueDisc.png" style="width:200px" />
    </div>
    <svg xmlns="http://www.w3.org/2000/svg" id="svg1" width="500" height="400" style="background-color:purple;"></svg>
</body>
</html>
```
and 
```python
from browser import window, document, svg, html

div2 = html.DIV("My DIV!", id="div2", style={"position":"absolute", "left":50, "top":60, "width":100, "height":30, "backgroundColor":"pink"})
document["div1"] <= div2

svg2 = svg.rect(x=40, y=70, width=120, height=20,  fill="blue", stroke_width=5)
document["svg1"] <= svg2

div1 = document["div1"]
div3 = document["div3"]
print (div1.Class)
print (div3.Class)
div1.style.width = 400
div1.xyz = "mystring"
print (div1.xyz)

div2.top += 50
div2.style.color = "green"
div2.xyz = 99
print (div2.xyz)

img1 = document["myimg1"]
img1.src = "hues.png"
img2 = document["myimg2"]
img2.src = "RedDisc.png"

svg1 = document["svg1"]
svg1.width = 600
svg1.style.backgroundColor = "yellow"
svg1.xyz = 999
print (svg1.xyz)

svg2.stroke = "red"
svg2.stroke_width = 10
svg2.xyz = "mystring"
print (svg2.xyz)
```
All works perfectly using Brython 3.5.1

Using the current master, ```print (div1.Class)``` does not work (it returns ```<bound method DIV.Class of <HTMLDivElement object>```. And ```print (div3.Class)``` has the same result, even though that class name was set by Javascript.  However, ```print (div1.className)``` works in both cases, and also works in 3.5.1 in both cases, so perhaps that is the preferable syntax.

Using current master, ```img2.src = "RedDisc.png"``` works (even though according to your explanation above it shouldn't :confused:). And so does ```img1.src = "hues.png"``` (this src is being set for the first time).

Your new syntax also works in these cases (eg ```print(div3.attrs["class"])``` or ```img1.attrs["src"] = hues.png```, but doesn't actually seem to be needed.

When we come to SVG, the case is different. ```svg2.stroke = "red"``` and ```svg2.stroke_width = 10``` do not fail, but (unlike in 3.5.1 where they worked perfectly) they do not have any effect on the drawing.  However, the new syntax ```svg2.attrs["stroke"] = "red"``` (setting stroke for the first time) and ```svg2.attrs["stroke-width"] = 10``` (changing the previous value) work perfectly.

Meanwhile the user-defined attributes (Xyz etc) are now case sensitive as in Python, for both HTML and SVG elements.

So congratulations, it seems that you have achieved something that works.  Also that if you decide to adopt the new syntax, I (and other users) will need to go though our projects rewriting code that uses SVG attributes, but not HTML attributes since for those both the old and the new syntax seem to work.  In my case that will not take too long, and it will be worth it if the new implementation you have introduced is cleaner and easier for you to maintain.

Sorry this such a long post, but I hope it is of some help and encouragement.

Andy
