### ISSUE TITLE
copy module fails on objects (v3.5.1)

### ISSUE THREAD

**Issue by mostlytigerproof** [brython-dev/brython#833]
Brython doesn't seem to like copying objects. e.g.
```
import copy

class Hello:
  pass

inst = Hello()
copy.copy(inst)
Error: un(shallow)copyable object of type <class '__main__.Hello'>

copy.deepcopy(inst)
Error: un(deep)copyable object of type <class '__main__.Hello'>
```

Ran the same stuff at the REPL in CPython 3.4.3 and it seems happy enough.

**Comment by PierreQuentel** [comment]
Commit 00d1bf2e40181febff101e1c4b89086d72f29c66 has fixed this issue. Thanks, and sorry for the very late fix...
