### ISSUE TITLE
Wrong error for an unbound local

### ISSUE THREAD

**Issue by schmave** [brython-dev/brython#836]
This test should pass but it does not:

```python
def f():
    if False:
        a = 1
    else:
        print(a)

assertRaises(UnboundLocalError, f)
```

Looks like the issue is that there is no `$B.$check_def_local` call being generated for `a` in `print(a)`. The code is quite complicated, though, so I couldn't come up with any easy fix.

**Comment by PierreQuentel** [comment]
Thanks for reporting this ; it shows that there is a serious problem with name resolution... The commit referenced above is a first step but as you say, the code is complex, so it might take a few days before the issue is fixed.

**Comment by schmave** [comment]
Thanks for looking into this and thanks for the update!

**Comment by PierreQuentel** [comment]
I reopen the issue, this code fails to throw an exception
```python
def f():
    if False:
        x = 0
    print(x)
f()
```
