### ISSUE TITLE
Type of "random" module is not right

### ISSUE THREAD

**Issue by schmave** [brython-dev/brython#838]
```python
import random
assert not isinstance(random, int)
```

I would expect this test to pass, as it does for the modules `os`, `sys`, and `math`. Instead, there is an exception thrown in the runtime:

```
Cannot read property 'length' of undefined
    at isinstance (py_builtin_functions.js:1093)
```

My line numbers may be off by one or two... this is the line in `isinstance` that gets run with `mro==undefined`:
```js
    for(var i = 0; i < mro.length; i++){
```

**Comment by PierreQuentel** [comment]
I have fixed the bug in the commit referenced above, by making sure that the imported modules written in Javascript (which is the case for `random`) have the class of modules. This fix replaces the one you proposed in PR #842 (cf my comment on this PR)
