### ISSUE TITLE
id() and "is" operators are inconsistent for long integers

### ISSUE THREAD

**Issue by schmave** [brython-dev/brython#840]
Test that fails but should succeed:
```python
x = 123 ** 20
y = 123 ** 20
assert (id(x) != id(y) or x is y)  # if id(x) == id(y), then (x is y) must be True
```
I think that removing the special case for ints & floats in `id()` (py_builtin_functions.js) so that they are handled the same way as other objects will fix this.

Loosely related: #669.

**Comment by jonathanverner** [comment]
@schmave at one point I tried working on a more compliant implementation of id for numbers, but then got sidetracked and I wasn't able to finish it... The work I did was trying to port the implementation of hashing from the standard library. You can find it in the [fix_hash_unittests](https://github.com/jonathanverner/brython/tree/fix_hash_unittests) branch of my Brython clone if you'd like to work on this and wanted some inspiration :-)

**Comment by schmave** [comment]
Interesting! This isn't my highest priority item right now but I will take a look at your stuff when I get around to it.

**Comment by schmave** [comment]
Thanks, Pierre!
