### ISSUE TITLE
Exponential increase in run time for format statement with 

### ISSUE THREAD

**Issue by mrwwalmsley** [brython-dev/brython#86]
print("{} abcdefghijklmnopqrstuvw {}".format("10", "20"))

Try this example. For every extra letter you add to the end of the big word in the middle the run time doubles... that's some crazy exponential algorithm.

Numbered parameters works fine:
     
    print("{0} abcdefghijklmnopqrstuvwxyz {1}".format("10", "20"))

**Comment by mrwwalmsley** [comment]
I think I have created the pull request right this time around with the single character addition.

**Comment by JamesHutchison** [comment]
My understanding is that this issue can be closed?

**Comment by mrwwalmsley** [comment]
assuming the pull request came through... yes. I have certainly fixed it in
my local version

On 14 January 2015 at 20:19, JamesHutchison <notifications@github.com>
wrote:

> My understanding is that this issue can be closed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brython-dev/brython/issues/86#issuecomment-69895769>.
>



-- 
Mike Walmsley
Creator of...

Learn to code, change the world!
Fun effective learning @ *codeavengers.com* <http://codeavengers.com/>

*twitter* <https://twitter.com/CodeAvengers>* | **facebook
<http://facebook.com/CodeAvengers>** | google +
<https://plus.google.com/105827980034533177298>*

**Comment by earney** [comment]
anyone opposed to closing this issue? (I believe it has been resolved).

**Comment by mrwwalmsley** [comment]
sure

On 9 February 2015 at 13:58, Billy Earney <notifications@github.com> wrote:

> anyone opposed to closing this issue? (I believe it has been resolved).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brython-dev/brython/issues/86#issuecomment-73443994>.
>



-- 
Mike Walmsley
Creator of...

Learn to code, change the world!
Fun effective learning @ *codeavengers.com* <http://codeavengers.com/>

*twitter* <https://twitter.com/CodeAvengers>* | **facebook
<http://facebook.com/CodeAvengers>** | google +
<https://plus.google.com/105827980034533177298>*
