### ISSUE TITLE
Problems using AJAX to upload files

### ISSUE THREAD

**Issue by andy31lewis** [brython-dev/brython#861]
Hi again
First of all, I'm not sure to what extent these issues are because there is something I don't understand, or whether they really are bugs.  So I'm going to give a fairly full example before I get to the point - sorry if it is long!

First, here is the minimal HTML:
```html
    <form>
        <input id="choosefiles" type="file" multiple="multiple" />
    </form>
    <button id="upload">Upload</button>
```
and CGI script on the server:
```python
import cgi
form = cgi.FieldStorage()
f = form["filetosave"]
g = open("uploads/"+f.filename, "w")
g.write(f.file.read())
g.close()
```
Now I have a javascript script which works perfectly with the above to upload files:
```javascript
var fileInput = document.getElementById('choosefiles');
var uploadButton = document.getElementById('upload');
var uploadFile;

uploadButton.addEventListener('click', function (event) {
  for (var i = 0; i < fileInput.files.length; i++) {
    uploadFile(fileInput.files[i]);
  };
});

uploadFile = function (file) {
  var formData = new FormData();
  formData.append('filetosave', file, file.name);

  var request = new XMLHttpRequest();
  request.open("POST", 'savefile.cgi');
 //request.setRequestHeader('content-type', "multipart/form-data")
  request.send(formData);
};
```
However, if I uncomment the setRequestheader line, I get an error from the server:
"Invalid boundary in multipart form"
This is expected, because the content-type header should not be set when using FormData, eg see the accepted answer here:
https://stackoverflow.com/questions/5392344/sending-multipart-formdata-with-jquery-ajax
"It’s imperative that you set the contentType option to false, forcing jQuery **not** to add a Content-Type header for you, otherwise, the boundary string will be missing from it."
Furthermore, it seems that once a header has been set, according to the [spec](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/setRequestHeader) it cannot be removed, eg see:
https://stackoverflow.com/questions/2464192/how-to-remove-http-specific-headers-in-javascript

I can emulate the javascript in Brython, which also works perfectly:
```python
def uploadfile(f):
    formdata = window.FormData.new()
    formdata.append('filetosave', f, f.name)
    
    req = window.XMLHttpRequest.new()
    req.open('POST',"savefile.cgi",True)
    req.send(formdata)

def uploadfiles(event):
    for f in document["choosefiles"].files:
        uploadfile(f)
```
However, the Brython Ajax documentation suggests I should be able to write:
```python
def uploadfile2(f):
    req = ajax.ajax()
    req.open('POST',"savefile.cgi",True)
    req.set_header('content-type', "multipart/form-data") #Flag to make Brython use FormData
    req.send({'filetosave':f})

def uploadfiles(event):
    for f in document["choosefiles"].elt.files:
        uploadfile(f)
```
I run into 3 problems with this:
1) Using ```.elt.files``` instead of just ```.files``` gives an AttributeError.  Is that just a typo in the documentation?
2) Because the ```content-type``` has been set, the server responds with the "Invalid boundary in multipart form" error as detailed above.
3) If I bypass setting the content-type (by kludging my local Brython installation), the server responds that ```f.filename = None```, because (peeking into the Brython code) the filename has not been set using the third parameter of ```FormData.append()```

I hope that all makes sense and I am not wasting your time here.

Thanks

Andy

**Comment by PierreQuentel** [comment]
@jonathanverner 

Can you take a look at this issue when you have time ? I think it's you who added the documentation on method `send()` of Ajax objects, and it doesn't seem to work as explained.

In any case, setting the Content-Type header for multipart/form-data [requires to specify a boundary](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type), for instance
```
req.set_header('content-type', "multipart/form-data;boundary=myownspecialboundary20180609")
```
otherwise you get the "Invalid boundary" error message.

**Comment by PierreQuentel** [comment]
The function added in the commit referenced above should make file upload easier. It is described in the documentation of __`browser.ajax`__.
