### ISSUE TITLE
name resolution error in recursive generator

### ISSUE THREAD

**Issue by TheWindX** [brython-dev/brython#866]
it is a more complicated test case of #865，recursive generator...
```
reg = None

def g():
    x = 'hello from here'
        
    def y():
        print(x)
        yield 0
        
    global reg    
    reg = y
    
    yield 0


gins = g()
next(gins)

next(reg())
```
###############
Traceback (most recent call last):
  module Panda line 
    next(reg())
  module Panda line 
    print(x)
NameError: free variable 'x' referenced before assignment in enclosing scope

**Comment by PierreQuentel** [comment]
Thanks again ! The commit also fixes this : 
```python
reg = None

def g():
    x = 'hello 3'
        
    def y():
        yield x
        
    global reg    
    reg = y
    
    yield 0


gins = g()
next(gins)

assert next(reg()) == "hello 3"
```

**Comment by TheWindX** [comment]
really appreciate your great work
