### ISSUE TITLE
The sum of two numbers is <object TagSum> [object Object][object Object]

### ISSUE THREAD

**Issue by Razlagutt** [brython-dev/brython#867]
Hello! I'm trying to develop a simple calculator with Brython and I can't get a valid sum result.
My html.
```html
<!DOCTYPE html>
<html>

<head>
  <link rel="stylesheet" href="theme.css">
  <script type="text/javascript" src="brython.js"></script>
  <script type="text/javascript" src="brython_stdlib.js"></script>
</head>

<body onload="brython()" >
  <script type="text/python" src="/scripts.py"></script>
  <form class="form-inline justify-content-center">
    <div class="input-group my-1">
      <input type="text" class="form-control mr-3 my-1" placeholder="First num" id="num1">
      <input type="text" class="form-control mr-3 my-1" placeholder="Second num" id="num2">
      <input type="text" class="form-control mr-3 my-1" placeholder="Result" id="res" value=""> 
</div>
    <a id="sum" class="btn btn-secondary">Sum</a>
  </form>
</body>
````
My scripts.py
```python
from browser import document


def sum(ev):
    num1 = document['num1']
    num2 = document['num2']
    sum = f'{num1 + num2}'
    document['res'].value = sum

document['sum'].bind('click', sum)
```
Where did I make a mistake?

**Comment by PierreQuentel** [comment]
`document['num1']` and `document['num2']` are references to DOMNode instances ; you can add such instances, but it gives you an instance of the internal class `TagSum`.

You should use their property `value` (just as you use it to set the value of `document['res']`), and convert it into an integer to be able to add the values.

```python
def sum(ev):
    num1 = int(document['num1'].value)
    num2 = int(document['num2'].value)
    sum = f'{num1 + num2}'
    document['res'].value = sum
```

You should even wrap the first two lines in a `try... except..` block in case the user enters a value that can't be converted to an integer.

You should also avoid giving functions and variables the name of Python built-in functions like `sum()`. In fact, defining a variable is not necessary here:

```python
def sum_values(ev):
    num1 = int(document['num1'].value)
    num2 = int(document['num2'].value)
    document['res'].value = num1 + num2
```

Also note that converting the result into a string by `f'{num1 + num2}'` is not necessary : the value given to `element.value` is always converted into a string.

**Comment by Razlagutt** [comment]
Hello! I found an error:
```python
    num1 = document['num1'] #must be num1 = int(document['num1'].value)
    num2 = document['num2'] #must be num2 = int(document['num2'].value)
```

**Comment by Razlagutt** [comment]
Thank you very much!
