### ISSUE TITLE
Can't call __iadd__ on member variable

### ISSUE THREAD

**Issue by schmave** [brython-dev/brython#869]
```python
class A(object):
    def __init__(self):
        self.value = 0
        
    def __iadd__(self, val):
        self.value += val

class B(object):
    def __init__(self):
        self.a = A()

b = B()
b.a += 10
assert b.a == 10
```

A JS exception is raised on the line `b.a += 10` because the generated code assigns to the result of a function call. The bug was introduced in commit 1f883910a589a2e2d161819f8367ad6b89c6a3e9.

**Comment by PierreQuentel** [comment]
The test doesn't pass with CPython either (method `__iadd__` should return `self.value`) ; and with this change, I don't think it has ever worked with any Brython version.

Thanks again for all the reports :-)
