### ISSUE TITLE
string formatting performance

### ISSUE THREAD

**Issue by JamesHutchison** [brython-dev/brython#87]
String formatting is a little sluggish, and using the + operator is significantly faster than using a formatter. I wouldn't expect it to take half a second to format a thousand strings.

```
import time
def str_a():
    start = time.time()
    for _ in range(1000):
        a = "%s_%s" % ("hi", "there")
    end = time.time()
    print(end - start)

def str_b():
    start = time.time()
    for _ in range(1000):
        a = "hi" + "_" + "there"
    end = time.time()
    print(end - start)

str_a()
0.44900012016296387

str_b()
0.012000083923339844
```

**Comment by JamesHutchison** [comment]
I'll see if I can take a crack at this tonight

**Comment by JamesHutchison** [comment]
Also, in the process of writing the rewrite I discovered that string padding doesn't work, so I'll fix that while I'm at it.

**Comment by JamesHutchison** [comment]
Looks like a significant portion of the performance cost is in the tuple creation. I'll make a separate issue for this

**Comment by JamesHutchison** [comment]
Just to give an update on this - have gotten made a bit of progress and have more than half of the formatters fully implemented. Performance has held up with initial results. Getting this done with unit tests before the end of the week is realistic.

**Comment by kikocorreoso** [comment]
:+1: :smile: 

I was working on implementing the old style string formatting ('%s' % (string)) but I'd prefer to wait until you finnish to see if it is necessary to continue working on it.

**Comment by JamesHutchison** [comment]
Not going to lie, the %g formatting was a real pain. This refactor has the side benefit of fixing several bugs.

**Comment by JamesHutchison** [comment]
Ok, got a pull request in that doesn't wipe out files... Git can frustrating at times...
