### ISSUE TITLE
Which scripts to use for building?

### ISSUE THREAD

**Issue by niccokunzmann** [brython-dev/brython#877]
While working on #876, I wanted to merge. This results in conflicts in the build files e.g. `brython.js`.
Thus, I would like to rebuild these files.
But: It does not work.
`scripts/make_dist.py` has errors
`manage.py dist make_dist` has the same error:
`sources = MANIFEST['sources']['core']`
There is only `MANIFEST['sources']['base']`

Which script files should I use, which files can I correct to work?

**Comment by PierreQuentel** [comment]
I think we can fix this issue.
