### ISSUE TITLE
brython does not load library scripts if there are url parameters that are themselves urls

### ISSUE THREAD

**Issue by andrewdove1** [brython-dev/brython#879]
I have a url of the form

https://somesite.com/page.html?someparam=http://10.10.10.10&otherparam=true

Obviously made-up but the important part is that one of the url params is itself a url
This causes brython to try to load a some.py file from 

https://somesite.com/page.html?someparam=http:/some.js

which in my case returns the html page and then brython chokes on it

I debugged the issue and it appears to be that when constructing $script_dir in  brython_builtins.js line 34 it uses window.location.href which contains all the params and then parses it as if there are none
When I changed this line to use window.location.origin+window.location.pathname things started working for me. Alternatively split on ? and take the first part only.

**Comment by PierreQuentel** [comment]
Thanks for the report and for the solution :-)
