### ISSUE TITLE
geattr cannot resolve from __proto__

### ISSUE THREAD

**Issue by stefanhoelzl** [brython-dev/brython#880]
I am trying to work with [Vue.js](http://www.vuejs.org) using Brython ([vue.py](https://github.com/stefanhoelzl/vue.py)).

And I ran into some trouble when having some list object.
See in this [jsfiddle](https://jsfiddle.net/c1dakgu7/)

On [getattr](https://github.com/brython-dev/brython/blob/c78b80775de9bef0ae696878184c69ae27ebe462/www/src/py_builtin_functions.js#L746) it raises an AttributeError because it cannot find the `push` attribute of the `todos` list (called in the `created`-hook of the Vue-Instance).

Changing this [line](https://github.com/brython-dev/brython/blob/c78b80775de9bef0ae696878184c69ae27ebe462/www/src/py_builtin_functions.js#L787) to:
```javascript
if(attr in obj){
```
would solve the problem

Another solution I found would change this [line](https://github.com/brython-dev/brython/blob/c78b80775de9bef0ae696878184c69ae27ebe462/www/src/py_utils.js#L166) to
```javascript
if(Object.getPrototypeOf(obj).__proto__ === Array.prototype)
```
(certainly would break other things)

Since I am not experienced with Javascript nor with brython I am not sure if one of this two solutions is a good solution.

**Comment by stefanhoelzl** [comment]
I tried my first proposed solution, and it solved the AttributeError.
A new item was pushed onto the list.

But another problem appeared:
The dict passed as an argument to the `todos.push()`-method was not parsed right and the newly added list item does not show any text.

**Comment by stefanhoelzl** [comment]
hey, thanks for getting onto this so quickly!

But there are still some problems. It only works in the `created`-hook of Vue.js but not when used in a [method](https://jsfiddle.net/hf2mLjz6/4)

Vue also wraps more than only the `push`-method ([Vue.js Array Change Detection](https://vuejs.org/v2/guide/list.html#Mutation-Methods))

**Comment by PierreQuentel** [comment]
Thank you for reporting the bugs!

The commit referenced above fixes the example in your second message. I had to dig into the vue.js code to realize that my previous fix was wrong : if the Javascript array (attribute `todos`) is converted into a Python list, using method `append()` on this object will not trigger the Vue objects' "watcher" engine.

I have updated the __test_vue.html__ page in the gallery with your examples. I don't close the issue in case your find other bugs.

**Comment by stefanhoelzl** [comment]
Thanks!
Looks good so far!

**Comment by stefanhoelzl** [comment]
tested also the other array-method (push, pop, shift, unshift...) and everything worked fine!

Thanks again, for fixing everything so fast!

**Comment by PierreQuentel** [comment]
Cool ! Can we close the issue ?

**Comment by stefanhoelzl** [comment]
yes, i think we are good to close it
