### ISSUE TITLE
misleading error message when multiply float with dict

### ISSUE THREAD

**Issue by stefanhoelzl** [brython-dev/brython#890]
when I multiply a float with a dict `1.5*{}` I expect the same exception as in CPython
`TypeError: unsupported operand type(s) for *: 'float' and 'dict'`

but with Brython I get
`RuntimeError: ReferenceError: Can't find variable: bool`

This is misleading, and I think it hides another bug inside Brython.

**Comment by schmave** [comment]
When I run `1.5 * {}` at https://brython.info/tests/ and with the latest master branch, it gives the expected exception. Maybe there is more to your code that triggers it?

**Comment by stefanhoelzl** [comment]
ah ok, sorry haven't checkt the latest on master
was working with 34d9698afe922e3b0c802c9dab6128e256a8346c
seems that after this were some changes and it is already fixed

Thanks!
