### ISSUE TITLE
splatting by star/asterisk doesn't seem to be supported

### ISSUE THREAD

**Issue by sakurai-youhei** [brython-dev/brython#896]
Hello,

I'm just newbie of brython but, because I found code that results differently from CPython, I'm opening this issue for those who'd be interested.

Thank you.

**Steps to reproduce**

1. Open [demo console](https://brython.info/tests/console.html).
2. Run following code.

```python
[*range(10)]
{*range(10)}
```

**Current result as of in 2018-07-26**

```
>>> [*range(10)]
[range(0, 10)]
>>> {*range(10)}

SyntaxError: invalid syntax

 module <string> line 1
  {*range(10)}
   ^
```

**Expected result (on CPython 3.7)**

```
>>> [*range(10)]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
>>> {*range(10)}
{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}
```

**Comment by PierreQuentel** [comment]
@sakurai-youhei 
Welcome to Brython :-) and thank you for reporting this.

These examples don't work on the version currently on line at brython.info, but additional unpacking generalisation (PEP 448) was introduced in commit 2b9d4120fdbacd5b48a9a6615214d41711bc1a46.
I will publish a major new release (3.7.0) in the next days and update brython.info.

I close the issue, feel free to re-open it, or another one, if you still see bugs when the new release is on line.
