### ISSUE TITLE
+= on lists 

### ISSUE THREAD

**Issue by tiggerntatie** [brython-dev/brython#897]
I see: 
Brython 3.6.0 on Netscape 5.0 (X11; CrOS x86_64 10718.63.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.76 Safari/537.36
>>> a = [1]
>>> a += [2]

Exception: TypeError: Cannot read property 'replace' of undefined

I expect to see:
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> a = [1]
>>> a += [2]
>>> a
[1, 2]

**Comment by PierreQuentel** [comment]
@tiggerntatie 
This is true (and scary...) for 3.6.0, but not in the current development version after the many commits I made today. I don't know which commit fixed the bug... Can you confirm that it works ?

**Comment by tiggerntatie** [comment]
I can confirm that it appears to be OK in the development version. Thank you!
