### ISSUE TITLE
Web worker failures

### ISSUE THREAD

**Issue by butscher** [brython-dev/brython#898]
When trying to run a script which starts a web worker using the Brython release files (version 3.6.2) Brython tries to load the file "web_workers/worker.js" (relative to web site file location).

When using the Brython source files, it loads lots of these files, then does nothing more, last web console entry is "ReferenceError: window is not defined" in "py2js.js". Probably it tries to retrieve `window` inside the web worker which fails naturally.

Used browser is Firefox 56.0b9 32bit on Windows 7 Pro 64bit.

**Comment by schmave** [comment]
I made a pull request with some changes I had in my local branch to fix webworker issues I encountered. I'd like to add a test for them in CI so I was hanging on to them, but I guess it's better to fix the bug now and add tests later. Hope it's helpful.

**Comment by butscher** [comment]
Thank you. Unfortunately this now ends up with

`TypeError: self.__BRYTHON__._load_scripts is not a function` at `worker.js:78:5`

**Comment by Pokechu22** [comment]
I've ran into this in the past and I have an old commit that fixes it locally.  I'm currently working on rebasing it (some of the things in it were also fixed in #899, but there are also some things that weren't) and I'll submit a PR once I've got everything working.

**Comment by PierreQuentel** [comment]
I tried solving this issue and found that the current implementation of web workers is difficult to understand. I have posted a [message on the Google Group](https://groups.google.com/forum/?fromgroups=#!topic/brython/CckNrH5kIfM) to present a new implementation. If you can take a look and tell me what you think, it would be helpful.
