### ISSUE TITLE
__base__ is missing

### ISSUE THREAD

**Issue by stefanhoelzl** [brython-dev/brython#904]
CPython classes have the attribute __base__
```python
class A:
    pass
print(A.__base__)
```

In Brython this argument is missing. It is raising
```bash
AttributeError: 'A' object has no attribute '__base__'
```

**Comment by stefanhoelzl** [comment]
I also noticed, that `object.__bases__` behaves differently to CPython.
In Brython direct subclasses of `object` contain `object` in there `__bases__` tuple, in Brython the do not.

Python
```python
>>> class A: pass
>>> A.__bases__
(<class 'object'>,)
```

Brython
```python
>>> class A: pass
>>> A.__bases__
()
```

**Comment by PierreQuentel** [comment]
I have fixed the missing `object` in `A.__bases__`, but `__base__` is not documented and in [this issue](https://bugs.python.org/issue22456) Guido says that it's CPython-specific, so I don't think it's useful to add it to Brython. I guess it's always the same as `A.__bases__[0]`.
