### ISSUE TITLE
UUID module

### ISSUE THREAD

**Issue by JamesHutchison** [brython-dev/brython#91]
Not yet implemented? The GUID functionality (`uuid.uuid4()`) is in particular quite useful.

https://docs.python.org/3/library/uuid.html

Not sure if all of these can be implemented in javascript (and I wouldn't implement it unless it can be done properly), but uuid4 does look possible. Here's a completely unreadable but optimized version:

```
var lut = []; for (var i=0; i<256; i++) { lut[i] = (i<16?'0':'')+(i).toString(16); }
function e7()
{
  var d0 = Math.random()*0xffffffff|0;
  var d1 = Math.random()*0xffffffff|0;
  var d2 = Math.random()*0xffffffff|0;
  var d3 = Math.random()*0xffffffff|0;
  return lut[d0&0xff]+lut[d0>>8&0xff]+lut[d0>>16&0xff]+lut[d0>>24&0xff]+'-'+
    lut[d1&0xff]+lut[d1>>8&0xff]+'-'+lut[d1>>16&0x0f|0x40]+lut[d1>>24&0xff]+'-'+
    lut[d2&0x3f|0x80]+lut[d2>>8&0xff]+'-'+lut[d2>>16&0xff]+lut[d2>>24&0xff]+
    lut[d3&0xff]+lut[d3>>8&0xff]+lut[d3>>16&0xff]+lut[d3>>24&0xff];
}
```

source:

http://stackoverflow.com/questions/105034/create-guid-uuid-in-javascript#answer-21963136

We can raise a `NotImplementedError` for the functions that can't be done in javascript.

**Comment by earney** [comment]
I have the basic module somewhat importing.  This is waiting on Pierre's long integer implementation, which he just stated in an email today, that a long integer implementation is what he is working on.
