### ISSUE TITLE
problem with native style['property'] and style.setProperty(property, value)

### ISSUE THREAD

**Issue by frederickavita** [brython-dev/brython#910]
Hi brython give me this error with native function javascript
  document.body.style['background-color'] = "blue"

Traceback (most recent call last):
  module __main__ line 81, in hiding
    document.body.style['background-color'] = "blue"
AttributeError: 'CSSProperty' object has no attribute '__setitem__' brython.js:5571:49

document.body.style.setProperty("background-color", "blue")
TypeError: "'setProperty' called on an object that does not implement interface CSSStyleDeclaration."

**Comment by PierreQuentel** [comment]
Merci Frédéric !

Usually, style attributes are set using the dotted syntax : 
```python
document.body.style.backgroundColor = "blue"
```
but the commit referenced above also allows the syntax in your example.

The second example with `setProperty` was a bug, it should be fixed by this commit.
