### ISSUE TITLE
re.compile problem

### ISSUE THREAD

**Issue by frederickavita** [brython-dev/brython#912]
in python : 
>>> import re
>>> pattern = re.compile(
...     r'^(:?(([a-zA-Z]{1})|([a-zA-Z]{1}[a-zA-Z]{1})|'  # domain pt.1
...     r'([a-zA-Z]{1}[0-9]{1})|([0-9]{1}[a-zA-Z]{1})|'  # domain pt.2
...     r'([a-zA-Z0-9][-_a-zA-Z0-9]{0,61}[a-zA-Z0-9]))\.)+'  # domain pt.3
...     r'([a-zA-Z]{2,13}|(xn--[a-zA-Z0-9]{2,30}))$'  # TLD
... )
>>> pattern.match("example.com")
<_sre.SRE_Match object; span=(0, 11), match='example.com'>

with brython:
import _jsre as re
>>> pattern = re.compile(
...     r'^(:?(([a-zA-Z]{1})|([a-zA-Z]{1}[a-zA-Z]{1})|'  # domain pt.1
...     r'([a-zA-Z]{1}[0-9]{1})|([0-9]{1}[a-zA-Z]{1})|'  # domain pt.2
...     r'([a-zA-Z0-9][-_a-zA-Z0-9]{0,61}[a-zA-Z0-9]))\.)+'  # domain pt.3
...     r'([a-zA-Z]{2,13}|(xn--[a-zA-Z0-9]{2,30}))$'  # TLD
... )

>>> pattern.match("example.com")
>>>> None

**Comment by PierreQuentel** [comment]
Salut Frédéric,

Your example works if you replace `import _jsre as re` by `import re`.

The _jsre module is provided as an alternative to the standard re module ; since it's written in Javascript it should be faster, but it doesn't cover the whole syntax of the re module (cf issue #901).
