### ISSUE TITLE
Can't import multiprocessing

### ISSUE THREAD

**Issue by chezyann** [brython-dev/brython#913]
Got an error on :
import multiprocessing

Find attach the console log
[127.0.0.1-1534375343462.log](https://github.com/brython-dev/brython/files/2291988/127.0.0.1-1534375343462.log)

PS : I also tried on your website's editor https://brython.info/tests/editor.html
which leads to :
```
ImportError: No module named _queue
Traceback (most recent call last):
  module lambda5 line 2, in <lambda>
    from browser import html
  module editor line 112, in run
    exec(src, ns)
  module <module> line 1
    import multiprocessing
  module multiprocessing line 40
    from multiprocessing.util import SUBDEBUG,SUBWARNING
  module multiprocessing.util line 18
    from subprocess import _args_from_interpreter_flags
  module subprocess line 140
    import select
  module select line 13
    import queue
  module queue line 16
    from _queue import Empty
```

**Comment by PierreQuentel** [comment]
Thanks for reporting this issue. It should be fixed now, but don't expect the module to do anything useful, multiprocessing is not relevant in the browser context.

**Comment by chezyann** [comment]
Thank you very much. I was just looking for a way to simulate some distributed system but I don't care if processes are iteratively executed.

**Comment by bor8** [comment]
If you'll let me get in here: I get a very similar error when importing irc.client.

Before this error occurs, I must enter `touch jaraco/__ini__.py`, otherwise another error occurs.

Now my real question: Can irc or irc.client (version 16.4) work with Brython at all?
