### ISSUE TITLE
Weird behavior of globals and locals in exec function

### ISSUE THREAD

**Issue by qlurkin** [brython-dev/brython#916]
Hello,
I try to overwrite the open function when using `exec()` by defining global/local dictionaries but a ran into weird behaviors.

With this example:
```
ns = {"open": print}
exec('open("hello")', ns)
```
The overwrite is ignored

With this one:
```
ns = {"open": print}
lo = {}
exec('open("hello")', ns, lo)
```
The overwrite works but if there is an error in the source string:
```
ns = {"open": print}
lo = {}
exec('open("hello"', ns, lo)
```
The exception report is broken:
```
no src for <string>
File "<string>", line 1
    0
    ^
SyntaxError: Unbalanced bracket (
```

My final goal is to make a small python IDE into the browser that let you create/open/read files in an "in memory virtual file system". The correct report of exceptions is therfore important.

Thank you,

**Comment by PierreQuentel** [comment]
Thanks for the report. The commit referenced above fixes the first bug, but not the wrong error message, so I keep the issue open.

**Comment by PierreQuentel** [comment]
With the second commit the error message should be ok.

**Comment by qlurkin** [comment]
Thanks you
