### ISSUE TITLE
pickle time obj err in  implementation [3, 6, 2, 'final', 0]

### ISSUE THREAD

**Issue by QGB** [brython-dev/brython#920]
Uncaught Error
    at Object._b_.AttributeError.$factory (eval at $make_exc (brython.js:6773), <anonymous>:34:413)

import time
print(time.localtime()  )
import pickle
print(pickle.dumps(time.localtime() ) )

**Comment by QGB** [comment]
sb=b'\x80\x03ctime\nstruct_time\nq\x00(M\xe2\x07K\tK\rK\x10K\x17K7K\x03M\x00\x01K\x00tq\x01}q\x02(X\x07\x00\x00\x00tm_zoneq\x03X\x1e\x00\x00\x00?D1\xc2\xa8\xc2\xb2\xc2\xa1\xc3\x80\xc2\xa8\xc2\xba\xc2\xa1\xc3\x81?\xc2\xa8\xc2\xba\xc2\xa1\xc3\x80??q\x04X\t\x00\x00\x00tm_gmtoffq\x05M\x80pu\x86q\x06Rq\x07.'
import pickle
print(pickle.loads(sb))#  same Error

**Comment by PierreQuentel** [comment]
Thanks for the report. There were bugs in various places... The examples you give should work now, but I haven't made tests of the pickle module with other kinds of objects ; if you find other ones feel free to reopen this issue or to create another one.
