### ISSUE TITLE
Bug  in the overloading of comparison operators on a right position

### ISSUE THREAD

**Issue by fmaurel** [brython-dev/brython#925]
First, thank you and congrats for Brython. It is an amazing tool.

There is a bug in the overloading of comparison operators on a right position.

The following code should show 2 and the 1 (it does that in python3).
In Brython 3.7, it shows 1 and 1.

```
class A():
    def __lt__(self, other): return 1
    def __gt__(self, other): return 2
alert(1<A())
alert(A()<1)
```

It is problematic because it simply reverse the comparison.

1 < A() should default to A() > 1 (since 1 doesn't know how to compare with A()), hence 2.
In Brython, it currently defaults to A() < 1 which is clearly wrong.

**Comment by fmaurel** [comment]
I found a workaround:

add a check that `typeof x!="number"` in the rich_comp implementation

```
if(**typeof x!="number"){
   res=$B.$call(_b_.getattr(x,op))(y)
   if(res!==_b_.NotImplemented){return res}
}
```

I'm not convinced it's perfect.
We could probably also check `x.__class__===undefined` as it is done nearby.

**Comment by fmaurel** [comment]
Thank you for fixing this.

**Comment by PierreQuentel** [comment]
Thanks for the report @fmaurel !

I think returning `NotImplemented` is the correct way of handling this. In CPython:
```
>>> x = 1
>>> x.__lt__('a')
NotImplemented
```

**Comment by fmaurel** [comment]
I agree that this seems quite sensible.

Thanks again!
