### ISSUE TITLE
Possibility to disable Indexed DB usage?

### ISSUE THREAD

**Issue by MarkusBordihn** [brython-dev/brython#927]
First of all thanks a lot for all of the work on Brython and the ongoing development.

I currently working on an web-app which has no real context (data-url) to access the Indexed Database.
So I wonder if it would be possible to disable the Indexed DB usage even it it would cause performance issues or any other side effects.

Seems `__BRYTHON__.has_indexedDB = false;` do the trick, but want to check if there is maybe an better way for this.

**Comment by PierreQuentel** [comment]
Thanks @MarkusBordihn for the suggestion. The use cases should be rare, but in the commit referenced above I have added and documented an option `indexedDB` to pass to the function `brython()` to disable the use of the indexedDB database : 
```xml
<body onload="brython({indexedDB: false})">
```
