### ISSUE TITLE
Potential interaction with sqrt and complex arithmetic

### ISSUE THREAD

**Issue by tiggerntatie** [brython-dev/brython#928]
Running with latest code from Sept 25, 2018:
```
from math import sqrt
print(sqrt(1)+1j)
```
Produces the following (on runpython.org):
```
    traceback.print_exc()
  module traceback line 159, in print_exc
    print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
AttributeError: 'object has no attribute traceback'
```
Replacing sqrt(1) with simply 1 works correctly. This is not reproducible on the Brython web site (which is rc1?) at the moment.

**Comment by PierreQuentel** [comment]
@tiggerntatie 
Sorry, I can't reproduce the bug, the code gives the correct result, both in the console or inside a <script> tag. I use the version after commit 0e54151552ffbd6a28b3853a0dfb65f1a9d3e40c.

**Comment by tiggerntatie** [comment]
This is what I was afraid of (hence "potential"). There is some new interaction with runpython.org that I need to sort out. Thank you!

**Comment by tiggerntatie** [comment]
For what its worth, my example was not very good. My problem occurs with any inclusion of floating point real values in a complex number: print(1.0 + 1j)

I will close this in any case and continue to investigate.

**Comment by tiggerntatie** [comment]
In HTML I was using a single <script> to import brython.js. I switched to the style used in the brython.info console and editor pages (with multiple <script> tags importing many different .js files) and this problem disappeared. 

Is the use of a single brython.js import deprecated in this release?

**Comment by PierreQuentel** [comment]
No, loading __brython.js__ should always be the same as loading the individual scripts.

The only exception is when a bug fix or a new feature requires unrelated changes in several individual scripts ; in this case there are several commits, each one with a different message to remember the change, and I update the generated scripts such as __brython.js__ in a final commit. In this case, if you clone the repository just before the generated scripts are updated, there is a difference ; but this should be exceptional, and on Sept. 25 there were no such commits, so I still don't understand what went wrong.
