### ISSUE TITLE
== not working as per CPython 

### ISSUE THREAD

**Issue by brreith** [brython-dev/brython#936]
New here, and Brython is immensely impressive (thank you!!!), but the == behaviour caught me by surprise, ie.

>>> x = 1
>>> x == 1
True
>>> x == "1"
False
>>> 1 == "1"

TypeError: unorderable types: str() < int()
Traceback (most recent call last):
  module __main__ line 114, in myKeyPress
    _ = editor_ns['_'] = eval(currentLine, editor_ns)
  module <module> line 1
    1 == "1"
>>>

Is this intentional, or a bug?

Many thanks again

**Comment by PierreQuentel** [comment]
Thanks @brreith - this must be one of the most embarrassing Brython bugs ever...
