### ISSUE TITLE
Transpile Py to JS without running the code

### ISSUE THREAD

**Issue by outkine** [brython-dev/brython#937]
Is there a function in this library that can be called to transpile, but not run, some python code?  The docs mention [how the compiler works behind the scenes](https://brython.info/static_doc/en/modele.html), but I haven't been able to figure out how to replicate that process in order to avoid the `eval` called by `brython`.

Sorry if this is a silly question.

**Comment by PierreQuentel** [comment]
Hi @outkine 

Did you try function `py2js` in module `javascript` ?

```python
from browser import window
import javascript

js = javascript.py2js("""for i in range(5):
    print(i)""")

window.eval(js)
```

**Comment by outkine** [comment]
I was hoping for a way to do it from within JavaScript (my use case is
transpiling python to js inside of Vue).

**Comment by PierreQuentel** [comment]
Sorry, I misunderstood your request.

In the commit referenced above I have added a function `__BRYTHON__.run_from_js(python_source[, script_id])`, meant to execute Python from a Javascript program. `script_id` is the identifier of the Python program, defaulting to `"__main__"`.

If it's what you expect, can you try it with a few examples ? If it's ok I will document it.

**Comment by outkine** [comment]
Better yet, `run_from_js` could accept a function that transforms the js code right before it is run (accepts a code string and returns one). That way the developer has the option to add any js they want before the string is `eval`ed, but Brython can still perform any cleanup that it needs to.

**Comment by PierreQuentel** [comment]
Maybe it's my question that is silly, but when would you want to execute js code _inside_ the function call, instead of before or after ?

**Comment by outkine** [comment]
That works perfectly. Thank you so much!
