### ISSUE TITLE
Get Python source location of runtime error

### ISSUE THREAD

**Issue by outkine** [brython-dev/brython#938]
Getting information about where a runtime error happened in the original source is currently impossible. For example, the following code:

`x += 1`

Produces the following error:
```javascript
{
  $line_info: undefined,
  $py_error: true,
  $stack: [["__main__", {$line_info: undefined}, "__main__", {...}]],
  args: ["name 'x' is not defined", __brython__: true, __class__: {...}],
  ...
}
```

The `lineno` and `colno` are the location of the error as it occurred in the [generated JS](https://pastebin.com/Pk57ETup). Is there any way to extract the original source?

I've found that this is not a problem for syntax errors, only runtime errors.

**Comment by pkemarco** [comment]
Hi. Have you defined x ?

-----Message d'origine-----
De : "Anton" <notifications@github.com>
Envoyé : ‎08/‎10/‎2018 16:40
À : "brython-dev/brython" <brython@noreply.github.com>
Cc : "Subscribed" <subscribed@noreply.github.com>
Objet : [brython-dev/brython] Get Python source location of runtime error(#938)

Getting information about where a runtime error happened in the original source is currently impossible. For example, the following code:
x += 1
Produces the following error:
{
  $line_info: undefined,
  $py_error: true,
  $stack: [["__main__", {$line_info: undefined}, "__main__", {...}]],
  args: ["name 'x' is not defined", __brython__: true, __class__: {...}],
  ...
}The lineno and colno are the location of the error as it occurred in the generated JS. Is there any way to extract the original source?
I've found that this is not a problem for syntax errors, only runtime errors.

**Comment by outkine** [comment]
No, but I used that purposefully incorrect code to demonstrate that there
is currently no way to find out where the error is occurring.

**Comment by PierreQuentel** [comment]
@outkine 
Are you using the latest development version ? With the one after commit 6dbf1e30eb45887283f30623ae9a9bdfcfa570fc I get the correct error message.

**Comment by PierreQuentel** [comment]
I close the issue for the moment. If you think the bug is not fixed, please reopen it.
