### ISSUE TITLE
Bad error messages when using the result of += value

### ISSUE THREAD

**Issue by schmave** [brython-dev/brython#940]
```python
x = 10
y = x += 3
```
When I run this in the console at brython.info, I get an error message "SyntaxError: Unexpected token ;". In CPython 3.6.5, I get a clearer syntax error: 
```
>>> y = x += 3
  File "<stdin>", line 1
    y = x += 3
           ^
SyntaxError: invalid syntax
```

```python
class A(): pass
a = A()
x = 10
a.foo = x += 3
```
When I run this second snippet in the console, I get the error message "TypeError: can't set attributes of built-in/extension type 'object'". CPython gives this:

```
>>> a.foo = x += 3
  File "<stdin>", line 1
    a.foo = x += 3
               ^
SyntaxError: invalid syntax
```

Thanks for taking a look!

**Comment by PierreQuentel** [comment]
Thanks Evan ! This issue is fixed, as well as the reverse

```python
x += y = 3
```

But it is a quick fix, I am sure there are other similar issues when assignments and augmented assignments are mixed.

**Comment by schmave** [comment]
Thanks, Pierre. A quick fix is much better than nothing!
