### ISSUE TITLE
Wrong behavior for class.__getattr__

### ISSUE THREAD

**Issue by schmave** [brython-dev/brython#949]
```python
class A(object):
    def __getattr__(self, name):
        return 'A-%s' % name
        
print(A.foo)
```
In Brython, this prints "A-foo" to the console, but CPython gives the following error:
```
AttributeError: type object 'A' has no attribute 'foo'
```

It seems that a class's `__getattr__` should only be called with instances of that class, not the class object itself.

**Comment by schmave** [comment]
Nice. I did not know about Python metaclasses before today--that definitely makes this tricky!

**Comment by PierreQuentel** [comment]
I didn't know anything about metaclasses myself before implementing them for Brython...
