### ISSUE TITLE
Possible bug in dictionary imported from javascript.

### ISSUE THREAD

**Issue by elenzil** [brython-dev/brython#950]
it seems like there may be a bug around converting javascript dictionaries which contain sub-dictionaries.

i've put a small repro here: https://gist.github.com/elenzil/d3ca288078574c0c16550c84b3dd53b8#file-brython_dict-html

basically, converting the following dictionary and then doing a dumps() on it errors out on the key 'subkey' inside the sub-dictionary:
{ "subdict":{"subkey":2 } }

(slightly more context [here in google groups](https://groups.google.com/forum/#!msg/brython/oe0weSMIpBo/2dVfYbenBQAJ))

**Comment by PierreQuentel** [comment]
Thanks for the report. This was fixed in commit 572333ebbab89d6c0f0b30dd0f962ff8ac98e6ce.
