### ISSUE TITLE
Template .render() function not working in Edge and IE11

### ISSUE THREAD

**Issue by ariroffe** [brython-dev/brython#964]
```
<html>
<head>
<script type="text/javascript" src="brython.js"></script>
<script type="text/javascript" src="brython_stdlib.js"></script>
</head>
<body onload="brython(1)">

<div id="foo" b-include="foo.html"></div>

<script type="text/python" id="nav">
    from browser import document
    from browser.template import Template
    Template("foo").render()
</script>

</body>
</html>
```

foo.html contains:

```
Foo
<br>
Bar
```

Works fine in Firefox and Chrome, but in Edge and IE11 results in:

`RuntimeError: TypeError: Object doesn't support property or method 'forEach'`

Polyfills (e.g. [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach?fbclid=IwAR26qME2sz25g3zxyidyTn56599-jEOBU5hRus3LmQqzGXSsYtuMuGNGe-Y#Polyfill)) don't seem to work to resolve the issue.

**Comment by PierreQuentel** [comment]
Thanks for reporting this issue. It seems that on Firefox and Chrome, [NamedNodeMap](https://developer.mozilla.org/en-US/docs/Web/API/NamedNodeMap) instances support `.forEach()`, which is not in the standard.
