### ISSUE TITLE
Some syntax errors cannot be printed with traceback module

### ISSUE THREAD

**Issue by schmave** [brython-dev/brython#965]
This code works as I would expect (a SyntaxError is raised and printed):

```python
import traceback

try:
    exec('x /// 0')
except:
    traceback.print_exc()
```

But this fails and prints errors to the JS console:

```python
import traceback

try:
    exec('if: x = 2')
except:
    traceback.print_exc()
```

**Comment by PierreQuentel** [comment]
The bug was in fact that 
```python
if: x = 2
```
didn't raise a `SyntaxError`...

**Comment by schmave** [comment]
@PierreQuentel Ah gotcha. Thanks for the fix!
