### ISSUE TITLE
possible bug in condition evaluation

### ISSUE THREAD

**Issue by samgratte** [brython-dev/brython#967]
Hi,

I encounter a fairly simple scenario where the condition evaluation is not what it should be:

    In CPython 3.6:
    In [1]: True == 'Toggle'                                                                     
    Out[1]: False

    In Brython 3.7.0:
    >>> True == 'Toggle'
    True

best regards

Samuel

**Comment by PierreQuentel** [comment]
Merci Samuel !

**Comment by samgratte** [comment]
Merci à vous pour Brython et votre réactivité !

Le jeu. 8 nov. 2018 à 16:37, Pierre Quentel <notifications@github.com> a
écrit :
