### ISSUE TITLE
Handling for native JS exceptions is confusing

### ISSUE THREAD

**Issue by schmave** [brython-dev/brython#968]
I think that prior to 3.7.0, Brython's handling of native JS exceptions was a bit better than it is right now. Here's an excerpt of an HTML file:

```html
<script type="text/javascript">
function makeTestError() {
    let x;
    return x.width;
}
</script>

<script type="text/python3">
from javascript import JSObject
from browser import window
import traceback


def f():
    window.makeTestError()

# Test 1
try:
    f()
except:
    traceback.print_exc()

# Test 2
try:
    exec("f()")
except:
    traceback.print_exc()

</script>
```

Both "Test 1" and "Test 2" cause errors in the traceback module, or perhaps internal Brython errors--it's hard to tell. For "Test 2", the original JS exception is printed to the JS console, so it is easy to see what happened if you are looking, but for "Test 1", the original exception (In this case, something like `TypeError: Cannot read property 'width' of undefined`) is never shown.

**Comment by PierreQuentel** [comment]
@schmave 
Thanks for the report. The commit above should give better results. 

I wish there was a cross-browser Javascript API for exceptions that would provide the script name, line number, etc. In this version, the raw Javascript exception is printed in the console; the information is available, but in different formats for Firefox, Chrome and Edge...

**Comment by schmave** [comment]
That's a huge improvement. Thanks, @PierreQuentel.
