### ISSUE TITLE
Strange bug with comments causing bracket matching error

### ISSUE THREAD

**Issue by BrenBarn** [brython-dev/brython#971]
On the Brython I have installed via pip, this code causes an "unbalanced bracket" error:

```
x = [k for k in [
	1, # this comment is ok
	2 # removing this one fixes it
]]
```

This seems similar to bugs #658 and #776, but those were apparently fixed more than a year ago.  I don't see the behavior in the console at brython.info.  Is that because that's running a newer version of Brython?  Does that mean the next release will fix this?

**Comment by PierreQuentel** [comment]
@BrenBarn 
This code works correctly with the current development version. I tested the latest release on PyPI (3.7.0rc1; I didn't upload rc2 but it's the same as on brython.info) and it raises a `SyntaxError`, so I guess the bug was fixed inbetween, I don't know when.
