### ISSUE TITLE
slicing implemtation in syntax parser causes issues with subclassing

### ISSUE THREAD

**Issue by jmetz** [brython-dev/brython#975]
I've been playing around with subclassing in brython, and a very trivial example I wanted to get working was the possibility of multi-dimensional slicing (which would be required for a numpy type interface). 

What I found is that before this even gets sent to the list object's __getitem__ method, the syntax parser throws an error, for example: 

Normal python: 

```py
    l = [1,2,3]
    l[:,:]
```

throws the error 

    TypeError: list indices must be integers or slices, not tuple

while in Brython this causes a SyntaxError:

      File <stdin>, line 1
        l[:,:]
           ^
    SyntaxError: invalid syntax

Presumably this is because the syntax parser has been written to expect a single slice, while normal Python will happily take in the multiple slices as a tuple but then `list`'s `__getitem__` complains. 

Obviously having this be a syntax error would mean a multiple slice (for e.g. multi-dimensional slicing) would never be possible!

I also tried the same with a custom class - it still never gets to __getitem__ as the SyntaxError stops the process.

**Comment by PierreQuentel** [comment]
Thanks @jmetz for the report !
