### ISSUE TITLE
Providing custom dialog support for "input"

### ISSUE THREAD

**Issue by MarkusBordihn** [brython-dev/brython#978]
Brython currently use the browser window.prompt dialog for any input command.
But window.prompt is not working in all scenarios like sandboxes, webview and restricted views.

It would be great to provide the possibility to overwrite this with some custom prompt dialog.
Similar to the Skulpt "inputFun" options like:
```
Sk.configure({
    inputfun: yourFunction,`
   ...
});
```

**Comment by PierreQuentel** [comment]
This is something that has been asked and discussed many times. Unfortunately there doesn't seem to be a solution : `input()` must be a _blocking_ function, and opening a popup element won't block the script execution.

For instance if you have code like :
```python
while True:
    x = input()
    if x == "a":
        break
```
if `input()` doesn't block execution, the next line (`if x == "a"`) will be executed immediately, which is not expected.

I don't know if Skulpt has a solution for the code above with something else than the browser prompt. I know they have this concept of "suspensions" but never understood what it is, and if it could be implemented in Brython without changing the whole implementation.

**Comment by MarkusBordihn** [comment]
Technical they are using an Promise and an kind of stack queue to pause the execution.
I don't know the technical internal structure, but maybe something like async and await could be work in this case.
But I agree that it's hard to adding something like this if there is currently no way to pause the execution.

**Comment by PierreQuentel** [comment]
I am closing the issue since I don't think it's possible to fix it in the current state of Brython.
