### ISSUE TITLE
Create documentation about Brython development

### ISSUE THREAD

**Issue by PierreQuentel** [brython-dev/brython#980]
As suggested on Twitter by Benjamin Rigaud : "Hello Pierre, j'aimerais commencer à triturer / comprendre les entrailles de Brython et éventuellement faire des modifications : est-ce qu'il y a une doc pour les devs sur comment modifier Brython et le recompiler ? J'ai essayé plusieurs choses hier sans succès."

**Comment by frederickavita** [comment]
moi aussi je serais preneur car pas évidant à tout comprendre derrière brython

**Comment by goffi-contrib** [comment]
*as this thread is in French, I'm writing in French, but can switch to English on request*

@PierreQuentel j'ai le même problème, je dois fouiller pour savoir quels scripts lancer pour tester mes modifs en local pour Brython. Une page de wiki serait un bon début déjà.
Il y a aussi des petites choses gênantes, par exemple `scripts/make_dist.py` doit être lancé depuis `scripts` (j'ai dû comprendre ça après avoir essayé `python scripts/make_dist.py`.

Bref à mon avis il faudrait à minima une page wiki (ou de la doc qui apparaisse sur le site Brython) avec:

- comment compiler Brython après avoir fait une modif
- indiquer s'il est possible de faire des modifs en temps réél (par exemple je modifie `aio.py`, j'aimerais pouvoir tester tout de suite ma modif sans avoir à lancer des scripts, réinstaller brython, etc).
- indiquer comment lancer les tests

Petite remarque au passage: est-ce qu'il existe un salon de messagerie instantanée avec une communauté active en temps réél ? Je me souviens qu'il y avait un salon IRC à une époque, c'est toujours le cas ? Si non, je peux aider à créer un salon XMPP (je suis développeur XMPP), avec un accès facile par le web sans besoin de créer un compte.

**Comment by PierreQuentel** [comment]
@goffi-contrib 
Tu as bien fait de relancer cette discussion !
Je viens de publier une [première version](https://github.com/brython-dev/brython/wiki/Brython-development) sur le wiki. Si tu as un moment pour jeter un coup d'oeil, ton avis m'intéresse !

**Comment by goffi-contrib** [comment]
@PierreQuentel c'est un bon début, merci ! Au moins on sait où commencer avec ça, et ça va sûrement être amélioré avec le temps et les contributions.

**Comment by PierreQuentel** [comment]
After adding content to the [wiki page](https://github.com/brython-dev/brython/wiki/Brython-development), I close this issue.
