### ISSUE TITLE
Traceback is truncated

### ISSUE THREAD

**Issue by BrenBarn** [brython-dev/brython#981]
When code within an imported module raises an exception, the traceback seems to show only the portion of the call stack which is in the main module.  As an example, with this HTML file:

```
<!doctype html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="description" content="Blah">
		
		<title>Blah</title>
		
		<script src="brython/brython.js"></script>
	</head>
	
	<body onload="brython(1)">
		<script type="text/python">
from perftest import bar
def foo():
	bar()


foo()

		</script>
	</body>
</html>
```

And this perftest.py:

```
def bar():
	baz()

def baz():
	1/0
```

The traceback only shows this:

```
Traceback (most recent call last):
  module __main__ line 6
    foo()
  module __main__ line 3, in foo
    	bar()
ZeroDivisionError: division by zero
```

The exception was raised within `baz`, but neither `bar` nor `baz` appear in the traceback.

**Comment by PierreQuentel** [comment]
Thanks for the very clear report :-)
