### ISSUE TITLE
"pas de src" in 3.7.0rc2

### ISSUE THREAD

**Issue by tiggerntatie** [brython-dev/brython#983]
I am trying out rc2 and am running into sporadic cases where "pas de src" appears in the console. This appears to be associated with an import line (importing one of my modules, not a standard one). The program will not run in this case, also producing a "js exc" in the console. Noticing that the string "pas de src" is absent in the latest sources I have tried grabbing the tip revision as well, but the program continues to show sporadic failure to execute, although without the error message.

For example, I can have identical program in two browser tabs. One produces the error and one does not!

I am wondering what might be causing this "pas de src" error to occur, so that I can figure out what I am doing (or not doing) to make it happen. Thank you for your help!!

**Comment by PierreQuentel** [comment]
It was a debug trace (in French !) that was removed a few days ago in commit 7155e817206148e3c11719fd17bfddcce7d36069. It is still in the rc2 release but will not appear in the next one.
