### ISSUE TITLE
Error in global name resolution

### ISSUE THREAD

**Issue by schmave** [brython-dev/brython#985]
```python
def f():
    global x
    print(x)

def g():
    global x
    x = 1

f()
```

This should raise a `NameError` on the line containing `print(x)`, but instead it prints "&lt;undefined>" to the console.

**Comment by PierreQuentel** [comment]
Thanks Evan !
Just out of curiosity, how do you detect this kind of bugs ?

**Comment by PierreQuentel** [comment]
Wow, 1000 students a week using Brython ! I wasn't aware of this at all, and I appreciate very much that you mention it on the page. Unless you have objections, I will mention this use in future messages about Brython.

**Comment by schmave** [comment]
Yes, you are welcome to mention it!
