### ISSUE TITLE
CPython __dict__ test regression

### ISSUE THREAD

**Issue by schmave** [brython-dev/brython#988]
This is probably already be on your radar, @PierreQuentel, but in case not, your commit ce4d844131a0a57a16a54b5174f32542329ac542 caused a test from Lib/test/test_dict.py to start failing. Here it is, in a simplified version that doesn't require loading unittest:

```python
class Foo:
    def __init__(self, msg):
        self.msg = msg
f = Foo('123')
class _str(str):
    pass
assert f.msg == getattr(f, _str('msg'))
assert f.msg == f.__dict__[_str('msg')]
```

**Comment by PierreQuentel** [comment]
Thanks for the report. I use the CPython test suite from time to time to detect bugs, and test_dict.py is one of the rare scripts that passes without error...

**Comment by PierreQuentel** [comment]
Ok, so all those "ok" on my unittest runs were a false joy :-(

I will remove the @skip on my repo to see if I can fix some bugs, I do this regularly when there are not too many reports in the issue tracker.

**Comment by schmave** [comment]
Excellent!
