### ISSUE TITLE
the event input bug with module template  

### ISSUE THREAD

**Issue by frederickavita** [brython-dev/brython#991]
the event input bug  when : 
home.html
`<input` id="titre_tache"  placeholder="titre" type="text" b-on="keyup:create_project" 
index.py
def create_project(ev, element):
    element.data.name_projet =  document['titre_tache'].value
  
brython version 3.6.2.
impossible to type in the field

**Comment by PierreQuentel** [comment]
Salut,

Le problème c'est que si `element.data` est modifié dans la fonction, _le template est redessiné_ (c'est voulu, pas un bug), donc le champ `<input>` est de nouveau vide.

Je ne pense pas que capturer chaque caractère avec un "keyup" soit la meilleure solution, il vaudrait mieux laisser saisir le titre dans la zone `<input>` et capturer soit l'événement "blur" sur cette zone (quand l'utilisateur clique en-dehors), soit un clic sur un bouton "Valider" à côté, ou encore capturer "keyup", mais ne rien faire sauf si la clé est le retour chariot.

**Comment by frederickavita** [comment]
merci de ses reponses et precisions. A titre personnelle je prefere utilise le module html je trouve que que c'est plus souple.
