### ISSUE TITLE
import zipfile fails with TypeError: unorderable types: 'str' <= int()

### ISSUE THREAD

**Issue by vanous** [brython-dev/brython#996]
I just try to import zipfile from the stdlib but am probably unlucky...  

TypeError: unorderable types: 'str' <= int()

am i doing something wrong?

thank you

have tried 3.6.2, 3.7.0.rc.2 but same results as below. Minimal example:

files in my folder:

brython.js 
brython_stdlib.js  
demo2.html  

demo2.html:

<html>
<head>
<meta charset="utf-8">
<title>Brython demo</title>
<style>
</style>
</head>
<body onload="brython(1)">
<script src="brython.js"></script>
<script src="brython_stdlib.js"></script>
    <script type="text/python"  id="script10">
    import zipfile
    </script>
</body>
</html>

result:

GEThttp://localhost:8000/demo2.html
[HTTP/1.0 200 OK 1ms]
GEThttp://localhost:8000/brython.js
[HTTP/1.0 200 OK 5ms]
GEThttp://localhost:8000/brython_stdlib.js
[HTTP/1.0 200 OK 114ms]
GEThttp://localhost:8000/favicon.ico
[HTTP/1.0 404 File not found 1ms]
using indexedDB for stdlib modules cache brython.js:formatted:23218
run Python code from VFS _io brython.js:formatted:31417
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/ brython.js:formatted:31136
XHRGEThttp://localhost:8000/grp.py?v=1544524681965
[HTTP/1.0 404 File not found 1ms]
Error 404 means that Python module grp was not found at url http://localhost:8000/grp.py brython.js:formatted:31158
XHRGEThttp://localhost:8000/grp/__init__.py?v=1544524682139
[HTTP/1.0 404 File not found 7ms]
Error 404 means that Python module grp was not found at url http://localhost:8000/grp/__init__.py brython.js:formatted:31158
XHRGEThttp://localhost:8000/Lib/site-packages/grp.py?v=1544524682163
[HTTP/1.0 404 File not found 2ms]
Error 404 means that Python module grp was not found at url http://localhost:8000/Lib/site-packages/grp.py brython.js:formatted:31158
XHRGEThttp://localhost:8000/Lib/site-packages/grp/__init__.py?v=1544524682182
[HTTP/1.0 404 File not found 1ms]
Error 404 means that Python module grp was not found at url http://localhost:8000/Lib/site-packages/grp/__init__.py brython.js:formatted:31158
XHRGEThttp://localhost:8000/libs/grp.js
[HTTP/1.0 404 File not found 1ms]
XHRGEThttp://localhost:8000/Lib/grp.py
[HTTP/1.0 404 File not found 1ms]
XHRGEThttp://localhost:8000/Lib/grp/__init__.py
[HTTP/1.0 404 File not found 1ms]
var $B = __BRYTHON__;
eval(__BRYTHON__.InjectBuiltins());

var $locals_zipfile = $B.imported["zipfile"] || {}, $locals = $locals_zipfile;
$locals_zipfile["__doc__"] = '';
$locals_zipfile["__name__"] = $locals_zipfile["__name__"] || "zipfile";
$locals_zipfile["__package__"] = $locals_zipfile["__package__"]
$locals_zipfile["__file__"] = "undefined";None;

var $top_frame = ["zipfile", $locals_zipfile, "zipfile", $locals_zipfile, "a"]; $B.frames_stack.push($top_frame); var $stack_length = $B.frames_stack.length;
try{
    ;$locals.$line_info = "1,zipfile";
    '';
    ;$locals.$line_info = "6,zipfile";
    $B.$import("io", [],{},$locals_zipfile, true);None;;
    ;$locals.$line_info = "7,zipfile";
    $B.$import("os", [],{},$locals_zipfile, true);None;;
    ;$locals.$line_info = "8,zipfile";
    $B.$import("re", [],{},$locals_zipfile, true);None;;
    ;$locals.$line_info = "9,zipfile";
    $B.$import("imp", [],{},$locals_zipfile, true);None;;
    ;$locals.$line_info = "10,zipfile";
    $B.$i…
brython.js:formatted:31394
Error: ""
	factory http://localhost:8000/brython.js line 6771 > eval:166:371
	__le__ http://localhost:8000/brython.js line 9910 > eval:1:70
	method http://localhost:8000/brython.js:6044:37
	rich_comp http://localhost:8000/brython.js:5695:5
	getNum3989 http://localhost:8000/brython.js line 7600 > eval:1263:84
	calcsize3991 http://localhost:8000/brython.js line 7600 > eval:1354:55
	<anonymous> http://localhost:8000/brython.js line 7600 > eval:126:41
	exec_module http://localhost:8000/brython.js:7600:5
	cl_method http://localhost:8000/brython.js:5046:33
	import_hooks http://localhost:8000/brython.js:12016:5
	__import__ http://localhost:8000/brython.js:7764:75
	import http://localhost:8000/brython.js:7796:43
	<anonymous> http://localhost:8000/brython.js line 4631 > eval:13:5
	loop http://localhost:8000/brython.js:4631:1
	idb_load http://localhost:8000/brython.js:4580:1
	onsuccess http://localhost:8000/brython.js:4590:29
brython.js:formatted:31395
args 
Array [ "unorderable types: 'str' <= int()" ]
brython.js:formatted:31397
__class__ 
Object { __class__: {…}, __name__: "TypeError", __bases__: (1) […], __module__: "builtins", __mro__: (3) […], "$factory": factory()
, "$is_class": true }
brython.js:formatted:31397
$py_error true brython.js:formatted:31397
$stack 
Array(4) [ (5) […], (5) […], (5) […], (5) […] ]
brython.js:formatted:31397
$line_info 283,_struct brython.js:formatted:31397
Array(70) [ "_importlib", "browser.html", "browser", "javascript", "_sys", "zipfile", "io", "builtins", "undefined", "os", … ]
brython.js:formatted:31399
Traceback (most recent call last):
  module script10 line 1
    import zipfile
TypeError: unorderable types: 'str' <= int()

**Comment by PierreQuentel** [comment]
Sorry, I can't reproduce the bug. `import zipfile` works on the version at [brython.info](https://brython.info) (console or editor), with Firefox, Edge and Chrome. Can you give more context ?

**Comment by andy31lewis** [comment]
Your `demo2.html` file seems to be incomplete as it never calls `brython()`, so `script10` isn't executed.  But if I add: `<body onLoad="brython()"></body>` to the end of `demo2.html`, and place it in a folder with just `brython.js` and `brython_stdlib.js` (no other files), the import works fine for me. Sorry, that is probably not much help to you!

**Comment by vanous** [comment]
OK, it works, but don't ask me how...

When i copied the minimal example to this issue, i accidentally removed the <body> tag with brython(), but that wasn't the issue.

But, after some long elaborating, i am not sure what was the issue. I was now 99% positive after some tests that it was uBlock Origin, but then, after several other tests, suddenly it works no matter what. Probably combination of caching and ,,, bad luck :)

Tested on latest Firefox, Chrome and Chromium running on Debian buster/sid (64-bit)

Thank you all for helping anyways and sorry for the noise. Perhaps this helps to someone else.
