### ISSUE TITLE
template event hashchange 

### ISSUE THREAD

**Issue by frederickavita** [brython-dev/brython#997]
est-ce que tu peux verifier ce point la template ne reconnait pas cette d'événement 

example:

python
def test(ev, element):
     if  window.onhashchange == "function":
          element.data.test = True

html

<div on-code="hashchange: test" ></div>

normalement  il se detecte comme ça : window.bind('hashchange', test)

**Comment by PierreQuentel** [comment]
Salut Frédéric,

"hashchange" est un événement qui porte sur l'objet `window` , alors que le template s'applique à une partie d'un `document`. On ne peut donc pas gérer cet événement par la syntaxe que tu proposais dans ton message sur le groupe:

```xml
<div on-code="hashchange: test" ></div>
```

puisque "hashchange" n'est pas un événement des éléments `<DIV>` (et d'ailleurs la syntaxe pour la gestion d'événement n'est pas correcte : c'est `on` et non `on-code`)

Par contre cet événement est gérable par la syntaxe habituelle, par exemple:

```python
from browser import window, bind

@bind(window, "hashchange")
def hashchange(ev):
    print(ev.newURL)
```

**Comment by frederickavita** [comment]
ok merci
