### ISSUE TITLE
caches desonot work😣😣😣

### ISSUE THREAD

**Issue by Mohamed-Kaizen** [brython-dev/brython#999]
When I  call window.caches.open("new caches") it creates  cache but doesn't store file 
I try  to store window.caches.open("new caches") inside variable   but it become  Promise object  
What I  am trying  to use brython to make pwa (progressive  Web app) 
In other word working with service worker

**Comment by PierreQuentel** [comment]
Sorry for the very late answer, I didn't know anything about the `caches` interface.

Instance of `Promise` have the same methods `then()` and `catch()` as in Javascript, so you can use them with code like: 
```python
from browser import window

url = "http://api.open-notify.org/iss-now.json"

def ok(ev):
    print("stored")

def err(ev):
    print("error", ev)

def populate(cache):
    cache.add(url).then(ok).catch(err)

window.caches.open("test").then(populate)
```

**Comment by PierreQuentel** [comment]
I close the issue, don't hesitate to re-open it if you think that something is still wrong.
